### ISSUE TITLE
youtube.com##.ytp-cards-teaser

### ISSUE THREAD

**Issue by aravindvnair99** [AdguardTeam/AdguardFilters#77420]
Blocking this prevents the cards from loading. With it enabled:

![image](https://user-images.githubusercontent.com/22199259/111030578-0f4a8680-8429-11eb-8d8e-83e07eb7b6f1.png)

Found in:

![image](https://user-images.githubusercontent.com/22199259/111030592-22f5ed00-8429-11eb-9396-cb8f55cfd866.png)

**Comment by krystian3w** [comment]
Block exclude misclick / mistouching.

**Comment by Alex-302** [comment]
@aravindvnair99 please write how to reproduce it.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 please write how to reproduce it.

@Alex-302 Any YouTube video with cards works. Example: https://youtu.be/VPkzytYls48?t=1596

**Comment by krystian3w** [comment]
test these:

`#@#.ytp-ce-element`
(maybe hide by Fanboy's Annoyances and Polish Annoyance Filters).

```css
youtube.com#$#html:root body .ytp-ce-element { display: block !important; }
```

**Comment by Alex-302** [comment]
> Any YouTube video with cards works as a test case. Example: https://youtu.be/VPkzytYls48?t=1596
 
This is correct behavior.

**Comment by aravindvnair99** [comment]
> > Any YouTube video with cards works as a test case. Example: https://youtu.be/VPkzytYls48?t=1596
> 
> This is correct behavior. In some cases it is annoying.

@Alex-302 Could you give me an example where it's annoying? So far in my experience, I only found them useful and not annoying. No unnecessary pop-ups as such.

**Comment by aravindvnair99** [comment]
@Alex-302 As shown here, it looks odd when the cards are supposed to come and doesn't come: https://github.com/AdguardTeam/AdguardFilters/pull/77528#issue-592586833

**Comment by krystian3w** [comment]
First exclude hide this by:

`##.ytp-ce-element`

**Comment by aravindvnair99** [comment]
> First exclude hide this by:
> 
> `##.ytp-ce-element`

@krystian3w Unblocking that restores one of the cards and the channel logo:

![image](https://user-images.githubusercontent.com/22199259/111118902-68ccc580-858f-11eb-9a7e-e0e14af2f98e.png)

**Comment by aravindvnair99** [comment]
> First exclude hide this by:
> 
> `##.ytp-ce-element`

@krystian3w Unblocking that restores everything.

**Comment by aravindvnair99** [comment]
> > First exclude hide this by:
> > `##.ytp-ce-element`
> 
> @krystian3w Unblocking that restores everything.

@krystian3w Just for clarification... By everything I meant to say, it's back to normal. The cards become visible.

**Comment by krystian3w** [comment]
> ##.ytp-ce-element


Well, that leaves you to rethink whether AdGuard Annoyance still need this rule.

Supposedly, sometimes the creator can put something these links without such a board (embeded into video stream) and normally we have an obscured film for about 30 seconds. Additionally, did YouTube limit inserting those elements only at the end of the movie (if so, it is rather spamming random movies died).

**Comment by Alex-302** [comment]
AdGuard Annoyance is not enabled by default. Users can just exclude unnecesary rules.

**Comment by aravindvnair99** [comment]
> AdGuard Annoyance is not enabled by default. Users can just exclude unnecesary rules.

@Alex-302 Could you give me an example where it's annoying? So far in my experience, I only found them useful and not annoying. No unnecessary pop-ups as such.

In my opinion, it's a false positive. I have had many ask me why it's not coming and why they see a blank thing, but they want to keep using AdGuard Annoyance. Naturally, most will think it's 2 random boxes and a circle instead of figuring out what it is or why it's not coming.
