### ISSUE TITLE
https://club.m.autohome.com.cn/ - Banner

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7744]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32991734-fd9e6a08-cd49-11e7-9545-19c1cf39cd26.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.36.82 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.32 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.21.20 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.76 Enabled=YES
ID=101 Name="EasyList" Version=1.0.77.40 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.4.46 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 9.3.2
Operating system version (Android/iOS) | iPhone OS
Browser:                               | Safari
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1671881

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't access.

**Comment by AdamWr** [comment]
Fixed.
