### ISSUE TITLE
www.nba.com - Adblocker

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7750]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

When going to nba.com there is an Antiblock message.
BUT also, in Chrome the website freezes up in a minute, so we can't click on anything.
Though in Mozilla for example, this doesn't happen.

Also page would become unresponsive in Chrome (as on screenshot)

Use these links to check the website http://www.nba.com/scores#/
www.nba.com/#/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screen shot 2017-11-19 at 9 38 12 pm](https://user-images.githubusercontent.com/31481372/32995204-e5323d70-cd79-11e7-8e14-40102f60fdc7.png)

Here we couldn't click on anything after a minute in Chrome.

 Eventually it might unfreeze.

![screen shot 2017-11-19 at 9 21 30 pm](https://user-images.githubusercontent.com/31481372/32995231-3635ab9e-cd7a-11e7-82d9-feda5687f580.png)

![screen shot 2017-11-19 at 9 39 05 pm](https://user-images.githubusercontent.com/31481372/32995565-21d4b532-cd7f-11e7-833b-42cfffb49940.png)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**: 

FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
FilterId:5 Name: Experimental filter Url: https://filters.adtidy.org/extension/chromium/filters/5.txt
FilterId:16 Name: French filter Url: https://filters.adtidy.org/extension/chromium/filters/16.txt
FilterId:0 Name:  Url: no_url

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 
Browser:                               | Chrome
AdGuard version:                       | 6.2.433.2167
Stealth mode options (Windows only)    | enabled
Helpdesk ID (if exists):               | 1577721

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It works fine in my Chrome.
Removed few ad leftovers and fixed the player
```
nba.com##.block-globalheaderadblock
nba.com###scores-page-ad
nba.com###nba_tos
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=watch.nba.com
```

**Comment by Alex-302** [comment]
@AdamWr please check

**Comment by iverkhohliad** [comment]
Can the reason for the page freezing be in the website itself?

**Comment by Alex-302** [comment]
I don't know. Is it works fine without AdGuard?

**Comment by iverkhohliad** [comment]
Seemed to be okay.
The user also had his Windows reinstalled. And that's when he noticed the issue.

**Comment by AdamWr** [comment]
Antiadblock message fixed.
On my end this website freezes for a while, even without AdGuard.

**Comment by iverkhohliad** [comment]
Is there any way to fix this freezing?  Or is it just the website itself?
