### ISSUE TITLE
Faz - Anti Adblock

### ISSUE THREAD

**Issue by YoKoGFX** [AdguardTeam/AdguardFilters#7762]
The Website:
http://www.faz.net/aktuell/stil/drinnen-draussen/beton-liegt-im-trend-sechs-einrichtungstipps-in-grau-15003481.html

uses a Anti Adblock Script. Please Fix

**Comment by vitalkanev** [comment]
Filters? Version? Browser?

<details><summary>Screenshot (I managed to capture just now)</summary>

![2017-11-20 11-29-56](https://user-images.githubusercontent.com/18398761/33008993-5076463c-cde6-11e7-8cc1-a6956138dc83.png)

</details>

**Comment by YoKoGFX** [comment]
Yes, that is the Warning. I use the latest Filters on MacOS. 
Version: 1.5.0
Broser: Safari

**Comment by Alex-302** [comment]
@YoKoGFX please send report via this tool
https://reports.adguard.com/de/new_issue.html

**Comment by danidoedel** [comment]
Read this: https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/
