### ISSUE TITLE
timesnownews.com social placeholder

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdguardFilters#77638]
Social buttons placeholder in sidebar.
`https://www.timesnownews.com/sports/cricket/article/indias-remaining-t20is-against-england-to-be-played-behind-closed-doors-gca-to-refund-spectators/732828`

Proposed filters:
```
timesnownews.com##._newsocial
```

**Comment by Yuki2718** [comment]
We don't block follow buttons unless they're redundant.
@zloyden Please check.

**Comment by cantunborn** [comment]
Yeah I think for me the non-redundant buttons were blocked by fanboy's annoyance. I'll report it there, it doesn't seem to suit adguard social.

**Comment by zloyden** [comment]
> Social buttons placeholder in sidebar.

This element we can block because it has recommendations.
Also unblocked their social links.

@Yuki2718 only one exception. If they only had this element with social links on the website, we wouldn't be doing anything.

**Comment by Yuki2718** [comment]
@zloyden I think that unblock bit too much, `##.social-media-component` should still be blocked. I'll add this.
