### ISSUE TITLE
zhongzicili.me - missed ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#7764]
1. AdGuard for iOS and easylistchina enabled
and
adblock browser https://itunes.apple.com/us/app/adblock-browser/id1015653330?mt=8 with the same filter.
2. http://zhongzicili.me/
3. screenshots
with adg: https://imgur.com/a/He5iI
with adblock browser: https://imgur.com/a/LU0VQ

and two questions: why is the difference and can we block the banner?

**Comment by zebrum** [comment]
from here: https://github.com/AdguardTeam/AdguardForiOS/issues/511

**Comment by justforadblock** [comment]
*$third-party,domain=zhongzicili.me 
add to adguard custom list can clean the ads..
please close the issue

**Comment by Alex-302** [comment]
AdGuard for iOS has optimized filters, because rules limit in Safari - 50000 rules.
Added
```
||lygshgj.com^$third-party
||fate-xy.com^$third-party
||dsdsc.win^$third-party
```
