### ISSUE TITLE
[NSFW] zmovs.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7768]
**Site Sample** | 
----|
http://zmovs.com/video/orGbBBKR/?sid=12111

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.436.2170**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ad leftover

### Fix

```
zmovs.com##.player-aside-banners
```

<details><summary><b>Screenshot:</b></summary>

![20171120-145924-001](https://user-images.githubusercontent.com/9846948/33021828-752543bc-ce03-11e7-8be7-49bbf5d58aaa.png)

</details><br/>

**Comment by Alex-302** [comment]
Added
