### ISSUE TITLE
[NSFW] gotporn.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7769]
**Site Sample** | 
----|
https://www.gotporn.com/nicole-aniston-bath-time-with-nicole-aniston/video-7065718

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.436.2170**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ad box

### Fix

```
gotporn.com##.sponsored
```

<details><summary><b>Screenshot:</b></summary>

![20171120-150700-001](https://user-images.githubusercontent.com/9846948/33022152-7bb7adc2-ce04-11e7-98a9-ab74e4bc6327.png)

</details><br/>

**Comment by Alex-302** [comment]
Added
