### ISSUE TITLE
CleverPush button blocked on Bsdex.de

### ISSUE THREAD

**Issue by rugk** [AdguardTeam/AdguardFilters#77724]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![profileNoPushIcon](https://user-images.githubusercontent.com/11966684/111383995-47f89300-86a9-11eb-8569-4466fef505b7.png)
</details><br/>

* **Expected behaviour**: 

There is no bell allowing me to opt-in to notifications (and the banner for that is blocked too).

<details><summary>Screenshot:</summary>

![grafik](https://user-images.githubusercontent.com/11966684/111384389-bb9aa000-86a9-11eb-9820-7124076a47b1.png)

</details><br/>

***Steps to reproduce the problem***:
Go to (needs login): `https://app.bsdex.de`
If logged in there should be a bell at the top right.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Fedora
Operating system version (Android/iOS) | 33
Browser:                               | Firefox 86
AdGuard version:                       | N/A
Filters enabled:                       | ublock defaults + AdGuard Annoyances
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | N/A
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**see alos downstream report: https://github.com/uBlockOrigin/uAssets/issues/8727**

**Comment by krystian3w** [comment]
Bad is line:

https://github.com/AdguardTeam/AdguardFilters/blob/48235af321b8bcb89c95be1227c5e227297e216a/AnnoyancesFilter/sections/push-notifications.txt#L360

**Comment by Alex-302** [comment]
In general, this is correct behavior for AdGuard Annoyances
