### ISSUE TITLE
siasat.com [Ad Text Strings]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#77783]
https://www.siasat.com/frances-sarkozy-goes-back-on-trial-this-time-for-election-spending-2112472/

Please remove the ad text strings seen on the page. Checked with AG for Android on Chrome.

**Comment by Nzzyme** [comment]
https://www.siasat.com/google-blocked-99m-covid-related-fake-ads-in-2020-2112809/

I am also seeing ad text strings on Chrome running AG extension on Win 10. Can you check ?

**Comment by zloyden** [comment]
I've seen only one ad text string. Added a rule to the Base filter.
