### ISSUE TITLE
Add YousList to the list of known subscriptions

### ISSUE THREAD

**Issue by yous** [AdguardTeam/AdguardFilters#7784]
Hi, I'm an author of [YousList](https://github.com/yous/YousList), which is a Korean adblock filter. It's mainly for Korean websites, but I'm trying to make this work globally. The URL of the filter is <https://github.com/yous/YousList/raw/master/youslist.txt>.

This filter has 4,152 items and keeps on updating. It's compatible with Adblock Plus 2.0 rules, and added to [uBlock](https://github.com/gorhill/uBlock/pull/1029) and [Adblock Plus](https://adblockplus.org/subscriptions) filter list.

I couldn't find some guides for adding a filter to this project, so if I did something wrong, please let me know.

**Comment by ameshkov** [comment]
Hey! You did everything right, thank you! Adding a new filter to the list of available may take some time, but we will definitely do it.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #10](https://github.com/AdguardTeam/FiltersRegistry/issues/10) via [**ZenHub**](https://www.zenhub.com/)
