### ISSUE TITLE
www.zuvio.com.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#77849]
pls add ads and trackers from `xxx.zuvio.com.tw` to adguard filter list~

https://www.zuvio.com.tw/

https://irs.zuvio.com.tw/

https://irs.zuvio.com.tw/student5/welcome/index

https://www.zuvio.com.tw/student

zuvio.tw
zuvio.com.tw

forum.zuvio.com.tw

https://qt.zuvio.com.tw/student5/chickenM/articles

**Comment by Alex-302** [comment]
It seems it is used by education service. Please provide a source.
