### ISSUE TITLE
dcard.tw dcard.cc dcard.io dcard.hk https://bilanx-stage.dcard.io/v1/events

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#77857]
https://bilanx-stage.dcard.io/v1/events

from:
https://www.dcard.cc/f
https://www.dcard.tw/f
https://stage.dcard.io/f

refer:
https://github.com/AdguardTeam/AdguardFilters/search?q=dcard.tw&type=issues
https://github.com/AdguardTeam/AdguardFilters/search?q=dcard&type=issues
dcard.tw dcard.cc dcard.io dcard.hk

**Comment by Alex-302** [comment]
What is it?

**Comment by c2xusnpq6** [comment]
> What is it?

same thing, but diff domain name

**Comment by Alex-302** [comment]
Please describe why it must be blocked.

**Comment by c2xusnpq6** [comment]
> you may write in your language

thx **T.T**
