### ISSUE TITLE
Question: Adguard blocking session replay scripts?

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#7786]
Do the Adguard filters block tracking/keylogging scripts that create replay sessions?

See e.g. the article on the recent Princeton study: https://www.wired.com/story/the-dark-side-of-replay-sessions-that-record-your-every-move-online/

PS: Adblock Plus now blocks these.

**Comment by Alex-302** [comment]
Yes, new rules was added.
