### ISSUE TITLE
mooc? tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#77933]
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php?actype=start
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php?actype=end

```
||i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php^
or
/mooc/controllers/course_ajax.php (more than 1 sch using this system)
/controllers/course_ajax.php ?
```

![image](https://user-images.githubusercontent.com/75058881/111773241-e32b7b80-88e8-11eb-9b4f-efb571a90522.png)
![image](https://user-images.githubusercontent.com/75058881/111773264-ec1c4d00-88e8-11eb-842d-6707041d8774.png)
![image](https://user-images.githubusercontent.com/75058881/111784055-e5480700-88f5-11eb-8d19-93215c2cb890.png)

**Comment by c2xusnpq6** [comment]
https://www.google.com/search?q=%22mooc%2Fcontrollers%22

**Comment by c2xusnpq6** [comment]
intitle:網路學園
https://www.google.com/search?q=intitle%3A%E7%B6%B2%E8%B7%AF%E5%AD%B8%E5%9C%92

**Comment by c2xusnpq6** [comment]
旭聯科技SUNNET https://www.sun.net.tw/
https://www.sun.net.tw/custom_list.php#tab-tab6

**Comment by Alex-302** [comment]
Could you please record HAR and send to filters@adguard.com? I cannot just block request.

**Comment by c2xusnpq6** [comment]
@AdguardTeam @Alex-302 https://github.com/easylist/easylist/issues/7457#issuecomment-808916011

pls help....... `$referer`? `$from`? `$post`? `$formdata`? `$data`?

**Comment by Alex-302** [comment]
Blocked.

**Comment by c2xusnpq6** [comment]
@Alex-302 no............

pls undo https://github.com/AdguardTeam/AdguardFilters/commit/5b8a69c07f3e8d67d2041a19d8fe435ea2442f67

**Comment by c2xusnpq6** [comment]
It seems that it might break the webpage. @Alex-302

pls undo 7271699 and add:
/mooc/controllers/course_ajax.php?actype=end, /mooc/controllers/course_ajax.php?actype=start

and also block this too?:
/mooc/controllers/course_ajax.php and it must be from here(referer): /learn/path/download_preview.php

**Comment by c2xusnpq6** [comment]
`$referer`? `$from`? `$post`? `$formdata`? `$data`? `$postdata`? @Alex-302
