### ISSUE TITLE
adguard拓展无法正常工作

### ISSUE THREAD

**Issue by Graskize** [AdguardTeam/AdguardFilters#77952]
adguard for Mac的自带Safari拓展在所有网站都无法开启，都是禁用状态
![Xnip2021-03-20_00-36-26](https://user-images.githubusercontent.com/48375862/111813579-54ccef00-8914-11eb-98eb-f69196a32baf.jpg)
此网站已被禁用，旁边的开关只要开启就会刷新网页，但是依旧是关闭状态

**Comment by Alex-302** [comment]
@lolka4toli please assist.

**Comment by lolka4toli** [comment]
@Graskize in this case you better contact our support team at support@adguard.com.
