### ISSUE TITLE
fireoscaptiveportal.com/generate_204

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardFilters#77964]
***Description***:

RU AdList: Counters filter blocks HTTP 1.1 fireoscaptiveportal.com/generate_204 , which results in Fire TV disconnecting and reconnecting to WiFi every time that address is blocked/filtered.  That behavior is observed on multiple routers in my business facilities. The domain fireoscaptiveportal.com must be resolved and fireoscaptiveportal.com/generate_204 must be allowed for Fire TV to stay fully connected to WiFi.

**Comment by Alex-302** [comment]
@EntropySmoke Hi. This is foreign filter. Please write to https://github.com/easylist/ruadlist/issues
