### ISSUE TITLE
ABP Japanese filters

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7806]
I am an ios adguard (free) app user from Japan. I like all the filters
installed by default like EasyList and custom filters works great as well,
and I found that ABP Japanese Filters can block all annoying popups for
ads-depending website (e.g. movie streaming), only ABP Japanese filters
worked for them.

However, when you have ABP JP Filters enabled, lots of site break, I can’t
even search google (it shows this URL was blocked by contents blocker),
can’t load some .jp domain websites, and can’t load videos or thumbnails on
streaming websites (e.g. gostream.is 9anime.to).

I really want ABP Japanese filters work properly so that I can block all
the popups.

I tried disabling all the filters and importing raw ABP Japanese filters
from source, but not able to import because of bunch of error which I think
they’re caused by syntax differences.

Can you make ABP Japanese filters less strict?

Ticket ID:  1669988

**Comment by ameshkov** [comment]
Unfortunately, we cannot. ABP Japanese Filter is a third party filter and it is not maintained by us.
