### ISSUE TITLE
livemint.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#78095]
[https://www.livemint.com/news/world/saudi-arabia-prohibits-men-from-marrying-women-from-pakistan-3-other-nations-11616211574411.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.livemint.com/news/world/saudi-arabia-prohibits-men-from-marrying-women-from-pakistan-3-other-nations-11616211574411.html)

![overlay](https://user-images.githubusercontent.com/35470489/111899604-77423380-8a0c-11eb-98a8-ab373e38f829.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by wout-codes** [comment]
I don't think the cross button should be blocked, it's there just to collapse the article you're reading.

**Comment by adranger** [comment]
It's an annoyance especially on phones. It covers the article. By the way, the mobile version has a `.mobileAd` banner area.

**Comment by wout-codes** [comment]
`livemint.com##.mobileAd`
