### ISSUE TITLE
Plug.DJ not working

### ISSUE THREAD

**Issue by HatsanK** [AdguardTeam/AdguardFilters#7809]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: plug.dj not working correctly, no song histroys and can not join wait list
* **Current behaviour**: Disable all filters work fine. Enable all filters expect English filter work fine. 

<details><summary>Blocked Filtering logs(only turn on English filter)</summary>

https://adservice.google.com/adsid/integrator.js?domain=plug.dj
JavaScript
/adservice.
plug.dj

https://securepubads.g.doubleclick.net/gpt/pubads_impl_168.js
JavaScript
/securepubads.
plug.dj

https://ecdn.firstimpression.io/fi_client.js
JavaScript
||firstimpression.io^$third-party
plug.dj

https://cdn.districtm.ca/merge/merge.v4.2.116540.js
JavaScript
||districtm.ca^$third-party
plug.dj

https://cdn.districtm.ca/merge/merge.v4.2.116540.js
JavaScript
||districtm.ca^$third-party
plug.dj

</details></br>

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://screenshots.firefoxusercontent.com/images/1b36467c-272d-4f45-afcd-976194109c0a.png)

History view in plug.dj comunity

![image](https://screenshots.firefoxusercontent.com/images/e3a4ee71-c1a9-41ba-bf27-58aac5737597.png)

communities view in plug.dj comunity
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://screenshots.firefoxusercontent.com/images/0f9adafa-7c6f-4f5e-9fac-b6347b56c48a.png)

![image](https://screenshots.firefoxusercontent.com/images/79a4a84d-4dec-4047-b70c-a18cd6cabaaa.png)
</details><br/>

***Steps to reproduce the problem***: Enable English filter, join plug.dj community(note: dashboard works fine, and sometimes works fine in community.) 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

Firefox Beta(58.0b3)

**Filters:** English Filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox Beta
AdGuard version:                       | 2.7.3
Filters enabled:                       | English Filter (Social media filter, Annoyances filter, Japanese filter, Experimental filter, Mobile Ads filter, EasyList China, List-KR)
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

edit 1: It was working correctly but not working since last 1-2 days.

**Comment by Alex-302** [comment]
Can't reproduce. I need direct URL of the page. Which filter breaks it?

**Comment by HatsanK** [comment]
on https://plug.dj/nightblue 
and only `English filter` breaks it

**Comment by Alex-302** [comment]
I can't reproduce
<details>

![image](https://user-images.githubusercontent.com/8361299/33169387-2d93fd44-d04d-11e7-93ce-dfb5ec5c0916.png)

</details>

Please check one-by-one:
```
@@||plug.dj^$urlblock
```
```
@@||plug.dj^$elemhide
```
```
@@||plug.dj^$document
```

**Comment by HatsanK** [comment]
I tried `@@||plug.dj^$urlblock` , `@@||plug.dj^$elemhide`, `@@||plug.dj^$document` one-by-one

Result is working 2 rules with ads. expect `@@||plug.dj^$elemhide`, which has same incorrect blocking.

When i start w/ fresh profile in firefox 58.0.b5 and two working rules, this messages shown. I think it's welcome message. which is not shown w/o user filter rules.
<details><summary>Working Detail</summary>
![image](https://screenshots.firefoxusercontent.com/images/c9396065-00e8-4029-b761-e5b0f6962d5b.png)
</detail>

Also, this site was just work fine in some days ago.

**Comment by Alex-302** [comment]
Ok. Remove these rules, open filtering log, reproduce the issue and export the log.

**Comment by HatsanK** [comment]
[gist](https://gist.github.com/HatsanK/d1b15c4ab0953d2fd4257d111d045559)

I don't know how to export logs in web-ext. i just save page. I think logs are include in htm file.

**Comment by Alex-302** [comment]
It is unreadable. Please make screenshot of blocked requests
![image](https://user-images.githubusercontent.com/8361299/33209821-5f6f9f98-d120-11e7-9e5b-0b7c4504cd0d.png)

**Comment by HatsanK** [comment]
Ok, reposted.
![image](https://user-images.githubusercontent.com/30770849/33212359-041839b6-d166-11e7-84aa-0c0bc4ee98f6.PNG)

**Comment by Alex-302** [comment]
Ok. Please try to create exclusions for these domains, using this mask:
```
@@||domain.com^$domain=plug.dj
```
`domain.com` - is blocked domain.
For example, `doubleclick.net` => `@@||doubleclick.net^$domain=plug.dj`

**Comment by HatsanK** [comment]
Ok, I check console and show this error.

![image](https://user-images.githubusercontent.com/30770849/33474635-d56fad98-d6be-11e7-8e5a-94f927fe008c.png)

googletag is not defined, they using some of like... webframework? that error shows up on require.js? and app.js? like file. they stop processing when google tag fuctions is not working.

So, When i put `@@||securepubads.g.doubleclick.net^$domain=plug.dj` in user rules and work fine.

**Comment by Alex-302** [comment]
@HatsanK Ok)

> @@||securepubads.g.doubleclick.net^$domain=plug.dj

it is wide(can unblock unnecessary requests).
Please check
```
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=plug.dj
```

**Comment by HatsanK** [comment]
Yes, it works too.
Please close issue after add that rule in filter. Thank yoy!

**Comment by Alex-302** [comment]
Added
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=plug.dj`
