### ISSUE TITLE
AdGuard breaks https://mailchimp.com/ admin panel

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7810]
Adguard breaks MailChimp. Even when I add an exception via Assistant. It starts working when you whitelist it and remove the ~extension operator from the rule.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/33113933-314f8fe2-cf63-11e7-8b65-64dbbbf32930.png)

</details>

### Customer ID 
1112873

### Your environment

* Adguard version: AdGuard 6.2.433.2167
* Subscriptions: English, Spyware, Experimental, Reek
* Driver type: WFP
* HTTPS: On

**Comment by Alex-302** [comment]
Can't reproduce.
Try both rules(not ony-by-one)
```
@@||admin.mailchimp.com^
@@||admin.mailchimp.com^$extension
```

**Comment by GollyJer** [comment]
@Alex-302 It's when you log into a mailchimp account.  All the sections are blank... Campaigns, Templates, Lists, Reports.

**Comment by Alex-302** [comment]
Please add the rules above and check again.

**Comment by GollyJer** [comment]
Yes.  Anything that hides the extension button works.
It seems strange it's only me.  It works for you without any added filter rules and the extension showing on page?

**Comment by Alex-302** [comment]
> It works for you without any added filter rules and the Assistant showing on page?

yes. But mailchimp.com can be used for advertising. Added that excretions.
