### ISSUE TITLE
Failed to bypass antiadblock at netfi.me

### ISSUE THREAD

**Issue by anphucnguyen** [AdguardTeam/AdguardFilters#78111]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Adguard can not bypass antiadblock at netfi.met
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%
![image](https://user-images.githubusercontent.com/27940316/111904713-dd659f80-8a7a-11eb-9b58-c0db2b8d6b19.png)
%)
</details><br/>

* **Expected behaviour**: Can bypass antiadblock at this site..

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***: Visit netfi.me

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
AdGuard version:                       | 7.6 nightly 24
Filters enabled:                       | Adguard Base, Adguard Tracking protection, Adguard Annoyances, Adblock warning removal, Adguard Experimental
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Enabled
Helpdesk ID (if exists):               | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by sugarfreesweetener** [comment]
`https://who.is/whois/netfi.me`
