### ISSUE TITLE
www.9to5google.com - with AdGuard Content Blocker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#78132]
@Truman82 commented on [Thu Mar 18 2021](https://github.com/AdguardTeam/ContentBlocker/issues/249)

### Steps to reproduce

1. Go to www.9to5google.com with your adblocker activated on samsung browser. There should be three dots in middle upper side of screen which folöows you when you scroll down or up the website.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)|
| Browser in use:| (Samsung Interner/Yandex Browser)|
| Filters enabled in Adguard:| (e.g. English, Annoyances)|
| Device model:| (e.g. Google Pixel)|
| Operating system and version:| (e.g. Android 7.1.2)|
| Rooted or not? | (Yes/No) |

**Comment by BlazDT** [comment]
Issue seems to be a direct elemhide rule as with $elemhide exclusion it works (when social filter is active), with $generichide not (already excluded both rules from our social filter to no avail). The three button icon should always stay at top, but with Social filter not.

**Comment by ameshkov** [comment]
As far as I recall, `$generichide` is not supported by Samsung/Yandex.

**Comment by Alex-302** [comment]
@Truman82 Please make screenshots. The only difference with/without AdGuard on my device - ads.

**Comment by Truman82** [comment]
It was fixed by itself since you last mailed me.

Hanki Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
