### ISSUE TITLE
Unable to connect to free wi-fi networks

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7814]
> The problem is still related to Adguard blocking mostly datavalet and gstatic - the services that most wi-fi providers use to validate the connection. 
If I disable Adguard, I can connect to any free wifi service. With Adguard
enabled most of them just hang up.

The customer reported that he's unable to connect to McDonald's and Canadian Tire free hotspots, logs with time markers are available here: 1470818

### Customer ID 
1470818

### Your environment

* Adguard: 2.10.164
* Android: 6.0.1
* Subscriptions: , 3, 4, 14, 11, 203
* HTTPS: Off
* Filterng mode: VPN
* Method: Full

**Comment by ameshkov** [comment]
Wrong repo?

**Comment by Alex-302** [comment]
Is it caused by filters/DNS?

**Comment by evgeniy-ADG** [comment]
okay okay sorry
https://github.com/AdguardTeam/AdguardForAndroid/issues/1606
