### ISSUE TITLE


内容打不开

### ISSUE THREAD

**Issue by Renjh5218** [AdguardTeam/AdguardFilters#78154]
![Screenshot_20210322-111849.jpg](https://user-images.githubusercontent.com/79973902/111938219-7391d800-8b04-11eb-931a-1aab319abdd9.jpg)![Screenshot_20210322-113931.jpg](https://user-images.githubusercontent.com/79973902/111938230-7b517c80-8b04-11eb-8bd8-a8c1f42b704d.jpg)
您好，我把
||i.snssdk.com^$domain=~i.snssdk.com
这条规则拦截后内容可以显示，拦截后它会跟踪我吗？谢谢

**Comment by Alex-302** [comment]
@Renjh5218 Hi. Sorry, don't understand what do you mean.
If request is blocked, served cannot receive it.

**Comment by krystian3w** [comment]
So apps not regonize `$domain=~i.snssdk.com` / `$third-party`  and needed `,app=~org.example.app`?

**Comment by Renjh5218** [comment]
> @Renjh5218 Hi. Sorry, don't understand what do you mean.
> If request is blocked, served cannot receive it.

Hi,thank you help me.
I mean, maybe this rule 
||i.snssdk.com^$domain=~i.snssdk.com blocked by mistake, because the content of the web page cannot be displayed normally. If I lock it, will I be tracked?  This rule is located in a filter called Adguard Tracking Protection Filter
![Screenshot_20210327-110536__01.jpg](https://user-images.githubusercontent.com/79973902/112708861-a3b7ed00-8eef-11eb-8b0d-cf8c5d779336.jpg)
And maybe it should be remove from the filter
Thank you.

**Comment by Alex-302** [comment]
Please describe how to reproduce this issue.
