### ISSUE TITLE
https://www.finam.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7816]
The graph won't load

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/33125714-48c684e2-cf8a-11e7-96bc-c2cf98308d04.png)

</details>

### Your environment
1670370

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
Уже было вроде. Без нас он тоже не работает, даже в IE
http://imagizer.imageshack.com/img922/6117/hUhVo8.jpg

**Comment by bconskri** [comment]
Добрый день

Хочу оставить комментарий как инициатор обращения в AdGuard. Не до конца понял ответ, так как это не какой-то мелкий сайт. Это финам, который зарабатывает на том, что люди смотрят у них графики и они у них работают. Не знаю как в IE, но в Safari точно. 
При обращении я оставлял сразу два скрина. Один, когда AdGuard включен и график не грузится и второй скрин, когда Adguard выключен и график грузится. 
Собственно по сей день и пользуюсь таким способом - отключаю Adguard, чтобы посмотреть finam.ru
Кстати, при выключенном adguard но при использовании adguard dns тоже не работает график.

**Comment by bconskri** [comment]
скрин когда adguard выключен и все загружается
https://www.dropbox.com/s/ixsfh7sg4xy2tnn/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202017-12-07%20%D0%B2%2017.03.21.png?dl=0

**Comment by bconskri** [comment]
скрин когда в эту же минуту, что видно по часам adguard включен и ничего не работаетhttps://www.dropbox.com/s/3zeei6skhvq5jd0/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202017-12-07%20%D0%B2%2017.03.34.png?dl=0

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/8189#issuecomment-350178999
