### ISSUE TITLE
Yandex browser 21.3.0.373 beta Tableau is blocked by AdGuard

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#78178]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

В Яндекс.Браузере Версия 21.3.0.373 beta перестало открываться Табло с начальными вкладками. При этом никаких ручных изменений и настроек не производилось. При очередном включении компьютера просто показывается пустой экран с анимацией. Если выключить расширение и перезапустить браузер, то это не решает проблему, а если выключить саму программу на компьютере и перезапустить браузер, то Табло вновь появляется. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/111974303-f36d7180-8b07-11eb-88f6-464a393b0b53.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/111974358-008a6080-8b08-11eb-980c-40f321ee1b69.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

Ru Adlist, Base, Tracking protection, Russian

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10.0.19042.0
Browser:                               | Yandex browser 21.3.0.373 beta
AdGuard version:                       | 7.5.3
Filters enabled:                       | Ru Adlist, Base, Tracking protection, Russian
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    |  Disabling Stealth mode does not help
Helpdesk ID (if exists):               | 3268173

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@Eugene-Savenko вчера вроде исправили. Проверь плз со свежими фильтрами.
