### ISSUE TITLE
Feature request: Create filter with ClearURL rules for cleaning links

### ISSUE THREAD

**Issue by logos88** [AdguardTeam/AdguardFilters#78286]
Currently there are many browser extensions for automatically remove tracking elements from URLs when browsing through the Internet like [ClearURL](https://addons.mozilla.org/es/firefox/addon/clearurls/), [Neat URL](https://addons.mozilla.org/es/firefox/addon/neat-url/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) or [Link Cleaner](https://addons.mozilla.org/es/firefox/addon/link-cleaner/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).

This extensions use rules to remove tracking from URLs, block ping tracking, prevent ETag tracking or skip redirect pages of facebook, reddit or bitly pages.

Since they use rules for doing that, I think Adguard could make a specific filter to cover such issues directly from Adguard without needing other extensions.

For this I would recommend using ClearURL lists since it's a very good extension with a constantly updated and open source list.

As the author states [here](https://gitlab.com/KevinRoebert/ClearUrls/-/issues/155), he likes the idea that other people also use the rule file in their projects, and that's the reason he has published a new rules file, with a more independent structure. 

In this[ wiki entry](https://gitlab.com/KevinRoebert/ClearUrls/-/wikis/Specifications/Rules) explains how the files work and how to use them.

**Comment by krystian3w** [comment]
see: https://github.com/AdguardTeam/FiltersRegistry/issues/401

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #448](https://github.com/AdguardTeam/FiltersRegistry/issues/448) via [**ZenHub**](https://www.zenhub.com/)
