### ISSUE TITLE
www.vpsmm.com

### ISSUE THREAD

**Issue by qianduanmei** [AdguardTeam/AdguardFilters#78323]
规则：https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

像正常的几个广告屏弊，顶部表格、侧边图片等，属于正常广告范围内。

例如：

vpsmm.com##.sidebar 
vpsmm.com##div[class*="sidebar"]
vpsmm.com##div[id^="top"]
vpsmm.com##.header + div

上述的这些过滤掉广告，无可厚非。

但有几个不太友好的过滤规则，已经影响到了网站的正常访问了。尤其是后台部分，只要有链接的图片和文字，新窗口的链接之类，或者，只要有表格显示，就全部都无法显示。

例如：

vpsmm.com##a[target="_blank"]
vpsmm.com##a[style]
vpsmm.com##div > a > img
vpsmm.com##td > a
vpsmm.com##th > a

希望能整理一下，删除掉这几个对网站实在影响太大的规则。

**Comment by Alex-302** [comment]
Hi. Please describe an issue in English. Google translate it iseless
