### ISSUE TITLE
dcard.tw - AnnoyancesFilter request

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#78338]
![image](https://user-images.githubusercontent.com/75058881/112294762-22354480-8cce-11eb-940c-0802df7e8011.png)

```
dcard.tw###__next > div.bvk29r-0.bpvGjj:nth-child(2) > div.bvk29r-2.hRYgdl:nth-child(2) > div.sc-10tqbnq-0.LctwW > div.sc-10tqbnq-1.kDeEqR > div.d4ydwz-0.eQRUQs > div.f5pygf-0.iLxWRn:first-child
```
![image](https://user-images.githubusercontent.com/75058881/112294545-e8643e00-8ccd-11eb-833c-7f0b81cef8a5.png)

**Comment by piquark6046** [comment]
Please give me the URL.

**Comment by piquark6046** [comment]
@c2xusnpq6

**Comment by c2xusnpq6** [comment]
oh... sorry.... ^^'' https://www.dcard.tw/f/fju

**Comment by piquark6046** [comment]
I think that field is content of a group.

**Comment by krystian3w** [comment]
try these:

`##div[role="main"] > div > div > div > div > div > picture > img[src*="/full."]`

**Comment by Alex-302** [comment]
Dangerous. For user filter:
`dcard.tw#?#img[alt$="/default-cover.jpg"][width="1800"][height="600"]:upward(4)`
