### ISSUE TITLE
elearningindustry.com

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardFilters#78360]
Annoyances, cookies on https://elearningindustry.com/what-is-microlearning-benefits-best-practices
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/112328742-aa641b80-8cc7-11eb-8308-809cb478f608.png)

</details><br/>

**Comment by krystian3w** [comment]
Need repair scroll or accept (if other pop-ups are broken by use scriptlets/ExtendedCSS).
