### ISSUE TITLE
Missed Ad on minecraft.fandom.com

### ISSUE THREAD

**Issue by jo620kix** [AdguardTeam/AdguardFilters#78407]
##### URL
`https://minecraft.fandom.com/wiki/Java_Edition_21w11a`

##### Description
The "Gamepedia Pro" ad on the right is not blocked.

<details><summary>Screenshot:</summary>

![screenshot](https://user-images.githubusercontent.com/81214276/112449740-a4b01980-8d4b-11eb-9276-31bda5a126de.png)

</details>

**Comment by krystian3w** [comment]
smell anti-adblock mechanism.

**Comment by AdamWr** [comment]
Added to `AdGuard Annoyances filter`:
```
fandom.com##body #pageWrapper > #content[role="main"] > div[id^="siderail_"][id*="_gamepedia"]
fandom.com#$?##pageWrapper > #content[role="main"] > #bodyContent:has(+div[id^="siderail_"][id*="_gamepedia"]) { width: 100%!important; }
```
Update should be available in 1-2 hours.
