### ISSUE TITLE
Missed Ad / Annoyance on hk.appledaily.com

### ISSUE THREAD

**Issue by jo620kix** [AdguardTeam/AdguardFilters#78485]
##### URL
`https://hk.appledaily.com/`

##### Description
The ad on the top (marked by red borders) is not blocked.

[Apple Daily](https://en.wikipedia.org/wiki/Apple_Daily) is a Chinese-language newspaper, and the ad links to its another website which lists various offers from merchants.

<details><summary>Screenshot:</summary>

![screenshot](https://user-images.githubusercontent.com/81214276/112594754-4ba2bd00-8e01-11eb-98a8-b64ec18805d7.png)

</details>

**Comment by jo620kix** [comment]
The filter does not work now (maybe the website code has changed?), and the advertisement is not filtered:

<details><summary>Screenshot:</summary>

![screenshot](https://user-images.githubusercontent.com/81214276/115404922-47d64080-a1dd-11eb-8b10-893c3eda82e5.png)

</details>

**Comment by Alex-302** [comment]
@jo620kix Hi. Fixed.

**Comment by jo620kix** [comment]
Thank you very much!
