### ISSUE TITLE
Why some scripts are removed in adguard filters????

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#7849]
@saravanakumar1 commented on [Thu Nov 23 2017](https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/120)

Some ThirdParty Scripts are removed in adguard filter  (Eg: in url: https://filters.adtidy.org/extension/chromium/filters/3.txt, you hve removed scripts like inplaybricks.com
linkexchange.com), Can i know the reason for script removable?

**Comment by Alex-302** [comment]
> inplaybricks.com

I don't see it in the filters.

> linkexchange.com

this rule exists in English filter.

**Comment by saravanakumar1** [comment]
Thanks for ur reply!!!!!
but it seems like some rules are missed,  I need to know whether removal of rules happened while updating filters???

**Comment by Alex-302** [comment]
You are looking in the wrong file.
https://filters.adtidy.org/extension/chromium/filters/3.txt - is Spyware filter
English is `2.txt`

**Comment by saravanakumar1** [comment]
okay!! so none of the rules will be removed from filters right at any time??? only updation of rules will be happened?

**Comment by Alex-302** [comment]
> okay!! so none of the rules will be removed from filters

yes. Only optimized filters have less rules. For example
`https://filters.adtidy.org/extension/chromium/filters/2_optimized.txt`
