### ISSUE TITLE
prosieben.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#78524]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Video can’t be played.
`https://www.prosieben.de/tv/germanys-next-topmodel/video/168-staffel-16-episode-8-strike-a-pose-ganze-folge`

Account required. Account data:
E-Mail: `zsaalleemfezon@duybuy.com`
Password: `zsaalleemfezon@duybuy.com1A`

Clear cookies if it can’t be reproduced
</details><br/>

[//]: # (Substitute this line with a description of the problem)

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.34
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

When i whitelist `usercentrics.eu` the player works but it shows ads

**Comment by BlazDT** [comment]
Playing fine without whitelisting something. Please check @AdguardTeam/filters-maintainers

**Comment by Morku** [comment]
oh lol, Ads even with an account.

<details><summary>Screenshot-1:</summary>

![Screenshot 2021-03-26 160717](https://user-images.githubusercontent.com/6276915/112652629-e45f2a00-8e4d-11eb-916a-71ffaa492bd3.png)


</details><br/>

**Comment by BlazDT** [comment]
@morku please try to enable experimental filter.

**Comment by AdamWr** [comment]
Regarding ads, I can reproduce it and it seems that this rule blocks them:
`||zomap.de^$domain=prosieben.de`

**Comment by Morku** [comment]
@BlazDT 
Yes, with Experimental filter (or Adams rule) it says "starting Ad in 3-2-1...", but it doesn't start the Ad :o)

**Comment by JobcenterTycoon** [comment]
Nobody can reproduce? I need these 3 filters to fix the breakage:

`@@||api.usercentrics.eu/translations/translations-de.json`
`@@||app.usercentrics.eu/browser-sdk/*/cross-domain-bridge.html`
`@@||consents.usercentrics.eu/consent*?controllerId=*`

**Comment by JobcenterTycoon** [comment]
The request only appear after adding the 2 first filter.

Your fix doesn’t work for me. I need the last filter while the url `graphql.usercentrics.eu` don’t need on the whitelist on my end

**Comment by AdamWr** [comment]
I checked it with these rules:
```
@@||api.usercentrics.eu/translations/translations-*.json$domain=sixx.de|prosiebenmaxx.de|sat1.de|prosieben.de|kabeleins.de|sixx.de|sat1gold.de|ran.de|joyn.de
@@||app.usercentrics.eu/browser-sdk/*/cross-domain-bridge.html$domain=sixx.de|prosiebenmaxx.de|sat1.de|prosieben.de|kabeleins.de|sixx.de|sat1gold.de|ran.de|joyn.de
```
and I wasn't able to reproduce that request, that's why I asked and didn't close that issue.

When `graphql.usercentrics.eu` is blocked then button to close cookie popup works with a delay on my end.

Does rule like this work fine?
```
@@||consents.usercentrics.eu/consent*?controllerId=$domain=sixx.de|prosiebenmaxx.de|sat1.de|prosieben.de|kabeleins.de|sixx.de|sat1gold.de|ran.de|joyn.de
```

**Comment by JobcenterTycoon** [comment]
Yes it works

**Comment by AdamWr** [comment]
Okay, added.
Thank you for your reply.
