### ISSUE TITLE
m.economictimes.com mobile site

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdguardFilters#78598]
Mobile site `https://m.economictimes.com/markets`

- Ad placeholder above footer nav
- App banner and overlay (randomly appears)
    - To get overlay, first open an article then go back
    - Reload current page `https://m.economictimes.com/markets` multiple times

Proposed filters:
```
! Ad placeholder
m.economictimes.com##.ads
m.economictimes.com###btmNav:style(min-height: unset !important)

! Banner & overlay
m.economictimes.com###prominentOverlay, #prominentBanner, #mappBanner
m.economictimes.com##body:style(overflow: auto !important)
```

**Comment by Alex-302** [comment]
Popups not reproduced. 
Please check after filters update.

**Comment by cantunborn** [comment]
`m.economictimes.com###btmNav` blocks entire footer instead of empty ad space.

I can't figure out the logic of how the popup appears, so it may not be testable.

Below filters are easily testable in chrome responsive mode in dev tools:
```
m.economictimes.com##.ads
m.economictimes.com###btmNav:style(min-height: unset !important)
m.economictimes.com###mappBanner
```

**Comment by Alex-302** [comment]
> m.economictimes.com###btmNav:style(min-height: unset !important)

ok.


> m.economictimes.com###mappBanner
> m.economictimes.com##.ads

I don't see. Please make screenshot.

**Comment by cantunborn** [comment]
![Screenshot (82)](https://user-images.githubusercontent.com/70632433/112853953-fdc0da00-90ca-11eb-9a18-84c092b32706.png)
![Screenshot (83)](https://user-images.githubusercontent.com/70632433/112853964-00233400-90cb-11eb-8f6c-0a358676085a.png)
![Screenshot (84)](https://user-images.githubusercontent.com/70632433/112853971-01ecf780-90cb-11eb-8f05-45a3d0091fa0.png)
![Screenshot (85)](https://user-images.githubusercontent.com/70632433/112853974-031e2480-90cb-11eb-9b9e-be0bf333fb3d.png)

**Comment by wout-codes** [comment]
Please try with AdGuard Extension.

**Comment by cantunborn** [comment]
I have all adguard filters enabled in uBO.

**Comment by cantunborn** [comment]
Also, `​https://jsm.etimg.com/js_interstitial/v-205,minify-1.cms` serves interstitial ads. The easylist issue I created for this was not solved properly.

**Comment by cantunborn** [comment]
Popup banner reproduced.

![Screenshot (86)](https://user-images.githubusercontent.com/70632433/112856161-20ec8900-90cd-11eb-9208-9d70203cf404.png)
![Screenshot (87)](https://user-images.githubusercontent.com/70632433/112856173-234ee300-90cd-11eb-8e45-5a614f1985b4.png)

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/78598#issuecomment-809436893 fixed

**Comment by Alex-302** [comment]
> Popup banner reproduced.

fixed

**Comment by cantunborn** [comment]
> > Popup banner reproduced.
> 
> fixed

Also need to restore scrolling `m.economictimes.com##body:style(overflow: auto !important)`.

**Comment by Alex-302** [comment]
done
