### ISSUE TITLE
[blocklist] phishing via whatsapp urgent

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/AdguardFilters#78614]
119910.xyz
xbtbxggxz.asia
xss.news
145650.xyz
chatwhatsapp.today
cdn-bimi.akamaized.net
www.googles-analytics.com
ajax.googlescdn.com

![photo_2021-03-27_16-45-11](https://user-images.githubusercontent.com/8227101/112726142-2bb3ec00-8f1c-11eb-8e85-d1a7a99d6225.jpg)

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/domain/www.googles-analytics.com/details

**Comment by Yuki2718** [comment]
@scafroglia93 Please provide full URLs, just visiting the domain returns error. We check all the issues.

**Comment by scafroglia93** [comment]
guys, the other domains are used by phishing -> this was extracted from nextdns log

**Comment by scafroglia93** [comment]
xss.news -> this site create other domains like this ->
734137.xyz
wxlztpg.site
xccredit.club
tqgcuie.asia
579695.xyz
78657968.xyz

**Comment by Yuki2718** [comment]
>  this was extracted from nextdns log

How you got that screenshot then? Some of the domains just redirect to others in the list or similar, I'll add few more destination page than entrance. The rest may be malicious and may be found on VT, that's @lolka4toli 's decision.

**Comment by scafroglia93** [comment]
These are all the domains I found for the moment

342694.xyz
579695.xyz
688547.xyz
734137.xyz
739487.xyz
78657968.xyz
apqkl.club
khdfmb.vip
tqgcuie.asia
wxlztpg.site
xccredit.club
ykiznuffn.asia

**Comment by lolka4toli** [comment]
Blacklisted.
