### ISSUE TITLE
https://mobile.twitter.com/ - popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7863]
https://github.com/AdguardTeam/AdguardFilters/issues/6011

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/33187574-65c29754-d09b-11e7-8115-21415d7564b7.png)

</details>

AdGuard 1.3.1
Safari
The list of filters

Filters subscriptions:

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.36.82 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.15.54 Enabled=YES
- **ID=14 Name="Annoyances filter" Version=1.0.21.19 Enabled=YES**
- ID=11 Name="Mobile Ads filter" Version=1.0.10.53 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.76 Enabled=YES
- ID=101 Name="EasyList" Version=1.0.77.40 Enabled=YES
- ID=118 Name="EasyPrivacy" Version=1.0.91.5 Enabled=YES
- ID=207 Name="Adblock Warning Removal List" Version=1.0.91.34 Enabled=YES
- ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES

**Comment by Alex-302** [comment]
Popup has random code. Removing is dangerous.
