### ISSUE TITLE
dejure.org: anti-adblock overlay

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#7865]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Website***: dejure.org
***Noticed on webpage***: https://dejure.org/gesetze/BauGB/45.html
***Description***: anti-adblock script
* **Current behaviour**: anti-adblock script creates an overlay asking the visitor to disable his adblocker

<details><summary>Screenshot:</summary>

![snap-antiadblock](https://i.imgur.com/rJqkwa4.jpg)
</details><br/>

* **Expected behaviour**: no anti-adblock overlay

<details><summary>Screenshot:</summary>

![snap-clean](https://i.imgur.com/quecl0q.jpg)
</details><br/>

***Steps to reproduce the problem***: just navigate to the site or the webpage; if necessary, delete the dejure.org cookie beforehand

***System configuration***

**Filters:**
**Adguard Filters:** English, Spyware, Social media, Annoyances, Russian, German, Japanese, French, Dutch, Spanish/Portuguese, Mobile Ads, Safari
**EasyList:** EasyList, EasyPrivacy, Fanboy's Social Blocking List, Fanboy's Annoyances, EasyList Czech and Slovak, EasyList Germany, EasyList Italy, Icelandic ABP List, Norsk adblockliste, void.gr, Fanboy's Enhanced Tracking List
**Other:** Adblock Warning Removal List, Anti-Adblock Killer (Reek), CJX's Annoyance List, Fanboy Anti-Facebook List, I don't care about cookies, Malware Domains, Peter Lowe's list, Prebake, Spam404, BarbBlock

Information                            | Value
---                                    | ---
Operating system:                      |  OS X 10.11.6
Browser:                               | Safari 11.0.1
AdGuard version:                       | Adguard Desktop for macOS 1.5.0
Filters enabled:                       | *see above*
AdGuard DNS:                           | None

**Comment by Alex-302** [comment]
fixed
