### ISSUE TITLE
http://www.dysfz.cc/ - Banner

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7867]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://www.dysfz.cc/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/33190968-360054cc-d0bc-11e7-8353-2334ffff574e.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.36.68 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.28 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.76 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.2
Operating system version (Android/iOS) | iOS
Browser:                               | Sfari
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1670785

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed.
