### ISSUE TITLE
ok.ru app - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7879]
AdGuard blocks pictures in [the ok.ru app](https://play.google.com/store/apps/details?id=ru.ok.android&hl=ru)

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/33221620-cd5d8bd2-d148-11e7-83d0-2bd3af42502b.png)

</details>

### Customer ID 
1118879, with logs and timing

### Your environment

* Adguard version: 2.10
* Android 7.1.1
* HTTPS: On
* DNS Off
* VPN mode
* HQ method
* "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

**Comment by Alex-302** [comment]
I can't reproduce. Is it caused by filters?
