### ISSUE TITLE
[Android] - My Talking Tom in-app ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#788]
https://play.google.com/store/apps/details?id=com.outfit7.mytalkingtomfree&hl=en
http://snag.gy/S7kqI.jpg
http://snag.gy/PeN7T.jpg
CCI-295-21021

**Comment by Alex-302** [comment]
Added to mobile filter
||cdn.outfit7.com/promo-nc$empty
||apps.outfit7.com/rest/ad/$empty
||appclick.co^$empty

**Comment by Alex-302** [comment]
Please check it.

**Comment by Alex-302** [comment]
Какой режим фильтрации?

**Comment by vgavrish** [comment]
Качественный, https есть
сегодня при первой загрузке приложения появилось окно на весь єкран

**Comment by Alex-302** [comment]
В таких случаях нужен лог HTTP запросов с указанием времени запуска приложения. Перед запуском нужно сперва полностью его остановить и очистить кэш.

**Comment by Alex-302** [comment]
Вот такие правила можно попробовать
```
||unityads.unity3d.com^$app=com.outfit7.mytalkingtomfree
||api.bee7.com^$empty
||adjust.io^$empty
||pssvc.iqzone.com^$empty
||cdn.outfit7.com/s2s/$app=com.outfit7.mytalkingtomfree
```
Окно на весь экран может быть своим. Нужен скрин.
