### ISSUE TITLE
Threema and Signal dont notificate me when Adguard is activated

### ISSUE THREAD

**Issue by trash-it** [AdguardTeam/AdguardFilters#78879]
Hi, 
Threema and Signal dont bring notifications when adguard is activated. Doesnt matter is i exculde these apps in adguard or not. I can see something special in the filter protocol.

I have the Version 3.6.1 for Android. My personal filters blocking only facebook, but i activated nearly all filterlists.

**Comment by Alex-302** [comment]
> Threema and Signal

What is it? Please describe how to reproduce.
Is stealth mode enabled?

**Comment by Alex-302** [comment]
> The repord demands and complete url.

you can enter download link(app store or their site)



> Steath is activated.

please try to disable `Block Push API` option and check again.

**Comment by trash-it** [comment]
Block Push APi makes no difference. I even tried to complete deaktivate the stealth also nothing. But i found out some interesting behaviour. I dont have the problem when I surf over an active wifi connection. But when I surf with the provider network than the problem exist. 

I also notice when I deactivate Adguard than sometimes/ not always  I dont have internet. I mean I try to open an website and nothing happens, my apps not refresh and so on. When I activate and deactivate the airplane mode everything works. This behavior I also only have with the provider coverage. I though at first it is because I set an custom dns server in Adguard. But even with the standard provider dns i have the problem. 

I will try to send the reports today.

**Comment by Alex-302** [comment]
Hmm. Maybe provider block/intercept DNS requests.

> I also notice when I deactivate Adguard than sometimes/ not always I dont have internet.

Not filters related. @lolka4toli please assist.

**Comment by trash-it** [comment]
I testet some things on the weekend. I have the same problem, even when i dont change the DNS server and use the isp server instead. Still strange that there are no problems with active wifi. 

Btw I wanted to upload the reports, at the end the formular wants two screenshots. I cant create two different screenshots. because the error is not visable. In the applications is not written that there is no connection. I just dont get new messages. 
But I noticed that it happens to multiple apps. Not only signal an threema. Its also my banking and ebay app at example. Could it be, that they all use a specific service to upload data? A Service which is not used, when I have a wifi connection?  
I have a Samsung S10+ and have nearly blocked everything which I dont know what it is.

**Comment by lolka4toli** [comment]
@trash-it in this case you better contact us at support@adguard.com to send all the additional info and screenshots if needed.
