### ISSUE TITLE
Videos on golem.de incorrectly blocked by AdGuard Base Filter

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardFilters#78871]
***Description***: 
* **Current behaviour**: 

Videos on golem play only sound (no image) when the AdGuard Base Filter is active. Works fine when the filter is inactive.

* **Expected behaviour**: 

Video plays _visibly_ in the video player

***Steps to reproduce the problem***:

Go to [this article](https://www.golem.de/news/vision-s-sonys-elektroauto-wird-oeffentlich-gezeigt-2103-155351.html), make sure the AdGuard Base Filter is active, and start the video.

***System configuration***

**Filters:**
AdGuard Base Filter

Information                            | Value
---                                    | ---
Operating system:                      | macOS
Operating system version  | 11
Browser:                               | Safari
AdGuard version:                       | 2.5.3.955
AdGuard DNS:                           | Default

**Comment by BlazDT** [comment]
Please try to enable German filter and update.

**Comment by SebastianRasch** [comment]
No you're right, my bad. The problem only occurs with AdGuard Base Filter **AND** AdGuard German Filter both active. Sorry I didn't mention that this filter is active, too.

I don't want to use EasyList German because it filters way less than AdGuard German Filter (see for yourself on the same page). I also need the English filter obviously.

**Comment by SebastianRasch** [comment]
That is so weird. It works in Microsoft Edge (Chrome based) but not in Safari. Maybe a problem with M1 Macs? It might have started with my new M1 Mac beginning of this year, not sure.
I deactivated all other filters and only have the AdGuard Base and AdGuard German filters active. Videos start for a second and then the play button appears again. When I then press play again it only plays sound and the video itself is black.

**Comment by SebastianRasch** [comment]
Sorry I didn't read this earlier.

The video plays fine separately, no problems here. Also, the video seems to play normally on golem.de when the page has been opened the first time. Upon reloading the page it would have the described problem. Reloading the page again would make it work again for one time, really weird. It seems to work every second time.

What's blocked by the AdGuard Base or German filter is as followed:
`<link href="//cdn-a.yieldlove.com" rel="dns-prefetch">` by `||yieldlove.com^$third-party`
`<link href="//ad.doubleclick.net" rel="dns-prefetch">` by `||ad.doubleclick.net^$third-party`
`<link href="//securepubads.g.doubleclick.net" rel="dns-prefetch">` by `/securepubads.`
`<script src="https://cdn.stroeerdigitalgroup.de/metatag/live/ctc_golem/metaTag.min.js" type="text/javascript"></script>` by `||stroeerdigitalgroup.de/metatag/$third-party`
`<script type="text/javascript">` by `*onemillionwebpages*$$script[tag-content="Flags."][min-length="20000"][max-length="300000"`
`https://www.golem.de/staticrl/scripts/adsense/golem_csi-133-min.js` by `/adsense/*`
`https://imasdk.googleapis.com/js/sdkloader/ima3.js` by `||imasdk.googleapis.com^$third-party`

So far all normal, I guess. But then it goes on to block this, too:
`https://video.golem.de/download/23947?q=medium&rd=rlrmp&v=d&cpxl=0&dlidx=gif&ra=155351` by `||video.golem.de/download/*&cpxl=$image`
Albeit not by the Base or German filter but the tracking protection filter which, on its own, doesn't pose a problem.

**Comment by BlazDT** [comment]
Working fine when adding this rule?

`@@||video.golem.de/download`

**Comment by SebastianRasch** [comment]
No, unfortunately not. I can also reproduce this problem every single time now, not like the other day where it would play every second time. So it doesn't play at all anymore (independently of the video.golem.de/download-filter).

**Comment by Alex-302** [comment]
@BlazDT

**Comment by BlazDT** [comment]
Sadly I cannot reproduce. Would need remote access to check.

**Comment by SebastianRasch** [comment]
Yeah we can do that @BlazDT 
Should be easy with iMessage.

**Comment by BlazDT** [comment]
How is Thursday or Friday evening for you (German time)? You can contact me on forum (Blaz).

**Comment by SebastianRasch** [comment]
Yes that can work. I'll try to find you in the forum.

**Comment by BlazDT** [comment]
Disabled rules. Update available in about 3 hours.

**Comment by BlazDT** [comment]
Strangely the same type of rules produced no issues on Computerbild.de As mentioned via iMessage, will disable all the other rules like those as replace rules on .json file is sufficient for those VAST ads.
