### ISSUE TITLE
Missed ads in Ace Stream HD for Windows

### ISSUE THREAD

**Issue by isHrytsai** [AdguardTeam/AdguardFilters#78875]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: 

There are ads for 5-10 seconds on the launch of torrent file viewer called Ace Player. Also there are 5-sec ads when the video is resumed after a pause. HTTPS filtering has been enabled for all Ace components.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](
![image]( https://user-images.githubusercontent.com/73004090/112962652-46ba7200-914f-11eb-9e8a-923bb6a3d64d.png )
)
</details><br/>

* **Expected behaviour**: 

Videos should start and get resumed without ads. 

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Go to Ace Stream website: http://www.acestream.org/
Download the app.
Set HTTPS filtering rules for all its components in ADG Settings > Network > List of filtered apps
Download any torrent video on any tracker 
Run the video with Ace Player 

***System configuration***

**Filters:**

ADG Base Filter, ADG Annoyances Filter, AdBlock warning removal list, I don't care about cookies, Online malicious URL blocklist, ADG experimental filter, ADG Russian Filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Pro
Browser:                               | Ace Stream (app)
AdGuard version:                       | 7.6 Nightly 28
Filters enabled:                       | ADG Base Filter, ADG Annoyances Filter, AdBlock warning removal list, I don't care about cookies, Online malicious URL blocklist, ADG experimental filter, ADG Russian Filter
AdGuard DNS:                           | ADG DoH
Stealth mode options (Windows only)    | disabled

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check this rule:
`.torrentstream.*/get?_*=$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/`

**Comment by Alex-302** [comment]
ок
