### ISSUE TITLE
nemzetiklimavedelmihatosag.kormany.hu

### ISSUE THREAD

**Issue by buhera** [AdguardTeam/AdguardFilters#78896]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
* **Current behaviour**: Adguard filtering problem: cookie acceptance window does not appear

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><a href="https://imgur.com/c6tXEoC"><img src="https://i.imgur.com/c6tXEoC.jpg" title="source: imgur.com" /></a><br/>

* **Expected behaviour**: Disable AdGuard Annoyances filter: cookie acceptance window appears OK

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><a href="https://imgur.com/WK7nwh2"><img src="https://i.imgur.com/WK7nwh2.jpg" title="source: imgur.com" /></a><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** (uBlock Origin) AdGuard Annoyances, AdGuard Base, EasyList, AdGuard Tracking Protection, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list, HUN: hufilter, Anudeep's Blacklist

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Pro 20H2
Browser:                               | Vivaldi 3.7.2218.49 (Stable channel) (64 bites)

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@buhera Do you have this issue on another subdomains?

**Comment by buhera** [comment]
There is no other problem. Thanks!
