### ISSUE TITLE
phimbathu.com - Incorrect blocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7891]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

can't see film picture cover in site.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screen shot 2017-11-25 at 6 50 57 am](https://user-images.githubusercontent.com/31481372/33227549-4705857a-d1ad-11e7-92c7-69d17d76dce5.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.37.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.61 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.21.65 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.24 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.70 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.67 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.79 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.2.88 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.91.76 Enabled=YES
ID=214 Name="ABPVN List" Version=1.0.5.18 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=226 Name="Fanboy's Vietnamese" Version=1.0.0.4 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 
Operating system version (Android/iOS) | 9.1
Browser:                               | Safari
AdGuard version:                       | 1.2.1.71
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1677057

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by bigdargon** [comment]
It's working normal! 
![img_1112](https://user-images.githubusercontent.com/10969626/33228229-b3e4fd16-d1e8-11e7-968f-9155a70925e3.PNG)
