### ISSUE TITLE
doramatv.ru.p.pstl.live - Missed ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#7925]
http://doramatv.ru.p.pstl.live/list/country/thailand?sortType=updated

Missed ads

![image](https://user-images.githubusercontent.com/22892774/33261806-ba168ef4-d36c-11e7-9d8b-f3c47c945ab0.png)

***System configuration***

**Filters:** 1 2 3 4 11 14

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS
Browser:                               | Chrome
AdGuard version:                       | 1.5.0
Filters enabled:                       | 1 2 3 4 11 14
Helpdesk ID (if exists):               | 764270

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
