### ISSUE TITLE
https://c-api-bit.shopeemobile.com/tw/tr

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#79284]
tracker?
https://c-api-bit.shopeemobile.com/tw/tr
https://c-api-bit.shopeemobile.com/ph/tr
```
||c-api-bit.shopeemobile.com/*/tr^
```

https://shopee.ph/
![image](https://user-images.githubusercontent.com/75058881/113475734-f6724580-94a9-11eb-83a1-d31a6ae32a3f.png)

https://shopee.tw/
![image](https://user-images.githubusercontent.com/75058881/113475736-f7a37280-94a9-11eb-93ec-b9e99df9c500.png)

**Comment by Alex-302** [comment]
Need source site.

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/113645455-7d493d00-96b9-11eb-80d7-0d2ce9f411f0.png)
@Alex-302
