### ISSUE TITLE
www.tvcok.ru - Preroll

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7928]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://www.tvcok.ru/film/zvezdnyj-put-diskaveri.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/33274953-2e1e3392-d39a-11e7-933a-2f4dcc61f66f.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.37.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.63 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.60.37 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.79 Enabled=YES

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 10.3.2
Operating system version (Android/iOS) | iOS
Browser:                               | Safari
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None / Default / Family Protection
Helpdesk ID (if exists):               | 1677295

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторяется. Конфигурация аналогичная, iOS такая же.

**Comment by Alex-302** [comment]
Добавил
```
||n1307adserv.xyz^
```
