### ISSUE TITLE
https://50waystogetajob.com/(signup popup)

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#79305]
***Description***: pop for subscription for sign up. 
* **Current behaviour**: 
* 
![image_71](https://user-images.githubusercontent.com/76880977/113482898-5a066e00-94be-11eb-93ce-eaa2248d9c3d.png)

![image_70](https://user-images.githubusercontent.com/76880977/113482892-5377f680-94be-11eb-8410-7a62639765f1.png)

[//]: # (signup popup)

* **Expected behaviour**: no pop up

***Steps to reproduce the problem***:
1. go to site 
2. wait 

***System configuration***
![image_72](https://user-images.githubusercontent.com/76880977/113482955-98039200-94be-11eb-9810-49a47ae7bf08.png)

[//]: # (This template is meant for popup)

**Comment by Alex-302** [comment]
Too few visitors.

**Comment by chirag127** [comment]
Is there any way to find number of visitors on a site.

**Comment by Alex-302** [comment]
I use https://a.pr-cy.ru/github.com/ and https://www.similarweb.com/website/github.com/
But also we look at content.

**Comment by krystian3w** [comment]
Or alexa ranks.
