### ISSUE TITLE
https://vidlox.tv

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7936]
**Site Sample** | 
----|
https://vidlox.tv
https://vidlox.tv/09t82qkrlnre

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.436.2170**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Popups, redirects. ESET blocked `JS/Adware.Serhoxs.A` -`JS/Adware.Serhoxs is an adware - an application designed for delivery of unsolicited advertisements. The program code of the malware is usually embedded in HTML pages.`  (http://www.virusradar.com/en/JS_Adware.Serhoxs.A/description) 

<details><summary><b>Screenshot:</b></summary>

![20171127-192749-001](https://user-images.githubusercontent.com/9846948/33282518-3c8f03de-d3a9-11e7-974a-51d905ef726e.png)
![20171127-192813-001](https://user-images.githubusercontent.com/9846948/33282520-3cb659a2-d3a9-11e7-823b-9ad5eb7736b1.png)
![20171127-192827-001](https://user-images.githubusercontent.com/9846948/33282522-3cda91a0-d3a9-11e7-917a-d1b4c4fcd5cd.png)

</details><br/>

**Comment by AdamWr** [comment]
Fixed.
