### ISSUE TITLE
shopee ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#79468]
shopee.tw
shopee.ph
shopee.**
```
data-sqe="ad"
```
![image](https://user-images.githubusercontent.com/75058881/113520973-18161e80-95c9-11eb-8440-20c6f7921804.png)
![image](https://user-images.githubusercontent.com/75058881/113521052-9b377480-95c9-11eb-8eb4-6369fbcc7bc0.png)

**Comment by Alex-302** [comment]
Just promoted items, related to request.
