### ISSUE TITLE
www.590103.idv.tw/blog - Anti Adblock Script

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#7967]
Issue URL: www.590103.idv.tw/blog — Anti Adblock
Issue Type: Anti Adblock Script
Comment:
AdGuard English filter blocks its Anti-adblock JavaScript.
So it asks to disable adblockers.
Otherwise, we are unable to read articles on his blog.

Screenshot:

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iyvAvFi.png)
</details><br/>

***Steps to reproduce the problem***:
Enable AdGuard English filter and try to read any articles on his blog.

Solution:
Please add the rule in English filter.
@@||590103.idv.tw/advertisement.js$domain=www.590103.idv.tw

Or maybe you have another better rule.

Thanks a lot!

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Adguard driver: | WFP
Browser:                               | Google Chrome v62.0.3202.94
AdGuard version:                       | AdGuard for Windows v6.2.433.2167
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
Stealth mode options (Windows only)    | Enable Stealth mode, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies, Disable cache for third-party requests, Block WebRTC, Block Location API
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
