### ISSUE TITLE
myshows.me пропуск баннера.

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#7971]
На myshows.me через раз начал выскакивать баннер на странице серий над комментами (для примера https://myshows.me/view/episode/1950569/)

![image](https://image.prntscr.com/image/opbUgDOeQiqS2JUo2ZZzwA.jpg)

**Comment by Alex-302** [comment]
поправил

**Comment by Smorvel** [comment]
@Alex-302 и еще справа только что появился. Его тоже убрал?

**Comment by Alex-302** [comment]
3 штуки
