### ISSUE TITLE
9to5mac.com - Incorrect blocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7974]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

https://9to5mac.com/

Убрана навигационная строка (вторая сверху)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/33379940-2655b638-d522-11e7-9d6c-ac1301a6fbfc.png)

![image](https://user-images.githubusercontent.com/31481372/33379945-2b59b652-d522-11e7-84a4-5bd4f0c3a477.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.37.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.66 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.60.37 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.79 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.91.89 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.1.2
Operating system version (Android/iOS) | iOS
Browser:                               | Safari
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1236012

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Уже должно работать.
