### ISSUE TITLE
File Commander app - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#7976]
https://play.google.com/store/apps/details?id=com.mobisystems.fileman&hl=en

![image](https://user-images.githubusercontent.com/22892774/33382217-c929f350-d528-11e7-9105-834e6783e5ec.png)

**Filters:** 1 2 3 4  11 14

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 5.1.1
AdGuard version:                       | 2.10.164
Filters enabled:                       | 1 2 3 4  11 14
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On 
Helpdesk ID (if exists):               | 1674604

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2463 ?
