### ISSUE TITLE
AdGuard Base filter prevents javascript user rule from executing. 

### ISSUE THREAD

**Issue by SebastianGrans** [AdguardTeam/AdguardFilters#79855]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
AdGuard Base filter blocks javascript user rule from running on Wikipedia (and possible other places) 

* **Current behaviour**: 
With AdGuard Base filter *enabled*.  
Specify the following user rule:
```javascript
wikipedia.org#%#console.log("Hello, world!");
```
Visit a random wikipedia page an look at the js console: 
<img width="539" alt="Screen Shot 2021-04-08 at 16 33 08" src="https://user-images.githubusercontent.com/10030015/114045720-889e9300-9888-11eb-94f2-bb5e067fcab4.png">

No log message visible. 

* **Expected behaviour**: 
Now disable the base filter, open a new tab and visit another random wikipedia page: 
<img width="468" alt="Screen Shot 2021-04-08 at 16 35 18" src="https://user-images.githubusercontent.com/10030015/114045953-b8e63180-9888-11eb-8c7b-a8675871167c.png">

Log message is there! As expected. This is a basic example, but any kind of user rule javascript is blocked from running.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***Steps to reproduce the problem***:
See above. 

**Filters:**
 * AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal List, I don't care about cookies, Filter unblocking search ads and self-promotion

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  MacOS Bug Sur
Operating system version (Android/iOS) | 11.2.3
Browser:                               | Safari 14.0.3 
AdGuard version:                       | 1.8.10
Filters enabled:                       | See above. 
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I guess it's related to this issue - https://github.com/AdguardTeam/AdGuardForSafari/issues/484#issue-762927459
>JS rules are disabled by $generichide exception.

There is `@@||wikipedia.org^$generichide` in Base filter and it causes that javascript rules don't work.
You can try to add to user filter:
`@@||wikipedia.org^$generichide,badfilter`
and javascript rules should working fine.

**Comment by SebastianGrans** [comment]
That worked great! 
Thanks for the lightning fast answer as well :)
