### ISSUE TITLE
Rabb.it doesn't work

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#7990]
@Bluscream commented on [Wed Nov 22 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2021)

### Steps to reproduce

1. Go to any rabb.it room (for example https://www.rabb.it/Bluscream349)
2.  Load a website

### Expected behavior

The screen shows the content of the livestream.

### Actual behavior

The area stays black

<details><summary>Screenshot:</summary>

![grafik](https://user-images.githubusercontent.com/3318223/33148443-379d7f44-cfcc-11e7-97f7-1391cd5acd0b.png)

</details>

### Customer ID 

got no mail back so far

1326210
--

### Your environment

* Environment name and version (e.g. Chrome 59):
* Operating system and version (e.g. Windows 10, v.1703, build 15063.413)
Microsoft Windows [Version 10.0.15063]
Firefox 57.0 (64-bit)

---

@Bluscream commented on [Wed Nov 22 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2021#issuecomment-346466363)

I think it needs to be in the stealth whitelist cuz of webrtc
but that makes no sense cuz i already have that in my user filter:
```js
@@||rabb.it^$important,document,~extension,stealth
```

compeletely disabling webrtc blocker allows the audio to load but not the video

---

@ameshkov commented on [Thu Nov 30 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2021#issuecomment-348193434)

@zebrum should be moved to the Adguardfilters

**Comment by Alex-302** [comment]
@AdamWr please check this issue. I have no web cam.

**Comment by AdamWr** [comment]
@Alex-302 I don't have web cam too.

**Comment by Alex-302** [comment]
@vozersky can you reproduce this issue?

**Comment by zebrum** [comment]
reproduced

**Comment by Bluscream** [comment]
Yeah webcam is not the problem, the screen stream itself stays black ^^

**Comment by ameshkov** [comment]
> Maybe problem is that, stun requests are blocked even when

Blocking WebRTC is somewhat too rough.

It seems that we need a `$network` exception to unblock that.

**Comment by ameshkov** [comment]
Do they use their own STUN server or is it something public?

**Comment by Bluscream** [comment]
[Archive 17-12-04 00-37-05.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1525284/Archive.17-12-04.00-37-05.har.zip)
<details><summary>pw</summary>agwin</details>

**Comment by BlazDT** [comment]
@ameshkov @AdamWr any news?

**Comment by ameshkov** [comment]
@BlazDT you can see the STUN request on Adam's screenshot:
https://github.com/AdguardTeam/AdguardFilters/issues/7990#issuecomment-348216781

What you need to do is add a `$network` type of exception rule and unblock that IP

**Comment by Bluscream** [comment]
Had to go with `@@216.*.*.*$network` because rabb.it owns too many ip ranges

**Comment by ameshkov** [comment]
Hm, that'd be too much, really.

Could you please check who this IP belongs to?

**Comment by BlazDT** [comment]
So far I found this list (without inject exclusion I was redirected to main page - all generic #%# were disabled though):

```
@@||rabb.it^$jsinject
! A100 Row Gmbh
@@18.195.48.249:3478$network
! A100 Row Gmbh
@@18.195.48.250:3478$network
! Rabbit Inc
@@216.66.6.33:48047$network
@@216.66.6.33:52603$network
@@216.66.6.33:56185$network
@@216.66.6.33:58170$network
! Hurricane Electric Llc
@@216.66.71.25:35146$network
@@216.66.71.25:37603$network
@@216.66.71.25:43254$network
@@216.66.71.25:48971$network
@@216.66.71.25:49441$network
@@216.66.71.25:57449$network
```

**Comment by Bluscream** [comment]
I'll try next time i use it

**Comment by BlazDT** [comment]
@ameshkov 
The complete rule is ignored if $stealth is in the rule it seems as jsinject above got also ignored. Looks like a little bug to me.

**Comment by ameshkov** [comment]
> The complete rule is ignored if $stealth is in the rule it seems as jsinject above got also ignored. Looks like a little bug to me.

The `$stealth` modifier cannot be accompanied by other whitelist modifiers, that's just how it works.
