### ISSUE TITLE
stolicazdrowia.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7999]
**Site Sample** | 
----|
https://www.stolicazdrowia.pl

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.436.2170**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Adblock detect after while during scrolling window 

<details><summary><b>Screenshot:</b></summary>

![20171130-170109-001](https://user-images.githubusercontent.com/9846948/33440380-1be8a72c-d5f0-11e7-93ad-5023c9107ecd.png)

</details><br/>

CC @AdamWr

**Comment by AdamWr** [comment]
Fixed.
