### ISSUE TITLE
Add sgcpanel.com to white list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#800]
Look here for details:
http://www.wilderssecurity.com/threads/adguard-ad-blocker.342850/page-51#post-2529673

**Comment by Alex-302** [comment]
excluded
@@||sgcpanel.com^$document
but I can't access to this site ("Webpage not available")

**Comment by ameshkov** [comment]
It's ok, the actual panels are on subdomains.
