### ISSUE TITLE
technews.tw antiadblocker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80024]
https://technews.tw/2021/04/08/virtual-particle-muon-magnetic-moment/
```
technews.tw###secondary > div.AD_wrapper:nth-child(2)
```

**Comment by wout-codes** [comment]
Is AdGuard Annoyances Filter enabled?

**Comment by c2xusnpq6** [comment]
> Is AdGuard Annoyances Filter enabled?

No. Because I need those third-party tools

**Comment by wout-codes** [comment]
It's already fixed in AdGuard Annoyances Filter. Enable it and update.
