### ISSUE TITLE
Ads on "My feed" in Edge

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#80149]
Please check if we can do smth about that.

<details>

![image](https://user-images.githubusercontent.com/15856304/114296839-14e1cd80-9ab6-11eb-948c-603168d264a6.png)

![image](https://user-images.githubusercontent.com/15856304/114296856-23c88000-9ab6-11eb-8f0b-dc350b64f195.png)

</details>

The config is the exact same as here https://github.com/AdguardTeam/AdguardFilters/issues/71534 
MS Edge v. 89.0.774.68

**Comment by BlazDT** [comment]
Already being worked on:
https://github.com/AdguardTeam/AdguardFilters/issues/80044
