### ISSUE TITLE
doz.pl android app content issue

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#80224]
APP: https://play.google.com/store/apps/details?id=pl.looksoft.doz&hl=pl&gl=US
ISSUE: Not display content when domain is blocked.
SOLUTION:
```
@@||wrap.tradedoubler.com^$third-party,domain=doz.pl
```

NOTE: I cannot make screenshots - app denied this. 

EDIT: removing `important`.

**Comment by krystian3w** [comment]
`Important` works with `@@||`

?

**Comment by FadeMind** [comment]
@krystian3w miałem opcję w kreatorze to dodałem. Sprawdzę bez.

**Comment by krystian3w** [comment]
AdamWr jak nie działa opcja to pozgłaszasz by dla dopuszczeń usuwnęli zaznaczenie "wymyś moc reguły".

No chyba, że zaimplementujecie, że dopuszczenie ma wygrywać z regułą blokującą:

`||wrap.tradedoubler.com^$third-party,domain=doz.pl,important

co raczej sensu nie ma - taki się dezaktywuje z pomocą `badfilter`.

**Comment by FadeMind** [comment]
@krystian3w bez `important` też działa. W kreatorze reguł masz `nadaj wyższy priorytet` i to dodaje `important` do reguły białej listy.

**Comment by krystian3w** [comment]
W takim razie dobrze by było zrobić ukrywanie tej opcji np. wyszarzenie pola lub całkowite znikanie linii.

Bardzo opcjonalnie, że zaznaczanie nie dokleja błędnych modyfikatorów (tak robi uBO, bo raczej nikt nie ma ochoty na kolejny JS wykrywający czy w polu przed jest z listy zaznaczone "dopuść").

**Comment by FadeMind** [comment]
@krystian3w przykład użycia kreatora
![Screenshot_2021-04-12-10-06-34-741_com adguard android](https://user-images.githubusercontent.com/9846948/114361826-eb3cab00-9b76-11eb-9431-864588ff56f4.jpg)

**Comment by AdamWr** [comment]
@FadeMind Zainstalowałem tę aplikację, ale nie potrafię tego odtworzyć.
Mógłbyś proszę napisać w jaki konkretnie sposób odtworzyć ten problem?

>@@||wrap.tradedoubler.com^$third-party,domain=doz.pl

Ta reguła jest dla strony internetowej, nie powinno tam być `app=pl.looksoft.doz` zamiast `domain=doz.pl`?

**Comment by FadeMind** [comment]
Zgłupiałem xD

Teraz jak odpalam apkę z wyłączoną regułą *tradedoubler* to po prostu działa :v Ewentualnie wina VECTRY, która po swojej stronie czasami odwala manianę z niedostępnością serwerów. 

To nie zmienia faktu, że kreator białej listy ma błąd logiczny- skoro używa important zamiast badfilter. 

Minęło kilka dni od zgłoszenia, więc zwalam winę na ISP. Wybaczcie zamieszanie xD

**Comment by krystian3w** [comment]
A może kombinacja obu.


jakby to była nakładka na przeglądarkę to może i to ruszy dla filtrów kosmeyczynych https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#non-basic-rules-modifiers

**Comment by krystian3w** [comment]
Czyli jakiś tam error z DNS aplikację zadowala a echo/pogłos ciszy z AdGuard już be.

**Comment by AdamWr** [comment]
W AdGuardzie `important` może być używany zrówno do reguł blokujących, jak i w wyjątkach.
```
||example.org^$important
@@||example.org^$important
```
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#important

>Minęło kilka dni od zgłoszenia, więc zwalam winę na ISP. Wybaczcie zamieszanie xD

Okej, w takim razie myślę, że można to zamknąć.
Dziękuję za odpowiedź.
