### ISSUE TITLE
Flubot (Android Malware)

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/AdguardFilters#80229]
VT ->
https://www.virustotal.com/gui/file/88527fb710478e1c54c6540fd15c0734bee1c4d1724abefcb84d7fa4102b8411/detection

qoisocrldvnesni.ru
xawsnngjljanxof.su
bdvwidxfiextwof.ru
krvpsegjeukhoqk.su
auqcmkubxjmeeyf.ru
vloxaloyfmdqxti.ru

**Comment by Alex-302** [comment]
@scafroglia93 please provide download link. We will block network for it.

**Comment by scafroglia93** [comment]
I struggle to give you the site as it is a DGA; changes with each download request

**Comment by Alex-302** [comment]
We can block these domains. But what makes requests to these domains? What is DGA?

**Comment by scafroglia93** [comment]
DGA Reference ->
https://en.m.wikipedia.org/wiki/Domain_generation_algorithm

It's very hard to find all domain used

Il mar 13 apr 2021, 13:54 Alex ***@***.***> ha scritto:

**Comment by Alex-302** [comment]
What is the source of that domains? Which app made requests?

**Comment by scafroglia93** [comment]
APK ->
https://www.virustotal.com/gui/file/88527fb710478e1c54c6540fd15c0734bee1c4d1724abefcb84d7fa4102b8411/detection

**Comment by Alex-302** [comment]
I need APK download link, not virustotal.

**Comment by scafroglia93** [comment]
http://youthvision.cn/track/

This is one but there are tons of this

Il giorno mer 14 apr 2021 alle ore 13:12 Alex ***@***.***> ha
scritto:

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/114709984-e40fcb80-9d35-11eb-8726-3e5ca954a04d.png)

**Comment by scafroglia93** [comment]
try with mobile (android)

Il giorno mer 14 apr 2021 alle ore 14:27 Alex ***@***.***> ha
scritto:

**Comment by scafroglia93** [comment]
That's all !

https://github.com/prodaft/malware-ioc/tree/master/FluBot

https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.7_5000_domain.txt
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.7_germany.txt
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.8_domains.txt
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.9_italy.txt

**Comment by Alex-302** [comment]
Uh, that files are made from dead domains(at the moment)

**Comment by scafroglia93** [comment]
It can happen, especially if domains generated by some algorithm are used.

This makes blocking at the dns level complicated

**Comment by scafroglia93** [comment]
this is the latest update from italian cert ->
https://cert-agid.gov.it/wp-content/uploads/2021/04/flubot_ioca_cert-agid_19-04-2021.json_.txt

**Comment by Alex-302** [comment]
They create one file, which contains all domains. You can add it to AdGuard home or another blocker.
https://github.com/prodaft/malware-ioc/issues/1

**Comment by GewoonJaap** [comment]
https://flubot.mrproper.dev/
Here is a list with URLs, flubot APK is not downloaded from DGA domains AFAIK, the DGA is used once the APK is installed.

**Comment by scafroglia93** [comment]
> https://flubot.mrproper.dev/
> Here is a list with URLs, flubot APK is not downloaded from DGA domains AFAIK, the DGA is used once the APK is installed.

The phenomenon has arrived

rather it tries to create a file containing the domains to be blocked instead of writing meaningless sentences

**Comment by GewoonJaap** [comment]
> > https://flubot.mrproper.dev/
> > Here is a list with URLs, flubot APK is not downloaded from DGA domains AFAIK, the DGA is used once the APK is installed.
> 
> The phenomenon has arrived
> 
> rather it tries to create a file containing the domains to be blocked instead of writing meaningless sentences

What do you mean? In the footer is a free API that lists the URL's. If you want, I can try and make this into a adblocker ready filter list, if that is what you mean?

**Comment by Alex-302** [comment]
@GewoonJaap Hi. I didn't understand your previous message. That domains are actual flubot's domains? DGA does not cover all cases?

**Comment by GewoonJaap** [comment]
Hey @Alex-302 ,
This is true. The domains used to spread flubot are mostly hacked PHP websites, the once flubot is downloaded, it Will contact the command and control servers which use DGA domains.

**Comment by GewoonJaap** [comment]
So all the URL's you see on my website are domains used to host the .apk file for flubot

**Comment by GewoonJaap** [comment]
When you open inspect element/devtools, set your window to a android phone so you can visit those hacked sites

**Comment by scafroglia93** [comment]
https://flubot.mrproper.dev/item

can you create a list with only domain ?

**Comment by Alex-302** [comment]
@GewoonJaap Ok. Could you please add that domains to some file which can be downloaded by AdGuard Home or another DNS filters? Are that domains not static, changed from time to time?

**Comment by scafroglia93** [comment]
No response, closed
