### ISSUE TITLE
#3444 still hasn't fixed

### ISSUE THREAD

**Issue by TemaZosin** [AdguardTeam/AdguardFilters#8024]
Check again #3444. I dunno why you can't normal check but your screenshots are not correct. You should short any link first by site tmxc.ru and after you will get the page with problem. Don't try to open /create.php first coz on your screenshots we can see error message about "short first".

**Comment by TemaZosin** [comment]
You can also check the same problem on http://uto.wm-scripts.ru/

**Comment by Alex-302** [comment]
use reporting tool
https://reports.adguard.com/new_issue.html
