### ISSUE TITLE
9to5mac.com - Incorrect blocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8025]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Incorrect blocking on page:
https://9to5mac.com/

On 9to5 mac mobile page the menu bar on the top is missing

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/33510945-7cfd5702-d71b-11e7-9d44-56b28f220f5c.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.37.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.79 Enabled=YES
ID=101 Name="EasyList" Version=1.0.77.75 Enabled=YES
ID=224 Name="Korean Adblock List" Version=1.0.0.7 Enabled=YES
ID=227 Name="List-KR" Version=1.0.3.51 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.1.2
Operating system version (Android/iOS) | iOS
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          | On 
Helpdesk ID (if exists):               | 1680450

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce this issue.
It is related to this - https://github.com/AdguardTeam/AdguardFilters/issues/7749 and it was fixed here - https://github.com/AdguardTeam/AdguardFilters/commit/5f2f7aac001d824c54efca13de117a72009545fd
