### ISSUE TITLE
https://www.reddit.com/ - Missed ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8027]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/33511626-90d314e6-d726-11e7-9811-340dcd3d5411.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.3 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.34 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.86 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.87.50 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.69 Enabled=YES
ID=234 Name="ROLIST2" Version=1.0.0.2 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.89.57 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=230 Name="FanboyEspanol" Version=1.0.0.3 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 10.3.3
Operating system version (Android/iOS) | iOS
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1574318

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Can't reproduce, on my end it's hidden by this rule:
`reddit.com##.NavFrame > .DualPartInterstitial`
