### ISSUE TITLE
xunlei windows client tracker stat.download.xunlei.com

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80332]
`stat.download.xunlei.com`

https://www.virustotal.com/gui/file/ab48d2e3a4b6947d5502ea47d9806ad8c7470de36c4b481b894a024401e04ce2/behavior/VirusTotal%20Jujubox
![image](https://user-images.githubusercontent.com/75058881/114553758-909b7000-9c98-11eb-9830-1f6d08458ba3.png)

https://www.virustotal.com/gui/file/5bf4f46258b4463c81a78e4b4963a0e11d378d78ce8d88cfbe289593d0236a6a/behavior/VirusTotal%20Jujubox
![image](https://user-images.githubusercontent.com/75058881/114553804-9db85f00-9c98-11eb-9753-1a55667c3867.png)

**Comment by chirag127** [comment]
@c2xusnpq6 how do you know that it is a tracker.
