### ISSUE TITLE
hdrezka.ag - Incorrect blocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8037]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Пропущена реклама на странице:
http://hdrezka.ag/series/action/1871-zvezdnyy-put-enterprayz.html#t:84-s:1-e:1

После похода на форум было добавлено свое правило, но видео начало прерываться. 
Также, в ряде случае реклама блокируется частично, остается звук от рекламного ролика, который пропадает при повторном нажатии на Play. 

**Ссылка за запись экрана** https://www.icloud.com/iclouddrive/0kTlj_ovvHsMlI-LCo75uCaNQ#ScreenRecording_11-26-2017_01.29

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.1.2
Operating system version (Android/iOS) | iOS
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1656409

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторяется. Английский фильтр её блокирует. С воспроизведением видео тоже нет проблем. iOS 10.3
