### ISSUE TITLE
tracker bilanx.dcard.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80386]
`||bilanx.dcard.tw^$app=com.sparkslab.dcardreader`
if you block the whole `bilanx.dcard.tw` domain, it will break the web version `dcard` https://dcard.tw/ , but it won't affect `dcard` android app

**Comment by c2xusnpq6** [comment]
@Alex-302 @Yuki2718 i told you.... it will break the website if you block the whole domain, but same feature, android still can work... it seem that the android app won't rely the request resonpon (noob eng T.T

**Comment by c2xusnpq6** [comment]
so.... in case some user browse dcard via browser, not via the app, you may want to add: `$app=com.sparkslab.dcardreader` (idk the ios version)
so.............. `||bilanx.dcard.tw^$app=com.sparkslab.dcardreader` this!!!

**Comment by c2xusnpq6** [comment]
why I so want it to be.... block the whole domain.... because the app uses `https`
so if you want more privacy, u must use this: `||bilanx.dcard.tw^$app=com.sparkslab.dcardreader` broooooooooo ok?

**Comment by Alex-302** [comment]
added
