### ISSUE TITLE
Am I possible to block IP range like /24 /16?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80389]
```
202.128.224.0/19$network
```
Is this gonna work on `Adguard Windows`, `Adguard Android` and `Adguard Chrome`? thx!~

**Comment by Alex-302** [comment]
No.
Only like 
202.128.224.*
202.128.*
202.*
etc.

**Comment by c2xusnpq6** [comment]
then pls support that... thx

**Comment by c2xusnpq6** [comment]
@Alex-302 @AdguardTeam
