### ISSUE TITLE
HK gov covid app tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80384]
The Hong Kong government claims that the application will not connect to the Internet, but Hong Kong people are still worried (google translate~~ T.T
```
leavehomesafe.gov.hk/site.json
||app.regqr.gov.hk^
||app1.regqr.gov.hk^
||app2.regqr.gov.hk^
||www1.regqr.gov.hk^
||www2.regqr.gov.hk^
regqr.gov.hk/app
202.128.226.49$network
202.128.226.161$network
$app=hk.gov.ogcio.leavehomesafe
```

https://www.leavehomesafe.gov.hk/site.json
![image](https://user-images.githubusercontent.com/75058881/114656453-b53b2a80-9d20-11eb-9b49-ce7bab9c7ddf.png)
![image](https://user-images.githubusercontent.com/75058881/114656711-2549b080-9d21-11eb-97bc-5beaeab749a0.png)

reference:
https://blog.headuck.com/2021/02/18/%E3%80%8C%E5%AE%89%E5%BF%83%E5%87%BA%E8%A1%8C%E3%80%8D%E8%83%BD%E5%90%A6%E5%AE%89%E5%BF%83%E4%BD%BF%E7%94%A8%EF%BC%9F%EF%BC%88%E5%9B%9B%EF%BC%89/

https://www.leavehomesafe.gov.hk/tc/

https://www.facebook.com/AFewWordsFromLeo/posts/%E4%BB%8A%E6%97%A5%E9%80%A3%E7%99%BB%E4%BB%94%E5%B7%B2%E7%B6%93%E6%9C%89%E5%80%8B-post-%E9%A0%97%E8%A9%B3%E7%B4%B0%E5%92%81%E6%8B%86%E8%A7%A3%E5%AE%89%E5%BF%83%E5%87%BA%E8%A1%8Capp%E6%89%80%E4%BB%A5%E5%A4%A7%E5%AE%B6%E7%9B%B4%E6%8E%A5%E5%8E%BB%E7%9D%87%E5%95%A6httpslihkgcomthread2287615page1-%E6%88%91%E6%B7%A8%E4%BF%82%E6%83%B3%E5%96%BA%E5%BA%A6%E8%A3%9C%E5%85%85%E5%B0%91%E5%B0%91%E5%80%8B/709212343045008/

https://play.google.com/store/apps/details?id=hk.gov.ogcio.leavehomesafe

**Comment by c2xusnpq6** [comment]
https://github.com/c2xusnpq6/anticult_list/
![image](https://user-images.githubusercontent.com/75058881/114664808-d1de5f00-9d2e-11eb-9daf-323d29263592.png)
https://github.com/c2xusnpq6/anticult_list/raw/main/leavehomesafe_tracker_advanced.txt

**Comment by Alex-302** [comment]
Not sure if something must be blocked here.

**Comment by c2xusnpq6** [comment]
> Not sure if something must be blocked here.

reopen pls
