### ISSUE TITLE
[blocklist] Formbook Malware

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/AdguardFilters#80390]
- https://tria.ge/210413-f55xlkqvws

- https://app.any.run/tasks/3f168845-f797-4e34-9e4a-30e5a7f7c43f

- https://www.hybrid-analysis.com/sample/5fef6e5e702f6ac33542c50d34d3054d1b957c3afd5dffc8fbeaa81d82fdf562/6076259ba8ede771b62e5a86

- https://www.joesandbox.com/analysis/386358/0/executive
firstblognew123.blogspot.com
getyournewblog.blogspot.com
newblogheresee.blogspot.com
newblogset144.blogspot.com
papagunnakjdnmwdnwmndwm.blogspot.com
238olive.com
665asilo.com
1000-help6.club
4515a.com
100973671.review
adsmat.com
afternoontravel.site
agnostec.com
algoritas.com
alinkarmay.com
alkiefsaudi.com
amazon-service-app-account.com
amymako.com
another-sc.com
ap-333.com
aprilmarieclaire.com
artcode-software.com
artebythesea.com
avantfarme.com
ayescarrental.com
banejia.com
barryteeling.com
belenusadvisory.net
bellee-select.com
benficalovers.com
betteringthehumanexperience.xyz
beyoutifulblessings.com
bizcert360.com
boiler-portal.com
buildnextfrc.com
camelliaflowers.space
champsn.com
chienluocmarketing.net
china-ymc.com
citestaccnt1597691130.com
clickqrcoaster.com
cname.landingi.com
coffeyquiltco.com
colinboycemp.net
constipationhub.com
contecoliving.com
courtneyrunyon.com
cruiseameroca.com
deerokoj.com
doctorsdietgulfport.com
ebitit.com
esdras-almeida.com
esrise.net
esseneceedibles.com
ezcovid19.com
fairisnotfair.com
fangyu5827.com
fasoum.com
findmyautoparts.com
finestfaux.com
flawlessdrinking.com
frontrangetechnologies.com
grandpaurbanfarm.net
greenbelieve.com
greenstavern.com
guide4idiots.com
gyrostoyou.com
hauteandcood.com
heritagediscovery.net
heritageivhoa.com
hnzywjz.com
holdergear.com
holisticpacific.com
houseof2.com
identityofplace.com
issue72-paypal.com
jonathantyar.com
klinku.com
littner.xyz
livinoutthedreamsco.com
lovewillfindaway.net
lownak.com
metabolytix.com
microsoftpods.com
middlehambooks.com
midollan.com
mirrorsmarbella.com
nashvillegems.com
neopivot.com
norastravel.com
northernlsx.com
nyariorganics.com
ohrchadash.com
okque.com
oouuweee.com
packtmall.com
podcastyourvote.com
ponorogokita.com
protocolmodern.com
pubgfrut.com
qzhongkong.com
restoremyorigin.com
retrievingbest.net
riceandginger.com
robertabraham.com
royermaldonado.com
sapanyc.com
sgsnit.com
shopyourgift.com
shpwmy.com
singlebarrel.net
snowandmotion.com
stainlesslion.com
suafrisolac.com
supportserverhotline23.info
team5thgroup.com
tententacleshydro.com
themodernspiritualgoddess.com
thepowersinyou.com
theweddingofshadiandmike.com
tinymodeldiana.com
tourbuzz.net
ultraprecisiondata.com
unlock-motorola.com
v-travelclub.com
validdreamers.com
wbz.xyz
wealthtruckingco.com
whitetreechainmail.com
woodandresin.club
wzocflfor.com
xyfs360.com
yaxett.net
yowoit.com
yuksukcu.club
zahidibr.com

**Comment by scafroglia93** [comment]
There are taken from my work email (spam section)

**Comment by lolka4toli** [comment]
Blacklisted.
