### ISSUE TITLE
[Android] - Racing Fever in-app ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#804]
http://imgur.com/E9kzKMh
https://play.google.com/store/apps/details?id=mobi.gameguru.racingfever
PLZ-218-99187

**Comment by Alex-302** [comment]
Added some rules for other game. User should to update the filters, clear game cache and try again.

**Comment by vbagirov** [comment]
Didn't help. Requested HTTP requests log.

**Comment by Alex-302** [comment]
Нужна поддержка HTTPS. Пока закрываю.
