### ISSUE TITLE
Missing ads in Korean ALYac Antivirus on Windows

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardFilters#80447]
@isHrytsai commented on [Mon Apr 12 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3747)

There's a Korean Antivirus software called ALYac that injects its ads into its interface and (possibly) into Windows notifications. 
See the links here: 
(KOR) https://www.estsecurity.com/public/product/alyac
(ENG) https://en.estsecurity.com/product/alyac

### Steps to reproduce

1. Install and the software
2. Behold the ads

### Expected behavior

The software should be executed with no ads in it.

### Actual behavior

The software shows ads in its interface and in Windows notification area.

<details><summary>Screenshot:</summary>

 ![image](https://user-images.githubusercontent.com/73004090/114385439-b80b1380-9b98-11eb-8f1b-7bfefbe9173a.png)

 ![image](https://user-images.githubusercontent.com/73004090/114385472-c0634e80-9b98-11eb-8ee3-da8a4fc9d35a.png)

</details>

### Customer ID 

Ticket number: 501476

### Your environment

* Operating system and version: (Windows 10 Pro, v.2004, build 19041.868)

---

@Aydinv13 commented on [Tue Apr 13 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3747#issuecomment-818692531)

@isHrytsai Hi there!
Follow these steps, please:
1. Download the `.txt` file below.
2. Open AdGuard-> Settings-> Ad Blocker tab->Filter Editor.
2. Add a new filter (a cross in the lower left corner).
3. Choose the path to the file you downloaded.
[adguard_user_filter.txt](https://github.com/AdguardTeam/AdguardForWindows/files/6303584/adguard_user_filter.txt)

It must help as a temporary solution. We'll try to improve ad blocking in this area

**Comment by Sergey-Lyapin** [comment]
@piquark6046 could you please check? I can't install on Windows for some reasons, I'll check tomorrow too on Mac

**Comment by piquark6046** [comment]
![Screenshot](https://user-images.githubusercontent.com/37463155/114844075-fd625780-9dc9-11eb-8aaa-15258c1a2d20.png)
Installed successfully.

**Comment by Sergey-Lyapin** [comment]
@piquark6046 
I was able to install the program, I clicked wrong button =) I'm sorry to bother you.

**Comment by piquark6046** [comment]
`||data.news.zumst.com/alyac/popular` :  Annoyance
`||displayad.zum.com^` `121.189.38.123^$network` : Ad
