### ISSUE TITLE
dcard.tw tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80488]
```
||dcard.tw/service/api/v2/stories/*/view^
```
https://www.dcard.tw/f/fju
These will trigger and send an HTTP request when you have finished viewing the picture and have logged in
![image](https://user-images.githubusercontent.com/75058881/114821351-061b5380-9df3-11eb-8ddf-595f3d8a0346.png)

**Comment by Alex-302** [comment]
Cannot reproduce.
