### ISSUE TITLE
I'd Like To Report CNAME Trackers But Need Some Help

### ISSUE THREAD

**Issue by SeparateAd7322** [AdguardTeam/AdguardFilters#80491]
Hello, I was reading your post about cname trackers (https://github.com/AdguardTeam/cname-trackers)

and it says: **"it’s hard to imagine someone would check the whole web in search for CNAME-cloaked trackers."** 
I accept that challenge!

But I do need a little help, I'm using Firefox with the uBO logger to find and view the cname's, but how do tell the difference between a normal cname and a "cloaked" one? I know some are required to view images for example. 

And also, (this may tie in with my question) but I noticed that some of the trackers that you guys block I don't see pop up on uBO's logger? What do you use to view what loads on a page?

**Comment by krystian3w** [comment]
Maybe AdGuard Home show cname invisible in uBO logger.

**Comment by Yuki2718** [comment]
@SeparateAd7322 Hi, we appreciate your good intention very much! In uBO logger, cloaked requests will be shown in blue color so you can tell if it's CNAME cloak or not, assuming the request is not blocked by a rule targeting it self (i.e. already known CNAME tracker). Not all CNAME tracker in the list are actually used in the wild, also note CNAME tracker is sometimes dependent on what stub resolver you use. I usually check with CleanBrowsing and ISP DNS, sometimes also Cloudflare.

**Comment by Yuki2718** [comment]
Another way which may or may not work is - search engine(s). Search for various related words such as "DNS", "ITP", "CNAME", "first party" in your mother tongue might reveal a few company engaging in CNAME tracking. I found ebis and a8 CNAME tracker in this way.

**Comment by SeparateAd7322** [comment]
Hi and thank you guys for the response!

So if I'm reading this right, uBlock makes its really easy to find cloaked requests?

If that's the case, I believe I found a lot on these sites. Are any of these the trackers the article was talking about?

[NSFW]
`https://www.aznudes.com`
`https://www.pornmd.com/straight/porn?response!`

**Comment by Yuki2718** [comment]
@SeparateAd7322 
I see `aznude.com` is a CNAME of `stackpathcdn.com` and `pornmd.com` of `rncdn7.com`; however, these are not tracker. CNAME itself is not for tracking and used on various sites, but the thing is some tracking company abuse this system. So you have to look for what are blocked only by CNAME uncloaking - in uBO logger shown in blue character AND red row.

**Comment by Alex-302** [comment]
Please create new issues to report about missed trackers(with source sites)
