### ISSUE TITLE
nnm.me

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#805]
Ads in background

http://nnm.me/brand/nnm_branding.png

ORD-352-12356

**Comment by Alex-302** [comment]
Добавил
||nnm.me/brand/
Пусть отпишется

**Comment by Bohdan-SUP** [comment]
Вот такое появилось:
http://prntscr.com/a32ybd
IAM-663-78850

**Comment by Alex-302** [comment]
Это nnm-club.me, и сейчас там чисто.

**Comment by vgavrish** [comment]
Андроид
nnm.me
на главной: http://prntscr.com/blkc7c

**Comment by Alex-302** [comment]
Поправил.

**Comment by vgavrish** [comment]
ВИН. программа. вулкан на фоне
фильтры: 1,2,3,4,14
IE, chrome
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19218373/ce5910d8-8e00-11e6-9b1e-b05f11de97cc.png)

**Comment by Alex-302** [comment]
Fixed.

**Comment by Bohdan-SUP** [comment]
Ads are back:
![screen shot 2017-04-18 at 15 45 17](https://cloud.githubusercontent.com/assets/14153331/25131369/22385dd8-244e-11e7-8a6e-3994e0d7311d.png)

Filters:
![image](https://cloud.githubusercontent.com/assets/14153331/25131401/43c9b7c6-244e-11e7-9918-ce27f8311445.png)

**Comment by Alex-302** [comment]
Fixed.
