### ISSUE TITLE
shopee tracker ( shopee.* & shopee.com.* )

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80609]
seller.shopee.ph --> `seller.shopee.*/api/collection/csp_report`

`shopee.*`:
seller.shopee.tw
seller.shopee.ph
seller.shopee.sg

`shopee.com.*`
seller.shopee.com.my
seller.shopee.co.id

```
seller.shopee.*/api/collection/csp_report
or
seller.shopee.*/api/collection/* ?
```

![image](https://user-images.githubusercontent.com/75058881/115001232-11937b00-9ed6-11eb-87b0-588921256c73.png)

![image](https://user-images.githubusercontent.com/75058881/115001535-50c1cc00-9ed6-11eb-88d8-91f6d89d2854.png)

**Comment by Alex-302** [comment]
Not a tracker.

**Comment by c2xusnpq6** [comment]
@Alex-302 or this one?? https://github.com/easylist/easylist/commit/6c0e456853c4f78c37dd6c50502e7552ec66e57b
