### ISSUE TITLE
xnxx.com [NSFW]

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#80626]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

`https://www.xnxx.com/video-ynq4v0f/ein_junger_schuler_lutscht_einen_neuen_lehrer`

***Description***: popup when i click on another video. After the popup the site placing a cookie with the content: `wpn-popupunder = 1`

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.5.34
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Yuki2718** [comment]
I can't reproduce.
