### ISSUE TITLE
tracking on multiply sites

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#80625]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Tracking on `https://tweakers.net` coming from `https://tweakers.net/x/scripts/min/UklYkl.js` (randomized script it changes every day) and tracking 1x1 pixel coming from `https://tweakers.net/406025085368687/wt0nuy_a_zshiu?cg2=Frontpage&one=1&eid=2161857506191250991&cs3=Geen&p=445,tweakers_net.,1,2560x1440,24,1,1618575061728,1,1284x998,0&np=&cg1=tweakers.net&fns=1&la=de&pu=https%3A%2F%2Ftweakers.net%2F`

tracking on `https://noen.at` coming from `https://tracking.noen.at/track.js?cachebuster=1`

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.5.34
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany + Dutch filter (activated by AdGuard)
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
The filter doens’t cover all `https://tweakers.net/x/scripts/min/1gnp75X.js` is unblocked.

It is possible to use a scriptlet to break the Webtrekk stuff on this site when its not possible to block the script with a regex?

**Comment by Yuki2718** [comment]
@JobcenterTycoon 
```
tweakers.net#%#//scriptlet('abort-on-property-read', 'WebTrekkClickMap')
tweakers.net#%#//scriptlet('abort-on-property-read', 'snowplow')
```
work on my end.

**Comment by JobcenterTycoon** [comment]
Good no tracking script requests now. But please add a filter for uBlock Origin too to block the tracking on both Adblocker

**Comment by Yuki2718** [comment]
@JobcenterTycoon Can you confirm no breakage?

**Comment by JobcenterTycoon** [comment]
No breakage for me. Im checked: Cookie banner, articles, creating an account, loggin in, comment, video (its just youtube)

**Comment by Yuki2718** [comment]
Thx, will add to both.

**Comment by JobcenterTycoon** [comment]
The filter doens’t work anymore the tracking crap is back again

**Comment by mbvlist** [comment]
The current rules for tweakers.net block all pictures at the forum. Have a look at:
https://gathering.tweakers.net/forum/list_messages/822140/164
I see a lot of javascript-errors, which are not present with ublock disabled.

**Comment by AdamWr** [comment]
It has been fixed 2 days ago, please update filters.

**Comment by JobcenterTycoon** [comment]
Tracking script requests and 1x1 pixel are back again
`https://tweakers.net/x/scripts/min/xisIAJ.js`

`https://tweakers.net/103820290768866/?P2NnMT10d2Vha2Vycy5uZXQmY3AxNT0xODEyNTQmY2cyPU5pZXV3cyZjZzQ9SW50ZXJuZXQmbGE9ZGUmY3AzPTIwMjEtMDUtMDUlMjAwOCUzQTUxJmNzMj1tYiZjcDY9SGF5dGUlMjBIdWdvJnA9NDQ1LG5pZXV3cyUyRmFydGljbGUlMkZzcGFjZXgtbWVsZHQtbWVlci1kYW4taGFsZi1taWxqb2VuLWJlc3RlbGxpbmdlbi1vZi1wcmVvcmRlcnMtdm9vci1zdGFybGluaywxLDI1NjB4MTQ0MCwyNCwxLDE2MjAyNDQ4NTIwMjcsMSwxNDA0eDg3NSwwJnB1PWh0dHBzJTNBJTJGJTJGdHdlYWtlcnMubmV0JTJGbmlldXdzJTJGMTgxMjU0JTJGc3BhY2V4LW1lbGR0LW1lZXItZGFuLWhhbGYtbWlsam9lbi1iZXN0ZWxsaW5nZW4tb2YtcHJlb3JkZXJzLXZvb3Itc3RhcmxpbmsuaHRtbCZjZzM9SVQlMjBQcm8mZWlkPTIxNjE5NzkyNjE3NzIzNzIwMTMmY3A1PVNwYWNlWCZjcDEzPW5vcm1hbCZjZzU9SW50ZXJuZXR0b2VnYW5nJmNnNj1FZGl0b3JpYWwmY3A0PVJ1aW10ZXZhYXJ0JTNCU2F0ZWxsaWV0JTNCSW50ZXJuZXR0b2VnYW5nJTNCc3RhcmxpbmsmY3MzPUdlZW4`

**Comment by Yuki2718** [comment]
It's now a war of attrition. I'll update scriptlet but not sure about the pixel rule. Regex will be safer, but won't last long anyway.

**Comment by Yuki2718** [comment]
These work but may cause breakage:
```
tweakers.net#%#//scriptlet('abort-current-inline-script', 'document.createElement', 'newTracker')
tweakers.net#%#//scriptlet('abort-current-inline-script', 'loadJS', '_trackPage')
```
@JobcenterTycoon @AdamWr Can you check?

**Comment by AdamWr** [comment]
It seems that this rule - `tweakers.net#%#//scriptlet('abort-current-inline-script', 'loadJS', '_trackPage')` breaks website (some buttons don't work and images don't load).
I think that this one should works fine - `tweakers.net#%#//scriptlet('abort-current-inline-script', 'AbStats', 'trackId')`
The first rule seems to be okay.

**Comment by Yuki2718** [comment]
Thx confirmed. So loadJS can't be aborted even when narrowed down by the 2nd param.

**Comment by JobcenterTycoon** [comment]
Tracking is back please update

**Comment by Yuki2718** [comment]
I guess it's now impossible to prevent call to the scripts without $$ or $replace which are not supported on some platforms.
@AdamWr How do you think about
```
/x\/scripts\/(min\/)?[0-9a-z]{6,}\.js$/$script,~third-party,domain=tweakers.net
tweakers.net#%#//scriptlet('abort-on-property-write', 'webtrekkConfig')
tweakers.net#%#//scriptlet('abort-on-property-write', 'webtrekkMediaTracking')
tweakers.net#%#//scriptlet('prevent-addEventListener', trackerRefresh')
```

**Comment by AdamWr** [comment]
I guess that regex rule should be tested for a while until it will be added, other rules probably are fine.

By the way, if I'm not wrong, something like this should also works:
`tweakers.net#%#//scriptlet('set-constant', 'tweakersConfig.wtConfig.scriptUrl', '')`

**Comment by Yuki2718** [comment]
Great, the script regex is targeting is not called so the scriptlets other than the last one is not needed.

**Comment by Yuki2718** [comment]
Is `||tweakers.net/*/event-tracking/` safe?

**Comment by AdamWr** [comment]
>Is ||tweakers.net/*/event-tracking/ safe?

Should be safe, I think.

>Maybe `tweakers.net#%#//scriptlet('set-constant', 'tweakersConfig.spConfig.scriptUrl', '')` too (smartphone?).

The problem is that if we add both rules (scriptlets), then only one of them will works - https://github.com/AdguardTeam/Scriptlets/issues/65

**Comment by Yuki2718** [comment]
> > Is ||tweakers.net/*/event-tracking/ safe?
> 
> Should be safe, I think.
> 
> > Maybe `tweakers.net#%#//scriptlet('set-constant', 'tweakersConfig.spConfig.scriptUrl', '')` too (smartphone?).
> 
> The problem is that if we add both rules (scriptlets), then only one of them will works - [AdguardTeam/Scriptlets#65](https://github.com/AdguardTeam/Scriptlets/issues/65)

Didn't know, I'll then add PLATFORM hint.

**Comment by Yuki2718** [comment]
Hmm, on Firefox with mobile UA + AG Extension I can't block call to the script with either rule.

**Comment by crisp-tweakers** [comment]
This rule is breaking our so-called 'tracker' (what's in a name?)

`tweakers.net##+js(aeld, /trackerRefresh|trackerRestore/)`

These function handle the refresh of our sidebar tracker and have nothing to do with 'tracking':

![image](https://user-images.githubusercontent.com/32640525/119389909-8ecbc000-bccc-11eb-8eab-0eee05c64e9f.png)

By the way: do you have any sort of code of conduct or guidelines to determine when something is eligible for blocking? We use Webtrekk as a privacy-friendly alternative for Google Analytics, but it seems that you do not make such distinction when it comes to analytics tooling. Why is that?

**Comment by Yuki2718** [comment]
@crisp-tweakers Oh, sorry didn't check enough. Will remove from uAssets.

**Comment by uBlock-user** [comment]
> We use Webtrekk as a privacy-friendly alternative for Google Analytics

uBO follows EasyPrivacy's policy and blocks **all** analytics/tracking sites and code, privacy friendly or not.

**Comment by uBlock-user** [comment]
> We use Webtrekk as a privacy-friendly alternative for Google Analytics

uBO follows EasyPrivacy's [policy](https://github.com/easylist/easylist#easyprivacy) and blocks **all** analytics/tracking sites and code, privacy friendly or not.
