### ISSUE TITLE
[android] instagram app - ads in the feed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#807]

**Comment by Alex-302** [comment]
Sample links:
- ad
http://scontent-arn2-1.cdninstagram.com/hphotos-xaf1/t51.2885-15/s750x750/sh0.08/e35/11925717_855164657912076_1160312155_n.jpg
- just photo
http://scontent-arn2-1.cdninstagram.com/hphotos-xaf1/t51.2885-15/e35/12070660_475413682641556_657395864_n.jpg

Log from android(5)
[adguard.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/6858/adguard.txt)
Requests from Fiddler:
```
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
1	200	HTTP	Tunnel to	31.13.72.53:443	0						
42	206	HTTP	scontent-arn2-1.cdninstagram.com	/hphotos-xaf1/t50.2886-16/12039993_167695020240440_2038306185_n.mp4	914 110		video/mp4				
53	200	HTTP	Tunnel to	66.220.159.3:443	0						
179	200	HTTP	Tunnel to	173.194.222.188:5228	0
```

**Comment by evgeniy-ADG** [comment]
MPW-859-35224
![image](https://cloud.githubusercontent.com/assets/15856304/14242103/28526694-fa58-11e5-80f8-f2048ab12c26.png)

**Comment by Alex-302** [comment]
can't find this ad, but I think we can't block it without $rempace modifier

**Comment by vozersky** [comment]
Do we have any new ideas how to block these "sponsored" post ads?

**Comment by vozersky** [comment]
@Alex-302  pm'ed you the password for this log, check it:
[adguard.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/242516/adguard.zip)

**Comment by ameshkov** [comment]
To remove the ad we should inspect response body.

**Comment by evgeniy-ADG** [comment]
http://prntscr.com/b6yc1p
IHX-177-16237

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попроси юзера установить бету и записать HAR. В одной из задач описывал как это сделать.

**Comment by Alex-302** [comment]
ssl pinning
