### ISSUE TITLE
developers.google.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80719]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://developers.google.com/admob/android/banner have a newsletter.

![image](https://user-images.githubusercontent.com/76880977/115111495-4bc84f80-9f9e-11eb-99d5-3fcc63177299.png)
![image](https://user-images.githubusercontent.com/76880977/115111508-5c78c580-9f9e-11eb-9c17-3cf63414aec1.png)

![image](https://user-images.githubusercontent.com/76880977/115111514-613d7980-9f9e-11eb-98e4-3c06333d037e.png)

**Comment by Alex-302** [comment]
Not annoying.
