### ISSUE TITLE
developers.google.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80720]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
button to learn about Google Ads is broken

![image](https://user-images.githubusercontent.com/76880977/115111822-dbbac900-9f9f-11eb-8770-2ef3b0dee8e9.png)
![image](https://user-images.githubusercontent.com/76880977/115111825-dd848c80-9f9f-11eb-97ab-c1e58e9d940b.png)
  
![image](https://user-images.githubusercontent.com/76880977/115111856-ef662f80-9f9f-11eb-9d75-674a4e7c6976.png)

![image](https://user-images.githubusercontent.com/76880977/115111861-f5f4a700-9f9f-11eb-87be-1e78fdffbc0d.png)

**Comment by chirag127** [comment]
How much time will it take to update adguard base after the commit in
easylist .

**Comment by Yuki2718** [comment]
> How much time will it take to update adguard base after the commit in easylist.

Usually few hours but may take more depending on server condition.
