### ISSUE TITLE
https://www.entrepreneur.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80736]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.entrepreneur.com/article/369558
* **Current behaviour**: 
Advertisement + newsletter
![image](https://user-images.githubusercontent.com/76880977/115120981-058ae480-9fce-11eb-82d1-2978c56697a6.png)
![image](https://user-images.githubusercontent.com/76880977/115121097-81852c80-9fce-11eb-9206-f8bdb2bb1f2d.png)
![image](https://user-images.githubusercontent.com/76880977/115121099-86e27700-9fce-11eb-8d6b-c7f9abe146d8.png)
![image](https://user-images.githubusercontent.com/76880977/115121109-92ce3900-9fce-11eb-9aaf-0b18ba2f3eaf.png)

**Comment by Alex-302** [comment]
Not reproduced.
