### ISSUE TITLE
Multiple Tabs Search

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80782]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://chrome.google.com/webstore/detail/multiple-tabs-search/mhbpfljoihafefdodgklimejeacejnde extention window have an advertisement.

* **Current behaviour**: 
advert

[//]: # (advert)

[//]: # (
![image](https://user-images.githubusercontent.com/76880977/115142409-454ddc80-a05f-11eb-8b26-fa45ce216011.png)
![image](https://user-images.githubusercontent.com/76880977/115142413-48e16380-a05f-11eb-8ec6-57b79a0e566a.png)
![image](https://user-images.githubusercontent.com/76880977/115142427-51399e80-a05f-11eb-98cb-2dff7f4f5b7e.png)

.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 
[//]: # (no advert)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:
[//]: # (1. install the extension .
2. click on extension
)

***System configuration***
![image](https://user-images.githubusercontent.com/76880977/115142467-80e8a680-a05f-11eb-939a-9f888a4bd312.png)

**Comment by krystian3w** [comment]
IMO this need paid app for Windows/macOS, addon can't delete network request in other addon.

**Comment by chirag127** [comment]
Okay is that already blocked in windows.

**Comment by Alex-302** [comment]
It cannot be blocked. Banner is not loaded from network, just local file
![image](https://user-images.githubusercontent.com/8361299/115701315-556fff80-a370-11eb-9aac-ea4838746088.png)
