### ISSUE TITLE
dealabs.com

### ISSUE THREAD

**Issue by yesiamanothergithubuser** [AdguardTeam/AdguardFilters#80829]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: modals (in-page popups like login, menus) are not shown
* **Current behaviour**:  can't login, nor use account menu

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

* **Expected behaviour**: 

modals appears

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
1. Go to https://www.dealabs.com
2. Click on top right Connexion button
3. No modal appears

***System configuration***

**Filters:**

AdGuard Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | windows
Browser:                               | firefox
AdGuard version:                       | ublock extension
Filters enabled:                       | AdGuard Annoyances

-----

***NOTE***
By trying editing filter list, I managed to get modals working using following configuration:

```
www.dealabs.com#@##fb-root:not(body):not(html)
www.dealabs.com#@#.popover
www.dealabs.com#@#.btn--facebook
```

Thanks for your work guys <3 !

**Comment by krystian3w** [comment]
@AdamWr  to chyba pierwowzór `pepper.pl`
