### ISSUE TITLE
nu.nl - videos don't play

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#809]
on - http://imgur.com/qKNqoAd
off - http://imgur.com/6rqDN4V
http://www.nu.nl/politiek/4137409/bij-conflict-syrie-moet-nederland-geen-speelbal-van-russen-worden.html
DKZ-129-67215

**Comment by Alex-302** [comment]
Can't reproduce. Need the filters list.

**Comment by Alex-302** [comment]
Added to analytics
@@||google-analytics.com/ga.js$domain=media.zie.nl
to NL filter
||servedby.rtbiddingplatform.com^$domain=media.zie.nl

**Comment by evgeniy-ADG** [comment]
It started happening again.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22239992/8c642210-e221-11e6-859a-c44db0ae5f69.png)

</details>

MacOS X, Chrome 55, Adguard 1.4, Basic filters + German, Dutch, Mobile ads and Icelandic ABP

**Comment by Alex-302** [comment]
Блин, ну нет никаких "Basic filters". Дефолтный - только английский, все остальные - опциональные.
Передай на проверку:
```
@@||google-analytics.com/ga.js$domain=media.zie.nl
```
если не поможет:
```
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_108.js$domain=nu.nl
@@||nl-gmtdmp.mookie1.com/*/learn?tagid=$domain=nu.nl
@@||tpc.googlesyndication.com/safeframe/1-0-5/html/container.html$domain=nu.nl
@@||google-analytics.com/ga.js$domain=media.zie.nl
@@||cdn.krxd.net^$domain=nu.nl
@@||beacon.krxd.net^$domain=nu.nl
@@||cdn.krxd.net/controltag$domain=nu.nl
@@||static.criteo.com^$domain=nu.nl
@@||google-analytics.com^$domain=nu.nl
@@||scorecardresearch.com^$domain=nu.nl
```
Проперять лучше в приватном режиме.

**Comment by Alex-302** [comment]
Первое добавил в фильтр аналитики и мобильный.
