### ISSUE TITLE
https://www.duolingo.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80907]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.duolingo.com/learn Download the free app for new features and more! pop up 
![image](https://user-images.githubusercontent.com/76880977/115270160-afe34300-a159-11eb-9762-6181731367c3.png)
![image](https://user-images.githubusercontent.com/76880977/115270161-b1147000-a159-11eb-8c9e-38f3a82d6953.png)
![image](https://user-images.githubusercontent.com/76880977/115270204-b70a5100-a159-11eb-8815-171e09675d20.png)

**Comment by Alex-302** [comment]
Not reproduced(with/without account)
