### ISSUE TITLE
perfectgirls.net[NSFW] Advertisement

### ISSUE THREAD

**Issue by PoRtvine** [AdguardTeam/AdguardFilters#8091]
perfectgirls.net##.adv_block

perfectgirls.net##div[class^="advertisement"]

perfectgirls.net##.additional-block-bg

perfectgirls.net##.banner-wrapper

**Comment by vitalkanev** [comment]
Filters? Version?

**Comment by Alex-302** [comment]
@vitalkanev не нужно этого делать. Мы в состоянии сами задать нужный вопрос. Потом у юзеры не будут понимать от кого ждать решения проблемы.

**Comment by Alex-302** [comment]
Fixed.
