### ISSUE TITLE
https://www.cnbc.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80944]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.cnbc.com/2021/04/20/indias-social-media-law-puts-big-techs-power-into-states-hands-critics-say.html have a newsletter

![image](https://user-images.githubusercontent.com/76880977/115340706-d4283980-a1c4-11eb-8875-d183907338e4.png)
![image](https://user-images.githubusercontent.com/76880977/115340705-d38fa300-a1c4-11eb-8c13-b236a7c41071.png)
![image](https://user-images.githubusercontent.com/76880977/115340717-d8545700-a1c4-11eb-801e-888707fb4abb.png)

**Comment by Alex-302** [comment]
No need to block it.

**Comment by chirag127** [comment]
Fine
