### ISSUE TITLE
https://www.investing.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#80961]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.investing.com/ has pop up 
![image](https://user-images.githubusercontent.com/76880977/115365476-0c8a4080-a1e2-11eb-81e2-266a235ddfc0.png)
![image](https://user-images.githubusercontent.com/76880977/115365481-0d22d700-a1e2-11eb-8abc-dd190724ce0c.png)
![image](https://user-images.githubusercontent.com/76880977/115365504-1318b800-a1e2-11eb-9f8f-ccb9f729fe02.png)

**Comment by BlazDT** [comment]
Not sure if we should fix that @AdguardTeam/filters-maintainers

**Comment by zloyden** [comment]
This is a useful popup as a hint, so we shouldn't block it.
@chirag127 try `investing.com###topAlertBarContainer` in the User rules.
