### ISSUE TITLE
Gray overlay blocking access YouTube

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#80962]
@stuart-tetley commented on [Thu Apr 15 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/584)

Watching YouTube today after 2 videos, the screen went dim, and interactions stopped.  Probably YouTube trying to open a login prompt.

See code from Safari inspector.  Removing/renaming the "opened" css class fixed the problem. Code attached as 'insert code' doesn't seem to work...

`<tp-yt-iron-overlay-backdrop style="z-index: 2201;" class="opened" opened="">
    

    
</tp-yt-iron-overlay-backdrop>`

[YouTube code sample.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/6318527/YouTube.code.sample.txt)

---

@TheHasagi commented on [Mon Apr 19 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/584#issuecomment-822268505)

@stuart-tetley 

Are you sure that issue is not caused by a third-party filter? Can you check only with AdGuard base filter, Annoyances? Also, please, provide any screenshots.

---

@Oleg-Chashko commented on [Mon Apr 19 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/584#issuecomment-822344444)

@TheHasagi 
_Are you sure that issue is not caused by a third-party filter?_
No, because I don't use them.

P.S. Occurs, this issue is very rare and not every day. And the sequence that causes it I did not find.

Filters:
<img width="1072" alt="Bildschirmfoto 2021-04-19 um 12 00 25" src="https://user-images.githubusercontent.com/62497891/115218504-e80d6600-a106-11eb-9c96-6720b2cc4482.png">

---

@Oleg-Chashko commented on [Mon Apr 19 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/584#issuecomment-822363997)

@TheHasagi 
I found the sequence: 
You clear the browser history, YouTube opens, you accept the agreement, the video channel opens and.

https://user-images.githubusercontent.com/62497891/115222442-01181600-a10b-11eb-86de-c715f906b75b.mp4

---

@stuart-tetley commented on [Mon Apr 19 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/584#issuecomment-822416378)

Hi!  Thanks for the info.  Sorry for the delay replying. Very very busy atm.

That video looks much like my experience.  I had watched two full videos before it popped up) and I never saw the login prompt at the start.

[I was puzzled when I logged this - I don't recall being asked to confirm which block lists I have.  The previous time I was. )

Hopefully, including the html/css element was helpful.  I could try reproduce this with only base filter but I'm a bit busy for the next 2-3 days!

**Comment by TheHasagi** [comment]
@Alex-302 It looks like a filter issue. Please, take a look.

**Comment by Alex-302** [comment]
Please check
`youtube.com##tp-yt-iron-overlay-backdrop` (it may break the site functions, if I am not wrong)
On my end not reproduced, probably an issue with advanced rules execution.

**Comment by stuart-tetley** [comment]
Hi, just saw this and checked.  

Overlay pops up then almost immediately disappears.  Everything else seems to work ok

Thanks!

**Comment by stuart-tetley** [comment]
Just tried again as I wasn't sure filters were updated previously. I've updated and it now work perfectly - no overlay and everything else still ok.
