### ISSUE TITLE
Adguard block access to legitimate site (http://adsabs.harvard.edu/ads_abstracts.html)

### ISSUE THREAD

**Issue by quark67** [AdguardTeam/AdguardFilters#80976]
In the URL http://adsabs.harvard.edu/ads_abstracts.html, "ads" is not for "advertising", but for "Astrophysics Data System".

I cannot access to this page, the error message is (approximately, because I translate from French): _Safari cannot open the page "http://adsabs.harvard.edu/ads_abstracts.html". Error: "the URL was blocked by a content blocker"_. 

Perhaps can you allow this URL?

**Comment by krystian3w** [comment]
@Yuki2718 can you check and maybe fix in EL?

**Comment by Yuki2718** [comment]
Can't reproduce with AG Extension on Chromium (Base, TPF, Social, Annoyances, & French). Do not skip the template.

**Comment by quark67** [comment]
I just updated "AdGuard for Safari" to version 1.9.13, and same behaviour: the page is blocked. 
Installed: 
* AdGuard
* AdGuard Advanced Blocking
* AdGuard Autres (=AdGuard Others)
* AdGuard Custom
* AdGuard Privacy
* AdGuard Security
* AdGuard Social
* Icône AdGuard Safari (=AdGuard Safari Icon)

**Comment by krystian3w** [comment]
@Yuki2718 maybe possible reporduce on Android + AdGuard Content Blocker for Samsung Internet "browser" / Yandex Browser.

https://play.google.com/store/apps/details?id=com.yandex.browser
https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser

\+

https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker


Unless it is filters directly from the AdGuard project that are causing the blocking, such are repaired at the AdGuard list level and not with a pending repair in EL/EP.

**Comment by Alex-302** [comment]
@quark67 I can't reproduce. Could you please check which filter breaks the site?

**Comment by quark67** [comment]
How can I find the filter? Which steps must I do? In Safari Web inspector? Where? In Adguard for Safari? Where? Thanks.

**Comment by Alex-302** [comment]
@quark67 Hi. Just disable filters one by one with checking(wait ~10-15 seconds after each disable/enable)

**Comment by quark67** [comment]
So, the results:

- AdGuard Advanced Blocking 1.9.13 deactivated: still the same blocking;
- plus AdGuard Others 1.9.13 deactivated: still the same blocking;
- plus AdGuard Custom 1.9.13 deactivated: still the same blocking;
- plus AdGuard Privacy 1.9.13 deactivated: still the same blocking;
- plus AdGuard Security 1.9.13 deactivated: still the same blocking;
- plus AdGuard Social 1.9.13 deactivated: still the same blocking;
- plus AdGuard 1.9.13 deactivated: **hourra! I can access to the site**.

Must I do another test?

**Comment by quark67** [comment]
Here are the settings from the "AdGuard for Safari" app:
![image](https://user-images.githubusercontent.com/9338576/117166171-6b48e000-adc6-11eb-83e9-f4ba29ea5b25.png)

And more specifically for the Ads Block:
![image](https://user-images.githubusercontent.com/9338576/117166577-cb3f8680-adc6-11eb-8a73-b377422f7977.png)

Deactivating "Filtre anglais AdGuard" (English Filter AdGuard) does nothing about the blocking of the page (when all the extensions from the previous list are reactivated).

**Comment by krystian3w** [comment]
So something match with:

`://ads` (all domain will not load) or `/ads_` (only few `.html` files with unlucky names)

**Comment by Sergey-Lyapin** [comment]
The problem is caused by AdGuard French filter (most likely by `/ads_$popup` rule)

**Comment by quark67** [comment]
Yes, after updating, I can reach the page  http://adsabs.harvard.edu/ads_abstracts.html, thanks.
