### ISSUE TITLE
https://www.duolingo.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81046]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.duolingo.com/learn have pop up overlay .

![image](https://user-images.githubusercontent.com/76880977/115454191-20fc2680-a23e-11eb-9e5a-3d84fa9666e7.png)
![image](https://user-images.githubusercontent.com/76880977/115454195-22c5ea00-a23e-11eb-98ae-a848343e8855.png)
![image](https://user-images.githubusercontent.com/76880977/115454215-278a9e00-a23e-11eb-938b-c7673372a3a6.png)

**Comment by Alex-302** [comment]
duplicate
https://github.com/AdguardTeam/AdguardFilters/issues/80907

**Comment by chirag127** [comment]
@Alex-302  It is not duplicate. It is invite friend request pop up, and that was download our app pop up.

**Comment by Alex-302** [comment]
In any case I cannot reproduce. Need code of element.

**Comment by chirag127** [comment]
I will give the code if I'm able to reproduce it.
