### ISSUE TITLE
https://www.zentralplus.ch/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81053]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:https://www.zentralplus.ch/ has a newsletter.
![image](https://user-images.githubusercontent.com/76880977/115461382-f8c4f580-a246-11eb-803f-c80719219aca.png)
![image](https://user-images.githubusercontent.com/76880977/115461407-ff536d00-a246-11eb-82e9-42bc4bbfe076.png)

**Comment by Alex-302** [comment]
Not reproduced. Please show code of element.
