### ISSUE TITLE
Is this gonna work?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#81080]
```
202.128.224-226.23$network
or
202.128.22*.23$network
or~....
202.128.2*4.23$network
202.128.2*.23$network
```
Is this gonna work on `Adguard Windows`, `Adguard Android` and `Adguard Chrome`? thx!~

**Comment by piquark6046** [comment]
Please read [this doc](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier).

**Comment by c2xusnpq6** [comment]
> Please read [this doc](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier).

the support it thx!

**Comment by zloyden** [comment]
`202.128.224-226.23$network` should work in app.
`202.128.22*.23$network` it's invalid rule on my end (works on extension). @ameshkov what can you say about using `*` in such rules?

**Comment by ameshkov** [comment]
They'll work on Android and Win, but not on Mac.
