### ISSUE TITLE
https://www.adobe.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81251]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.adobe.com/ has pop up 
![image](https://user-images.githubusercontent.com/76880977/115854415-d817be00-a447-11eb-9d6e-fe85bfe790c1.png)
![image](https://user-images.githubusercontent.com/76880977/115854419-d8b05480-a447-11eb-9ddd-a187010d1ded.png)
![image](https://user-images.githubusercontent.com/76880977/115854436-de0d9f00-a447-11eb-98df-2cd204719f3c.png)

**Comment by zloyden** [comment]
It's a useful popup. You can block it via User rules:
```
adobe.com#$#body { overflow-y: visible !important; }
adobe.com#$#.modalContainer > locale-modal { display: none !important; }
```
