### ISSUE TITLE
https://medium.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81260]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://medium.com/swlh/the-top-10-most-useful-online-courses-you-can-take-for-free-411aaa0dd80d has a pop up + tweeter share button.

![image](https://user-images.githubusercontent.com/76880977/115870365-c856a480-a45c-11eb-9b3c-4d5593b001c9.png)
![image](https://user-images.githubusercontent.com/76880977/115870366-c856a480-a45c-11eb-80ff-c60b02806ce9.png)
![image](https://user-images.githubusercontent.com/76880977/115870377-ce4c8580-a45c-11eb-8525-442fae632ef7.png)

**Comment by krystian3w** [comment]
Maybe no worth to block with ExtendedCSS:

```css
##div[style^="position: absolute; inset: auto auto 0px 0px; transform: translate("]class*=" "[data-popper-reference-hidden="false"][data-popper-escaped="false"][data-popper-placement="top"]
```

**Comment by chirag127** [comment]
@krystian3w 

> no worth
would you mind elaborating it?


social share buttons are always blocked.

**Comment by krystian3w** [comment]
No in e.g. Apple music page: #apple

**Comment by chirag127** [comment]
> > social share buttons are always blocked.
> 
> No in e.g. Apple music page: [#56035 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/56035#issuecomment-634837239)
> 
> ![obraz](https://user-images.githubusercontent.com/35370833/115892992-ff768700-a457-11eb-9f81-7c57af29648b.png)

but there the social button comes after many clicks

**Comment by krystian3w** [comment]
But this case makes it impossible to achieve the condition of 100% effectiveness for reported social share "links".

**Comment by krystian3w** [comment]
#83715 #83808  #84529
