### ISSUE TITLE
AdGuard blocking e-mail attachments

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#8126]
Hi,

The AdGuard Chrome extension is preventing any e-mail attachments from being viewed via Outlook.com (see screen below):

![untitled](https://user-images.githubusercontent.com/19891537/33605812-1863b1f2-d9b3-11e7-8ec7-d183d5355852.png)

Disabling the extension allows said attachments to display as normal.

I e-mailed support@adguard.com about this but no response so far. Thanks!

**Comment by Alex-302** [comment]
Please create report using reporting tool
https://reports.adguard.com/new_issue.html

**Comment by tbcam88** [comment]
Uninstalling/reinstalling the extension solved the problem. Thanks.

**Comment by Alex-302** [comment]
ok
