### ISSUE TITLE
https://www.mozilla.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81363]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:https://www.mozilla.org/en-US/ has download our app banner
![image](https://user-images.githubusercontent.com/76880977/115965484-1d6ee500-a547-11eb-88ff-5376c0ee8d47.png)
![image](https://user-images.githubusercontent.com/76880977/115965485-1e077b80-a547-11eb-9e00-21ef550b7cb4.png)
![image](https://user-images.githubusercontent.com/76880977/115965492-2495f300-a547-11eb-93fa-788a81ef3f3c.png)

**Comment by chirag127** [comment]
That means that I should report Non popup download our app banner?

**Comment by zloyden** [comment]
It's a popup that can be blocked in AdGuard Annoyances.
If you see the app banner (a static element) that placed is not in the header or footer, you can also report about it.
