### ISSUE TITLE
chrome.google.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81428]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://chrome.google.com/webstore/detail/selection-search/gipnlpdeieaidmmeaichnddnmjmcakoe/related has pop up 
![image](https://user-images.githubusercontent.com/76880977/115987847-7d5f9d00-a5d4-11eb-9b28-2c3cbcd4f773.png)
![image](https://user-images.githubusercontent.com/76880977/115987845-7d5f9d00-a5d4-11eb-8ae7-c9b2f78f56ca.png)
![image](https://user-images.githubusercontent.com/76880977/115987848-7df83380-a5d4-11eb-9075-83a1d0d7b88d.png)
![image](https://user-images.githubusercontent.com/76880977/115987853-8486ab00-a5d4-11eb-9cd0-f58f645c2776.png)

**Comment by Alex-302** [comment]
Neep popup code.

**Comment by chirag127** [comment]
@Alex-302  See second image.

**Comment by Alex-302** [comment]
It is useless. Popup is in iframe, and I don't see it.
