### ISSUE TITLE
turtlemobile.com.tw batmobile.com.tw tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#81434]
https://meteor.today/board/all --> https://backend.turtlemobile.com.tw/collector/sync
This website (https://meteor.today/) is powered by `Data Management Platform` turtlemobile.com.tw and batmobile.com.tw
```
||backend.turtlemobile.com.tw/collector/*
||turtlemobile.com.tw^$third-party
||batmobile.com.tw^$third-party
```
https://www.facebook.com/BATMobileInc/
https://www.facebook.com/TurtleMobile/
![image](https://user-images.githubusercontent.com/75058881/115991978-bfe99f80-a5fd-11eb-92fc-912f9db3c94c.png)

**Comment by c2xusnpq6** [comment]
And these~

https://meteor.today/article/k5ni4A
--> https://meteor.today/ad/get_web_ad
--> https://meteor.today/adv2/get_ads
```
||meteor.today/adv2/^
||meteor.today/ad/^
```
No ads.......... yet
![image](https://user-images.githubusercontent.com/75058881/115996099-8b331380-a610-11eb-8122-106e6dbb5956.png)

https://meteor.today/board/all  -->
```
<div id="rightadboard" class="right-div">

||meteor.today/redirect/webad/^
```
![image](https://user-images.githubusercontent.com/75058881/115995937-e1ec1d80-a60f-11eb-82dd-2cb5a8fb8e70.png)
![image](https://user-images.githubusercontent.com/75058881/115996023-47400e80-a610-11eb-860b-ec73a7061d89.png)
![image](https://user-images.githubusercontent.com/75058881/115996253-1f9d7600-a611-11eb-9d0a-2d591317b10b.png)

**Comment by Alex-302** [comment]
> ||meteor.today/redirect/webad/^

not reproduced.
