### ISSUE TITLE
https://sound-effects.bbcrewind.co.uk/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81474]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://sound-effects.bbcrewind.co.uk/ has pop up
![image](https://user-images.githubusercontent.com/76880977/116002125-d4d22d00-a615-11eb-994e-202b3c9fad11.png)
![image](https://user-images.githubusercontent.com/76880977/116002124-d4d22d00-a615-11eb-9eff-46daddeda50c.png)
![image](https://user-images.githubusercontent.com/76880977/116002126-d56ac380-a615-11eb-9193-5db08d469c87.png)
![image](https://user-images.githubusercontent.com/76880977/116002130-d996e100-a615-11eb-98cf-5492c9503ab2.png)

**Comment by AdamWr** [comment]
Fixed cookie notice but I couldn't reproduce popup.

**Comment by chirag127** [comment]
seems to come after sometime. i had also share some code , won't it help?
