### ISSUE TITLE
livemint.com top ad banner

### ISSUE THREAD

**Issue by karl-pae** [AdguardTeam/AdguardFilters#81472]
**Issue Details**

**AdGuard version:** Adguard Content Blocker (v 2.6.2) on Samsung Internet

**Filtering mode:** User rules

**Device:** OnePlus 7T

**Details**
When I visit livemint.com the top banner ad is blocked and not displayed but space isn't hidden. I ran inspect mode, and found that changing display property of class="mobileAd" to **none** hides the element, but adding user rules doesn't make any changes after loading.. HTML line : <div id="adfreeDivMobile" class="mobileAd">

**Additional Information**
tried using cosmetic filter : `livemint.com###adfreeDivMobile`
tried using CSS rules: `livemint.com#$#.mobileAd {display: none!important; }`

**Comment by karl-pae** [comment]
@Alex-302 this solution doesn't seem to work with Adguard content Blocker. I added your commit rules in "user rules" section. Any solution?

**Comment by Alex-302** [comment]
@karl-pae `Adguard content Blocker` cannot use CSS rules because browser's API has no support. AdGuard for Android app suppport all rule types.
