### ISSUE TITLE
https://www.datenightquestions.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81470]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.datenightquestions.com/ have newsletter
![image](https://user-images.githubusercontent.com/76880977/116000898-ab160780-a60f-11eb-9df4-b5eabae98d88.png)
![image](https://user-images.githubusercontent.com/76880977/116000899-ab160780-a60f-11eb-92f9-3b439678e710.png)
![image](https://user-images.githubusercontent.com/76880977/116000905-af422500-a60f-11eb-8b9c-a92d757df568.png)

**Comment by Alex-302** [comment]
For user filter
`datenightquestions.com##.tint`
