### ISSUE TITLE
m.livehindustan.com

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdguardFilters#81517]
Chrome android with adguard for android (uBO lists added).

- Anti-adblock modal & article limit login popup originates from `https://m.livehindustan.com/static/build_mobile/dist_mobile/modules/mobile_detail-4e60409d36.js`
- Scroll blocked
- CSS filters not working
- Open app button

Proposed filters:
```
! Open app
m.livehindustan.com##.opn-apbtn

! Scroll & anti-adb
m.livehindustan.com##+js(aeld, scroll, adBlockerCalled)
m.livehindustan.com##html:style(overflow: auto !important)
```

**Comment by cantunborn** [comment]
Account is not required, maybe try with VPN set to India.

> Is `m.livehindustan.com##html:style(overflow: auto !important)` required, or this rule against cookie notification?

May be required, because while testing sometimes the scrolling was not fixed with just scriplet rule.

Scroll blocking is injected into html tag as a class.

**Comment by Alex-302** [comment]
Ok, also added `m.livehindustan.com#%#//scriptlet("prevent-addEventListener", "scroll", "adBlockerCalled")`

**Comment by cantunborn** [comment]
Steps to reproduce scroll block:
- Open any article in fresh tab.
- Scroll through 3 articles, scroll blocked on 4th.
- Cookie named `lh_page_viewd` is used to count article views.
- After 3rd article, `skippable` class is added to `html` tag which blocks scrolling.
- Logic can be viewed in the script in original comment.

Scrolling not fixed through `body` tag https://github.com/AdguardTeam/AdguardFilters/commit/038817c7e718c3dce1c70eb24513fcb542877ff5#.

`m.livehindustan.com##html:style(overflow: auto !important)` works.

Also, open app button annoyance `m.livehindustan.com##.opn-apbtn`.

**Comment by cantunborn** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Ok, changed.
