### ISSUE TITLE
https://www.highspeedinternet.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81527]
***Description***: https://www.highspeedinternet.com/tools/speed-test has newsletter + this page has ads warning
![image](https://user-images.githubusercontent.com/76880977/116116248-90f42c00-a6d8-11eb-88e0-c65eedab6cce.png)
![image](https://user-images.githubusercontent.com/76880977/116116254-918cc280-a6d8-11eb-8555-e8280a752fe0.png)
![image](https://user-images.githubusercontent.com/76880977/116116252-90f42c00-a6d8-11eb-9e82-d87f813f02e5.png)
![image](https://user-images.githubusercontent.com/76880977/116116288-9e111b00-a6d8-11eb-8c3e-05184f9b0d1c.png)

**Comment by chirag127** [comment]
what about the ads warning at the top?
![image](https://user-images.githubusercontent.com/76880977/116432644-61732a00-a866-11eb-8d9d-b6771f28e40e.png)

**Comment by Alex-302** [comment]
I don't see ads. What do you mean?

**Comment by chirag127** [comment]
We may earn money when you click our links written ad the top is ads warning. Just like cookie warning.
