### ISSUE TITLE
https://www.webnots.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81540]
https://www.webnots.com/seo-tools/http-header-checker/

![image](https://user-images.githubusercontent.com/76880977/116151789-b26a0d80-a702-11eb-8c1f-fa7737c74324.png)
![image](https://user-images.githubusercontent.com/76880977/116151801-b8f88500-a702-11eb-888b-1df1b9f559c1.png)

**Comment by Alex-302** [comment]
Not reproduced.
Please check testing rule 
`@@||webnots.com^$urlblock`
