### ISSUE TITLE
Request addition of following tracking parameters

### ISSUE THREAD

**Issue by techIndia-hacker** [AdguardTeam/AdguardFilters#81558]
I sometimes read the filtering logs and came up with more tracking parameters in https get requests. Please add them. 

"imei model fingerprint product device build_id manufacturer brand deviceIpAddress hardware"

**Comment by Alex-302** [comment]
What is it? Need examples.

**Comment by techIndia-hacker** [comment]
Add them in the list of tracking parameters for stealth mode.

**Comment by Alex-302** [comment]
Where you found them? I cannot just add random parameters.

**Comment by techIndia-hacker** [comment]
Ohk, I sent u a screenshot in telegram. Remember??

**Comment by Alex-302** [comment]
Send URL as text.

**Comment by techIndia-hacker** [comment]
![Screenshot_20210429-001918__01](https://user-images.githubusercontent.com/58086339/116457607-3ba74e80-a881-11eb-9275-94b503f3232c.jpg)

**Comment by techIndia-hacker** [comment]
Will the screenshot work?

**Comment by techIndia-hacker** [comment]
@ameshkov Sir, your opinion is requested in this matter. This is important

**Comment by ameshkov** [comment]
These are not tracking parameters, just normal parameters that speedtest uses for configuring the test.

Note that tracking params are usually used in third-party context (for instance, when you click a link to some website, and some additional data is passed via tracking params).
