### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#81589]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

Anti Adblock:
`https://majesy.com`
`https://majesy.org`
`https://magesy.eu`
`https://magesy.fr`
`https://magesy.be`
`https://mage.si/1V6K`
`https://www.prosieben.de/tv/germanys-next-topmodel/video/151-pailletten-posen-kleine-pannen-so-meistern-die-models-ihre-erste-fashion-show-clip`

popups:
`http://protect-link.biz`

Ad reinsertion:
`https://www.desired.de/lifestyle/bilderstrecke/19-sinnlose-produkte-die-du-tatsaechlich-kaufen-kannst/`

private tab blocking:
`https://www.abandonmail.com/`

clipboard manipulation when i copy the solution
`https://www.blitzrechner.de/prozent/`

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

`prosieben.de`
<img width="568" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/116244245-0c50ee80-a768-11eb-8c4e-b192d1fca578.PNG">

`majesy ...`
<img width="593" alt="Unbenannt2" src="https://user-images.githubusercontent.com/48647394/116244251-0d821b80-a768-11eb-9570-036af11898c6.PNG">

`abandonmail.com`
<img width="977" alt="Unbenannt3" src="https://user-images.githubusercontent.com/48647394/116244253-0e1ab200-a768-11eb-8eb5-d2f98d49b551.PNG">

`desired.de`
<img width="786" alt="Unbenannt4" src="https://user-images.githubusercontent.com/48647394/116244255-0e1ab200-a768-11eb-9534-f9bff9e3589c.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.5.34
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Sergey-Lyapin** [comment]
https://www.prosieben.de/tv/germanys-next-topmodel/video/151-pailletten-posen-kleine-pannen-so-meistern-die-models-ihre-erste-fashion-show-clip 
I can't reproduce antiadblock here
https://www.desired.de/lifestyle/bilderstrecke/19-sinnlose-produkte-die-du-tatsaechlich-kaufen-kannst/
and I was not able to reproduce ads here

@BlazDT could you check please?

**Comment by Sergey-Lyapin** [comment]
https://www.abandonmail.com/

The site works fine in private tab on my device

https://www.blitzrechner.de/prozent/ clipboard issue is fixed

**Comment by BlazDT** [comment]
Not reproduced.

**Comment by JobcenterTycoon** [comment]
`https://www.abandonmail.com` use Firefox with private tab.

`http://protect-link.biz` need to be fixed

all another issues are fixed now after 14 days.

**Comment by Alex-302** [comment]
Fixed.
