### ISSUE TITLE
(bug) Ads passing through on edge browser

### ISSUE THREAD

**Issue by gpodder770** [AdguardTeam/AdguardFilters#81601]
1mlsbd.com
If i enable the dns filtering section filter in the adguard android app and and the default filters 
Then ads come through 
But if i only use the default filters and turn off dns filtering the ads seems to dissapear on edge android

![Screenshot_20210427-212006_Edge](https://user-images.githubusercontent.com/71787759/116267598-6076c580-a79e-11eb-947c-c7eb761d6774.jpg)

![Screenshot_20210428-142402_AdGuard](https://user-images.githubusercontent.com/71787759/116374084-ca8b7b00-a82f-11eb-8e59-d026b078409d.jpg)

**Comment by gpodder770** [comment]
Anyone?

**Comment by gpodder770** [comment]
@Yuki2718 can u plz check this

**Comment by Yuki2718** [comment]
I can't reproduce, ads blocked with DNS filtering on AG for Android + Chrome.

**Comment by gpodder770** [comment]
> I can't reproduce, ads blocked with DNS filtering on AG for Android + Chrome.

Yes for some reason it only happens on edge android and firefox nightly( someone on telegram chat confirmed)

**Comment by Yuki2718** [comment]
I can't reproduce Edge for Android as well. Firefox Nightly gets certificate error.

**Comment by gpodder770** [comment]
On firefox nightly u have to activate the certificate via about:config 
On edge it passes through when dns filtering is on 
After loading the website for 1-2sec 
The ads come

**Comment by Yuki2718** [comment]
> On firefox nightly u have to activate the certificate via about:config

Yeah, but anyway I couldn't reproduced on Edge with the mentioned steps. Wait for other members to confirm.

**Comment by gpodder770** [comment]
> > On firefox nightly u have to activate the certificate via about:config
> 
> Yeah, but anyway I couldn't reproduce on Edge with the mentioned steps. Wait for other members to check.

The edge one is a strange problem 
After applying dns filtering, the content filters would have cleaned 
But for some reason the content filters don't work on that site with dns filtering :(

**Comment by Alex-302** [comment]
Also not reproduced. Added one rule, which may help. Please check after filters update.
