### ISSUE TITLE
chinese gov tracking app for chinese people

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#81622]
```
$app=com.fiberhome.wifiserver

$app=com.hicorenational.antifraud
```

https://www.virustotal.com/gui/file/dc12d5c78117af8167d8e702dd131f838fe86930187542cf904b2122ba32afd1/
https://www.virustotal.com/gui/file/6b2d11765d5f1965b9550f7be154875d510f4c371862bf74e53574eb754574be/
https://www.virustotal.com/gui/file/277aa67186e33e494daa26e2879bae86a86d4ddf83d562aa4dbad8385f885c21/

https://github.com/c2xusnpq6/anticult_list/blob/main/ChineseGOVTrackerList_Extreme.txt (I'll push a huge commit later)

**Comment by Alex-302** [comment]
Added `$app=com.fiberhome.wifiserver`
Secont app is legal, I guess. And can be uninstalled by user without problems.

**Comment by c2xusnpq6** [comment]
> And can be uninstalled by user without problems.

But their government forces them to install the app... you can install `coolapk` (Chinese App Store) and search for "com.hicorenational.antifraud"... then check the comments, you can see many people are forced to install it, and they DONT LIKE that

so reopen pls... if you needed more detail... tell me ^^

**Comment by c2xusnpq6** [comment]
just google `com.hicorenational.antifraud` and `com.bestmind.antifraud` ^^
