### ISSUE TITLE
papaly.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81667]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://papaly.com/ has a pop up 
![image](https://user-images.githubusercontent.com/76880977/116408451-6e851e80-a850-11eb-98f0-78e8b07c7974.png)
![image](https://user-images.githubusercontent.com/76880977/116408447-6dec8800-a850-11eb-8a5f-5a8e9a1aae07.png)
![image](https://user-images.githubusercontent.com/76880977/116408453-6f1db500-a850-11eb-9659-d8f2bb1b0eb3.png)
![image](https://user-images.githubusercontent.com/76880977/116408466-73e26900-a850-11eb-99f0-28fa8e4943ca.png)

**Comment by Alex-302** [comment]
Useful
![image](https://user-images.githubusercontent.com/8361299/119007045-92dca280-b999-11eb-89d3-18908ca44bc5.png)
