### ISSUE TITLE
my.eset.com and login.eset.com required access to googletagmanager.com scripts

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#81678]
ESET released
https://play.google.com/store/apps/details?id=com.eset.myeset
for management. 
Adguard blocking some traffic and app cannot login to network at all on Android.
Second issue is each time login I had mail from eset with unusal trafic from network warning. 

@ameshkov 

Fix after testing:
```
@@||googletagmanager.com^$domain=login.eset.com|my.eset.com,important,third-party
```
after adding this no more warning about unusal network traffic from ESET. 

Reproduce:
1. Create an ESET account.
2. Enable Adguard with standard protection (Base, Spy, Social) and Peter Lowe's list. Try login. 
3. On Android phone just try login to account in app. 

EDIT: After testing:
- With unblocked `googletagmanager.com` for eset domains MyESET service remeber login and after open page again - login automatically. 
- No more issues. 

![20210428-1619620364-001](https://user-images.githubusercontent.com/9846948/116421834-7e483700-a83f-11eb-9eac-2182c44c2ae0.png)

![Screenshot_2021-04-28-16-36-44-817_com adguard android](https://user-images.githubusercontent.com/9846948/116422425-075f6e00-a840-11eb-931d-08c1d033be90.jpg)

![20210428-1619620898-001](https://user-images.githubusercontent.com/9846948/116423079-a5533880-a840-11eb-9dff-73c898f4003e.png)

![20210428-1619621210-001](https://user-images.githubusercontent.com/9846948/116423899-607bd180-a841-11eb-8527-2b7dbdf6d4ce.png)
![20210428-1619621197-001](https://user-images.githubusercontent.com/9846948/116423901-61146800-a841-11eb-909f-759d7014bb4d.png)

**Comment by Sergey-Lyapin** [comment]
@FadeMind Hello, sorry for late reply

I reproduced the problem, but it is caused by blocking `google-analytics.com` on my device. 
But I was not able to reproduce the second issue, could you check again? Btw I don't sure that we should do something with it.

**Comment by FadeMind** [comment]
I workaround issue:
- remove myESET from filtering app
- add `@@||googletagmanager.com^$domain=login.eset.com|my.eset.com,important,third-party` to user filters in Adguard Android app. 
![Screenshot_2021-05-19-13-39-36-275_com adguard android](https://user-images.githubusercontent.com/9846948/118807357-7876cc00-b8a8-11eb-857b-28fe7aebb233.jpg)

In Desktop Environment (Windows + Edge + Adguard Extension) I have only warnings about unusal logins - but seens to be internal _eset_ things not related with Adguard. 

Anyway Mobile app without whitelisting googletagmanager does not work. I cannot share any screenshots - denied in app.

**Comment by FadeMind** [comment]
One more. In desktop I don't need whitelist anything. 

Login works.

**Comment by ameshkov** [comment]
I really don't think we should fix anything here, AdGuard DNS users will also run into this.

Could you please send a message to ESET support service? App breakage due to blocked analytics is a bug.

**Comment by FadeMind** [comment]
@ameshkov https://forum.eset.com/topic/28503-myeset-android-app-required-connect-to-googletagmanager-script/

We will see. 😁

**Comment by ameshkov** [comment]
If they don't react to the complaint, please let me know, we'll try some twitter therapy.

**Comment by FadeMind** [comment]
Topic without any reply on forum.

**Comment by FadeMind** [comment]
@ameshkov  Today - latest myESET update app resolved issue. Adguard can filtering app and login works. None data are blocked by Adguard. Nothing to whitelist. Closing.
