### ISSUE TITLE
gaana.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#81718]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://Gaana.com/ has a pop up .
![image](https://user-images.githubusercontent.com/76880977/116466548-40253480-a88c-11eb-9371-6c26465e080c.png)
![image](https://user-images.githubusercontent.com/76880977/116466550-40253480-a88c-11eb-804c-6ce569dbe01d.png)
![image](https://user-images.githubusercontent.com/76880977/116466634-5f23c680-a88c-11eb-87e5-2e65c153b661.png)

**Comment by Alex-302** [comment]
@stanislav-atr

**Comment by stanislav-atr** [comment]
@chirag127, hi! This element can't be removed without removing next language selection window.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/119379626-63df6d00-bcc8-11eb-937a-52c4d33ed751.png)
</details><br/>
If you are ok with blocking them both, you may add 

```
gaana.com##.popupbg1
gaana.com##body > div[style="display: block;"].overlay
```

to you userfilter.
