### ISSUE TITLE
[Windows] Реклама в Shareman

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#818]
Некое приложение Shareman, у пользователя там реклама WZM-620-21941

https://www.shareman.tv/

**Comment by Alex-302** [comment]
Shareman version 3
Can't block url
||page.shareman.tv/*/shareman_rk.php?p=catalog
http://screencast.com/t/leN4zbkF

**Comment by Alex-302** [comment]
Нужно чтоб юзер снова проверил. В версии 4.5 вроде чисто.

**Comment by Alex-302** [comment]
Ещё нужно чтоб exe был добавлен в список браузеров.

**Comment by vbagirov** [comment]
Написал пользователю.

**Comment by evgeniy-ADG** [comment]
У нас еще один пользователь с аналогичной проблемой. У нас тоже повторяется.
![image](https://cloud.githubusercontent.com/assets/15856304/12092075/98500b0a-b303-11e5-8625-c93fb212ab71.png)
ZIU-285-85370

**Comment by Alex-302** [comment]
Должно фильтроваться. Не пойму что не так.

@ameshkov Почему добавленное приложение может не фильтроваться? Исключений нет.

**Comment by ameshkov** [comment]
@Alex-302 там вообще запросов от него в журнале нет? Надо смотреть список процессов, нужно смотреть что там в журнале вообще за запросы.

**Comment by Alex-302** [comment]
@ameshkov есть, но они с кодом 304 не смотря на правила
```
||page.shareman.tv/rostk/bottom.html
||page.shareman.tv/rostk/top_right.html
||page.shareman.tv/rostk/right.html
||page.shareman.tv/rostk/top.html
```
Картинки блоктровались, но стоило хоть раз пропустить, и стали грузитьсяиз кэша
``` 
http://page.shareman.tv/rostk/img/Banner_728_90.gif
http://page.shareman.tv/rostk/img/book_of_ra_728_90.gif
```
Если возвращять запросам 204, то выглядит так
http://imagizer.imageshack.com/img908/7052/0XAE1w.jpg

**Comment by ameshkov** [comment]
Если с 304, то надо кэш почистить.

**Comment by ameshkov** [comment]
Ну по ходу нельзя ни разу пропускать то есть или что?:)

**Comment by Alex-302** [comment]
Выходит, что так.
Или как-нибудь код ответа менять до получения 304

**Comment by ameshkov** [comment]
Ну у нас есть задачка по сбросу кэша, можно ее и для андроида продублировать:
https://github.com/AdguardTeam/AdguardForWindows/issues/675

Можешь в андроидной ветке создать?

**Comment by Alex-302** [comment]
сделал
https://github.com/AdguardTeam/AdguardForWindows/issues/675

**Comment by Alex-302** [comment]
здесь закрою пока

**Comment by evgeniy-ADG** [comment]
LYC-118-41287
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13264042/08a8e988-da75-11e5-9543-ed14902b153e.png)

**Comment by Alex-302** [comment]
Вообще должно быть как минимум без картинок, просто пустые поля.

@ameshkov 
как такое может быть? Пропуски после блокировке этого же урла
http://ipic.su/img/img7/fs/kiss_44kb.1456344199.png
