### ISSUE TITLE
How to block all app requests from the same developer?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#81832]
hash? md5?
`developer name` & `developer name hash.md5` match?
`developer cert sign` & `developer cert sign hash.md5` match?

like these .apk sample:
https://github.com/motherboardgithub/bxaq/blob/master/base.apk
https://www.virustotal.com/gui/file/dc12d5c78117af8167d8e702dd131f838fe86930187542cf904b2122ba32afd1/details
![image](https://user-images.githubusercontent.com/75058881/116634409-82cf3580-a98e-11eb-9df2-871200c8dcd7.png)
![image](https://user-images.githubusercontent.com/75058881/116635011-413f8a00-a990-11eb-9c02-f376d5b77554.png)

https://www.virustotal.com/gui/file/a5d87370d81bfbd9c76ee1bfe938c591a41da1d260ae98b9dde17c4e64e5e5da/details
https://www.virustotal.com/gui/file/527b68a73f466a6cdc6fd05dd462700399cef6a974d748a28724322e7ea73e42/details
![image](https://user-images.githubusercontent.com/75058881/116635287-f3775180-a990-11eb-8fed-c926beb74928.png)

https://github.com/c2xusnpq6/anticult_list/blob/main/ChineseGOVTrackerList_Extreme.txt

and what if I want to block these:
app `name` included: `bestmind` or `fiberhome` or `fenghuo`
app `cert.sign.ou`,`cert sign.cn` included: `bestmind` or `fiberhome` or `fenghuo`
app `cert.sn` = `7119dd2f` and `b3998086d056cffa`
app `cert.hash` or `cert.thumbprint`? or `cert.fingerprint`? = `27196e386b875e76adf700e7ea84e4c6eee33dfa`
can you guys support this? it will be very veryyyyyyyyyyyyy useful for chinese user...... the whole world~ ^W^

( wait, i'm eating~ )

**Comment by Alex-302** [comment]
Тщю Better ask here
https://github.com/AdguardTeam/AdguardForAndroid/issues
