### ISSUE TITLE
https://www.finam.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by bconskri** [AdguardTeam/AdguardFilters#8189]
The graph won't load
Хочу оставить комментарий как инициатор обращения в AdGuard. @Alex-302 я не понял вашего ответа, что значит finam.ru в принципе не работает, так как это не какой-то мелкий сайт. Это как русский bloomberg, который зарабатывает на том, что люди смотрят у них графики и они у них работают!). Не знаю как в IE, но в Safari точно.
При обращении я оставлял сразу два скрина. Один, когда AdGuard включен и график не грузится и второй скрин, когда Adguard выключен и график грузится.
Собственно по сей день и пользуюсь таким способом - отключаю Adguard, чтобы посмотреть finam.ru - и все на сайте отображается корректно.
Кстати, при выключенном adguard но при использовании adguard dns тоже не работает график.

Прошу еще раз рассмотреть вопрос и помочь в решении проблемы

previous issue https://www.finam.ru/ - incorrect blocking

Actual behavior

Screenshot:
скрин когда в эту же минуту, что видно по часам adguard включен и ничего не работаетhttps://www.dropbox.com/s/3zeei6skhvq5jd0/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202017-12-07%20%D0%B2%2017.03.34.png?dl=0

скрин когда adguard выключен и все загружается
https://www.dropbox.com/s/ixsfh7sg4xy2tnn/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202017-12-07%20%D0%B2%2017.03.21.png?dl=0

Your environment

1670370

Adguard version: AdGuard for Mac 1.5.0
Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
DNS: Off

**Comment by vbagirov** [comment]
I have this no matter what: https://uploads.adguard.com/vbagirovyya03.png

Both with enabled and disabled AdGuard

**Comment by Alex-302** [comment]
У нас график не работает без Адгарда. Если у Вас работает, то могу удалённо глянуть.
Пока можете проверить такое правило:
```
@@||finam.ru^$elemhide
```

**Comment by bconskri** [comment]
Могу дать доступ через TeamViewer например. Проверил сейчас в Parallels в Windows IE у меня работает.
Вероятно у вас что-то с настройками безопасности java или с java как таковой

Вашу настройку подоткнул. не помогло

С уважением,
Родион Каргаполов





> 7 дек. 2017 г., в 18:44, Alex <notifications@github.com> написал(а):
> 
> @@||finam.ru <http://finam.ru/>^$elemhide

**Comment by bconskri** [comment]
Very strange. I think you have some problem with java security settings or java rte at all. 
I’ll test this issue on classic IE (not Edge) Windows 10 without adguard installed.
screenshot


С уважением,
Родион Каргаполов

**Comment by Alex-302** [comment]
> Могу дать доступ через TeamViewer например.

только ID и пароль здесь приводить не надо. Вы на форуме зарегистрированы?

**Comment by bconskri** [comment]
Не зарегистрирован. Даже не знаю про какой Вы форум).  Дайте пжл ссылку и инструкции что делать. 
Пароль временный и TV у меня постоянно не запущен в целях безопасности, так что нужно будет тогда по времени синхронизироваться, чтобы я выслал, а вы тут же посмотрели.
Можно мессанджером выслать. Например телеграмм

С уважением,
Родион Каргаполов

**Comment by Alex-302** [comment]
https://forum.adguard.com/
Телеграм тоже подходдит
https://4pda.ru/pages/go/?u=https%3A%2F%2Ftelegram.me%2Fadguard&e=34432486
`@Alex302`

**Comment by Alex-302** [comment]
@Stillness-2 @IvanIin 
можете удалённо глянуть или у себя повторить? Помогает только добавление сайта в исключения HTTPS. Фильтры никак не влияют.

**Comment by Alex-302** [comment]
Вроде повторилось. Здесь закрываю.

**Comment by bconskri** [comment]
Спасибо огромное. Временное решение от @Alex302 замечательно работает. 

С уважением,
Родион Каргаполов
