### ISSUE TITLE
chinese gov tracking app for chinese people (3)

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#81919]
https://github.com/c2xusnpq6/anticult_list/blob/main/chinese_gov_tracker_advanced.txt

https://github.com/c2xusnpq6/anticult_list/raw/main/chinese_gov_tracker_advanced.txt

https://github.com/AdguardTeam/AdguardFilters/issues/81687

https://github.com/AdguardTeam/AdguardFilters/issues/81622

**Comment by c2xusnpq6** [comment]
this is the final version, less misstake block. based on the packets sent by the tracking apps

**Comment by c2xusnpq6** [comment]
People don't like this, they are forced to install those tracking apps.
![image](https://user-images.githubusercontent.com/75058881/116759168-4a8a2e80-aa44-11eb-8f78-32e7a6fbc8ca.png)
![image](https://user-images.githubusercontent.com/75058881/116429263-4e695580-a878-11eb-9545-351544f82748.png)
![image](https://user-images.githubusercontent.com/75058881/116429153-32fe4a80-a878-11eb-8182-a031f515a442.png)

**Comment by c2xusnpq6** [comment]
@Alex-302

**Comment by c2xusnpq6** [comment]
ping?

**Comment by c2xusnpq6** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
@c2xusnpq6 Sorry but what to add/fix?

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 Sorry but what to add/fix? If you mean everything in the list, we prefer case by case report for each.

`ChineseGOVTrackerList_Extreme.txt` deprecated

`chinese_gov_tracker_advanced.txt` recommended version

**Comment by c2xusnpq6** [comment]
@Yuki2718 google or baidu search these apps: `com.fiberhome.wifiserver` `com.hicorenational.antifraud` `com.bestmind.antifraud` `com.bjxz.srhy`

and observe deeply and observe what they send outside

**Comment by c2xusnpq6** [comment]
![IMG_20210502_035732.jpg](https://user-images.githubusercontent.com/75058881/116793662-9bf4f500-aafa-11eb-84b4-223b33607f2d.jpg)

![IMG_20210502_035657.jpg](https://user-images.githubusercontent.com/75058881/116793664-9dbeb880-aafa-11eb-8273-8ef83ab354b4.jpg)

**Comment by c2xusnpq6** [comment]
ping?

**Comment by Alex-302** [comment]
> google or baidu search these apps: com.fiberhome.wifiserver com.hicorenational.antifraud com.bestmind.antifraud com.bjxz.srhy

I don't understand what do you want to do with these apps and why.
Please add descriptions for each.

**Comment by c2xusnpq6** [comment]
> > google or baidu search these apps: com.fiberhome.wifiserver com.hicorenational.antifraud com.bestmind.antifraud com.bjxz.srhy
> 
> I don't understand what do you want to do with these apps and why.
> Please add descriptions for each.

I want them to be disconnected with the outside world

**Comment by c2xusnpq6** [comment]
`$app=com.xxx.xxx,ask` ---> ask user that do you really want to block those app or not? it's better than... the list maker manages the entire rules, including some powerful and dangerous rules, which are too powerful...

**Comment by c2xusnpq6** [comment]
Or...ask the user's wishes first by default?

**Comment by c2xusnpq6** [comment]
Someone told me that I must delete this repository, I'm sorry
