### ISSUE TITLE
Fake site impersonating Netflix

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#82070]
Website passing through Netflix to pick up account and credit card dat
(The site has no verification with the Netflix database to verify the email/password is registered/password is valid.)

Fake: https://appnetflix.com
whois: https://www.namecheap.com/domains/whois/result?domain=appnetflix.com

Official: https://netflix.com

**Comment by krystian3w** [comment]
On my IPS is offline.

**Comment by eduardoaddad** [comment]
![Screenshot_20210502-151307_Samsung Internet.jpg](https://user-images.githubusercontent.com/16819380/116823088-ea38e100-ab58-11eb-942d-9cabb436b3ea.jpg)

For me it's still online (in Brazil)
DNS: AdGurd DNS

**Comment by krystian3w** [comment]
Still offline:

![obraz](https://user-images.githubusercontent.com/35370833/116829015-9fdc5200-aba2-11eb-88ea-c7a8475461fe.png)

**Comment by Alex-302** [comment]
It is dead.
