### ISSUE TITLE
Unable to view items in Shopping tab on Microsoft Bing iOS

### ISSUE THREAD

**Issue by errorsxp** [AdguardTeam/AdguardFilters#82075]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
If you open up the shopping tab using Microsoft’s search engine Bing.com and open an item you aren’t able to view the correct contents of the page

* **Expected behaviour**: 
Google’s Shopping page shows so this one should as well. This page should be given an exception because you search it voluntarily and normal search ads would be blocked.

***Steps to reproduce the problem***:
Open up an internet browser on a device that has AdGuard for iOS installed and search on Bing.com for a product. When you tap an item in the shopping tab, the contents on the page are mostly blocked. 

***System configuration***
Currently on iOS 14.5
**Filters:**
None

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version  | 14.5 
Browser:                               | Bing 
AdGuard version:                       | Latest
Filters enabled:                       | None
Simplified filters       |Off
AdGuard DNS:                           | Default

**Comment by Alex-302** [comment]
Hi. I don't see shopping tab. Please copy URL and make screenshot.

**Comment by errorsxp** [comment]
> Hi. I don't see shopping tab. Please copy URL and make screenshot.

Search for a good on Microsoft Bing and in the top menu there is Images, Videos, Maps, Shopping, etc. You have to make a search to see it.

**Comment by Alex-302** [comment]
> You have to make a search to see it.

I did it.

Please copy URL and make screenshot.

**Comment by errorsxp** [comment]
Can't do that on my device.

**Comment by errorsxp** [comment]
Actually, I found the url for the base site but I can’t do screenshots.
https://www.bing.com/shop

**Comment by Alex-302** [comment]
@errorsxp Hi. What I seewithout AdGuard on desktop:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/118705365-d364e080-b820-11eb-8015-a83466eefb73.png)
</details>

and on iOS:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/118706529-1ecbbe80-b822-11eb-82f4-0a2f7ef09182.png)

</details>

Does the site work es expected without AdGuard? Which filter causes it?(please try to disable filters on by one with check, but wait 20-30 seconds after each disabling/eanabling)

**Comment by errorsxp** [comment]
If you tap on the Shopping tab and tap on a product some images won't display and links wont work. I wish I could screenshot but my device is managed by an organization.

**Comment by Alex-302** [comment]
What about video, recorded by enother device?
Does it happen when DNS filtering disabled?
