### ISSUE TITLE
[nsfw][ads] http://fantasti.cc

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#8208]
**Site Sample** | 
----|
http://fantasti.cc/user/desomore/videos/upload/Shoplifter-gets-pounded-by-LP-officer-in-the-back-office/1572175

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ads

<details><summary><b>Screenshot:</b></summary>

![20171208-110353-001](https://user-images.githubusercontent.com/9846948/33760960-d360377c-dc07-11e7-91a1-adeb72a500eb.png)

</details><br/>

**Comment by BlazDT** [comment]
```
fantasti.cc##.right_column > .left-column-top-link:contains(SPONSOR)
||fantasti.cc/static/js/libs/exbl.js
||fantasti.cc/exbl.php
```
