### ISSUE TITLE
[nsfw] http://pornxs.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#8210]
http://pornxs.com

**Site Sample** | 
----|
http://pornxs.com/top10s/busty-grannies/?place=10&video_id=2624749

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Adleftover

### Fix

```
pornxs.com##.wrap
```

<details><summary><b>Screenshot:</b></summary>

![20171208-115031-001](https://user-images.githubusercontent.com/9846948/33762749-04880aea-dc0e-11e7-8c8f-8d5ee844c9d4.png)

</details><br/>

**Comment by BlazDT** [comment]
Also hid ad left-over on video and share buttons.
