### ISSUE TITLE
yle.fi

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#82190]
[https://areena.yle.fi/audio/1-50800984](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://areena.yle.fi/audio/1-50800984)
[https://arenan.yle.fi/audio/1-4473526](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://arenan.yle.fi/audio/1-4473526)

![sharebar](https://user-images.githubusercontent.com/35470489/116833983-7ca9a680-ab92-11eb-9b92-c6ea53557c64.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by adranger** [comment]
@Alex-302 They have different subdomains. The links that I posted are different.

**Comment by Alex-302** [comment]
Ok, changed.
