### ISSUE TITLE
openuserjs.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#82206]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
***URL(ANNOYANACE)***: https://openuserjs.org/scripts/darkred/Google_YouTube_search_link
![image](https://user-images.githubusercontent.com/76880977/116857406-621b1000-ac1a-11eb-96da-4d27adb49504.png)
![image](https://user-images.githubusercontent.com/76880977/116857438-7101c280-ac1a-11eb-93e4-943e7ca2fe7a.png)

![image](https://user-images.githubusercontent.com/76880977/116857421-67785a80-ac1a-11eb-8202-45d2cd9ca7dd.png)

**Comment by krystian3w** [comment]
`##.alert-dismissible`

 (bootstrap?) and Kiboke addon (IDCAC) uses click to close.
