### ISSUE TITLE
manual blocking cannot be reversed

### ISSUE THREAD

**Issue by 3ldritch147** [AdguardTeam/AdguardFilters#82230]
I blocked an element on a page for fun using the "block ads on this website" tool and I don't think there is a way to revert this other than pausing/disabling adguard

thanks in advance

**Comment by Yuki2718** [comment]
Hi, please go to User rules in Adguard settings and delete the created filter(s).

**Comment by 3ldritch147** [comment]
thank you

**Comment by Yuki2718** [comment]
You're welcome!
