### ISSUE TITLE
films-now и serials-now.ru прорвались майнеры

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#8227]
Майнеры на этих сайтах снова свободно делают свою дело.. на этот раз адреса сайтов рандомные.. если блочишь один, сайт тут же подключается к другому.. хорошо хоть все на одном домене пока)
*.space

![image](https://image.prntscr.com/image/FkKYQy_mS__FFmU-nFOdaw.jpg)

**Comment by Alex-302** [comment]
поправил
