### ISSUE TITLE
[AG Browser Extension] movies777.org - Pop-up

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardFilters#8234]
**Site**: https://movies777.org

**Issue**: Pop-up encountered on the page.

**Operating system**: Windows 7 (x86)
**Browser**: 63.0.3239.84 (Official Build) (32-bit)
**AdGuard version**:  AdGuard Browser Extension 2.7.2
**Filters enabled**: English, Spyware, Social Media & Annoyances, Mobile Ads & Malware Domains, Peter Lowe's list, Spam404
**User Filter**: None
Phishing and malware protection is enabled

**Comment by BlazDT** [comment]
Can't reproduce. Probably fixed by stun rule in English filter.
Can you please test again, thank you.

**Comment by clementine123** [comment]
Yes, I could not see the pop-up either :(
