### ISSUE TITLE
r1x.pw

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardFilters#8235]
**Site**: http://r1x.pw/HJxBz3

**Issue**: Adblock message seen

Screenshot: https://i.gyazo.com/6fc9e86f37bcf801c0a7875cc3b0642c.png

**Operating system**: Windows 7 (x86)
**Browser**: 63.0.3239.84 (Official Build) (32-bit)
**AdGuard version**:  AdGuard Browser Extension 2.7.2
**Filters enabled**: English, Spyware, Social Media & Annoyances, Mobile Ads & Malware Domains, Peter Lowe's list, Spam404
**User Filter**: None
Phishing and malware protection is enabled

**Comment by Alex-302** [comment]
done
