### ISSUE TITLE
Altibox.no - Broken functions (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#82370]
### Affected site:
`https://www.altibox.no/`

### Issue:
Various functions, like confirming your TV and/or internet subscription contents, doesn't work, due to a blocked cookie consent, which needs to be accepted!

(To reproduce, you need to be logged in to an account)

### Blocked assets:
```
https://policy.app.cookieinformation.com/*/altibox.no/*.js
https://policy.app.cookieinformation.com/uc.js
```

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rule:
`||policy*.cookieinformation.com^$third-party`

### Possible fix:
`@@||policy.app.cookieinformation.com^$script,domain=altibox.no`

### Other problem filters:
* **Easylist Cookie List** / **Fanboy's Annoyance List** ( https://github.com/easylist/easylist/issues/7805/ )
`###coiOverlay[role="banner"][style*="flex"]`
`||cookieinformation.com/*/*.js`

* **I don't care about cookies** _(NOTIFIED)_
`policy.app.cookieinformation.com$domain=~kartor.eniro.se|~kart.gulesider.no|~kort.degulesider.dk|~map.krak.dk|~babysam.dk|~minaftale.dk`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.2.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by THEtomaso** [comment]
> How to reproduce?

You can't, because like I pointed out; you need to have an account, be logged in, and even encounter specific situations.
Anyway, I was quite thorough, when narrowing the issue down, so you can add the fix in good conscience!

FYI; @DandelionSprout added a fix to his Nordic filters, a few days ago:
https://github.com/DandelionSprout/adfilt/blob/8e43eb3f32b9f57d10a9f8206f1b28d830d4ec33/NorwegianList.txt#L1650
https://github.com/DandelionSprout/adfilt/blob/8e43eb3f32b9f57d10a9f8206f1b28d830d4ec33/NorwegianList.txt#L1651
Don't know if he confirmed the issue himself, or simply took my word for it. :)

**Comment by Alex-302** [comment]
ok.

**Comment by THEtomaso** [comment]
@Alex-302:
A new fix is needed for '**AdGuard Cookie Notices filter**'.
Read my report here: https://github.com/uBlockOrigin/uAssets/issues/27748/

**Comment by Alex-302** [comment]
ok
