### ISSUE TITLE
How do I enable the blocking of self promotion using a uBlock Origin?

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#82417]
Hello. I'm currently using uBlock Origin with the base AdGuard filter enabled. I've noticed I'm seeing self promotional ads. I'm aware in the official AdGuard extension there is an option to disable self promotional ads. How would I do this in uBlock Origin?

Sorry if this isn't the right place to ask, I didn't know where else I would be able to ask a question like this.

**Comment by Andy-Kl** [comment]
you could ask here
https://www.reddit.com/r/uBlockOrigin/
or
https://github.com/gorhill/uBlock/issues

**Comment by krystian3w** [comment]
Allow self-promo is not embeded into AdGuard Base - this is another list with exceptions:

https://github.com/AdguardTeam/AdguardFilters/tree/master/UsefulAdsFilter/sections

So try delete subscribed "Filter unblocking search ads and self-promotion":

`raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt`
`https://filters.adtidy.org/extension/ublock/filters/10.txt`

And remove subscribed:

`https://easylist-downloads.adblockplus.org/exceptionrules.txt`

**Comment by zloyden** [comment]
@krystian3w gave you the full answer.
If we talk about our extension, you're right. It has an option that allows / disables useful ads.
