### ISSUE TITLE
chip.de ads

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#82457]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

Ad here: `https://www.chip.de/downloads/CCleaner_16317939.html`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![117204973-487ff100-adf1-11eb-8aae-081bc53c864e](https://user-images.githubusercontent.com/48647394/117206182-d27c8980-adf2-11eb-9d7d-23b78e230d85.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.5.34
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

possible filter: `static.chip-secured-download.de/*/$image`

**Comment by Morku** [comment]
@BlazDT 
It turned into an Ad placeholder:

<details><summary>Screenshot-1:</summary>

![chip2](https://user-images.githubusercontent.com/6276915/117266415-87479280-ae55-11eb-951e-74c251803781.png)


</details><br/>

**Comment by BlazDT** [comment]
And the ext-CSS rule not hiding it for you?

Please try this bit modified one:
`chip.de#?#body > div[id][align="center"]:has(> div[id][class] > div[id][class] > a[onclick] > img)`

**Comment by Morku** [comment]
@BlazDT 
Yes, this one works fine :)

**Comment by BlazDT** [comment]
Thanks for testing, changed rule.
