### ISSUE TITLE
imdb app (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#82563]
||video-ads.a2z.com^

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/118273198-59ed8b00-b4cc-11eb-8530-c86e9ab2135a.png)

**Comment by jordanelliott23** [comment]
@Alex-302 

go to this link: https://prod.entry.video-ads.a2z.com/2018-01-01/ads?lp=6f0af710-5d11-4914-a2fd-3b8150dfee1c&adUnit=imdb.us.web.desktop&maxd=30&pj=%7B%22CustomMacroContext%22%3A%7B%22PriorityVideoSource%22%3A%22true%22%7D%7D&slot=preroll&pid=0101d93d781a9d987e9d6675e7a218cbb846bc3a4bce6332cf3fcb4981fcaddb5fa6&vid=vi4226400281&ptner=imdb&ip=104.11.98.189&rt=vast3&prid=imdb&bp=preroll&mind=6&pt=all&sid=0101d93d781a9d987e9d6675e7a218cbb846bc3a4bce6332cf3fcb4981fcaddb5fa6&maxc=1&slots=%5B%7B%22s%22%3A%22320x180%22%2C%22mt%22%3A%22v%22%7D%5D&dplat=web&tkws=%7B%22tt%22%3A%22f%22%2C%22coo%22%3A%22us%22%2C%22clientId%22%3A%22imdb_web%22%2C%22resp%22%3A%22vast3%22%2C%22g%22%3A%22ac%7Cad%7Csf%7Cbaa%7Cth%7Cf%22%2C%22m%22%3A%22R%22%2C%22vi%22%3A%22_PLAYLISTINDEX_%22%2C%22u%22%3A%222464819031527585.5%22%2C%22vl%22%3A%22_PLAYLISTID_%22%2C%22mh%22%3A%22R%22%2C%22id%22%3A%22vi4226400281%7Ctt0293429%22%2C%22vt%22%3A%22_PLAYERTYPE_%22%2C%22ml%22%3A%22R%22%7D&geoc=US&uagent=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F90.0.4430.212%20Safari%2F537.36%20Edg%2F90.0.818.62

**Comment by Alex-302** [comment]
@jordanelliott23 Ok. Please describe how to reproduce that ad.

**Comment by jordanelliott23** [comment]
> @jordanelliott23 Ok. Please describe how to reproduce that ad.

i had to go on the pc and look in the adguard log. sorry.

**Comment by Alex-302** [comment]
Reproduced with US VPN.
Added for DNS users
`||prod.entry.video-ads.a2z.com^$third-party`
