### ISSUE TITLE
can you add this link in the annoyance filter?

### ISSUE THREAD

**Issue by noadsforall** [AdguardTeam/AdguardFilters#82583]
https://static.infoglobo.com.br/paywall/js/tiny.js 

can you add this link in the annoyance filter?

**Comment by chirag127** [comment]
1. example of sites that use this script?
2. what does blocking this do?

**Comment by BlazDT** [comment]
On infoglobo.com.br or globo.com.br I do not get that request.
If it is real paywall, it will not be blocked.

**Comment by zloyden** [comment]
It can be a real paywall. We can't add this without more information.
