### ISSUE TITLE
[android] DVGet - missed ads 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#826]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=43546656

**Comment by Alex-302** [comment]
Can't reproduce. Asked about options.

**Comment by Alex-302** [comment]
That was a cached ads.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/18365621/7118e45c-75e1-11e6-8c7c-1db2e216b933.png)
<details>
"androidVersion" : "6.0.1 (sdk=23)",
  "appLanguage" : "ru",
  "applicationId" : "82544d5a6722f754",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "HTC 10",
  "deviceSpeedRank" : 131,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 1, 11 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "NONE",

"sslMitmConfiguration" : "{\"mitmList\":\"980 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:87528; Traffic saved:2280252416;",
  "trial" : false,
  "updateChannel" : "BETA",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.7.220",
  "whitelist" : [ ]

**Comment by Alex-302** [comment]
встроено
