### ISSUE TITLE
ruhrnachrichten.de ads

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#82602]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

Ad picture: `https://www.ruhrnachrichten.de/bvb/musste-mich-pruegeln-otto-addo-ueber-rassismus-ein-bayern-angebot-und-kuriose-bvb-verhandlungen-1631272.html` and annoyance in page popup appearing after ~10 seconds

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1907" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/117443578-a10dd600-af38-11eb-92a4-f0798b1614f1.PNG">
annoyance:
<img width="791" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/117444100-46c14500-af39-11eb-997d-fd56c670f7a6.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.5.34
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Popup not reproduced.

**Comment by JobcenterTycoon** [comment]
Thanks. But the filter `
ruhrnachrichten.de###ctl00_ctl00_m_ctrlMainMasterContentPlaceHolder_m_ctrlMainContentPlaceHolder_ctl00_m_ctrlEditContainer` breaks articles on the page

example: `https://www.ruhrnachrichten.de/nachrichten/coronavirus-7-tage-inzidenz-liegt-unter-100-nrw-kratzt-an-wichtiger-marke-liveblog-plus-1537692.html`
