### ISSUE TITLE
Aliexpress - Incorrect bllocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8261]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Когда защита включена, захожу на сайт Aliexpress, кликаю на какой либо товар чтобы посмотреть подробности, но вместо того чтобы перейти на страницу товара, открывается новая вкладка со страницей авторизации " войти или зарегистрироваться " . Отключаю защиту Adguard , открываю алиэкспресс , выбираю товар, кликаю на него, открывается страница с описанием товара, всё работает как надо. При чем это происходит  в разных браузерах одинаково.

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | 0,1,2,6
Stealth mode options (Windows only)    | enabled
Helpdesk ID (if exists):               | 1680072

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Антитрекинг, наверное, накручен. Попроси скрины.

**Comment by Alex-302** [comment]
@iverkhohliad
