### ISSUE TITLE
[NSFW] http://xxxadultphoto.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#8269]
**Site Sample** | 
----|
http://xxxadultphoto.com/149-18-year-old-big-black-tits

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ads

<details><summary><b>Screenshot:</b></summary>

![20171210-083519-001](https://user-images.githubusercontent.com/9846948/33802981-26473296-dd85-11e7-8211-93dd791d4fe2.png)
![20171210-083532-001](https://user-images.githubusercontent.com/9846948/33802982-266a0078-dd85-11e7-9580-9917ec75d1cd.png)

</details><br/>

**Comment by AdamWr** [comment]
Fixed.
