### ISSUE TITLE
android app Messenger

### ISSUE THREAD

**Issue by gzenio22** [AdguardTeam/AdguardFilters#82716]
@AdamWr Od razu cię oznaczę bo po angielsku tego nie wyjaśnię a nie chce walić screnami z danymi userów 

w aplikacji messenger od Facebooka mam reklamy na liście kontaktów np allegro mimo zainstalowanej apki adguard na tel oczywiście z licencją 

Da sie to pozamiatać? :)

**Comment by chirag127** [comment]
Adguard on android can't filter encrypted app like Facebook, YouTube .
