### ISSUE TITLE
[ad][nsfw] pictoa.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#8272]
**Site Sample** | 
----|
https://www.pictoa.com/albums/curious-brunette-teenie-getting-ass-drilled-for-the-first-time-2825991/69204798.html

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ad text link above images gallery

### Fix 

```
pictoa.com###player > p.subtitle_wrapper:first-child
```

or

```
pictoa.com##.subtitle_wrapper
```

<details><summary><b>Screenshot:</b></summary>

![20171210-104447-001](https://user-images.githubusercontent.com/9846948/33803746-2f4c67aa-dd97-11e7-9e99-af59f1ca43a1.png)

</details><br/>

**Comment by AdamWr** [comment]
Added:
```
pictoa.com##a[href="https://www.pictoa.com/o/dating.html"]
pictoa.com###tab-gallery > a[href][target="_blank"][rel="nofollow"]
pictoa.com#%#Object.defineProperty(window, 'tiPopAction', { get: function() { throw null; }, set: function() { throw null; } });
```
