### ISSUE TITLE
slutsounds.com [ NSFW ]

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#82933]
***Description***:  https://www.slutsounds.com/slut-sounds-episode-1/ [ **NSFW** ] has ads + newsletter.

<details><summary>Screenshot[ **NSFW** ]:</summary>
https://user-images.githubusercontent.com/76880977/117720968-efeb9200-b1fc-11eb-86b6-b83c7c4cfe99.png
https://user-images.githubusercontent.com/76880977/117720973-f0842880-b1fc-11eb-9b49-30ee719c74d9.png
https://user-images.githubusercontent.com/76880977/117720974-f11cbf00-b1fc-11eb-8e78-ab8abbafbd0a.png
</details><br/>
![image](https://user-images.githubusercontent.com/76880977/117721005-fb3ebd80-b1fc-11eb-98e8-5f12cd596943.png)

**Comment by Alex-302** [comment]
Too few visitors. Blcoked ads only.
