### ISSUE TITLE
taiwan ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#82964]
```
||medialand.com.tw^$third-party
```
Medialand provides digital marketing solutions

**Comment by Alex-302** [comment]
Need the site where it is used.

**Comment by c2xusnpq6** [comment]
`dcard.tw` app

**Comment by Alex-302** [comment]
I don't see this domain in the log. Not sure about blocking.

**Comment by c2xusnpq6** [comment]
You need to click into a post before it will appear

**Comment by c2xusnpq6** [comment]
reopen pls
