### ISSUE TITLE
shopee tracker seller-log-collector.shopee.* & log-collector.shopee.*

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#82961]
https://www.google.com/search?q=%22log-collector.shopee%22
https://www.google.com/search?q=%22seller-log-collector.shopee%22
```
||log-collector.shopee.*
||log-collector.shopee.*.*
||seller-log-collector.shopee.*
||seller-log-collector.shopee.*.*
```

**Comment by Alex-302** [comment]
I see log-collector.shopee.co.id Did you see another TLDs?

**Comment by wout-codes** [comment]
From what I know, Shopee has different Top Level Domains. For example, `shopee.ph`, `shopee.cn`, `shopee.tw`, `shopee.id`. 

So I think it's better to add an asterisk (`||log-collector.shopee.co.id`).

Only sellers can reproduce this, `||seller-log-collector.shopee.*`

**Comment by c2xusnpq6** [comment]
ping?

**Comment by c2xusnpq6** [comment]
> Where is it used?

don't go google play, go apkpure.com

and search shoppe, you can see many different versions shopee app for different countries

**Comment by Alex-302** [comment]
Ok, added:
```
||log-collector.shopee.
||seller-log-collector.shopee.
```
