### ISSUE TITLE
boniu ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#82979]
https://www.boniu123.cc/ / https://www.boniu.club/ / https://boniushenghuo.com/ --> 

```
boniu123.cc##div.header_head:nth-child(3) > div.header_center > div.left_side:nth-child(14) > a > img
```

Chinese forum, the main users are Chinese in the Philippines

**Comment by Alex-302** [comment]
@c2xusnpq6 I don't see this element. Please check again and make screenshots.

**Comment by Alex-302** [comment]
This?
![image](https://user-images.githubusercontent.com/8361299/120374265-054a6c80-c322-11eb-8749-02af067a10b5.png)

**Comment by Alex-302** [comment]
Added
```
boniu123.cc##.left_side
boniu123.cc##.right_side
```

**Comment by c2xusnpq6** [comment]
> Added
> ```
> boniu123.cc##.left_side
> boniu123.cc##.right_side
> ```

one more thing.....

**Comment by c2xusnpq6** [comment]
I'll check it later
