### ISSUE TITLE
faceit tracker? analytics.faceitanalytics.com

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83029]
```
||analytics.faceitanalytics.com^
or
||faceitanalytics.com^
```

![image](https://user-images.githubusercontent.com/75058881/117929629-9cc62c00-b32f-11eb-96e8-3f67264bd8f8.png)

**Comment by sioxe823** [comment]
https://github.com/easylist/easylist/commit/178482ef966a6b74b600bb19dc9422704e0ad30c
