### ISSUE TITLE
chinese "Growing" tracker 

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83034]
growingio.com  gio.ren  datayi.cn growingio.cn giocdn.com growin.cn

![image](https://user-images.githubusercontent.com/75058881/117937740-e8310800-b338-11eb-9065-0ba7763505c9.png)
![image](https://user-images.githubusercontent.com/75058881/117937837-fbdc6e80-b338-11eb-83a5-fbbf8c8ef1c1.png)
![image](https://user-images.githubusercontent.com/75058881/117938364-891fc300-b339-11eb-907b-a714e858b4ca.png)

**Comment by c2xusnpq6** [comment]
All domains from the same company: @ryanbr 

![image](https://user-images.githubusercontent.com/75058881/118143577-16e4d680-b43e-11eb-8040-ad668743ecca.png)

**Comment by c2xusnpq6** [comment]
https://github.com/easylist/easylist/commit/185622149331e16d6bb3f88ba890304d7e12b507

https://github.com/easylist/easylist/commit/728aa1422feca07b06304356eee6959ecf33b491

**Comment by zloyden** [comment]
Added some domains, but for others can't find confirmation.
