### ISSUE TITLE
stackoverflow.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83058]
***Description***: https://stackoverflow.com/questions/67282121/removal-of-dynamically-generated-ads has a pop-up

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/117968887-529b7580-b344-11eb-9c47-c697d93f5fb3.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by Alex-302** [comment]
Already hidden
`stackoverflow.com###divQuestionFollowFeaturePopover`
