### ISSUE TITLE
airmore.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83073]
***Description***:  https://airmore.com/download has ad.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118011534-c43be980-b36d-11eb-9656-f3f427e37121.png)
![image](https://user-images.githubusercontent.com/76880977/118011540-c69e4380-b36d-11eb-8512-33ac7ca80de0.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by stanislav-atr** [comment]
Hi! These are already blocked by `airmore.com#?#.aside > section:has(> h5:contains(Ads))` of Base filter on my side.
