### ISSUE TITLE
sourceforge.net [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#83102]
https://sourceforge.net/directory/communications/streaming-comms/os:windows/

Seeing ads on the page. Checked with uBO with AG filters and others.

https://prnt.sc/12vbfwi

**Comment by wout-codes** [comment]
Add:
```
sourceforge.net##.can-truncate
||sf-syn.com/conversion_outbound_tracker$subdocument,domain=sourceforge.net
```
