### ISSUE TITLE
Taiwan Chunghwa Telecom ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83109]
`Referer: https://csapp.cht.com.tw/CustService/Web/payment-web.html` ---> https://csapp.cht.com.tw/CSAPP/SSO/dashboard/SiteCoreADItems

```
||csapp.cht.com.tw/CSAPP/SSO/dashboard/SiteCoreADItems^
```

![image](https://user-images.githubusercontent.com/75058881/118093549-2e04d380-b400-11eb-8a0f-ffacafc8932f.png)

![image](https://user-images.githubusercontent.com/75058881/118093501-1a596d00-b400-11eb-9fa5-a9b0db329ea1.png)

![image](https://user-images.githubusercontent.com/75058881/118093497-17f71300-b400-11eb-9c55-910456371be0.png)

**Comment by c2xusnpq6** [comment]
---> https://web-eshop.cdn.hinet.net/eShop%20Images/AD%20Banner/1280x720/202103021602-5_20210302160359.jpg
```
||web-eshop.cdn.hinet.net/eShop%20Images/AD%20Banner/^
or
||web-eshop.cdn.hinet.net/*/AD%20Banner/^
```
![image](https://user-images.githubusercontent.com/75058881/118093822-8fc53d80-b400-11eb-803c-b207d922be0e.png)

**Comment by Alex-302** [comment]
Is it third-party ad or self-promo?
How to reproduce? I can open https://csapp.cht.com.tw/CustService/Web/payment-web.html but I see no request with `SiteCoreADItems` Also please make screenshot of the page.

**Comment by c2xusnpq6** [comment]
self promo

very sorry but i forgot

**Comment by Alex-302** [comment]
Ok, better leave as is.
