### ISSUE TITLE
bancodesio.it

### ISSUE THREAD

**Issue by albertopasqualetto** [AdguardTeam/AdguardFilters#83128]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
# Issue URL:
bancodesio.it

***Description***:
The problem is because "https://www.bancodesio.it/sites/all/modules/eu_cookie_compliance/js/" is blocked because of the string "eu_cookie" in the url.
I resolved whitelisting all "bancodesio.it" url in uBlock"
(It is a bank website, so it is safe).

* **Current behaviour**: 

Popup "ACCESSO clienti" doesn't open and also accessibility options hidden.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/39854348/118126961-54734080-b3f9-11eb-82af-fa6a5515860a.png)
</details><br/>

* **Expected behaviour**: 

The popup opens on click, and accessibility options not hidden.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/39854348/118127087-8389b200-b3f9-11eb-8a5b-ee1f53944f85.png)
</details><br/>

***Steps to reproduce the problem***:

Try clicking and nothing happens.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Microsoft Edge (Chromium)
AdGuard product:       |"AdGuard Annoyances" filters in uBlock origin

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by albertopasqualetto** [comment]
It can be corrected by adding:
``` @@||bancodesio.it^$domain=bancodesio.it ```

Pull request in #83130

**Comment by krystian3w** [comment]
No better only allow load:


`||bancodesio.it/sites/all/modules/eu_cookie_compliance/$~third-party`

or add these:

```
/eu_cookie_$script,stylesheet
/eu_cookie_$script,stylesheet,domain=~bancodesio.it
```

**Comment by krystian3w** [comment]
No better only allow load:


`@@||bancodesio.it/sites/all/modules/eu_cookie_compliance/$~third-party`

or add these:

```diff
--- /eu_cookie_$script,stylesheet
+++ /eu_cookie_$script,stylesheet,domain=~bancodesio.it
```

in  `/AnnoyancesFilter/sections/cookies_general.txt`?

**Comment by albertopasqualetto** [comment]
Ok, I am not so expert, I tried watching to documentation for something easy.
So can you adjust it for me?

In anycase I am not sure this:

> No better only allow load:
> 
> `@@||bancodesio.it/sites/all/modules/eu_cookie_compliance/$~third-party`

 is correct for this case because the filter is about something in the same site, so it is not "third-party".

**Comment by krystian3w** [comment]
`~third-party` mean same to  in uBlock Origin syntax `1p`:

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#1p

**Comment by albertopasqualetto** [comment]
Thanks

**Comment by krystian3w** [comment]
I actually forgot that iOS doesn't know how to use `third-party`.

So for minimize allow load should enough path "bancodesio.it/sites/all/modules/eu_cookie_compliance/" or change into:

`$domain=bancodesio.it`
