### ISSUE TITLE
up.timipc.com tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83137]
`up.timipc.com` appears in my NextDNS log multiple times

i'm using mi gaming laptop btw

xiaomi = mi --> linked to --> timipc.com (Timi laptop/ Timi notebook)

xiaomi timi != tencent timi

I'm not sure, but you may be able to find what you need here:

https://c.mi.com/thread-2167081-1-0.html

https://www.mi.com/service/bijiben/drivers

https://www.mi.com/service/bijiben/drivers/game-2019

![image](https://user-images.githubusercontent.com/75058881/118154671-eb67e900-b449-11eb-839c-f9ee0c952b81.png)

**Comment by Alex-302** [comment]
I don't know. If you can collect HAR file, I will check it.
