### ISSUE TITLE
discudemy.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83132]
***Description***: https://www.discudemy.com/language/english has ad leftover.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118141694-43412880-b427-11eb-95c4-e8d55e617a3b.png)
![image](https://user-images.githubusercontent.com/76880977/118141727-52c07180-b427-11eb-8d21-12847b5c4774.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by krystian3w** [comment]
`#?#section.card > label ~ .adsbygoogle:upward(section)`

also

`#?#section.card > label ~ .adsbygoogle:upward(1)`

possible convert to older:

`#?#section.card:has(> label ~ .adsbygoogle:upward(section))` but upward may better due less section elements.
