### ISSUE TITLE
chinese umeng tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83162]
umeng --> company=北京锐讯灵通科技有限公司 --> taobao/alibaba
![image](https://user-images.githubusercontent.com/75058881/118194803-95606900-b47c-11eb-97d2-e5aaf83d9a23.png)
![image](https://user-images.githubusercontent.com/75058881/118194781-8974a700-b47c-11eb-8ea4-001f3bb47bad.png)

All domains of the same owner (yellow = not sure)
![image](https://user-images.githubusercontent.com/75058881/118194563-2a169700-b47c-11eb-9158-fcfecac90b06.png)

and there is no record of `umeng.co`, which is very interesting.............. because chinese company need to report to CN GOV what domains belong to them?? i'm not chinese so i'm not so sure about it......😅🤔
![image](https://user-images.githubusercontent.com/75058881/118195220-626aa500-b47d-11eb-9c4f-213c773af323.png)

**Comment by c2xusnpq6** [comment]
```
||umengcloud.com^
||umeng.com^
# ||umengcloud.com.gds.alibabadns.com^
# ||umeng.com.gds.alibabadns.com^
||umeng*.*.alibabadns.com^
||umeng*.alibabadns.com^
# ||umengjmacs.m.taobao.com^
# ||umengacs.m.taobao.com^
||umeng*.taobao.com^
||umeng*.*.taobao.com^
```

**Comment by Alex-302** [comment]
> umengcloud.com
> ||umeng.com^

we already have the necessary rules.

> ||umengcloud.com.gds.alibabadns.com^
> ||umeng.com.gds.alibabadns.com^
> ||umengjmacs.m.taobao.com^
> ||umengacs.m.taobao.com^

Added.
