### ISSUE TITLE
freepress.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83187]
***Description***: https://www.freepress.net/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118254527-d2524d00-b4c8-11eb-9d23-f6ebab3cb91d.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
We don't block such newsletters in the header / footer.
