### ISSUE TITLE
privateinternetaccess.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83233]
***Description***: https://www.privateinternetaccess.com/pages/linus-tech-tips/linus2 has a widget .

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118334659-a6b47e80-b52b-11eb-802e-eca5d6e78b71.png)
![image](https://user-images.githubusercontent.com/76880977/118334667-a87e4200-b52b-11eb-911d-7100b4d9d2fc.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by Alex-302** [comment]
Not sure about this.
