### ISSUE TITLE
arc.io untracking ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83262]
https://arc.io/ ---> `{your_website}/arc-sw.js`
```
/arc-sw.js
```
![image](https://user-images.githubusercontent.com/75058881/118351118-9680bb80-b58c-11eb-9780-da43be4c76af.png)

it's untracking ads, or.... just let it go? ha~

it just like coin miner, but lite version?

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118351416-8538ae80-b58e-11eb-8115-a3536597fada.png)

**Comment by c2xusnpq6** [comment]
one more... https://joinmassive.com/ lite coin miner

**Comment by Alex-302** [comment]
I don't see `/arc-sw.js` on https://joinmassive.com/

**Comment by Alex-302** [comment]
Where do you find an info about mining?

**Comment by c2xusnpq6** [comment]
> Where do you find an info about mining?

google search `"arc-sw.js"`, or... here is the link: https://www.google.com/search?q=%22arc-sw.js%22

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118694588-cc4ccb00-b83e-11eb-89cd-91ad14fe27c4.png)

https://arc.io/faq/

**Comment by Alex-302** [comment]
Not sure if it must be blcoked. It does nothing until you allow.
