### ISSUE TITLE
freehottip.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83265]
***Description***: https://freehottip.com/8EWN4Ay has a counter timer.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118353145-a6939d80-b582-11eb-82ab-98e7c1054bd6.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by AdamWr** [comment]
It seems that timer is checked on server side and can't be adjusted/boosted, because "Get Link" button will be broken.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/118786851-828dd000-b892-11eb-873a-aa8bc0b0b56e.png)

</details>

**Comment by chirag127** [comment]
Then how does this https://chrome.google.com/webstore/detail/auto-link-bypasser/doiagnjlaingkmdjlbfalakpnphfmnoh working perfectly. It even bypassed the captcha.

**Comment by AdamWr** [comment]
I mean that it can't be skipped with current scriptlets like for example this one - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#adjust-setInterval
If this extension works fine, then you can just use it.
