### ISSUE TITLE
Russian filter blocks FAPI script (inline Payment forms from fapi.cz)

### ISSUE THREAD

**Issue by Shimmi** [AdguardTeam/AdguardFilters#83311]
***Description***:
* **Current behaviour**: 

The Russian filter has a [general url rule `/script.php?id=$third-party`](https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/general_url.txt#L714) which has no domain filter and is pretty generic and blocks [fapi.cz](https://fapi.cz/) integration. I believe this rule can cause more harm than good given it's vague specification.

I found it out as it blocks payment form from fapi.cz which is [integrating using following snippet](https://napoveda.fapi.cz/article/75-vlozeni-prodejniho-formulare-na-web):
`<script type="text/javascript" src="https://form.fapi.cz/script.php?id=<<UUID>>"></script>`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3158339/118378629-690c3000-b5d5-11eb-91a6-4c823d8ca809.png)

</details><br/>

* **Expected behaviour**: 

The FAPI script is not being blocked and the FAPI payment form is rendered.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3158339/118378602-4aa63480-b5d5-11eb-8a25-0ec1f66805f4.png)</details><br/>

***Steps to reproduce the problem***:

1. Install Ad Guard
1. Enable Russian language filter
1. Go to https://www.rehabilitacnipodlozka.cz/#objednat (ERROR State: no form is shown)
1. Disable Russian language filter/or Ad Guard
1. Reload the page
1. The form is visible (OK State)

***System configuration***

**Filters:**

AdGuard Russian filter

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Operating system version (Android/iOS) | BigSur (11.2.3)
Browser:                               | Chrome (Version 90.0.4430.93 (Official Build) (x86_64))
AdGuard version:                       | 3.5.34
Filters enabled:                       | AdGuard Russian filter
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

**Comment by Alex-302** [comment]
Removed that rule(was added more that 5 years ago and it seems obsolete)
