### ISSUE TITLE
businessinsider.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83338]
***Url(ads)***: https://www.businessinsider.com/germany-has-an-arrogance-problem-2017-5?IR=T 

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118392035-00fd2e80-b655-11eb-9821-55adc6169466.png)
![image](https://user-images.githubusercontent.com/76880977/118392038-035f8880-b655-11eb-85d0-9b0d188a6592.png)
![image](https://user-images.githubusercontent.com/76880977/118392040-03f81f00-b655-11eb-8fbb-a271ce7b7a7e.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
Not reproduced on my end.
