### ISSUE TITLE
Create AdGuard URL Tracking filter

### ISSUE THREAD

**Issue by skypoc** [AdguardTeam/AdguardFilters#83344]
**These rules relate to popular url trackers, including Chinese social media sites, and Google searches.**

Contains the url tracking parameters for the following websites：

- iqiyi.com
- google.com
- bilibili.com
- taobao.com

```
$removeparam=spm_id_from
$removeparam=share_medium
$removeparam=share_plat
$removeparam=from
$removeparam=seid
$removeparam=client
$removeparam=newwindow
$removeparam=hl
$removeparam=source
$removeparam=share_source
$removeparam=share_tag
$removeparam=timestamp
$removeparam=unique_k
$removeparam=share_plat
$removeparam=sa
$removeparam=ved
$removeparam=biw
$removeparam=bih
$removeparam=dpr
$removeparam=vfrm
$removeparam=frmblk
$removeparam=vfrmrst
$removeparam=gs_lcp
$removeparam=ei
$removeparam=uact
$removeparam=sclient
$removeparam=stats_click
$removeparam=initiative_id
$removeparam=spm
```
------------------------------------- update-------------------------------------------
**amazon**
```
$removeparam=ref
$removeparam=pd_rd_wg
$removeparam=pd_rd_w
$removeparam=pd_rd_r
$removeparam=pf_rd_p
$removeparam=pf_rd_r
$removeparam=pf_rd_i
$removeparam=pf_rd_t
$removeparam=pf_rd_r
$removeparam=pf_rd_s
$removeparam=pf_rd_m
$removeparam=subject
```
 @Yuki2718

**Comment by krystian3w** [comment]
List exist: https://github.com/AdguardTeam/AdguardFilters/tree/master/TrackParamFilter/sections

**Comment by skypoc** [comment]
> List exist: https://github.com/AdguardTeam/AdguardFilters/tree/master/TrackParamFilter/sections
Thank you for your reply. But the list below is a new addition to mine.
```
$removeparam=spm_id_from
$removeparam=client
$removeparam=newwindow
$removeparam=hl
$removeparam=source
$removeparam=share_source
$removeparam=share_tag
$removeparam=timestamp
$removeparam=unique_k
$removeparam=share_plat
$removeparam=sa
$removeparam=ved
$removeparam=biw
$removeparam=bih
$removeparam=dpr
```

**Comment by krystian3w** [comment]
Maybe @Yuki2718 can help add some parametrs after many tests or need wait for Alex-302.

**Comment by Yuki2718** [comment]
This is beyond what I can decide, but more details will be welcome. Are all the parameter used in every pages of all the four sites? If not, please add Steps to reproduce for each parameter one by one or group by group. We need to check if they are really tracking parameter, and moreover, we have responsibility to ensure removing them doesn't affect functioning of the sites.

**Comment by skypoc** [comment]
> This is beyond what I can decide, but more details will be welcome. Are all the parameter used in every pages of all the four sites? If not, please add Steps to reproduce for each parameter one by one or group by group. We need to check if they are really tracking parameter, and moreover, we have responsibility to ensure removing them doesn't affect functioning of the sites.

Thank you for your response, I will provide more details within 24 hours and certify that the removal of these parameters will not affect the operation of the site :)

**Comment by krystian3w** [comment]
No I tested this and works fine after add into "AdGuard Annoyance":

`||google.*/search$queryprune=/^(bih|biw|client|dpr|ei|gs_lcp|iflsig|oq|sa|sclient|source|spell|uact|ved)/,domain=google.*`

**Comment by Yuki2718** [comment]
@skypoc Great, thanks!

>  I will provide more details within 24 hours

Don't need to too hurry, while the official AG members will start to work again around May 17 morning in GMT (next evening in CST Beijing time), it will take time for them to start review of this issue as there're too many issues opened as you see.

**Comment by skypoc** [comment]
> Now I tested this and works fine after add into "AdGuard Annoyance":

I'm glad they work (in fact I've tested them as I'm also an adblock plugin developer 😂)
Thank you for your test.

**Comment by skypoc** [comment]
thank you for all you do. 

> @skypoc Great, thanks!
> 
> > I will provide more details within 24 hours
> 
> Don't need to too hurry, while the official AG members will start to work again around May 17 morning in GMT (next evening in CST Beijing time), it will take time for them to start review of this issue as there're too many issues opened as you see.

Thank you for all you do. Adguard is the best ad blocking software available, thank you.

I don't live in China 😂
But anyway, I'll provide details as soon as I can.

**Comment by skypoc** [comment]
> @skypoc Great, thanks!
> 
> > I will provide more details within 24 hours
> 
> Don't need to too hurry, while the official AG members will start to work again around May 17 morning in GMT (next evening in CST Beijing time), it will take time for them to start review of this issue as there're too many issues opened as you see.

Hello,@Yuki2718 here are the details.

**bilibili.com**
`
A normal link (example)：https://www.bilibili.com/video/BV1oW411w7LA
After sharing with others, this link is added to the tracking parameters (example)：https://www.bilibili.com/video/BV1oW411w7LA?p=1&share_medium=iphone&share_plat=ios&share_source=COPY&share_tag=s_i&timestamp=1621142362&unique_k=exampleID

tracking parameters：

$removeparam=from
$removeparam=seid
$removeparam=spm_id_from
$removeparam=share_medium
$removeparam=share_plat
$removeparam=share_source
$removeparam=share_tag
$removeparam=timestamp
$removeparam=unique_k
$removeparam=share_plat

Removing these parameters will not affect the operation of the site
`
**//google.com**

@krystian3w has tested it, it has no impact of the site and the tracking parameters are blocked (thanks!)
`
||google.*/search$queryprune=/^(bih|biw|client|dpr|ei|gs_lcp|iflsig|oq|sa|sclient|source|spell|uact|ved)/,domain=google.*

$removeparam=client
$removeparam=newwindow
$removeparam=hl
$removeparam=sa
$removeparam=ved
$removeparam=biw
$removeparam=bih
$removeparam=dpr
$removeparam=gs_lcp
$removeparam=ei
$removeparam=uact
$removeparam=sclient
$removeparam=stats_click

`


**iqiyi.com**
```
A normal link (example)：https://www.iqiyi.com/v_kkyqtjybqs.html
After sharing with others(example)：https://www.iqiyi.com/v_kkyqtjybqs.html?vfrm=pcw_home&vfrmblk=D&vfrmrst=712211_focus_A_image1

tracking parameters：

$removeparam=vfrm
$removeparam=frmblk
$removeparam=vfrmrst

Removing these parameters will not affect the operation of the site

```

**taobao.com**
```
$removeparam=initiative_id
$removeparam=spm
```

As I am an adblocker developer, these tracking parameters I have tested in adguard and they are valid and do not affect the site.

**Comment by Yuki2718** [comment]
@Alex-302 I guess we need "URL parameter" tag or such.

**Comment by Yuki2718** [comment]
Google: 
`client` is on almost all searches and telling UA (e.g. firefox)
The below are if you navigate through search pages.
`source`: maybe source but encoded?
`bih`: window height
`biw`: width
`ved`, `ei`: encoded, IDK

**Comment by skypoc** [comment]
> Google:
> `client` is on almost all searches and telling UA (e.g. firefox)
> The below are if you navigate through search pages.
> `source`: maybe source but encoded?
> `bih`: window height
> `biw`: width
> `ved`, `ei`: encoded, IDK

yep,thank you!

**Comment by krystian3w** [comment]
But looks bad to share on forums, then work path with only `p=` or `tbm=nws`.

**Comment by chirag127** [comment]
Will this also include removing referral marketing (like amazon affiliate link parameters as https://gitlab.com/KevinRoebert/ClearUrls/ consider them as tracking parameters) parameters from the URLs?

**Comment by skypoc** [comment]
> Will this also include removing referral marketing (like amazon affiliate link parameters as https://gitlab.com/KevinRoebert/ClearUrls/ consider them as tracking parameters) parameters from the URLs?

Thank you for your advice. I will update the tracking parameters about amazon and ebay within 24 hours.

**Comment by Alex-302** [comment]
@Yuki2718 > I guess we need "URL parameter" tag or such.

We already have label `T: Stealth Mode issue`

**Comment by Alex-302** [comment]
Without URL it is a bad idea to strip parameters. At least for begining.
Please provide URLs with these parameters(or send to filters@adguard.com)

**Comment by chirag127** [comment]
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDYzVFlfSFBwYkFadHhkRkZqUVB3NnMtQ0FXd3xBQ3Jtc0tuOVc5cmRzT2JrYl9mRU00UzdISEpPejlBRi1EZ3hzVXNJLWhnbWpqeW9yY283QW45NlBWWTdfcWpUMDA1ZVUwUEVkQjJjWGJPUFVPLW90cFNjZFUxRjY0Q1c0VHlHNm1Sai14QkJ2NzVvMVp2QzZTdw&q=https%3A%2F%2Famzn.to%2F2McQ8Vs 
can be cleaned to
 https://amzn.to/2McQ8Vs 

https://www.amazon.in/gp/product/B07B43WPVK/ref=as_li_tl?ie=UTF8&camp=3638&creative=24630&creativeASIN=B07B43WPVK&linkCode=as2&tag=dhruvrathee-21&linkId=11cf18f3d7414ae272ae7a76920b349f 
can be cleaned to 
https://www.amazon.in/gp/product/B07B43WPVK .

https://unacademy.com/test-series/world-affairs-upsc-cse/N9L2OC7Q?shortlink=WorldAffairs&pid=UPSC%20CSE%20INT&c=UPSC%20CSE%20-%20WorldAffairs&deep_link_value=https://unacademy.com/test-series/world-affairs-upsc-cse/N9L2OC7Q
 can be cleaned to 
https://unacademy.com/test-series/world-affairs-upsc-cse/N9L2OC7Q

**Comment by krystian3w** [comment]
> `https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDYzVFlfSFBwYkFadHhkRkZqUVB3NnMtQ0FXd3xBQ3Jtc0tuOVc5cmRzT2JrYl9mRU00UzdISEpPejlBRi1EZ3hzVXNJLWhnbWpqeW9yY283QW45NlBWWTdfcWpUMDA1ZVUwUEVkQjJjWGJPUFVPLW90cFNjZFUxRjY0Q1c0VHlHNm1Sai14QkJ2NzVvMVp2QzZTdw&q=https%3A%2F%2Famzn.to%2F2McQ8Vs`
> can be cleaned to
> `https://amzn.to/2McQ8Vs`

domains no match, out of scope for safe `remove param`.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/83515 https://github.com/AdguardTeam/AdguardFilters/issues/83224

**Comment by Yuki2718** [comment]
Bilibili:

Only parameter I could find is `from` which simply tells where you're from when you click e.g. recommended articles, and similarly on search `from_source`.

**Comment by skypoc** [comment]
> Bilibili:
> 
> Only parameter I could find are `from` which simply tells where you're from when you click e.g. recommended articles and `seid` on clicking any search results. Similarly on search `from_source`. IDK where ohter proposed parameter are used.

The other parameters are added when sharing using the bilibili mobile client.
When using the bilibli mobile client to share, the api will convert the URL to a short URL: b23.tv. After restoring the short URL, you can see that a lot of tracking parameters have been added (exactly the ones I wrote)
api：https://api.bilibili.com/x/share/click
