### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83345]
***Url(annoyance)***: https://www.dropbox.com/s/5k5pm5f2xwbk7gb/soft-organizer-746-setup.exe
 
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118395032-d36cb100-b665-11eb-8079-201010a82fb7.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by brynnb** [comment]
This appears to still be an issue today.
