### ISSUE TITLE
tvfplay.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83386]
***Description***: https://tvfplay.com/show/permanent-roommates/3 has broken header

>second is without adgaurd
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118411260-42232c00-b6b1-11eb-9ffe-3d07d87c7818.png)
![image](https://user-images.githubusercontent.com/76880977/118411264-44858600-b6b1-11eb-964c-052d06819aa1.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
I guess without an account with subscription it can't be checked. Please provide it or anydesk (write a convenient time to the filters@adguard.com, I can connect from 9 am to 6 pm Moscow time). Have you checked the site only with AdGuard filters? If not, please leave only our filters and check the site again.
