### ISSUE TITLE
yourbittorrent2.com (cpu miner)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#83392]
||arc.io^

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://yourbittorrent2.com/torrent/15492907/ghost-adventures-season-7plete.html)

this is what it says when searching arc.io up: Basically, a tiny portion of your users' bandwidth and CPU will be used to power Arc's CDN

**Comment by jordanelliott23** [comment]
also fake stream and download buttons and ad leftover in the middle

**Comment by Yuki2718** [comment]
`arc.io` is now opt-in: https://github.com/uBlockOrigin/uAssets/pull/8874

**Comment by Yuki2718** [comment]
Addressed placeholder, I don't see fake buttons.
