### ISSUE TITLE
[anti-adblock-script] http://fm.tuba.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#8343]
**Site Sample** | 
----|
http://fm.tuba.pl/play/10/2/radio-tok-fm?appId=03

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Radio did not work. Blocked with anti-adblock-script. CC @AdamWr 

### HAR files
2 HAR files with enabled and disabled ADG.

[HAR.files.zip](https://github.com/AdguardTeam/AdguardFilters/files/1550704/HAR.files.zip)

<details><summary><b>Screenshot:</b></summary>

![20171212-085502-001](https://user-images.githubusercontent.com/9846948/33873150-2fb04818-df1a-11e7-92a4-473e75967fea.png)

</details><br/>

**Comment by AdamWr** [comment]
Fixed.
