### ISSUE TITLE
uderent.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83458]
***Description***: https://uderent.com/ detect adguard.

> Adding @@||uderent.com/js/prebid-ads.js$domain=uderent.com to user rules solves the issues to me

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/118566986-9c47ee00-b792-11eb-95ca-23ba890f9536.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
The site is currently unavailable.

**Comment by chirag127** [comment]
Use Indian VPN

**Comment by chirag127** [comment]
@zloyden site is available now .

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
