### ISSUE TITLE
googe url tracking param

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83515]
```
https://www.google.com/search?q=%22arc-sw.js%22&oq=%22arc-sw.js%22&aqs=edge&sourceid=chrome&ie=UTF-8

aqs? sourceid?
```

You can refer to this:
https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/master/data.min.json (Used by default on ClearURLs)
https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/master/data.json

**Comment by c2xusnpq6** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/83224

**Comment by Alex-302** [comment]
Duplicate.
