### ISSUE TITLE
problem with shopback app

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83531]
```
@@*$app=com.shopback.app (?)
@@||shopback.com^$stealth
@@||shopback.com^
@@||shopback.com^$document (?)

@@||shopback.com.tw^$stealth
@@||shopback.com.tw^
@@||shopback.com.tw^$document (?)

or...

@@||shopback.*^$stealth
@@||shopback.*^
@@||shopback.*^$document (?)
```

**Comment by Sergey-Lyapin** [comment]
Hello @c2xusnpq6 
Please describe the problem and specify a link to this app

**Comment by c2xusnpq6** [comment]
@Sergey-Lyapin 

https://apkpure.com/shopback-the-smarter-way-shopping-cashback/com.shopback.app

https://play.google.com/store/apps/details?id=com.shopback.app

**Comment by Sergey-Lyapin** [comment]
@c2xusnpq6 thank you, I installed the app, but what is the problem? 
Btw I was not able to sign in.

**Comment by c2xusnpq6** [comment]
@Sergey-Lyapin 
> ShopBack is the smarter way to shop online: we offer up to 30% cashback on all your online purchases

For this, it must be excluded from Adguard filtering
