### ISSUE TITLE
mooc problem

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83546]
https://github.com/AdguardTeam/AdguardFilters/blob/c3bbbe3ec921039f739cce6113c9416dd22a2b88/SpywareFilter/sections/general_url.txt#L73

pls undo https://github.com/AdguardTeam/AdguardFilters/commit/5b8a69c07f3e8d67d2041a19d8fe435ea2442f67

i'm very sorry 😅😅

**Comment by BlazDT** [comment]
Which page breaks?

**Comment by c2xusnpq6** [comment]
Used to obtain course information and tracking at the same time, so you can't stop it now

**Comment by c2xusnpq6** [comment]
ping?

**Comment by BlazDT** [comment]
That did not answer the question.

**Comment by c2xusnpq6** [comment]
> That did not answer the question.

it will break all the pages now

**Comment by Alex-302** [comment]
removed
