### ISSUE TITLE
Chinese made Anti-virus software "AVL" tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83661]
Chinese made Anti-virus software "AVL", and it has a close relationship with the Chinese government

AVL (for foreign markets) = 安天 (Its Chinese name) = antiy (Chinese pinyin)

pure APK download:
https://apkpure.com/avl/com.antiy.avl

Apps of the same developer:
https://apkpure.com/developer/AVL%20Mobile%20Security

`com.antiy.avl` APK `virustotal` report:
https://www.virustotal.com/gui/file/f45171c920bdab15a8b76568ae4bea4261b82bcb7d27291f99e3bbbb34bbda8a/relations

`avl` tracker:
```
logupdate.avlyun.sec.miui.com
us.log.slb.avlyun.com
log.avlyun.com

||logupdate.avlyun.sec.miui.com^
||log.slb.avlyun.com^
||log.avlyun.com^


tracker? (not sure):
log-abroad.avlyun.com
miuilog.update.avlyun.com
```

Other domains they own:
```
avlyun.net
avlyun.cn
avlsec.com
avlinsight.com
avlyun.com
avlyun.org

antiy.com
antiy.cn
antiy.net.cn
cloud-backup.com.cn
antiycloud.com

and these: (some may have expired)
machinecurity.org
avlvision.net
avlinsight.cn
avlincycle.cn
avlmetrics.org
avlinsight.org
avlmobilesec.com
avlsecure.com
avltrends.com
avl.mobi
avlvision.cn
avlmobsec.cn
machinecurity.cn
avlengine.org
machinecure.cn
avlsec.com
avlcdn.com.cn
avlscan.cn
avlyun.net
avlyun.com
mobileagle.org
avlincycle.org
avlvision.com
avlradar.com
avlyun.org
avlsec.mobi
avlindex.cn
avlsecurity.cn
avlengine.cn
avlindex.com
avlinside.org
machinecure.org
machinecure.com.cn
seceed.org
avlsecurity.net
avlteam.cn
avltomahawk.cn
avltrends.net
avlyun.cn
avlmobilesec.cn
avlsecure.cn
avlindex.net
avlinside.cn
avlmobilesec.net
avlstats.com (Maybe this is a tracker?)
avlsec.cn
avlsdk.cn
machinecurity.com.cn
antiymobile.cn
avlscan.org
avlmsec.cn
seceed.com.cn
avlmobilesecurity.cn
avlmetrics.cn
avlstats.net
avlsecure.net
```
![image](https://user-images.githubusercontent.com/75058881/119003359-3e005280-b9c0-11eb-9a75-d6e327a12f7e.png)

NextDNS log:
![image](https://user-images.githubusercontent.com/75058881/119003548-6425f280-b9c0-11eb-98aa-725f662381f2.png)

Apps of the same developer:
![image](https://user-images.githubusercontent.com/75058881/119002976-ecf05e80-b9bf-11eb-82c5-e2d90b09112c.png)

These are the companies that are using `AVL`:
![image](https://user-images.githubusercontent.com/75058881/119003073-05607900-b9c0-11eb-9778-e3d2dac95430.png)
![image](https://user-images.githubusercontent.com/75058881/119003115-0e514a80-b9c0-11eb-8c28-663c9b8f240a.png)

**Comment by c2xusnpq6** [comment]
If you want to block trackers for apps made in China, I suggest you download the non-GooglePlay version, because you can find more trackers there. (e.g. Chinese app store)

**Comment by c2xusnpq6** [comment]
I found out that it belongs to the owner of `CleanMaster`: `Cheetah Mobile`, and `Cheetah Mobile` belongs to `Kingsoft`, and `Kingsoft` is closely related to `Xiaomi`

**Comment by Alex-302** [comment]
added
```
||logupdate.avlyun.sec.miui.com^
||log.avlyun.sec.intl.miui.com^
||log.avlyun.com^
```
