### ISSUE TITLE
AliExpress.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#83668]
Не переключается язык с русского на (например) английский, если на сайт зайти в ПЕРВЫЙ РАЗ или предварительно удалить куки.
 Причина тому включённая опция "Самоуничтожение сторонних файлов cookies" в разделе "Антитрекинг".

<details><summary>Screenshot:</summary>

![2021 05 19-1](https://user-images.githubusercontent.com/17948007/118989006-59e90180-b98a-11eb-8e21-1a97075f87c7.png)
</details>

 Решение могло бы быть `@@||aliexpress.*$cookie`, но из-за [бага](../../AdguardBrowserExtension/issues/1511#issuecomment-845268965) пока не работает.

[https://aliexpress.ru](https://href.li/?https://aliexpress.ru)

___________________________________________________
 Adguard v3.5.34 | FireFox v78.10 ESR | Win7SP1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики
 Антитрекинг: Стандарт + Блокировка WebRTC

**Comment by XX-J** [comment]
> Проверил без Адгарда - повторяется. Проблема не из-за нас.

 Я проверял много раз и только что ещё раз - Без Adguard'a - ПЕРЕКЛЮЧАЕТСЯ с первого раза. Смотреть надо не на русский язык на странице, а на TLD - .COM. Проверял в режиме "Приватный просмотр", в котором у меня ни одно расширение не работает!

**Comment by Alex-302** [comment]
Не меняется TLD без Адгарда.

**Comment by XX-J** [comment]
Противоположные результаты - надо чтобы кто-нибудь ещё проверил...

**Comment by Alex-302** [comment]
@Sergey-Lyapin посмотри у себя.

**Comment by Sergey-Lyapin** [comment]
@XX-J  А какое значение в поле Самоуничтожение сторонних файлов cookies у вас стоит (у меня стандартное 2880)? и какие конкретно опции stealth mode включены? 
У меня язык переключается и перенаправляет на .com с включенным Адгардом

**Comment by XX-J** [comment]
> А какое значение в поле Самоуничтожение сторонних файлов cookies у вас стоит (у меня стандартное 2880)? и какие конкретно опции stealth mode включены?

 Написано-же:
> Антитрекинг: Стандарт + Блокировка WebRTC
__________
> У меня язык переключается и перенаправляет на .com с включенным Адгардом

 У меня тоже, НО либо после того как хоть РАЗ переключал язык УСПЕШНО, либо с отключенной опцией "Самоуничтожение сторонних файлов cookies".

**Comment by Sergey-Lyapin** [comment]
У меня переключается успешно с включенной опцией "Самоуничтожение сторонних файлов cookies", проверил на 2х компьютерах, с расширением и AG for Windows.

**Comment by XX-J** [comment]
Вы предварительно удаляли файлы cookie AliExpress'a и/или открывали сайт и переключали язык в "Приватном просмотре" с AdGuard'ом?

**Comment by Sergey-Lyapin** [comment]
Да, я в режиме инкогнито проверяю, в данный момент язык не переключается в Хроме, а в фаерфоксе переключается вне зависимости от Адгарда.

Нашел только один сценарий, когда Адгард влияет - если удалить вручную все куки в Фаерфоксе, то не переключается (причем в Хроме переключается в такой ситуации), но не думаю, что мы со своей стороны должны тут  что-то делать.

**Comment by XX-J** [comment]
> ...если удалить вручную все куки в Фаерфоксе...

 Удаление всех кук AliExpress'a  =  Первому заходу на AliExpress в новом профиле Firefox'a.  -  Об этом я и говорю.

> ...язык не переключается в Хроме, а в фаерфоксе переключается вне зависимости от Адгарда.
> ...если удалить вручную все куки в Фаерфоксе, то не переключается (причем в Хроме переключается в такой ситуации)...

 Но вообще странное поведение у этого сайта...
