### ISSUE TITLE
chinese smart tv tracker (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83678]
wait.... still doing research, i'll update later

---

According to the Chinese brand smart TV user and after analyzing the apk file provided by that user, it can be known that the following are likely to be trackers:

---

https://github.com/AdguardTeam/AdguardFilters/issues/81602

chinese smart tv - 创维电视(skyworth tv) tracker

```
gz-data.com (100% sure)
gzdata.com.cn (not sure)
gozendata.com

https://github.com/privacy-protection-tools/anti-AD/issues/402
https://github.com/privacy-protection-tools/anti-AD/issues/403
gzads.com
```

 Please refer to the article "My TV is monitoring all connected devices":
 https://www.v2ex.com/t/772523

 And these?
 https://gitee.com/bigdataleaveme/dontcollectme/raw/master/dontcollectme.txt

**Comment by Alex-302** [comment]
> gz-data.com (100% sure)

![image](https://user-images.githubusercontent.com/8361299/120372668-23af6880-c320-11eb-9cf4-68b304857756.png)

> gzads.com

![image](https://user-images.githubusercontent.com/8361299/120372736-37f36580-c320-11eb-94da-e5ba88a3dff3.png)

Domains are not working.

**Comment by c2xusnpq6** [comment]
reopen pls....

**Comment by Alex-302** [comment]
They are not working. Please show nslookup output from your location.
