### ISSUE TITLE
somd5.com tracker (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83674]
No. It's tracker!....

The only thing it needs is the final version of the string you type, not every character you type.

---

https://www.somd5.com/ ---> `https://www.somd5.com/tijiao.php?hash={every char you typed}`
tijiao.php --> tijiao (chinese) = submit
```
||somd5.com/tijiao.php^
```

**Comment by c2xusnpq6** [comment]
You can ask me to provide more information instead of closing the issue yourself.... thx 😅😃

**Comment by Alex-302** [comment]
In any case they will receiwe text entered by user.

**Comment by c2xusnpq6** [comment]
> In any case they will receive text entered by user.

reopen pls

**Comment by c2xusnpq6** [comment]
This is a md5 cracked website

**Comment by c2xusnpq6** [comment]
It will record every word the user enters in order to improve its service, but this is the same as google, not everyone wants to share data with it

**Comment by c2xusnpq6** [comment]
ping?
