### ISSUE TITLE
Shiftdelete—Obsolete rules

### ISSUE THREAD

**Issue by Erengit** [AdguardTeam/AdguardFilters#83670]
Shiftdelete now has a new design. So it seems current old rules not needed. I checked all rules. They don't show up in HTML and the filtering log.

**Ads**
```
shiftdelete.net##.empty-space.h40
shiftdelete.net##.banner_kutu
shiftdelete.net##iframe[src^="https://shiftdelete.net/assets/bannerz/"]
||shiftdelete.net/assets/bannerz/
shiftdelete.net##[id="300x600"]
shiftdelete.net##.banner_must_head
shiftdelete.net###adSelector
```

**Social**
```
shiftdelete.net##.v2Social_Shares > a[class]:not(._sreddit)
shiftdelete.net##div.yt 
shiftdelete.net##.toolbar-bottom 
~shiftdelete.net##.fa-youtube-square
shiftdelete.net##.social_share
```

**Annoyance**
```
shiftdelete.net##.e_magazine_mobile 
shiftdelete.net##img[title="Torrent Yasal mı? - ShiftDelete.Net"]
```

**Mobile**
```
shiftdelete.net##.top_banner_ad
shiftdelete.net##[class^="big_banner"]
shiftdelete.net##.mobile_ad_content
shiftdelete.net##iframe[src*="/getAd?"]
```

**Whitelist**
```
! https://github.com/AdguardTeam/AdguardFilters/issues/14124
@@||eotech-yoqblou5gqrdrn.netdna-ssl.com^$domain=shiftdelete.net
@@||shiftdelete.net/wp-content/themes/*_shiftdelete_net//app/mobile/dfp.js$domain=shiftdelete.net
```

**Spyware**
`||shiftdelete.net/api/banner_`

---

**Update**: This rule `shiftdelete.net##a[href^="https://www.hepsiburada.com/"] > img` doesn't work as expected. It just hides the thumbnail but ad is still there. I think it can be removed.

**Comment by krystian3w** [comment]
`shiftdelete.net##a[href^="https://www.hepsiburada.com/"] > img` possible use `:upward(1)` and maybe again works.

```css
shiftdelete.net#?#a[href^="https://www.hepsiburada.com/"] > img:upward(1)
```

or older `:has(> )`:

```css
shiftdelete.net#?#a[href^="https://www.hepsiburada.com/"]:has(> img)
```

but this exclude hide ads on iOS/iPadOS and Android Content Blocker "plugin".

**Comment by Alex-302** [comment]
> **Update**: This rule `shiftdelete.net##a[href^="https://www.hepsiburada.com/"] > img` doesn't work as expected. It just hides the thumbnail but ad is still there. I think it can be removed.

Works fine on my end. Please make screenshot.

**Comment by Erengit** [comment]
@Alex-302 

**Behavior when rule is enable:**

<details><summary>Screenshot</summary>
 
![s1](https://user-images.githubusercontent.com/79805068/120712500-606a9380-c4c9-11eb-877f-4ecb16aecbd8.png)


</details>

**Behavior when rule is disabled:**

<details><summary>Screenshot</summary>
 
![s2](https://user-images.githubusercontent.com/79805068/120712520-682a3800-c4c9-11eb-841c-ead6264ebb60.png)


</details>

---

I just checked in desktop version. Maybe it works on mobile, I don't know

**Comment by krystian3w** [comment]
Maybe on PC this will be good:
```
##.thb-article-bottom-ad
##.thb-article-bottom-ad + thb-sponsored-content-container
```

**Comment by Alex-302** [comment]
@Erengit Please provide URL and full screenshot. I don't see unblocked ads on iPad.

**Comment by Alex-302** [comment]
> Maybe on PC this will be good:

that elements already hidden.

**Comment by krystian3w** [comment]
Not on `Erengit`, maybe he disabled AdGuard Turkey before exclude bug with hide only photos.

**Comment by Alex-302** [comment]
Will wait his reply.

**Comment by Erengit** [comment]
@Alex-302 

First, add whitelist these two rules:
```
shiftdelete.net#@#.thb-article-bottom-ad
shiftdelete.net#@#.thb-sponsored-content-container
```

---

Click the link below:
https://shiftdelete.net/kripto-paralar-neden-dusuyor

---

There is an advert at the bottom of the article that directs you to Hepsiburada.

<details><summary>Image</summary>

 
![s3](https://user-images.githubusercontent.com/74098460/120865866-83fc0f80-c597-11eb-9c9c-4dc9e5772b5d.png)


</details>

---

This rule only blocks the thumbnails of the ad. `##a[href^="https://www.hepsiburada.com/"] > img`

**When rule is enable:**

<details><summary>Image</summary>

 
![s1](https://user-images.githubusercontent.com/74098460/120865989-c45b8d80-c597-11eb-9214-5f1f6c3aa216.png)


</details>

---

**When the rule is disabled:**

<details><summary>Image</summary>

 
![s2](https://user-images.githubusercontent.com/74098460/120868829-924d2a00-c59d-11eb-83fd-803fbb626fa8.png)


</details>

Thumbnails appear when you disable rule. `#@#a[href^="https://www.hepsiburada.com/"] > img`

---


So actually this rule is not needed because the ad is already blocked by `##.thb-article-bottom-ad` and `##.thb-sponsored-content-container`

**Comment by krystian3w** [comment]
Maybe older plugin not used `thb-article-bottom-ad` and on a few urls is active?

**Comment by Alex-302** [comment]
ok
