### ISSUE TITLE
Mega Application android

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#83722]
For some reason, on my mobile (samsung note 8)
Mega App is unable to connect with adguard on
Can u check?

**Comment by Sergey-Lyapin** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3863](https://github.com/AdguardTeam/AdguardForAndroid/issues/3863) via [**ZenHub**](https://www.zenhub.com/)
