### ISSUE TITLE
Turkey - Turkcell VoWifi new ip address

### ISSUE THREAD

**Issue by bymcs** [AdguardTeam/AdguardFilters#83734]
Hello Turkcell is using a new VoWifi ip address and it does not work with Adguard enabled.
I want you to add this.

new adress : 188.59.227.1:4500
                     188.59.228.1:4500

**Comment by krystian3w** [comment]
Try add allow rule:

`@@||188.*.*.*:4500^`

to user rules Filter (maybe later to DNS user rules Filter).

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3864](https://github.com/AdguardTeam/AdguardForAndroid/issues/3864) via [**ZenHub**](https://www.zenhub.com/)
