### ISSUE TITLE
ripe.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83748]
***Issue URL (Ads)***: https://atlas.ripe.net/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/119158849-4914ba80-ba74-11eb-988b-4d08c13f7d27.png)
![image](https://user-images.githubusercontent.com/76880977/119158859-4b771480-ba74-11eb-9c78-f40c2e73c467.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
Not an ad.
