### ISSUE TITLE
gamevicio.com

### ISSUE THREAD

**Issue by user0050** [AdguardTeam/AdguardFilters#83741]
**Description:**

Some ads that have not been blocked

```
gamevicio.com##.header-logo-extra
gamevicio.com##.hasBgApb:style(margin-top: 0px !important;)
gamevicio.com##[class^="bgApbContent"]
gamevicio.com##.slice-ad-footer
```
![1](https://user-images.githubusercontent.com/84577151/119145730-4daf8380-ba20-11eb-8914-f1d84d769ebf.PNG)

**List of subscriptions:**
```
EasyList
AdGuard Base 
AdGuard Mobile Ads
Peter Lowe's Blocklist
AdGuard Tracking Protection
EasyPrivacy
Fanboy's Enhanced Tracking List
AdGuard Annoyances
AdGuard Social Media
Fanboy’s Annoyance
Online Malicious URL Blocklist
Spam404
spa, por: AdGuard Spanish/Portuguese
AdGuard Russian filter
CHN: AdGuard Chinese (中文)
JPN: AdGuard Japanese
```

**OS/version**: Windows 10 x64 20H2
**Browser/version**: Google Chrome 90.0.4430.212
**Adblock Extension/version**: uBlock Origin 1.35.2

**Comment by AdamWr** [comment]
Added (update should be available in 1-2 hours), thank you.
