### ISSUE TITLE
sourcegraph.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83744]
***Issue URL (Annoyance)***: https://sourcegraph.com/github.com/Cookie-AutoDelete/Cookie-AutoDelete

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/119152593-14056980-ba6e-11eb-8b7d-d1ae67ae9643.png)
![image](https://user-images.githubusercontent.com/76880977/119152601-1667c380-ba6e-11eb-8f9c-2d19ca9d3b3d.png)
</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
We don't block tooltips.
