### ISSUE TITLE
shopee tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#83751]
https://github.com/search?q=org%3AAdguardTeam+%22__t__%22&type=code

https://github.com/AdguardTeam/FiltersRegistry/blob/fff490854931445cfce4db4a1409933dbcb573ba/filters/ThirdParty/filter_202_Adblock-Thai/filter.txt#L607-L612

tracker:
```
||akamaihd.net/shopee/*/*TrackingRules$script,domain=shopee.*
||akamaihd.net/shopee/*/TrackingRules$script,domain=shopee.*
||shopee.*/__t__$xmlhttprequest
||shopee.*/userstats_record$xmlhttprequest
||shopeemobile.com/*/tr$xmlhttprequest
```
![image](https://user-images.githubusercontent.com/75058881/119168746-d0bdf180-ba93-11eb-8310-be4f0b668cf0.png)

**Comment by Alex-302** [comment]
Not sure about it. If you have a HAR file, pelase send to filters@adguard.com
