### ISSUE TITLE
YouTube ads getting through (iOS safari)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#83775]
Ive been having this isssue for weeks now. I’m guessing YouTube updated their ad system. Weirdly I have the same exact filters on my pc using AdGuard extension in Microsoft edge and I get no ads. These ads i reproduced on my iPad and two iPhones with the exact same filters.

screeenshots:

https://ibb.co/3BVJMfJ
https://ibb.co/kmf8YhJ

**Comment by wout-codes** [comment]
Read the manual of `Block YouTube Ads in Safari on iPhone/iPad`: https://github.com/AdguardTeam/BlockYouTubeAdsShortcut

**Comment by jordanelliott23** [comment]
> Read the manual of `Block YouTube Ads in Safari on iPhone/iPad`: https://github.com/AdguardTeam/BlockYouTubeAdsShortcut

thanks
