### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardFilters#8378]
Expectation: Remove the annoy banner tell you to view in the reddit app

Filter: Safari, Mobile Ads, Annoyance, English, ABPVN

Device: Adguard iOS

Screenshot: https://user-images.githubusercontent.com/33868262/33826392-1f67fde4-de65-11e7-8dc7-bbbd6db937bb.jpeg

**Comment by Alex-302** [comment]
Please fill the template or create report using online tool:
https://reports.adguard.com/new_issue.html
