### ISSUE TITLE
helpdeskgeek.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#83847]
***Issue URL (Ads)***: https://helpdeskgeek.com/help-desk/google-chrome-crashing-freezing-or-not-responding-7-ways-to-fix-it/

I propose `helpdeskgeek.com##[id^="adngin"]` .
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/119261801-a0429880-bbf6-11eb-9a0d-88d97403d878.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by Pyae224** [comment]
How to find premium mod app for X-vpn-version-154
![Screenshot_20210523_201138](https://user-images.githubusercontent.com/84670376/119262991-43011400-bc03-11eb-89df-e3d411b32884.jpg)

**Comment by zloyden** [comment]
> How to find premium mod app for X-vpn-version-154

To do this, you should use special forums, but I recommend our [AdGuard VPN](https://adguard-vpn.com/en/welcome.html).

**Comment by chirag127** [comment]
What the hell I thought you will remove this ,but you just asked him to go to special forum . 😂😂

**Comment by chirag127** [comment]
Is that necessary to add div before [id^="adngin"] ?

**Comment by zloyden** [comment]
> Is that necessary to add div before [id^="adngin"] ?

Yes, there are only such elements.
