### ISSUE TITLE
Improve crypto-miners detection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#8391]
http://goodkino.biz/publ/serialy/gotehm_4_sezon_12/1-1-0-9407
gridcash.net/igrid.org

**Comment by ameshkov** [comment]
@Alex-302 their domain:
`gridiogrid.com`

**Comment by ameshkov** [comment]
They plan to switch domains quite often, the current domain is always here:
https://gridcash.net/instat.php?r=1&d=2

Regarding detection, it'd be hard and I'd better avoid it for now (unless they're popular enough).

**Comment by Alex-302** [comment]
Ok, blocked it.
