### ISSUE TITLE
meteoblue.com (Filter suggestion)

### ISSUE THREAD

**Issue by pas-calc** [AdguardTeam/AdguardFilters#83914]
Filter suggestion: remove GDPR message and make body scrollable on meteoblue.com
```
! https://www.meteoblue.com : remove GDPR message and make body scrollable
meteoblue.com##.gdpr_message
meteoblue.com##body:style(overflow:auto!important)
```

**Comment by krystian3w** [comment]
AG need these syntax:

```
meteoblue.com#$#.gdpr_message { display: none !important; }
meteoblue.com#$#body {overflow: auto !important }
```

other story is change `overflow: auto` to value `visible` or `intial` (sometimes works better than auto).

**Comment by krystian3w** [comment]
PS. project Polsh Cookie-GDPR added long time ago this:

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/c37fb01d4f712c00849d5dc9135c981e08cd51a0

**Comment by Alex-302** [comment]
Added to our filter.
