### ISSUE TITLE
Adguard Family DNS Bild.de again not working

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#8392]
@jonathanmmm commented on [Wed Dec 13 2017](https://github.com/AdguardTeam/AdguardDNS/issues/213)

Hello,

Bild.de is still not working and showing adblocking in family adguard dns

ww251.smartadserver.com is blocked, maybe that`s another server.

Please can you check if there is any difference in adguard family and normal adguard dns regarding Bild.de?

Because with the normal dns all is working fine.

**Comment by vozersky** [comment]
paywall at http://www.bild.de/ with dns family protection

**Comment by Alex-302** [comment]
it must be blocked by family adguard dns
