### ISSUE TITLE
continental.ru

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#83943]
Не работает скролл на сайте https://www.continental.ru/car Если выключить AdGuard, то появляется сообщение о принятии кук, похоже оно мешает.

Application version: 2.5.3.955 release (CL-1.7.200)
Network Service Type: NetworkExtension

Filters subscriptions:
ID=2 Name="AdGuard Base filter" Version=2.1.77.29
ID=3 Name="AdGuard Tracking Protection filter" Version=2.0.24.81
ID=4 Name="AdGuard Social Media filter" Version=2.0.40.55
ID=14 Name="AdGuard Annoyances filter" Version=2.0.81.55
ID=10 Name="Filter unblocking search ads and self-promotion" Version=2.0.1.37
ID=1 Name="AdGuard Russian filter" Version=2.0.53.39
ID=6 Name="AdGuard German filter" Version=2.0.19.46
ID=7 Name="AdGuard Japanese filter" Version=2.0.8.32
ID=8 Name="AdGuard Dutch filter" Version=2.0.1.31
ID=9 Name="AdGuard Spanish/Portuguese filter" Version=2.0.9.59
ID=16 Name="AdGuard French filter" Version=2.0.28.24
ID=224 Name="AdGuard Chinese filter" Version=2.0.25.69
ID=108 Name="EasyList Hebrew" Version=2.0.3.67
ID=109 Name="EasyList Italy" Version=2.0.88.12
ID=110 Name="EasyList Lithuania" Version=2.0.1.41
ID=111 Name="Latvian List" Version=2.0.0.45
ID=112 Name="Liste AR" Version=2.0.88.11
ID=119 Name="Icelandic ABP List" Version=2.0.0.7
ID=233 Name="Adblock List for Finland" Version=2.0.4.40
ID=0 Name="User rules" Version=0.0.0.0

**Comment by Alex-302** [comment]
Fixed
