### ISSUE TITLE
Can’t load The Daily podcast in Pocket Casts

### ISSUE THREAD

**Issue by ShamylZakariya** [AdguardTeam/AdguardFilters#83972]
The Pocket Cast app was able to load The Daily (New York Times daily podcast) until recently. Now it fails to download or stream, unless AdGuard is disabled.

**Comment by AdamWr** [comment]
Hi,

If I'm not wrong, this issue has been fixed two days ago - https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/677
Do you still can reproduce that problem?

**Comment by ShamylZakariya** [comment]
Yes, I've been able to download the Daily twice - which seems encouraging and not just a fluke. Closing.
