### ISSUE TITLE
куражбамбей.рф

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/AdguardFilters#8399]
http://куражбамбей.рф/serial-teoriya-bolshogo-vzryva-11-sezon-3-seriya.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](http://images.vfl.ru/ii/1513198325/bc4b0ed7/19796297.png)
</details><br/>

Information                            | Value
---                                    | ---
Operating system:                      | Win
Browser:                               | Mozilla Firefox 57.0.2
AdGuard version:                       | 6.2.437.2171
Filters:                       | English, Spyware, Social media, Annoyances, Russian, Experimental

**Comment by Smorvel** [comment]
Подключи RuAdlist и не будет.

**Comment by Alex-302** [comment]
Поправил.

**Comment by zovihuxij** [comment]
@Smorvel , к чему этот совет? Зачем мне подключать сторонние фильтры?
