### ISSUE TITLE
one.google.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84000]
***Issue URL (Annoyance)***: https://one.google.com/benefits?hl=en

I tried to block it with adguard but only ublock  can block iframe . please add this function to adguard too.
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/119624981-54c30100-be27-11eb-8fac-0ee9702cd5de.png)
![image](https://user-images.githubusercontent.com/76880977/119624988-57bdf180-be27-11eb-8eb5-1c8c617dbe7f.png)
![image](https://user-images.githubusercontent.com/76880977/119624997-5a204b80-be27-11eb-8a86-cbd01d0e0200.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by krystian3w** [comment]
Also I have `#google-hats-survey`.

**Comment by chirag127** [comment]
I can still reproduce . Are you logged in ?


<details><summary>Screenshots:</summary>



![image](https://user-images.githubusercontent.com/76880977/120357267-df719780-c322-11eb-8a40-98834eb37715.png)

</details><br/>

**Comment by krystian3w** [comment]
Maybe no enforced English and tried on Russian interface - then may be not loaded at all.

**Comment by Alex-302** [comment]
Logged in
![image](https://user-images.githubusercontent.com/8361299/120363147-797e1380-c314-11eb-97ab-487885b7b313.png)
Interface is English.
