### ISSUE TITLE
trakt.tv надоедливая кнопка магазина

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#8407]
Предлагаю в фильтр раздражителей сунуть это:
<details><summary>Скрин:</summary>

![image](https://image.prntscr.com/image/KeN2JADmTaeZQyz6gJ8Z-A.jpg)
</details><br/>
С недавнего времени появилась кнопка shop и с нею вместе это сообщение. Стоит ее только зацепить мышкой как оно тут же всплывает. Если не хотите блокировать саму кнопку, то хотя бы это сообщение уберите.

**Comment by Alex-302** [comment]
Думаю с ней можно смириться.
