### ISSUE TITLE
Параметры отслеживания `source_type`, `workflow`, `study`, `service`, `product` для `magazine.skyeng.ru`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardFilters#84094]
Пожалуйста, добавьте в фильтр https://github.com/AdguardTeam/AdguardFilters/blob/master/TrackParamFilter/sections/specific.txt удаление парамеров отслеживания для [Skyeng Magazine](https://magazine.skyeng.ru/) таких, как `source_type`, `workflow`, `study`, `service`, `product`. Примеры страниц сайта:
- https://magazine.skyeng.ru/lichnyj-opyt-ja-stala-professionalnoj-perevodchicej-iz-za-ljubvi-k-serialu/?source_type=magazine&workflow=adults&study=individual&service=english&product=magazine
- https://magazine.skyeng.ru/?source_type=magazine&workflow=adults&study=individual&product=magazine&service=english

**Comment by Alex-302** [comment]
Оно ничего не трекает. Есть другие ссылки?

**Comment by rakleed** [comment]
Других ссылок нет. А почему эти параметры ничего не трекают?

**Comment by Alex-302** [comment]
Они у всех ссылок одинаковы. Откуда пришел - по этим параметрам не понять.
