### ISSUE TITLE
polish annoyance filters

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/AdguardFilters#8413]
Polskie filtry annoyances

this list
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/PPB.txt

**Comment by Alex-302** [comment]
Why do you close it?)

**Comment by Alex-302** [comment]
@AdamWr could you check this filter? Is it useful?

**Comment by AdamWr** [comment]
It is like AdGuard Annoyances filter, but for Polish websites, so I think it is useful.

**Comment by Alex-302** [comment]
Ok, we will add it, but a bit later.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #8](https://github.com/AdguardTeam/FiltersRegistry/issues/8) via [**ZenHub**](https://www.zenhub.com/)
