### ISSUE TITLE
glassdoor.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#84215]
[https://www.glassdoor.com/Overview/Working-at-Northwestern-University-EI_IE3919.11,34.htm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.glassdoor.com/Overview/Working-at-Northwestern-University-EI_IE3919.11,34.htm)

Overlay annoyance. If you don't get the overlay after opening it for the first time, click on `Reviews` to change the page and see it.

This affects their `glassdoor.*` international domains too.

![glassdoor](https://user-images.githubusercontent.com/35470489/120020061-9f778100-bfbf-11eb-9352-d9b219ab2ef3.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Yuki2718** [comment]
I wonder if `||glassdoor.com/app/static/js/dist/gd-user-hardsell-overlay.` is safe. Needs to be thoroughly tested.

**Comment by Alex-302** [comment]
It seems nothing is broken.
