### ISSUE TITLE
AdGuard Tracking Protection and SearchPreview plugin

### ISSUE THREAD

**Issue by Nova900** [AdguardTeam/AdguardFilters#84211]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: uBlock Origin blocks SearchPreview images when AdGuard Tracking Protection filter is active
* **Current behaviour**:

I use the uBlock Origin with this Filter and the SearchPreview plugin which shows small images of websites to the side of search results in Google and other sites. These apparently get blocked by the AdguardFilter or some interaction with it. Weirdly it works fine in Firefox, but not in Chrome

<details><summary>Screenshot:</summary>

![image](https://s20.directupload.net/images/210528/abvz6y2x.png)
</details><br/>

* **Expected behaviour**:

The images from SearchPreview are the main feature of the plugin and should not be blocked. Any privacy risks of loading these pictures from a third-party server are inherent to the way the plugin works, there's no realistic alternative to that.

<details><summary>Screenshot:</summary>

![image](https://s20.directupload.net/images/210528/qgzbr6g3.png)
</details><br/>

***Steps to reproduce the problem***:

Install Google Chrome. Install uBlock Origin. Activate the AdGuard Tracking Protection filter in uBlock Origin. Install SearchPreview plugin, available under that name in the Chrome webstore. Search something on Google. To see the difference, deactivate the AdGuard Tracking Protection filter and reload the Google search tab.

***System configuration***

**Filters:**
Problem happens with AdGuard Tracking Protection active, and doesn't happen anymore when that filter is deactivated. Any other filter I tested didn't change that outcome.

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Google Chrome
AdGuard version:                       | None (uBlock Origin)
Filters enabled:                       | AdGuard Tracking Protection

**Comment by Alex-302** [comment]
It seems extension uses attributes, removed by `www.google.*#%#//scriptlet('remove-attr', 'ping|data-ved', 'div[id="search"] a[data-ved][ping]')`, to find the place, where previews must be inserted.

You can add exclusion `www.google.*#@%#//scriptlet('remove-attr', 'ping|data-ved', 'div[id="search"] a[data-ved][ping]')`
