### ISSUE TITLE
lenta.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8422]
Некоторые сайты пытаются что-то подгрузить с яндекс.директа.
Например, с лентой.ру сложности. Вроде страница загружается. Но спустя пару секунда она тянется видимо за банером или рефером на яндекс и я вижу "Не удается отобразить эту страницу"

Например вместо этой 

https://lenta.ru/news/2017/12/05/princessurgant/?utm_source=lentatg&utm_medium=social
вот эту https://an.yandex.ru/mapuid/lentaru/5d384e7b887a8f6a257deeb9f70db68c?jsredir=1&location=https%3A%2F%2Flenta.ru%2Fnews%2F2017%2F12%2F05%2Fprincessurgant%2F%3Futm_source%3Dlentatg%26utm_medium%3Dsocial

это может происходить как автоматически, так и если просто ткнуть мышью в любое место страницы.

---

Лента.ру до сих пор вываливается в невозможность отобразить страницу по переходу поссылке
https://an.yandex.ru/mapuid/lentaru/2524da2927d7cf7e544e06bdfe992124?jsredir=1&location=https%3A%2F%2Flenta.ru%2Fnews%2F2017%2F12%2F14%2Fpolice%2F

----

Можно ли этот момент как-то исправить?

**Comment by evgeniy-ADG** [comment]
USER ID: 1664122

**Comment by Alex-302** [comment]
ничего не понятно

**Comment by evgeniy-ADG** [comment]
Commented by vozersky 15:29
переход с главной в статью типа он описывает

**Comment by Alex-302** [comment]
у меня никаких проблем там уже давно не было

**Comment by evgeniy-ADG** [comment]
у меня тоже не повтоярется. попросили завести в фильтры.

**Comment by Alex-302** [comment]
даже не известно, есть ли у него Адгард.

**Comment by hooddy** [comment]
Здравствуйте. Это мой тикет в общем. Нет, адгвард у меня не установлен, только прописан на роутере ваш ДНС. Я сейчас посмотрел и нашел, при каких условиях это не воспроизводится. Я пользуюсь IE. Если полностью отключить скрипты например, вот так:

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3]
"1400"=dword:00000003

То ничего странного не происходит. Лента работает, все ок. Но если скрипты не заблокированы, то лента ведет себя так, как я написал. Даже еще более странне. При нажатии на любу ссылку, например на эту

https://lenta.ru/news/2017/12/14/f22vssu35/

идет реферер сперва на Рамблер

https://palacesquare.rambler.ru/qnnsefkok/Nm9oN2MuOGdwcWx6OUB7ImRhdGEiOnsiQWN0aW9uIjoiUmVkaXJlY3Q/iLCJSZWZmZXJlciI6Imh0dHBzOi8vbGVudGEucnUvIiwiUHJvdG9jb2/wiOiJodHRwczoiLCJIb3N0IjoibGVudGEucnUifSwibGluayI6Imh0d/HBzOi8vYW4ueWFuZG/V4LnJ1L21hcHVpZC9sZW50YXJ1LzIyMTExNGYyODNlMTFlNjYyOWNhZDFkZjNhNDc0MWM1P2pzcmVkaXI9MSZsb2NhdGlvbj1odHRwcyUzQSUyRiUyRmxlbnRhLnJ1JTJGbmV3cyUyRjIwMTclMkYxMiUyRjE0JTJGZjIydnNzdTM1JTJGIn0%3D

а потом на яндекс директ

https://an.yandex.ru/mapuid/lentaru/221114f283e11e6629cad1df3a4741c5?jsredir=1&location=https%3A%2F%2Flenta.ru%2Fnews%2F2017%2F12%2F14%2Ff22vssu35%2F

И я совершенно не понимаю причины.

**Comment by hooddy** [comment]
Ересь какая-то. Была включена защита от слежения. При этом там в списках явно ничего нет относящегося к ленте, Рамблеру, Яндексу и т.п. Только гугловые сайты. Да и то при заходе на ленту иконка щита не отображается, т.е. вроде как ничего не блокируется. Я ее, защиту, выключил. Перезапустил IE, лента работает нормально. Включил опять защиту, браузер перезапустил и уже не могу воспроизвести все. пока никаких рефереров. И я винду пару раз уже переставлял, и это на каждой инсталляции происходило. Почти наверняка случится и снова. Но суть не в этом. Ситуация не типичная, т.ч. забейте. Закройте тикет.
