### ISSUE TITLE
wordpress.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84265]
***Issue URL (Ads + Annoyance+ social widgets)***: https://pritishsirkar.wordpress.com/2010/12/30/how-to-commit-suicide-without-feeling-any-pain/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120067142-ad003a00-c097-11eb-8409-bfa6a19b9b2c.png)
![image](https://user-images.githubusercontent.com/76880977/120067146-b093c100-c097-11eb-99ee-6a85bcdb2486.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by krystian3w** [comment]
May need test position in Alexa ranks.

**Comment by zloyden** [comment]
The site has low visitors.
