### ISSUE TITLE
liftmydepression.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84266]
***Issue URL (Annoyance)***: http://liftmydepression.com/blogs/inspiration/14-ways-hurt-yourself-when-depressed/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120067256-2e57cc80-c098-11eb-95b2-7b289cc1249c.png)
![image](https://user-images.githubusercontent.com/76880977/120067259-30ba2680-c098-11eb-82dc-3cd6cc22322d.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
