### ISSUE TITLE
thinksimplenow.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84335]
***Issue URL (Annoyance)***: http://thinksimplenow.com/happiness/15-simple-ways-to-overcome-anger/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120093498-5a2a8f00-c138-11eb-81ae-36d759cf228a.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.

**Comment by chirag127** [comment]
Okay
