### ISSUE TITLE
mediafuse.com

### ISSUE THREAD

**Issue by bnainar** [AdguardTeam/AdguardFilters#84359]
* `player.mediafuse.com`
* `hb.mediafuse.com`
Found in qz.com
https://qz.com/1802881/how-socialism-became-anti-american/

**Comment by Alex-302** [comment]
They are already blocked
![image](https://user-images.githubusercontent.com/8361299/120220303-330db380-c245-11eb-95db-32a56e0675fe.png)

**Comment by bnainar** [comment]
Thanks 😊

**Comment by Alex-302** [comment]
Blcoked ad leftovers.
