### ISSUE TITLE
thewindowsclub.com [Ad Block Message]

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardFilters#8440]
http://www.thewindowsclub.com/sandbox-sandboxing-software

Can you please check the above page and fix the adblock message.

**Screenshot**: https://i.imgur.com/vJPo4wP.jpg

**Extension**: Adguard Adblocker 2.6.7
**Browser**: Chrome Version 60.0.3112.101 (Official Build) (32-bit)
**OS**: Windows 7 Professional SP1 (32 bit)
**Filters**: English, Spyware, Social Media, Annoyances, Mobile Ads & Malware Domains
**Phishing and malware protection is enabled**

**Comment by BlazDT** [comment]
Can't reproduce with given filter lists.

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't reproduce this too, but it seems that it is Admiral, so you check this rule:
`thewindowsclub.com#%#AG_abortInlineScript(/,blockerScore:/, 'Promise');`

**Comment by clementine123** [comment]
You are right. I can't see this issue now.
