### ISSUE TITLE
AD CDN https://jawsfixture.com

### ISSUE THREAD

**Issue by iieternal** [AdguardTeam/AdguardFilters#84445]
Block https://jawsfixture.com
It is a cdn for popup ad networks.

Example: https://jawsfixture.com/00/6d/e3/006de322d94b642e435fc6e6b36f095f.js

https://jawsfixture.com/f0/63/15/f063151059dda8a63c1b51e01bf0388c.js

**Comment by IThinkIAmCool** [comment]
Any web page where an ad can be seen?

**Comment by iieternal** [comment]
https://1-23movies.cc/

**Comment by Alex-302** [comment]
It is already blcoked by regexp. Blocked domain for DNS filter.
