### ISSUE TITLE
news.sportbox.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8447]
### Issue URL (Ads)
[https://news.sportbox.ru/](https://news.sportbox.ru/)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/15856304/34048779-a543ee36-e1bd-11e7-92b5-ee311181889d.png)

</details>

### System configuration

Information | value
--- | ---
Platform: | And 6
AdGuard version: | 2.10.176
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>German,<br>Filter unblocking search ads and self-promotion,<br>Mobile Ads,<br>Annoyances

**Comment by Alex-302** [comment]
Не повторяется. Нужен HAR.
