### ISSUE TITLE
getadblock.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84529]
### Issue URL (Social Widget)
https://blog.getadblock.com/adblock-version-4-16-0-fix-for-youtube-ad-blocking-issues-baa2dd3b718d
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120234002-a8dd4380-c274-11eb-9ce4-e893284e32b5.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by krystian3w** [comment]
Maybe any Medium CMS blog have this button.

**Comment by krystian3w** [comment]
I tested rule from https://github.com/AdguardTeam/AdguardFilters/commit/07e7c7e996a8da5d074f14af130a27ba99a4f124 and works on reported page, but not on:

`https://medium.com/@kamalganwani4/34-must-have-chrome-extensions-for-web-developers-and-designers-e39a4128fefc`
`https://medium.com/analytics-vidhya/how-to-use-google-colab-with-github-via-google-drive-68efb23a42d`
