### ISSUE TITLE
thegurukul.club

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84549]
**Issue URL (Ads)** :
https://www.thegurukul.club/p/important-questions-in-emerging.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120271800-92150c00-c2c9-11eb-8b66-140991408a59.png)
![image](https://user-images.githubusercontent.com/76880977/120271802-93decf80-c2c9-11eb-8aa5-c5de5e0958bf.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
