### ISSUE TITLE
cloudsek.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84572]
***Issue URL (Annoyance)***: https://cloudsek.com/how-to-bypass-captchas-easily-using-python-and-other-methods/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120317592-72e3a200-c2fc-11eb-83ce-49a11c116276.png)

</details><br/>

<details><summary>Filter:</summary>

![image](https://user-images.githubusercontent.com/76880977/117950608-fc710700-b330-11eb-80e7-b0c02a3ba7a5.png)

</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
