### ISSUE TITLE
remove adblock protector 2

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/AdguardFilters#8458]
>AdBlock Protector 2 Canceled in favor of Nano Adblocker

https://github.com/AdBlockProtector2/AdBlockProtector2#adblock-protector-2-canceled-in-favor-of-nano-adblocker

![2017-12-15 21_47_12-ustawienia adguard](https://user-images.githubusercontent.com/5884000/34059927-9e200b0c-e1e1-11e7-8f2f-580d80d62271.png)

**Comment by Alex-302** [comment]
@ameshkov can we remove it?

**Comment by ameshkov** [comment]
We can rename it or replace with another filter.

**Comment by ameshkov** [comment]
Let's replace it with the Polish Annoyances filter maybe?
https://github.com/AdguardTeam/AdguardFilters/issues/8413

**Comment by Alex-302** [comment]
@ameshkov I can't change description in DB.

**Comment by ameshkov** [comment]
@Alex-302 sorry for the late reply. It's not too long till you'll be able to do it manually without messing with the DB.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #9](https://github.com/AdguardTeam/FiltersRegistry/issues/9) via [**ZenHub**](https://www.zenhub.com/)
