### ISSUE TITLE
aajkikhabar.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84599]
***Issue URL (Ads+Annoyance)***: https://www.aajkikhabar.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120347804-39ba2a80-c31a-11eb-8119-ae6e3e9fa135.png)
![image](https://user-images.githubusercontent.com/76880977/120347806-3a52c100-c31a-11eb-8ca4-48def9a10bd6.png)
![image](https://user-images.githubusercontent.com/76880977/120347810-3aeb5780-c31a-11eb-8c1c-59ed5fd786f7.png)
![image](https://user-images.githubusercontent.com/76880977/120347813-3b83ee00-c31a-11eb-93dc-134912139d49.png)
![image](https://user-images.githubusercontent.com/76880977/120347816-3c1c8480-c31a-11eb-86e1-5878f64ff78e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
