### ISSUE TITLE
asklaila.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84601]
***Issue URL (Annoyance)***:
https://www.asklaila.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120349186-85210880-c31b-11eb-9ab6-4a6a4a2aa65f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
We don't block such elements.

**Comment by chirag127** [comment]
What do you mean by such elements . Nither it is a tooltip or effect website functionality.

**Comment by zloyden** [comment]
> website functionality

The window from the screenshot. It's about the geo-position, so we don't block such elements.
