### ISSUE TITLE
freecoursessites.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84669]
***Issue URL (Annoyance)***: https://www.freecoursessites.com/downloading-center/?dlm-dp-dl=4789 has a counter .

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120448193-f2c74600-c3a8-11eb-9765-7f67a86372f9.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
It seems they have a server-side check, so you should wait.
