### ISSUE TITLE
[Android] Mahjong Solitaire

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#847]
https://play.google.com/store/apps/details?id=com.leagem.mahjong&hl=en

Реклама в приложении

YQI-339-54227

**Comment by Alex-302** [comment]
Не срабатывает правило:
||f.doodlemobile.com:8080/feature_server_v3/$empty

**Comment by evgeniy-ADG** [comment]
Пользователь снова обращается по этому вопросу. Есть ли какие-то новости?

**Comment by Alex-302** [comment]
@Revertron need help!
||doodlemobile.com^$empty - not work on Android
