### ISSUE TITLE
m.pandora.tv  - Incorrect blocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8470]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://m.pandora.tv/?c=view&ch_userid=box2010&prgid=47678425

Can't watch a video, adguard block all both ads and video.

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.39.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.16.28 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.22.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.87 Enabled=YES
ID=224 Name="Korean Adblock List" Version=1.0.0.7 Enabled=YES
ID=227 Name="List-KR" Version=1.0.3.61 Enabled=YES

Information                            | Value
---                                    | ---
Operating system:                      | 11.2
Operating system version (Android/iOS) | iOS
AdGuard version:                       | 1.3.3.118
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1695507

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Mobile filter must be enabled.
