### ISSUE TITLE
firmcodes.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84776]
**Issue URL (Ads)** : http://www.firmcodes.com/write-printf-function-c/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120542174-6b112400-c408-11eb-93d7-245bac77128b.png)
![image](https://user-images.githubusercontent.com/76880977/120542177-6ba9ba80-c408-11eb-9b13-076796502e4d.png)
![image](https://user-images.githubusercontent.com/76880977/120542178-6c425100-c408-11eb-9141-084ee43334e9.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
No visitors.

**Comment by chirag127** [comment]
![image](https://user-images.githubusercontent.com/76880977/120644209-b53fe700-c494-11eb-8e57-b1c0e30a9803.png)
