### ISSUE TITLE
foodpanda tracking order page ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#84781]
```
https://tw.fd-api.com/api/v5/partnerships-ads-api/ads?language_id=6&page=postorder

||fd-api.com/api/v5/partnerships-ads-api^

tw.fd-api.com --> tw = taiwan
```

`贊助` = `sponsor`

![image](https://user-images.githubusercontent.com/75058881/120556445-17660100-c42f-11eb-954a-c7152fe49714.png)

![image](https://user-images.githubusercontent.com/75058881/120556452-192fc480-c42f-11eb-98af-407b6f2c3260.png)

**Comment by Alex-302** [comment]
Need screenshot of ads and URL(always in all issues).

**Comment by c2xusnpq6** [comment]
......... I am not a person who uses foodpanda often....

**Comment by c2xusnpq6** [comment]
but you can trust me? haha....😭

**Comment by c2xusnpq6** [comment]
You can see from the image above that the request URL contains the keyword `ads`

**Comment by Alex-302** [comment]
I cannot just block it.

**Comment by c2xusnpq6** [comment]
> I cannot just block it.

reopen pls

look!... https://github.com/easylist/easylist/commit/d2756373881f7b977e1a10468d932cff24c54122

**Comment by Alex-302** [comment]
Easylist is upstream for Base filter.

**Comment by c2xusnpq6** [comment]
```
https://tw.fd-api.com/api/v5/partnerships-ads-api/ads?page=postorder&next_gen_version=v2&language_id=6
```

![Screenshot_20210709-063117_Trebuchet.png](https://user-images.githubusercontent.com/75058881/124998705-7565b400-e07f-11eb-877d-44f1ddd9cc09.png)
