### ISSUE TITLE
gomovies.tech [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8479]
**Site**: https://gomovies.tech/film/geostorm-22400

**Issue**: Seeing ad on the page.

**Screenshot**: https://prnt.sc/ho9hh3

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
Can't reproduce without AdGuard. Please upload saved page.

**Comment by clementine123** [comment]
Correct. Not seen anymore.

**Comment by yesmovieshd** [comment]
try this - https://123movies.fun/film/geostorm-22400
its an ads free version!!
