### ISSUE TITLE
globaltimes.cn 

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84814]
**Issue URL (Social Widget)** : https://www.globaltimes.cn/page/202105/1223479.shtml

globaltimes.cn##.article_left_share
globaltimes.cn##.article_top_share
globaltimes.cn##.article_footer_share

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120663318-897a2c80-c4a7-11eb-8a55-2559f60d38ea.png)
![image](https://user-images.githubusercontent.com/76880977/120663321-8a12c300-c4a7-11eb-82eb-34f3f8fb9a37.png)
![image](https://user-images.githubusercontent.com/76880977/120663316-897a2c80-c4a7-11eb-9a0a-cab04a804708.png)
![image](https://user-images.githubusercontent.com/76880977/120663320-8a12c300-c4a7-11eb-951c-5b5989c1f8d4.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by chirag127** [comment]
Not added globaltimes.cn##.article_footer_share ?

**Comment by zloyden** [comment]
Somehow it didn't hit the commit, but I'll rewrite those rules.

**Comment by chirag127** [comment]
Strange.... ! https://github.com/AdguardTeam/AdguardFilters/issues/84814#issuecomment-857556964

**Comment by zloyden** [comment]
The update should be available in 1-2 hours, thanks for letting me know.
