### ISSUE TITLE
bitcoin-otc.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84812]
**Issue URL (Ads)** : https://bitcoin-otc.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120654836-ad397480-c49f-11eb-87b8-e03c8bd4dbe5.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
Not reproduced, it's already blocked.
