### ISSUE TITLE
thereporterz.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84926]
**Issue URL (Ads)** : https://thereporterz.com/its-worth-a-shot-washington-dangles-tech-gadgets-1m-prize-and-more-to-encourage-covid-vaccines/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120819310-0fae7580-c571-11eb-89d6-3daede591573.png)
![image](https://user-images.githubusercontent.com/76880977/120819312-10470c00-c571-11eb-977d-7bb55359e5ed.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
