### ISSUE TITLE
therundownlive.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84927]
**Issue URL (Ads)** : https://therundownlive.com/free-equal-tv-kingsley-edwards/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120819638-65831d80-c571-11eb-9d15-67f12b866580.png)
![image](https://user-images.githubusercontent.com/76880977/120819640-661bb400-c571-11eb-8d52-9b0cf8d2e34d.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
