### ISSUE TITLE
mediamass.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84922]
**Issue URL (Ads)** : https://en.mediamass.net/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120817357-45eaf580-c56f-11eb-8f62-e900ef39b60a.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
It's blocked on my end, also removed socials.
