### ISSUE TITLE
vimeo.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84948]
***Issue URL (Annoyance)***: https://vimeo.com/249996828

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120857111-67170a80-c59e-11eb-8180-4e8faf3a1163.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
Well, this element it's a part of the functionality of the website, so it can't be blocked.

**Comment by chirag127** [comment]
If it is necessary than it should  also show on the mobile website . But it is not shown in the mobile website . And by the way, however what it is?
