### ISSUE TITLE
early-riser.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#84951]
***Issue URL (Annoyance)***: http://www.early-riser.com/punish-yourself.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120859857-713b0800-c5a2-11eb-8936-1ffe38c01808.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors, but you can add those rules to the user rules.
```
early-riser.com#?#div[class] ~ h1[style]:contains(Newsletter)
early-riser.com#?#div[class] ~ h1[style]:contains(Newsletter) + p
early-riser.com#?#div[class] ~ h1[style]:contains(Newsletter) + p + div[class]
```
