### ISSUE TITLE
일부 사이트에서 광고차단이 되지 않습니다.

### ISSUE THREAD

**Issue by WESO0** [AdguardTeam/AdguardFilters#84967]
전 에드가드dns를 사용중 입니다. 근데 나무위키 일부 검색어에서 광고가 차단되지 않습니다.  빨리 해결해 주세요

**Comment by Yuki2718** [comment]
Precisely describe in which sites AG doesn't work, also check your AG settings.

**Comment by Alex-302** [comment]
What I see with DNS only
![image](https://user-images.githubusercontent.com/8361299/121709005-c4501600-cae0-11eb-9e87-2d0627ae9e6b.png)

Blank spaces cannot be removed by DNS.

**Comment by WESO0** [comment]
Ok! Thanks!

2021년 6월 12일 (토) 00:14, Alex ***@***.***>님이 작성:
