### ISSUE TITLE
xtorx.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85004]
**Issue URL (Ads)** : https://www.xtorx.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120897608-a4ce6e80-c644-11eb-9860-ccefd90e84e9.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
Probably fixed in this commit - https://github.com/AdguardTeam/AdguardFilters/commit/4221c849c4fd3cc0d76def8857aa3fe626020028

**Comment by chirag127** [comment]
Hmm... I had made this issue 3 days before that issue . By the way , Is there any defined order of solving of the issues .
