### ISSUE TITLE
pr-cy.ru

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85130]
**Issue URL (Ads)** : https://a.pr-cy.ru/aajkikhabar.com

> self promotion
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/120979334-203e3600-c793-11eb-8de4-a8acab5f1c72.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
Not an annoyance - it's an ad. Please enable AdGuard Russian.
