### ISSUE TITLE
filerio.in [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8514]
**Site**: http://filerio.in/09a2233ilac6

**Issue**: Remove fake links on the page

**Screenshot**: http://prntscr.com/hoizci

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
fixed
