### ISSUE TITLE
www.amazon.* URL Tracking filter

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#85274]
Can we start to debloat Amazon?

'By clicking around and searching' I found the following parameter which I added to AdGuard and the page still works fine.
Especially the products in the horizontal result have a lot of parameter starting with `pd` or `pf`.
Also search for products, click on the result, it will have other parameter.

<details><summary>Screenshot-1:</summary>

![amazon](https://user-images.githubusercontent.com/6276915/121243580-266d0900-c89e-11eb-8801-60a43da44a6a.png)

</details><br/>

This is my (probably not final) list:

`||amazon.*^$removeparam=pd_rd_w`
`||amazon.*^$removeparam=pd_rd_r`
`||amazon.*^$removeparam=pf_rd_p`
`||amazon.*^$removeparam=pf_rd_r`
`||amazon.*^$removeparam=pd_rd_wg`
`||amazon.*^$removeparam=pd_gw_unk`
`||amazon.*^$removeparam=pd_rd_i`
`||amazon.*^$removeparam=pf_rd_m`
`||amazon.*^$removeparam=pf_rd_s`
`||amazon.*^$removeparam=pf_rd_t`
`||amazon.*^$removeparam=pf_rd_i`
`||amazon.*^$removeparam=ref_`
`||amazon.*^$removeparam=_encoding`
`||amazon.*^$removeparam=ie`
`||amazon.*^$removeparam=qid`
`||amazon.*^$removeparam=sr`
`||amazon.*^$removeparam=keywords`
`||amazon.*^$removeparam=s`
`||amazon.*^$removeparam=storeType`
`||amazon.*^$removeparam=pageType`
`||amazon.*^$removeparam=refRID`
`||amazon.*^$removeparam=psc`
`||amazon.*^$removeparam=dchild`

There is one more parameter which won't work to remove: `||amazon.*^$removeparam=ref`
When I add it, it still in the URL, but isn't necessary for the work of the page. Maybe you can find a solution.

It will be difficult to find specific parameter again if you will ask for, but I will try.

**Comment by Alex-302** [comment]
Better provide all urls with these parameters(do not remove values, but you may change some)

**Comment by Alex-302** [comment]
> ||amazon.*^$removeparam=keywords

Definitely bad rule - breaks suggestions.

I guess we can add these rules:
```
||amazon.*$removeparam=pd_rd_i
||amazon.*$removeparam=pd_rd_r
||amazon.*$removeparam=pd_rd_w
||amazon.*$removeparam=pd_rd_wg
||amazon.*$removeparam=pf_rd_i
||amazon.*$removeparam=pf_rd_m
||amazon.*$removeparam=pf_rd_p
||amazon.*$removeparam=pf_rd_r
||amazon.*$removeparam=pf_rd_s
||amazon.*$removeparam=pf_rd_t
||amazon.*$removeparam=ref
||amazon.*$removeparam=ref_
||amazon.*$removeparam=refRID
||amazon.*$removeparam=smid
```
Will test some time.

**Comment by Morku** [comment]
Example links:

https://www.amazon.com/s?bbn=16225016011&rh=n%3A%2116225016011%2Cn%3A471304&dc&language=de&fst=as%3Aoff&pf_rd_i=16225016011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=03b28c2c-71e9-4947-aa06-f8b5dc8bf880&pf_rd_r=VKD0GZY2X2NDD3B0F7FQ&pf_rd_s=merchandised-search-3&pf_rd_t=101&qid=1489016289&rnid=16225016011&ref=s9_acss_bw_cts_AEVNVIDE_T4_w

https://www.amazon.com/-/de/dp/B07PQVRPR1/?_encoding=UTF8&pd_rd_w=hEmg3&pf_rd_p=f1970459-a9aa-42ac-bf6d-142ef05b9a5c&pf_rd_r=VKD0GZY2X2NDD3B0F7FQ&pd_rd_r=8b85f735-8afb-48e4-8788-a05af300031d&pd_rd_wg=bv1eX&ref_=pd_gw_unk

https://www.amazon.com/s?k=gaming+apparel&language=de&pd_rd_r=8b85f735-8afb-48e4-8788-a05af300031d&pd_rd_w=5QDtn&pd_rd_wg=bv1eX&pf_rd_p=aae1da38-b146-405e-9d82-f406c3b2a5ee&pf_rd_r=VKD0GZY2X2NDD3B0F7FQ&ref=pd_gw_unk

https://www.amazon.com/-/de/dp/B07Q38W3XZ/ref=sr_1_4?dchild=1&keywords=gaming+apparel&pd_rd_r=8b85f735-8afb-48e4-8788-a05af300031d&pd_rd_w=5QDtn&pd_rd_wg=bv1eX&pf_rd_p=aae1da38-b146-405e-9d82-f406c3b2a5ee&pf_rd_r=VKD0GZY2X2NDD3B0F7FQ&qid=1623234098&sr=8-4

https://www.amazon.com/-/de/b/?_encoding=UTF8&ld=AZUSSOA-sell&node=12766669011&ref_=nav_cs_sell_9321d964d1ab428b8d83e204c043fc01

https://www.amazon.com/-/de/dp/B01MXZWR3D/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=teapot&qid=1623234149&sr=8-3

https://www.amazon.com/100pcs-Black-Disposable-3-ply-Breathable/dp/B08LL3MP1J/ref=gbps_img_m-9_475e_dd95a80c?smid=A172WIERJMFM7R&pf_rd_p=5d86def2-ec10-4364-9008-8fbccf30475e&pf_rd_s=merchandised-search-9&pf_rd_t=101&pf_rd_i=15529609011&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=9T68XH4B0CWNJ2ECT94M

If you are looking for a parameter which might miss to check, let me know.

**Comment by Alex-302** [comment]
Ok, added to the list above
```
||amazon.*$removeparam=pf_rd_m
||amazon.*$removeparam=qid
```
not sure about another parameters(they can be used for technical purposes).

**Comment by Morku** [comment]
Whats the issue with the other?
How we can find out the 'technical purpose'?

Sure, I can't test every way people will browse the page and to be honest, I didn't check the whole purchase checkout.

**Comment by Alex-302** [comment]
Will try to test purchase tomorrow.

**Comment by Morku** [comment]
I got a link from someone, but it's hard to figure out how the person got the result. It has a lot of other paramter:

https://www.amazon.de/Teekanne-frio-4er-Pack-Pfirsich/dp/B01E059VLE/ref=asc_df_B01E059VLE/?tag=googshopde-21&linkCode=df0&hvadid=310635158110&hvpos=&hvnetw=g&hvrand=13859153460388015589&hvpone=&hvptwo=&hvqmt=&hvdev=m&hvdvcmdl=&hvlocint=&hvlocphy=9042954&hvtargid=pla-561353150373&psc=1&th=1&psc=1&tag=&ref=&adgrpid=65495602927&hvpone=&hvptwo=&hvadid=310635158110&hvpos=&hvnetw=g&hvrand=13859153460388015589&hvqmt=&hvdev=m&hvdvcmdl=&hvlocint=&hvlocphy=9042954&hvtargid=pla-561353150373

All information I got was "I searched for Frio Teekanne" on "my Startscreen" and shared to the messenger. No using an Amazon App. Using Android.
I don't know if searched in Chrome oder some Google searchbar. I don't use Android, I can't verify.

**Comment by Morku** [comment]
When I duckduckgo of some of the new parameter of my last reported link, I can find Amazon result.
For example: https://duckduckgo.com/?t=ffcm&q=hvdvcmdl&ia=web

<details><summary>Screenshot-1:</summary>

![Screenshot 2021-06-13 181938](https://user-images.githubusercontent.com/6276915/121814930-f180fd80-cc73-11eb-8eb0-dbab8e105cd1.png)


</details><br/>

https://duckduckgo.com/?t=ffab&q=hvpone&ia=web

<details><summary>Screenshot-2:</summary>

![Screenshot 2021-06-13 182038](https://user-images.githubusercontent.com/6276915/121814959-268d5000-cc74-11eb-819d-8587ef1d6851.png)


</details><br/>

Unfortunately I still didn't figure out, what's the normal way of source to get an Amazon result with this different parameters.

**Comment by Morku** [comment]
@Alex-302 
Why are the other Tracking parameter not relevant?

**Comment by Alex-302** [comment]
They are empty, the purpose is unknown.
