### ISSUE TITLE
epocanegocios.globo.com

### ISSUE THREAD

**Issue by Pccode66** [AdguardTeam/AdguardFilters#85288]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
There are ad placeholders on `https://epocanegocios.globo.com/` (first screenshot) and in articles, like `https://epocanegocios.globo.com/Empresa/noticia/2021/06/berkshire-hathaway-de-buffet-investe-us500-milhoes-no-nubank.html` (second screenshot)

I suggest these filters:
```
epocanegocios.globo.com##div[class^="container-adv"]
epocanegocios.globo.com##li.adv-item
epocanegocios.globo.com##li[data-item-type="advertising"]
```

The following two filters may be needed, since the formatting of articles previews gets messed up otherwise (see third screenshot) (the articles previews are supposed to be close to one another):
```
epocanegocios.globo.com###home-section-list-3x1-1 > ul:style(justify-content: unset !important;)
epocanegocios.globo.com###home-section-list-3x1-1 > ul > li > section > div:style(margin-right: 30px !important;)
```

The ad placeholders on the article can be fixed by `epocanegocios.globo.com##[id^=pub-materia]`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/tfzs2lZ.jpg)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ItmzLms.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ZgPrrlf.png)
</details><br/>

***System configuration***

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Browser:                               | Firefox
Filters enabled:                       | AdGuard Base, EasyList, EasyList Privacy, Adguard Tracking Protection, AdGuard Annoyances, Fanboy’s Annoyance, Peter Lowe’s Ad and tracking server list, spa, por: AdGuard Spanish/Portuguese

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not sure about CSS rules.

**Comment by Pccode66** [comment]
Thank you!

**Comment by Pccode66** [comment]
I hadn't noticed Adguard has their own [CSS rules syntax](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#css-rules)

**Comment by Pccode66** [comment]
Can you (@Alex-302) consider the following filters: `epocanegocios.globo.com#$##home-section-list-3x1-1 > ul { justify-content: unset!important;}` and
`epocanegocios.globo.com#$#ul[data-tb-region="home-section-highlight-list-1"] > li { margin-right: 30px!important;}`? 

Without CSS filter:

![1](https://user-images.githubusercontent.com/49125134/121607346-40395800-ca26-11eb-95d4-e029e326c57d.png)

With CSS filter:

![2](https://user-images.githubusercontent.com/49125134/121607352-44657580-ca26-11eb-869c-17717e58e230.png)

Do you think it's too risky?

**Comment by Alex-302** [comment]
> I hadn't noticed Adguard has their own [CSS rules syntax](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#css-rules)

Yes, the "problem" is with changing that styles, I think it is not critical issue and the most of users will not pay attention on that space.
