### ISSUE TITLE
foodpanda update

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#85291]
remove these:
https://github.com/easylist/easylist/blob/d2756373881f7b977e1a10468d932cff24c54122/easyprivacy/easyprivacy_specific.txt#L2744-L2751
to these:
```
||foodora.*/lJuB4eTB/init.js
||foodpanda.*/lJuB4eTB/init.js

or

/lJuB4eTB/init.js
```

https://github.com/easylist/easylist/issues/8006

https://github.com/easylist/easylist/commit/d2756373881f7b977e1a10468d932cff24c54122#

https://www.google.com/search?q=lJuB4eTB%2Finit.js

**Comment by c2xusnpq6** [comment]
https://github.com/easylist/easylist/issues/8060

**Comment by Alex-302** [comment]
ok
