### ISSUE TITLE
telerik.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85308]
***Issue URL (Annoyance)***: https://www.telerik.com/fiddler

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121340578-6931ee00-c93d-11eb-9bf8-88a679837e0b.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
It may be useful.
