### ISSUE TITLE
jwplayer.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85328]
***Issue URL (Annoyance)***: https://www.jwplayer.com/learn-more/?e=6

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121374047-326bd000-c95d-11eb-8288-e6a04f766fe7.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
It seems that it's duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/85001
