### ISSUE TITLE
fmoviesgo.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85359]
**Issue URL (Ads)** : https://fmoviesgo.net/watch-tv/alma-matters-inside-the-iit-dream-2021-full-69844.4208354

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121408262-d796a080-c97d-11eb-8a00-5ab6284fa2cf.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Yuki2718** [comment]
Not sure if ads or self-promo.
