### ISSUE TITLE
Unblocked advert

### ISSUE THREAD

**Issue by abo7aneen** [AdguardTeam/AdguardFilters#85361]
https://asp.mapgotrade.live/isftblvd/?utm_campaign=pEv9cTd8QNHYzqqr5UNFx2COHvnp_JE3r8uVIhm3Qww1&t=main9&f=1&sid=t3~cieoamyytfzari4sytu3mgiq&fp=jLWAIe0T8oFQOFaYxANFoXb7HvaFw82%2FCp2jgz5lBUBBXmQ8qDBUGZ8KrzkZca2W7wm9yp58Ti1ZaML5JjB34Jugwe9vJnREuqBQzFAESAwF89pdjeh0KviK0Lg3F%2FLruoeG32Mb95UOR9wGh%2BdjeBGnBlC%2BUrXGOYuuauAdfJN%2FTHr%2BT%2BxCgZUVtyJ6XeCo2dD2e9ZmD312h89ootRRW10L8ioPJ2xDny%2BJUwDMSQrMVpJDu37gq%2BGF2yuQ%2BzK2kmZsmn8J5evCCW2VgEtfrhF80XIBnC0Wk4ARp%2Bfj1BYMM0pcq5Q6jHbK9qqZYX9ocgAuJ8ngf4LbxjqdnCbKJuY2YB69VxDzgMD5HvMoiaawbL8IX%2F1DViuUHQMQXUF1SlzHpnsnB2BWQ9lO2Z9wI5PyWxPk7J1imzy1N2tbv%2Bc%2BJtYpcMfAvaQv4hGlG5A3AQAqrswxHcfADQSSSQqBAGpcrKVvnGuryNHx3MLczWJN7f1GxIhEZ8Pb1hT0Sma0hfPP%2FQZbhzqLFx%2B3bgxKlNMGYCE8lxBxi0R3Cn0tZFj1%2B7dzDxOv3DSDdrBa85aOhdzi9K9wn%2Fbk0mGs%2BPH1U1d%2B55dmN6sY9z2Q9aMvn2xQ00kK7zr%2F590BCtlKEcoUl5717IGF8X87W1cb3UQdo5hyTlJUWiDBbvcqSLAqkS8%2BytCfGXyE53ejswFBOwgvqQJfy9HjUZPVuC6z1UAmRUKZ%2B0r6CzTak31VEdMxcTwEXF0WDfDGnVUlk4AC97%2BzvNrc1Dx98AgXViaUt9ECPuO%2FiI56GMckQBRJk%2BSKgGkVOtYsHvTri0n%2FJUES35HGkwHCzQ25j%2FBfUAXH%2BEq9YVXyo5rjMxVshsSFMrc31HvvVmg348PnrbAFTRSb%2BAmMnbBqJFL2fwKx9r%2BjGknVIY8awixb5%2B2nZXGP7x2MeuNp4HtZG5T0iQd14jrrVwyrAsMfhOWwCCAQK4VNtv788%2FjX8L2JgRvXI2wf3G4dvkGjxvkA3kICU5xTUW8wvq9NpXCnK%2BscukaDjMHKM%2F0RSqdppCxHDKzI98n%2FDcrRo3BzgBbCR6MYeuADQxAdV0sJidtpqcxNEacXAwIeuhIaafdR3Y5%2FlD6Jf7xNCOnpLtAe5p6TaYAQYmqSHlPwITuF4%2BFgDPEhWzGL00Rsiv5LM%2B1vU2iC6rGo26wdCGUgZsiRobpQoY9doMIUSF%2BJmhPKO2vFz%2BppUgkO5gwg7z4Egr1HDSNQvdj%2FaAyp2EpGHyvLlNUEshmSFS%2Fj7UkOhQ2r67MrJdxQIHjUjZ%2F%2FA30aLMXn%2FNTJ8WWqmou%2Fq%2ByZ1UeIvod9PrLN5%2F%2BvJi4RoTsAergFnDWhSWEW5j1%2BhBt9QTe92dutGoqFjc6ECric71g6xMtNIGL%2FXFEdMceZMQ07HL%2B54w1nCqHzlR6%2BVcOg8UtVn4pu7gT9AfjUK1LZZdTk2cGUt8zINKpDzCfBdcdlTwu2bbwvla6eCgl78fZ3Tbm5orx5a2qX7c3XAUK06vrrgzEu%2BCY9O4b%2B0Go%2B0xJRP4VOJIQm9XYsMd5ec0ueYWdRrrb9hQriO4p5dZYcDVUiOUzsH%2B2on%2BduN%2FIq9VDXzfXaebhXjptB5NAxqbrXoI24zi5E6Dnz9Pa708ANAYA1p13Xk3EvpcrrUsgFvK%2Fv%2FHMnlg2mLLw1pBeMkw13C5b4NgEOCdNFyV896p0HQ%2FVTmTTJtJMbVKzOg5Urz6LNY2lczsNBJUQyKbLEC5HmjDNT%2F2reO1wKiynQ6tFgdDe4RFli%2FylErwX7uYAfldoPclJ3XxivZ%2B1zWwYuaj2QDA%3D%3D

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/121556920-f8620300-ca1c-11eb-878a-66d432268ad0.png)

**Comment by Alex-302** [comment]
Need the source site.
