### ISSUE TITLE
greatist.com 

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85369]
***Issue URL (Annoyance)***: https://greatist.com/happiness/how-to-cool-down-a-room

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121422157-8f32af00-c98c-11eb-8627-42182e9f9d16.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
I don't think that we should block it.

**Comment by chirag127** [comment]
If the affiliate links are not removed by adguard . Then it should remain . Did you see any non - removed advertising link ?

**Comment by zloyden** [comment]
Normally, I wouldn't block this, but I found leftovers with ads. Also added them to our filters.
