### ISSUE TITLE
Replace Rule make some rule does not work

### ISSUE THREAD

**Issue by laulguo** [AdguardTeam/AdguardFilters#85381]
***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
I previously used
*. *$subdocument,replace=/target="_blank"/target="_self"/
rule to modify the ATTRIBUTE attribute of all pages, but recently I found that loading such a rule will disable the filtering of many pages
The page visited is:http://www.xbiquge.la/15/15003/17163209.html
Time 11:52 minutes, used the rule:*. *$subdocument,replace=/target="_blank"/target="_self"/
 http://www.xbiquge.la/15/15003/17163209.html
recorded yesterday using the full log function that comes with ADGUARD
[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![1](https://user-images.githubusercontent.com/38545281/121468057-c769da00-c9ec-11eb-88b6-5a45cb1c0909.png)
![2](https://user-images.githubusercontent.com/38545281/121468065-c9339d80-c9ec-11eb-9996-1222ab66d9a7.png)

These two diagrams reflect the difference between whether the filter are loaded or not 
Log are here
[adg_logs_7.6.3583.0_0515_1152.zip](https://github.com/AdguardTeam/AdguardFilters/files/6628490/adg_logs_7.6.3583.0_0515_1152.zip)

![3](https://user-images.githubusercontent.com/38545281/121467736-3561d180-c9ec-11eb-9665-50dcd33df342.png)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10
Browser:                               | Firefox/Chrome
AdGuard version:                       | 7.6.1
Filters enabled:                       | Chinese+Base
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | No
Helpdesk ID (if exists):               | ?

**Comment by AdamWr** [comment]
Issue moved to [AdguardTeam/CoreLibs #1463](https://github.com/AdguardTeam/CoreLibs/issues/1463) via [**ZenHub**](https://www.zenhub.com/)
