### ISSUE TITLE
Disable adblocker

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#85387]
Using browser extension 
On this is link shortner 
https://link1s.com/2Xdqd0
After going to 2/3 it asks to disable adblocker

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by Bhooty** [comment]
![Screenshot_20210610-221915_Firefox](https://user-images.githubusercontent.com/46019727/121561316-328dcd80-ca3a-11eb-845a-efef28084f53.jpg)

**Comment by Alex-302** [comment]
Please send report from AdGuard(Support menu)
