### ISSUE TITLE
seafarerswelfare.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85445]
***Issue URL (Annoyance)***:
  https://www.seafarerswelfare.org/resources/publications/good-practice-guide-piracy

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121520468-90a5bb00-ca10-11eb-997e-698f1672bac8.png)
![image](https://user-images.githubusercontent.com/76880977/121520469-913e5180-ca10-11eb-91b8-8c5db0721761.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4630 visitors/month, >30000 needed

**Comment by chirag127** [comment]
How do you check the check the monthly visitors ?
