### ISSUE TITLE
www.kommersant.ru

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#85470]
Отслеживание по URL: https://www.kommersant.ru/doc/4855309?from=hotnews
Только это убьёт архив статей по календарю здесь: http://s13.ru/archives/arhive/?from=20.05.2021&to=20.05.2021

**Comment by Alex-302** [comment]
Ломать точно не стоит.

**Comment by zubrRB** [comment]
Так можно в исключения вносить... Есть же такая возможность в фильтре отслеживания по URL.

**Comment by zubrRB** [comment]
На сайте РБК такое же отслеживание: https://www.rbc.ru/society/30/06/2021/60dc36f29a7947d241c2f3a1?from=from_main_6

**Comment by zubrRB** [comment]
+КиноПоиск: https://www.kinopoisk.ru/film/2441/?from=discovery_player

**Comment by zubrRB** [comment]
+Men’s Health с 5 миллионами уникальных пользователей  в месяц и более 1 миллиона подписчиков в соцсетях.
https://www.mhealth.ru/technics/news/neyroset-nachala-shtrafovat-voditeley-za-vyklyuchennye-fary/?from=main_photo

**Comment by Alex-302** [comment]
Так значения особого интереса не представляют же.

**Comment by zubrRB** [comment]
Отслеживают места переходов (области кликов) внутри сайтов.

**Comment by zubrRB** [comment]
+3DNews: https://3dnews.ru/1047433/microsoft-gotovitsya-k-zapusku-windows-11-v-oktyabre-2021-goda?from=related-grid&from-source=1047782

**Comment by zubrRB** [comment]
+Яндекс: https://yandex.ru/news?from=tabbar

**Comment by zubrRB** [comment]
Для yandex и amazon избирательно заданы правила удаления параметра `from`. Чем они хуже, а все остальные лучше?)

**Comment by zubrRB** [comment]
+Mail.ru:
https://my.mail.ru/?from=whiteline&utm_source=portal&utm_medium=portal_navigation&utm_campaign=my.mail.ru
https://games.mail.ru/?from=navi&utm_source=portal&utm_medium=portal_navigation&utm_campaign=games.mail.ru
https://news.mail.ru/?from=menu&utm_source=portal&utm_medium=portal_navigation&utm_campaign=news.mail.ru
https://e.mail.ru/payment/center/gibdd?from=headline

Отдельно ещё такого вида там же на Mail.ru:
https://youla.ru/?fromheadline=1&utm_source=portal&utm_medium=portal_navigation&utm_campaign=youla.ru
https://tamtam.chat/?fromportal=1
https://vseapteki.ru/?frommail

**Comment by Alex-302** [comment]
> Для yandex и amazon избирательно заданы правила удаления параметра `from`. Чем они хуже, а все остальные лучше?)

значения параметра у них различные, а здесь энтропия низкая.

**Comment by zubrRB** [comment]
Лишние длиннющие параметры в адресной строке браузера, как минимум, настораживают.

**Comment by Alex-302** [comment]
Проверь такие:
```
$removeparam=from,domain=rbc.ru|mhealth.ru|kinopoisk.ru|yandex.*|mail.ru|3dnews.ru
$removeparam=from-source,domain=3dnews.ru
$removeparam=fromheadline,domain=youla.ru
$removeparam=fromportal,domain=tamtam.chat
$removeparam=frommail,domain=vseapteki.ru
```

**Comment by zubrRB** [comment]
Эти все очищаются. Не забудь добавить домен ИД "Коммерсант" (самая первая ссылка в заголовке).

**Comment by zubrRB** [comment]
Здесь https://yandex.ru/all:
не очищает по заголовку "Услуги" https://uslugi.yandex.ru/category/uborka--3124?from=vrtx&text=геймерская%20уборка

При желании другие параметры: 
по заголовку "Диск": https://disk.yandex.ru/?source=services-main
по заголовку "Яндекс.Браузер": https://browser.yandex.ru/?banerid=0400004260

_________
Здесь https://yandex.ru/news при клике вверху "Картинки" и "Видео" ссылки преобразуются и содержат параметр `?rdrnd`:

https://yandex.ru/images/?from=tabbar > https://yandex.ru/images/?rdrnd=76771&redircnt=1632910799.1
https://yandex.ru/video/?from=tabbar > https://yandex.ru/video/search?rdrnd=457579&text=видео
И на каждом из них свои отслеживающие параметры в тех же местах.

**Comment by zubrRB** [comment]
https://www.goodhouse.ru/stars/zvezdnye-istorii/10-rossiyskih-zvezd-kotorye-umerli-ot-raka/?from=main_photo
