### ISSUE TITLE
forum.release-apk.com

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#85472]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

При открытии треда на ресурсе в браузере текст треда скрывается такой вот AntiAdBlock плашкой :

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/12525093/121546266-af995280-c9fa-11eb-8c81-b71ecfde837c.jpg)
</details><br/>

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 5.1
Browser:                               | Chrome 71.0.3578.99
AdGuard version:                       | 3.6.2
Filters enabled:                       | ?
AdGuard mode (Android only):           |  Proxy (manual)
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Повтор
https://github.com/AdguardTeam/AdguardFilters/issues/84456
Они быстро адаптируются, следят за репортами.

**Comment by Baltazar500** [comment]
>Они быстро адаптируются, следят за репортами.

Ну т.е. проблема нерешаема ? Или есть варианты ? Или раз там реагируют быстро на этот сайт можно забить ? Просто я проверял время от времени после закрытия issue наличие плашки - она как была так и осталась на месте. Хотя фильтры я обновлял перед проверкой.

**Comment by krystian3w** [comment]
Maybe possibile use Extended CSS to hide placeholders instead defuse anti-adblock (page mostly checking how you hide empty placeholders).

**Comment by Baltazar500** [comment]
Where can I find Extended CSS ? How can I use it in AdGuard for Android ?

**Comment by krystian3w** [comment]
E.g.:

https://github.com/uBlockOrigin/uAssets/issues/8489#issuecomment-859013470
https://github.com/uBlockOrigin/uAssets/commit/d5cebdd3164a7cfe14b43e07d80b1551020d3473

**Comment by Alex-302** [comment]
@Baltazar500 Решаема, если не добавлять правила в общие фильтры, а держать у себя. В их скриптах видно все проверки для прошлых решений. Через гитхаб отслеживать новые правила особненно легко и удобно. Теперь и за убошными правилами будут следить.

**Comment by Baltazar500** [comment]
>uBlockOrigin/uAssets@d5cebdd
@krystian3w, I added these rules to Adguard 3.6.2 for Android, but it didn't work

@Alex-302, я не дока в этом деле. Поэтому иду за помощью в данном вопросе к тем, кто в этом разбирается. Форум AdGuard'a полуживой и там ответа можно неделями ждать, а здесь хоть какая-никакая активность есть.

Ну и до кучи правила uBO для меня не работают ибо как сказали на forums.lanik.us - нужен свежий фокс и свежий uBo (у меня ESR 52.9.0, слезть с которого я пока не могу по ряду причин и uBO legacy), а иначе никак. 

Мб придётся использовать десктопный AdGuard. Главное, чтобы фильтры работали. Пока я тред из тестовой ссылки видел лишь в гугло-кеше ...

**Comment by Alex-302** [comment]
@Baltazar500 Сайтом же можно пользоваться вроде, только чуть дольше ждать, пока скрипт отработает и отобразится всё содержимое.

**Comment by Baltazar500** [comment]
@Alex-302, на десктопе в фоксе с uBo у меня вначале наг-скрин который если убрать (работает разово, потом надо заново), и антиадблок - плашка, за ним. В хроме на ведре с AdGuard 3.6.2  наг-скрина нет, но плашка всё так же "прибита гвоздями" к экрану и скрывает содержимое треда.
