### ISSUE TITLE
arc.io untracking ads (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#85497]
https://arc.io/ ---> `{your_website}/arc-sw.js`
```
/arc-sw.js
```

https://github.com/easylist/easylist/issues/7872

https://github.com/AdguardTeam/AdguardFilters/issues/83262

**Comment by c2xusnpq6** [comment]
similar mining platform:

> one more... https://joinmassive.com/ lite coin miner

**Comment by Alex-302** [comment]
https://github.com/easylist/easylist/issues/7872#issuecomment-856243239
