### ISSUE TITLE
aladdintv.co

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85539]
**Issue URL (Ads)** :
https://aladdintv.co/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121685250-53f3c580-cadd-11eb-9e72-7efb9819b224.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
