### ISSUE TITLE
desichannel.su

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85531]
**Issue URL (Ads)** : https://desichannel.su/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121683426-feb6b480-cada-11eb-85b7-a1a5a1814a4f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors (20300, >30000 required)

**Comment by chirag127** [comment]
I think that a Alexa country rank should also be a criteria as this website have a rank of 6188 in Pakistan . But if country rank is not a criteria in anyway for now than it's fine.
