### ISSUE TITLE
udariyaan.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85537]
**Issue URL (Ads)** : https://udariyaan.net/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121684723-b8625500-cadc-11eb-9025-7e1ae3656158.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
