### ISSUE TITLE
mehndihairachnewaali.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85538]
**Issue URL (Ads)** : https://mehndihairachnewaali.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121685082-227afa00-cadd-11eb-8496-771fa3785ae7.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
