### ISSUE TITLE
desitvchannel.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85541]
**Issue URL (Ads)** : https://desitvchannel.net/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121685552-b351d580-cadd-11eb-8fbc-9aa68cf0287c.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
