### ISSUE TITLE
multidesidrama.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85561]
**Issue URL (Ads)** :

https://multidesidrama.com/taarak-mehta-ka-ooltah-chashmah-11th-June-2021-watch-online/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121715483-911b8000-cafc-11eb-97c0-5d85490187ba.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
