### ISSUE TITLE
rudrakaal.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85560]
**Issue URL (Ads)** :
https://rudrakaal.net/taarak-mehta-ka-ooltah-chashmah-11th-june-2021-episode-3186-video-update

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121714941-f9b62d00-cafb-11eb-9a55-ca77c4a0f143.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The site has low visitors.
