### ISSUE TITLE
pl.tvn.player.tv

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#85603]
***Description***:
* **Current behaviour**: 

Throws an error message with protection enabled:
<details><summary>Screenshot:</summary>

![PXL_20210609_093618030](https://user-images.githubusercontent.com/33634917/121742698-de055380-cb08-11eb-91b1-70ec495457a8.jpg)

</details><br/>

***Steps to reproduce the problem***:

1. Install the app on a TV box and try to open something

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 9
Browser:                               | N/A
AdGuard version:                       | 4.0.55
Filters enabled:                       | "Oficjalne polskie filtry dla AdBlock, uBlock Origin i AdGuard", "Filtr reklam dla urządzeń mobilnych AdGuard", "Filtr elementów szpiegujących AdGuard", "Podstawowy filtr AdGuard", "Polski filtr przeciwko alertom o Adblocku", "Filtr irytujących elementów AdGuard", "Filtr mediów społecznościowych AdGuard"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | Off
AdGuard DNS:                           |  Default
Helpdesk ID (if exists):               | Z516143

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
It may be related to this issue - https://github.com/AdguardTeam/AdguardForAndroid/issues/3646#issuecomment-720350439 and caused by DNS filtering option enabled, but I'm not able to check it anymore, because if I'm not wrong, this app offers only paid content now.

**Comment by krystian3w** [comment]
Tak, teraz trzeba dać im "łapówkę" 30 zł na rok.
