### ISSUE TITLE
Заглушка на сайте https://forum.brcbet.com

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#8566]
При входе на сайт заглушка, раньше не было. Я думаю, что логи тут не нужны, проблема на всех устройствах, iOS и Android, так что должна появится у @Alex-302. Если будет так необходимо, то прикреплю логи

**Comment by ministr91** [comment]
https://forum.brcbet.com
![screenshot_2017-12-18-02-14-05](https://user-images.githubusercontent.com/22351242/34084921-2b2e9aa8-e391-11e7-8be9-a49b48f25124.png)

**Comment by ministr91** [comment]
На ПК эта проблема тоже должна быть. У меня стоит блокировщик баннеров от Касперского и эта табличка появляется тоже, хотя раньше не было.

**Comment by Alex-302** [comment]
Скрины всегда под спойлер прячь
```

<details>


</details>
```

**Comment by ministr91** [comment]
хорошо, @Alex-302. Я уже не надеялся на решение, думал, что без логов не будешь решать.

**Comment by ministr91** [comment]
@Alex-302 спасай, они его улучшили
<details>
![screenshot_2017-12-21-13-54-14](https://user-images.githubusercontent.com/22351242/34252924-2ba44f7c-e64e-11e7-8db4-2028a922e010.png)
</details>
