### ISSUE TITLE
docviewer.yandex.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#85685]
**Блокировка рекламы.**

<details><summary>Screenshot:</summary>

![2021 06 12-4](https://user-images.githubusercontent.com/17948007/121784589-66453080-cbbd-11eb-80c3-956224e82471.png)
----------
![2021 06 12-5](https://user-images.githubusercontent.com/17948007/121784597-6f360200-cbbd-11eb-8b17-a65e10407e66.png)
----------
![2021 06 12-1](https://user-images.githubusercontent.com/17948007/121784631-a1476400-cbbd-11eb-9940-feaba5084228.png)
</details>

`docviewer.yandex.*##.fullscreen-container [style="width: 100%;"]`

___________________________________________________

 **Убирание остаточного отступа.**

<details><summary>Screenshot:</summary>

![2021 06 12-2](https://user-images.githubusercontent.com/17948007/121784781-a22cc580-cbbe-11eb-882a-3920d604b4bf.png)
----------
![2021 06 12-3](https://user-images.githubusercontent.com/17948007/121784798-ace75a80-cbbe-11eb-82fd-33f29cbe03e3.png)
</details>

`docviewer.yandex.*#$#[class=""] > div[class] { top: unset !important; height: calc(100vh - 100%) !important; }`

 Ссылка 1 (GitHub декодирует символы в ссылке, после чего она становится нерабочей, поэтому так):
`https://href.li/?https://docviewer.yandex.ru/view/0/?*=N35NhBf%2BmtKwzOxGPBBR700RbkB7InVybCI6InlhLWRpc2stcHVibGljOi8vSGFUR3FJOVRubmhvLytJejA0Qm5HMG5xYW5WUmhFbDZIZ1ZJSGRXUXhTaz06L19QYWNrYWdlc19BcHB4X2ZpbGVzL1BhY2thZ2VzX2Zvcl9MVFNDL1BhY2thZ2VzX2Zvcl9MVFNDLnR4dCIsInRpdGxlIjoiUGFja2FnZXNfZm9yX0xUU0MudHh0Iiwibm9pZnJhbWUiOmZhbHNlLCJ1aWQiOiIwIiwidHMiOjE2MjM1MTY4MzYxMTQsInl1IjoiMjAxMzc2MDcxNjIzNTE2ODM2In0%3D`

[Ссылка 2](https://href.li/?https://docviewer.yandex.ru/view/0/?*=Jl7VBlyWHE%2F8HeWeoLcIdtkBJYB7InVybCI6InlhLWRpc2stcHVibGljOi8vSGFUR3FJOVRubmhvLytJejA0Qm5HMG5xYW5WUmhFbDZIZ1ZJSGRXUXhTaz06L1dpbmRvd3MgMTAgMTgwOSAtIDIxSDEvT2xkIHZlcnNpb25zL0F1dG9TZXR0aW5nc1BTX3YuMC4yLjcuemlwIiwidGl0bGUiOiJBdXRvU2V0dGluZ3NQU192LjAuMi43LnppcCIsIm5vaWZyYW1lIjpmYWxzZSwidWlkIjoiMCIsInRzIjoxNjIzNTE1NDc2NTA2LCJ5dSI6IjQ5ODc4NzY5OTE2MjM1MTU0NzYifQ%3D%3D)

___________________________________________________
 Adguard v3.6.6 | FireFox v78.10 ESR | Win7SP1
Базовый фильтр AdGuard | Фильтр отслеживания по URL | Фильтр счетчиков и систем аналитики
Фильтр виджетов социальных сетей | Фильтр раздражителей | Русский фильтр
 Антитрекинг: Стандарт + Блокировка WebRTC

**Comment by Alex-302** [comment]
Там и так чисто, с Экстрой.

**Comment by XX-J** [comment]
...если бы она была встроена в AdGuard.
 Но, в некоторых случаях, как видим, можно обойтись и без неё...
