### ISSUE TITLE
kingsoftoday.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85691]
**Issue URL (Social Widget)** : https://kingsoftoday.com/how-to-stop-beard-growth/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121786894-66a2f300-cbe0-11eb-9730-2d27eec310b2.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors
