### ISSUE TITLE
adespresso.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85716]
***Issue URL (Annoyance)***:
https://adespresso.com/blog/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121799617-be764400-cc4a-11eb-8c22-5d827df87dcb.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
this is their own ad

**Comment by chirag127** [comment]
@Sergey-Lyapin that's why I reported it as Annoyance in self promotion .
