### ISSUE TITLE
godbolt.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85726]
***Issue URL (Ads + Annoyance)***: https://godbolt.org/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121800143-bff53b80-cc4d-11eb-8efb-cad18687d7a9.png)
![image](https://user-images.githubusercontent.com/76880977/121800141-bec40e80-cc4d-11eb-8524-0c3a640e454b.png)
![image](https://user-images.githubusercontent.com/76880977/121800142-bf5ca500-cc4d-11eb-93e8-6ef961aa0afa.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
@Sergey-Lyapin I can't open `Privacy policy` with your rules.
1. Open this website in the Incognito mode (Chrome).
2. Click on the `Privacy policy`.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/122940345-10227b00-d37d-11eb-9ff5-51225c32a1c2.png)
</details><br/>
