### ISSUE TITLE
runnersworld.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85733]
***Issue URL (Annoyance)***: https://www.runnersworld.com/runners-stories/a36688883/gabby-thomas-olympic-trials/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121800605-912c9480-cc50-11eb-9a5e-70a9631d2694.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
This element doesn't annoy.
