### ISSUE TITLE
wapkiz.site

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85773]
**Issue URL (Ads)** : https://mp3tau.wapkiz.site/page-download/2078/DJ-Pe-Nachungi.html%22 

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121815930-5fd6b780-cc96-11eb-8617-9ec0b0aa4f53.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors
