### ISSUE TITLE
app.posthog.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#85777]
***Description***:
* **Current behaviour**: 

Whole domain (and associated web app) gets blocked as a tracker.

* **Expected behaviour**: 

Only the following paths should be blocked:

https://app.posthog.com/static/array.js
https://app.posthog.com/static/recorder.js
https://app.posthog.com/decide/
https://app.posthog.com/e/
https://app.posthog.com/s/

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 9
Browser:                               | n/a
AdGuard version:                       | 3.6 release
Filters enabled:                       | Base, Russian, Annoyances, Mobile ads
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | Z517016

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not blocked
![image](https://user-images.githubusercontent.com/8361299/122271393-06fe5d80-cee8-11eb-868e-5da82fb3540d.png)

Need more details.

**Comment by Alex-302** [comment]
@akmLaVx
