### ISSUE TITLE
Slack `/api/ublockworkaround.history`

### ISSUE THREAD

**Issue by shreyasminocha** [AdguardTeam/AdguardFilters#85846]
Slack seems to be making two `POST` requests to the suspiciously named `/api/ublockworkaround.history`. When I block these requests with uBO it attempts to make these requests four times before triggering what looks like a page refresh with the additional query parameter `force_cold_boot=1`, after which no such requests are attempted. Blocking the request doesn't seem to break any functionality, but I'm not sure — someone should probably verify this.

From what I understand the request tries to fetch a history of slack-related events (`apps_uninstalled,channel_deleted,channel_rename,channel_history_changed,commands_changed,email_shared,…`) which doesn't seem problematic, but the name of the endpoint is enough to raise my suspicions.

You'll need to sign in to a slack workspace and open the web client to reproduce.

<details>
<summary>Request HAR (long)</summary>

<pre>
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "LibreWolf",
      "version": "89.0"
    },
    "browser": {
      "name": "LibreWolf",
      "version": "89.0"
    },
    "pages": [
      {
        "startedDateTime": "2021-06-14T12:49:39.536+00:00",
        "id": "page_1",
        "title": "Slack",
        "pageTimings": {
          "onContentLoad": -1623674974334,
          "onLoad": -1623674974334
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_1",
        "startedDateTime": "2021-06-14T12:49:39.536+00:00",
        "request": {
          "bodySize": 1287,
          "method": "POST",
          "url": "https://[redacted].slack.com/api/ublockworkaround.history?_x_id=[redacted]&_x_csid=[redacted]&slack_route=[redacted]&_x_version_ts=1623664339&_x_gantry=true",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "[redacted].slack.com"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Content-Type",
              "value": "multipart/form-data; boundary=---------------------------41783809426267831843649887472"
            },
            {
              "name": "Content-Length",
              "value": "1287"
            },
            {
              "name": "Origin",
              "value": "https://app.slack.com"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "b=[redacted]; d=[redacted]; d-s=[redacted]; lc=[redacted]; shown_ssb_redirect_page=1; shown_download_ssb_modal=1; show_download_ssb_banner=1; no_download_ssb_banner=1; x=[redacted]"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [
            {
              "name": "b",
              "value": "[redacted]"
            },
            {
              "name": "d",
              "value": "[redacted]"
            },
            {
              "name": "d-s",
              "value": "[redacted]"
            },
            {
              "name": "lc",
              "value": "[redacted]"
            },
            {
              "name": "shown_ssb_redirect_page",
              "value": "1"
            },
            {
              "name": "shown_download_ssb_modal",
              "value": "1"
            },
            {
              "name": "show_download_ssb_banner",
              "value": "1"
            },
            {
              "name": "no_download_ssb_banner",
              "value": "1"
            },
            {
              "name": "x",
              "value": "[redacted]"
            }
          ],
          "queryString": [
            {
              "name": "_x_id",
              "value": "[redacted]"
            },
            {
              "name": "_x_csid",
              "value": "[redacted]"
            },
            {
              "name": "slack_route",
              "value": "[redacted]"
            },
            {
              "name": "_x_version_ts",
              "value": "1623664339"
            },
            {
              "name": "_x_gantry",
              "value": "true"
            }
          ],
          "headersSize": 978,
          "postData": {
            "mimeType": "multipart/form-data; boundary=---------------------------41783809426267831843649887472",
            "params": [],
            "text": "-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"start\"\r\n\r\n1623674927.500000\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"count\"\r\n\r\n2000\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"no_payload_if_has_more\"\r\n\r\ntrue\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"batch_deleted_files\"\r\n\r\ntrue\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"include_events\"\r\n\r\nmessage\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"token\"\r\n\r\n[redacted]\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"_x_reason\"\r\n\r\nfetchEventLogHistoryImmediately\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"_x_mode\"\r\n\r\nonline\r\n-----------------------------41783809426267831843649887472\r\nContent-Disposition: form-data; name=\"_x_sonic\"\r\n\r\ntrue\r\n-----------------------------41783809426267831843649887472--\r\n"
          }
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "date",
              "value": "Mon, 14 Jun 2021 12:49:39 GMT"
            },
            {
              "name": "server",
              "value": "Apache"
            },
            {
              "name": "x-xss-protection",
              "value": "0"
            },
            {
              "name": "pragma",
              "value": "no-cache"
            },
            {
              "name": "strict-transport-security",
              "value": "max-age=31536000; includeSubDomains; preload"
            },
            {
              "name": "cache-control",
              "value": "private, no-cache, no-store, must-revalidate"
            },
            {
              "name": "access-control-allow-origin",
              "value": "https://app.slack.com"
            },
            {
              "name": "x-slack-req-id",
              "value": "[redacted]"
            },
            {
              "name": "access-control-allow-credentials",
              "value": "true"
            },
            {
              "name": "x-content-type-options",
              "value": "nosniff"
            },
            {
              "name": "referrer-policy",
              "value": "no-referrer"
            },
            {
              "name": "access-control-expose-headers",
              "value": "x-slack-req-id, retry-after"
            },
            {
              "name": "x-slack-backend",
              "value": "r"
            },
            {
              "name": "x-oauth-scopes",
              "value": "identify,read,post,client,apps"
            },
            {
              "name": "x-accepted-oauth-scopes",
              "value": "read"
            },
            {
              "name": "expires",
              "value": "Mon, 26 Jul 1997 05:00:00 GMT"
            },
            {
              "name": "access-control-allow-headers",
              "value": "slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags"
            },
            {
              "name": "vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "content-encoding",
              "value": "gzip"
            },
            {
              "name": "content-length",
              "value": "69"
            },
            {
              "name": "content-type",
              "value": "application/json; charset=utf-8"
            },
            {
              "name": "x-envoy-upstream-service-time",
              "value": "25"
            },
            {
              "name": "x-backend",
              "value": "main_normal main_canary_with_overflow main_control_with_overflow"
            },
            {
              "name": "x-server",
              "value": "slack-www-hhvm-main-iad-uyiu"
            },
            {
              "name": "x-via",
              "value": "envoy-www-iad-3e4k, haproxy-edge-fra-yqtf"
            },
            {
              "name": "x-slack-shared-secret-outcome",
              "value": "shared-secret"
            },
            {
              "name": "via",
              "value": "envoy-www-iad-3e4k"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json; charset=utf-8",
            "size": 50,
            "text": "{\"ok\":true,\"events\":[],\"has_more\":false,\"total\":0}"
          },
          "redirectURL": "",
          "headersSize": 1189,
          "bodySize": 1258
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 289,
          "receive": 0
        },
        "time": 289,
        "_securityState": "secure",
        "serverIPAddress": "3.123.248.34",
        "connection": "443"
      },
      {
        "pageref": "page_1",
        "startedDateTime": "2021-06-14T12:49:39.538+00:00",
        "request": {
          "bodySize": 1625,
          "method": "POST",
          "url": "https://[redacted].slack.com/api/ublockworkaround.history?_x_id=[redacted]&_x_csid=[redacted]&slack_route=[redacted]&_x_version_ts=1623664339&_x_gantry=true",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "[redacted].slack.com"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Content-Type",
              "value": "multipart/form-data; boundary=---------------------------961089496603925592392623961"
            },
            {
              "name": "Content-Length",
              "value": "1625"
            },
            {
              "name": "Origin",
              "value": "https://app.slack.com"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "b=[redacted]; d=[redacted]; d-s=[redacted]; lc=[redacted]; shown_ssb_redirect_page=1; shown_download_ssb_modal=1; show_download_ssb_banner=1; no_download_ssb_banner=1; x=[redacted]"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [
            {
              "name": "b",
              "value": "[redacted]"
            },
            {
              "name": "d",
              "value": "[redacted]"
            },
            {
              "name": "d-s",
              "value": "[redacted]"
            },
            {
              "name": "lc",
              "value": "[redacted]"
            },
            {
              "name": "shown_ssb_redirect_page",
              "value": "1"
            },
            {
              "name": "shown_download_ssb_modal",
              "value": "1"
            },
            {
              "name": "show_download_ssb_banner",
              "value": "1"
            },
            {
              "name": "no_download_ssb_banner",
              "value": "1"
            },
            {
              "name": "x",
              "value": "[redacted]"
            }
          ],
          "queryString": [
            {
              "name": "_x_id",
              "value": "[redacted]"
            },
            {
              "name": "_x_csid",
              "value": "[redacted]"
            },
            {
              "name": "slack_route",
              "value": "[redacted]"
            },
            {
              "name": "_x_version_ts",
              "value": "1623664339"
            },
            {
              "name": "_x_gantry",
              "value": "true"
            }
          ],
          "headersSize": 976,
          "postData": {
            "mimeType": "multipart/form-data; boundary=---------------------------961089496603925592392623961",
            "params": [],
            "text": "-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"start\"\r\n\r\n1623674927.500000\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"count\"\r\n\r\n2000\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"no_payload_if_has_more\"\r\n\r\ntrue\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"batch_deleted_files\"\r\n\r\ntrue\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"include_events\"\r\n\r\napps_uninstalled,channel_deleted,channel_rename,channel_history_changed,commands_changed,email_shared,emoji_changed,external_org_migration_started,external_org_migration_finished,file_deleted,force_reload,group_history_changed,im_deleted,im_history_changed,mpim_history_changed,pin_added,pin_removed,star_added,star_removed,subteam_deleted,teams_left_shared_channel\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"token\"\r\n\r\n[redacted]\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"_x_reason\"\r\n\r\nfetchEventLogHistoryImmediately\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"_x_mode\"\r\n\r\nonline\r\n-----------------------------961089496603925592392623961\r\nContent-Disposition: form-data; name=\"_x_sonic\"\r\n\r\ntrue\r\n-----------------------------961089496603925592392623961--\r\n"
          }
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "date",
              "value": "Mon, 14 Jun 2021 12:49:39 GMT"
            },
            {
              "name": "server",
              "value": "Apache"
            },
            {
              "name": "x-xss-protection",
              "value": "0"
            },
            {
              "name": "pragma",
              "value": "no-cache"
            },
            {
              "name": "strict-transport-security",
              "value": "max-age=31536000; includeSubDomains; preload"
            },
            {
              "name": "cache-control",
              "value": "private, no-cache, no-store, must-revalidate"
            },
            {
              "name": "access-control-allow-origin",
              "value": "https://app.slack.com"
            },
            {
              "name": "x-slack-req-id",
              "value": "[redacted]"
            },
            {
              "name": "access-control-allow-credentials",
              "value": "true"
            },
            {
              "name": "x-content-type-options",
              "value": "nosniff"
            },
            {
              "name": "referrer-policy",
              "value": "no-referrer"
            },
            {
              "name": "access-control-expose-headers",
              "value": "x-slack-req-id, retry-after"
            },
            {
              "name": "x-slack-backend",
              "value": "r"
            },
            {
              "name": "x-oauth-scopes",
              "value": "identify,read,post,client,apps"
            },
            {
              "name": "x-accepted-oauth-scopes",
              "value": "read"
            },
            {
              "name": "expires",
              "value": "Mon, 26 Jul 1997 05:00:00 GMT"
            },
            {
              "name": "access-control-allow-headers",
              "value": "slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags"
            },
            {
              "name": "vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "content-encoding",
              "value": "gzip"
            },
            {
              "name": "content-length",
              "value": "69"
            },
            {
              "name": "content-type",
              "value": "application/json; charset=utf-8"
            },
            {
              "name": "x-envoy-upstream-service-time",
              "value": "22"
            },
            {
              "name": "x-backend",
              "value": "main_normal main_canary_with_overflow main_control_with_overflow"
            },
            {
              "name": "x-server",
              "value": "slack-www-hhvm-main-iad-rhcu"
            },
            {
              "name": "x-via",
              "value": "envoy-www-iad-3oc5, haproxy-edge-fra-yqtf"
            },
            {
              "name": "x-slack-shared-secret-outcome",
              "value": "shared-secret"
            },
            {
              "name": "via",
              "value": "envoy-www-iad-3oc5"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json; charset=utf-8",
            "size": 50,
            "text": "{\"ok\":true,\"events\":[],\"has_more\":false,\"total\":0}"
          },
          "redirectURL": "",
          "headersSize": 1189,
          "bodySize": 1258
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 288,
          "receive": 0
        },
        "time": 288,
        "_securityState": "secure",
        "serverIPAddress": "3.123.248.34",
        "connection": "443"
      }
    ]
  }
}
</pre>
</details>

**Comment by Alex-302** [comment]
Hi. Maybe uBO breaks something. I don't know what is it. And not sure if these requests must be blocked. I see them withoiut ad blcoker.
