### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#85858]
Вопрос не столько по рекламе, сколько по фильтрам, поэтому таблицу заполнять не стал (тем более вручную через правку markdown это делать гемморойно и долго).

Как на pikabu.ru дезактивировать фильтрами бесконечный скролл страниц и задействовать постраничный просмотр, что спрятан в блоке noscript ? С помощью фильтров это возможно ? Мб есть на JS какие костыли, которые можно через adguard заюзать ?

**Comment by Alex-302** [comment]
Смотря какой Адгард. 
Если программа или расширение для Фокса, то помогут такие правила:
```
pikabu.ru##.stories-feed__spinner
||pikabu.ru/?twitmode=1
pikabu.ru$replace=/<noscript>|<\/noscript>//
```
Третье правило удаляет тэг `noscript`, второе - блокирует подгрузку.

**Comment by Baltazar500** [comment]
@Alex-302, а для AdGuard'a под андроид это решение сгодится ? Или там уже не прокатит ?

**Comment by Alex-302** [comment]
Не проверял.

**Comment by Baltazar500** [comment]
>Не проверял. Но синтаксис поддерживается.

На старом смарте с ведром 4.2 и AdGuard 2.12.250 (последний для 4.2) данный набор правил работает идельно. На смарте с 5.1 и AdGuard 3.6.2 noscript выпиливается, а скролл (спиннер) продолжает работать. Хром в обоих случаях с той же версии и с тем же UA. Режимы фильтрации идентичные. Я хз что не так.

**Comment by Alex-302** [comment]
```
||pikabu.ru/?twitmode=1
pikabu.ru$~script,~xmlhttprequest,replace=/<noscript>|<\/noscript>//
pikabu.ru##.stories-feed__spinner
```
вот так сработает.

**Comment by Baltazar500** [comment]
Спасибо. На 3.6.2 скролл ушёл ;)

**Comment by Baltazar500** [comment]
С правилом

>pikabu.ru$~script,~xmlhttprequest,replace=/<noscript>|<\/noscript>//

вылезли проблемы в гуглопоиске. Запрос вида

>site:pikabu.ru abc

в поиске гугла уводит оный в loop с бесконечными редиректами. Вырубаю правило - всё работает нормально.

**Comment by Baltazar500** [comment]
Добавил в начало правила "||"и проблема ушла. Как оно кореллировало с гуглом я так и не понял

**Comment by Baltazar500** [comment]
На 2.12.250 поломался постраничный просмотр, хотя на днях всё работало
![2021 08 19_17 04 06~01](https://user-images.githubusercontent.com/12525093/130023649-b53e36f5-fcac-42a6-bc0d-78ad14631bfc.jpg)

**Comment by Alex-302** [comment]
> Добавил в начало правила "||"и проблема ушла. Как оно кореллировало с гуглом я так и не понял

примерялось к адресу, который содержал `pikabu.ru`

**Comment by Alex-302** [comment]
Попробуйте
`pikabu.ru$$noscript`

**Comment by Baltazar500** [comment]
Поломалось правило. Что-то поменяли и скролл снова вознобновил работу.
