### ISSUE TITLE
lifehacker.ru баннер над шапкой

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#8586]
Появился гугловский баннер над шапкой lifehacker.ru.
<details><summary>скрин:</summary>

![image](https://image.prntscr.com/image/okFlyIQaQ1mmSJafxz2P_A.jpg)
</details><br/>

**Comment by Alex-302** [comment]
Заполни шаблон или отправь отчёт.

**Comment by Smorvel** [comment]
После удаления печенек реклама пропала, и больше немогу заставить ее появится...

**Comment by bufferbay** [comment]
Спасибо, что убиваете нас.
