### ISSUE TITLE
lostallhope.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85875]
***Issue URL (Annoyance)***: https://lostallhope.com/suicide-methods/statistics-most-lethal-methods

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121931604-7564e380-cd61-11eb-9542-2f4a1f77b4cc.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
We don't block age-confirming popups.
