### ISSUE TITLE
lionsroar.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85870]
***Issue URL (Annoyance)***:
https://www.lionsroar.com/right-way-kill/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121926592-bc4fda80-cd5b-11eb-8d93-3c2470a0039b.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
We don't block donation widgets

**Comment by chirag127** [comment]
I found it quite big and annoying .
