### ISSUE TITLE
gramajyothi.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85909]
**Issue URL (Ads)** : http://www.gramajyothi.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122002621-9cf29500-cdcf-11eb-92f5-3368d037533f.png)
![image](https://user-images.githubusercontent.com/76880977/122002620-9cf29500-cdcf-11eb-91d7-61027c18478e.png)
![image](https://user-images.githubusercontent.com/76880977/122002622-9d8b2b80-cdcf-11eb-9984-3c272dac67d1.png)
![image](https://user-images.githubusercontent.com/76880977/122002648-a8de5700-cdcf-11eb-8312-ba5d43d17ac3.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors
