### ISSUE TITLE
swarajnewstoday.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#85908]
**Issue URL (Ads)** : http://swarajnewstoday.com/news-details.php?news_id=8927

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122002402-4edd9180-cdcf-11eb-9324-340a41cc439e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors
