### ISSUE TITLE
shopee huge update

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#85906]
https://github.com/search?q=org%3AAdguardTeam+__t__&type=code

https://github.com/AdguardTeam/FiltersRegistry/blob/fff490854931445cfce4db4a1409933dbcb573ba/filters/ThirdParty/filter_202_Adblock-Thai/filter.txt#L608-L612

![image](https://user-images.githubusercontent.com/75058881/121995052-ea273480-cdd8-11eb-9ee7-f088e7a63b86.png)

```
||akamaihd.net/shopee/*/*TrackingRules$script,domain=shopee.*
||akamaihd.net/shopee/*/TrackingRules$script,domain=shopee.*
||shopee.*/__t__$xmlhttprequest
||shopee.*/userstats_record$xmlhttprequest
||shopeemobile.com/*/tr$xmlhttprequest
```

![Screenshot_20210615-124745_Trebuchet.png](https://user-images.githubusercontent.com/75058881/121994627-2f973200-cdd8-11eb-853a-e1a2c74a0ac7.png)

https://github.com/AdguardTeam/AdguardFilters/issues/83751

https://github.com/easylist/easylist/search?q=shopee

https://github.com/AdguardTeam/AdguardFilters/search?q=shopee

https://github.com/AdguardTeam/AdguardFilters/blob/809879f915987f380830ae9d3a79b9b57d70d119/MobileFilter/sections/css_extended.txt#L214

**Comment by c2xusnpq6** [comment]
tracker? (not sure)
```
https://df.infra.shopee.tw/v2/shpsec/report
https://live.shopee.tw/dataapi/dataweb/event/reportPB
```

**Comment by zloyden** [comment]
I can't reproduce those requests on my end.
> https://c-api-bit.shopeemobile.com/tw/dp

This is a tracker and we have a rule in AdGuard Tracking Protection.

**Comment by c2xusnpq6** [comment]
```
http://content.garena.com/shopee/track_config/conf.json

||df.infra.shopee.TLD/v*/shpsec/report
||df.infra.shopee.TLD/v*/shpsec/event
||shopee.TLD/userstats_record$xmlhttprequest
||shopee.TLD/__t__$xmlhttprequest
||content.garena.com/shopee/track_config^
```

**Comment by c2xusnpq6** [comment]
chinese tencent's shopee app .apk download: https://apkpure.com/p/com.shopee.ph
https://apkpure.com/p/com.shopee.th
https://apkpure.com/p/com.shopee.sg
...

https://www.google.com/search?q=site:apkpure.com+shopee
