### ISSUE TITLE
google ads?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#85907]
```
https://growth-pa.googleapis.com:443/google.internal.identity.growth.v1.GrowthApiService/GetPromos

||growth-pa.googleapis.com/google.internal.identity.growth.v1.GrowthApiService/GetPromos^
or
||growth-pa.googleapis.com/*/GetPromos^
```

![Screenshot_20210615-132907_Trebuchet.png](https://user-images.githubusercontent.com/75058881/121998119-fa8dde00-cddd-11eb-9901-54b2974c76df.png)

![Screenshot_20210615-132934_Trebuchet.png](https://user-images.githubusercontent.com/75058881/121998123-fbbf0b00-cddd-11eb-971f-184afea98370.png)

**Comment by Alex-302** [comment]
No.
