### ISSUE TITLE
[URL Tracking filter] add _atrk_opts ?

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#85920]
@dnmTX commented on [Sat Jun 12 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3820)

Hello @AdguardTeam 👋 . This could be of interest as a new edition to the Tracking filter list.
Discovered it in `vidhotel.com`. The video link originated from `streamz.ws` This is the content of the script:
```
script type = "text/javascript" >
    _atrk_opts = {
        atrk_acct: "Ltftk1aUy100i4",
        domain: "streamz.ws",
        dynamic: true
    };
(function() {
    var as = document.createElement('script');
    as.type = 'text/javascript';
    as.async = true;
    as.src = "https://certify-js.alexametrics.com/atrk.js";
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(as, s);
})();

```
Just to note here,if there are plans to add `certify-js.alexametrics.com`. 
I did some research and it looks like most of the time the delivery domains for the same script are from `cloudflare.com` but
`/atrk.js` is present in all cases.

Cheers 👍 

P.S. I just saw that `alexametrics.com` is listed in the Tracking Protection filter,which didn't stop the script neither blocked the domain !

**Comment by TheHasagi** [comment]
@Alex-302 

Please, assist with the question.

**Comment by Alex-302** [comment]
There are no urls with that parameter.
