### ISSUE TITLE
energienutricao.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#85970]
[https://energienutricao.com.br/blog/cogumelo-nao-e-fonte-de-proteina-voce-sabia/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://energienutricao.com.br/blog/cogumelo-nao-e-fonte-de-proteina-voce-sabia/)

Overlay when you scroll down:

![overlay](https://user-images.githubusercontent.com/35470489/122101022-3b8bef80-cdea-11eb-8b96-cd66804b52b0.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Cannot access.

**Comment by adranger** [comment]
The site seems to be down today. Please check again tomorrow.
