### ISSUE TITLE
lastmomenttuitions.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86043]
***Issue URL (Annoyance)***: https://lastmomenttuitions.com/mcqs/first-year/basic-electrical-engineering/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122211585-867a3580-cec4-11eb-8baf-0ee6f8084071.png)
![image](https://user-images.githubusercontent.com/76880977/122211682-a01b7d00-cec4-11eb-9300-e1ccc84317cc.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
13600 visitors/month (> 30000 needed)

**Comment by chirag127** [comment]
@Sergey-Lyapin 
Okay,Please tell me the user filters .

**Comment by Sergey-Lyapin** [comment]
@chirag127
`lastmomenttuitions.com###popups`
