### ISSUE TITLE
ambebharti.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86052]
***Issue URL (Ads  + Annoyance)***: https://www.ambebharti.com/2020/08/aktu-final-year-mcq-based-sample-paper.html?m=1

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122213508-aa3e7b00-cec6-11eb-8bc1-13a317fb7669.png)
![image](https://user-images.githubusercontent.com/76880977/122213511-aad71180-cec6-11eb-9411-d76abde59f05.png)
![image](https://user-images.githubusercontent.com/76880977/122213509-aad71180-cec6-11eb-9773-2b61ae1239a0.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors
