### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86064]
**Issue URL (Ads)** : https://blockadblock.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122221272-bfb7a300-cece-11eb-875c-ac4d1864df7f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by krystian3w** [comment]
Maybe bait element and AdGuard disable anti-adblock with soft exceptions.

**Comment by chirag127** [comment]
@krystian3w   Nope ,

I turned off adguard and see It actually serve ads .

![image](https://user-images.githubusercontent.com/76880977/122289016-df22f000-cf0f-11eb-99d7-5854528d5e60.png)

**Comment by krystian3w** [comment]
so test `blockadblock.com#?#.adsbygoogle:upward(.well)`
