### ISSUE TITLE
chinese bytedance's pstatp.com ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#86080]
```
sf3-ttcdn-tos.pstatp.com

https://sf3-ttcdn-tos.pstatp.com/obj/ad-pattern/renderer/package.json

||pstatp.com/*ad-pattern^
```

[Screenshot_20210616-231057_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122245290-30bf8080-cef8-11eb-811b-5b3531a14343.png)

[Screenshot_20210616-231043_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122245293-31f0ad80-cef8-11eb-8a64-fad2c21397d3.png)

**Comment by c2xusnpq6** [comment]
巨量引擎 - 巨量引擎广告投放平台
北京巨量引擎网络技术有限公司

巨量引擎广告投放平台是字节跳动旗下的一站式营销服务平台，覆盖今日头条、抖音、西瓜视频、抖音火山版、懂车帝、穿山甲等产品数亿优质用户，推广定向 ...

巨量引擎是字节跳动旗下的官方营销服务品牌,整合了今日头条、抖音、西瓜视频等营销资源的广告投放平台,了解今日头条推广,抖音广告投放,抖音推广,抖音广告,抖 ...


![image](https://user-images.githubusercontent.com/75058881/122257745-de379180-cf02-11eb-8f06-830b60863ce8.png)

![Screenshot_20210617-002606_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122257498-a7617b80-cf02-11eb-9e99-56f3cbd640e2.png)

![Screenshot_20210617-002611_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122257518-acbec600-cf02-11eb-8cc1-352f116c31ab.png)

**Comment by Alex-302** [comment]
Ok.
