### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86107]
***Issue URL (Annoyance)***: https://blockadblock.com/adblocking/six-months-since-china-banned-ad-blockers/

> self- promo 

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122288300-6d4aa680-cf0f-11eb-9eee-8a3b6b9c8c6c.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by krystian3w** [comment]
Maybe better copy into oldie your opened topic or anonymus tagged opened topic.

**Comment by chirag127** [comment]
Naah, it have a different url + different issue .

**Comment by krystian3w** [comment]
AG bot generate mega issues and nobody who write comitts "cry" to split to smaller issues because one see ad, second tracking, 3-rd social button.


Other story is generate legacy domain like `maps.(google|yandex).*`.

**Comment by chirag127** [comment]
Hmm... Sounds interesting

who see ad ? ,who see tracking ? , who see social button ?.
