### ISSUE TITLE
jodilogik.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86104]
***Issue URL (Annoyance)***:
https://blog.jodilogik.com/index.php/arranged-marriage-proposal/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122284678-76397900-cf0b-11eb-8d23-766452ed7b97.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Please add to user rules:
`jodilogik.com##img[src$="/Add-some-colour_updated.png"]]`
