### ISSUE TITLE
book-drive.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86141]
***Issue URL (Annoyance)***: https://book-drive.com/let-us-c-17th-edition/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122342980-d6a7d500-cf62-11eb-8d03-f5d39ef302dc.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
We don't block donation widgets, please add to user rules `book-drive.com###custom_html-61`
