### ISSUE TITLE
appfolio app (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#86178]
||appfolio-analytics.com^

i think you have to have an account to see the tracker not sure though. but everything works fine with it blocked.

https://apps.apple.com/us/app/online-portal-by-appfolio/id1376350358

**Comment by Alex-302** [comment]
@jordanelliott23 Hi. I have no account. Could you please show full domain? `appfolio-analytics.com` is not resolved.

**Comment by jordanelliott23** [comment]
tenant-content.apm.appfolio-analytics.com
