### ISSUE TITLE
pornhub.org

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#86179]
***Issue URL ***: https://www.pornhub.org/channels/step-siblings

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/122468182-ff6ab180-cfd8-11eb-890a-63f641ca3244.png)

https://www.pornhub.org/channels/step-siblings
</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Not reproduced. It is hidden by Base filter.

**Comment by neer9** [comment]
@Alex-302
Are you sure you were at pornhub.org
I forgot to mention that you have to use Indian VPN to access pornhub.org
as pornhub.com is banned in India so pornhub.com redirects to pornhub.org
in indian . While outside India pornhub.org redirects to the pornhub.com .
So you will have to add rules for pornhub.org .

**Comment by neer9** [comment]
@Alex-302
Are you sure you were at pornhub.org ?
I forgot to mention that you have to use Indian VPN to access pornhub.org
as pornhub.com is banned in India, so Pornhub.com redirects to pornhub.org
In Indian. While outside India pornhub.org, redirects to the pornhub.com .
So you will have to add rules for pornhub.org .

**Comment by Alex-302** [comment]
Please check after filters update.

**Comment by neer9** [comment]
So you were not at pornhub.org ??? When you added can't reproduce .

**Comment by Alex-302** [comment]
Just added this domain to existing rule.

**Comment by neer9** [comment]
Yes , but I think you need to add this domain some others rules too. Please
just go to any video on pornhub.org with Indian vpn as there are ads left
overs there too . There is ad leftover just below the player with class
name underplayerad .

**Comment by Alex-302** [comment]
It redirects me to .com
Better show screenshot + code.

**Comment by neer9** [comment]
Did you tried to use Indian VPN as I had said in my previous ?

**Comment by neer9** [comment]
As I had search the Adguard base filter for rules for pornhub.org I found
many rules which are for pornhub.com . If it would have redirected everyone
to .com then no one would have added pornhub.org rules to the Adguard base
filter .
