### ISSUE TITLE
tubeninja.net

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#86180]
***Issue URL ***: https://www.tubeninja.net/?url=https%3A%2F%2Fwww.pornhub.org%2Fchannels%2Fbratty-sis

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/122468763-bd8e3b00-cfd9-11eb-8965-2e25531af430.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
I don't see this banner. Need full screenshot.

**Comment by neer9** [comment]
@Alex-302
I forgot to mention that it come after you put any video link and click the
download button

**Comment by neer9** [comment]
@Alex-302 
It comes after you put any video link  (e.g. https://www.youtube.com/watch?v=bi5PhlIQpwU  ) and click the
download button .

**Comment by Alex-302** [comment]
Fixed.
