### ISSUE TITLE
streamtape.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#86181]
***Issue URL ***: https://streamtape.com/v/2b0pjPLMQDuZ8xK

click on download button .

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/122470912-41e1bd80-cfdc-11eb-9350-0cf7b83e4fa2.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Too short.
