### ISSUE TITLE
Blocking ad js cdn

### ISSUE THREAD

**Issue by iieternal** [AdguardTeam/AdguardFilters#86212]
https://serpentcheerfullybeds.com/00/6d/e3/006de322d94b642e435fc6e6b36f095f.js

https://serpentcheerfullybeds.com/f0/63/15/f063151059dda8a63c1b51e01bf0388c.js

https://serpentcheerfullybeds.com

https://photographiccreche.com/a2/b3/31/a2b3311488877a183018689286e13b78.js

https://photographiccreche.com

The above links corresponds to ad cdn's. Please block them on the adguard extensions and dns. 
Ex site: https://1-23movies.cc/
https://o2tvseries.com

**Comment by Alex-302** [comment]
Hi. Already in Base filter.
