### ISSUE TITLE
latestlaws.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86224]
**Issue URL (Ads)** : https://www.latestlaws.com/legal-faqs/hindu-marriage-laws-faqs/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122575529-79994580-d06e-11eb-99f1-13a916750511.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by latestlaws** [comment]
Hi,

What is this issue, Can you explain please?

Thansk

**Comment by chirag127** [comment]
> Thansk

BTW,You typed s before k.Seems like you were in hurry while typing the comment.

**Comment by latestlaws** [comment]
Ohh, sorry for that.

Thanks again. :)
