### ISSUE TITLE
moddroid.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86280]
***Issue URL (Annoyance)***: https://moddroid.com/download/snaptube-21994/3

> can waiting time (Your link is almost ready, please wait a few seconds...) be skipped .

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122638037-58d4fc80-d10f-11eb-964b-ea751be7c375.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
`moddroid.com#%#//scriptlet("adjust-setTimeout", "download", "3000", "0.02")`
please add this to user rules

**Comment by chirag127** [comment]
@Sergey-Lyapin 

I'm using this rule from some days and it works completely fine. Is there any particular reason why it was not added to the filters? 
It have 24,680,000 Visitors/month .

**Comment by Sergey-Lyapin** [comment]
@chirag127
It's only 3 seconds to wait, it is not worth adding to the main filters.

**Comment by chirag127** [comment]
Ah, it's only 3 seconds. BTW, it is noticeably for me. I thought it's longer than that.

Yes,I agree it's not worth it.
