### ISSUE TITLE
pcmag.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86295]
***Issue URL (Annoyance)***: https://www.pcmag.com/news/hp-accused-of-quietly-installing-spyware-on-windows-pcs

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122640316-92603480-d11c-11eb-83c5-157e0686c6bf.png)
</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
Not an add or annoyance, but you can block it by adding pcmag.com###app > div.w-full:first-child to your userfilter.
