### ISSUE TITLE
Support for Hosts based filters in iOS 

### ISSUE THREAD

**Issue by VGisHere** [AdguardTeam/AdguardFilters#86300]
### Problem Description

There are many filters available over the net that support the hosts format which isn’t available in iOS
In iOS we have to directly put in URL preceded by ‘||’ while same would get replaced by 0.0.0.0 in hosts file
Having the ability to add hosts file URL to Custom filter would help.

### Proposed Solution

While interpreting the file, if 0.0.0.0 is found, replace it by ‘||’

### Alternatives Considered

Sometimes, some websites need to be blocked which are part of such a hosts file without restricting any other functionalities.

**Comment by VGisHere** [comment]
@AdamWr @Alex-302 @BlazDT @Yuki2718 @lolka4toli @Sergey-Lyapin

**Comment by DandelionSprout** [comment]
To the best of my knowledge, only the Android and (very recent) Windows versions of AdGuard supports hosts files. And even then, they only support it in "DNS mode".

Neither iOS nor web browsers support hosts files, and *none* support them in regular mode, for reasons I simply don't know about.

Your specific problem could probably be re-reported to https://github.com/AdguardTeam/AdguardForiOS/issues, though in my eyes this is an AdGuard-wide problem.

**Comment by VGisHere** [comment]
How about reading it in format that becomes eligible for iOS too?
Like maybe supporting ‘0.0.0.0 ‘ along with ‘||’ OR while interpreting the filters, replace ‘0.0.0.0’ with ‘||’ such that it matches the AdGuard syntax.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #1779](https://github.com/AdguardTeam/AdguardForiOS/issues/1779) via [**ZenHub**](https://www.zenhub.com/)
