### ISSUE TITLE
gitlab.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86314]
***Issue URL (Annoyance)***: https://gitlab.com/users/sign_in

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122653769-944de600-d164-11eb-93de-6f76c401e945.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
@AdguardTeam/filters-maintainers please check
