### ISSUE TITLE
dhooprime.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86313]
***Issue URL ad ***: dhooprime.com

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122653617-61572280-d163-11eb-9bb5-a7dff381aaa6.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors, please add this to user rules:
`dhooprime.com###ads160_600-widget-2`
