### ISSUE TITLE
telegramlinksgroup.xyz

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86317]
**Issue URL (Ads)** :
 https://www.telegramlinksgroup.xyz/

<details><summary>Screenshots:</summary>

0
![image](https://user-images.githubusercontent.com/76880977/122654901-0970e980-d16c-11eb-827d-86e7f72c9126.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4010 visitors/month
