### ISSUE TITLE
UNO ™ & Friends by Gameloft - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8636]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://itunes.apple.com/us/app/uno-friends/id537263603?mt=8

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/34150266-9091d318-e4b0-11e7-839e-e83fe93282df.png)

![image](https://user-images.githubusercontent.com/15856304/34150278-9873435a-e4b0-11e7-9f9d-2289dbf34c84.png)

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.39.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.16.24 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.26.57 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.86 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.3.4 Enabled=NO
[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11.2.1
Browser:                            | n/a
AdGuard version:                    | 1.3.3.118
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | Standard servers, Full tunnel
Helpdesk ID (if exists):            | 1693651

**Comment by Alex-302** [comment]
@AdamWr you can use Fiddler(and add Fiddler's cert to iOS device).

**Comment by AdamWr** [comment]
I don't understand how to reproduce this ad.
I played 3 times and I don't see it, even without AdGuard DNS.

<details><summary>Screenshot</summary>

![scuno](https://user-images.githubusercontent.com/29142494/34220245-3af47438-e5b4-11e7-925a-419a1bbf5331.png)

</details>

**Comment by Alex-302** [comment]
@evgeniy-ADG please ask for details.
