### ISSUE TITLE
akkushop.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#86373]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

Breakage because the cookie banner is blocked but the background is not blocked
`https://www.akkushop.de`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="365" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/122684539-2b1eaf00-d206-11eb-9110-e733180e9e9c.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.6.6
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
Similar breakage: `https://technik-hauptstadt.de/nvidia-grafikkartentreiber-updaten-so-gehts/4385/`

**Comment by THEtomaso** [comment]
@Alex-302:
More affected domains:
```
https://akkushop-b2b.de/
https://batterie-boutique.fr/
https://www.akku-shop.nl/
https://www.akkushop.dk/
https://www.akkushop-austria.at/
https://www.akkushop-schweiz.ch/
https://www.akkushop-turkiye.com.tr
```

**Comment by Alex-302** [comment]
Done.
