### ISSUE TITLE
za.gl

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86403]
***Issue URL (Annoyance)***: **https://za.gl/f64H**

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122719157-7333e500-d28b-11eb-9c2b-61ef4f675874.png)
</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
This timer works server-side so can't be fixed.
