### ISSUE TITLE
vk.com - music player in Edge

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#8640]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: English filter blocks the playback of the music player at https://vk.com

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

* **Expected behaviour**: Music should play with no issues

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows NT 10.0.16299.0
Browser:                               | Microsoft Edge
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English filter
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | off
Helpdesk ID (if exists):               | 1695727, 1256729, 1064887

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by altokarev** [comment]
There are lots of reports at support. Added one more here.

**Comment by evgeniy-ADG** [comment]
1064887:

> ADGUARD из-за него опять начинает виснуть приложение в контакте,в часности музыка. Я уже писал вам,проблема была решена буквально на 2 месяца. Щас опять начинается,музыка виснет и не играет,само приложение тормозит.Почему фильтры не обновляются,и приложение не обновляется?Когда отключаешь ADGUARD все прекрасно работает.МОЙ БРАУЗЕР "EDGE"
