### ISSUE TITLE
overmind.datatheorem.com

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#86441]
```
https://overmind.datatheorem.com/trustkit/report

||datatheorem.com^ ?
```

![Screenshot_20210622-022719_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122810144-97caa400-d301-11eb-9f53-85d7e10bbf44.png)

**Comment by c2xusnpq6** [comment]
> Data Theorem is a leading provider of modern application security. Its core mission is to analyze and secure any modern application anytime, anywhere. The Data ...

**Comment by Sergey-Lyapin** [comment]
Hello, @c2xusnpq6
Where are these domains used? Please specify a link to website or app

**Comment by c2xusnpq6** [comment]
> Hello, @c2xusnpq6
> Where are these domains used? Please specify a link to website or app

tencent game booster: 
https://play.google.com/store/apps/details?id=com.tencent.xriver

**Comment by Sergey-Lyapin** [comment]
It's about security, I'm not sure we should block it.
