### ISSUE TITLE
prebenormen.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86475]
**Issue URL (Ads)** : https://prebenormen.com/progress-success-failure/productivity/keep-book-open

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122897704-dd21bc80-d367-11eb-9c3c-972ae7ef0048.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
Website doesn't have enough monthly visitors to add it to main filters.
You may add` prebenormen.com###custom_html-3` to remove these elements.
