### ISSUE TITLE
VideoDevil Android App (openstreamapps.com) [NSFW] 

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8648]
**App**: VideoDevil

**App Homepage**: www.videodevilapp.com

**Link**: See attached screenshot

**Issue**: Seeing a link in the Filtering log which I believe should be blocked. Can you please check and confirm if this is the case?

**Note**: This is an adult app and is not available on the Play Store.

**Screenshot**: https://ibb.co/e7UR5R

**Setup**:
```
AdGuard for Android v.2.10.176
Android version: 6.0.1 MMB29M
MIUI version: MIUI Global 8.5 | Stable [ 8.5.7.0 (MHOMIED)
Filters: English, Spyware, Social media, Annoyances, Mobile Ads, EasyList China, Anti-Adblock Killer | Reek

Phishing & Malware protection enabled, HTTPS Filtering enabled, High quality filtering enabled & Filtering mode is Local VPN
```

**Comment by Alex-302** [comment]
I don't see ads.
Try to block
```
||app.openstreamapp.com/*/getallads/
```

**Comment by Nzzyme** [comment]
Works, please add to the list. Thank you.

**Comment by Alex-302** [comment]
Added
