### ISSUE TITLE
bypass ooni probe

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#86501]
```
for android:
@@*$app=org.openobservatory.ooniprobe

for pc:
@@*$app=ooniprobe.exe
```

https://ooni.org/
https://ooni.org/install/

**Comment by Alex-302** [comment]
Why we need to unblock everything?

**Comment by c2xusnpq6** [comment]
Because this will affect its judgment

For example, Adguard will reject QUIC, which will make OONI mistakenly believe that the user's area or operator or government restricts users from browsing that website.
