### ISSUE TITLE
turkcell.com.tr

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#8655]
***Description***:

I think this code is tracker?

`https://s.turkcell.com.tr/static_lib/assets/scripts/turkcell/google-analytics/web/google-analytics-web.js?1513484658000`

![image](https://i.hizliresim.com/g9a9MQ.png)
</details><br/>

**Browser**                        | Chrome
**AdGuard version**                      | 2.7.2
**Filters enabled**                       | English - Spyware - Social Media -  Annoyance - Turkish - Fanboys Social Blocking List
**Other Extensions** | Disconnect - HTTPS Everywhere

**Comment by BlazDT** [comment]
As google analytics url is blocked, nothing gets received.

Script also seems to include useful code like this:
```

	$('#productDetailBuyButtonCash').on('click',function(e){
		try {
			if(SHOP.isUserLoggedIn()){
				addToBasket("Turkcell", "Pesin"); // (Loginli - Pesin) sepete ekleme
			}
		} catch (e) {
			googleAnalyticLog(e, true);
		}
	});
	
	$('#shop_sign_in #none-login-sale-button').on('click', function(e){
		try {
			addToBasket("Non-Turkcell", "Pesin"); // (Loginsiz - Pesin) sepete ekleme
		} catch (e) {
			googleAnalyticLog(e, true);
		}
	});
	
	$('#shop_sign_in #lightboxActionButton').on('click', function(e) {
		try {
			var $form = $(".sign_in_form:visible");
			if (isFormValid($form) && $(this).data('requestState') === "cash-buy") {
				addToBasket("Turkcell", "Pesin"); // (Login Popup ---> Login - Pesin) sepete ekleme
			}
		} catch (e) {
			googleAnalyticLog(e, true);
		}
	})
```
So blocking it may result in broken page.
