### ISSUE TITLE
[badfilter] ||invoca.net^$third-party

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#86553]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: T-Mobile log in issues

* **Current behaviour**:  With this rule in place it's literally not possible to log-in in `https://www.t-mobile.com` 

* **Expected behaviour**: Be able to log in,pay my bill,have working phone 😅 

***System configuration***

**Filters:** The rule is in **AdGuard Tracking Protection Filter**

[//]: # (Please enter the correct values for your case to the table below)

Browser:    **Slimjet Version 30.0.5.0 (based on Chromium 88.0.4324.150) (Official Build) (64-bit)** 
AdGuard version:  **7.6.1(latest:stable)**

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not seeing it requested on login page, only on main page:

`https://account.t-mobile.com/signin/v2/?redirect_uri=https:%2F%2Fwww.t-mobile.com%2Fsignin&scope=TMO_ID_profile%2520associated_lines%2520billing_information%2520associated_billing_accounts%2520extended_lines%2520token%2520openid%2520vault&client_id=MYTMO&access_type=ONLINE&response_type=code&approval_prompt=auto&prompt=select_account&state=eyJpbnRlbnQiOiJMb2dpbiIsImJvb2ttYXJrVXJsIjoiaHR0cHM6Ly93d3cudC1tb2JpbGUuY29tL2FjY291bnQvZGFzaGJvYXJkIn0%3D`

Is this rule working?
`@@||pnapi.invoca.net/*/na.jsonp$domain=t-mobile.com`

**Comment by dnmTX** [comment]
@BlazDT  today is even worst apparently 🤔 . I was able to log in yesterday by whitelisting the whole `invoca.net` domain,which didn't help much when testing today. I tried so many variations,you can't even imagine. The end result was allways this:
![T-Mobile](https://user-images.githubusercontent.com/34774426/123145822-d906a500-d422-11eb-94c9-a303ddffcc02.png)

So this what made it work. I had to whitelist completely `account.t-mobile.com` + `invocacdn.com` + `invoca.net`.
Otherwise...no joy. Even whitelisting only  `invocacdn.com` + `invoca.net` couldn't get me trough.
And to brake it down. Domains that are needed:
`https://solutions.invocacdn.com/js/pnapi_integration-latest.min.js`
`https://solutions.invocacdn.com/js/networks/1639/1045158119/tag-live.js`
`https://pnapi.invoca.net/1639/na.jsonp?network_id=1639&js_version=4.21.5&tag_id=1639…`
`https://pnapi.invoca.net/7/api/2014-09-01/map_number.jsonp?....`
+
`@@||account.t-mobile.com^`  ( tried whitelisting $stealth only,didn't help)
For now this is what i got on my end,let me know how you planning to do it on yours:
 `@@/(invocacdn.com|invoca.net|account.t-mobile.com)/$domain=t-mobile.com`

**Comment by BlazDT** [comment]
Can you reproduce when you enter wrong login data too?

**Comment by dnmTX** [comment]
> Can you reproduce when you enter wrong login data too?

I remember entering at one point wrong password and it was just let me stay on the same screen.
So,now you want me to enter completely wrong credentials? 
What's the point,at the end of the day i have to be able to log in,don't you think?

**Comment by BlazDT** [comment]
It was about to be able to reproduce without having a contract with them.

**Comment by dnmTX** [comment]
I guess,tracking or not,those domains are needed in order users to be able to log in.
Still wondering about why i had to whitelist `account.t-mobile.com`.

**Comment by BlazDT** [comment]
@AdguardTeam/filters-maintainers 
Anyone of you having an account?

**Comment by Alex-302** [comment]
I don't have. This is US operator.

**Comment by dnmTX** [comment]
> This is US operator

It is. Broader help is needed here. Beyond Russian borders 😄

**Comment by Alex-302** [comment]
If you want, I can check remotely)

**Comment by dnmTX** [comment]
> If you want, I can check remotely

@Alex-302 if you asking for access to my PC,sorry but i can't do that.
I'm actually all set on my end with the rule that i posted earlier so no rush here. 
You guys either abandon that issue for now and wait for more complaints(which i assume will come sooner or later) or find somebody knowledgeable with account on US side i guess but access i can not give.

**Comment by Alex-302** [comment]
Ok. Please test this rule without previous or your own:
`@@||account.t-mobile.com^$genericblock`

**Comment by dnmTX** [comment]
> Ok. Please test this rule without previous or your own:
@@||account.t-mobile.com^$genericblock

Confirming the rule is working. I was able to log in without a hassle. Good job @Alex-302 👍 
<details><summary>Screenshot:</summary>
![Capture1](https://user-images.githubusercontent.com/34774426/123171026-dd41bb00-d440-11eb-8776-35a8a7efeaf2.PNG)
![Capture2](https://user-images.githubusercontent.com/34774426/123171057-e894e680-d440-11eb-90e1-164cded7b2e6.PNG)
</details><br/>

**Comment by Alex-302** [comment]
Thanks for testing. We can add it to filter.
Could you please show screenshot of the log without the rule and with these log options? Just want to see what we unblock.
![image](https://user-images.githubusercontent.com/8361299/123173009-9f678580-d486-11eb-858c-d7930c7394cf.png)

**Comment by dnmTX** [comment]
Here you go @Alex-302,exactly like you asked:
<details><summary>Screenshot: 👇 </summary>

![image](https://user-images.githubusercontent.com/34774426/123174301-838fbf80-d445-11eb-8155-20b132e2c2c7.PNG)
![image](https://user-images.githubusercontent.com/34774426/123174316-88547380-d445-11eb-94e2-e43c27fb632b.PNG)
</details><br/>

When are you planning to add the rule(so i can remove the duplicate on my end),also i have to go so i'll let you guys close this
whenever appropriate 👍

**Comment by dnmTX** [comment]
Shoot,i messed up,you asked not to apply the rule,stand by......

**Comment by dnmTX** [comment]
@Alex-302 and @BlazDT never mind on the whole thing here.Don't add any rules please. The problem was that i have extension to block WebWorkers,and even that i new it creates problems on that website i had to turn it off,restart the browser and then it wasn't interfering. What i was doing earlier was restart the browser and then turn it off,which was still making problems apparently.
Sorry,i feel kind of embarrassed to make you look for a problems where there are none. That extension i guess is very aggressive so i'll make sure to turn it off before the browser is restarted.
Or i might be mistaking(small possibility),but i tested it twice and was able to log in. I'll keep the rule(disabled) on my end for a while just in case and if anything will reassess.
Thanks again for not giving up to find solution,even though it wasn't needed 👍 
Cheers.....Closing.....

**Comment by Alex-302** [comment]
Great)
