### ISSUE TITLE
data-flair.training

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86564]
**Issue URL (Ads)** : https://data-flair.training/blogs/structures-in-c/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123049311-09e3db80-d41d-11eb-87bf-c5c21ec51fea.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
Also no reproduced with AG turned off.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/125068869-a4e7e100-e0be-11eb-8be5-78f1cd8a7190.png)
</details><br/>

**Comment by chirag127** [comment]
@stanislav-atr  I can still reproduce it .
