### ISSUE TITLE
beginnersbook.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86565]
**Issue URL (Ads)** : https://beginnersbook.com/2014/01/c-structures-examples/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123049620-60511a00-d41d-11eb-9a9c-acf99e626835.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
Not reproduced with AG turned off:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/125068253-f5ab0a00-e0bd-11eb-902e-797e90be9738.png)
</details><br/>
@chirag127 is the issue still relevant for you?

**Comment by chirag127** [comment]
No, same here.

I have seen many companies which claims that they notify the website owner whenever the ads on their site get reported on AdGuard or easylist.
Do you think it is possible?
