### ISSUE TITLE
tutorialspoint.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86577]
**Issue URL (Ads)** : https://www.tutorialspoint.com/cprogramming/c_break_statement.htm

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123054151-364e2680-d422-11eb-880c-f1aed464d25e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
Not an ad leftover.
