### ISSUE TITLE
gkplanet.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86570]
***Issue URL (Annoyance)***: http://answers.gkplanet.in/2018/03/default-parameter-passing-mechanism-is.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123050435-554ab980-d41e-11eb-855e-35904e49c80a.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
Website doesn't have enough monthly visitors to add it to main filters.
`gkplanet.in###bizzbar` for userfilter.
