### ISSUE TITLE
golang.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86580]
***Issue URL (Annoyance)***: https://golang.org/doc/faq

> unpaid promotion

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123056226-4ebf4080-d424-11eb-81ad-978cdba0e88d.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
You may use `golang.org##.Header > div.Header-banner` in your userfilter for this element.
