### ISSUE TITLE
lawrato.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86586]
***Issue URL (Annoyance)***:
https://lawrato.com/family-legal-advice/can-a-20-year-old-boy-get-married-according-to-hindu-law-in-india-41844

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123065027-68648600-d42c-11eb-97bd-41b3dbab7afe.png)
![image](https://user-images.githubusercontent.com/76880977/123065030-68fd1c80-d42c-11eb-8cfb-81c11aedefe1.png)
![image](https://user-images.githubusercontent.com/76880977/123065031-6995b300-d42c-11eb-97ea-dcd4ad92478b.png)
![image](https://user-images.githubusercontent.com/76880977/123065033-6a2e4980-d42c-11eb-92a2-54e4b7c1c921.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by stanislav-atr** [comment]
I've removed popup. We dont remove first-party chat widgets and blue banners lead to the same domain.

**Comment by chirag127** [comment]
What about" Need help? I won't keep you waiting "Popup?
