### ISSUE TITLE
huffpost.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86595]
***Issue URL (Annoyance)***: https://www.huffpost.com/archive/in/entry/india-is-the-25th-best-country-in-the-world-and-its-attitude_a_21874552

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123068881-ec6c3d00-d42f-11eb-9e17-9a7842b9c26e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
for user rules: `huffpost.com##.archive-notice`
