### ISSUE TITLE
Link1s (turn off adblocker)

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#86600]
Anyway this can be fixed?
https://link1s.com/xtOEkz

After u go to the link and timer goes to zero
U click "click here to continue" 
Then it will bring up a google search
Select the first link
Then it go captcha screen
After finishing website says
Please disable Adblock to proceed to the destination page.
![Screenshot_20210618-182233_Vivaldi](https://user-images.githubusercontent.com/46019727/123084710-462a3280-d443-11eb-94ad-79207f0e6b43.jpg)

**Comment by BlazDT** [comment]
Fixed, update available in about 3 hours.

**Comment by Bhooty** [comment]
Atlast thanks for fixing it
Last time i reported i forgot to add the steps :3
