### ISSUE TITLE
xccelerate.co

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86610]
***Issue URL (Annoyance)***: https://xccelerate.co/en/blog/python-vs-javascript/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123088983-031c8f00-d444-11eb-910b-1135c89cf438.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
too few visitors, for user rules:
`xccelerate.co#$#.MuiDialog-root { display: none!importnat;} `
`xccelerate.co#$#.body { overflow: visible!important;} `
