### ISSUE TITLE
freevirtualsmsnumber.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8662]
**Site**: https://freevirtualsmsnumber.com/from-sender/SMSC.RU@?page=5

**Issue**: Seeing adblock message on the page

**Screenshot**: https://image.ibb.co/mt7jc6/Capture.jpg

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Fixed.
