### ISSUE TITLE
Spotify links can't be opened on iOS

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardFilters#86639]
**Issue**:
AdGuard incorrectly blocks Spotify links from opening on iOS (14.6).
**Steps to recreate**:
1. make sure to have NOT installed the Spotify app on your iPhone.
2. try to open a Spotify link on your iPhone, f.e. https://open.spotify.com/playlist/7vTUX5URUS4ntuIroEXtAv
**Behavior**: 
the website got blocked by AdGuard
**Expected Behavior**:
Safari should open the website
**Filters**:
basic filter; tracking protection; social media; annoyances (this may cause the issue); German

**Comment by Alex-302** [comment]
I don't have Spotify app, and I can't reproduce with your settings(also with AdGuard DNS).
I need screenshot.

**Comment by iDjay** [comment]
Weird, I had this issue since months however it’s gone now. Why does this always happen when I report something 😂

**Comment by iDjay** [comment]
The issue is back @Alex-302 
![69D54C06-7931-4D71-9BE8-CF778B950A8F](https://user-images.githubusercontent.com/83946731/124801662-608e0100-df57-11eb-84a3-e789d407a5c9.png)

**Comment by Alex-302** [comment]
Need sample link.

**Comment by iDjay** [comment]
Just any link leading to Spotify.
https://open.spotify.com/playlist/6S4pdwnUd2LcOyQvKJv3AA?si=bula4dhQSNSnXp2gCFP9cQ&nd=1

**Comment by Alex-302** [comment]
Works fine on my end with DNS.
@AdguardTeam/filters-maintainers please take a look.

**Comment by iDjay** [comment]
Yes for some reason it‘s working fine now again, but it didn‘t work for months until I decided to turn off AdGuard to open the page once. That did the trick.
Also it seems like that only shared Spotify links have this issue, f.e. If someone sends you the link in iMessage. Normally iOS would redirect to the AppStore/ launch Spotify to open the link within the app.

**Comment by iDjay** [comment]
That’s the exact url which redirects to the Spotify app:
https://app.adjust.net.in/abuwqb?tracker_limit=250000&deep_link=spotify%3A%2F%2Fplaylist%2F6xGLprv9fmlMgeAMpW0x51%3Fsi%3Dy_YdGXqvQvWQa9AF0bvStg&redirect=http%3A%2F%2Fopen.spotify.com%2Fplaylist%2F6xGLprv9fmlMgeAMpW0x51%3Fsi%3Dy_YdGXqvQvWQa9AF0bvStg%26nd%3D1&label=sp_cid%3A1a193ca74f9e53dbd733faa234cba5e1

**Comment by Alex-302** [comment]
Which filter blocks it(disable one by one with checking)?

**Comment by iDjay** [comment]
@Alex-302 AdGuard Privacy Protection

**Comment by Alex-302** [comment]
@iDjay Please test
`@@||app.adjust.net.in/*&redirect=redirect=http%3A%2F%2Fopen.spotify.com%2Fplaylist`

**Comment by iDjay** [comment]
Doesn‘t seem to work with the link above.

**Comment by Alex-302** [comment]
try
`@@||app.adjust.net.in/*&redirect=redirect=*open.spotify.com`

**Comment by iDjay** [comment]
Nope :D

**Comment by chirag127** [comment]
> The issue is back @Alex-302
> ![69D54C06-7931-4D71-9BE8-CF778B950A8F](https://user-images.githubusercontent.com/83946731/124801662-608e0100-df57-11eb-84a3-e789d407a5c9.png)

what is written in the photo?

**Comment by iDjay** [comment]
Safari can't open the webpage.
Error: Page is blocked by an AdBlocker.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/SafariConverterLib #25](https://github.com/AdguardTeam/SafariConverterLib/issues/25) via [**ZenHub**](https://www.zenhub.com/)
