### ISSUE TITLE
uptobox.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86647]
***Issue URL (Annoyance)***: https://uptobox.com/16cof94nspyn

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123129546-a764fc80-d469-11eb-90e3-1297c5494208.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
They control timeout.
