### ISSUE TITLE
220-volt.ru

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#86676]
Как таковой рекамы на сайте сверх обычного не было, но вот при разовом посещении ссылки с данного ресурса  (никогда там не бывал) на яндекс-ящик прилетела спам-рассылка с купонами от podarok@flocktory.com для 220-volt.ru. Подозреваю, что сайт проводил какие-то манипуляции с куками от того же я-маркета (например) и на основе этих данных было сгенерировано спам-письмо.

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 5.1
Browser:                               | Chrome 71.0.3578.99
AdGuard version:                       | 3.6.2
Filters enabled:                       | ?
AdGuard mode (Android only):           |  Proxy (manual)
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

**Comment by Alex-302** [comment]
Скорее всего когда-то регистрировались там, или кто-то базу емейлов продал.

**Comment by Baltazar500** [comment]
>Скорее всего когда-то регистрировались там, или кто-то базу емейлов продал.
Никогда там не бывал и не регистрировался. Даже если они купили базу, это не отменяет махинаций. По ссылке присланной в телеграм (от родственника) в 19.35 я перешёл через пару - тройку минут, в 19.48 мне прилетел мейл от этого сайта именно на яндекс - ящик. В самом низу главной страницы сайта висит предложение оценить сайт на я-маркете, так что они как-то связаны с этим делом. В общем присмотритесь к этому сайту и их скриптам более пристально ...
