### ISSUE TITLE
blick.ch

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86704]
**Issue URL (Ads)** : https://www.blick.ch/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123257821-46443400-d510-11eb-83f2-7f94971d47d5.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by BlazDT** [comment]
Please enable German filter and update.
