### ISSUE TITLE
music.yandex.ru

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/AdguardFilters#8672]
# Issue URL
https://music.yandex.ru/home
# Comment

# Screenshots
<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/20907093/34198248-b8f0c9b6-e57a-11e7-860d-98687cc8b7c9.png)</details>

# System configuration
Information|value
---|---
Platform:|Win10
AdGuard version:|6.2.437.2171
Browser:|Mozilla Firefox 57.0.2
AdGuard driver:|WFP
Stealth mode options:|Отправлять заголовок Do-Not-Track, Убрать заголовок X-Client-Data из HTTP-запросов, Очистить URL от параметров отслеживания, Блокировать заголовок Authorization, Отключить кэш-память для сторонних запросов, Блокировать WebRTC, Блокировать Push API, Блокировать Location API, Блокировать Flash, Блокировать Java, Скрыть IP адрес(43.236.224.0)
Filters:|English,<br>Spyware,<br>Social media,<br>Annoyances,<br>Russian,<br>Experimental

**Comment by Alex-302** [comment]
Репорты отправляй. Развешивание меток время отнимает.
