### ISSUE TITLE
Block ads for x8speeder

### ISSUE THREAD

**Issue by anastenko** [AdguardTeam/AdguardFilters#86771]
@kotoricon commented on [Mon Jun 21 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3882)

Offical website: https://x8speeder.com/

This app now always force show ads if you want use their apps, or it will show 'please view the completed ads or it dont work'.
Preview version like 3.2.x or older dont have the function like this and Adguard ever work for it, but dont work for new version now.

---

@anastenko commented on [Fri Jun 25 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3882#issuecomment-868401266)

@kotoricon Hello.

Please send a feedback via AdGuard application:
- Open AdGuard settings;
- Support --> Send Feedback --> Missed ad or tracker/Incorrect blocking.

After you've filled in the form, an issue will be created in the right repository on GitHub. There will also be a link to monitor progress towards the solution of your problem.

Please make sure you add all necessary information on that feedback.

**Comment by Alex-302** [comment]
Looks loke adware. It loads tonns of ads and sent analytics.
