### ISSUE TITLE
urlvoid.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86785]
**Issue URL (ADS)**: https://www.urlvoid.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123431129-8c6bc700-d5e6-11eb-98b8-69d9966d71c7.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by BlazDT** [comment]
Fixed self-promo (website owned by same company).

**Comment by chirag127** [comment]
Hmm... Took me to a different website so thought it's an advertisement .
