### ISSUE TITLE
plannedparenthood.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86813]
**Issue URL (Annoyance)**: https://www.plannedparenthood.org/learn/teens/ask-experts/what-are-the-chances-of-getting-pregnant-with-a-condom

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123466864-79b8b880-d60d-11eb-880f-c0667d56ada4.png)
![image](https://user-images.githubusercontent.com/76880977/123466868-7b827c00-d60d-11eb-932f-896690a7ee82.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by BlazDT** [comment]
Not shown.
