### ISSUE TITLE
akgec.ac.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86822]
**Issue URL (Annoyance)**: https://www.akgec.ac.in/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123475178-a9b98900-d618-11eb-9781-ca5dc6acfce8.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by BlazDT** [comment]
Getting redirected to akgec.ac.in - fixed there. Please reply if you still get the initial page.

**Comment by chirag127** [comment]
You mean redirected to akgec.ac.in instead of www.akgec.ac.in

<details><summary>Screenshots:</summary>


![image](https://user-images.githubusercontent.com/76880977/124314680-66b76280-db90-11eb-9d1a-3916918abf0b.png)


</details><br/>

**Comment by BlazDT** [comment]
An extension of mine did remove the .in, therefore it looked strange. Update available in about 3 hours.
