### ISSUE TITLE
vumoo.to

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#86859]
https://vumoo.to/movies/an-unquiet-grave-2021

Unable to play video when AG extension for Chrome is enabled with basic AG filters. I am able to see the play button and the video plays when AG is disabled.

**Comment by Alex-302** [comment]
Not reproduced. What breaks the site?

**Comment by AdamWr** [comment]
I can reproduce it only with Stealth mode enabled (caused by `Hide your Referrer from third-parties` option).
Added rule which should fix it, update will be available in 1-2 hours.
