### ISSUE TITLE
purposefulfaith.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86888]
**Issue URL (Ads)** : https://purposefulfaith.com/gods-people-want-to-die/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123519020-79302880-d6c6-11eb-952c-29c24433fabd.png)
![image](https://user-images.githubusercontent.com/76880977/123519022-79c8bf00-d6c6-11eb-9771-77c4c7a1ee20.png)
![image](https://user-images.githubusercontent.com/76880977/123519021-79302880-d6c6-11eb-8626-a0b7a4ca3af7.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
Not enough visitors.
Please add these rules to user filter:
```
purposefulfaith.com###text-8
purposefulfaith.com###text-13
purposefulfaith.com###text-15
```
