### ISSUE TITLE
google.co.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#86883]
**Issue URL (Annoyance)**: https://books.google.co.in/books?id=hk-TBAAAQBAJ&pg=PA137&lpg=PA137&dq=god,+please+take+me+away+from+this+world&source=bl&ots=34vW7OXCef&sig=ACfU3U0tDbqb0vrUdiqLAAThjmUQ70C5Zw&hl=en&sa=X&ved=2ahUKEwiI5KLf1LXxAhXadCsKHXvKAUoQ6AEwIXoECC4QAw#v=onepage&q=god%2C%20please%20take%20me%20away%20from%20this%20world&f=false

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123518859-800a6b80-d6c5-11eb-9f10-572569e55c7c.png)
![image](https://user-images.githubusercontent.com/76880977/123518860-80a30200-d6c5-11eb-9659-474ebeab093d.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
I'm not sure if informations about new layout should be blocked, but in this case there is also a similar button on the top, so I added rule to block it.
