### ISSUE TITLE
smskola.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8688]
**Site**: https://smskola.com/

**Issue**: Seeing adblock message on the page

**Screenshot**: https://image.ibb.co/cVauc6/Capture.jpg

**OS**:
> `Windows 8.1 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains, Fanboy's Enhanced Tracking List, Peter Lowe's list 

[No user filter used | Phishing & Malware Protection Enabled]

**Comment by AdamWr** [comment]
Fixed.
