### ISSUE TITLE
Not blocking ads in KIJK and RTLXL apps on Samsung TV

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8689]
I have a Samsung smart TV with YouTube and some dutch video apps like RTLXL, NPO and KIJKgemist. How can I block video ads using ADGuard? I try to use the DNS server 176.103.130.130 but this is not working.

On a regular Android device, you can install those apps. But my Samsung Smart TV does not run Android. The apps KIJK and RTLXL are builtin the Smart TV. This is my TV: http://www.samsung.com/uk/tvs/suhd-ks7000/UE49KS7000UXXU/

ID: 1685232

**Comment by Alex-302** [comment]
I can't access to Internet with custom DNS on my TV.

**Comment by evgeniy-ADG** [comment]
RTL XL
https://apkpure.com/rtl-xl/com.tapptic.rtl5.rtlxl <https://apkpure.com/rtl-xl/com.tapptic.rtl5.rtlxl>

KIJK
https://apkpure.com/kijk/nl.sbs.kijk <https://apkpure.com/kijk/nl.sbs.kijk>

NPO
https://apkpure.com/npo/nl.uitzendinggemist <https://apkpure.com/npo/nl.uitzendinggemist>


These are apps in question. Andrey asked me to file the task.

**Comment by Alex-302** [comment]
Can't download 2 and 3 If you can, re-upload them, please.

**Comment by evgeniy-ADG** [comment]
I can download 2 and 3, here you go https://www.dropbox.com/s/5j946ve9kqookk8/Archive.zip?dl=0

**Comment by Alex-302** [comment]
nl.sbs.kijk is clean on my device. 
nl.uitzendinggemist - video is not vorking.
