### ISSUE TITLE
www.lupa.cz - Incorrect blocking

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8693]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
https://www.lupa.cz/

It shows only blank page

[//]: # (Substitute this line with a description of the problem)

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.63 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.47 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.94 Enabled=YES
ID=101 Name="EasyList" Version=1.0.76.70 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.89.66 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.78.79 Enabled=YES
ID=105 Name="EasyList Czech and Slovak" Version=1.0.2.68 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.5.56 Enabled=YES
ID=201 Name="Czech List" Version=1.0.0.3 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.2.1
Operating system version (Android/iOS) | iOS
AdGuard version:                       | 1.3.3.89
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1699673

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Issue lies in EasyList Czech and Slovak.

Reported:
https://github.com/tomasko126/easylistczechandslovak/issues/125
