### ISSUE TITLE
Feature request  - app management

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#8697]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Not a bug, just a feature request. Would like to be able to sort the apps
by if adguard is enabled or disabled on that app. Would be nice if all
disabled apps show up at the beginning of the app list. Similar to how
Android lets you sort apps by enabled or disabled status.

Information                            | Value
---                                    | ---
Operating system version (Android/iOS) | Android
Helpdesk ID (if exists):               | 1699129

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not a filter issue.

Please post over at https://github.com/AdguardTeam/AdguardForAndroid/issues - thank you.
