### ISSUE TITLE
http://seosprint.net/ is blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8698]
with the standard dns:

![image](https://user-images.githubusercontent.com/15856304/34246346-eb4f401a-e636-11e7-989d-bd0d673a83c6.png)

without:

![image](https://user-images.githubusercontent.com/15856304/34246402-1b2a734a-e637-11e7-8f09-1886003c3d7a.png)

**Comment by Alex-302** [comment]
fixed
