### ISSUE TITLE
[Android] CM's Weather Info ad

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#870]
Similar to #755, #782, & #869, [CleanMaster](http://play.google.com/store/apps/details?id=com.cleanmaster.mguard)'s Weather Info feature also has an advertisement that isn't currently blocked.  This ad usually only comes up a few seconds after the Weather Info screen is activated.

**Comment by TPS** [comment]
@Alex-302 There may be a different cause for this, but I did file ticket# OXG-496-68436.

**Comment by Alex-302** [comment]
I don't see ads, the app is clean.

**Comment by TPS** [comment]
I see a banner between sections "Today & Tomorrow" & "Daily Forecast," but it's not all the time.  Sometimes, 1 needs to wait several seconds or open several times.

**Comment by Alex-302** [comment]
Tried with US VPN - nothing:)

**Comment by Alex-302** [comment]
If you can install Fidder, I can connect to you via TeamViewer and try to block this ad,
