### ISSUE TITLE
Paytm [Android App] (register.appsflyer.com)

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8701]
**App**: Paytm

**App Homepage**: https://play.google.com/store/apps/details?id=net.one97.paytm&hl=en

**Link/URL**: See attached screenshot

**Issue**: Seeing a link in the Filtering log which I believe should be blocked. Can you please check and confirm if this is the case? A similar link is included in the Mobile Ads filter (stats.appsflyer.com) but not sure if this one also needs to be blocked.

**Screenshot**: https://i.screenshot.net/nrzdvfd

**Setup**:

> AdGuard for Android v.2.10.176
> Android version: 6.0.1 MMB29M
> MIUI version: MIUI Global 8.5 | Stable [ 8.5.7.0 (MHOMIED)
> Filters: English, Spyware, Social media, Annoyances, Mobile Ads, EasyList China, Anti-Adblock Killer | Reek
> 
> Phishing & Malware protection enabled, HTTPS Filtering enabled, High quality filtering enabled & Filtering mode is Local VPN

**Comment by Alex-302** [comment]
Hi
Screenshot is wrong. Could you copy that URL as test or record web-requests log?

**Comment by Nzzyme** [comment]
Sorry, try this: https://i.screenshot.net/s/nrzdvfd

**Comment by Alex-302** [comment]
> Could you copy that URL as test or record web-requests log?

**Comment by Nzzyme** [comment]
URL is:

`https://register.appsflyer.com/api/v4/androidevent?buildnumber=4.7.1&app_id=net.one97.paytm`

**Comment by Alex-302** [comment]
it is not tracking url
