### ISSUE TITLE
Adguard block access to legitimate site (http://ads.springer.de) [ads is for Astrophysics Data System]

### ISSUE THREAD

**Issue by quark67** [AdguardTeam/AdguardFilters#87057]
In the URL http://ads.springer.de, "ads" is not for "advertising", but for "Astrophysics Data System".

I cannot access to this page, the error message is (approximately, because I translate from French): Safari cannot open the page "http://ads.springer.de". Error: "the URL was blocked by a content blocker".

Perhaps can you allow this URL?

I have previously reported a very similar bug : https://github.com/AdguardTeam/AdguardFilters/issues/80976 (also "ads" in astrophysical related site).

So I think the solution is to search all astrophysics related sites with "ads" in it's URL and adding it in a "allow list" in AdGuard. Good luck! A good start is with this search words: "ads astrophysics data system".

**Comment by Alex-302** [comment]
Fixed.
