### ISSUE TITLE
Entries in AdGuard Base that uBlock Origin's logger thinks are miswritten

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#87137]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Entries in AdGuard Base that uBO's logger claims have been miswritten:
* `/expla*.js^$important,domain=rarbgto.org.` - uBO doesn't seem to like the dot at the end, despite it being a part of some URLs.
* `sysnettechsolutions.com##[style*="cursor:"][style*="z-index:"][style*="transform"]s` - Is the "s" at the end supposed to be there?
* `$webrtc,domain=dualpaste.net|hdmovieswatchs.net|bitporno.com|zippyshare.com` - Would've had to be converted to `dualpaste.net,hdmovieswatchsnet,bitporno.com,zippyshare.com##+js(nowebrtc)` in the uBO list versions.
* `||jsc.marketgid.com/*.js?t=$redirect=noop.txt,important,~websocket,image,media,subdocument,stylesheet,script,xmlhttprequest,other` - uBO doesn't seem able to combine `$redirect` with `$~websocket` for unclear reasons.

Entry values that are unsupported in uBO, and which can be removed from the uBO versions of AdGuard's lists to reduce the filesizes:
* `$jsinject`
* `$content`
* `#@%#`
* `:matches-property`
* `@@$webrtc`
* `$urlblock`

Additionally, `pcgames.de#$#.stickyHeader+#loginFormMobileWrapper+.navigation+main { margin-top: 5,5rem !important; }` in AdGuard Mobile Filter should most likely use `5.5rem` instead of `5,5rem`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/123889182-3f288600-d955-11eb-8d55-ebb2fe28b208.png)
</details><br/>

* **Expected behaviour**: 

The entries in question have their syntax corrected, or are discarded during the uBO portion of https://github.com/AdguardTeam/FiltersCompiler

***Steps to reproduce the problem***:

1) Turn on uBO.
2) Open an incognito session in Chrome.
3) Open up uBO's logger, and keep its domain set to "All".
4) With the logger still open, go to chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#3p-filters.html
5) Choose to sync AdGuard Base and AdGuard Mobile Ads, and only those two filters.
6) If this was done correctly, the logger will show around ninety "Invalid [network/extended] filter in (…)" errors about specific entries in those two lists.

***System configuration***

**Filters:**

N/A

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 21H1 x64
Browser:                               | Chrome 91.0.4472.124 x64
AdGuard version:                       | uBO 1.36.1b1
Filters enabled:                       | N/A
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> * `sysnettechsolutions.com##[style*="cursor:"][style*="z-index:"][style*="transform"]s` - Is the "s" at the end supposed to be there?

No. Fixed.

> * `||jsc.marketgid.com/*.js?t=$redirect=noop.txt,important,~websocket,image,media,subdocument,stylesheet,script,xmlhttprequest,other` - uBO doesn't seem able to combine `$redirect` with `$~websocket` for unclear reasons.

Maybe Easylist has own rule with the same purpose. This rule not fresh, not sure if it causes any issue.

> * `$webrtc,domain=dualpaste.net|hdmovieswatchs.net|bitporno.com|zippyshare.com` - Would've had to be converted to `dualpaste.net,hdmovieswatchsnet,bitporno.com,zippyshare.com##+js(nowebrtc)` in the uBO list versions.

@slavaleleka Is it necessary or correct? Also please take a look on modifiers list.

**Comment by slavaleleka** [comment]
conversion of rule with `$webrtc` modifier can not be handled by adding an alias to Scriptlets. if it is really necessary, Compiler should do that
