### ISSUE TITLE
missed ad in Magic Phone Cleaner 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#8715]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: missed ad in Magic Phone Cleaner - https://itunes.apple.com/ru/app/magic-phone-cleaner/id1176756975?mt=8

<details>

![image](https://user-images.githubusercontent.com/23372054/34266010-73b1da0a-e680-11e7-830b-7fef65fc89cf.png)

</details>

Application version: 1.3.3.118
Device: iPhone
OS: 11.2.1
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.40.31 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.16.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.26.93 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.23.12 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.61.60 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.77 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.11.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.94 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.3.12 Enabled=NO

PRO:
Pro feature ENABLED.
Tunnel mode SPLIT
DNS server: Свой
176.103.130.130
176.103.130.13

Customer ID 1138152

**Comment by Alex-302** [comment]
I can't reproduce with AdGuard DNS, `googleads.g.doubleclick.net` is blocked.
Try to enable and disable airplane mode to flush DNS cache.
