### ISSUE TITLE
no Assistant on mail.ru

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#8716]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: there is no AdGuard Assistant on this page https://my.mail.ru/apps/711108?ref=lmnu
Ads are not removed. Video attached
[converted_file_d7b66389.zip](https://github.com/AdguardTeam/AdguardFilters/files/1580240/converted_file_d7b66389.zip)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Browser:                               | Mozilla, Chrome
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian, Dutch
Stealth mode options     | enabled

Customer ID 626782

**Comment by Alex-302** [comment]
Maybe HTTPS issue.
