### ISSUE TITLE
rare.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87171]
***Issue URL (Incorrect Blocking)***: https://www.rare.co.uk/?q=news

> broken header 

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/123959602-feb81f00-d9cb-11eb-83ad-bf29fcadcec8.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
It looks the same without AdGuard.
