### ISSUE TITLE
chrome.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87209]
**Issue URL (Annoyance)**: https://developer.chrome.com/docs/devtools/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124037790-baee0580-da1d-11eb-96be-7bef63c69808.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by krystian3w** [comment]
Maybe protected domain, works manually block elements?

**Comment by chirag127** [comment]
> works manually block elements?

Yes it works
