### ISSUE TITLE
snowfl.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87264]
**Issue URL (Ads)** :
https://snowfl.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124146922-dbfd3780-daab-11eb-8d97-ec6d66dcf14d.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by DandelionSprout** [comment]
I propose `snowfl.com##.aunit`
