### ISSUE TITLE
getrelax.club - Anti Adblock Script & add the adult website in the filter of AdGuard Family DNS

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#8727]
Issue URL: getrelax.club — Anti Adblock
Issue Type: Anti Adblock Script
Comment:
A net friend reported to me.
After enabling AdGuard, the website doesn't allow to read the content in any articles.
There is a annoying pop-up on the website.
And it shows Anti-Adblock message on the web page after entering any articles.

Screenshot:

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cSe1hr5.jpg)
</details><br/>

***Steps to reproduce the problem***:
Enable AdGuard English filter and try to read any content on getrelax.club.

Solution:
1. The data of Anti-Adblock Killer | Reek is too old.
It seems that the developer of Anti-Adblock Killer Continued (AAK-Cont) didn't allow AdGuard to use its filter and ever argued with AdGuard team on the forum, right?
I'm curious how to hide the annoying pop-up on the website.
I found the solution in Anti-Adblock Killer Continued (AAK-Cont) filter.
https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-notubo.txt

Please add the 2 rules in English filter.
getrelax.club##.loaded-popup-wrapper
@@||getrelax.club^$generichide (or @@||getrelax.club^$elemhide)

2. This is an adult website.
However, AdGuard Family DNS server doesn't block the adult website.
Please add getrelax.club in your filter of AdGuard Family DNS server.

Thanks a lot!

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Adguard driver: | WFP
Browser:                               | Google Chrome v63.0.3239.108
AdGuard version:                       | AdGuard for Windows v6.2.437.2171
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
Stealth mode options (Windows only)    | Enable Stealth mode, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies, Disable cache for third-party requests, Block WebRTC, Block Location API
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Fixed adblock detection and popup.
AdGuard DNS will be done by someone else.

**Comment by lancelot-moon** [comment]
Hi,

I'm learning rule syntax from the solutions by AdGuard team.
Making clever rules is my goal.
You use "getrelax.club#@#.google-ad" for anti-adblock.
Is there difference between @@||getrelax.club^$generichide, @@||getrelax.club^$elemhide and getrelax.club#@#.google-ad?

Thanks.

**Comment by BlazDT** [comment]
The rule #@# will exclude only the rule part after it, in this case .google-ad
generichide will disable all generic rules for the site.
elemhide will hide complete elem hiding rules on the site.

**Comment by lancelot-moon** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/7596#issuecomment-351387478

How could I know what I should fill in after the rule #@#?
On the above link, I tried this rule.
ani.gamer.com.tw#@#.afs_ads

Why is ".afs_ads", not other?

In that case, we chose @@||ani.gamer.com.tw^$generichide.
Because "ani.gamer.com.tw#@#.afs_ads" can only hide the 1st anti-adblock message, not hide the 2nd anti-adblock message.

After login into gamer.com.tw:
The 1st anti-adblock message appears.
(If not login into the account, no the 1st anti-adblock message.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9p1KqqC.png)
</details><br/>

Anyway, thanks for your reply!
Happy Xmas and New Year!

**Comment by BlazDT** [comment]
It depends on what their adblock script checks. If it only checks one or two elements, #@# is usually used.
If more elements, generichide.

Please take a look at https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters about how to create your own filters.

If you still have questions, please post on the forum in custom filters forum part. Github should be used for fixing ads and not having a general discussion.
Thank you for your understanding.

**Comment by lancelot-moon** [comment]
Hi,
I just found a problem.
For browsers on Windows, your rule, getrelax.club#@#.google-ad, can solve anti-adblock.
But it still shows anti-adblock if using browsers on Android.

@@||getrelax.club^$generichide can solve it.

**Comment by BlazDT** [comment]
Can't reproduce on my Android 7.

@AdamWr 
Could you please check with rule from commit on Android, thank you.

**Comment by AdamWr** [comment]
It works fine on my end (checked it on Android and Windows).

**Comment by lancelot-moon** [comment]
In my AdGuard for Android, English Filter is v1.1.40.50 and Annoyances Filter is v1.0.23.25.
There are your new rules in them.
Do I need to clear cookie in my chrome of Android?

**Comment by BlazDT** [comment]
@Alex-302 
Can you add the site to DNS family please.
