### ISSUE TITLE
sports.ndtv.com

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8728]
**Site**: https://sports.ndtv.com/formula-1

**Issue**: Please remove the word "Advertisement" at the bottom of the page.

**Screenshot**: http://prntscr.com/hqzlj0

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Also fixed social buttons and some ad left-overs at main site.
