### ISSUE TITLE
viewportsizer.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87286]
**Issue URL (Ads)** : https://viewportsizer.com/what-is-my-screen-size/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124178761-7d49b500-dacf-11eb-849d-14462d6c4613.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
9150 visitors/month
for user rules:
`viewportsizer.com##.cloudways`
