### ISSUE TITLE
robloxhacks.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#87299]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

anti adblock (blockadblock)
`https://robloxhacks.net/`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
<img width="1130" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/124219084-e34c3180-dafb-11eb-9859-10f2911e9384.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.6.6
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by DandelionSprout** [comment]
I propose:
```
@@/favicon.ico|
@@/favicon1.ico|
@@/doubleclick.ico|
```

Alternately: `@@.ico|$domain=robloxhacks.net`

**Comment by JobcenterTycoon** [comment]
doesn’t work for the advanced BlockAdblock version because the script checks a ton of ad servers

But Adguard and uBlock Origin have a special defuser: `##+js(nobab)`
