### ISSUE TITLE
douploads.com [Fake Button]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8729]
**Site**: https://douploads.com/y0i6mtz91xyl

**Issue**: Seeing a fake download button on the second page (after completing the captcha and on the next page).

**Screenshot**: http://prntscr.com/hr0rnh

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Also disabled their annoying music and hid playback button in Annoyance filter.
