### ISSUE TITLE
mcqhubb.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87309]
**Issue URL (Annoyance)**: https://www.mcqhubb.com/cad-cam-and-automation/which-of-the-following-is-not-subtractive-process-311me/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124244427-8cb31780-db3c-11eb-85e4-b6479ec68ffb.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2840 visitors/month
for user rules:
```
mcqhubb.com#?#.rightsidebar > div.bg-maincol:has(> p:contains(newsletter))
mcqhubb.com#?#.rightsidebar > div:has(> div.sharemedia)
```
