### ISSUE TITLE
updatesinsider.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87316]
**Issue URL (Ads)** : https://www.updatesinsider.com/viewer/best-mbox-file-viewer/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124270076-55069880-db59-11eb-9001-c29d8f9cfd3a.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
11 200 visitors/month (> 30000 needed)
for user rules:
`updatesinsider.com###custom_html-3`
