### ISSUE TITLE
Adguard stopped block ads in Yandex weather yesterday

### ISSUE THREAD

**Issue by azlk** [AdguardTeam/AdguardFilters#87322]
Everything was ok until yesterday, now it doesn't block ads in Yandex weather app!
I didn't change anything, all filters are fresh and updated
![Screenshot_20210702_155047_ru yandex weatherplugin](https://user-images.githubusercontent.com/4054635/124277070-4e722400-db4d-11eb-8464-4025f7870189.jpg)

**Comment by Alex-302** [comment]
You may turn off ads in About menu.
If ad domain is blcoked, weather map is broken.
