### ISSUE TITLE
Uber Eats tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#87336]
https://www.ubereats.com/ --> https://www.ubereats.com/ramendca/events/ack?seq=0 tracker?
https://www.ubereats.com/ --> https://www.ubereats.com/_events

```
https://www.ubereats.com/ramendca/events/ack?seq=0

||ubereats.com/ramendca/events^
||ubereats.com/*_events^
||uber.com/*_events^
```

**Comment by Sergey-Lyapin** [comment]
I did not find this request:
`https://www.ubereats.com/ramendca/events/ack?seq=0`
