### ISSUE TITLE
jatheon.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87355]
**Issue URL (Annoyance)**: https://jatheon.com/blog/should-you-delete-or-archive-email/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124317846-71282b00-db95-11eb-9f3c-fd156209169a.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
6770 visitors/month
`jatheon.com##.blog-newslleter`
