### ISSUE TITLE
workplaceprivacyreport.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87368]
**Issue URL (Annoyance)**: https://www.workplaceprivacyreport.com/2018/01/articles/international-2/does-the-gdpr-apply-to-your-us-based-company/

<details><summary>Screenshots:</summary>

https://www.workplaceprivacyreport.com/2018/01/articles/international-2/does-the-gdpr-apply-to-your-us-based-company/
![image](https://user-images.githubusercontent.com/76880977/124331625-35995b00-dbad-11eb-8447-ab847241018c.png)
![image](https://user-images.githubusercontent.com/76880977/124331624-3500c480-dbad-11eb-80a9-a6d84f34d766.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2270 visitors/month
