### ISSUE TITLE
baho.com.tr

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#8748]
***Description***: 

Anti Adblock Script

[https://www.baho.com.tr/Galeri/2017-de-viral-olmus-ve-bircok-insani-inandirmis-8-yanlis-haber/8172/1/](url)
<details><summary>Screenshot:</summary>

![bh](https://i.hizliresim.com/a1OL3R.png)

</details><br/>

Information                            | Value
---                                    | ---
Operating system:                      | Win10
Browser:                               | Chrome - Extension
AdGuard version:                       | 2.7.2
Filters enabled:                       | English - Spyware - Social Media -Annoyance - Turkish - Fanboy's Social Blocking List
Other extensions:  | Disconnect - HTTPS Everywhere

**Comment by PentagramTr** [comment]
I gave the correct link but it gives 404 error.

https://www.baho.com.tr/Galeri/2017-de-viral-olmus-ve-bircok-insani-inandirmis-8-yanlis-haber/8172/1/

**Comment by AdamWr** [comment]
Fixed.

**Comment by PentagramTr** [comment]
Thanks Adam
@AdamWr
