### ISSUE TITLE
Adblocker

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#87593]
https://animedevil.com/

![Screenshot_20210705-232540_Firefox Beta](https://user-images.githubusercontent.com/46019727/124503962-62858200-dde8-11eb-88ca-fce051b089de.jpg)

Hope to get a fix

**Comment by BlazDT** [comment]
Please provide required information as outlined here:
https://github.com/AdguardTeam/AdguardFilters/blob/master/.github/ISSUE_TEMPLATE/Ad_report.md
