### ISSUE TITLE
vi.nl

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87643]
***Issue URL (Incorrect Blocking)***: https://www.vi.nl/

<details><summary>Screenshots:</summary>

https://www.vi.nl/cookies/
![image](https://user-images.githubusercontent.com/76880977/124575318-eb440280-de68-11eb-96e8-97987de67d39.png)

+ ### ADGUARD DNS
</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
What's wrong? The website opens fine.

**Comment by chirag127** [comment]
Well I can still reproduce the screen shown in the screen shot.

**Comment by zloyden** [comment]
The screen will be just once - after applying the JS rule, you won't see it anymore.
