### ISSUE TITLE
Replace script rules and use `remove-attr` scriptlets instead 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#87667]
There're many rules that call `removeAttribute` (mostly, in the `tweaks.txt` file).

We should replace them with scriptlet rules instead:
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-remove-attr

**Comment by stanislav-atr** [comment]
@ameshkov, there are some rules like
```
siyasetcafe.com#%#AG_onLoad(function() { setTimeout(function() { var b = document.body; if(b) { b.removeAttribute("onselectstart"); b.removeAttribute("oncontextmenu"); b.removeAttribute("ondragstart"); } }, 300); });

poisonous-raspberry-fields.blogspot.com#%#AG_onLoad(function(){var a=document.getElementsByTagName("body")[0];a&&(a.removeAttribute("onmousedown"),a.removeAttribute("onselectstart"),a.removeAttribute("ondragstart"));a=document.querySelectorAll(".post-body[ondragstart][onmousedown][onselectstart]");for(var b=0;b<a.length;b++)a[b].removeAttribute("onmousedown"),a[b].removeAttribute("onselectstart"),a[b].removeAttribute("ondragstart")});
```
with multiple attributes being removed in a script. Should we keep them as it is or break down into few scriptlets?

**Comment by ameshkov** [comment]
@stanislav-atr it'd be better to replace them with multiple rules

**Comment by stanislav-atr** [comment]
Resolved [here](https://github.com/AdguardTeam/AdguardFilters/pull/87851).
