### ISSUE TITLE
nbcnews.com (ios safari)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#87672]
||geoip.nbcnews.com^

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nbcnews.com/business/business-news/office-life-beckons-again-pandemic-s-digital-nomads-weigh-benefits-n1273000)

**Comment by Alex-302** [comment]
Not sure if it must be blocked.

**Comment by Alex-302** [comment]
Not sure if it must be blocked.
