### ISSUE TITLE
peacock tv (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#87673]
||geoloc.yospace.com^
||video-ads-module.ad-tech.nbcuni.com^

https://apps.apple.com/us/app/peacock-tv-stream-tv-movies/id1508186374

you have to create an account to see them

**Comment by Alex-302** [comment]
Cannot register. Is nothing broken by these rules?

**Comment by jordanelliott23** [comment]
successfully watched multchanels and a movie everything works great with both filters in place:)
