### ISSUE TITLE
mercadopago.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#87675]
[https://www.mercadopago.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.mercadopago.com.br/)
 
 ![cookies](https://user-images.githubusercontent.com/35470489/124658066-b2f8f000-de79-11eb-8b42-f876ed7a3eee.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by IThinkIAmCool** [comment]
@ryanbr
