### ISSUE TITLE
thecalculatorsite.com

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#87697]
https://www.thecalculatorsite.com/articles/units/how-big-is-an-acre.php

Unable to see content in the box as seen in the screenshot when AG extension is enabled for Chrome in Windows. When AG extension is turned off, I am able to see the content.

When AG extension is on: https://prnt.sc/196ziz0
When AG extension is off: https://prnt.sc/196zsvt

**Comment by zloyden** [comment]
Not reproduced with out filters. If you still have the issue, please make a report via [the link](https://agrd.io/report).
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/125414894-6f8c876f-4c24-4c7f-98b6-2050b3dee6f1.png)

</details><br/>
