### ISSUE TITLE
rule proposal against google analytics via jentis.com serverside tracking

### ISSUE THREAD

**Issue by deserteagle** [AdguardTeam/AdguardFilters#87723]
### Problem Description

jentis.com offers serverside google analytics tracking via random subdomains and random script filenames hostet (currently) in the azure cloud - thus making it hard to detect and block. a jentis integration url may look like this:
`https://132abc.current-visited-domain.tld/get/live/web/_/321cba.js`
with `132abc` and `321cba` being random strings.

### Proposed Solution
the integration JS snippet has some parts of the initial request url hardcoded, the filter rule below seems to do the trick.
`||*/get/live/web/_/*`

**Comment by Alex-302** [comment]
Hi. We need few examples.

**Comment by deserteagle** [comment]
Hello,
while looking for example pages, i found another url structure:
`https://132abc.current-visited-domain.tld/get/domainname-tld/live/_/jts.js`
which can be ruled out with `||*/get/*/live/_/jts.js`

as requested, here are some examples who load jentis
[https://www.refurbed.at/](https://www.jentis.com/)
[https://www.refurbed.at/](https://www.refurbed.at/)
[https://news.greenpeace.at/](https://news.greenpeace.at/)

**Comment by Alex-302** [comment]
Ok.
