### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87724]
**Issue URL (Annoyance)**: https://www.bing.com/search?q=url:https%3A%2F%2Fblog.nextdns.io%2F&go=Search

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124753803-13099800-df47-11eb-92fa-6222c5aab5af.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
Not reproduced on my end, but we don't block first party widgets. This rule from the screenshot shoulbe enough for user rules.

**Comment by chirag127** [comment]
Hmm... This kind of a pop up. I think they are A/B testing it.
