### ISSUE TITLE
spotify.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87976]
**Issue URL (Annoyance)**: https://open.spotify.com/album/4QLAtpLNUsHEYrcHXmMIZZ

>  can't copy the name of the album - Stay (with Justin Bieber)
<details><summary>Screenshots:</summary>

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
@chirag127
Please describe the issue in more detail

**Comment by chirag127** [comment]
I can't copy the name of the album - Stay (with Justin Bieber). Is it possible to remove this annoyance using adguard?

**Comment by chirag127** [comment]
Adguard please resolve this issue.
