### ISSUE TITLE
independent.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#87991]
**Issue URL (Ads)** : https://www.independent.co.uk/asia/india/nz-karl-rock-youtube-blacklisted-india-b1881165.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/125122695-6a5c6380-e113-11eb-8b10-e8843328fb1b.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Not sure about it.

**Comment by chirag127** [comment]
@Alex-302 By the there no way I can use the voucher as it is further already blocked Adguard DNS. If it is not advertisement then why ADGUARD DNS filter block it when I try to click on the affiliate link.
