### ISSUE TITLE
Duplicate and reduntant rule

### ISSUE THREAD

**Issue by duryytt** [AdguardTeam/AdguardFilters#88007]
https://github.com/AdguardTeam/AdguardFilters/blob/76d65ebfc35689149202e8c980b732c15a71c0f5/TurkishFilter/sections/specific.txt#L49

https://github.com/AdguardTeam/AdguardFilters/blob/76d65ebfc35689149202e8c980b732c15a71c0f5/TurkishFilter/sections/specific.txt#L4595

![site](https://user-images.githubusercontent.com/85909109/125143512-a7305680-e123-11eb-89c2-859dc0adb67b.png)

---

I guess `fragmanlar.com##.reklam-300` is a redundant rule because the rule `fragmanlar.com##div[class^="reklam-"]` blocks all ads.

https://github.com/AdguardTeam/AdguardFilters/blob/76d65ebfc35689149202e8c980b732c15a71c0f5/TurkishFilter/sections/specific.txt#L3944

https://github.com/AdguardTeam/AdguardFilters/blob/76d65ebfc35689149202e8c980b732c15a71c0f5/TurkishFilter/sections/specific.txt#L441

**Comment by Alex-302** [comment]
Thanks.
