### ISSUE TITLE
tmonews.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88056]
||analytics.tmonews.com^

appears in log when clicking on facebook article

**Comment by Alex-302** [comment]
How to reproduce it?

**Comment by jordanelliott23** [comment]
i clicked an article and it showed up in my log

**Comment by Alex-302** [comment]
It is not used at the moment.
![image](https://user-images.githubusercontent.com/8361299/125771581-514e16f1-53c6-4e67-adb7-b40bbb9d9168.png)
