### ISSUE TITLE
rotating adservers

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88050]
||displacepepperyadvertisement.com^
||toadassuagevolatile.com^
||congressaffrayghosts.com^
||technicalityplayground.com^
||quandarydisadvantage.com^
||windscreenregimepros.com^
||perceivefilthy.com^
||spotsetcpar.com^
||planneradministratorsignify.com^
||ir3.xyz^
||clickonik.com^
||trackier.net^
||o18.click^
|femax20.com^
||ff-04.com^
||boughtinvulnerablenothing.com^
||districtprovocativeforceful.com^
||h04y.com^
||boughtinvulnerablenothing.com^

any better way to block them? the ad domain redirects popop after clicking play on each video players they keep adding more domains. also there is leftover exit ad buttons

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://watchmalcolminthemiddle.com/stream/malcolm-in-the-middle-3x3/(

**Comment by Sergey-Lyapin** [comment]
@jordanelliott23
I'll add watchmalcolminthemiddle.com to this rule (which blocks third-party scripts except scripts from specified domains.):
/^(?!.*(bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|googletagmanager.com|gstatic.com|jquery.com|jsdelivr.net|jwpcdn.com|jwplatform.com|polyfill.io|recaptcha.net|shrink.pe|twitter.com|ulogin.ru|unpkg.com|userapi.com|vidazoo.com|vk.com|yandex.|yastatic.net|ytimg.com|zencdn.net|player|youtube.com|cackle.me|googleoptimize.com|vuukle.com|chatango.com|twimg.com|google-analytics.com|hcaptcha.com|raincaptcha.com|media-imdb.com|blogger.com)).*$/$third-party,script,domain=

**Comment by jordanelliott23** [comment]
still lots of unblocked ad donainswhen clicking on each ad player

**Comment by jordanelliott23** [comment]
tons of adservers still
