### ISSUE TITLE
skype (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88064]
||browser.pipe.aria.microsoft.com^ (used for
metrics: https://techcommunity.microsoft.com/t5/sharepoint/spo-site-makes-a-call-to-browser-pipe-aria-microsoft-com/m-p/829304/highlight/true#M33958)

||self.events.data.microsoft.com^
||events.data.microsoft.com^

https://apps.apple.com/us/app/skype-for-iphone/id304878510

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/825
