### ISSUE TITLE
avanigo.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88091]
**Issue URL (Ads)** : https://avanigo.com/what-do-you-mean-by-incredible-india-what-is-its-significance/#What_is_Incredible_India_meaning

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/125190528-460b9e80-e25b-11eb-9ab1-d276878a780c.png)
![image](https://user-images.githubusercontent.com/76880977/125190530-46a43500-e25b-11eb-81eb-c110fca70fb6.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I was not able to reproduce this breakage and this site has 4020 visitors/month.

**Comment by chirag127** [comment]
@Sergey-Lyapin 

It's not breakage. It's ads leftover . 2nd image is without adguard extension and Just using dns filtering. If it was breakage I would have written incorrect blocking in the bracket.

**Comment by Sergey-Lyapin** [comment]
Now I understand, thanks for explanation, but anyway this site doesn't have enough visitors.
