### ISSUE TITLE
tomshardware.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8812]
**Site**: http://www.tomshardware.com/reviews/best-ram,4057.html

**Issue**: Seeing ad on top of the page.

**Screenshot**: https://screenshotmachine.com/serve.php?img=tomshardware-com-1024x768desktop-1d2bfc.png

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
InstartLogic again.

@seanl-adg 
Can you please take a look at https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js and maybe you find out how we can realize it in AdGuard, thank you.

**Comment by Nzzyme** [comment]
Hi, a gentle reminder. I hope this is being considered. Thanks
