### ISSUE TITLE
kinopoisk.ru

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#88144]
Конфиг тот же, что и #85472

По любому линку с инфо о фильме типа такого https://www.kinopoisk.ru/series/408571/ после прокручивания страницы чуть вниз до подгружаемых элементов возникает loop - перезагрузка страницы. В логе мелькает sso.​kinopoisk.ru. Если разрешить его правилом

>`@@||sso.kinopoisk.ru^$domain=sso.passport.yandex.ru`

то проблема уходит. Даже если потом дезактивировать правило.

**Comment by stanislav-atr** [comment]
@Baltazar500, добрый день! Проблема еще актуальна? Не воспроизводится на андроид с версией AG v4.0 nightly 20

**Comment by Baltazar500** [comment]
>Проблема еще актуальна? Не воспроизводится на андроид с версией AG v4.0 nightly 20

А на 3.6.2 (stable), как указано в конфиге ? Я нестабильные/экспериментальные/бета релизы обычно не использую :/ Насчёт актуальности трудно сказать. После единичного разрешения проблема ушла. На 4pda про подобное уже отписывались другие люди и я создал тикет дабы обозначить наличие проблемы.

**Comment by stanislav-atr** [comment]
На свежем stable тоже не повторяется. @Sergey-Lyapin, посмотри, пожалуйста.

**Comment by Sergey-Lyapin** [comment]
@Baltazar500
Здравствуйте, а у вас именно циклическая перезагрузка? У меня только один раз редирект на sso.kinopoisk.ru и обратно происходит, причем повторяется с выключенным Адгардом и Экстрой. 
Какие именно фильтры/опции антитрекинга у вас включены?
