### ISSUE TITLE
enjoyfuck.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8814]
**Site**: http://enjoyfuck.com/hosted/YTItMjktNTIzMTUzNw==/No-Sound%3A-Beautiful-Helen-and-luck-bbc/

**Issue**:
1. Remove ad banner on video player
2. Remove ad that remains when scrolling (see at bottom right of page)
3. Pop-up
4. Remove a fake small window that says Upgrade chrome (seen here: http://prntscr.com/hrlyvk)

**Screenshot**: http://prntscr.com/hrlyd2

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Please check for popup after filter update (in about 2-3 hours), thank you. I could not reproduce it.

**Comment by Nzzyme** [comment]
Pop-up not seen now. Thank you
