### ISSUE TITLE
fuckgonzo.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8815]
**Site**: http://fuckgonzo.com/jv/indoor/YTItMzItNDkxNTk1Ng==/Patricia-Kimberly-Gets-Fucked-In-The-Ass/

**Issue**:
1. Remove "x" that remains when scrolling (see at bottom right of page)
2. Pop-up

**Screenshot**: http://prntscr.com/hrm1ki

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Please check for updates in about 2-3 hours. I couldn't reproduce popup.

**Comment by Nzzyme** [comment]
Not seeing pop-up. Thank you
