### ISSUE TITLE
Texas sites

### ISSUE THREAD

**Issue by TX-ssos9s9dhdew** [AdguardTeam/AdguardFilters#88163]
_Hi AdGuard team, can you help us Texas users?_

_I wanna make sure there's no hidden trackers on our local news sites._

_However, with Texas being so big there's a lot of local news stations (NBC, Fox, abc, ect). 
Dallas, San Antonio and Houston all have their own stations. I tried to include as many as I could for each place, but I know you guys are busy so I only added 8._

_When testing each site you should also try to click a random article, it might give you a unique ad Id on the page._

`https://foxsanantonio.com`

`https://www.fox26houston.com`

`https://www.nbcdfw.com`

`https://www.kens5.com`

`https://www.ksat.com`

`https://abc13.com`

`https://www.fox4news.com`

`https://www.khou.com/local/`

**Comment by Alex-302** [comment]
@TX-ssos9s9dhdew Done. Blocked few trackers, ad leftovers and fixed 2 incorrect blockings.

**Comment by TX-ssos9s9dhdew** [comment]
Thank you guys so much! :)

Can't believe there was so many trackers!
