### ISSUE TITLE
icallhelpline.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88170]
***Issue URL (Annoyance)***: https://icallhelpline.org/

> Please tell me the user filter.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121152477-df155700-c862-11eb-8954-5c1b47a5194f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
For user rules:
```
icallhelpline.org##.pps-popup
icallhelpline.org##.b-modal
```
