### ISSUE TITLE
Zoominfo.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88184]
***Issue URL (Incorrect Blocking)***: https://www.zoominfo.com/c/nextdns-inc/482552930

getting redirected from https://www.zoominfo.com/c/nextdns-inc/482552930 to https://www.zoominfo.com/ when adguard is enabled.

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
The problem is caused by EasyPrivacy, by rule `/amplitude-*.js$script`
Please add to user rules: `@@||zoominfo.com/c/amplitude-js.*.js`

@ryanbr please take a look
