### ISSUE TITLE
healthgrades.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88196]
||ade.googlesyndication.com^

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.healthgrades.com/right-care/kidneys-and-the-urinary-system/difficulty-urinating-after-surgery)

**Comment by Alex-302** [comment]
Not reproduced even without AdGuard.

**Comment by jordanelliott23** [comment]
must be in usa only?

**Comment by jordanelliott23** [comment]
i can also reproduce in tubi tv app for apple tv too the same domain using opendns logger

**Comment by Alex-302** [comment]
I see one result in my AdGuard Home log, but I don't know which site/app requested it.
