### ISSUE TITLE
gitlab tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#88197]
https://assets.gitlab-static.net/assets/webpack/commons-pages.admin.audit_logs-pages.admin.impersonation_tokens-pages.analytics.productivity_analyti-0cf84cb4.189cbab7.chunk.js

**Comment by jordanelliott23** [comment]
definitely a tracker

**Comment by Alex-302** [comment]
Need page address with this request.
