### ISSUE TITLE
putlocker.cz [Fake Buttons]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8822]
**Site**: http://putlocker.cz/episode/the-flash-season-4-episode-5/

**Issue**: 

1. Please remove the fake buttons seen in the screenshots. They lead to fake sites.

**Screenshot**: 

http://prntscr.com/hrnqq7
http://prntscr.com/hrnqwo

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Site seems to be down :(

**Comment by Nzzyme** [comment]
Just checked and able to open the site. Can you check now / use a VPN? Thank you

**Comment by BlazDT** [comment]
Screenshots are of another putlocker site. Please open a new issue about the other site.
Fixed the one I could find for putlocker.cz
