### ISSUE TITLE
Trendyol tracking parameters?

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#88225]
After click order tracking link in my mail address, something like tracking parameters is added to the link.
Could you please check if it really is a parameter?

I can provide an account for you to check.

Some sample links:

- This is the first link that appears before viewing the order page:

 `https://app.adjust.com/jsr?url=https%3A%2F%2Fp8zh.adj.st%2Fei1zb4_q4nmai%3Fadjust_t%3Dei1zb4_q4nmai%26MyAccount%3DMyOrders%26Page%3DOrderDetail%26orderParentId%3D704076304%26utm_source%3Demail%26utm_medium%3Dfree%26utm_campaign%3DTY_TR_OrderConfirm%26adjust_adgroup%3Dall%26adjust_campaign%3DTY_TR_OrderConfirm%26adjust_tracker_limit%3D999999999%26adjust_deeplink%3Dty%253A%252F%252F%253FMyAccount%253DMyOrders%2526Page%253DOrderDetail%2526orderParentId%253D704076304%2526adjust_t%253Dei1zb4_q4nmai%2526utm_source%253Demail%2526utm_medium%253Dfree%2526utm_campaign%3DTY_TR_OrderConfirm%2526adjust_adgroup%253Dall%2526adjust_campaign%3DTY_TR_OrderConfirm%2526adjust_tracker_limit%253D999999999%26adjust_redirect%3Dhttps%253A%252F%252Fwww.trendyol.com%252FHesabim%252F%2523%252FSiparislerim%252FSiparisdetay%252F704076304%2526adjust_t%253Dei1zb4_q4nmai%2526utm_source%253Demail%2526utm_medium%253Dfree%2526utm_campaign%3DTY_TR_OrderConfirm%2526adjust_adgroup%253Dall%2526adjust_campaign%3DTY_TR_OrderConfirm%2526adjust_tracker_limit%253D999999999`

- Link on order page:

 `https://www.trendyol.com/hesabim/siparislerim/704076304?adjust_t=ei1zb4_q4nmai&adjust_adgroup=all&adjust_campaign=TY_TR_OrderConfirm&adjust_tracker_limit=999999999`

- The link after clicking on the product you bought:

`https://www.trendyol.com/fizello/shiba-inu-kawaii-eating-ramen-noodles-t-shirt-p-119180721?boutiqueId=61&merchantId=115224&_ga=2.115148807.1628198939.1626172302-756124041.1626172302`

**Comment by Alex-302** [comment]
Please test these rules:
```
||trendyol.com^$removeparam=_ga
||trendyol.com^$removeparam=adjust_campaign
```

You can find parameters in dev tools
![image](https://user-images.githubusercontent.com/8361299/125773598-a46b71cf-0e7f-43f4-9831-f313e06bcd61.png)

In app.adjust.com is only one parameter - `url`

**Comment by RadicalNoise** [comment]
@Alex-302 

> Please test these rules:

```
||trendyol.com^$removeparam=_ga
||trendyol.com^$removeparam=adjust_campaign
```

It works fine.
