### ISSUE TITLE
appd.at

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#88258]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

Anti select, anti right click and anti shortcuts
`https://appd.at/`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.6.6
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Sergey-Lyapin** [comment]
This site does not have enough visitors. For user rules:
```
appd.at#%#//scriptlet("abort-on-property-write", "image_save_msg")
appd.at#%#//scriptlet('set-constant', 'nocontext', 'noopFunc')
```
