### ISSUE TITLE
Chinese Shopee tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#88271]
https://github.com/AdguardTeam/AdguardFilters/issues/85906

chinese tencent's shopee app .apk download: https://apkpure.com/p/com.shopee.ph
https://apkpure.com/p/com.shopee.th
https://apkpure.com/p/com.shopee.sg
...

https://www.google.com/search?q=site:apkpure.com+shopee

**Comment by c2xusnpq6** [comment]
```
http://content.garena.com/shopee/track_config/conf.json

||df.infra.shopee.TLD/v*/shpsec/report
||df.infra.shopee.TLD/v*/shpsec/event
||shopee.TLD/userstats_record$xmlhttprequest
||shopee.TLD/__t__$xmlhttprequest
||content.garena.com/shopee/track_config^
```

**Comment by c2xusnpq6** [comment]
https://shopee.tw/product/10259132/4490259159 --> https://shopee.tw/__t__

![image](https://user-images.githubusercontent.com/75058881/126265740-45d16b8a-4723-42d1-89df-caaa0fba96b1.png)

tracker?
```
https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/a64d2e060d72ef2bf813.tr.js
https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/303f45e5fd9aaf01aef1.tr.js
https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/81e06ee8fa02adbdce4d.tr.js
https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/8b73fe247bbda275787c.tr.js

||deo.shopeemobile.com/shopee/shopee-pcmall-live*/assets/*.tr.js
```
![image](https://user-images.githubusercontent.com/75058881/126265877-3b7dacf6-125c-4d96-8cd4-84521773187c.png)

**Comment by c2xusnpq6** [comment]
https://shopee.cn/ --> https://seller.shopee.sg/api/pap/report?uid={hidden}

tracker?:
```
https://seller.shopee.sg/api/pap/report?uid={hidden}

||seller.shopee.*/api/pap/report^
```

![image](https://user-images.githubusercontent.com/75058881/126267179-7bb27522-fa3d-4b58-a1f6-4a30fedf0b63.png)

**Comment by c2xusnpq6** [comment]
```
||shopee.*/__t__
```
![Screenshot_20210724-032950_Trebuchet.png](https://user-images.githubusercontent.com/75058881/126832174-84211807-8ea0-4e0e-97bd-e13af49c782e.png)

**Comment by stanislav-atr** [comment]
@c2xusnpq6, hi! Sorry fo the late reply, but i wasn't able to install this xapk on my MIUI device. Is this issue is still relevant?

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6, hi! Sorry fo the late reply, but i wasn't able to install this xapk on my MIUI device. Is this issue is still relevant?

https://amp.reddit.com/r/Xiaomi/comments/jyft24/installing_split_apks/

> You need to turn off MIUI Optimizations temporarily

**Comment by stanislav-atr** [comment]
@c2xusnpq6, i was able to check the app and only seen `||content.garena.com/shopee/track_config/conf.json` request, which i am adding to our Spyware filter.

**Comment by stanislav-atr** [comment]
It seems that  the other URLs are not there anymore, but you may contact Thai filters developers [here](https://adblock-thai.github.io/) to ask them to update existing rules.
