### ISSUE TITLE
expertology.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#88278]
При копировании выделенного текста в буфер обмена добавляется мусор.
 Причина в переназначении свойства `document.oncopy` в начале скрипта [https://expertology.ru/local/templates/proexperto/js/app.js](https://href.li/?https://expertology.ru/local/templates/proexperto/js/app.js).

`expertology.ru#%#//scriptlet('abort-on-property-write', 'document.oncopy')`

[https://expertology.ru/13-luchshikh-zamkov-dlya-velosipedov/](https://href.li/?https://expertology.ru/13-luchshikh-zamkov-dlya-velosipedov/)

___________________________________________________
 Adguard v3.6.6 | Serpent v52.2021.06.05 (<-Basilisk<-FireFox v52.9) | Win7SP1
Базовый фильтр AdGuard | Фильтр отслеживания по URL | Фильтр счетчиков и систем аналитики
Фильтр виджетов социальных сетей | Фильтр раздражителей | Русский фильтр
 Антитрекинг: Стандарт + Блокировка WebRTC

**Comment by zloyden** [comment]
Добавил правило в фильтр раздражителей, проверьте обновление фильтров через пару часов.
