### ISSUE TITLE
my.mail.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#88311]
**1**. Реклама.

<details><summary>Screenshot:</summary>

![](https://i.ibb.co/2Sf5bjM/2021-07-14-1.png)
</details>

`my.mail.ru##.b-column-right__block-sale`

___________________________________________________

 **2**. Остатки.

<details><summary>Screenshot:</summary>

![](https://i.ibb.co/1mh70wL/2021-07-14-2.png)
----------
----------
----------
![](https://i.ibb.co/HV9V88t/2021-07-14-3.png)
</details>

`my.mail.ru##.b-fourth-pseudo-column, .b-column-right__block-news-cloud`

[https://my.mail.ru/](https://href.li/?https://my.mail.ru/)

___________________________________________________
 Adguard v3.6.6 | Serpent v52.2021.06.05 (<-Basilisk<-FireFox v52.9) | Win7SP1
Базовый фильтр AdGuard | Фильтр отслеживания по URL | Фильтр счетчиков и систем аналитики
Фильтр виджетов социальных сетей | Фильтр раздражителей | Русский фильтр
 Антитрекинг: Стандарт + Блокировка WebRTC

**Comment by Alex-302** [comment]
Ничего не повторилось. 
@Sergey-Lyapin @zloyden проверьте у себя.

**Comment by zloyden** [comment]
Остатки не повторились, но элементы из первого скриншота убрал в раздражителях.
