### ISSUE TITLE
part 2 roating adservers on watchmalominthemiddle.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88320]
https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://watchmalcolminthemiddle.com/stream/malcolm-in-the-middle-3x3/(

click play on each player u will get multiple app urls even after latest update

**Comment by jordanelliott23** [comment]
||qocvicklgcgr.com^$important
||daijopimplo.com^$important
||predictiondexchange.com^$important
||zjwwbznpcqhk.com^$important
||bycashexo.com^$important
||zewhaphaste.com^$important


here are most of them

**Comment by jordanelliott23** [comment]
also leftover close ad buttons

**Comment by jordanelliott23** [comment]
@Alex-302  do u still all these domains popping up u have to switch to different players than plan and pause they should all appear

**Comment by zloyden** [comment]
Hi! What product have you been using? It would be better, if you had done a report via this [link](https://agrd.io/report) or our extension / app.
Btw, I don't see those requests on my end, but we have a Regex rule that blocks them.

**Comment by Alex-302** [comment]
I don't see missed ad servers with DNS only.
