### ISSUE TITLE
videopio.com popups and ad tracker

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88326]
||zjwwbznpcqhk.com^
||qocvicklgcgr.com^
||furricity-nursubaru.xyz^
||pfzzgurflf.com^
||adsemo.com^ (appeared in my logs like 20 min or some later)

you will have to refresh site two times to see the ad domains.

https://www.videopio.com/breaking-bad-s1-e1
![C58BC853-1DDD-4736-A8E2-D056FA09CBC9](https://user-images.githubusercontent.com/71462072/125704438-b412917e-e63b-4805-b96f-6dd25aa3780a.jpeg)

**Comment by jordanelliott23** [comment]
||adsemo^ (appeared in my logs like 20 min or some later)

**Comment by Alex-302** [comment]
Nothing reproduced.
