### ISSUE TITLE
watchfreenet.cc

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88328]
||syrsple2se8nyu09.com^
||easyads28.mobi^

click play and theze will appear in log

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://watchfreenet.cc/episode/loki-season-1-episode-1/)

**Comment by jordanelliott23** [comment]
are u on ios? its easy reproduable on ios

**Comment by Alex-302** [comment]
Sure. Second domain is not resolved, added the first rule.
