### ISSUE TITLE
tr.sabah

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardFilters#8835]
***Steps to reproduce the problem***:
1 - Please open the "Sabah" application
2- Open some new and you will see the white empty place on top. Blocked advert place. Please hide it.

***Screenshots***:
![Screenshot](https://user-images.githubusercontent.com/15933805/34327119-8170d098-e8cd-11e7-8ff8-c5a6ad6eca12.png)

***Google Play Link***:
https://play.google.com/store/apps/details?id=tr.sabah

Information                            | Value
---                                    | ---
Operating system version (Android/iOS) | Android 7.1.1 on Android One dvice
Application:                               | Sabah - https://play.google.com/store/apps/details?id=tr.sabah
AdGuard version:                       | 2.10.176
Filters enabled:                       | English + Spyware + Social + Annoyances + Turkish + Mobile
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)

**Comment by Alex-302** [comment]
It seems it builtin.
