### ISSUE TITLE
com.mobikolik.tumgazeteler

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardFilters#8836]
***Steps to reproduce the problem***:
1 - Please open the "Tüm Gazeteler" application
2- Open newspaper from list and you will see the advert end of the every page.

Added filtering log suspicious requests and the screenshot of the advert
>clearbit.com
>dygdigital.com
>agkn.com

etc.

***Screenshots***:
![tum_gazeteler_screenshot](https://user-images.githubusercontent.com/15933805/34327173-c325dbc2-e8ce-11e7-8a47-aff63ca43cdc.png)
![ss1](https://user-images.githubusercontent.com/15933805/34327176-d12a889e-e8ce-11e7-8a94-e79bda4814be.png)
![ss2](https://user-images.githubusercontent.com/15933805/34327177-d7aa312e-e8ce-11e7-80ce-65dafaec1cd2.png)
![ss3](https://user-images.githubusercontent.com/15933805/34327183-eb5660c6-e8ce-11e7-8bb8-b3c3f102c475.png)

***Google Play Link***:
https://play.google.com/store/apps/details?id=com.mobikolik.tumgazeteler

Information                            | Value
---                                    | ---
Operating system version (Android/iOS) | Android 7.1.1 on Android One dvice
Application:                               | Tüm Gazeteler - https://play.google.com/store/apps/details?id=com.mobikolik.tumgazeteler
AdGuard version:                       | 2.10.176
Filters enabled:                       | English + Spyware + Social + Annoyances + Turkish + Mobile
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)

**Comment by Alex-302** [comment]
added
```
||graph.facebook.com^$app=com.mobikolik.tumgazeteler
```
