### ISSUE TITLE
Happy mod

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#88431]
[Happy mod](https://www.happymod.com/) 

log
||log.happymod.com^
||log1.happymod.com^

**Comment by Sergey-Lyapin** [comment]
I was not able to reproduce these requests.

**Comment by SASUKE0721** [comment]
I'm requesting this communication within the app, not the site.

![21-07-22-03-18-37-749_deco](https://user-images.githubusercontent.com/87330832/126539463-71064a1c-a32a-4b99-a2af-b4fc0661969c.jpg)

**Comment by SASUKE0721** [comment]
log.pvpgang.com is also Happymod communication.
