### ISSUE TITLE
livelaw.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88430]
***Issue URL (Incorrect Blocking + ADs)***: https://www.livelaw.in/news-updates/delhi-high-court-notice-new-zealand-youtuber-karl-rocks-wife-blacklisting-entering-india-177576

> broken header + advertisement on scroll down and then up .
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/125977768-90ec0f6d-36e4-4fe1-872a-44169dab1257.png)
![image](https://user-images.githubusercontent.com/76880977/125977754-6e81e40c-47a6-4208-90ea-8a5b732a8b10.png)
![image](https://user-images.githubusercontent.com/76880977/125977771-304979e5-2eea-488c-910f-ab552ad76095.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
It seems that incorrect blocking is caused by `Fanboy's Annoyances`, so please add this rule to user filter:
`livelaw.in#@##top`

@ryanbr Could you please take a look?
It looks like that this rule - `bd.com,howtogermany.com,livelaw.in,vpnranks.com###top` breaks header on `livelaw.in`.
