### ISSUE TITLE
ahadns.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88467]
**Issue URL (Ads)** : https://ahadns.com/

ahadns.com###sponsors

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126026623-88df10f7-5157-4b1e-82cc-c4c406d7348d.png)
![image](https://user-images.githubusercontent.com/76880977/126026626-6ba51cfd-9232-4a72-b7ab-f14568e3c393.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
Not an ad.
