### ISSUE TITLE
missed ads in GO Keyboard v2.56 app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#885]
GO Keyboard v2.56

http://forum.adguard.com/showthread.php?7402-Adguard-Mobile-Umbra-s-Feedbacks&p=64650&viewfull=1#post64650

**Comment by Alex-302** [comment]
Answered
Answered on the forum.

**Comment by vgavrish** [comment]
В приложении баннер
http://prntscr.com/c778if
можно его удалить?

**Comment by Alex-302** [comment]
https://forum.adguard.com/index.php?threads/umbras-feedbacks-adguard-mobile.6566/reply&quote=61476
Пусть попробует выключить интернет, остановить это приложение, очистить кэш и проверить снова, без интернета. Рашьше он полностью не удалялся.
