### ISSUE TITLE
https://genshinimpactcalculator.com/genshinCalc header overlap

### ISSUE THREAD

**Issue by NogrTL** [AdguardTeam/AdguardFilters#88532]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:
The block rule `genshinimpactcalculator.com#$##BannerTop { height: 0 !important; }` makes interaction with top part of the website impossible

<details><summary>Screenshot:</summary>
![image](https://i.vgy.me/rpTXX3.png)
</details>

* **Expected behaviour**:
The rule should not make header overlap the main part

<details><summary>Screenshot:</summary>

![image](https://i.vgy.me/nd2uUC.png)
</details>

***Steps to reproduce the problem***:
1. Go To https://genshinimpactcalculator.com/genshinCalc

***System configuration***

**Filters:**
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "easylist",
    "adguard-spyware",
    "adguard-spyware-url",
    "easyprivacy",
    "urlhaus-1",
    "adguard-annoyance",
    "fanboy-cookiemonster",
    "ublock-annoyances",
    "plowe-0",
    "RUS-0"

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Pro 21H1
Operating system version (Android/iOS) | ?
Browser:                               | Microsoft Edge Version 91.0.864.70
AdGuard version:                       | uBlock Origin v1.36.2
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Hi,
Are you sure that it's caused by mentioned rule?
On my side it's caused by a different rule:
`##.adban`
and adding `genshinimpactcalculator.com#@#.adban` to user filter fixes this issue.
