### ISSUE TITLE
conquerbritishenglish.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88550]
**Issue URL (Annoyance)**: https://www.conquerbritishenglish.co.uk/indian-words

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126076612-ab799d67-1543-4281-96ff-dcceaad502b2.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
