### ISSUE TITLE
writtenchinese.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88551]
**Issue URL (Annoyance)**: https://www.writtenchinese.com/how-to-read-chinese-characters-a-beginners-guide/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126077476-c7b737fe-c013-486e-a756-be13cc55624f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Not sure about that.
