### ISSUE TITLE
bullhub.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8856]
**Site**: http://www.bullhub.com/gallery/beautiful-tranny-cock/index.html

**Issue**: Please remove the "X" symbols from the page

**Screenshot**: http://prntscr.com/hrzla9

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Fixed.
