### ISSUE TITLE
bmovies.ru [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8861]
**Site**: https://bmovies.ru/film/heartbeats.0ryo7/r8yrlp

**Issue**: Please remove the fake Stream & Download buttons

**Screenshot**: http://prntscr.com/hs0ndl

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by AdamWr** [comment]
Fixed.
