### ISSUE TITLE
watchonline.to [Fake Link]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8864]
**Site**: https://www.watchonline.to/movie/63259-star-wars-the-last-jedi-2017

**Issue**: Please remove the fake links as seen in the screenshot and also the adblock message

**Screenshot**: http://prntscr.com/hs0yo1

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Site is offline :(

**Comment by BlazDT** [comment]
Adblock detection not reproduced, hid fake links.

**Comment by BlazDT** [comment]
@Nzzyme
Can you still reproduce?

**Comment by AdamWr** [comment]
I can reproduce.
Fixed in Annoyances filter.
