### ISSUE TITLE
spellchecker.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88641]
**Issue URL (Ads)** : https://www.spellchecker.net/misspellings/mendatory

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126201424-90459db1-58d1-4abd-9053-10a60026fd54.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by krystian3w** [comment]
Possible update addon to 3.6.6

**Comment by chirag127** [comment]
> Possible update addon to 3.6.6

Does it make any difference. I don't know why it is not auto-updating.
