### ISSUE TITLE
raftaar.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88644]
**Issue URL (Ads)** : https://shabdkosh.raftaar.in/Meaning-of-MENDATORY-in-Hindi#gsc.tab=0

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126202050-fb05fea1-41ec-4710-addd-386a8127376f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Same site - https://www.raftaar.in/
