### ISSUE TITLE
gomovies.lol [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8865]
**Site**: https://www.gomovies.lol/little-hours-2017-full-movie-watch-online.html

**Issue**: When clicking on the "Ads" tab and then clicking on play / maximize video player shows pop-up. Please fix.

**Screenshot**: http://prntscr.com/hs1dm3

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
www.gomovies.lol unexpectedly closed the connection.

**Comment by Nzzyme** [comment]
Weird. Does not happen here. Are you able to visit the site without any AG product enabled? Can you try with a proxy/VPN? Thanks

**Comment by BlazDT** [comment]
Worked to day without any proxy/VPN.

Fixed.
