### ISSUE TITLE
zenius-i-vanisher.com score tracker broken 

### ISSUE THREAD

**Issue by jxu** [AdguardTeam/AdguardFilters#88661]
https://zenius-i-vanisher.com/v5.2/ddrscoretracker.php?function=enterscore 
requires login

***Description***: ublock origin modifies ##input.fb breaking the button functionality
* **Current behaviour**:  enter score buttons don't show up

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![Screenshot from 2021-07-19 20-40-32](https://user-images.githubusercontent.com/7989982/126244992-22638793-a9c7-48c2-8930-6fa93ea2835a.png)

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![Screenshot from 2021-07-19 20-42-05](https://user-images.githubusercontent.com/7989982/126245094-2abebd7c-3dea-408d-855e-6d4c46a1210d.png)

</details><br/>

***Steps to reproduce the problem***:

Login and go to page

***System configuration***

**Filters:**

AdGuard Social Media

**Comment by Alex-302** [comment]
@jxu Removed bad rule.
