### ISSUE TITLE
https://www.tpbaysproxy.com/ (ios safarai)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88660]
a vpn warning and ad redirect servers when clicking around

||avatroom.com^
|expresvpn-private-analytics.net^
||onlineuserprotector-mobtiz.com^
||vpnoffers.cc^

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.tpbaysproxy.com/)

**Comment by Alex-302** [comment]
Cannot reproduce.
