### ISSUE TITLE
Hongkonger TVB ads (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#88664]
https://news.tvb.com/local/60f6297e335d19d579838506 --> https://img.tvb.com/inews_web/js/videojs.ads.js?t=20210113
... --> https://api.ads.tvb.com/news/ana/config.php?os=web&device=pc&env=prod&lang=en
... --> https://api.ads.tvb.com/news/ad/config?os=web&device=pc&env=prod

TVB tv box --> https://api.ads.tvb.com/mytvs/ad/config?os=web&device=pc&env=prod --> https://adservice.mytvsuper.com/middle.php
... --> https://api.ads.tvb.com/mytvs/ad/smart?os=web&device=pc&env=prod

TVB website tvb.com --> https://img.ads.tvb.com/home/min.js
... --> https://img.ads.tvb.com/ana/gtm/home/min.js

```
ads.tvb.com:
https://api.ads.tvb.com/mytvs/ad/config?os=web&device=pc&env=prod
https://img.ads.tvb.com/home/min.js
https://img.ads.tvb.com/ana/gtm/home/min.js

https://img.tvb.com/inews_web/js/videojs.ads.js?t=20210113
https://adservice.mytvsuper.com/middle.php?bossId=[[bossId]]&deviceId=[[deviceId]]&rdid=[[rdid]]&[[actionKey]]=[[actionValue]]&orderId=[[orderId]]&advertiserId=[[advertiserId]]&vastAdId=[[vastAdId]]&creativeId=[[creativeId]]&assetPath=[[assetPath]]&ecid=[[ecid]]&platform=stb&source=player&destUrl=[[destUrl]]

||img.tvb.com/inews_web/js/videojs.ads.js
||ads.tvb.com^
||adservice.mytvsuper.com^

```

**Comment by jordanelliott23** [comment]
what websit do we use to test

**Comment by c2xusnpq6** [comment]
> what websit do we use to test

> https://www.tvb.com/
> https://news.tvb.com/local/60f6297e335d19d579838506

@jordanelliott23
