### ISSUE TITLE
vexmovies.org [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8866]
**Site**: http://vexmovies.org/mother-krampus

**Issue**: Please remove the fake links as shown in the screenshot.

**Screenshot**: http://prntscr.com/hs1g5k

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Also miner through bag2 request combined with normal elements. But AdGuard detects this miner :)
