### ISSUE TITLE
pussyspace.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88695]
***Issue URL***: https://www.pussyspace.com/vid-3642830-best-fairytail-english-dubbed-porn-animation-compilation-creampie-full-hd/ has ads

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/126337979-96882a3b-3325-46c7-999b-f4178e79cd5e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Yuki2718** [comment]
Looks to be `SysxVkKdsbq.serve` => `https://www.pussyspace.com/js/all.js?v=7739281` => eval, not sure what filter you is preferred.

**Comment by neer9** [comment]
Hmm.... I used to think that I'm the only one who gets confused between
which rules to choose.

**Comment by Yuki2718** [comment]
My fix should work, but won't last long.

**Comment by Alex-302** [comment]
Ads are blocked on my end.

**Comment by neer9** [comment]
Hmm... Then how yuki can reproduce the ads. Or someone fixed it?

**Comment by Yuki2718** [comment]
I fixed as you see.

**Comment by neer9** [comment]
I only see a commit in EnglishFilter/sections/antiadblock.txt

But none in specific filter that's why I was I was asking. Did you forget
to mention the issue while adding rules for this site to remove ads?

**Comment by Yuki2718** [comment]
Somehow the filter is in the wrong file, it should be in general_extension.txt. @Alex-302 
In any case my fix is to address the ads you saw.

**Comment by neer9** [comment]
Ah, that makes sense. I thought if the rule is added to
EnglishFilter/sections/antiadblock.txt then it would be just addressing the
anti-adblock issue only and not removing the ads.

**Comment by Yuki2718** [comment]
antiadblock.txt addresses ad-reinsertion too, but what I addressed is not even ad-reinsertion. IDK why the rule is there.

**Comment by neer9** [comment]
Hmm... antiadblock.txt addresses ad-reinsertion too ? Most of the rules in
it are scriptlets and I don't know what they do as I was not able to
understand the meaning of stack and property in
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#abort-on-property-read
probably I need to learn JavaScript first?
