### ISSUE TITLE
jiocinema.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88704]
**Issue URL (Analytics)** : https://www.jiocinema.com/watch/movies/omg--oh-my-god-/0/0/0_5o783214/0/0

||jiocinema.com/js/utils/analyticsJs-*.js

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126370318-68be0c49-0506-4d92-8550-d50391cdaa3e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
It breaks the site.
