### ISSUE TITLE
Hongkonger i-cable ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#88746]
```
http://news.i-cable.com/ott_api/ads?adsType=2&locale=zh_hk

||news.i-cable.com/ott_api/ads^
```

![Screenshot_20210721-151537_Trebuchet.png](https://user-images.githubusercontent.com/75058881/126447463-ca2c293d-e1b9-4ca8-8139-ad7d1111baca.png)

**Comment by Alex-302** [comment]
Need screenshot of ads.

**Comment by c2xusnpq6** [comment]
tracker: 100% sure
```
||cablenews.i-cable.com/ci/tracking^
```

**Comment by Alex-302** [comment]
What is collected?

**Comment by c2xusnpq6** [comment]
> What is collected?

How long have you watched the ad that will be displayed before the news video

**Comment by Alex-302** [comment]
which app? I need package name.

**Comment by c2xusnpq6** [comment]
> which app? I need package name.

https://play.google.com/store/apps/details?id=com.icable.android.joemud

**Comment by Alex-302** [comment]
I don't see these requests. Need a HAR.
