### ISSUE TITLE
yandex.ru - useful ads missed

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8878]
### Issue URL (Ads)
[https://www.yandex.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.yandex.ru)
### Comment
> В скриншоте пример поиска на сайте yandex.ru по запросу телевизор (фильтр полезной рекламы выключен - не должна быть показана полезная реклама, если я не ошибаюсь) 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://i.imgur.com/rRvcDTe.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://i.imgur.com/VrhJwZB.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://i.imgur.com/2y10BBf.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | iOS
AdGuard version: | 1.3.2
Browser: | Safari
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Experimental,<br>Mobile Ads,<br>Safari,<br>Annoyances

**Comment by Alex-302** [comment]
На iOS не заблокировать. Слишком мудрёный скрипт для борьбы с блокировщиками.
