### ISSUE TITLE
computerbase.de: Please reconsider blocking our Web App Manifest

### ISSUE THREAD

**Issue by steffenweber** [AdguardTeam/AdguardFilters#88782]
We've noticed your commit abda5baa642e847e0d1f88b0879b055b49c1d3fa in which you've started blocking our [Web App Manifest](https://web.dev/add-manifest/) to prevent Google Chrome from showing its standard Progressive Web App (PWA) install prompt.

The commit message mentions a "Chrome Extension install button in address bar". We don't have a "Chrome extension", what you are seeing is just the normal PWA installation button that Chrome displays on all websites that fulfill certain criteria (please see the link above).

Is there anything special about the PWA install button on our site? I don't think so. If you want to block these PWA install buttons then I suggest you go ahead and block `<link rel="manifest">` elements on all sites, not just on a single site because I think that doesn't make sense, seems unfair and confuses users.

**Comment by BlazDT** [comment]
Did not find other German site I know which is using that Annoyance. Else I would have blocked it for every page.

Why implement such thing in the first place? It clutters address bar.

**Comment by AdamWr** [comment]
As far as I know, we already have a rule to block it on all websites (except these on which it was causing problems), but only for mobile platforms.

https://github.com/AdguardTeam/AdguardFilters/blob/abda5baa642e847e0d1f88b0879b055b49c1d3fa/AnnoyancesFilter/sections/mobile-app.txt#L1173-L1177

**Comment by BlazDT** [comment]
$$ rules do not work in Chrome extension while url block rule does.

**Comment by steffenweber** [comment]
Using a Web App Manifest allows users to install your website as an app on their homescreen (on desktop as well as on mobile platforms). This is a feature that helps the web compete with native apps. Instead of spending money on the development and maintenance of native apps (that you'd have to submit to an app store) you can spend your time improving the web experience for everyone and those of your users who prefer a native app-like experience (homescreen icon, separate window, …) can install your website / web app. I think the button in the address bar of desktop browsers is a very unobtrusive way to inform users about this possibility.

A few examples of other sites that are using this feature:

https://developers.google.com/
https://devdocs.io/
https://twitter.com/
https://xenforo.com/community/
https://www.hardwareluxx.de/community/
https://extreme.pcgameshardware.de/

**Comment by BlazDT** [comment]
Thanks for the explanation.
@AdamWr 
Html tag is not removed, so I guess push elements if wanted should still work when manifest.json is blocked.

**Comment by AdamWr** [comment]
Unfortunately I'm not sure what exactly a push elements do you mean.
To be honest, for me this PWA install prompt is not annoying on desktop (it's just small icon on an address bar), unlike on mobile where it's a popup which hide part of the content.
So in my opinion we could unblock it on desktop platforms.

**Comment by BlazDT** [comment]
I meant the push elements broken which are discussed in linked thread of generic mobile rule.

@AdguardTeam/filters-maintainers what do you think? Address bar clutter annoying too much for filter list (at least it is to me)?

**Comment by Alex-302** [comment]
@steffenweber Annoyances filter is not enabled by default, and blocking various popups - one of purposes of this filter.

**Comment by steffenweber** [comment]
Is anybody still reading this issue or should I file a new one?

What you were seeing was a bug in Chrome that has now been fixed in Chrome 93.0.4577.82 which is being rolled-out to users since a few days. Please see https://bugs.chromium.org/p/chromium/issues/detail?id=1234856 (and https://twitter.com/steffenweber/status/1421039085590917121).

Can you please revert this change now?

**Comment by Alex-302** [comment]
Hi. I don't see that request now.
