### ISSUE TITLE
Domains that need to be updated.

### ISSUE THREAD

**Issue by duryytt** [AdguardTeam/AdguardFilters#88809]
These are sites that change domain names. Please replace the old names with new ones.

| **Old domain**  | **New domain** |
| ------------- | ------------- |
| hepfullfilmizle1.com | bayfilmizle.com
| fullfilmizle.pw  | fullfilmizle.vip  |
| setfilmizle.live | setfilmizlee.com
| filmizletv.net | filmizletv.pw
| balfilmizle.com | balfilmizlet.com

**Comment by zloyden** [comment]
Removed most of the sites from our filters - they don't have enough visitors.
