### ISSUE TITLE
puremovie.xyz

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88817]
**Issue URL (Ads)** : https://www.puremovie.xyz/2020/12/download-crown-season-1-4-dual-audio.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126593222-15cf76ce-d45c-48c1-9542-07d91d81a6c5.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Too few visitors.
