### ISSUE TITLE
toxicmoviecounter.co

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88816]
**Issue URL (Ads+annoyance)** : https://www.toxicmoviecounter.co/2021/01/The-Crown-Season%201%204.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126593057-9b4fea4f-a289-4b8d-9829-f644901a1330.png)
![image](https://user-images.githubusercontent.com/76880977/126593058-351114e8-80fb-49f4-946f-3e0c2be2184f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
No visitors.
