### ISSUE TITLE
dropmefiles.com

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#88832]
При нажатии на "скачать все" ничего не происходит + виджеты социальных сетей. https://dropmefiles.com/coGmK

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/126641568-5aeb4a6b-82b6-4d48-802a-6f2f69ab8a25.png)
</details><br/>

**Comment by gork7777** [comment]
Which filter do you use? I can download the file, no problem for me.

**Comment by zubrRB** [comment]
My settings https://github.com/AdguardTeam/AdguardFilters/issues/87497
