### ISSUE TITLE
woodbrass.com unblocked CNAME tracker and breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#88848]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 

CNAME tracker and unblocked cookie banner Background

`https://woodbrass.com/`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

Unblocked Cookie banner Background:
<img width="417" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/126680769-48c56c33-d377-4e15-9aee-8aab478eb67f.PNG">

CNAME tracker. The original tracking Domain is `dataunlocker.com`
<img width="746" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/126680924-eb67b118-401c-47b7-b7b4-9991293ee901.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | firefox developer
AdGuard version:                       | 3.6.6
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by chirag127** [comment]
> `hhttps://woodbrass.com/`

By the way, there is a extra h before the url.

**Comment by JobcenterTycoon** [comment]
i removed the extra h

**Comment by JobcenterTycoon** [comment]
@Alex-302 this issue got fixed here https://github.com/AdguardTeam/cname-trackers/issues/15 so the domain `1bw7etm93lf.www.woodbrass.com` is duplicate now so your entry can be removed
