### ISSUE TITLE
Whitelist Google Browse By Name - AdGuard URL Tracking Protection

### ISSUE THREAD

**Issue by corobin** [AdguardTeam/AdguardFilters#88862]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

The URL Tracking Protection list has a filter that removes sourceid:

`||google.*/search$removeparam=sourceid`

However, `sourceid` is a wanted parameter for Google's Browse By Name search: https://www.squarefree.com/2004/09/09/googles-browse-by-name-in-firefox/

Browse by name requires these two parameter and value pair *exactly*:

`&sourceid=navclient&gfns=1`

* **Expected behaviour**: 

Please add a whitelist for Google Browse By Name so that sourceid is not removed when used for this

***Steps to reproduce the problem***:

1. enable AdGuard URL Tracking Protection
2. try to use Browse By Name search

***System configuration***

**Filters:** 

Adguard URL Tracking Protection

Information                            | Value
---                                    | ---
Operating system:                      | All
Operating system version (Android/iOS) | All
Browser:                               | All
AdGuard version:                       | All
Filters enabled:                       | Adguard URL Tracking Protection
AdGuard mode (Android only):           | n/a
Filtering quality (Android only):      | n/a
HTTPS filtering (Android only):        | n/a
Simplified filters (iOS only)          | n/a
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | n/a
Helpdesk ID (if exists):               | n/a

**Comment by BlazDT** [comment]
That option by Google is not shown to me, just normal search and feeling lucky. How to reproduce? Copying linked google.com is not searching for me after adding a name for q parameter.

**Comment by Alex-302** [comment]
I see this parameter when searching
![image](https://user-images.githubusercontent.com/8361299/126848071-fb516b86-6e92-4b53-9a7e-7339b48d55cf.png)
Value does not contain interesting info, but nothing is broken.

**Comment by corobin** [comment]
> That option by Google is not shown to me, just normal search and feeling lucky. How to reproduce? Copying linked google.com is not searching for me after adding a name for q parameter.

What do you mean? The blog I linked explains it: https://www.squarefree.com/2004/09/09/googles-browse-by-name-in-firefox/

it is triggered with these two parameter and value pairs:

`&sourceid=navclient`

`gfns=1`

the filter currently filters out `sourceid` which breaks the function

**Comment by corobin** [comment]
on the current version of the filterlist I still see only 1 occurrence of `sourceid` in this rule `||google.*/search$removeparam=sourceid` and no occurrence of `gfns`

```
! Checksum: qGEmVpdwLJ9YCkLKQyVrCQ
! Title: AdGuard URL Tracking filter
! Description: Filter that enhances privacy by removing tracking parameters from URLs.
! Version: 2.0.0.73
! TimeUpdated: 2021-08-05T13:30:47+00:00
```

if this is a wontfix, `||google.*/search$removeparam=sourceid,badfilter` can be put in custom filters to deactivate this rule entirely

any suggestions for a more precise rule that _only_ whitelists `&sourceid=navclient&gfns=1` on google would be much appreciated, i'm not sure if it's possible to filter out a parameter except if it contains one very specific value, or maybe even only if it contains one specific value _and_ appears in conjunction with another parameter/value). thanks!
