### ISSUE TITLE
elastic beanstalk analytics

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88864]
||siteanalytics.*.elasticbeanstalk.com^

if you go to: siteanalytics.whatcounts.com you will see it reach out to the elastic beanstalk analytics.

**Comment by jordanelliott23** [comment]
||siteanalytics.whatcounts.com^ can also be added. what counts is a marketing platform and thats the analytics subdomain

**Comment by zloyden** [comment]
Can you provide URLs on which `the analytics` is used?


> if you go to: siteanalytics.whatcounts.com you will see it reach out to the elastic beanstalk analytics.

Not opened on my end.

**Comment by Alex-302** [comment]
100% analytics.


> Not opened on my end.

need spesific URL.
@jordanelliott23 could you please provide URL or where we can check?

**Comment by zloyden** [comment]
@Alex-302 if you are sure of something, block it otherwise without specific urls it is doubtful.
