### ISSUE TITLE
vedantu.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88886]
**Issue URL (Annoyance)**: https://www.vedantu.com/question-answer/define-average-value-of-ac-over-half-a-cycle-class-12-physics-cbse-5fd9b0417dd0d60c2b0e82fc

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126766452-9bbdb521-88ba-468c-b3da-c5b2944ab1cc.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.

**Comment by chirag127** [comment]
well, I checked it have more than 26.5 Million monthly visitors.

**Comment by zloyden** [comment]
Yes, I fixed it.
