### ISSUE TITLE
psychologies.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88908]
**Issue URL (Ads)** : https://www.psychologies.com/Couple/Problemes-sexuels

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126790160-2deeb543-7d12-4386-9fe9-5cdf1511eb3e.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by AdamWr** [comment]
Please enable `AdGuard French filter`.
