### ISSUE TITLE
playfulpromises.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88912]
**Issue URL (Annoyance)**: https://www.playfulpromises.com/

<details><summary>Screenshots:</summary>

https://www.playfulpromises.com/
![image](https://user-images.githubusercontent.com/76880977/126790766-def30ca1-67d8-4a9f-b0e4-1d7636bde334.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
I don't think that we should block it. There is useful information, but removed cookies.
