### ISSUE TITLE
effetdesoi.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88916]
**Issue URL (Annoyance)**:
https://www.effetdesoi.com/

<details><summary>Screenshots:</summary>

https://www.effetdesoi.com/
![image](https://user-images.githubusercontent.com/76880977/126796220-fd2a799d-9be5-4789-9977-efaf28a4bc68.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
