### ISSUE TITLE
exquise.fr

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88915]
**Issue URL (Annoyance)**: http://exquise.fr/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126796328-bf82a933-d6b7-49ad-8546-c5392734b4c9.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
