### ISSUE TITLE
yahoo.com (Broken page layout)

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardFilters#8893]
***Description***: Happens rarely with Yahoo.com and usually gets fixed with a page refresh.
* **Current behaviour**: Deleting the top banner sometimes breaks the page layout

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33634917/34351238-13c2f352-ea24-11e7-9f01-8f03d6a78314.png)
)
</details><br/>

* **Expected behaviour**: As shown on screenshot

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33634917/34351256-2320ce6e-ea24-11e7-9360-05580dafcc33.png)
)
</details><br/>

***Steps to reproduce the problem***:

Go to Yahoo.com. The bug seems to be intermittent, might take up to 10 page loads to reveal it. 

***System configuration***

**Filters:** English, Spyware, Social, Search ads & Self-promotion

Information                            | Value
---                                    | ---
Operating system:                      | Microsoft Windows 7 SP1
Operating system version (Android/iOS) | ?
Browser:                               | Internet Explorer 11
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Spyware, Social, Search ads & Self-promotion
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block third-party cookies(30), Block Location API, Remove X-Client-Data Header, Strip URL, Hide Search Queries, Send DNT, Remove Referrers from 3rd Party Requests, Block 3rd Party Authorization
Helpdesk ID (if exists):               | 1389397

**Comment by Alex-302** [comment]
added
```
yahoo.com###my-adsLDRB
```
