### ISSUE TITLE
pussyspace.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88940]
***Issue URL(INCORRECT BLOCKING)***: https://www.pussyspace.com/live/ms_seductive/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/126831250-cfc0f2a5-64fd-4b46-b046-f3c1236be44e.png)
![image](https://user-images.githubusercontent.com/82926303/126831254-fd0bf206-f915-4260-9f15-f73d13debe5f.png)

</details><br/>

<details><summary>System configuration
:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
</details><br/>

**Comment by Alex-302** [comment]
Not reproduced.
