### ISSUE TITLE
letmejerk.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88951]
**Issue URL (Ads)** : https://www.letmejerk.com/play/456476/hentai-xxx-ample-weenie-taut-cunny-english-dubbed.html

> click on the images takes me to 
![image](https://user-images.githubusercontent.com/82926303/126835005-da7f4185-8fae-4609-aded-2869eb48e1b8.png)

<details><summary>Screenshots:</summary>

https://www.letmejerk.com/play/456476/hentai-xxx-ample-weenie-taut-cunny-english-dubbed.html
![image](https://user-images.githubusercontent.com/82926303/126835035-01050e7f-86c3-4f98-a4a4-e5cd4cbebd85.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment]
@AdamWr Script filter to be replaced with scriptlet: `
letmejerk.com#%#(function(){var b=window.addEventListener;window.addEventListener=function(c,a,d){if(a&&-1==a.toString().indexOf("exoJsPop"))return b(c,a,d)}.bind(window)})();`

**Comment by AdamWr** [comment]
It seems that this rule is obsolete, so I have removed it.
