### ISSUE TITLE
hentaihaven.red

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88956]
**Issue URL (Annoyance| Anti adblock script)** : https://hentaihaven.red/hentai/soshite-watashi-wa-ojisan-ni-episode-1-english-subbed/

<details><summary>Screenshots:</summary>

https://hentaihaven.red/hentai/soshite-watashi-wa-ojisan-ni-episode-1-english-subbed/
![image](https://user-images.githubusercontent.com/82926303/126836297-4c134b2e-6f2e-40a9-a274-dd7224822057.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
I'm also blocking ads at dns level using NextDNS Ads & Trackers Blocklist
,AdGuard DNS filter and oisd.

</details><br/>

**Comment by neer9** [comment]
@Yuki2718 

I'm also blocking ads at dns level using NextDNS Ads & Trackers Blocklist
,AdGuard DNS filter and oisd. can this be due to that?

**Comment by Yuki2718** [comment]
@neer9 That's very likely. Additional fix can be added but I'm reluctant to investigate issues I can't reproduce deeper. Just wait for other members' review.

**Comment by Yuki2718** [comment]
Why closed? As I said, other members will review later. What you experienced can occur to other user, for example if DNS filtering is enabled.

**Comment by neer9** [comment]
> Why closed

I myself can not reproduce it without dns blocking. I don't want to get rebuked also by the members for reporting this.
