### ISSUE TITLE
lumendatabase.org

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88964]
**Issue URL (Annoyance)** : https://lumendatabase.org/notices/22330318

> I have read this pop up many times But it keeps coming.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/126838313-604c71f3-0bfb-4d16-a982-9caeffce8173.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
I don't think we should block this popup, but you can add `lumendatabase.org##.first-time-visitor` to the User rules.
