### ISSUE TITLE
xanimehub.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88962]
**Issue URL (Ads + Anti-Adblock script)** : https://xanimehub.com/high-school-best-porn-anime-hentai-scenes-seasons-1-4-english-dubbed/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/126838056-fe366f5e-b429-4914-820f-26e61e7937df.png)
![image](https://user-images.githubusercontent.com/82926303/126838055-9edc50a2-bbc8-4b43-a928-f0aa9f296934.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment]
Specific social filters may be needed for CB so I keep this opened.

**Comment by neer9** [comment]
> Specific social filters may be needed for CB so I keep this opened.

What does CB mean?

**Comment by Yuki2718** [comment]
> 
> What does CB mean?

Contents Blocker

**Comment by zloyden** [comment]
I don't see adblock detection, also removed some ads.
