### ISSUE TITLE
hentaidude.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88960]
**Issue URL (Ads)** : https://hentaidude.com/garden-episode-1/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/126837615-fa0b56d2-1379-46ab-83e7-5eff6705f7e1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment]
@Alex-302 
The site pretends to be dead if accessed from Japan, which can be fixed by `||hentaidude.com/wp-admin/admin-ajax.php?action=geocheck$xmlhttprequest,redirect=nooptext` but should it be added to Annoyances or Base?

**Comment by neer9** [comment]
Does Japan also blocks NSFW sites?

**Comment by neer9** [comment]
> The site pretends to be dead if accessed from Japan

Why this site pretend it?

**Comment by Alex-302** [comment]
@Yuki2718 Added to Annoyances.

**Comment by Yuki2718** [comment]
> Why this site pretend it?

Maybe due to copyright infringement, I don't know.

**Comment by chirag127** [comment]
> Why this site pretend it?

I googled it and found this
![image](https://user-images.githubusercontent.com/76880977/126974882-1e292ad0-eb02-405e-9f1d-e52e7b64d232.png)
on https://theconversation.com/the-web-really-isnt-worldwide-every-country-has-different-access-106739#:~:text=Users%20from%20certain%20countries%20can,decision%20to%20deny%20them%20access.&text=Media%20sites%20might%20not%20be,with%20other%20nations'%20privacy%20laws.
