### ISSUE TITLE
electricabout-dictionary.top

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#88966]
**Issue URL (Fraud domain)** : https://z08kcqt.electricabout-dictionary.top/rabimmdq/?u=tqck80z&o=zdqr96x&t=dropSHLAK&cid=2a7o2b0jlcrue&f=1&sid=t4~iyt10p1qt351w1noq5g3tpgf&fp=rFMf%2BSRgXo7efrKkXmWPJpoQU94umht1Ls5YUNUGEY9jC9c1ncgMpYXpuPHiIKIlddpAF8t10znMRxyGQspUpECDVMAV0G8CTePjizL4fLF1PvNcRzpca7SXlQ7TRHNHj10EHiZDyVIR15KKMENjC6hCPMExTkvWAPXd3QWJ%2BJTI%2F7nYtpoUO1m56rYekQkNgZE3bUtBwL94qnQk2PezHXayf%2B0hLxcNZQw2mOOC%2FoAr3h03VHNC1teCiW7GKt4o1PmOf19gHJJ45YotBt5g2OCuTQb5HYVJFbOqHB2rrbEtCXH%2FegyBBLZDypOnT2Z18qn5%2B8SPa4POPBQsjZF1PH9nP%2FChvzKGqltFk2IxheqcJY9YxPZvQyo77sW6Qfzq2yjDK5%2FF01rPoLDuVqewnk1onwZcqoDmZpKZyD8Hxx3Znm1ZmyNGyz%2BL2Hj1PqOrfUvvo0C5qtpUp6CROeNVGsznkOV3ZB2CDFim%2FJ1%2B072jK4Ixv4i411kP73%2BjDw4Y7oCEnUxYT0kMmBBiGsdiL360kV%2FqbrOTdfFT0f3udlEPDcDKm0lpOMLZFkm4KmEfgzleTx30C92juYMVU8Uwp%2FljKZ8hhCffFLaWCQc557gpKKBUVhPhheNZj8BI9gHpc5%2FlEf4KDtIAVlry6BWLDxLCZks%2Bh088QXQUnIaGHTq3VPKr64kW8RI3sn2eAEU3rWyIsjcjEFvAu8e1XRV0IVKICHuzXz%2FMGRcgSezLGLKRj4hwC2IS1zrt26X47pOi%2F1PaSiRcuWpy%2Bw90PmBWYMGnfBEda2nTn5r1eZe8QSTlNkOoV7d%2Fo97YxygjR2n591XeMGYMAQ1VNgl6bgupefDb2rxsN4EnL6GY0MNS%2Bg5pLUCOfy8FUQsDQxlcn7UNGoo501y3x4n9kva%2B25RlERBMWPXyuHeX9m2nGZYRB4M382%2FF0Pvnhiqsu6aHlspibr%2BxT%2F62tiWi99qzfFNkUtrHVfzMQc5mWjMG6H4u9VMqhS2Z8n8VUOrjVM%2BNyIU0b4VDnwntiIuSYr7ANWyYrRHFobyONcFUqhFtGevGXVHcZJlOFnPqCENhKesvJxVYa%2FYn%2Bcrcnq1mlG4Nqncr4sSaNgdfcMwUSh%2FpWh9YxEUdkbjNa8zFtCMiWL74ZmVUAG%2BbAlOyJ4b25FOrJNzHgKYAvWTWOugdJTTvs5%2BAfRx0JzsqyvP5XcPw%2BaIpCghKRhRZufYHYZgWkoY0EWJrNo2nH0aUv1hYBKEfxWqHVsEl%2BXtLusAT2k%2FJB%2F7f8n4c7UWTUONeqlQ8qDuzvph7gWN1WqDMe2lDBuq6KW2vjTH46TZTDdN6lKNPDUWA6jSNbKnvHAoEPZzlUee5mQfeCRyPxkTp0JYGH6mmo7hO0KO2zqJUL82ax%2FYonaSzozDVpDeIBYtgwwtMIesPTeeJkp01UEdIyUHueHUORCdFIK075cqPWCHI2XBhGqPhrYnO7TL1yjzeCfuRukJkN6JIWz8Xt8%2F9p53XLqHkvW53P1eOdAq9%2Fk2yrNW3encShgePzNs8wLqHrIkaef%2BUbVo%2F63PV60qtHz3rFdsiAeSsOzkJvOZlg86aNTiDHuw8NIwohSQOkuC0eQynASLOZ7aSDZsz%2BzSBhOwsqldeRpgxOR%2FITqSpPGOV%2FXhkoLMcA3CMLmat80pUT98vhV0emiTgCTzkZJszYIVUpHr4Hq%2FTcUBBiMcMPJNuSqESHWAWYD0wYtcC4%2FOc76L%2BiUyrmj5%2Fmty4GsplnukSo6ZTE7hD97zGvGpGxY3igtfI3DZozHaGg48%2B%2BraypdJUI45pzLtPe7WttOt0IkhYhYURyJC9cPz5pt9KJHzgtJvSo0Tp2JvhcVSDMMEo4Rxu0VHmP6VB01C%2FL1s516y9ItTtHkoSsASNCTxG15BpGlyo8TyFmdokTLqMLRGyYdZpSBA7J6mBe%2Fqy1ETMLQ82MO4SZ0A6baQ8XnEDFauoWyx5QSOxx6VI158Uxny3Aw5QQDIPqa4tvkdz8wiNpO1z2wjXoT5kcCZZrjeuTGt%2FHv94yNgHniL0sQgM%2BgStAnvEYxXH%2B4SJzJvvu3Aik1sjOmcMaLlJRZAY61xq%2F9%2BWpTtPHvIEdzpH

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
What's wrong?
