### ISSUE TITLE
Analytics.freetubeapp.io

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#88978]
**Issue URL (Incorrect Blocking)**: https://analytics.freetubeapp.io/

> Website is broken because of the shown rule.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126844263-dd5e0528-0d79-4e37-8523-06aff5a8e885.png)
![image](https://user-images.githubusercontent.com/76880977/126844265-3fafcc35-e943-4525-8132-7fe3070176ad.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by jordanelliott23** [comment]
why? analytics are analytics.

**Comment by chirag127** [comment]
analytics.google.com # just a domain for Google Analytics but not used for tracking itself .
analytics.twitter.com # just show analytics about my tweet like how many people see my tweet.

So, not every domain like this is itself used for tracking the users.
