### ISSUE TITLE
policiesforyou.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#88981]
||javoyynu.xyz^
||adshares.net^
||surveillance.sia.tech^

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://policiesforyou.com/archives/8844#clickimage)

**Comment by Sergey-Lyapin** [comment]
Hello @jordanelliott23
I don't see these requests there, please describe how to reproduce them

**Comment by jordanelliott23** [comment]
maybe they are just not blocked on ios

**Comment by Sergey-Lyapin** [comment]
I found `||javoyynu.xyz^` only
