### ISSUE TITLE
Opera news feed - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#8903]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: AdGuard misses ads in the Opera news feed.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/34354971-c860ecd6-ea3a-11e7-96c0-b678f58bd806.png)

![image](https://user-images.githubusercontent.com/15856304/34355067-6119e0a4-ea3b-11e7-9a66-ebf397fcd72e.png)

</details><br/>

***Steps to reproduce the problem***:

No specific steps, just install opera, head to the news feed, ads should be there

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 6.0.1
Browser:                               | Opera
AdGuard version:                       | 176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (Default) 
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1441641

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
@Alex-302 

![image](https://user-images.githubusercontent.com/15856304/34412050-7271cdfe-ebe3-11e7-82a3-5cdbe0cf1956.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG нужен HAR, записанный после остановки приложения. У меня там только новости.
