### ISSUE TITLE
gdtot.me

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89043]
**Issue URL (Annoyance)**: https://new.gdtot.me/file/2530900247

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126869921-2b657645-717e-463b-b0f2-8bd680a63ec1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
What is wrong?
