### ISSUE TITLE
wapbestmovie.biz [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8907]
**Site**: http://wapbestmovie.biz/2016/Full_Movies/Bollywood_Movies_2017/Tiger%20Zinda%20Hai%20Pdvd

**Issue**: Please remove the fake links as shown in the screenshot.

**Screenshot**: http://prntscr.com/hsf0d5

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by Alex-302** [comment]
can't open this site
