### ISSUE TITLE
robtex.com [False Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8909]
**Site**: https://www.robtex.com/dashboard

**Issue**: Clicking on the "Google" link on the page does not open the Google account login window. This happens because of the rule added in the Social Media Filter:

`||apis.google.com/js/platform.js$third-party`

Please check and unblock if necessary.

**Screenshot**: Sorry, could not take at the moment.

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by Alex-302** [comment]
try
```
@@||apis.google.com/js/platform.js$domain=robtex.com
```

**Comment by Nzzyme** [comment]
Works, but after sometime, I am seeing a message (http://prntscr.com/hsqsfp) This happens when I navigate to another tab and come back.

**Comment by Alex-302** [comment]
Does it happens without AdGuard?

**Comment by Nzzyme** [comment]
I think the issue is resolved. I am not seeing the issue anymore.

**Comment by Nzzyme** [comment]
Issue again surfaced. Unable to open Google login window. Please check
