### ISSUE TITLE
pandora (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#89105]
||stats-proto.pandora.com^

https://apps.apple.com/us/app/pandora-music-podcasts/id284035177

**Comment by Sergey-Lyapin** [comment]
@jordanelliott23
Hello, did you try to use this app with `||stats-proto.pandora.com^`? Does it break anything?
(I can't install this app because it requires ios 13.0 or later)

**Comment by jordanelliott23** [comment]
yes i was listening to music fine with it
