### ISSUE TITLE
mealob.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89103]
**Issue URL (Annoyance)**: https://www.mkvcinemas.in/?aa8266cad2=U3VwOEYrclNhTTlTUzBtMk5wSiswb0VZbTcxYWppeDhpa0NtS0MrbXAydjZxZkY4aGhobUM0eWtMenlwWit1VkltRzZpYk1lQU5ZTXBEK1prYk5uc3lVVEd5NGR1TkJuVXpHdkNRMmJNVlU9

> Please wait timer annoyance after clicking verify you are human 

> I had reached to the link from https://www.mkvcinemas.in/series/maharani-s01-2021-sony-web-series-hindi-webrip-all-episodes-130mb-480p-400mb-720p-1gb-1080p-mkv-f/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126892796-c5b51d84-2ae3-446a-9f6b-2d13190d706d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
They have a server-side check, so there is no way to solve it otherwise you'll get an error.
