### ISSUE TITLE
adventurousmiriam.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#89135]
**Issue URL (Annoyance)** : https://adventurousmiriam.com/10-weird-laws-singapore-get-trouble/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/126898651-f6bf8a6d-a4cf-435f-acc0-a7c92ff329a3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Not an issue.
