### ISSUE TITLE
Segment user groups

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#89143]
Subdivide Chinese language users (and Russian... language users?). For example, users in Hong Kong and Taiwan will not use Weibo and Baidu apps from mainland China. For mobile devices, continuing to subdivide the Chinese language block list is expected to improve the battery life of the device

**Comment by c2xusnpq6** [comment]
Chinese users
    \__ Mainlander
    \__ Taiwanese
    \__ Hongkonger
    \__ Macanese
    \__ Overseas Chinese
        \__ ...

**Comment by Alex-302** [comment]
No need to do it.
