### ISSUE TITLE
www.amazon.* AdGuard URL-Tracking filtering error

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#89163]
***Steps to reproduce the problem***:
When you want try to chat with customer support, it fails. It will reload the contact us page instead of starting a chat.

Affected rule: `||www.amazon.*/message-us$removeparam=origRef`

1. Browse https://www.amazon.de/gp/help/customer/contact-us (Log-In)
2. click on Chat now. Don't worry, you'll chat with a Bot, not a human
<details><summary>Screenshot:</summary>

![ama3](https://user-images.githubusercontent.com/6276915/126910560-b61fd99d-c4eb-426d-8c50-328767819c58.png)

</details><br/>

3. a tiny window opens which is supposed to be the chat window. Instead the contact us page will load again
4. When disable this rule, the chat starts fine
5. Be aware, if you close the chat, the "chat now" button will turn into "continue chat".  When you enable back the rule and "continue chat", it will work without issue. So to reproduce the issue, you have to bring the chatbot to an end and start a new chat.

<details><summary>Screenshot-1:</summary>

![ama1](https://user-images.githubusercontent.com/6276915/126910512-1081fed7-b327-4a1f-bb76-f666a842d0da.png)

</details><br/>

<details><summary>Screenshot-2:</summary>

![ama2](https://user-images.githubusercontent.com/6276915/126910517-6c90d4fc-cac6-44fb-b59f-fdd2e62dc1c5.png)

</details><br/>

`origRef=de_poc` seems to be relevant for the chat to transfer to a german agent.

**Comment by BlazDT** [comment]
When I tested it works (likely due to English interface of mine).
