### ISSUE TITLE
goticapastel.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#89172]
[https://www.goticapastel.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.goticapastel.com.br/)

Newsletter and cookie annoyances:

![cookies](https://user-images.githubusercontent.com/35470489/126914516-97e08310-ada1-4665-b6ab-a9179dcf32c6.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Sergey-Lyapin** [comment]
This site has not enough visitors.
