### ISSUE TITLE
Would Azerbaijani-language entries fit better in AdGuard Turkish than in AdGuard Base?

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#89227]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I've seen Wikipedians claim that Turkish and Azeri are highly mutually intelligible, to the point where it could be considered if the entries in the link/embed below could've been moved from AdGuard Base to AdGuard Turkish, to help reduce filesizes for non-Turkic AdGuard/uBO users (as the move would've involved some 450 entries):

https://github.com/AdguardTeam/AdguardFilters/blob/3271a98e78196ac51c9de63dee04e4b5b6762004/EnglishFilter/sections/foreign.txt#L423-L899

### Proposed Solution

Explained in the problem description.

### Alternatives Considered

None that I'm currently aware of.

### Additional Information

Furthermore, entries from the Taiwan paragraph could be moved to AdGuard Chinese, presuming that the list is meant to be about Chinese-*language* sites:

https://github.com/AdguardTeam/AdguardFilters/blob/3271a98e78196ac51c9de63dee04e4b5b6762004/EnglishFilter/sections/foreign.txt#L7839-L8067

On much less important notes, the Romanian and Moldov(i)an paragraphs could be combined, the 3 Mexican entries could be moved to AdGuard Spanish, and the 20-ish non-whitelisting French entries could be moved to AdGuard French.

**Comment by Alex-302** [comment]
Turks and Azerbaijanis understand each other without problems. It is not a problem if some Turkish sites with AZ lang are in Turkish filter.

**Comment by Alex-302** [comment]
Will move TW to CN.
