### ISSUE TITLE
itnijs.frl (N: uBlock Origin) (T: Ads)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#89239]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

What seems to be various ads. I propose adding these to AdGuard Dutch:
```
itnijs.frl##.last.widget
itnijs.frl##.widget-5 > .banner
itnijs.frl##.attachment-full.alignnone
```

The site is technically in West Frisian, an official minority language of The Netherlands.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/127031631-4bdb50e0-2ae4-41ac-a18d-97786a5b90f4.png)
</details><br/>

* **Expected behaviour**: 

The ads are removed, provided they do indeed count as ads.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/127031527-4c8f9e66-f838-41d2-9e9c-a692d0890527.png)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/127031688-aefed22a-467f-4897-916c-2c9e1168f10b.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 21H1 x64
Browser:                               | Chrome 92.0.4515.107 x64
AdGuard version:                       | uBO 1.37.1b1 + IDCAC 3.3.1
Filters enabled:                       | See above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ok, added. 
Please hide image with filters under `details` tag(I guess you use saved template).

**Comment by DandelionSprout** [comment]
Oh, okay. According to the old template, there was no mandation for filter screenshots to be hid under \<details\>, but I am more than willing to do so if it's mandated in the new template.
