### ISSUE TITLE
apple ad domain

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#89247]
found this in my log dont know where it came from.

||proxy-skadnetwork.apple.com^

**Comment by Alex-302** [comment]
Cannot find any info about this domain.

**Comment by jordanelliott23** [comment]
SKAdNetwork is an aggregate method for measuring attribution of mobile ad campaigns for iOS apps

https://www.admonsters.com/what-is-skadnetwork/

@Alex-302

**Comment by jordanelliott23** [comment]
i just found it in another app but now its not showing in log lol

**Comment by Alex-302** [comment]
Which app(s) uses it?
