### ISSUE TITLE
aktutor.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89276]
**Issue URL (Ads)** : https://www.aktutor.in/quantum-series/b-tech-1st-year-quantum/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127121807-8d7c5045-daba-465f-9d42-e9ce47d1b2ca.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
5520 visitors/month

**Comment by chirag127** [comment]
@Sergey-Lyapin 

Okay, this sites Seems to have random class names. Can you please tell me the user filter?

**Comment by Sergey-Lyapin** [comment]
@chirag127
this rule should be ok:
`aktutor.in###custom_html-2`
