### ISSUE TITLE
stateofdigital.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89288]
**Issue URL (Annoyance)**: https://www.stateofdigital.com/isp-level-ad-blocking/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127147847-7b47bf17-70be-4685-ab5c-a09f1034178a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
18600 visitors/month
