### ISSUE TITLE
sohu.com

### ISSUE THREAD

**Issue by shenzhiming88** [AdguardTeam/AdguardFilters#89289]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Unexpected gaps

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/66902050/126960545-29c9b1c6-4fdf-4b1a-98d0-f04061c979cf.png)

</details><br/>

* **Expected behaviour**: 

There should be no gaps

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
Open address `https://www.sohu.com/a/479629395_260616`

***System configuration***

No need

**Filters:**
![image](https://user-images.githubusercontent.com/66902050/126786614-feac6ab4-324b-4902-8cc5-9388c96da462.png)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 21H1 19043.1110
Browser:                               | Microsoft Edge 92.0.902.55
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

ref:https://github.com/easylist/easylistchina/issues/43

**Comment by Alex-302** [comment]
@shenzhiming88 Next time please add filters list as text or hide uder `<details>` tag (I hope you use copy-pasted template).

**Comment by shenzhiming88** [comment]
> @shenzhiming88 Next time please add filters list as text or hide uder `<details>` tag (I hope you use copy-pasted template).

Fine. Thanks.
