### ISSUE TITLE
unblockproject.casa

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89314]
**Issue URL (Ads)** : https://tamilmv.unblockproject.casa/index.php?/forums/forum/92-post-share-here/&page=95

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127184361-83e41b5c-5e2a-4296-86b3-2891869b6dd1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website doesn't have enough visitors, but removed some adservers.
