### ISSUE TITLE
www.msn.cn

### ISSUE THREAD

**Issue by shenzhiming88** [AdguardTeam/AdguardFilters#89358]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

Gaps created after ad filtering

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/66902050/127163119-d7f77a05-52e2-454b-910d-855d76633c34.png)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

No gaps should be created here

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

- Download and use the Microsoft Edge browser (only reproducible in this browser)

- Open link `https://www.msn.cn/zh-cn/money/news/%E5%8F%B0%E9%A3%8E-%E7%83%9F%E8%8A%B1-%E7%99%BB%E9%99%86%E5%8D%8A%E5%B0%8F%E6%97%B6%E5%89%8D-%E4%B8%8A%E6%B5%B7%E5%B7%B2%E5%AE%89%E5%85%A8%E8%BD%AC%E7%A7%BB36%E4%B8%87%E4%BA%BA-%E6%97%A0%E4%BA%BA%E5%91%98%E4%BC%A4%E4%BA%A1/ar-AAMwKy8?ocid=winp1taskbar`

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

<details>

uBlock filters

uBlock filters – Badware risks

uBlock filters – Privacy

uBlock filters – Resource abuse

uBlock filters – Unbreak

EasyList

EasyPrivacy

Online Malicious URL Blocklist

Fanboy’s Annoyance

uBlock filters – Annoyances

Peter Lowe’s Ad and tracking server list

CHN: AdGuard Chinese (中文)

</details>

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 (64-bit)
Operating system version (Android/iOS) | 21H1 19043.1110
Browser:                               | Microsoft Edge 92.0.902.55
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zloyden** [comment]
I don't see gaps on Microsoft Edge, but I'm not sure that we can remove it. @AdamWr could you please take a look?

**Comment by AdamWr** [comment]
I don't see an easy way to remove this gap. Probably we would need to use additional script to remove it. It will cause that images will not display correctly (so additional fix will be required) and there will be a gap at the end anyway.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/128165575-7e6e8ba2-f9f7-4365-a0be-4b910281441a.png)

</details>
