### ISSUE TITLE
southwalesargus.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89373]
**Issue URL (leftovers )** : https://www.southwalesargus.co.uk/news/19467663.tokyo-olympics-much-gold-medal-worth/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127334547-3e224a01-cb8c-40c2-ba52-93ff6ee4ab83.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
This issue is caused by Fanboy's Annoyances rule `||uatu.newsquestdigital.co.uk^$third-party`,
 
@chirag127 please add to user rules:
`@@||uatu.newsquestdigital.co.uk^$domain=southwalesargus.co.uk`

@ryanbr @khrin please take a look
