### ISSUE TITLE
news.com.au

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#89404]
**Issue URL (Annoyance)** : https://www.news.com.au/world/tenyearold-girl-charged-with-raping-4yearold-boy/news-story/ccf93843376a424f3573c465d73a0ef9

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/127375944-adfa15b6-5757-43ec-a5de-de164dbd156a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352294-46ac9f21-4436-4822-8702-c7d7c09f0563.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
We don't block anything in footer.
