### ISSUE TITLE
godigit.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89427]
**Issue URL (Annoyance)**:https://www.godigit.com/guides/how-to-get-international-driving-license-in-india

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127393145-621ce8a2-5112-45f8-a131-26240a0af941.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
@chirag127
I can't reproduce this issue with your settings, is it still relevant?

![screen](https://user-images.githubusercontent.com/18536328/127657449-d38d3a84-5ed2-457a-b1d0-7833f8b1cbd9.png)

**Comment by neer9** [comment]
Well that element is a annoyance.

**Comment by chirag127** [comment]
Well that element is an annoyance

**Comment by Alex-302** [comment]
@Sergey-Lyapin

**Comment by Sergey-Lyapin** [comment]
In my opinion, this is part of functionality of the site, and we should not block it.
