### ISSUE TITLE
freakhosting.ro

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#89517]
Issue: Annoyances
URL: `https://freakhosting.ro/`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509266-0528bf41-d088-4b56-b067-315747e9c92f.png)
![image](https://user-images.githubusercontent.com/87933966/127509320-6d02231f-6997-4f50-a147-f4f385957fc4.png)
</details><br/>
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509459-23fa5edc-373b-402e-b426-3fe7cd0e6443.png)
</details><br/>

**Comment by zloyden** [comment]
This website has low visitors.
