### ISSUE TITLE
gazduirejocuri.ro

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#89519]
Issue: Annoyance
URL: `https://www.gazduirejocuri.ro/`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509645-94ab0033-58ec-4bcd-b8e0-d8e19a655408.png)
</details><br/>
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509928-48966743-c21d-4028-aa03-7202f7a05cd2.png)
</details><br/>

**Comment by AdamWr** [comment]
For user filer:
`gazduirejocuri.ro#?#.services + section.getready:has(#newslettersuccess)`
