### ISSUE TITLE
techiegamers.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#89515]
Issue: leftover
URL: `https://techiegamers.com/mrbeast-net-worth/`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/87933966/127508279-f04f596c-d85b-4e37-877f-e116569f6449.png)
</details><br/>
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127508331-9795a234-2f89-4105-8cc0-90d6af2d6f1e.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors (10800 visitors/month)
