### ISSUE TITLE
cnbc.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#89527]
Issue: Newsletter thing
URL: `https://www.cnbc.com/gaming/`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/87933966/127513430-b06b7e09-6e17-4492-939e-8a52be84ff37.png)
</details><br/>
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509928-48966743-c21d-4028-aa03-7202f7a05cd2.png)
</details><br/>

**Comment by AdamWr** [comment]
We do not block these kind of elements if are placed in the footer.
