### ISSUE TITLE
Remove onelink-translations.com from Spyware

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#89538]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

See https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/299, afterward the blocking rule was removed from EasyPrivacy. But I noticed the issue still occurs on `ja.delta.com` if TPF is used with uBlock Origin on Firefox for the same reason as the issue (cname). We already have `@@||*-swissotel-cloudfront-prod.onelink-translations.com/sw/prod-ld1/delivery/$domain=swissotel.de|swissotel.es|swissotel.fr|swissotel-hotels.ru|swissotel.ae|swissotel.cn|swissotel.jp|swissotel.com.tr` and according to publicwww `onelink-translations.com` is mostly used as click-through with just 11 hits.

<details>
<summary>Screenshot</summary>

![delta](https://user-images.githubusercontent.com/58900598/127530155-257ca46b-c054-499c-8d78-e2eee31529b0.png)

</details>

* **Expected behaviour**: 

No breakage

***Steps to reproduce the problem***:

Visit the site with uBO on Firefox.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 90.0.2
AdGuard version:                       | ?
Filters enabled:                       | uBO default + TPF
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Removed `||onelink-translations.com^$third-party`
Is enough?

**Comment by Yuki2718** [comment]
> Removed `||onelink-translations.com^$third-party`
> Is enough?

Yes, the issue is solved.
