### ISSUE TITLE
188.166.211.48

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#89540]
**Issue URL (Ads)** : https://188.166.211.48/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/127535118-93afc8c3-f0f7-4963-8873-ce0bea34fb8a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by zloyden** [comment]
This website has low visitors.
