### ISSUE TITLE
crestintotal.ro

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#89548]
Issue: Annoyance
URL: `https://crestintotal.ro/`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/87933966/127551734-03ed3d45-8080-4e38-8c9f-f0fcba8fef79.png)
</details><br/>
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509928-48966743-c21d-4028-aa03-7202f7a05cd2.png)
</details><br/>

**Comment by zloyden** [comment]
We don't block elements in the footer.
