### ISSUE TITLE
movies-flix.club

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89544]
**Issue URL (Ads)** : https://pl.movies-flix.club/?st=123movie.show&plcm=dwd&dld=true&q=The+Accidental+President+(2020)

> click on DOWNLOAD IN HD on https://www.123movie.show/watch/r8RB25Id/the-accidental-president-2020/L4e8MuT3bh/watch-for-free.html to reach this url. this issue is with  movies-flix.club . I get redirected to different domains I click on the download button on the source page.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127536161-aa164286-9981-4d66-87e5-a610873fc939.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by krystian3w** [comment]
Bad polonization so no worth for https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/ or https://github.com/MajkiIT/polish-ads-filter/ - must wait to hide in EasyList/AdGuard base.

**Comment by AdamWr** [comment]
`movies-flix.club` looks like a fake website.

**Comment by krystian3w** [comment]
Too small polonisation for KAD.

---

@lolka4toli need blacklist on DNS level this page?
