### ISSUE TITLE
cheatsquad.gg

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#89550]
Issue: Annoyance - I do not recall seeing the scroll bar or whatever.
URL: `https://cheatsquad.gg/csgo`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509928-48966743-c21d-4028-aa03-7202f7a05cd2.png)
</details><br/>

**Comment by zloyden** [comment]
Well, you should write about to their webmaster.
