### ISSUE TITLE
insidermonkey.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89557]
**Issue URL (Annoyance)**: https://www.insidermonkey.com/blog/7-easiest-painless-ways-of-killing-yourselves-quickest-360388/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127558212-73ee5669-c369-4d0f-a4ee-6c446806e7e3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Not sure.
