### ISSUE TITLE
flat-ads.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89569]
**Issue URL (Incorrect Blocking)**: https://www.flat-ads.com/

> broken website

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127592843-2f406554-4412-4295-b568-23a90ef10319.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
waiting for EL
