### ISSUE TITLE
systemtek.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89572]
**Issue URL (Annoyance)**: https://www.systemtek.co.uk/2017/08/what-is-gvt1-com/

<details><summary>Screenshots:</summary>

https://www.systemtek.co.uk/2017/08/what-is-gvt1-com/
![image](https://user-images.githubusercontent.com/76880977/127604042-b0887fbd-a292-43d0-ae3b-f105704c065c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Too few visitors.
