### ISSUE TITLE
cnnsofake.news

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#89589]
**I am not attempting to make a political statement. I am responsible for the content from `https://cnnsofake.news/`.**
Issue: Annoyances
URL: `https://cnnsofake.news/`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Screenshot (zoomed in):</summary>

![image](https://user-images.githubusercontent.com/87933966/127638884-5c74e7a5-1338-4015-a953-19bc07466fd2.png)
</details><br/>
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509928-48966743-c21d-4028-aa03-7202f7a05cd2.png)
</details><br/>

**Comment by krystian3w** [comment]
If you create html code on that page try use generic classes / ID from:

https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/cookies_general.txt

Harder is found generic for newsletters:

https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/annoyances.txt#L1986

**Comment by krystian3w** [comment]
Kiboke as generic added:

`#SubscribeBox.PopupBox ~ #bottompopup.bottompopup`

**Comment by krystian3w** [comment]
To hide newsletter in right column may works:

`##.Sticky2 > #Widget15`
