### ISSUE TITLE
auchan.ro

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#89587]
Issue: Cookie notice
URL: `https://www.auchan.ro/store/home`
Browser: Google Chrome
AdGuard product: AdGuard Browser Extension
<details><summary>Filters:</summary>

![image](https://user-images.githubusercontent.com/87933966/127509928-48966743-c21d-4028-aa03-7202f7a05cd2.png)
</details><br/>

**Comment by krystian3w** [comment]
Kiboke used:

```
##.cookiesContainer:not(body):not(html)
```
