### ISSUE TITLE
foodpanda tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#89603]
```
https://perseus-productanalytics.deliveryhero.net/v1/insert/pandora/hits

||perseus-productanalytics.deliveryhero.net^
```

<details><summary>Screenshot:</summary>

![Screenshot_20210731-001807_Trebuchet.png](https://user-images.githubusercontent.com/75058881/127682714-157a97f0-73e6-4b64-9cf1-29e682b49542.png)
</details><br/>

**Comment by zloyden** [comment]
@c2xusnpq6 it can be, but it's hard to say - this app doesn't work on my end. Do you have issues if you block it?

**Comment by Alex-302** [comment]
Installed, but I do not see this domain in the log.
