### ISSUE TITLE
www.gazeta.ru

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#89616]
Раздражители на главной и внутренних.
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/127712339-1e523160-2e66-4d38-962b-4f3425df4a9a.png)
![2](https://user-images.githubusercontent.com/50718960/127712350-a9d7fec5-a289-4f82-9497-4ff2b75f7248.png)
</details><br/>

**Comment by zubrRB** [comment]
А на главной (первый скрин) блок "Реклама отключена" не раздражитель?

**Comment by Alex-302** [comment]
У меня нет этого блока.

**Comment by zubrRB** [comment]
Сохранённая страница: [Газета.Ru.zip](https://github.com/AdguardTeam/AdguardFilters/files/6940240/Ru.zip)

**Comment by Alex-302** [comment]
ок
