### ISSUE TITLE
Chinese Terabox tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#89712]
https://github.com/Crystal-RainSlide/AdditionalFiltersCN/blob/80a8d7dcefaef873ba772696611342ab4ba9138b/CN/DC.txt#L66-L71

```
||terabox.com/api/report^
||terabox.com/api/activity^
```

![Screenshot_20210731-190252_Trebuchet.png](https://user-images.githubusercontent.com/75058881/127738373-c1b7dec9-eb30-4a65-8a7d-8ee716f8054d.png)

**Comment by Alex-302** [comment]
Need details.
