### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#89750]
I found that there are already Chinese apps using new methods to bypass the blockade

![Screenshot_20210801-044630_Trebuchet.png](https://user-images.githubusercontent.com/75058881/127752164-01f609d7-c078-472b-ae0a-15b41e23cf4e.png)

![Screenshot_20210801-044636_Trebuchet.png](https://user-images.githubusercontent.com/75058881/127752166-9891bda8-373e-41bb-b99e-48cb29319156.png)

https://www.virustotal.com/gui/ip-address/183.232.25.151/relations

🤔

**Comment by c2xusnpq6** [comment]
Their own DOH server?

**Comment by c2xusnpq6** [comment]
![Screenshot_20210802-214920_Trebuchet.png](https://user-images.githubusercontent.com/75058881/127872561-8bc17a2f-23cd-4ff5-8f95-ec642628f51f.png)

**Comment by c2xusnpq6** [comment]
Set rules for this?

```
http://203.107.1.66/191607/resolve?host=grpc.biliapi.net

/resolve?host=
```

Do you want to block the app's own DNS server? [Y/n]

**Comment by Alex-302** [comment]
This resolves their API.
