### ISSUE TITLE
ura.news

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#89795]
Раздражители на главной и внутренних: https://ura.news/news/1052496995
И нужно сменить доменную зону в существующих правилах с `.ru` на `.news` в связи с редиректом.
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/127772951-f60ae9bf-6cc4-4da8-83b1-5b4ead82432d.png)
![2](https://user-images.githubusercontent.com/50718960/127772999-501dab20-6ccc-4d46-b7f4-92364fff8c1b.png)
</details>

**Comment by zubrRB** [comment]
На втором скрине оба раздражителя (со стрелками) — остались.

**Comment by Alex-302** [comment]
ок
