### ISSUE TITLE
thesun.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89797]
**Issue URL (ADs)**: https://www.thesun.co.uk/fabulous/5955296/random-erection-causes-signs-about/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127774184-7f420daa-ebdd-4247-b16c-dfa640a56b53.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Dangerous. They can move/add content to similar blocks above.

**Comment by chirag127** [comment]
@Alex-302 

Can't you use some extended css as I see a element with id which is clearly used for ads
