### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#898]
Приложение "Мастер тетриса" - Adguard блокирует верхнюю строку и закрывает счет игры.

Подробности и скриншот в комментарии: https://adguard.com/ru/adguard-report/vk.com/report.html#comment-2344185291

**Comment by Alex-302** [comment]
не повторилось
http://imagizer.imageshack.com/img907/3826/4yFSj9.jpg

**Comment by vgavrish** [comment]
В приложении:
https://vk.com/kroko?mid=22595048
После нажатия "Играть" вылазит реклама. Chrome
<details>
![screenshot_9](https://cloud.githubusercontent.com/assets/18548949/16712413/65036b0a-468f-11e6-901e-9d959d0b3b3d.jpg)
![screenshot_8](https://cloud.githubusercontent.com/assets/18548949/16712409/40e94a6e-468f-11e6-8106-711f951d7618.jpg)

**Comment by vgavrish** [comment]
Еще появляется рекламная запись в разделе Новости, как только включаешь аудиозапись и снова переходишь в раздел Новости. 
![screenshot_10](https://cloud.githubusercontent.com/assets/18548949/16712440/26b444fe-4690-11e6-86a9-d3d955c47f02.jpg)

**Comment by Alex-302** [comment]
Рекламных постов не вижу.
Для игры добавил
```
||188.93.22.210/BARServer/BARAds.xml
```

**Comment by vgavrish** [comment]
Рекламные посты редко бывают
если поможет
![screenshot_15](https://cloud.githubusercontent.com/assets/18548949/16756378/54a0d57a-480d-11e6-83c4-2fae7750889f.jpg)

**Comment by Alex-302** [comment]
Вроде починили.
