### ISSUE TITLE
Add utm_ad to the URL tracking parameter filter

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#89869]
There is a new utm tracking parameter that isn't blocked by AdGuard's new URL filter or Stealth Mode: `utm_ad`. Here is the link for it that I came across:

https://tradethesectors.com/replay2?utm_ad=8076&bsft_aaid=8fe1efe9-08a5-44aa-89cf-89925121010d&bsft_eid=dbb4ba76-ff7d-4cd3-a591-9dc799c3251f&utm_campaign=spp5sendemail-1am-pm-7_17_2021&utm_source=blueshift&utm_medium=email&utm_content=spp5sendemail-4pm-7_20_2021&bsft_clkid=afd712c6-498f-45ef-aea9-01e5be5fb6f2&bsft_uid=e904de22-3a3e-4daa-b8a7-f8aa97d47a68&bsft_mid=dbe6ac9e-334d-4e01-88a7-cb80c14c4926&bsft_mime_type=html&bsft_ek=2021-07-20T20%3A42%3A31Z&bsft_lx=6&bsft_tv=8

Luckily I have $removeparam=/utm/ in my user filter or it wouldn't have been stripped at all.

Zendesk ID: 524670

**Comment by infinitewaveparticle** [comment]
$removeparam=/utm_/  would be a great way to kill them all.

**Comment by Alex-302** [comment]
@Eugene-Savenko What is the source link? I guess user just clicked non-blocked ad.

**Comment by infinitewaveparticle** [comment]
@Alex-302 I am the person who reported this. What do you mean the source link? I clicked a link in an email (I'm subscribed to an email list) that opened the link included in the report above. If you want me to send you the email I may or may not still have it.

**Comment by Alex-302** [comment]
Blocked few tracking parameters.
