### ISSUE TITLE
[In-App Advertising] `银河奇异果`

### ISSUE THREAD

**Issue by shenzhiming88** [AdguardTeam/AdguardFilters#89875]
Hello!
Galaxy Kiwi (`银河奇异果`) is a popular online video player on Android TV boxes in China, downloadable from http://app.iqiyi.com/tv/player/index.html. However, AdGuard does not seem to be able to filter ads in this software, such as opening screen ads, and ads before video playback. As the video shows.
Can this be handled? Thanks!
Note: In order to use the software properly to play online videos, you may need a VPN to China

https://user-images.githubusercontent.com/66902050/127876132-3e954204-756e-461d-aafd-3ae11931df83.mp4

Settings: all default, and the rules are updated to the latest

**Comment by Alex-302** [comment]
@shenzhiming88 Hi. Could you please record HAR file and send it to filters@adguard.com?
https://kb.adguard.com/en/android/solving-problems/har#how-to-get-har-files

**Comment by shenzhiming88** [comment]
> @shenzhiming88 Hi. Could you please record HAR file and send it to [filters@adguard.com](mailto:filters@adguard.com)?
> https://kb.adguard.com/en/android/solving-problems/har#how-to-get-har-files

Hello!
Already sent
Thanks!

**Comment by Alex-302** [comment]
@shenzhiming88 Hi. You send the log, not HAR:)
But it seems this player - one of the most popular Chinese video hostings, and ad cannot be blocked without root access and HTTPS filtering.

**Comment by shenzhiming88** [comment]
@Alex-302 Hello!
I have obtained Root access on that device and installed the certificate as a system certificate and turned on https filtering, but it still does not filter
Also, I am following the instructions and it should be a HAR file, can you reopen the issue?

**Comment by Alex-302** [comment]
Please test:
`||mixer.cupid.ptqy.gitv.tv/mixer?a=$replace=/("adSkipTime\\":\\)"30(\\")/$1"1$2/`
or
`||mixer.cupid.ptqy.gitv.tv/mixer?a=$replace=/("adSkipTime\":\\)"30(\")/$1"1$2/`

**Comment by Alex-302** [comment]
or
`||cupid.ptqy.gitv.tv/mixer?$replace=/"adSlots"/"adSlots_"/`

**Comment by shenzhiming88** [comment]
@Alex-302 I just tested it
```
||cupid.ptqy.gitv.tv/mixer?$replace=/"adSlots"/"adSlots_"/
```
works
```
||cupid.ptqy.gitv.tv/mixer?$replace=/("adSkipTime\\":\\)"30(\\")/$1"1$2/
||cupid.ptqy.gitv.tv/mixer?$replace=/("adSkipTime\":\\)"30(\")/$1"1$2/
```
doesn't work.
But the ads when launching the app don't seem to be filtered
Thanks

**Comment by Alex-302** [comment]
> works

What works?

**Comment by shenzhiming88** [comment]
> > works
> 
> What works?

I'm sorry I didn't make myself clear
`||cupid.ptqy.gitv.tv/mixer?$replace=/"adSlots"/"adSlots_"/
`

**Comment by Alex-302** [comment]
Ok. No side effects? 100% good?

**Comment by shenzhiming88** [comment]
> Ok. No side effects? 100% good?

Hello!
I've been testing for a while and didn't find any damage, if so, I'll talk to you again under this issue

**Comment by Alex-302** [comment]
Ok. I need `package_name` of this app.
I want to add the rule as
`||cupid.ptqy.gitv.tv/mixer?$replace=/"adSlots"/"adSlots_"/,app=package_name`

**Comment by shenzhiming88** [comment]
@Alex-302 `com.gitvdemo.video`
