### ISSUE TITLE
theatlantic.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#89933]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

If you browse around on `https://www.theatlantic.com/` to different articles, eventually there is a soft block that sets the body to `overflow: hidden` and you can't scroll at all (I happened to be on `https://www.theatlantic.com/science/archive/2021/07/obituary-carbon-tax-beloved-climate-policy-dies-47/619507/` when it happened). This essentially breaks the site since you can't scroll down it and can't click on certain parts of the page anymore. There are also invisible (I think they are invisible because other rules are blocking parts of them?) overlays that are preventing clicking on content which can be removed by blocking `[data-category*="nudge"]` elements. 

To fix this, add these rules:
```
theatlantic.com##[data-category*="nudge"]
theatlantic.com##body:style(overflow: auto !important;)
```

**Comment by Alex-302** [comment]
Cannot reproduce. Opened 10 articles with US IP.
