### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#89931]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Condé Nast publications have a new sticky social share bar across all their sites. It can be blocked with:
```
allure.com,architecturaldigest.com,bonappetit.com,cntraveler.com,gq.com,newyorker.com,vanityfair.com,vogue.com,wired.com##.article__social-share
```

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="553" alt="image" src="https://user-images.githubusercontent.com/88003315/127926518-7c51f714-9e59-4704-aac1-0c4871ab97d8.png">

</details><br/>

**Comment by Alex-302** [comment]
Not reproduced on all these sites.
