### ISSUE TITLE
newrepublic.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#89934]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

On `https://newrepublic.com/article/163103/dont-rush-get-third-covid-shot-pfizer` there is a sticky footer, popup overlay (if you scroll down the page), newsletter forms, and a paywall overlay (after viewing a few articles).

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshots:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127927784-d1c39ea8-ffc5-4ebc-a4ab-eb2909d5a659.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127928131-15873107-c853-4fea-8b54-6e44902d75ab.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/88003315/127927962-6802579a-d95a-4a7a-aaa2-d325b127c4c6.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127928499-74bc6a0e-5c1a-455a-9c92-31e4379ac120.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127928540-6d4d8de8-64b5-49e4-ad96-52f73d09a05c.png">

</details><br/>

**Comment by sweetcashew** [comment]
Might want to consider blocking `||validate.onecount.net/js/all.min.js` as well, as this seems to sometimes redirect pages to a subscribe ad.

**Comment by sweetcashew** [comment]
Thanks!

It appears that the newsletter ad is still showing up:

```
##.footer-newsletter-cta
```

<details><summary>Screenshot</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128578373-b2971ea7-96e1-44a8-b39f-809fd0221a03.png">
</details>

**Comment by Alex-302** [comment]
ok
