### ISSUE TITLE
foreignaffairs.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#89938]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

There are sticky footer ads, newsletter subscription forms, and footer ads on `https://www.foreignaffairs.com/articles/united-states/2021-07-30/how-americans-think-about-trade`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127930741-82db4c57-79d4-434b-aaf1-bb7b4de12ae8.png">

<img width="996" alt="image" src="https://user-images.githubusercontent.com/88003315/127930791-54032025-45aa-4c4c-bac3-f9c590ac5546.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127930851-65b327f1-442e-43c9-8cdd-d2e659a81f82.png">

</details><br/>

**Comment by sweetcashew** [comment]
Found an in-content newsletter form here: `https://www.foreignaffairs.com/articles/united-states/2021-08-06/why-quad-alarms-china`

<details><summary>Screenshots</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128578665-71b51095-8ab5-4053-a353-76d749b8e601.png">

</details>

And on the homepage: ``

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128578705-834ff96a-0aad-424b-b4c2-aa6a6c87aa5b.png">

**Comment by Alex-302** [comment]
ok
