### ISSUE TITLE
commondreams.org

### ISSUE THREAD

**Issue by teddybradford** [AdguardTeam/AdguardFilters#89942]
On `https://www.commondreams.org/views/2021/08/02/how-corporate-courts-impede-efforts-battle-climate-crisis` there is a newsletter banner at the top and a donate ad at the end of the article.

<details><summary>Screenshots:</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3684553/127935644-1d7be5d2-6cf7-417e-a4f9-49aea82f5cfa.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3684553/127935655-1d0a0dbd-2dff-4956-a8a1-0d2aa1995528.png">
</details>

On `https://www.commondreams.org/latest-news` there is a newsletter sidebar box. It can be blocked with: `commondreams.org##.block:has(> #subscribeModal)`.

<details><summary>Screenshot:</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3684553/127946956-b082821f-df33-43d7-b7c3-43876d5ba887.png">
</details>

**Comment by Alex-302** [comment]
Thanks, fixed.
