### ISSUE TITLE
vimeo.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#89952]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

When logged in to `vimeo.com` there are self promo ads.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/127948858-7b5baaf2-53aa-4513-a0d6-a2e8f2d2a36c.png">

</details><br/>

When logged in and on a video page like `https://vimeo.com/572080731` there is a sticky footer banner ad.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1280" alt="Screen Shot 2021-08-02 at 10 36 19 PM" src="https://user-images.githubusercontent.com/88003315/127948948-cbe37a2c-4599-45e2-b71f-b1056fdbb261.png">

</details><br/>

**Comment by Alex-302** [comment]
Cannot register
![image](https://user-images.githubusercontent.com/8361299/128542953-79747f22-6753-4cda-a547-7d0016cf9be4.png)
Please show HTML of these elements.

**Comment by sweetcashew** [comment]
For the sidebar ad:

```html
<div class="UQAet">
  <div class="_3dEqE">
    <div class="_3Em88">Try Vimeo Pro</div>
    <p class="_1L7ZM">Powerful privacy options and analytics.</p>
    <a
      data-fatal-attraction="container:sidebar_menu|component:upgrade_link|keyword:pro"
      href="/store/free30daypro"
      target="_blank"
      ><span class="sc-iELTvK iBuQQI" format="success"
        ><span class="sc-cmTdod iFAQUL"
          ><!-- react-text: 143 -->Start free trial<!-- /react-text --></span
        >
        <div class="sc-jtRfpW fzrDDz"></div></span
    ></a>
  </div>
</div>
```

and for the sticky footer:

```html
<div class="sc-btzYZH kuVuKv">
  <button class="sc-bYSBpT kkylLH sc-uJMKN cgkrYM" format="dark">
    <span class="sc-gGBfsJ eynEjA"
      ><svg viewBox="0 0 20 20" class="sc-elJkPf dstEGb" color="#969696">
        <path
          d="M11.06 10l4.597-4.596a.749.749 0 10-1.061-1.06L10 8.938 5.404 4.343a.749.749 0 10-1.06 1.061L8.938 10l-4.596 4.596a.749.749 0 101.061 1.06L10 11.062l4.596 4.596a.749.749 0 101.06-1.061L11.062 10z"
          fill="#1A2E3B"
          fill-rule="evenodd"
        ></path></svg
    ></span>
    <div class="sc-jnlKLf itJjvp"></div>
  </button>
  <p class="sc-lhVmIH jZvetc sc-jqCOkK dyPGzI" format="dark" color="inherit">
    Get more storage, unlimited video creation, collaboration tools, and much
    more.
  </p>
  <div class="sc-jtRfpW iqwVVr">
    <button class="sc-kTUwUJ fxEIQN sc-fYxtnH deKPzE" format="alternative">
      <span class="sc-tilXH NLwOZ"
        ><!-- react-text: 113 -->Upgrade now<!-- /react-text --></span
      >
      <div class="sc-iELTvK iOKxTU"></div>
    </button>
  </div>
</div>
```
