### ISSUE TITLE
electricallive.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#89962]
**Issue URL (Ads)** :https://electricallive.com/2015/03/torque-slip-characteristics-in-three.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127964002-0e0a8434-3f83-4a49-9f61-6f034a631b0d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
No visitors.
