### ISSUE TITLE
platon.ru

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardFilters#8999]
***Description***: Gets blocked by AdGuard family protection DNS

* **Current behaviour**: 
Using DNS 176.103.130.132 & 176.103.130.134 causes platon.ru to redir to http://family.block.dns.adguard.com/

* **Expected behaviour**: 
Contains no adult content, shouldn't get blocked

**Comment by Alex-302** [comment]
Родительский контроль заблокировал. Я тут не помогу.
@zebrum @vozersky @altokarev что в этом случае делаем?

**Comment by altokarev** [comment]
Добавил в исключения нашего род. контроля. В течении суток должно обновиться и заработать.
