### ISSUE TITLE
Probably Tencent Tracker

### ISSUE THREAD

**Issue by shenzhiming88** [AdguardTeam/AdguardFilters#89990]
Hello!
This is QQMusic.
This is most likely Tencent's tracker, and disabling it does not seem to affect normal functionality
```
||monitor.music.qq.com^
```
![Screenshot_2021-08-03-19-16-44-079_com adguard android](https://user-images.githubusercontent.com/66902050/128008617-70f70ca7-c89d-4aae-bb00-39a7085f8425.jpg)

**Comment by Alex-302** [comment]
Please test:
```
||monitor.music.qq.com^
||adstats.tencentmusic.com^
||stat.y.qq.com^
```

**Comment by shenzhiming88** [comment]
> Please test:
> 
> ```
> ||monitor.music.qq.com^
> ||adstats.tencentmusic.com^
> ||stat.y.qq.com^
> ```

Thank you!
There does not appear to be any functional damage

**Comment by shenzhiming88** [comment]
@Alex-302 Please also add this rule. Thanks!
```
||ad.tencentmusic.com^
```
![Uploading Screenshot_2021-08-05-23-02-44-281_com.adguard.android.jpg…]()
