### ISSUE TITLE
slack.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90014]
**Issue URL (Annoyance)**: https://slack.com/intl/en-in/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128064109-1ee6ea6d-f955-42f8-bb1b-0b567da7e99d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Not so annoying. I guess they will remove it later.
