### ISSUE TITLE
[In-App Advertising] Bilibili

### ISSUE THREAD

**Issue by shenzhiming88** [AdguardTeam/AdguardFilters#90084]
Hello!
Bilibili will show ads when opening the app, using AdGuard to track and find the link to download the ads is as follows
http://upos-sz-staticks3.bilivideo.com/ssaxcode/c1/0f/m210730a22u8b9c40wvn8b1nn91u0fc1-1-SPLASH.mp4
http://upos-sz-staticks3.bilivideo.com/ssaxcode/kt/0a/m210729a2cfo7bciw9q4a1cccffp0akt-1-SPLASH.mp4
![Screenshot_2021-08-04-22-03-41-196_com adguard android](https://user-images.githubusercontent.com/66902050/128195366-20fa59c9-f497-49dd-8f55-711a900d2372.jpg)
I think this filter rule should work
```
||upos-sz-staticks3.bilivideo.com/ssaxcode
```
Please take care of it, thanks!

**Comment by Alex-302** [comment]
Please copy-paste `package_name`.
What shown instead of ad when requests are blocked?

**Comment by shenzhiming88** [comment]
@Alex-302 `tv.danmaku.bili`
It will continue to display the opening screen instead of ads

**Comment by Alex-302** [comment]
Could you please make screenshot?
What opens when you press that ads?

**Comment by shenzhiming88** [comment]
Hello!
The software only occasionally shows ads, I just tested it many times and the ads did not appear!
Could you please keep this issue open until the ads come back and then deal with it?

**Comment by Alex-302** [comment]
Maybe thhese ads like in Aliexpress app - 3 seconds popup with their own promos?

**Comment by shenzhiming88** [comment]
> Maybe thhese ads like in Aliexpress app - 3 seconds popup with their own promos?

Sometimes yes, but more often ads pop up that point to other software

**Comment by Alex-302** [comment]
Need sample links and screenshot when ads blocked. Not sure if broken ad popup is good.

**Comment by shenzhiming88** [comment]
@Alex-302 Hello!
Sorry, I can't reproduce this ad at the moment, I will contact you when it is reproduced.
