### ISSUE TITLE
downloadhub.fit

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90091]
**Issue URL (Annoyance)**: https://downloadhub.fit/?a79b4e104b=SjdydStIbHRuSnJYKy85N2tyTXRDVHhFM3BHWlFVODZOUktERnZSY1VseXVVaFE3Q1FYTUluQ3NXN1BEQkZ3R0FqQ3p0UUZtZjFFZDNLVno5Uk13TXM5M0pKUlRIbnZuUDNtNGt6dkZtTU09

> there is timer annoyance at the destination .

<details><summary>Screenshots:</summary>

https://downloadhub.fit/lagaan-2001-hindi-720p-hdrip-x264/

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
It seems that it's checked on server side, because skipping timer causes that link doesn't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/128693105-5727059b-90e7-4ac2-b5f7-65ea3a1154ea.png)

</details>
