### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90108]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

There are several ads appearing on `https://www.newyorker.com`

```
newyorker.com##.ticker-view
newyorker.com##[class*="StickyHeroAdWrapper-"]
newyorker.com##.consumer-marketing-unit--nav-left
newyorker.com##.consumer-marketing-unit--cm-banner
newyorker.com##.consumer-marketing-unit--homepage-mid-content
newyorker.com##.consumer-marketing-unit--cm-footer
```

<details><summary>Screenshot:</summary>

<img width="1280" alt="Screen Shot 2021-08-04 at 4 00 38 PM" src="https://user-images.githubusercontent.com/88003315/128253695-dd7d1912-51de-4eb9-874b-27446f2f2c0f.png">
<img width="1280" alt="Screen Shot 2021-08-04 at 4 00 47 PM" src="https://user-images.githubusercontent.com/88003315/128253708-fc178ec9-d151-41e6-8cd8-4856681e4020.png">
<img width="1280" alt="Screen Shot 2021-08-04 at 4 01 21 PM" src="https://user-images.githubusercontent.com/88003315/128253715-e4b1072d-c5ec-437f-8d2c-03a2dfc3c167.png">
<img width="1280" alt="Screen Shot 2021-08-04 at 4 02 00 PM" src="https://user-images.githubusercontent.com/88003315/128253723-aa757eda-21b8-4d27-a269-17530e453227.png">

</details><br/>

And on article pages like `https://www.newyorker.com/magazine/2021/08/09/the-seas-are-rising-could-oysters-protect-us` there is a banner ad at the bottom of the page.

<details><summary>Screenshot:</summary>

<img width="1280" alt="Screen Shot 2021-08-04 at 4 03 12 PM" src="https://user-images.githubusercontent.com/88003315/128253771-83b4f944-fa61-4872-b811-328468717cc1.png">

</details><br/>

**Comment by Yuki2718** [comment]
Will be closed with #90108, #90109, #90110, #90111 once my Pull request in EasyList is merged, meanwhile if you find anything not fixed by the rule I added to Annoyances and `##div[class^="StickyHeroAdWrapper-"]` in the PR, please report back.
