### ISSUE TITLE
allure.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90106]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

There is an adblock detecting cookie (seemingly used for bypassing some ad blocking) set on Conde Nast sites, which can be removed with:

`allure.com,architecturaldigest.com,bonappetit.com,cntraveler.com,gq.com,newyorker.com,vanityfair.com,vogue.com,wired.com##+js(cookie-remover, CN_ad_block)`

Also there are some elements specific to allure.com, e.g. on `https://www.allure.com/story/why-pandemic-weight-gain-isnt-bad`:

1. banner below nav
2. mid-content ad
3. footer ad

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128251508-4aa8d9cd-6dfc-43db-93ee-cac6ee98caf7.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/88003315/128251490-fceee376-7235-4b9f-bfe4-fa7ec564939f.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128251528-a7ce86f2-04ce-413e-aabe-f042d6338243.png">

</details><br/>

On the homepage, `https://www.allure.com/`, there is:

1. banner ad at top
2. footer ad

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128253243-7e018dd9-907b-44c1-a097-1951df29f995.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128253373-84927714-acf9-4180-a8c4-ffe64de7d02b.png">

</details><br/>

**Comment by Alex-302** [comment]
@sweetcashew
