### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90111]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

On ` https://www.wired.com/story/new-way-train-ai-curb-online-harassment/` there is:

1. header banner ad
2. sidebar ad
3. footer banner ad
4. sometimes this secondary banner ad space is populated too `wired.com##.consumer-marketing-unit__slot--cm-footer`

<details><summary>Screenshot:</summary>

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/88003315/128255053-c2a3fcf7-c681-4cd4-8c13-0e726d24cfd7.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/88003315/128255079-807288e2-a5e0-4590-821d-0285586cc9a7.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128255104-0afba12c-e2bf-4ce9-9758-ba888c847bd3.png">

</details><br/>

**Comment by chirag127** [comment]
You didn't mentioned what filters you are using.
