### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90117]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

For the URL Tracking Protection list, consider adding:

`$removeparam=s,domain=twitter.com`

Shared tweet URLs have this `s` param attached, e.g. `?s=09`

**Comment by Alex-302** [comment]
Need sample URL and how to get it.

**Comment by sweetcashew** [comment]
If you go to a tweet, e.g. `https://twitter.com/stefscribbles/status/1424679486809944064` and
1. click the share button (below tweet)
2. click "copy link to tweet"
3. you get this URL: `https://twitter.com/stefscribbles/status/1424679486809944064?s=20` with the share param

**Comment by Alex-302** [comment]
On my end `s=20` - it seems no need to remove this param.

**Comment by sweetcashew** [comment]
I thought the purpose of the URL tracking list was to remove tracking params? On mobile, the share param is `?s=09`, so the param is being used to track device type.
