### ISSUE TITLE
vox.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90113]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

There's a footer subscription ad on `https://www.vox.com/22559293/food-waste-expiration-label-best-before`

<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128256847-65374f5b-de65-4b5a-a677-0a127bce3baa.png">

</details><br/>

**Comment by Sergey-Lyapin** [comment]
We block very annoying donation widgets only, so this element should not be blocked.
