### ISSUE TITLE
bostonglobe.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90126]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

On `https://www.bostonglobe.com/2021/07/31/business/it-has-be-known-what-was-done-us-natick-couple-harassed-by-ebay-tell-their-story-first-time/?outputType=amp` there is a sticky ad at the bottom of the page.

```
bostonglobe.com##amp-subscriptions-dialog
```

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128263958-186e211c-80a4-40f5-be5c-f62b8edb0f0f.png">
</details><br/>

**Comment by sweetcashew** [comment]
### Issue description

Also, on `https://www.bostonglobe.com/2021/07/31/business/it-has-be-known-what-was-done-us-natick-couple-harassed-by-ebay-tell-their-story-first-time/` there is a newsletter form.

<details><summary>Screenshots</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128398485-807cfc40-3b6f-47d8-9288-6e94680141f1.png">

</details>

**Comment by zloyden** [comment]
The newsletter is already blocked, please enable AdGuard Annoyances.
