### ISSUE TITLE
cenakrasna.info - Anti Adblock

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#9012]
Сообщение о просьбе выключить AdBlock: https://cenakrasna.info/spb/search?search=Voimix

<details><summary>Screenshot:</summary>

![cenakrasna info](https://user-images.githubusercontent.com/17948007/34413354-f00ce356-ebf3-11e7-93d9-bb041cda319c.png)
</details><br/>

 Правило скрытия: `cenakrasna.info###adb`
___________________________________________________
Pale Moon v26.5 (Win7) - Adguard v2.8.1 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
добавил

**Comment by XX-J** [comment]
Забыли закрыть...
