### ISSUE TITLE
nationalgeographic.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90123]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

On `https://www.nationalgeographic.com/` there's an app download banner ad.

```
nationalgeographic.com##[data-track-creative_type="inline_banner_static"]
```

<details><summary>Screenshot:</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128262805-6d369211-7996-45e5-bdab-1434ba50e88f.png">
</details><br/>

On `https://www.nationalgeographic.com/animals/article/wild-us-deer-found-with-coronavirus-antibodies` there's an inline ad spot and an inline email container.
```
nationalgeographic.com##.InsertedAd
nationalgeographic.com##.InlineEmail__Container
```

<details><summary>Screenshot:</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128262937-b849b533-a1e1-4a43-9090-9a64ad2167a1.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128263004-c0756a69-95fe-462a-913b-bd61d68186d2.png">

</details><br/>

On `https://api.nationalgeographic.com/distribution/public/amp/animals/article/wild-us-deer-found-with-coronavirus-antibodies` there's a banner ad.
```
api.nationalgeographic.com##[class*="bannerWrapper_"]
```

**Comment by Yuki2718** [comment]
I can't reproduce the app banner, @Alex-302 @AdamWr Please take a look.
BTW I want to use @AdguardTeam/filters-maintainers mention if possible.

**Comment by Alex-302** [comment]
> BTW I want to use @AdguardTeam/filters-maintainers mention if possible.

Only members can use it, to avoid spam:)

**Comment by Alex-302** [comment]
But you can add `@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr ` to saved replies
![image](https://user-images.githubusercontent.com/8361299/128385585-76d35078-1a33-4e5a-be75-58eda16a56ec.png)

**Comment by sweetcashew** [comment]
Thanks!

It looks like there's also an empty ad container on the homepage, `https://www.nationalgeographic.com/`, (and also appears on some article pages):

<details><summary>Screenshot</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128386362-153c08b9-7f68-47a3-be59-ed12d4b6cbad.png">
</details>

**Comment by Yuki2718** [comment]
> But you can add `@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr ` to saved replies

Thx, didn't know that funciton.

**Comment by Alex-302** [comment]
> Thx, didn't know that funciton.

Very useful) I have 20 saved replies)
