### ISSUE TITLE
aliexpress.com

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#90142]
Помогите с правилом косметического характера на али. Как запретить при клике по полному превью товара увеличивать картинку, сделав её кликабельной, дабы можно её было открыть через ПКМ ?
![Screenshot_20210805_182000](https://user-images.githubusercontent.com/12525093/128317044-198b3151-116f-45b9-a347-7f60e8eca7e0.jpg)

**Comment by Alex-302** [comment]
Вроде так работает:
```
aliexpress.*#%#//scriptlet('remove-attr', 'style', '.magnifier-image')
aliexpress.*#$?#.magnifier-cover { remove: true; }
```
Себе оставлю)

**Comment by Baltazar500** [comment]
Спасибо :)

На 3.6.2 сработало, на 2.12.250 не прокатило. Видать староват билд для таких правил.

**Comment by Alex-302** [comment]
Да, 2.12 слишком стара.

**Comment by Baltazar500** [comment]
Правила на али перестали работать. Можете починить ?

**Comment by Alex-302** [comment]
`aliexpress.*#%#//scriptlet('remove-class', 'image-view-magnifier-wrap', 'div')`

**Comment by Baltazar500** [comment]
Спасибо. Помогло. Хотя картинка при лонг-тапе продолжает масштабироваться. ну да ладно. Или там надо было второе старое правило добавить в довесок ?
