### ISSUE TITLE
obsolete/redundant filter on modekoninginmaxima.nl

### ISSUE THREAD

**Issue by JohnyP36** [AdguardTeam/AdguardFilters#90146]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: obsolete/redundant filter on modekoninginmaxima.nl
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
On the site `modekoninginmaxima.nl` is a filter in `Adguard Base`.  
This filter is: `modekoninginmaxima.nl##+js(nobab)`   
The mentioned filter had the task to solve the anti-adblock message.  
However, if I disable this filter and reload the page in a new browser profile there is no anti-adblock message.  

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # 
So what I think is that `modekoninginmaxima.nl##+js(nobab)` could be removed from `Adguard Base Filters`

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration*** 

**Filters:** 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | 21H1
Browser:                               | MS Edge
AdGuard version:                       | none
Filters enabled:                       | Adguard Base, Adguard Tracking Protection
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          | 
AdGuard DNS:                           | **None** / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JohnyP36** [comment]
I'm sorry. This rule is still necessary.

![image](https://user-images.githubusercontent.com/81161435/128341515-0d745dd1-3172-4a7b-969a-6e23dbcc3028.png)

**Comment by krystian3w** [comment]
AG addons use html filtering and own pure JS scriptlet (works better than nobab in AdGuard https://github.com/AdguardTeam/Scriptlets/issues/21).
