### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90187]
### Issue description

On `https://www.forbes.com/sites/antoinegara/2021/08/03/deal-of-the-century-how-michael-dell-turned-his-declining-pc-business-into-40-billion-windfall/?sh=3b6031395c2a` there are blank ad spaces.

<details><summary>Screenshots</summary>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/88003315/128397511-9b05e8cd-8402-4b99-bcc1-08fa2bc70d8d.png">

</details>

### System configuration

<details><summary>Filters</summary>
<img width="483" alt="image" src="https://user-images.githubusercontent.com/88003315/128388195-db3b8c65-a07a-41fd-aecf-ee24e0c75bbc.png">
</details>

**Comment by AdamWr** [comment]
It's probably caused by `@@||forbes.com^$ghide` from `uBlock filters`.
