### ISSUE TITLE
thetrace.org

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90188]
### Issue description

On `https://www.thetrace.org/2018/12/remington-rifle-mississippi-brothers-shooting/` there is a subscribe CTA in the footer.

<details><summary>Screenshots</summary>
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/88003315/128397830-fb2e8857-abed-4f44-8e62-e3f4fe53fbcb.png">

</details>

### System configuration

<details><summary>Filters</summary>
<img width="483" alt="image" src="https://user-images.githubusercontent.com/88003315/128388195-db3b8c65-a07a-41fd-aecf-ee24e0c75bbc.png">
</details>

**Comment by zloyden** [comment]
We don't block such paid subscriptions.
