### ISSUE TITLE
washingtonpost.com

### ISSUE THREAD

**Issue by sweetcashew** [AdguardTeam/AdguardFilters#90197]
### Issue description

On `https://www.washingtonpost.com/sports/2021/08/02/race-norming-nfl-concussion-settlement/` there are empty ad containers creating extra space in the content flow.

They can be removed with:
```
washingtonpost.com##.hide-for-print:has(> .ad-container)
```

<details><summary>Screenshots</summary>
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/88003315/128399545-a7e5fbcc-2474-40dc-a8ce-fe568f88a73c.png">

</details>

### System configuration

<details><summary>Filters</summary>
<img width="483" alt="image" src="https://user-images.githubusercontent.com/88003315/128388195-db3b8c65-a07a-41fd-aecf-ee24e0c75bbc.png">
</details>

**Comment by zloyden** [comment]
Not reproduced with AdGuard extension / UBO and US IP. Please check `washingtonpost.com##.article-body .hide-for-print:has(> .ad-container)`.

**Comment by sweetcashew** [comment]
The ad containers no longer appear for me. Maybe the site was changed.
