### ISSUE TITLE
tumblr.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90268]
**Issue URL (Annoyance)**: https://www.tumblr.com/tagged/a+practical+guide+to+evil?sort=top

<details><summary>Screenshots:</summary>

https://www.tumblr.com/tagged/a+practical+guide+to+evil?sort=top
![image](https://user-images.githubusercontent.com/76880977/128532499-b22c0258-6892-467a-8aa9-d2a8b6b6770e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment]
Does Tumblr have dark theme or any settings to change color? Otherwise `tumblr.com###base-container > div[style="background-color:RGB(var(--navy))"] + div[class^="_"] > div[class^="_"]:last-child` would be one option to avoid random-looking class name.

**Comment by chirag127** [comment]
> Otherwise `tumblr.com###base-container > div[style="background-color:RGB(var(--navy))"] + div[class^="_"] > div[class^="_"]:last-child` would be one option to avoid random-looking class name.

But are you sure that only this element will have this colour?

**Comment by Alex-302** [comment]
Added `tumblr.com##div[style^="background: rgb(124, 92, 255)"][style*="color: rgb(255, 255, 255);"]`
