### ISSUE TITLE
rutube.ru - антиадблок

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#903]
Антиадблок при просмотре видео.
Актуально только с расширением.
VWL-297-93513

**Comment by Alex-302** [comment]
C прогой тоже, просто не со всеми видео повторяется, и может пропасть при повторном открытии. Под них сложно подстроиться тк быстро реагируют.

**Comment by Bohdan-SUP** [comment]
http://prntscr.com/aa5myc
помогает отключение Английского фильтра

**Comment by Alex-302** [comment]
@Bohdan-SUP 
если расширение - можешь закрывать, там не исправить

**Comment by Bohdan-SUP** [comment]
С прогой тоже:
https://i.imgur.com/TmtwQIy.png

**Comment by Alex-302** [comment]
а ссылка на видео?
Её вообще всегда желательно выкладывать

**Comment by vbagirov** [comment]
http://rutube.ru/video/5874b930eeeb1bee173ef80cf460ddda/?pl_type=source&pl_id=8837 - еще ссылка

http://forum.adguard.com/showthread.php?9854-%D0%A3%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%9F%D0%BE%D0%BC%D0%BE%D1%89%D0%BD%D0%B8%D0%BA%D0%B0-Adguard/page3 - форум

**Comment by Bohdan-SUP** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/903
http://rutube.ru/video/9a455dfa009f3d76c7f76616440233bf/
http://prntscr.com/b9cmme

**Comment by Alex-302** [comment]
@Bohdan-SUP 
это с расширением или прогой?

**Comment by Bohdan-SUP** [comment]
Было с прогой, сейчас не повторяется.

**Comment by vgavrish** [comment]
Прога
"Во всех видео! Для примера:"
http://rutube.ru/video/b953dd5849a4a0018e370ad272426288/?pl_type=source&pl_id=1467
http://rutube.ru/video/e3864ce4f4e69d887db9ad746373977a/?pl_type=source&pl_id=8188
![7a2a5b27ec354934a769886bb076bc07](https://cloud.githubusercontent.com/assets/18548949/16484402/9dbe2cee-3ec1-11e6-919f-1a51d1a15e33.png)

У меня ни одно видео не хочет проигрываться.
Фильтры: Russian, English, Spyware filter, Social media, Annoyances filter, ЭФ

**Comment by ketchup48** [comment]
Rutube problem is actual!!! Help.
Rutube проблема еще актуальна!

**Comment by vgavrish** [comment]
Браузер Edge.  Windows 10. Прога.
Фильтры 1,2,3,4,14
В плеере пишется, что я не могу посмотреть видео в хорошем качестве, т.к. у меня установлен блокировщик рекламы!
https://rutube.ru/video/37e3218fdfb5a7cd13e30997335a0567/?ref=logo
У меня не повторяется

**Comment by evgeniy-ADG** [comment]
@vgavrish а у меня повторяется
https://rutube.ru/video/9586cc824a13205379201ee2ad9b2ea0/?ref=logo
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17458903/eff403d4-5c2c-11e6-9496-ef6ecbeedb3a.png)

**Comment by vgavrish** [comment]
1066531
@Alex-302 
пользователь сообщил, что здесь снова ограничение на просмотр видео в высоком качестве
https://rutube.ru/video/f6090e61b371dfe206bceb39eed9d757/?ref=logo
ф: 1,2,14, 211, Adblock polskie reguły

**Comment by Alex-302** [comment]
Не открывает даже с прокси. Пусть без польского проверит.
Другие видео с детектом расширения с программой работают как следует.

**Comment by vgavrish** [comment]
> После отключения фильтра и проверки обновления ничего не изменилось!
Может там с журнала фильтрации скрины нужны или скрин кода элемента?
еще один пользователь обращался по этому поводу

**Comment by Alex-302** [comment]
Какие у них Адгарды? С расширениями ловить нечего.

**Comment by vgavrish** [comment]
Adguard 6.1.287.1519
https://rutube.ru/video/d9fbfb3f4c6b34f91e4d7a05c6c746f7/?pl_id=4569&pl_type=source
- конкретный ролик.
Ф: 1,2,3,4,5,14,15

**Comment by Alex-302** [comment]
Может какой-то ещё блокировщик стоит? Зашел с прокси - качество переключилось.

**Comment by Serzh-SUP** [comment]
@Alex-302 У пользователя в Internet Explorer также.
У меня тоже пишет про блокировшик. Использовал VPN для просмотра.

**Comment by Alex-302** [comment]
@Serzh-SUP с прогой? Какой VPN?

**Comment by Serzh-SUP** [comment]
@Alex-302 HideMe.ru VPN

**Comment by evgeniy-ADG** [comment]
Может, вы ТВ организуете как-то? Может, пользователю предложить?
Ибо нам жалуются.

**Comment by vgavrish** [comment]
предложила

**Comment by vgavrish** [comment]
в пятницу 09.12 во второй половине дня юзер согласился на тим.
потом отпишу точное время и в скайп скину лог пас
