### ISSUE TITLE
games for cats (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#90316]
||adservice.google.*^

https://apps.apple.com/us/app/games-for-cats/id1394742877

**Comment by jordanelliott23** [comment]
i think making it generic with the star is good because ive seen it used on multiple google domains: https://confection.io/cookies/adservice-google-is/

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/129018514-56967f65-9411-47b4-a2a7-f00e33c1452f.png)

**Comment by jordanelliott23** [comment]
sometimes it is not blocked by cname. i found it unblocked in my log even tho doubleclick was blocked

**Comment by jordanelliott23** [comment]
@Alex-302

**Comment by jordanelliott23** [comment]
for example i manually tried reaching a domain and it was blocked but when the app reached out it wasn't because the cname wasn't contacted
