### ISSUE TITLE
yts.mx

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90343]
**Issue URL (Annoyance)**: https://yts.mx/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128601133-4f7d3f7a-29b9-4bee-94f1-07dd56060e80.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by jordanelliott23** [comment]
also on the movie pages

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://yts.mx/movies/vivo-2021)
