### ISSUE TITLE
taiwanese 104.com.tw ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#90389]
```
104.com.tw###board-27
or
104.com.tw##.advert-type21, .d-flex ?
```

![image](https://user-images.githubusercontent.com/75058881/128623112-6ccb95d1-c513-4bec-b8f9-afa94c8d3676.png)

**Comment by Alex-302** [comment]
Need screenshot with opened devtools with this element.
