### ISSUE TITLE
blog-sim.com (N: uBlock Origin) (T: Ads)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#90433]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Large placeholder near the top. I propose adding these entries to AdGuard Japanese:
```
blog-sim.com#?#.EntryInnerBlock:has(#ninja-blog-inactive)
blog-sim.com##.NinjaEntryCommercial
```

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/128642574-d4e4d2f9-ca6b-442c-9a2a-b96fa85f64b7.png)
</details><br/>

* **Expected behaviour**: 

The placeholder is removed.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/128642622-cce5b309-5591-4e83-b63a-4a0a6f0f6b16.png)
</details><br/>

***Steps to reproduce the problem***:

Visit the site.

***System configuration***

**Filters:**

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/128642647-54cdbe24-8674-473b-a77d-d8ec1fe7ac81.png)
</details><br/>

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 21H1 x64
Browser:                               | Chrome 92.0.4515.131 x64
AdGuard version:                       | uBO 1.37.3b7 + IDCAC 3.3.1
Filters enabled:                       | See above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by hirorpt** [comment]
URL: [https://naka.blog-sim.com/streets%20of%20simcity/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnaka.blog-sim.com%2Fstreets%2520of%2520simcity%2F)
`blog-sim.com` is one of [the 100 different domains offered by Ninja Blog](https://www.ninja.co.jp/blog/selectable-domain).

**Comment by Yuki2718** [comment]
Need some time.
