### ISSUE TITLE
riafan.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#9045]
***Description***:
* **Current behaviour**: 

Contains non-removable Yandex ads. They do not react to any kind of blocking, either automatic or manual.

<details><summary>Screenshot:</summary>

![567413904](https://user-images.githubusercontent.com/33634917/34430581-32ccbeca-ec6f-11e7-8cfa-676642378088.jpg)

</details><br/>

* **Expected behaviour**: 

Ads missed by AdGuard should be clearly blockable

</details><br/>

***Steps to reproduce the problem***:

1. Visit any kind of newspage at the site, e.g. https://riafan.ru/1012038-putin-povysil-mrot-do-prozhitochnogo-minimuma
2. Voila!

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows 8.1
Browser:                               | CentBrowser
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian, Spyware, Annoyances
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block third-party cookies (30), Disable third-party cache, Block browser location API, Send Do-Not-Track header, Hide IP (209.141.53.254)
Helpdesk ID (if exists):               | 1013323

**Comment by Alex-302** [comment]
Не повторяется. Нужна сохранённая страница.

**Comment by akmLaVx** [comment]
Пользователь сообщает, что проблема самоустранилась некоторое время назад.
