### ISSUE TITLE
spotiflix.site

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#90457]
[https://spotiflix.site/assistir-ou-baixar-o-filme-milagres-de-jesus-o-filme-completo-e-dublado](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://spotiflix.site/assistir-ou-baixar-o-filme-milagres-de-jesus-o-filme-completo-e-dublado)

The download button under the video player is legit, but you have to click on it twice to get to the actual download page. People who only click on it once might think it's fake.

![download](https://user-images.githubusercontent.com/35470489/128655438-68c6540c-fb31-4f52-9896-7f9a87cb3062.png)

The first click opens an `alternativecpmgate.com` ad page blocked by Easylist. 

The second click goes to the correct download page:

![download](https://user-images.githubusercontent.com/35470489/128655516-0db73048-29b4-453a-8345-2dd3ec9dd3f4.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Cannot be prevented completely. Same popup for ad and video, just server redirects to different places.
