### ISSUE TITLE
shopify tracker 

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#90523]
||knoinsights.com^
||knocdn.com^

i found these two in my log after making a purchase. they are used for shopify analytics. there was no subdomains. if u go to the first website it basically says its used for analytics

**Comment by Alex-302** [comment]
Not sure about knocdn.com, probably shop's CDN.
Did you try to make purchase after blockeing knoinsights.com?(clear log before this)
