### ISSUE TITLE
imdb.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#90546]
[https://www.imdb.com/find?q=shadows&s=tt](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.imdb.com/find?q=shadows&s=tt)

[https://www.imdb.com/title/tt0091251/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.imdb.com/title/tt0091251/)

These ad banners shown to logged-in users are currently just hidden instead of being blocked, but apparently blocking them altogether doesn't break anything:

 `||m.media-amazon.com/images/I/*$image,domain=imdb.com`

Their new design is heavier, so adding this will help slower connections.
 
![ads](https://user-images.githubusercontent.com/35470489/128802826-d254743f-d50f-422f-aac2-d1efee44627e.png)

 Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Too wide rule. 100% it will break something.
