### ISSUE TITLE
Taiwanese Chunghwa Telecom (CHT) ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#90551]
https://csapp.cht.com.tw/CustService/Web/payment-web.html#/PaidResult --> https://csapp.cht.com.tw/CustService/Web/payment.js?d=190426 --> https://csapp.cht.com.tw/CSAPP/SSO/dashboard/SiteCoreADItems --> 
- https://web-eshop.cdn.hinet.net/eShop%20Images/APP/1280x720/20200630_us_1280x720.jpg
- https://web-eshop.cdn.hinet.net/eShop%20Images/AD%20Banner/1280x720/202012011357-1_20210728154342.jpg
- https://web-eshop.cdn.hinet.net/eShop%20Images/AD%20Banner/1280x720/202012011357-1_20210728154342.jpg
- https://www.cht.com.tw/Prepaid/recharge/BuyList?utm_source=123_app&utm_medium=referral&utm_campaign=Prepaid_forstu&utm_term=202108&utm_content=1280x720
- ...

```
||csapp.cht.com.tw/CSAPP/SSO/dashboard/SiteCoreADItems
||web-eshop.cdn.hinet.net/eShop%20Images/AD%20Banner^
csapp.cht.com.tw###ads_swiper
```

![image](https://user-images.githubusercontent.com/75058881/128819097-032cdb1a-aa74-4e5a-8056-cd77f5931340.png)

![image](https://user-images.githubusercontent.com/75058881/128820147-d5897b90-263d-49ce-bd37-4ca838b54442.png)

![image](https://user-images.githubusercontent.com/75058881/128820151-73d7fc52-e14d-4076-a4fb-260cfb663662.png)

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/128820392-ee9027f4-a53a-47b7-92da-bd91c10a4ce6.png)

**Comment by Alex-302** [comment]
Dsngerous, like `-ttcdn-tos.pstatp.com` which breaks many sites aтв was removed.
