### ISSUE TITLE
senglehardt.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#9059]
***Description***:
* **Current behaviour**: 

A third-party script can fetch the login and password entered into the respective fields even before they are submitted to the server.

Customer-provided description: "As the site suggested, I created a fake email address with a password
and saved those with chrome beta for Android. Going to the next page
as directed, I see the email address get snooped. There's a note that
says Chrome requires that this page be interacted with to snoop the
password. Any click on that page populates the password. I have a
screenshot to demonstrate that I'll include when you auto reply to me.
PC Magazine says this has long been a vulnerability used to scam
visitors on a hidden page."

<details><summary>Screenshot:</summary>

![screenshot_20171228-124052](https://user-images.githubusercontent.com/33634917/34436211-2470c92a-ec9c-11e7-9902-b5aa20e7cfbd.png)

</details><br/>

* **Expected behaviour**: 

Login/password should not leak to any 3rd-party scripts.

***Steps to reproduce the problem***:

Open the site and try to enter login/password into the respective field.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.1
Browser:                               | Chrome BETA 
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Mobile Ads filter", "Simplified domain names filter", "Anti-Adblock Killer | Reek"
AdGuard mode (Android only):           | Proxy
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On, default
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1138191

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Please post direct link.
