### ISSUE TITLE
Enabling "Adguard Spyware Filters" in Ublock Origin disables call functionality in Web Skype

### ISSUE THREAD

**Issue by MavropaliasG** [AdguardTeam/AdguardFilters#9063]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Enabling "Adguard Spyware Filters" in Ublock Origin disables call functionality in Web Skype
* **Current behaviour**: Go to https://web.skype.com/, enable "Adguard Spyware Filters" in Ublock Origin and refresh. You will see the call icon being disabled.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: Enabling "Adguard Spyware Filters" in Ublock Origin should not disable call functionality in Web Skype

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***: Go to https://web.skype.com/, enable "Adguard Spyware Filters" in Ublock Origin and refresh. You will see the call icon being disabled.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***
Manjaro Linux KDE, chromium Version 63.0.3239.84 (Developer Build) (64-bit)
**Filters:**
Adguard Spyware Filters
[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Manjaro Linux KDE
Operating system version (Android/iOS) | ?
Browser:                               | chromium Version 63.0.3239.84 (Developer Build) (64-bit)
AdGuard version:                       | uBlock Origin v1.14.22
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Thanks, fixed.

**Comment by MavropaliasG** [comment]
Great !
