### ISSUE TITLE
flipboard.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90641]
**Issue URL (Annoyance)**: https://flipboard.com/@mrwolf6216/cyber-security-chronicle-emboqa6az/cybersecurity-firm-mandiant-uncovers-chinese-espionage-group-unc215-s-activity-i/a-OQCJv9otSle2UBcePB9Apg%3Aa%3A77430877-041aeefcd0%2Falgemeiner.com

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128968985-2e79fe35-9aca-40ef-a37c-8b0b77a084fd.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can't reproduce
@AdguardTeam/filters-maintainers please take a look

**Comment by chirag127** [comment]
I can still reproduce it 
![image](https://user-images.githubusercontent.com/76880977/129426648-932a50ab-e140-4f3e-ab69-02111efbb8e5.png)
