### ISSUE TITLE
www.algemeiner.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90643]
**Issue URL (Incorrect Blocking)**: https://www.algemeiner.com/2021/08/10/cybersecurity-firm-mandiant-uncovers-chinese-espionage-group-unc215s-activity-in-israel/

> page shifting left

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128968811-a3d0b34d-cfac-4899-9749-c751f46274a6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
> page shifting left

It's their design.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/129975003-fe785a4f-b67c-4878-bafe-dce61f8fe730.png)

</details><br/>
