### ISSUE TITLE
www.tripadvisor.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90648]
**Issue URL (Annoyance)**: https://www.tripadvisor.in/ShowTopic-g293860-i511-k10448834-How_dirty_is_India-India.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128969249-8c04940f-50d1-43fa-bedb-c4a73eeebecc.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
This is part of site's functionality.
For user rules:
`tripadvisor.in###ALSO_VIEWED_LIST`
