### ISSUE TITLE
thecybersecurity.news

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90644]
**Issue URL (Annoyance)**: https://thecybersecurity.news/general-cyber-security-news/chinese-espionage-group-unc215-targeted-israeli-government-networks-11845/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128968895-527aeb7c-0535-4a3a-832e-341ade922ec6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
