### ISSUE TITLE
www.business-standard.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90655]
**Issue URL (Annoyance)**: https://www.business-standard.com/article/current-affairs/tired-of-dirty-delayed-trains-railways-to-rank-best-worst-zones-trains-117120800326_1.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128970176-2a27424f-ec00-49fc-bfb3-da9ea6e6a770.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
It is useful. They infowm user about paid subscription to read article.
