### ISSUE TITLE
qz.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90656]
**Issue URL (Annoyance)**: https://qz.com/india/1489181/ahead-of-2019-play-the-poll-board-game-of-dirty-indian-politics/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128970410-36f10582-2be4-4741-841b-3b64feaa02df.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Not sure. 
For user filter:
`qz.com###article-content > div > p > em`

**Comment by chirag127** [comment]
@Alex-302 

I am complaining about the grey box .

**Comment by chirag127** [comment]
> Not sure.
> For user filter:
> `qz.com###article-content > div > p > em`

Either way I'm pretty sure that this rule will create false positives.

**Comment by Alex-302** [comment]
I don't know. They forbid to open article without money. Found in dev tools.

**Comment by chirag127** [comment]
> I don't know. They forbid to open article without money. Found in dev tools.

Is that so? Here in India I can open it without any paywall.
