### ISSUE TITLE
tls13.mitm.watch

### ISSUE THREAD

**Issue by kasper93** [AdguardTeam/AdguardFilters#9067]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:  Flash object is blocked.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

* **Expected behaviour**: Flash object should not be blocked.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***Steps to reproduce the problem***: Click "Start the test" button.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

Following filter is to blame:
```
##object[width="100"][height="100"]
```

I skipped all additional information as they are irrelevant to the issue.

**Comment by Alex-302** [comment]
fixed.
