### ISSUE TITLE
outlook.live.com is slow and takes longer to load

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#90686]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

https://outlook.live.com/mail/0/ is slow with AdGuard AdBlocker extension

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

It's a single scroll:

![screencast 2021-08-11 12-27-20](https://user-images.githubusercontent.com/15856304/129005437-57fdab72-fd87-412c-b4e0-048c5d08d541.gif)

</details><br/>

* **Expected behaviour**: 

Outlook scrolls fast 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows / macOS
Browser:                               | Chrome 92.0.4515.131
AdGuard version:                       | 3.6.6
Filters enabled:                       | Base, Tracking protection, Turkish, Russian, Chinese, useful ads
Helpdesk ID (if exists):               | 527431

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Eugene-Savenko** [comment]
Original complaint:

> Whilst using your extension. www.outlook.com is very slow when and it takes time to load and has become useable to use. Outlook will literally not fuction and its getting frustrating. Is this a recent bug or has microsoft detected that i am using adblocker and is purposefully slowing down outlook to the point in which it becomes unuseable to use. Can you please look into this matter? 

Please see links below as other people are have the issues i am having. 

https://adblockplus.org/forum/viewtopic.php?f=1&t=82004

https://www.reddit.com/r/uBlockOrigin/comments/m2o1u6/outlook_very_slow_to_load_last_few_days/

**Comment by Yuki2718** [comment]
@BlazDT Maybe a known conditional issue, see https://forums.lanik.us/viewtopic.php?f=64&t=45986&p=159406&hilit=outlook#p159406

@Eugene-Savenko 
Test adding `@@||pipe.aria.microsoft.com^$domain=outlook.live.com` to User rules and see if it helps.

**Comment by Eugene-Savenko** [comment]
The user who reported the problem to support states that these rules don't help:

> Yes i did try the rules and they did not work. 
> I have disabled adguard on outlook for now unless a fix is issued.

**Comment by Alex-302** [comment]
@Eugene-Savenko Please try `@@||outlook.live.com^$elemhide,important`
