### ISSUE TITLE
qz.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90734]
**Issue URL (Annoyance)**: https://qz.com/india/1489181/ahead-of-2019-play-the-poll-board-game-of-dirty-indian-politics/

> newsletter leftover greybox.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/128970410-36f10582-2be4-4741-841b-3b64feaa02df.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
@chirag127 
I don't see this leftover, please click on this element right mouse button > inspect, make a screenshot and send here

**Comment by chirag127** [comment]
![image](https://user-images.githubusercontent.com/76880977/129924489-cd9cb1c2-d4ef-4713-a947-caab61628aeb.png)
