### ISSUE TITLE
upstore.net 

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#90816]
**Issue URL (Annoyance)** : https://upstore.net/tYYcpib

> click on slow download for timer.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/129245938-5da72d04-f1ab-410a-af85-c983619aa9a2.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352294-46ac9f21-4436-4822-8702-c7d7c09f0563.png)
</details><br/>

**Comment by Yuki2718** [comment]
Skipping countdown and DL doesn't start, apparently is unfixable.

**Comment by zloyden** [comment]
Added a rule that doesn't break DL on my end, but if it's does on yours, let us know.

**Comment by neer9** [comment]
> Skipping countdown and DL doesn't start, apparently is unfixable.

Apparently @Yuki2718 was wrong.

**Comment by Yuki2718** [comment]
Yeah that work. Didn't test 0.5 boost TBH.

**Comment by neer9** [comment]
Are you sure you had
https://github.com/AdguardTeam/AdguardFilters/issues/90813 properly?

**Comment by neer9** [comment]
@Yuki2718
Are you sure you had tested
https://github.com/AdguardTeam/AdguardFilters/issues/90813 properly?

**Comment by Yuki2718** [comment]
> Are you sure you had #90813 properly?

Yes, they check on server side and whatever the last parameter in adjust-setInterval is (nor set-constant solution), the site returns error.
