### ISSUE TITLE
rapidgator.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90813]
**Issue URL (Annoyance)**: https://rapidgator.net/file/b1f34aa331edf7548aa37f2be2de4075/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129244897-2aa9236b-8640-4ea3-bc39-231a35dfd0ac.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment]
Skipping countdown breaks DL, is not fixable.

**Comment by Yuki2718** [comment]
@zloyden On my end 0.5 doesn't work but 0.8 does. Not sure it it's worth adding TBH.

**Comment by zloyden** [comment]
> On my end 0.5 doesn't work but 0.8 does. Not sure it it's worth adding TBH.

Test it several times. If it's ok, I suppose you can add to our filters.

**Comment by Yuki2718** [comment]
Got DL restriction, will test later (changing IP is a bit tedious).

**Comment by zloyden** [comment]
Ah. wait a second, the value is `0.8`. Maybe not worth it.

**Comment by Yuki2718** [comment]
Okay, apparently the minimal working value is 0.6.

**Comment by chirag127** [comment]
it not work? i get error after the time.

**Comment by Yuki2718** [comment]
> it not work? i get error after the time.

Such thing can happen and has happened in past, works for one and breaks for another. This is why I'm not very willing to fix by adjusting the parameter. I'll remove the filter.
