### ISSUE TITLE
https://hentaiworld.tv/

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#90840]
**Issue URL (Ads)** : https://hentaiworld.tv/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/129251278-289f4221-3c01-42d1-85ce-7b965bc4dc1f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by Disqu3-mirOir-qt** [comment]
hentaiworld.tv##a[href*="epvkjs.com"]
