### ISSUE TITLE
moviesrush.one

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90903]
**Issue URL (Anti Adblock Script):** https://moviesrush.one/18-step-sisters-2014-x264-english-webhd-480p-273mb-720p-751mb-mkv/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129364426-7d8a799f-b890-4b66-8905-c6c11814e54d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by thinksheiscool** [comment]
@Yuki2718 I encountered this in uBlock Origin.

**Comment by IThinkIAmCool** [comment]
> @Yuki2718 I encountered this in uBlock Origin.

@thinksheiscool just turn on the adguard base filter . I don't really understand the point of copying the rules to ubofilters.

**Comment by Yuki2718** [comment]
Or open an issue ticket or PR in uAssets. I've recently requested the same in uAssets too: https://github.com/uBlockOrigin/uAssets/issues/4501#issuecomment-898936303

**Comment by thinksheiscool** [comment]
@IThinkIAmCool I was confused. Btw, did you wait for me to delete the account?

**Comment by thinksheiscool** [comment]
> > @Yuki2718 I encountered this in uBlock Origin.
> 
> @thinksheiscool just turn on the adguard base filter . I don't really understand the point of copying the rules to ubofilters.

Because uBO addresses anti adblock mechanisms.
