### ISSUE TITLE
https://www.interviewbit.com/data-structure-interview-questions/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90906]
**Issue URL (Annoyance)**: https://www.interviewbit.com/data-structure-interview-questions/

<details><summary>Screenshots:</summary>

https://www.interviewbit.com/data-structure-interview-questions/
![image](https://user-images.githubusercontent.com/76880977/129371129-466ab0ea-66d6-4a15-94a4-a5759ca79b99.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Do not write full url in issue names.
