### ISSUE TITLE
https://www.digitalvidya.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90915]
**Issue URL (Annoyance)**: https://www.digitalvidya.com/blog/all-about-data-structures-and-algorithms-in-python/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129372650-3e6bd491-4369-4836-b3a7-cd48c736966e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
This is not email subscription.
