### ISSUE TITLE
savethestudent.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90924]
**Issue URL (Annoyance)**: https://www.savethestudent.org/student-jobs/top-10-smarter-ways-to-find-a-job.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129375122-1f638bd3-567a-41c9-8357-743fc1594f9b.png)
![image](https://user-images.githubusercontent.com/76880977/129375123-aabf7130-4372-43af-8502-51f262b1ba4e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by chirag127** [comment]
adguard please resolve this issue.

**Comment by AdamWr** [comment]
Fixed newsletter, but I'm not sure if this section with "Hottest Deals" should be blocked, so please add these rules to user filter:
```
savethestudent.org#?#.article-sidebar > .-cards:has(> .row > .col-xs-12 > h4:contains(/^Hottest Deals$/))
savethestudent.org#$#.article-sidebar > .-cards[style="display: none !important;"] + .-cards { margin: 0 !important; }
```
