### ISSUE TITLE
techrepublic.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91029]
**Issue URL (Annoyance)**: https://www.techrepublic.com/article/python-programming-language-a-cheat-sheet/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129446418-e4792734-39ec-4ea6-ba1c-6d0a27346484.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I don't think we should block this element,, please add to user rules: `niit.com##.commerce-disclaimer`
