### ISSUE TITLE
infoworld.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91021]
**Issue URL (ad)**: https://www.infoworld.com/category/java/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129445915-d4d28dcb-2402-46e8-9f5a-37c9683f2b13.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
May be interesting for users.
