### ISSUE TITLE
udacity.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91025]
**Issue URL (Annoyance)**: https://www.udacity.com/course/introduction-to-python--ud1110

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129446163-740984ca-cd3c-499f-bb19-cc9aca0fea3a.png)
![image](https://user-images.githubusercontent.com/76880977/129446164-962baf25-0bbe-4ec1-9c27-b225ed41813c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can' reproduce this popup, is it still relevant?

**Comment by chirag127** [comment]
it's solved now
