### ISSUE TITLE
https://www.hackerearth.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91043]
**Issue URL (Annoyance)**:
 https://www.hackerearth.com/challenges/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129447074-e14a33a9-12f9-4306-98fa-8317e01ef393.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Thair own YT chanel. Only one link on the site.
