### ISSUE TITLE
pluralsight.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91041]
**Issue URL (Annoyance)**: https://www.pluralsight.com/courses/what-is-programming

<details><summary>Screenshots:</summary>

https://www.pluralsight.com/courses/what-is-programming
![image](https://user-images.githubusercontent.com/76880977/129447020-62ebe237-9f4b-4ae2-89c6-cb94005c0593.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
It seems this issue is not relevant anymore. Fixed yellow promo block.
