### ISSUE TITLE
vermoegen.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#91066]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: History manipulation (leads to "fake" google) when i try to go back
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="604" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/129458742-295732f6-2844-4b38-a893-248625eae220.PNG">

</details><br/>

***Steps to reproduce the problem***:

1. Search on Google: `vermoegen.org`
2. Click on the result with the site `vermoegen.org` to open it
3. When i try to go back with the browser "go back" button it redirect to a "fake" google site (see screenshot)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.6.6
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by NaylyaM** [comment]
Hi,

We've checked this on our side, there seems to be an issue with Firefox browser. In this case we could only advise to contact Firefox team, so that they could check this on their side.

Best regards,
Naylya
