### ISSUE TITLE
www.dm5.com

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#9108]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Issue URL: www.dm5.com — Missed Ad
Issue Type: Ads
Comment:
Screenshot: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/B7WnI5M.jpg)

![image](https://i.imgur.com/UMeEJbb.png)

![image](https://i.imgur.com/rTBG7S3.png)
</details><br/>

***Steps to reproduce the problem***:
Visit www.dm5.com.
You'll find the ads there.
Well, EasyList China filter can block the ads.
The rule: ||mediav.com^$third-party
Maybe you can add that rule for English filter and other better rules for Simplified domain names filter.
Especially, you know that AdGuard Pro for iOS can't block ads if those ads domains aren't in Simplified domain names filter.
||mediav.com^$third-party is available for English filter.
But ||mediav.com^$third-party isn't accepted by Simplified domain names filter, right?
www.mediav.com is a local ad company in China.
If you don't want to block the whole mediav.com domain, you can add other better rules.
Thanks!

These are its official apps.
Android:
https://goo.gl/mUY2wk

iOS:
https://goo.gl/vgsx9X

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | Android/iOS
Browser:                               | ?
AdGuard version:                       | AdGuard for Android v.2.10.176 / AdGuard Pro for iOS v1.3.3
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default/Blacklist mode)
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default Protection, AdGuard Pro for iOS with AdGuard DNS server
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added. Please check.

**Comment by lancelot-moon** [comment]
Hi,

1. Read any comics on www.dm5.com via Safari on iphone.
AdGuard content blocker for Safari can't block the ad.
dm5.hk also uses the ad domain, adyun.com.

||adyun.com^$third-party
The above rule can block the ads here.

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/cHr7sIl.png)

![image](https://i.imgur.com/r8Xey3I.png)
</details><br/>

2. Read any comics on www.dm5.com via mobile browsers.
AdGuard content blocker for Safari can't block the ad.

/wxh_asy.js$domain=1kkk.com|dm5.com|dm5.hk
The above rule can block the ads here.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iazC597.jpg)
</details><br/>

Thanks.

**Comment by Alex-302** [comment]
Just enable EasyList China
