### ISSUE TITLE
medium.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#91091]
<details><summary> При попытке выделения любого слова в тексте после отпускания левой кнопки мыши или после двойного клика выделенное сбрасывается и появляется "всплывашка" с кнопкой:</summary>

![изображение](https://user-images.githubusercontent.com/17948007/129463276-292c592a-56bb-48b8-abb6-86dd766ae5d5.png)
</details>

 Поэтому невозможно произвести действия из контекстного меню - в 'Раздражители'.
 Для возвращения способности выделения: `medium.com#%#//scriptlet('prevent-addEventListener', '/mouse/')`

[https://medium.com/web-standards/logical-css-props-c5046c563640](https://href.li/?https://medium.com/web-standards/logical-css-props-c5046c563640)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.6 | Базовый AdGuard; &nbsp; Русский | Стандарт
 FireFox v78.10 ESR | Счётчиков и аналитики; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Раздражителей; &nbsp; Виджетов социальных сетей

**Comment by Alex-302** [comment]
У меня не повторяется сброс выделения. Добавил в соц фильтр одно правило, проверь после обновления.

**Comment by XX-J** [comment]
Удивительно, но работает! Спасибо.

 Только вот думаю это больше к раздражителям относится, чем к соц. блок-ам. Т.к. при нажатии на ту, единственную кнопку, которая всплывала, сайт просит зарегистрироваться для активации соответствующей функции.
