### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#91096]
Если зайти в обсуждение в ВКонтакте незарегистрированным и пытаться нажимать на картинки в основном сообщении или в комментариях, то картинки открываться не будут.

<details><summary>Screenshot'ы:</summary>

![2021 08 15-1](https://user-images.githubusercontent.com/17948007/129467260-f6fdae75-d07c-4a1c-8b25-711a15b6b970.png)
----------
----------
![2021 08 15-2](https://user-images.githubusercontent.com/17948007/129467263-3c52050c-2c4f-4934-bbe4-c38602842688.png)
</details>

 Это происходит из-за правила `vk.com#%#//scriptlet('set-constant', 'window.Unauthorized', 'undefined')` из "Фильтра раздражителей". Если отключить это правило, то после начала пролистывания комментариев каждый раз появляется раздражающее окно с просьбой зарегистрироваться или войти в аккаунт. Но и картинки начинают показываться после такого же окна с просьбой зарегистрироваться и нажатия справа внизу "Не сейчас".

 Проблема решается добавлением правила `vk.com#%#//scriptlet('set-constant', 'window.PageBottomBanners', 'undefined')` в дополнение к вышеозначенному. Оно позволяет обходить окно с просьбой зарегистрироваться при просмотре картинок в обсуждении.

`window.PageBottomBanners == Object { hideCookiesPolicy: hideCookiesPolicy(), initUnauthBanner: initUnauthBanner(e), initBanner: initBanner(e) }`

[https://vk.com/wall-28391636_7120](https://href.li/?https://vk.com/wall-28391636_7120)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.6 | Базовый AdGuard; &nbsp; Русский | Стандарт
 FireFox v78.10 ESR | Счётчиков и аналитики; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Раздражителей; &nbsp; Виджетов социальных сетей

**Comment by Alex-302** [comment]
Пока вот так сделал
`vk.com#%#//scriptlet('set-constant', 'window.PageBottomBanners.initUnauthBanner', 'noopFunc')`

**Comment by XX-J** [comment]
Работает.
