### ISSUE TITLE
AdGuard is not working/filtering chrome browser of second google account.

### ISSUE THREAD

**Issue by ShamilSd-ux** [AdguardTeam/AdguardFilters#91196]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: On android mobile we can add multiple google accounts. We will get chrome browsers of different google Accounts. Adguard should filter all browsers. 1st or 2nd or 3rd and on..., 

* **Current behaviour**: But Adguard is filtering ads from only first google account's chrome browser. Second google account's chrome browser is running ads indefinetely. Adguard filters are  not working on second chrome browser. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

![First Account google Chrome](https://user-images.githubusercontent.com/81691084/129532673-86707f07-db95-453c-923a-24edbbd8e061.jpg)

Same Page in second Browser with AD
![Second  Account google Chrome](https://user-images.githubusercontent.com/81691084/129535630-846b79b7-f42b-458c-9d78-f6e3d2e33591.jpg)

![first account google chrome](https://user-images.githubusercontent.com/81691084/129532544-dfa9d271-56b5-48ff-9777-bf1c787e3dd7.jpg)

Same page in second browser with AD
![Second account google chrome](https://user-images.githubusercontent.com/81691084/129532713-75d3aac9-b52b-472a-9ef9-e2348ae14ac8.jpg)

First  and Second Browsers of two google accounts in an Android Mobile.
![Both Google Chromes on Android screen](https://user-images.githubusercontent.com/81691084/129532828-5f68f25e-a349-480c-a372-41fcf4ee135e.jpg)

 Kindly go through the pictures and urls to find the difference and how Ads are loading in  2nd version of google. Please solve this issue immediately.

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) |  Android 9
Browser:                               | Chrome
AdGuard version:                       | 3.6.2
Filters enabled:                       | Yes
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On 
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           |  Default 
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Google ads must be blocked.
Please report ads from AdGuard: https://kb.adguard.com/en/technical-support/reporting-tool
