### ISSUE TITLE
http://www.markammay.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91214]
**Issue URL (Annoyance)**:

http://www.markammay.com/100-creative-ideas-for-a-website/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129555142-014bb40b-3eaf-469f-b441-d909f4f7a684.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
5310 visitors/month
`markammay.com##.markamayNewsletter`
