### ISSUE TITLE
https://www.wpbeginner.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91211]
**Issue URL (Annoyance)**: https://www.wpbeginner.com/beginners-guide/best-website-ideas-to-launch/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129554245-a0d83b9b-ea71-4645-850b-c40de167557a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I think we should not hide this element, for user rules: `wpbeginner.com##a[href="https://www.wpbeginner.com/blueprint/"] > img`
