### ISSUE TITLE
https://siteefy.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91213]
**Issue URL (Annoyance)**:
https://siteefy.com/website-ideas/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129555098-7e0e713d-d8b6-4ea5-a873-1b2b0ec681f3.png)
![image](https://user-images.githubusercontent.com/76880977/129555101-bb082304-931b-48d1-be8a-09f8dcf63744.png)
![image](https://user-images.githubusercontent.com/76880977/129555102-24fa89af-d92b-42c8-81fc-d98f7c81e1f6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
About 20000 visitors/month.
for user rules: `siteefy.com##div[id^="brave_popup_"]`
