### ISSUE TITLE
wikihow.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91233]
**Issue URL (tracking.)** :https://www.wikihow.com/Coaches?tab=mindful&?utm_source=wikihow

> Tracking parameter not  removed.

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
It will work in ext v4.0
