### ISSUE TITLE
the-japan-news.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#91255]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
White screen when you clicked any article

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![japannews](https://user-images.githubusercontent.com/58900598/129602982-4894ec0f-ca9e-4e9f-b836-d724c343d348.png)

</details><br/>

* **Expected behaviour**: 

Article can be read

</details><br/>

***Steps to reproduce the problem***:

1. Visit `https://the-japan-news.com/` with TPF enabled
2. click any article

***System configuration***

**Filters:**

Base, TPF, and JPF

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Brave 1.28.105
AdGuard version:                       | 3.6.6
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled
Helpdesk ID (if exists):               | ?

**Notes:** 

Caused by blockage of `the-japan-news.com/modules/js/lib/fgp/fingerprint2.js` and redirecting to noopjs/nooptext doesn't work.

**Comment by AdamWr** [comment]
Could you please check this rule (as a workaround until redirect resource for `Fingerprint2` will be added):
```
the-japan-news.com#%#//scriptlet('set-cookie-reload', 'fp', '1')
```

**Comment by Yuki2718** [comment]
@AdamWr Yes, working!

**Comment by AdamWr** [comment]
Okay, I have added this rule.
Thank you for your reply.
