### ISSUE TITLE
car.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#91310]
**1**. Раздражители:

 Самый главный раздражитель это то, что страница самопроизвольно перезагружается ~ через 2 минуты простоя:
`car.ru#%#//scriptlet('prevent-setTimeout', 'car__idle')`

 Остальные - 1 и 2 на картинке:
`car.ru##.close-button, .search-example`

 **2**. Социалочка:

 С 3-го по 6-й на картинке:
`car.ru##.list-car-social-gray, .main-page__content-middle-dzen`

<details><summary>Screenshot:</summary>

![2021 08 17-1](https://user-images.githubusercontent.com/17948007/129661031-8fc97db0-d815-448a-ac18-b560e37c7138.png)
</details>

 **3**. Допы:

 7-й, нормализация отмечаемого пункта:
`car.ru#$#.form-group-checkbox__form-control { width: 1em !important; height: 1em !important; }`

 Открепление шапки:
`car.ru#$#header { position: absolute !important; }`

 Сделать так, чтоб текст на кнопке-ссылке в "Телеграм" влазил:
`car.ru#$#.page-top-sell__button { margin-left: 20px !important; }`

[https://car.ru/news/gibdd/118608-toyota-rav4-naehala-na-koleso-ot-furyi-i-tri-raza-perevernulas-v-vozduhe/](https://href.li/?https://car.ru/news/gibdd/118608-toyota-rav4-naehala-na-koleso-ot-furyi-i-tri-raza-perevernulas-v-vozduhe/)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.6 | Базовый AdGuard; &nbsp; Русский | Стандарт
 FireFox v78.10 ESR | Счётчиков и аналитики; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Раздражителей; &nbsp; Виджетов социальных сетей

**Comment by Alex-302** [comment]
Вёрстку трогать лишний раз не стоит, не всем понравится.

**Comment by XX-J** [comment]
Что, даже 4 блока с "Подпиской" не уберёшь?

**Comment by Alex-302** [comment]
> Не сработало твоё решение по разминированию таймбомбы.

Что-то фоксовое. Посмотрим.

**Comment by XX-J** [comment]
**1**. Раздражитель - "Добавить в избранные источники". Появляется ~ в 50% случаев - зависит от статьи или иных обстоятельств.

<details><summary>Screenshot:</summary>

![2022 06 27-1](https://user-images.githubusercontent.com/17948007/176003858-ac66f3b2-aef6-4225-9034-cb9fdb921863.png)
</details>

`car.ru##.yandex-news-promo`

___________________________________________________

 **2**. Помимо перезагрузки страницы со статьёй ~ через 2 мин. (твоё правило не работает), перезагружается ещё и главная через 30 мин.

 Обе проблемы решаются единым правилом: `car.ru#%#//scriptlet('prevent-setTimeout', 'location')`

___________________________________________________

 **3**. Если в любой статье открыть картинку, то она откроется в их просмотровщике. В нём предусмотрена реклама в правой колонке, которая скрыта. Но пустое место от рекламы остаётся и занимает значительную часть экрана. Стилями там поправлять - много, проще удалить класс 'lg-with-ads'.

<details><summary>Screenshot:</summary>

![2022 05 13-1](https://user-images.githubusercontent.com/17948007/176009524-35b0642a-f73f-46d0-9541-fda91c907c55.png)
</details>

`car.ru#%#//scriptlet('remove-class', 'lg-with-ads')`

___________________________________________________

 **4**. С 4 по 7 пункт из первого сообщения так и не решено.

___________________________________________________

[https://car.ru/news/autogramota/217491-kak-vyibratsya-iz-tonuschego-avtomobilya-8-pravil/](https://href.li/?https://car.ru/news/autogramota/217491-kak-vyibratsya-iz-tonuschego-avtomobilya-8-pravil/)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v4.0.181 | Базовый AdGuard &nbsp; &nbsp; &nbsp; &nbsp; Русский | Стандарт
 FireFox v78.13 ESR | Счётчиков и аналитики &nbsp; &nbsp; &nbsp; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Виджетов социальных сетей &nbsp; &nbsp; &nbsp; &nbsp; Раздражителей | +Удаление параметров отслеживания

**Comment by XX-J** [comment]
А ~компот~ **2** и **3**?
