### ISSUE TITLE
Incorrect blocking of the services used by the bitcoin.com apps 'shareable link' feature

### ISSUE THREAD

**Issue by incarnis** [AdguardTeam/AdguardFilters#91311]
I'm using the adguard DNS and private DNS and having issues with just one particular feature of the bitcoin.com app which otherwise is working great. It's the shareable link feature. Unfortunately being a mobile app it seems a little bit harder to figure out where exactly the problem lies here. Looking at IP log it could potentially be with the connection to the branch.io services:

api2.branch.io
cdn.branch.io

Or

nexus-websocket-a.intercom.io 

If anybody is willing to take this on I will gladly share some Bitcoin Cash for testing the shareable link feature within the app if need be. 

Thanks!

**Comment by Alex-302** [comment]
Hi. branch.io is used for analytics, and it is popular. We cannot remove it from DNS filter(like google analytics).

**Comment by incarnis** [comment]
Ok that does make sense. Thanks for the update!
