### ISSUE TITLE
https://mediakix.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91325]
**Issue URL (Incorrect Blocking)**: https://mediakix.com/blog/travel-vloggers-youtube-channels-adventure/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129674805-7b9a1924-46e1-4f62-8c2c-972314096138.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by gork7777** [comment]
This issue caused by `Fanboy's Social Blocking List` filter.

**Comment by krystian3w** [comment]
@ryanbr / @khrin / @montza / @smed79
