### ISSUE TITLE
https://au.reachout.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91339]
**Issue URL (Annoyance)**: https://au.reachout.com/articles/what-to-do-if-you-are-having-thoughts-about-wanting-to-die

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129684457-5ac870fb-4aad-4aa2-bbec-18dbdb57bec5.png)
![image](https://user-images.githubusercontent.com/76880977/129684458-ace7ce3e-4b77-4b57-97f0-9c728c7d8aa8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
The share widget is already blocked by `||hwc.reachout.com/dist/NROShare/NROShare.umd.js` rule (it was added 4 days ago)
