### ISSUE TITLE
megacatstudios.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#91380]
[https://megacatstudios.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://megacatstudios.com/)

Overlay after a few seconds on the site:

![overlay](https://user-images.githubusercontent.com/35470489/129756118-b0991a15-6b75-4456-916b-5c165cc754dd.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Too few visitors.
