### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#91414]
||zion-telemetry.api.cnn.io^
||snowplow-collector-*.amazonaws.com^
||collector.cdp.cnn.com^
||collector-dev.cdp-dev.cnn.com^

these appeared when clicking a news article in facebook app

**Comment by thinksheiscool** [comment]
@ryanbr

**Comment by thinksheiscool** [comment]
@pgl
