### ISSUE TITLE
https://influencermarketinghub.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91435]
**Issue URL (Annoyance)**:
 https://influencermarketinghub.com/how-to-become-a-youtuber/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129826705-5843ada3-027a-4d1e-8846-f11438e1da0f.png)

https://influencermarketinghub.com/how-to-become-a-youtuber/

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I found this element but it is invisible and doesn't pop up.

**Comment by chirag127** [comment]
@Sergey-Lyapin 
I can still reproduce . 
![image](https://user-images.githubusercontent.com/76880977/130402727-3da96421-efdf-4dc9-a426-94988d53b7d1.png)

**Comment by Sergey-Lyapin** [comment]
@chirag127 
I've found, thank you
