### ISSUE TITLE
gillette.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#91461]
||youradchoices.com^

also a adchoices logo on bottom of page

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://gillette.com/en-us/products/razors-trimmers-and-blades/mach3-razor)

**Comment by Alex-302** [comment]
I see one request only:
`https://youradchoices.com/DAA_style/YAC/icon.png`

Blocked 
```
||gillette.com/index.php?action=track_
||analytics.getshogun.com^$third-party
```
