### ISSUE TITLE
some suggestions for AdGuard URL Tracking filter

### ISSUE THREAD

**Issue by ahmedtds** [AdguardTeam/AdguardFilters#91536]
imdb adds a ref parameter during navigation to every link, it would be nice to add this to filter.

instagram - igshid parameters

twitter - ?s=20 or similar. 21 etc.. these are tracking parameters too

**Comment by Alex-302** [comment]
@ahmedtds Hi. Need sample links or how to reproduce.


> twitter - ?s=20 or similar. 21 etc..

Not tracking. Value the same on my end.

**Comment by ahmedtds** [comment]
@Alex-302 

Hi, it's believed these are tracking parameters as to where the share have originated.

Please take a look at these conversations:

https://twitter.com/MattNavarra/status/1380141874372087808
https://twitter.com/ScorpionoxVoid/status/1202199959128309760

**Comment by Alex-302** [comment]
It does not contain private info, just _probably_ type of client.

**Comment by ahmedtds** [comment]
@Alex-302 ok, what about imdb _ref params?

**Comment by krystian3w** [comment]
Maybe no safe is deletion (e.g. app break page, but addon can't reproduce glitch).

**Comment by Alex-302** [comment]
At the moment `_ref` cannot be removed. https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1846
