### ISSUE TITLE
celestialseasonings.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#91568]
||pixel.convertize.io^

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://celestialseasonings.com/)

**Comment by Alex-302** [comment]
Cannot reproduce.

**Comment by jordanelliott23** [comment]
it was on safari browser on ios appeared in my log.

**Comment by jordanelliott23** [comment]
what about this page 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://celestialseasonings.com/collections/sleepytime-tea/products/sleepytime-classic-herbal-tea)
