### ISSUE TITLE
commonsensemedia.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91579]
**Issue URL (Social Widget)** : https://www.commonsensemedia.org/movie-reviews/the-girl-next-door

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130031084-d65c54c4-6afc-4286-a939-fb6966aeb61d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Do not write redundant text to title. Host name only - `commonsensemedia.org`
