### ISSUE TITLE
https://href.li/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91589]
**Issue URL (Annoyance)**: https://href.li/?https://newzfeedz.com/?id=TFExb1pxR1pQdDNFMjdCT3libXhKM2lxL1lzZ0J4WmpXN1JYL2t6L2VJeGlqSnU2UWx4Mk84QUttS1J1THBQemd4ejVQWUgrd0dNQ1FBMThGdG9LdjNtNXZkUUNYWnBSaUlEUWFseGh3K0JSMUdWa1hvMjg1dFd0OU4wQi90QVpRNHZGZDBLUWRjTzY2UXN3QjhETGpIaFhYMlh6eUdmVlFuYllISG9RamFzVitJMGtWTWVCYWNJZDVWcFphcWduU1ZPZFVrZTBxQVNiTmpvOGpxbFJGSDZJOTFxZFBSaFZxejJYazVKQVBvZUVySFBWNjI0WFBrVE4rVmRzdkRnRlZ2NS9UVTBnOU1VaDdRK0VQWnVHZ0J6UytxRnNiWisxRFVBZ0dReEF2NEE9

> providing source link for timer 
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130037381-6fe34214-0d89-47de-a165-a682d804e001.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The site isn't working on my end.
