### ISSUE TITLE
bc.ca

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91626]
**Issue URL (Ads)** : https://www.heretohelp.bc.ca/screening/online/?screen=depression

<details><summary>Screenshots:</summary>

https://www.heretohelp.bc.ca/screening/online/?screen=depression
![image](https://user-images.githubusercontent.com/76880977/130093762-b7bfd4a9-89a3-44ec-83e2-63a09f63bec3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
This is not an ad. It's their design.
