### ISSUE TITLE
engineerskatta.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91676]
**Issue URL (Ads)** :https://www.engineerskatta.com/python1/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130145545-33d9e400-604d-4048-b48a-350d78dce2a0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
