### ISSUE TITLE
Yandex.Q

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#91685]
Остатки.

<details><summary>Screenshot:</summary>

![2021 08 19-1](https://user-images.githubusercontent.com/17948007/130162851-f92f4f9c-32f7-41ee-8609-54d5162bcbf2.png)
</details>

`yandex.*,~disk.yandex.*,~mail.yandex.*,~market.yandex.*,~toloka.yandex.*,~translate.yandex.*,~zen.yandex.*##.page_qQuestionRoute #page section > div > div > div[class]:not([data-id]):has(> div > div:not([class]):not([data-id]))`

 Допы:

 После блокировки остатков один раз появилась реклама в правом столбце, внизу:
`yandex.*,~disk.yandex.*,~mail.yandex.*,~market.yandex.*,~toloka.yandex.*,~translate.yandex.*,~zen.yandex.*##.page_qQuestionRoute #page > div > div + div + div > div > div > div > div + div`

 Ну и - закрепление шапки:
`yandex.*,~disk.yandex.*,~mail.yandex.*,~market.yandex.*,~toloka.yandex.*,~translate.yandex.*,~zen.yandex.*#$#.page_qQuestionRoute header { position: unset !important; }`

[https://yandex.ru/q/question/pochemu_kogda_odin_chelovek_zevaet_riadom_e67544db/](https://href.li/?https://yandex.ru/q/question/pochemu_kogda_odin_chelovek_zevaet_riadom_e67544db/)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.6 | Базовый AdGuard; &nbsp; Русский | Стандарт
 FireFox v78.10 ESR | Счётчиков и аналитики; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Раздражителей; &nbsp; Виджетов социальных сетей

**Comment by zloyden** [comment]
@XX-J эта реклама убирается скриптом AdGuard Extra, но сейчас вижу некоторые остатки. Правила мы не добавляем в русский фильтр - они долго не живут.
