### ISSUE TITLE
bestbuy.com

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#91698]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard base, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyance
I'm not sure if it should be addressed.
URL with the issue: `https://www.bestbuy.com/site/lenovo-smart-clock-with-google-assistant-gray/6335321.p?skuId=6335321`

**Comment by Alex-302** [comment]
What exactly?

**Comment by thinksheiscool** [comment]
@Alex-302 
![image](https://user-images.githubusercontent.com/89113298/130336492-cdfc1179-cf7b-47ee-a7ff-c302f802df9e.png)
