### ISSUE TITLE
cnbc.com

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#91696]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard base, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyance towards the bottom of the webpage.
URL with the issue: `https://www.cnbc.com/2021/08/19/china-tech-crackdown-tencent-warns-of-more-regulations-ahead-for-gaming.html`

**Comment by Alex-302** [comment]
Next time please add screenstots
```
<details><summary>Screenshot:</summary>

paste image here

</details>
```

**Comment by thinksheiscool** [comment]
> Next time please add screenstots
> 
> ```
> <details><summary>Screenshot:</summary>
> 
> paste image here
> 
> </details>
> ```

Is it legal? Isn't there a risk of getting sued when uploading screenshots of certain websites?
