### ISSUE TITLE
petitchef.ro

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#91693]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard base, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Ad leftovers.
URL with the issue: `https://www.petitchef.ro/retete/felul-principal/ciorba-de-curcan-fid-696321`

**Comment by Alex-302** [comment]
Fixed.
