### ISSUE TITLE
dotesports.com

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#91699]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard base, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Space
URL with the issue: `https://dotesports.com/valorant/news/g2s-valorant-superteam-punch-last-ticket-to-vct-masters-3-berlin`

**Comment by Alex-302** [comment]
Left - by design.
