### ISSUE TITLE
bizarre.kiev.ua

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#9169]
***Description***:
* **Current behaviour**:  Chat is completely broken. Cannot send and receive any messages.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<details><summary>Screenshot:</summary>

Not applicable, site is completely broken

</details><br/>

* **Expected behaviour**:  Should work w/o issues

***Steps to reproduce the problem***: Just log in to the site. Credentials: adg-test1/adg-test

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 v1703
Browser:                               | Opera (WebKit)
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Spyware, Social, Unblock, Russian 
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd Party Cookies (30), Block Browser Location API, Remove X-Client-Data Header, Send DNT Header
Helpdesk ID (if exists):               | 1506932

**Comment by Alex-302** [comment]
что-то он плохо работает. Без блокировщика:
![image](https://user-images.githubusercontent.com/8361299/34568711-59ebce92-f16f-11e7-86d6-7d07a1f8c20a.png)

**Comment by evgeniy-ADG** [comment]
У меня работает с выключенным AdGuard.

**Comment by akmLaVx** [comment]
Уточнение от юзера:

Хочу сообщить информацию, которая, возможно, окажется полезной.
1 октября чат сменил хостера, по крайней мере сменился неурезаемый баннер справа внизу окна чата, hosted by.
До 1 октября чат всегда работал с включенным AdGuard. 31 сентября, вечером, еще до смены хостера я находился в чате, 1 числа днем пытаясь зайти, заметил смену этого баннера и то, что чат так и не загрузился.
Думаю "поломка" чата и смена хостера как-то взаимосвязаны. До этого хостером значился Comstar, после Vodafone.
Только что решил выключить AdGuard и зайти в чат. Чат ожидаемо загрузился. Не выходя из чата попробовал включить AdGuard. Обратил внимание на долгую загрузку программы с работающим чатом.
С момента запуска программы и до появления главного окна прошло примерно 5 минут. Однако, программа загрузилась, но служба не запустилась.
В главном окне программы все плитки оказались "выключенными" и была красная кнопка "Восстановить службу".
Во время всех этих операций чат продолжил работу и продолжил работать и после восстановления службы.
Возможно какие-то изменения произошли в программе 31 сентября-1 октября, а возможно какой-то параметр в программе или в службе блокирует трафик от нового хотера

**Comment by Alex-302** [comment]
Похоже на баг проги. Исключения не помогают.

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2082](https://github.com/AdguardTeam/AdguardForWindows/issues/2082) via [**ZenHub**](https://www.zenhub.com/)
