### ISSUE TITLE
theloadout.com

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#91694]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard base, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Space
URL with the issue: `https://www.theloadout.com/`

**Comment by Alex-302** [comment]
Fixed. 
Also added some removeparam rules, for this URL
`https://www.microsoft.com/en-us/p/xbox-game-pass-for-console/cfq7ttc0k6l8?ranMID=24542&ranEAID=SJ/t98NDjrI&ranSiteID=SJ_t98NDjrI-oRpjm3ffWlN_WvqFk6pjzA&epi=SJ_t98NDjrI-oRpjm3ffWlN_WvqFk6pjzA&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=%28ir__ajn92maphgkfq1veegf9afsh0m2xrhiwpllfe9sy00%29%287593%29%281243925%29%28SJ_t98NDjrI-oRpjm3ffWlN_WvqFk6pjzA%29%28%29&irclickid=_ajn92maphgkfq1veegf9afsh0m2xrhiwpllfe9sy00&activetab=pivot:overviewtab`
