### ISSUE TITLE
yandex.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#91706]
[https://yandex.com/images/search?text=cat](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://yandex.com/images/search?text=cat)

I've taken a look at some of the other issues about this site, but haven't found any page about these annoyances.

Every time you clear your cookies:

![yandex](https://user-images.githubusercontent.com/35470489/130197160-d78be8f9-c651-4ee3-802c-f1acee508294.png)

When you use the `Open` button:

![yandex2](https://user-images.githubusercontent.com/35470489/130197174-fd7d593d-4350-4036-bc3f-8061c8be8f26.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
2 - extra click is required.
1 - fixed.
