### ISSUE TITLE
tech.hindustantimes.com/gaming

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#91747]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard base, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Social widgets
URL with the issue: `https://tech.hindustantimes.com/gaming`

**Comment by AdamWr** [comment]
I see only links to their Facebook/Twitter pages and we do not block it.
