### ISSUE TITLE
finder.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#91775]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyance
URL with the issue: `https://www.finder.com/`

**Comment by thinksheiscool** [comment]
Another annoyance on `https://www.finder.com/ca/top-online-computers-electronics-stores`

**Comment by Alex-302** [comment]
Please add screenshots to issues.
