### ISSUE TITLE
DrugVokrug Ads

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#9179]
### Steps to reproduce
Open the app
Enjoy the ads! They are located in the bottom area, near Android system key controls

### Expected behavior
No ads

### Actual behavior
Ads

### Screenshot:
![screenshot_2018-01-01-23-24-25-576_drug vokrug](https://user-images.githubusercontent.com/33634917/34470993-cf6a61f0-ef45-11e7-8c71-dcc4f8675268.png)

### Customer ID
1712624

### Your environment
 * Adguard version: 2.10.176
 * Adguard filtering mode: VPN
 * Device model: Xiaomi Redmi Pro
 * Operating system and version: Android 6.0
 * Rooted or not?: No
 * Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None detected
 * Filtering method: high-quality, HTTPS filtering enabled
 * Filters used: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "German filter", "French filter", "Japanese filter", "Dutch filter", "Spanish/Portuguese filter", "Turkish filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter", "ABPindo", "Bulgarian list", "EasyList China", "EasyList Czech and Slovak", "EasyList Hebrew", "EasyList Italy", "Latvian List", "Liste AR", "Liste FR", "ROList", "void.gr", "ABPVN List", "Adblock-Persian list", "Adblock & uBlock polish filter", "Adblock & uBlock polish cookies filter", "Adblock & uBlock polish filter - Adguard supplement", "Anti-Adblock Killer | Reek", "Estonian List", "Fanboy's Swedish", "hufilter", "Korean Adblock List", "List-KR", "Juvander's Adblock List for Finland", "Schacks Adblock Plus liste"
 * DNS: None

**Comment by akmAa** [comment]
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/1596374/debug.txt)

Debug logs, issue at 3:51

**Comment by Alex-302** [comment]
встроена в приложение
