### ISSUE TITLE
newegg.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#91803]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyance on the lower side of the webpage
URL with the issue: `https://www.newegg.com/`

**Comment by Alex-302** [comment]
May be useful.
