### ISSUE TITLE
microsoft.com

### ISSUE THREAD

**Issue by thinksheiscool** [AdguardTeam/AdguardFilters#91812]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyances
URL with the issue: `https://www.microsoft.com/en-us/store/b/pc`

**Comment by chirag127** [comment]
![image](https://user-images.githubusercontent.com/76880977/130290398-e5840e21-4ed1-4773-893c-912182ac8d6f.png)
