### ISSUE TITLE
Skipped ads in com.pss.line

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardFilters#9186]
***Description***:
* **Current behaviour**: Shows ads

<details><summary>Screenshot:</summary>

![screenshot_2017-12-30-00-41-26-262_com pss line](https://user-images.githubusercontent.com/33634917/34485365-d977b458-efd2-11e7-9709-60d0b74dd6c2.png)
![screenshot_2017-12-30-00-43-19-268_com pss line](https://user-images.githubusercontent.com/33634917/34485366-d9953eb0-efd2-11e7-86b0-65d7be28408e.png)

</details><br/>

* **Expected behaviour**: Shouldn't show ads

***Steps to reproduce the problem***:

Open the app

***System configuration***

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Experimental filter", "Simplified domain names filter", "Adblock-Persian list", "Adblock & uBlock polish filter", "Adblock & uBlock polish cookies filter", "Adblock & uBlock polish filter - Adguard supplement", "Anti-Adblock Killer | Reek", "List-KR", "Juvander's Adblock List for Finland", "Schacks Adblock Plus liste"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.1.2
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Experimental filter", "Simplified domain names filter", "Adblock-Persian list", "Adblock & uBlock polish filter", "Adblock & uBlock polish cookies filter", "Adblock & uBlock polish filter - Adguard supplement", "Anti-Adblock Killer | Reek", "List-KR", "Juvander's Adblock List for Finland", "Schacks Adblock Plus liste"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1623929

**Comment by Alex-302** [comment]
@akmAa please upload correct screenshot.

**Comment by akmAa** [comment]
@Alex-302 Uploaded, sorry for the confusion.
