### ISSUE TITLE
guitarnutrition.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91865]
**Issue URL (Annoyance)**: https://guitarnutrition.com/blog/how-to-learn-music-theory-10-times-faster

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130296827-6794dfeb-a367-4fed-8018-4582ab3f952c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors, please add to user rules:
`guitarnutrition.com###termly-code-snippet-support`
