### ISSUE TITLE
thepinkroute.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91861]
**Issue URL (Ads)** : http://thepinkroute.com/uncategorized/is-whitehat-jr-genuine-honest-and-detailed-whitehat-jr-review-for-teachers/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130296563-bae9b0db-c4a1-4df2-b33f-7998edac680c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
I don't see enough visitors for the website.

**Comment by chirag127** [comment]
@zloyden 

Okay tell me user filter . will `thepinkroute.com###text-23` create FP .

**Comment by zloyden** [comment]
```
thepinkroute.com#?##secondary > aside.widget:has(> h3 > span:contains(ads))
thepinkroute.com##.entry-content > p ~ div[class][style^="clear:both;float:left;"]
```
