### ISSUE TITLE
music-theory-for-musicians.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91868]
**Issue URL (Annoyance)**:
https://www.music-theory-for-musicians.com/music-theory-beginners.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130297037-51b75a28-b75f-4c11-b868-ccd88d423af7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
Fixed.
