### ISSUE TITLE
amazon music (ios)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#91891]
||advertising.a2z.com^

https://apps.apple.com/us/app/amazon-music-songs-podcasts/id510855668

**Comment by Alex-302** [comment]
Did you check when this domain is blocked?
Better provide full, with sub-domains. I want to add as `||data-onboarding.advertising.a2z.com^`

**Comment by Alex-302** [comment]
@jordanelliott23 *ping*

**Comment by jordanelliott23** [comment]
the domain that came up was prod.cm.publishers.advertising.a2z.com

**Comment by Alex-302** [comment]
Blocked.
