### ISSUE TITLE
zoneseries.stream

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardFilters#91892]
go to try play uqload or vudeo not work because embed html blocked by adguard french filter

https://wwv.zoneseries.stream/40026-serie-chicago-med-saison-2-episode-4.html

whitlist document not good because whitlist popup too 

actualy for work whitout popup , i disabled french adguard and work

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by Disqu3-mirOir-qt** [comment]
vf-film.org
vf-serie.org

vudeo / uqload embed blocked too

**Comment by AdamWr** [comment]
Okay, fixed.
Update should be available in 1-2 hours.
