### ISSUE TITLE
networksolutions.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#91991]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyance
URL with the issue: `https://www.networksolutions.com/`

**Comment by Alex-302** [comment]
Not third-part chat.
