### ISSUE TITLE
Alarm Clock Plus missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#920]
http://forum.adguard.com/showthread.php?7561-Android-Adguard-2-1-267-Not-blocking-any-ads-(galaxy-s6)&p=65606#post65606

https://play.google.com/store/apps/details?id=com.vp.alarmClockPlusDock&hl=en

**Comment by Alex-302** [comment]
Checked it on apkscan.nviso.be - all ads domains are in Mobile filter, so they should be blocked, but I don't see any network activity.

**Comment by ameshkov** [comment]
Have you tried installing it?

**Comment by Alex-302** [comment]
Yes.
