### ISSUE TITLE
gsmarena.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92043]
**Issue URL (Ads)** :https://www.gsmarena.com/newscomm-45700.php

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130330996-7e3bd256-ecb0-4b28-98b7-820d6ef93cdd.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not an ad.
