### ISSUE TITLE
techpp.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92040]
**Issue URL (Ads)** : https://techpp.com/2020/11/26/xiaomi-ads-opinion/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130330953-c445163a-ef99-41ca-a35e-4cb76f8e7d21.png)
![image](https://user-images.githubusercontent.com/76880977/130330954-da71fd6e-a02d-456a-a3d4-b88878af226c.png)

https://techpp.com/2020/11/26/xiaomi-ads-opinion/

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by gork7777** [comment]
Also there's share list
