### ISSUE TITLE
sanity.io

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#92049]
||api.rudderlabs.com^
||sanity-dataplane.rudderstack.com^

rudderlabs is analytics:
https://www.nuget.org/profiles/rudderlabs

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.sanity.io/)

**Comment by thinksheiscool** [comment]
@ryanbr @pgl

**Comment by adranger** [comment]
@jordanelliott23  the correct link syntax is `[https://www.sanity.io/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.sanity.io/)`. 

You have to paste the domain twice at the beginning between brackets and at the ending to make it appear like this: [https://www.sanity.io/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.sanity.io/)

**Comment by krystian3w** [comment]
Need pruge list ("Filter" in AG syntax) in addons.
