### ISSUE TITLE
cplusplus.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#92064]
AdGuard product: AdGuard Browser Extension
Browser: Brave
Filters: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter
Issue: Annoyance
URL with the issue: `https://www.cplusplus.com/doc/tutorial/`

**Comment by Alex-302** [comment]
It automatically removed, immediately.
