### ISSUE TITLE
polymersearch.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92093]
**Issue URL (Annoyance)**: https://app.polymersearch.com/discover/github-awesome

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130344665-6b68122e-ce02-4c05-a937-adb64010a7a1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.

**Comment by chirag127** [comment]
@zloyden 

Okay please tell me user filter .

**Comment by zloyden** [comment]
`app.polymersearch.com##div[id*="modal_outer"]`
