### ISSUE TITLE
hamariweb.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92097]
**Issue URL (Ads)** :https://hamariweb.com/names/christian/english/boy/fulk-meaning_47914

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130346366-dd7400be-b30f-43f5-9092-b152f46b330f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
I don't see any ads inside this element.
