### ISSUE TITLE
about having issue in ad blocking 

### ISSUE THREAD

**Issue by jaypathak9460** [AdguardTeam/AdguardFilters#92143]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
I am using AdGuardHome on raspberry pi model 3 b+.
I had installed this  using the below command 
"curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v"
then I configured it  as step by step 
and I have enabled these links for blocking ads 
[
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://adaway.org/hosts.txt
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
https://someonewhocares.org/hosts/zero/hosts
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt
]
in the above list,
I have set up my router's DNS  to my raspberry pi which I have done statically to 192.168.0.110  using the router's DHCP configuration to fix mac on the above IP address,
I also used a Youtube blocking list from **GoodbyeAds** which remove a lot of advertisements from web UI, but not from the  youtube application, I still got annoying **banner ads** and **Products recommendation** list on youtube

* **Current behavior**: 
this software removes a lot of ads but not as I wanted 
I got ads in Hotstar also on youtube in the videoes, also not forgetting about banners 
if I block any other site req from youtube my youtube app stops loading videos or not having thumbnails on each video which gives an unpleasant experience 
in my house, everyone using android  and myself, also have a fire tv stick  which I occasionally used to watch youtube videos and movies

[//]: # (Substitute this line with a description of the problem)

* **Expected behavior**: 

I want to remove ads from youtube completely  not even banner and Product recommendation 
also want to remove ads from a website that I use frequently like animejp.net  gogo anime and so on
also want to remove ads from Hotstar in the app also from its website .

***Steps to reproduce the problem***:

if anyone  follows the above description they can recreate the situation also I live in India

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
These are the  filters i have used

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://adaway.org/hosts.txt
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
https://someonewhocares.org/hosts/zero/hosts
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt
[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Raspberry pi os
Operating system version (Android/iOS) | [10]
Browser:                               | chrome /edge/firfox anyone i want latest versions
AdGuard version:                       | latest Version: v0.106.3
Filters enabled:                       | yes
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default  - don't know about DNS
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | don't have any I use my raspberry pi using VNC 

i anyone have a suggestion kindly let me know also please help me 

thanks in advance

**Comment by krystian3w** [comment]
India banned on DNS level domain/subdomain:

`raw.githubusercontent.com`



---

YouTube ads the best block by `json-prune` not by network simple rules:

https://github.com/AdguardTeam/AdguardFilters/blob/c7379a17db870cd93be07ed5ddbbea42cc435c50/EnglishFilter/sections/specific.txt#L208-L210

https://github.com/AdguardTeam/AdguardFilters/blob/c7379a17db870cd93be07ed5ddbbea42cc435c50/EnglishFilter/sections/specific.txt#L196-L198

Also banner better block by cosmetic rules + ExtendedCSS:

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#cosmetic-rules
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-selectors

And on Android use Vanced YouTube if you not have oldie/weak phones:

https://vancedapp.com/

or enforce load `m.youtube.com` / `www.youtube.com` in Browsers like Chrome 92+ with installed: https://adguard.com/adguard-android/overview.html

**Comment by krystian3w** [comment]
> also want to remove ads from a website that I use frequently like animejp.net gogo anime and so on

> also want to remove ads from Hotstar in the app also from its website .

I suppose better create new issues instead join this into youtube ads. Maybe `animejp.net` not hidden ads as first-party file (so can by blocked by newtwork rule or DNS service) and similar in app "Hotstar".

**Comment by Alex-302** [comment]
@jaypathak9460 Hi. Some ads cannot be blocked on DNS level(for example, youtube or many video sites with VAST ad system), and adblocker app or extension still required.
