### ISSUE TITLE
g.live.com and g.msn.com

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardFilters#92272]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Windows 10 breaks functionality with OneDrive and Microsoft account services when `g.live.com` (also shown as `g.msn.com`) is blacklisted on the AdGuard DNS Filter. This is extremely problematic as it also prevents the device from uploading the BitLocker recovery key and other important services.

* **Current behaviour**: Device encryption fails with not being able to upload the recovery key, OneDrive cannot update or provide Important PC Folder backups, Windows 10 halts any updates not related to Windows Update. Windows Spotlight fails to update. Upgrades to major builds of Windows are not offered unless manually installed. Seems to be all cloud related services.

* **Expected behaviour**: Windows 10 can correctly function with OneDrive and Microsoft Account services immediately once unblocked.

***Steps to reproduce the problem***:
Set up a new Windows 10 installation with the AdGuard DNS Filter enabled in AdGuard Home and sign in with a Microsoft Account immediately on the out of box experience.

**Comment by Alex-302** [comment]
Ok, removed. Googled few similar issues .
