### ISSUE TITLE
systoolsgroup.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92348]
**Issue URL (Annoyance+ ads)**: https://www.systoolsgroup.com/updates/export-contacts-from-excel-to-whatsapp/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130651032-96500c54-2e04-4096-a75d-e9ea3979273d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Apious** [comment]
blocked
www.systoolsgroup.com##.col-md-4
