### ISSUE TITLE
techulator.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92350]
**Issue URL (Ads)** : https://www.techulator.com/resources/17726-how-to-save-bulk-contacts-whatsapp-phone.aspx

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130650900-852e0c04-54c4-414f-9e54-a72842581213.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Apious** [comment]
blocked as do
www.techulator.com##div.nopadding.row:nth-of-type(1)
