### ISSUE TITLE
advocatekhoj.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92361]
**Issue URL (Ads)** :
 https://www.advocatekhoj.com/library/bareacts/mentalhealthcare/46.php?Title=Mental%20Healthcare%20Act,%202017&STitle=Composition%20of%20State%20Authority

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130668273-a1948ea9-dfb4-451f-ab33-1428e8f176da.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Apious** [comment]
blocked as do
||www.advocatekhoj.com/images/ads/*
www.advocatekhoj.com##tr:nth-of-type(6)
