### ISSUE TITLE
dns过滤器导致中国联通app我的钱包无法显示

### ISSUE THREAD

**Issue by DongfeiSay** [AdguardTeam/AdguardFilters#92384]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
我在公网上使用ADG搭建dns供自己使用，过滤器启用默认的AdGuard DNS filter，AdGuard 防跟踪保护过滤器，在我打开联通app后，通过日志发现主要是被拦截了图上的5个域名(9:34:23~9:34:45)，AdGuard DNS filter也包含了这几个规则，将它们关闭后等待ttl结束重新打开我的钱包可以正常显示出来数据
* **Current behaviour**: 
![photo_2021-08-25_10-41-34](https://user-images.githubusercontent.com/49421020/130718957-32469954-2d4d-496c-8675-2f7181fc55a4.jpg)
![跟踪](https://user-images.githubusercontent.com/49421020/130718941-51a55320-9a4f-47f5-a89f-3032c85ede0a.JPG)

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)
![photo_2021-08-25_11-09-20](https://user-images.githubusercontent.com/49421020/130720015-484936dc-f45e-4b95-8b82-73ae6276ed2d.jpg)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

***System configuration***

**Filters:**

AdGuard DNS filter
AdGuard 防跟踪保护过滤器

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:          
             | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ok. Thanks. Please leave this exclusion in your list. 
If we receive more complaints, we will make changes in the DNS filter(because this is popular service, we cannot just add exclusion).
