### ISSUE TITLE
ecosia.org - Anti Adblock

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#9239]
При поиске в ecosia.org , вначале страницы появляется Anti Adblock сообщение: https://www.ecosia.org/search?q=дикие+и+домашние+-+совы

<details><summary>Screenshot:</summary>

![ecosia org](https://user-images.githubusercontent.com/17948007/34505263-4178361a-f035-11e7-9a26-64714bd86b57.png)
</details><br/>

 Пояснение: За показ сообщения 1 отвечает скрипт `https://cdn.ecosia.org/assets/scripts/bundles/main-784bee86e8.js` , но, при его блокировке, перестают работать кнопки 2. Поэтому нужно скрывать: `ecosia.org##.js-funnel-whitelistbox`

 Ещё можно заблокировать скрипт аналитики: `||analytics.ecosia.org/analytics.js` . ВРОДЕ это не даёт негативных последствий.
___________________________________________________
Pale Moon v26.5 (Win7) - Adguard v2.8.1 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Поправил.
