### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92419]
**Issue URL (Annoyance)**: https://www.newyorker.com/magazine/2021/05/10/how-the-pentagon-started-taking-ufos-seriously

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130782472-384e97cd-6f38-430b-888d-9126ce5967b4.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by DandelionSprout** [comment]
Such content cookie declarations are sadly not a good idea to block in mainstream annoyances lists; since it makes it impossible to watch embedded videos on such sites.

**Comment by chirag127** [comment]
What do you mean by "such"? 

> Such content cookie declarations are sadly not a good idea to block in mainstream annoyances lists; since it makes it impossible to watch embedded videos on such sites.

@DandelionSprout how  it makes it impossible to watch embedded videos?

**Comment by DandelionSprout** [comment]
From my experiences with Danish newspaper sites, "Accept cookies to see this content" messages are hiding video and Twitter embeds under them. If the messages themselves were blocked, end-users would be unaware of why articles don't have any videos or tweets in them.

**Comment by chirag127** [comment]
> From my experiences with Danish newspaper sites, "Accept cookies to see this content" messages are hiding video and Twitter embeds under them. If the messages themselves were blocked, end-users would be unaware of why articles don't have any videos or tweets in them.

But how will the site know if the message is blocked? There is no button to accept the cookies  it's just a notice.

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours. You have to clear your browser data (cookies / cache) after getting a fix to see this.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/131992240-d386e626-a5cb-4b35-b8df-b64d5a80e422.png)

</details><br/>
