### ISSUE TITLE
fourminutebooks.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92443]
**Issue URL (Annoyance)**: https://fourminutebooks.com/book-summaries/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130819574-12f8d788-42b2-4ed7-8ad7-4eda53672cb0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can't reproduce this newsletter element, fixed popup.
