### ISSUE TITLE
brainbook.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92447]
**Issue URL (Annoyance+Ads)**:https://brainbook.in/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130820780-a8a95276-b47b-46d7-a0f5-ebca1609640f.png)
![image](https://user-images.githubusercontent.com/76880977/130820784-1846e50b-b3f7-42ae-9eca-5fb1a074c4f9.png)
![image](https://user-images.githubusercontent.com/76880977/130820782-d26210ae-32c5-45ed-802b-118624411a59.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
5110 visitors/month
