### ISSUE TITLE
tckpublishing.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92451]
**Issue URL (Annoyance)**: https://www.tckpublishing.com/best-book-summary-sites/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130820614-72d5ee06-4fb1-4e37-8045-b77cd2a43447.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
This element doesn't annoy.
