### ISSUE TITLE
conspiracytheories.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92476]
**Issue URL (Social Widget)** : https://conspiracytheories.in/are-astra-mahabharata-todays-nuclear-weapons/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130833928-02b3bfe4-8ede-4f3f-8df5-fabcaae823d5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
8670 visitors/month
