### ISSUE TITLE
bhagavanbhakthi.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92471]
**Issue URL (Social Widget)** : https://bhagavanbhakthi.com/2020/11/weapons-used-in-mahabharata-ramayana/

<details><summary>Screenshots:</summary>

https://bhagavanbhakthi.com/2020/11/weapons-used-in-mahabharata-ramayana/
![image](https://user-images.githubusercontent.com/76880977/130833183-41fb9638-c0cd-49fc-8dba-64f6d3efb16a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
