### ISSUE TITLE
learning.ly

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92530]
**Issue URL (Annoyance)**:https://learning.ly/products/become-a-speeddemon-productivity-tricks-to-have-more-time

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130935690-79553a19-5333-4c1a-ab87-56aea417ab4b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
7620 visitors/month
