### ISSUE TITLE
rozblog.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92544]
**Issue URL (Ads)** :http://nulldownload.rozblog.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130938117-1403e66a-9d28-44e2-b3bb-2d7e99b7076b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
