### ISSUE TITLE
blogfa.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92547]
**Issue URL (Annoyance)**:http://versatile4u.blogfa.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130938517-189ee69d-9233-405d-9481-d798aee1bc22.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
I don't see this with `Adblock-Iran` enabled.
