### ISSUE TITLE
coursesforfree.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92549]
**Issue URL (Social Widget)** :

https://www.coursesforfree.net/business/download-linkedin-b2b-lead-generation-for-agencies-and-consultants-for-free/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130938682-f737cb15-f3a7-439e-ae70-048c0c89c9b5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
