### ISSUE TITLE
shoukhintech.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92557]
**Issue URL (Ads)** :https://shoukhintech.com/chrome-always-on-top/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130942393-341f8e46-02be-428f-a70a-23b0414d9926.png)
</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
6 510 visitors/month
