### ISSUE TITLE
aktubaba.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92552]
**Issue URL (Ads)** :https://aktubaba.com/aktu-passing-marks-html/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130940293-3f48eca5-7073-418f-9182-d9243118fe5a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2320 visitors/month
