### ISSUE TITLE
howtofree.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92550]
**Issue URL (Ads)** :https://www.howtofree.org/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130938765-a1f1b0ce-560e-4704-a6dd-85bc862e0387.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
20 600 visitors/month
