### ISSUE TITLE
newbollywoodhindisongs.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92566]
**Issue URL (Annoyance)**:https://www.newbollywoodhindisongs.in/new-english-international-hit-songs-2021/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130954207-e4ef1b42-71b3-423a-808c-d0e27c78fece.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
