### ISSUE TITLE
jiosaavn.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92563]
**Issue URL (Annoyance)**:
https://www.jiosaavn.com/s/playlist/phulki_user/Weekly_Top_Songs/LdbVc1Z5i9E_

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130953608-c3d07741-e2ea-4357-9211-d748f27073c6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not reproduced on my end. Can you show this element with opened devtools?

**Comment by chirag127** [comment]
@zloyden 
![image](https://user-images.githubusercontent.com/76880977/132509663-2a4bd65c-c9da-47cc-a5c4-d9aa1f413c7b.png)

**Comment by zloyden** [comment]
Please try one of these rules.
`jiosaavn.com#?#.c-modal:has(> div.c-modal__content em:contains(Listen to the top songs))`
`jiosaavn.com##.c-modal`.
