### ISSUE TITLE
babychakra.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92565]
**Issue URL (Annoyance)**:https://www.babychakra.com/learn/954-7-most-popular-english-songs-for-children

<details><summary>Screenshots:</summary>

https://www.babychakra.com/learn/954-7-most-popular-english-songs-for-children
![image](https://user-images.githubusercontent.com/76880977/130953935-65c84146-5e36-4a9e-a1dd-7cb8910fdd39.png)
![image](https://user-images.githubusercontent.com/76880977/130953939-b81928e1-feab-4b9e-82cc-47387e7b2522.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Removed subscription, but the popup is not reproduced on my end.
