### ISSUE TITLE
hindinut.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92575]
**Issue URL (Ads)** : https://hindinut.com/bhuj-full-movie-download-720p/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130958679-67a3ec42-bb27-4c80-a5aa-778d3233bf3f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>https://hindinut.com/bhuj-full-movie-download-720p/

**Comment by Sergey-Lyapin** [comment]
11 700 visitors/month
