### ISSUE TITLE
Tracking domain 

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#92577]
to track clicks

```
||clicks.h.hepsiburada.com/
||eu.spgo.io/

```
This is an email saying that the order has been shipped. If you want to check, I can send you the password of the mail.

<details><summary>Image</summary>

 
![clk](https://user-images.githubusercontent.com/74098460/130960672-d62dfb4a-7c7b-4dfa-b5b6-e0a28a4298b1.png)

</details>

**Comment by Alex-302** [comment]
@RadicalNoise Hi. Nothing:(

**Comment by RadicalNoise** [comment]
@Alex-302 I sent it again. To reproduce this, you need to log into the ProtonMail account in the e-mail I sent. You can find ProtonMail account information and reproduction steps inside the mail.

**Comment by Alex-302** [comment]
Damn. Still not received:( Please try to send to tmail00@yandex.ru

**Comment by RadicalNoise** [comment]
@Alex-302 Done.

**Comment by Alex-302** [comment]
@RadicalNoise Thanks, checked and blocked.
