### ISSUE TITLE
viralviralvideos.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92580]
**Issue URL (Annoyance)**:https://viralviralvideos.com/tag/cheating/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130961904-699b6774-9edb-4f37-8bad-f78919d7188c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
