### ISSUE TITLE
economist.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92597]
**Issue URL (Ads)** :https://safecities.economist.com/

<details><summary>Screenshots:</summary>

https://safecities.economist.com/
![image](https://user-images.githubusercontent.com/76880977/130986906-b1dfd163-fb86-44b8-8cf5-5ca10b7d45d8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not an ad / annoyance, I have this popup, if I click on this.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/132491983-b3ae4267-90b8-428f-9c77-c230763eaf29.png)
</details><br/>

**Comment by chirag127** [comment]
@zloyden the shown area is ad / annoyance
![image](https://user-images.githubusercontent.com/76880977/132509443-0ffb5f85-d99a-4b70-8fbb-6a7bdf3037e9.png)

**Comment by zloyden** [comment]
I can see that they duplicate this information, added to the AdGuard Annoyances.
