### ISSUE TITLE
minidl.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92590]
**Issue URL (Ads)** :http://minidl.org/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130972746-960963f1-f407-45e7-a3e9-4874a938eb8c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4 290 visitors/month
