### ISSUE TITLE
gatesnotes.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92659]
**Issue URL (Social Widget)** :https://www.gatesnotes.com/Books/Numbers-Dont-Lie

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131117855-6fdbef5c-9742-4578-ae97-096355414515.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
already fixed https://github.com/AdguardTeam/AdguardFilters/commit/32ee1e4d2e12b79c2f732a6fa50f98a1db78e49c
