### ISSUE TITLE
jumpstartyourdreamlife.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92667]
**Issue URL (Annoyance)**:
https://www.jumpstartyourdreamlife.com/how-to-read/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131122112-e9ac9d7f-9a56-4d95-9b88-fc443a829d4e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>https://www.jumpstartyourdreamlife.com/how-to-read/

**Comment by Sergey-Lyapin** [comment]
2420 visitors/month
