### ISSUE TITLE
bookboon.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92706]
**Issue URL (Annoyance)**:https://bookboon.com/blog/2019/07/motivation-skills-for-managers-6-steps-to-improve-employees-motivation/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131165016-d958a352-c51c-4879-8eea-7189f0b874cd.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website doesn't work on my end.
