### ISSUE TITLE
foumovies.se

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92715]
**Issue URL (Annoyance)**:https://www.foumovies.se/downloading/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131169754-bf76d75d-e188-4e32-b556-0264bbcf21b7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
It seems they have a server check.
