### ISSUE TITLE
notebookcheck.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92714]
**Issue URL (Anti Adblock Script):**
https://www.notebookcheck.net/Redmi-Note-10-gets-a-second-price-hike-in-less-than-a-month-in-India.557041.0.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131169019-7dd0baa0-cccb-4441-ad1b-3cf7c30e7dd3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
duplicate
