### ISSUE TITLE
thelaundress.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92731]
**Issue URL (Annoyance)**:https://www.thelaundress.com/how-to/360-wash/washing/hand-washing.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131184100-4d4f8e10-e666-4d76-b2c0-f653f59bece7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
This is part of the site's functionality.
