### ISSUE TITLE
travelchinacheaper.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92736]
**Issue URL (Ads)** :https://www.travelchinacheaper.com/is-it-legal-to-use-a-vpn-in-china

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131186542-121c4691-db47-4236-a9c4-1e333b6bd131.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not an ad, it's part of the article.
