### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#92779]
Возможно ли что-то сделать с попапом на vk на 2.12.250 под ведром, который вымогает авторизацию ?
![2021 08 28_20 02 54~01](https://user-images.githubusercontent.com/12525093/131214404-7f03e100-d189-478f-a2ca-e209ce464ac7.jpg)
Думал взять правило с 3.6.2 на более новом устройстве, но там в логах ничего по этому поводу не было даже близко. Немного поковырявшись на десктопе, получилось следующее :

>vk.com##div[class="popup_box_container UnauthActionBoxContainer UnauthActionBoxContainer--form"]
>vk.com##div[id="box_layer_bg"]
>vk.com##div[id="box_layer_wrap"]

но заставить работать скролл при этом не удалось. Линк для примера https://vk.com/mindmanga достаточно немного поскроллить и лезет эта пакость.

**Comment by Alex-302** [comment]
@Baltazar500 Фильтр раздражителей включен?

**Comment by Baltazar500** [comment]
@Alex-302, да.

![2021 08 30_20 54 30~01](https://user-images.githubusercontent.com/12525093/131329155-8226c8ec-dd8b-467e-ad65-053f8e7dfe85.jpg)

**Comment by Alex-302** [comment]
@Baltazar500 У меня блокируется фильтром раздражителей и программой и браузерным расширением.
Откройте журнал фильтрации, обновите вкладку и сделайте скриншот.

**Comment by Baltazar500** [comment]
>Откройте журнал фильтрации, обновите вкладку и сделайте скриншот.

Это всё, что есть в логе "негативного" при открытии странички vk

![2021 09 01_00 28 52~01](https://user-images.githubusercontent.com/12525093/131521783-6b2d9d2e-ae03-4d3c-861f-58500b3c750c.jpg)

Напоминаю, в данном случае проблема на 2.12.250

**Comment by Alex-302** [comment]
Слишком старая версия, не поддерживает используемый в этом случае синтаксис.

**Comment by Alex-302** [comment]
Можно попробовать так:
`vk.com#%#Object.defineProperty(window, 'Unauthorized', { get: function() { return undefined; } });`
`vk.com#%#Object.defineProperty(window, 'PageBottomBanners.initUnauthBanner', { get: function() { return undefined; } });`
