### ISSUE TITLE
breadnbeyond.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92776]
**Issue URL (Ads)** :https://breadnbeyond.com/youtube-marketing/youtube-thumbnail-tips/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131214211-ed2e2e8c-20dd-45ff-bd8a-c02cbe4e58ba.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors
