### ISSUE TITLE
crackmycbse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92819]
**Issue URL (Ads)** :
https://www.crackmycbse.com/2020/06/Communication%20Skills%20Class%2010%20Notes%20PDF.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131225886-8cbffb1f-c91d-4637-b0c8-e54a428ba0f4.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
