### ISSUE TITLE
indiabusinessjournal.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92825]
**Issue URL (Annoyance)**:https://www.indiabusinessjournal.com/full-story/262/rbi-extends-deadline-for-autorenewal-of-payments-by-six-months-to-september-30

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131226914-948ab3f2-e646-4b6a-93dd-5ae2647c4d3a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
