### ISSUE TITLE
tayarijeetki.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92820]
**Issue URL (Annoyance)**:https://www.tayarijeetki.com/communication-skills-2-pdf-notes/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131225864-a7b8c2e6-fb43-424e-8d64-301d73a1267e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
