### ISSUE TITLE
aminotes.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92821]
**Issue URL (Ads)** :https://www.aminotes.com/2018/04/introduction-to-communication-skills.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131225857-baddf59f-dce2-4dfd-a45c-d0366d2122fb.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
