### ISSUE TITLE
millionacres.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92830]
**Issue URL (Annoyance)**:https://www.millionacres.com/real-estate-basics/investing-basics/how-to-become-a-billionaire-in-real-estate/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131227134-e34f1d6b-6d30-49a9-b08f-f15cc0c1ba52.png)
![image](https://user-images.githubusercontent.com/76880977/131227135-60d5a08a-933f-45e7-abb0-1579e73348e8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by GoshaLand** [comment]
Hi! You can try to solve this problem with [a cosmetic rule.](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#example-cosmetic-rule-1)
My rules are below:
```
www.millionacres.com###milli_mid_article_pitch
www.millionacres.com##.bg--blue.trans.w-100.d-block.banner-wrap
```
[My link](https://github.com/GoshaLand/Jordonus/blob/main/Jord.txt) to the performance test filter.

1. [Screenshot...](https://user-images.githubusercontent.com/85258199/131229555-40367b02-123e-40f7-aabf-8bd87189f8a3.PNG)
2. [Screenshot...](https://user-images.githubusercontent.com/85258199/131229530-41fb883a-4f1a-44d8-9caa-da5092061395.PNG)
