### ISSUE TITLE
profitableventure.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92832]
**Issue URL (Ads)** :https://www.profitableventure.com/become-self-made-billionaire/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131227115-c601a959-adff-40d4-97dc-c3094a95547f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by GoshaLand** [comment]
Hi! You can try to solve this problem with [a cosmetic rule.](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#example-cosmetic-rule-1)
My rules are below:
`www.profitableventure.com##.code-block-1.code-block`

[My link](https://github.com/GoshaLand/Jordonus/blob/main/Jord.txt) to the performance test filter.

[Screenshot...](https://user-images.githubusercontent.com/85258199/131228069-c5acced5-3efa-4a86-a800-57ccd192a255.PNG)

**Comment by krystian3w** [comment]
But he prefere fix it for all people by commit into AdGuard filters.
