### ISSUE TITLE
gfxtra.uproxy.to

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92878]
**Issue URL (Ads)** :
http://gfxtra.uproxy.to/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131235911-09a7571d-48ab-4a40-b33b-65ca82664a55.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
I don't see ads on my end.
