### ISSUE TITLE
downloadlyir.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92876]
**Issue URL (Ads)** :
https://downloadlyir.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131235818-c8b92ffe-e50b-4f72-ade6-c228a492f786.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
This element looks the same without AdGuard.

**Comment by chirag127** [comment]
> This element looks the same without AdGuard.

but by the content of the element it seems to be a ad
![image](https://user-images.githubusercontent.com/76880977/132779456-579065e6-7d47-4db9-a8b8-fce1b45155fb.png)
