### ISSUE TITLE
softgozar.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92877]
**Issue URL (Ads)** :
https://www.softgozar.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131235907-1cf1aa2d-9862-4de6-a90b-cfb67be20947.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Please also enable `Adblock-Persian list`.
