### ISSUE TITLE
redox.com.ua

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92879]
**Issue URL (Ads)** :redox.com.ua

<details><summary>Screenshots:</summary>

aTEST
![image](https://user-images.githubusercontent.com/76880977/131235927-0450d46b-3410-4e19-8a88-35dca8b4b8e1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
