### ISSUE TITLE
Add hwcdn.net to exclusion in regex lockdown filter, or exclude uBO from the filter

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#92927]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Blocking `hwcdn.net`, currently not excluded in `/^(?!.*(bootstrapcdn.com` lockdown filter, breaks various videos with uBO running on Firefox for CNAME. An example is `https://www.homemoviestube.com/videos/551975/she-likes-it.html` (NSFW).

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![cname](https://user-images.githubusercontent.com/58900598/131257453-b1fc6bcb-2e0f-4f45-8bc5-1c6f1d09f5ef.png)

</details><br/>

* **Expected behaviour**: 

Base filter shouldn't block `hwcdn.net` in uBO on Firefox.

***Steps to reproduce the problem***:

Add Base filter to uBO on Firefox and visit the URL.

***System configuration***

**Filters:**

uBO default + Base

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 91.0.2
AdGuard version:                       | NA
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | NA
Helpdesk ID (if exists):               | ?

***Notes:

There are two possible solution as wrote in the title. I, as an user, prefer adding `hwcdn.net` to exclusion i.e.
`/^(?!.*(bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|googletagmanager.com|gstatic.com|hwcdn.net|jquery.com|jsdelivr.net|jwpcdn.com|jwplatform.com|polyfill.io|recaptcha.net|shrink.pe|twitter.com|ulogin.ru|unpkg.com|userapi.com|vidazoo.com|vk.com|yandex.|yastatic.net|ytimg.com|zencdn.net|player|youtube.com|cackle.me|googleoptimize.com|vuukle.com|chatango.com|twimg.com|google-analytics.com|hcaptcha.com|raincaptcha.com|media-imdb.com|blogger.com)).*$/`
but since this is uBO specific issue, if you don't like the above an alternative solution is `!+ NOT_PLATFORM(ext_ublock)`.

**Comment by Alex-302** [comment]
I don't see hwcdn.net in ubo's log. How to enable CNAME blocking?

**Comment by Yuki2718** [comment]
@Alex-302 On Firefox it's enabled by default, not available on Chromium. It can also be affected by DNS cache server you use.

**Comment by Alex-302** [comment]
@Yuki2718 Ok. I see it now. But I am not sure if it is correct to block by CNAME when applied the non-hostname domain specific rule.

**Comment by Yuki2718** [comment]
In this example `/^(?!.*(bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|googletagmanager.com|gstatic.com|hwcdn.net|jquery.com|jsdelivr.net|jwpcdn.com|jwplatform.com|polyfill.io|recaptcha.net|shrink.pe|twitter.com|ulogin.ru|unpkg.com|userapi.com|vidazoo.com|vk.com|yandex.|yastatic.net|ytimg.com|zencdn.net|player|youtube.com|cackle.me|googleoptimize.com|vuukle.com|chatango.com|twimg.com|google-analytics.com|hcaptcha.com|raincaptcha.com|media-imdb.com|blogger.com)).*$/` I just omitted `domain=` for simplicity, my point is to add `hwcdn.net` into excluded domain list in the regex.

**Comment by Alex-302** [comment]
Ok. Done.
