### ISSUE TITLE
yggtorrent.nz

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93016]
**Issue URL (Annoyance)**:https://www3.yggtorrent.nz/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131329492-4e4957a1-1ade-4238-a7fe-e2f9cca3aabe.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
This website doesn't work on my end.

**Comment by chirag127** [comment]
> This website doesn't work on my end.

Well @zloyden  it works fine on this side. Most probably your isp blocking the site.

**Comment by zloyden** [comment]
I checked this with VPN and had the same, but now the site opens. Fixed.
