### ISSUE TITLE
facttests.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93041]
**Issue URL (Annoyance)**:https://courses.facttests.com/p/download-page_54.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131353657-d64fd240-8250-4eb5-9b2c-81b1fb7ec352.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4960 visitors/month

**Comment by chirag127** [comment]
@Sergey-Lyapin tell me user filter as I didn't found any guide on fixing the timers.

**Comment by Sergey-Lyapin** [comment]
@chirag127
It seems this site is broken at all, timer and download don't work. (also without AG)
