### ISSUE TITLE
chip.de

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93053]
**Issue URL (Ads)** :
https://www.chip.de/

<details><summary>Screenshots:</summary>

2
</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by BlazDT** [comment]
Screenshot broken.
