### ISSUE TITLE
webogram.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93059]
**Issue URL (Annoyance)**:https://webogram.in/the-web-developer-bootcamp-2021-udemy-download-free/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131367965-ae96ff6d-e2d4-4416-9ebc-f2f98ca52955.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
1640 visitors/month
