### ISSUE TITLE
asianetnews.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93065]
**Issue URL (Ads)** :https://newsable.asianetnews.com/weird-news/traffic-halts-as-giant-anaconda-cross-the-road-watch-viral-video-gps-qydq47

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131380790-6458f1f7-2227-4ee1-8c19-902b7ec5ac2c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I don't see this leftover
