### ISSUE TITLE
QAStack.fr cookie banner

### ISSUE THREAD

**Issue by moviuro** [AdguardTeam/AdguardFilters#93069]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://qastack.fr/server/435779/for-l2arc-and-zil-is-it-better-to-have-one-large-ssd-for-both-or-two-smaller-s
* **Current behaviour**: has a cookie banner

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![sssusi](https://user-images.githubusercontent.com/6882978/131385935-5b984da3-95eb-4448-827e-b6ef96421d1d.png)
</details><br/>

* **Expected behaviour**: no cookie popup.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![sssusi](https://user-images.githubusercontent.com/6882978/131386020-9766ccc5-c1cd-4958-9922-aa315c0e286c.png)
</details><br/>

***Steps to reproduce the problem***: https://qastack.fr/server/435779/for-l2arc-and-zil-is-it-better-to-have-one-large-ssd-for-both-or-two-smaller-s

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

![sssusi](https://user-images.githubusercontent.com/6882978/131386122-8aeda5e6-bb05-4951-a8d2-35d9413d2ba5.png)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Archlinux
Operating system version (Android/iOS) | latest
Browser:                               | Firefox
AdGuard version:                       | N/A
Filters enabled:                       | AdGuard Base, Easylist, AdGuard annoyances
AdGuard mode (Android only):           | NA
Filtering quality (Android only):      | NA
HTTPS filtering (Android only):        | NA
Simplified filters (iOS only)          | NA
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | NA
Helpdesk ID (if exists):               | NA

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@moviuro Hi. Please hide big images under
```
<details><summary>Screenshot:</summary>


</details>
```
It seems you are using saved own template.
