### ISSUE TITLE
www.e1.ru ngs.ru www.nn.ru

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#93112]
Региональные сайты единой медиагруппы с идентичными проблемами: баннер возле лого + подписка + поделиться.
https://www.e1.ru/text/incidents/2021/08/31/70109228/
https://www.nn.ru/text/incidents/2021/08/30/70107602/
https://ngs.ru/text/entertainment/2021/08/29/70104479/

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/131489025-714e6d81-e1ab-494c-a48f-0566f01a478b.png)
</details><br/

**Comment by zubrRB** [comment]
По первой и третьей ссылке не заблокировал кликабельные баннеры правее от лого сайтов.

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/131674259-4b3893de-bfae-48a6-8b16-e1d485054e43.png)
</details><br/>

**Comment by zubrRB** [comment]
И добавь ко всем правилам дополнительные региональные домены  (с "поделиться" под каждой фотографией)":

https://74.ru/text/sport/2021/08/30/70099691/
https://76.ru/text/entertainment/2021/08/26/70100921/
https://161.ru/text/transport/2021/08/25/70096667/
https://ngs24.ru/text/food/2021/08/28/70102646/

**Comment by Alex-302** [comment]
Добавил доменов.

**Comment by zubrRB** [comment]
А старые (в заглавном комментарии которые) зачем удалил?! 
Надо было к ним добавлять, а не убавлять. Опять на них появились баннеры + подписка + поделиться.

**Comment by Alex-302** [comment]
Думал в большой список попали. Вернул.

**Comment by zubrRB** [comment]
И для этого большого списка надо ещё задать правило блокировки рекламного баннера возле логотипа.

![-](https://user-images.githubusercontent.com/50718960/131674259-4b3893de-bfae-48a6-8b16-e1d485054e43.png)

**Comment by Alex-302** [comment]
У меня он скрыт.

**Comment by zubrRB** [comment]
Сайт тяжёлый, баннер подгружается чуть позже. Вот сохранённая страница:  [e1.ru - новости Екатеринбурга.zip](https://github.com/AdguardTeam/AdguardFilters/files/7122872/e1.ru.-.zip)
Ссылка баннера: https://prinzip.su/its_prinzip/?utm_source=e1&utm_medium=logo&utm_campaign=mar2021&from=menu

**Comment by Alex-302** [comment]
Переделал, должно помочь если используется прога.
Лучше отправляй полноценные репорты, а то непонятно какой Адгард. Это имеет значение.

**Comment by zubrRB** [comment]
Сам сначала сказал отправлять мне простые... У меня ведь всегда прога с постоянным набором фильтров и скриптов.
Здесь к тому же целая куча родственных сайтов с идентичными проблемами, так что легче было их одним списком дать.

Заблокирую ещё повторно подписку под статьями на всех и "поделиться" под каждым фото как здесь https://github.com/AdguardTeam/AdguardFilters/issues/93112#issuecomment-910270310.

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/132687577-9238f5ac-7f35-4148-b0d7-c1ec527ba43c.png)

![2](https://user-images.githubusercontent.com/50718960/132687580-321f0034-1c9c-473f-b0b9-0ccc9d9614e3.png)
</details><br/>

**Comment by Alex-302** [comment]
Ну скопируй код готового репорта и меняй соотв. образом. Я же не помню у кого какие настройки.

**Comment by Alex-302** [comment]
поправил

**Comment by zubrRB** [comment]
Спасибо! А как целиком скопировать готовый репорт? Шаблон "New issue" и отправляемого через программу отличаются.
А при копировании через цитирование опубликованного issue теряется табличный вид отображения настроек системы.

**Comment by zubrRB** [comment]
Старое правило из фильтра раздражителей удалилось, а новое почему-то до сих пор не добавилось... Слишком длинное?

**Comment by Alex-302** [comment]
Ошибка в правиле. Поправил.

**Comment by zubrRB** [comment]
Хочешь верь, хочешь не верь, а подписка эта под статьями не пропала даже с обновлённым правилом.)

**Comment by Alex-302** [comment]
Уже должно быть чисто.

**Comment by zubrRB** [comment]
Да, всё осталось только на этом: https://ngs24.ru/text/food/2021/08/28/70102646/
Ко всем правилам, что здесь делал, добавь ещё эти сайты: `ngs22.ru,ngs24.ru,ngs38.ru,ngs42.ru,ngs54.ru,ngs55.ru,ngs70.ru`

**Comment by Alex-302** [comment]
Добавил.
