### ISSUE TITLE
onlinecoursereport.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93125]
**Issue URL (ads)**:https://www.onlinecoursereport.com/the-50-most-popular-moocs-of-all-time/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131494546-f41e1ea9-e023-4dc1-a315-7a119c6b8c1f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by chirag127** [comment]
@zloyden  i can reproduce
![image](https://user-images.githubusercontent.com/76880977/133185126-ee23ddcf-645c-40b6-8b97-78caba7c3175.png)

**Comment by zloyden** [comment]
Not an ad / annoyance, but you can remove it using the rule.
`onlinecoursereport.com#%#//scriptlet('remove-in-shadow-dom', '[label="Advertisement"]')`.
