### ISSUE TITLE
rediff.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93124]
**Issue URL (Annoyance)**:https://www.rediff.com/getahead/report/career-at-23-lakh-ba-is-indias-most-popular-course/20191002.htm

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131493625-a55e5afb-9bce-41aa-9521-7d9e85cf6a72.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
That's blocked on my end.
