### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#93136]
А чего не удаляются отслеживающие параметры при переходе по клику с новостного сайта?
https://twitter.com/NickKozlovich/status/1432665253700046850?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1432665253700046850%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Feuroradio.fm%2Fru%2Fu-onlinerby-budet-novyy-glavnyy-redaktor

**Comment by Alex-302** [comment]
Видимо баг. Посмотрим. Нужные правила в фильтре есть.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/tsurlfilter #34](https://github.com/AdguardTeam/tsurlfilter/issues/34) via [**ZenHub**](https://www.zenhub.com/)
