### ISSUE TITLE
[NSFW]pornhub.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#93177]
*You may need a US IP to encounter it*

ad
URL: (NSFW)`https://www.pornhub.com/`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/89752791/131579465-35357896-21f8-422c-a5c2-e7af34cd7184.png)

</details>

<details><summary>Screenshot of Filters:</summary>

![image](https://user-images.githubusercontent.com/89752791/131579613-a1367e35-d879-44f1-b6a0-51e3f81256cf.png)

</details>

**Comment by BlazDT** [comment]
I guess you are talking about that "Find Weed" button in screenshot?

**Comment by IMayKnow** [comment]
@BlazDT Yes, but I think it was addressed in EasyList.

**Comment by IMayKnow** [comment]
@Alex-302 @BlazDT could you address this?
