### ISSUE TITLE
topg.org

### ISSUE THREAD

**Issue by IMayKnow** [AdguardTeam/AdguardFilters#93193]
URL: `https://topg.org/`
Issue regarding the URL: leftovers
Encountered while using AdGuard Browser Extension (Filters: AdGuard Base Filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter)

**Comment by mountrogmr** [comment]
topg.org##main:nth-child(2) > div.ga_header:nth-child(2)
topg.org##main:nth-child(2) > div.ga:nth-child(3)
topg.org##main:nth-child(2) > div.main:last-child > div.container > div.row > div.col-lg-12:last-child > div.ga_header_f:nth-child(8)
