### ISSUE TITLE
talkesport.com

### ISSUE THREAD

**Issue by IMayKnow** [AdguardTeam/AdguardFilters#93196]
URL: `https://www.talkesport.com/guides/how-to-join-best-gta-rp-servers/`
Issue regarding the URL: space
Encountered while using AdGuard Browser Extension (Filters: AdGuard Base Filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter) & Brave

**Comment by Alex-302** [comment]
Please post screenshot.
