### ISSUE TITLE
grandoldteam.com/forum

### ISSUE THREAD

**Issue by Mennaruuk** [AdguardTeam/AdguardFilters#93212]
Issue URL (Annoyance/Anti-Adblock): [www.grandoldteam.com/forum](https://www.grandoldteam.com/forum) (similar to #84563)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/52135169/131597832-0ca3b2ff-1500-475f-b1b5-171555414fea.png)

</details><br/>

I also noticed same warning in the following sites:

bmw-scooters.com
cgarmy.com
ctx700-forum.com
demonscripts.com
eurocccam.net
forum.shoppingtelly.com
iptvsat-forum.com
largescaleforums.com
leaked.im _(NSFW)_
longpoint.on.ca
scriptsfire.com
udevstudio.com

**Comment by mountrogmr** [comment]
grandoldteam.com##div.j612f07d6d72f5744960127.c612f07d6d72fc722205039:nth-child(23)
