### ISSUE TITLE
gadgetsnow.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93218]
**Issue URL (Ads/ Incorrect blocking.)** :https://www.gadgetsnow.com/slideshows/windows-10-users-features-and-apps-that-will-be-removed-or-replaced-when-you-upgrade-to-windows-11/photolist/85823042.cms

> clicking on the ad take me to a broken page.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131615969-b641f3ac-89c5-4834-b63a-39fda7a27376.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
I don't see this element.
