### ISSUE TITLE
inbox.lt

### ISSUE THREAD

**Issue by Mennaruuk** [AdguardTeam/AdguardFilters#93216]
Issue URL (Annoyance/Anti-Adblock): https://inbox.lt

<details><summary>Screenshot 1:</summary>

![131610450-9a3c438b-65b2-4ce1-b966-3701e0b2cdf1_censored](https://user-images.githubusercontent.com/52135169/131610693-de96a74d-8b7b-4ed6-a817-5fe2b056433f.jpg)

</details><br/>

Anti-adblock prompt says:

"Adblock Detected! If you enjoy our email, please support us and purchase Mail+ account or disable your AdBlocker. We depend on ad revenue to keep creating quality service for you to enjoy for free.

Get Mail+

Yes, I will turn off adblock"

**Comment by Mennaruuk** [comment]
`inbox.lt##.in.fade.promo-modal_center-vertical.promo-modal_theme-default.promo-modal.modal`
`inbox.lt##.in.fade.modal-backdrop`

**Comment by Alex-302** [comment]
Cannot reproduce. Which filters?

**Comment by Mennaruuk** [comment]
Can you try in an incognito page? I have enabled:

- Ad Blocking (AdGuard Base, EasyList, Peter Lowe's)
- Privacy (AdGuard Tracking Protection, AdGuard URL Tracking, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking, Fanboy's Anti-Facebook)
- Social Widgets
- Annoyances (Adblock Warning Removal List, Web Annoyances Ultralist, Fanboy's Annoyances, AdGuard Annoyances)
- Security
- Other

This only shows once, and I think it gets saved in the cookies not to ever show again. But it still means anyone who doesn't have the filters I have in my second comment will stumble upon this warning on first visiting the site.

**Comment by Alex-302** [comment]
Reproduced, fixed.
