### ISSUE TITLE
usersdrive.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93224]
**Issue URL (Annoyance)**:https://usersdrive.com/36mqy8vkcddz.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131629865-e705b962-426a-4fc4-9305-d964ed1f07a4.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
They check if the timer is adjusted or modified.
