### ISSUE TITLE
janetpanic.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93264]
**Issue URL (Ads)** :https://janetpanic.com/do-atomic-bombs-still-exist/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131688782-f8b451fd-39fc-4cc3-8c49-89df2de62609.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
5370 visitors/month
