### ISSUE TITLE
healthline.com

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [AdguardTeam/AdguardFilters#93274]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
The filter `healthline.com#?##__next > div[class]:has(div[data-adbridg-ad-class])` added in [this commit](https://github.com/AdguardTeam/AdguardFilters/commit/74804f0a14a6f197dcd5f676fb0731ce34bd4528) is blocking content on the Healthline Website.
URL: `https://www.healthline.com/`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/88633614/131714750-c6c9d49d-5f03-485c-9094-0da15fde2560.png)
</details><br/>

***System configuration***

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Browser:                               | Firefox 91.0.2
Filters enabled:                       | Built-in uBlock Filters (uBlock filters, uBlock filters – Badware risks, uBlock filters – Privacy, uBlock filters – Resource abuse, uBlock filters – Unbreak), Adguard Base, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe's Ad and tracking server list, spa, por: AdGuard Spanish/Portuguese
Content Filter Software                | uBlock Origin v1.36.2

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Fixed.
