### ISSUE TITLE
cogipas.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93275]
**Issue URL (Annoyance)**:https://www.cogipas.com/privacy-guide-stay-anonymous-online/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131715378-039ae08c-d37b-4498-b94f-8d7511c1f325.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
