### ISSUE TITLE
filecollager.com

### ISSUE THREAD

**Issue by albertopasqualetto** [AdguardTeam/AdguardFilters#93282]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
When clicking "sign up for beta" nothing appears instead of subscription fields.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/39854348/131721334-6546d269-681c-49eb-b592-64341c9a89f6.png)
</details><br/>

**Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/39854348/131721182-7ef1ea9a-c546-405b-b62e-7f0dea47744a.png)
</details><br/>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10
Browser:                               |  Edge with uBlock
Filters enabled:                       | AdGuard Annoyances Filter

![image](https://user-images.githubusercontent.com/39854348/131721408-eb1be652-75c6-4083-a8b9-245b8765d3b5.png)

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/132511340-f5144731-c1a8-49cc-9f1d-4e0febecc126.png)
