### ISSUE TITLE
thetimes.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93365]
**Issue URL (Annoyance)**:https://www.thetimes.co.uk/article/what-i-found-out-as-a-woman-on-incel-sites-75w58jgl8

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131825664-c0cdd42d-4284-435b-baab-ef7353b07bb2.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can't reproduce this popup.
