### ISSUE TITLE
counterextremism.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#93377]
**Issue URL (annoyance)** :
https://www.counterextremism.com/content/unknown-user-incel-forum-unknown-date-1

<details><summary>Screenshots:</summary>

https://www.counterextremism.com/content/unknown-user-incel-forum-unknown-date-1
![image](https://user-images.githubusercontent.com/82926303/131827302-df1b603e-0d45-4d9e-a8b6-3ad6fb7eaa22.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by Alex-302** [comment]
Element in the footer, not annoying.
