### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#93385]
**Issue URL (Ads)** :
https://www.msn.com/en-in/news/other/delhi-rains-live-updates-heavy-rain-continue-to-lash-capital-adjoining-noida-imd-says-rainfall-likely-in-many-states-till-sept-5/ar-AAO0bnh?ocid=winp1taskbar

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/131832611-95699b85-076a-4cb9-85f1-055603180409.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by BlazDT** [comment]
No left-over shown for me.

**Comment by neer9** [comment]
Many ads leftover are showing to me here in India. Can you please try using
vpn with Indian server selected?

**Comment by neer9** [comment]
![image](https://user-images.githubusercontent.com/82926303/131842973-b6e59bfe-cfa9-436c-a31d-a12a32fce36e.png)
 

here is the code if it can help.

**Comment by neer9** [comment]
@BlazDT

**Comment by Alex-302** [comment]
Also not reproduced.
