### ISSUE TITLE
unblocknow.club

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93387]
**Issue URL (Ads)** :
https://tamilblasters.unblocknow.club/index.php?/forums/forum/53-english-movies-hdrips-bdrips-dvdrips/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131837823-db617f96-c1bd-46e7-bc05-1c934d74f0f0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors, fixed popunders and ads on unblocknow.club
