### ISSUE TITLE
newsweek.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#93380]
**Issue URL (Ads)** :
https://www.newsweek.com/self-proclaimed-incel-arrested-ahead-planned-shooting-targeting-women-college-1611999

<details><summary>Screenshots:</summary>

https://www.newsweek.com/self-proclaimed-incel-arrested-ahead-planned-shooting-targeting-women-college-1611999
![image](https://user-images.githubusercontent.com/82926303/131828020-e3851c3e-506c-4a79-bb1c-bb1c43e153de.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by gork7777** [comment]
This already blocked.
