### ISSUE TITLE
https://cryptofans.news/?framed=true

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#93416]
**Issue URL (Ads)** :https://cryptofans.news/?framed=true

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/131858543-51a28896-11b6-48ed-ae83-c24f321947fc.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by IMayKnow** [comment]
`@@||gagaltotal666.my.id^$generichide` may be good for addressing the anti adb
