### ISSUE TITLE
extension.today

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93447]
**Issue URL (Annoyance)**:https://extension.today/chrome/reverse-text-generator-%E1%90%88-spell-backwards/50834930

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131872992-875136d0-bec6-452c-93ec-088102871f6d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
