### ISSUE TITLE
indiaidol.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93458]
**Issue URL (Ads)** :
https://indiaidol.net/taarak-mehta-ka-ooltah-chashmah-2nd-september-2021-episode-3244-video/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131884696-7dbe09b5-3a37-416b-8474-3c4fb715ff85.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
