### ISSUE TITLE
indiatalks.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93450]
**Issue URL (Ads)** :
https://indiatalks.org/how-to-destroy-io-intel-in-fortnite/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131874267-03e7b92a-1bb9-4e07-863f-1f15454ee5ec.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>https://indiatalks.org/how-to-destroy-io-intel-in-fortnite/

**Comment by Sergey-Lyapin** [comment]
5520 visitors/month.
