### ISSUE TITLE
suay.site

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93529]
**Issue URL (Ads)** :

https://suay.site/?p=838
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131979593-ca36231f-9940-4b3b-92bb-646c30418fc0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4500 visitors/month
