### ISSUE TITLE
marcomrobot.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93538]
**Issue URL (Annoyance)**:
https://www.marcomrobot.com/blog/how-to-find-website-url-from-company-name-in-bulk

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131981333-0bc65fd8-37a4-48a3-ab83-ddbf6ffb21c8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
8500 visitors/month
