### ISSUE TITLE
wpbeginner.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93532]
**Issue URL (Annoyance)**:
https://www.wpbeginner.com/wp-tutorials/how-to-add-google-search-in-a-wordpress-site/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131979962-566124a7-d208-4916-9866-40576ab7be27.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I think we should not remove these elements, there are just a links to site's another pages and they don't annoy.
