### ISSUE TITLE
seohorsesense.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93537]
**Issue URL (Annoyance)**:https://seohorsesense.com/free/extract-domains.php

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131981410-ce94ee4c-3fff-4b03-ac0f-51b625e575ab.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
