### ISSUE TITLE
joydeepdeb.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93559]
**Issue URL (Annoyance)**:https://www.joydeepdeb.com/tools/check-status-code.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132003346-f46b6d56-2791-4d28-ab88-c4e85e0f14cc.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
24500 visitors/month.
