### ISSUE TITLE
shop.bora-sauna.de

### ISSUE THREAD

**Issue by MightyKnight** [AdguardTeam/AdguardFilters#93583]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Incorrect blocking in the **AdGuard Annoyances** list.
Affected url: https://shop.bora-sauna.de/tickets/template/1316/
The calendar on the site is prevented from loading, because the cookie-consent script is blocked.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/38622942/132019767-c61ef646-de4e-4499-9a9a-ec8018475453.png)

</details><br/>

**Expected behaviour**: 
Allowing the calendar to load, e.g. by not blocking `shop.bora-sauna.de/components/cookieconsent2/build/cookieconsent.min.js` script, since it seems connected to the sites functionality.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/38622942/132019982-999f18cf-4f5e-4fa4-be69-b229b44a5ee9.png)

</details><br/>

***Steps to reproduce the problem***:
Enable only the Adguard Annoyances list
2. Go to the url https://shop.bora-sauna.de/tickets/template/1316/
3. Enter some number in the fields on the right
4. Click on the button

Result will be nothing happening, while without the filter a calendar will be displayed.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

Adguard Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox
AdGuard version:                       | using Ublock Origin
Filters enabled:                       | Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
