### ISSUE TITLE
kinovego.ru

### ISSUE THREAD

**Issue by Kocsten** [AdguardTeam/AdguardFilters#93595]
Приветствую вас, так получилось у меня кино сайт по адресу http://kinovego.ru/ и многие пишут, что плеер битый, что потом сам установил приложение AdGuard и сам увидел такую картинку, это при включенным AdGuard - https://rataku.com/images/2021/09/03/561.jpg

Сам плеер один, но имеет несколько ссылок, а точнее 4 ссылки, которые AdGuard блокирует видео.

Как пример:
Ссылка для ставки видео

<iframe width="560" height="400" src="https://api1578915698.embedstorage.net/embed/movie/3766" frameborder="0" allowfullscreen=""></iframe>

И коду ставки перелагаю ссылки вывода видео

embedstorage.net
multikland.net
mir-dikogo-zapada.com
placehere.link

На этих ссылках не выводится видео, вот к примеру видео ссылкой http://kinovego.ru/load/prizrachnyj_patrul_2013_smotret_onlajn/18-1-0-131 - смотреть при включенном AdGuard.

Пожалуйста можно эти 4 домена на сайте http://kinovego.ru/ сделать так, чтоб они открывали видео а не блокировали его.

**Comment by Alex-302** [comment]
Через час будет доступно обновление, которое чинит плеер.

**Comment by Kocsten** [comment]
Спасибо!
