### ISSUE TITLE
elzaburu.es

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93666]
**Issue URL (Annoyance)**:https://www.elzaburu.es/blog/2021/02/spain-removed-from-notorious-markets-list-2020.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132086060-2907889b-41e1-41b7-9a82-6daeb1035a90.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
8280 visitors/month
