### ISSUE TITLE
enchan-trixto.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93676]
**Issue URL (Ads)** : https://enchan-trixto.com/hotstar-video-downloader/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132088190-c3691042-5ae4-4236-97de-a28588ce6555.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
8690 visitors/month
