### ISSUE TITLE
animationxpress.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93691]
**Issue URL (Annoyance)**:https://www.animationxpress.com/latest-news/exclusive-studio-durga-indias-first-anime-studio-creates-a-stir-within-the-indian-anime-community-with-the-trailer-of-karmachakra/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132091863-0f1cf261-4452-4c31-86fb-9605433eeb8e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/c123baeea4dbe6f09ff6d4ea8696cf88172fec1d
