### ISSUE TITLE
Send Anywhere has apparently unskippable ad/timer

### ISSUE THREAD

**Issue by Mennaruuk** [AdguardTeam/AdguardFilters#93700]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Send Anywhere is a file transfer site.

It has ads that are seemingly unskippable.

**Current behaviour**:

After entering the code on my PC, I have to wait about five seconds until the download starts.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/52135169/127789604-1f13035d-e0ec-4b87-8c45-e6177fe0b99d.mp4

</details><br/>

**Expected behaviour**: 

It'd save time to skip this timer, I send lots of files through Send Anywhere, and it's annoying to go through this every time.

***Steps to reproduce the problem***:

To reproduce, try to send a file from your phone to your computer. You should get a code. Input the code you get on your phone into your computer.

Then, the ad appears. It isn't really an ad, since nothing shows but a five-second timer. When the timer ends, the skip button shows. But it's still annoying.

***System configuration***

**Filters:**

- Ad Blocking (AdGuard Base, EasyList, Peter Lowe's)
- Privacy (AdGuard Tracking Protection, AdGuard URL Tracking, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking, Fanboy's Anti-Facebook)
- Social Widgets
- Annoyances (Adblock Warning Removal List, Web Annoyances Ultralist, Fanboy's Annoyances, AdGuard Annoyances)
- Security
- Other

**Notes:**

[This is how the friends at uAssets mitigated this timer.](https://github.com/uBlockOrigin/uAssets/commit/902900ae022b08f9c187511224f4f096b3991164)

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
need download links

**Comment by Mennaruuk** [comment]
It’s peer to peer. I can try sending you something, but you can do it too (from your phone or another computer). Then, you’ll get a code for you to enter on the receiving device. After that, download should begin.

**Comment by Alex-302** [comment]
Ok, fixed.
