### ISSUE TITLE
coursesbyvivekbindra.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93713]
**Issue URL (Annoyance)**:
https://coursesbyvivekbindra.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132102095-61c097b1-3bd9-4c9c-80a8-953f1bc277b1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
