### ISSUE TITLE
vivekbindraindia.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93719]
**Issue URL (Annoyance)**:
https://vivekbindraindia.com/ibc

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132102316-d229b60f-41ad-4b96-8f9d-93bff3ae073a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
