### ISSUE TITLE
zitcogroup.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93718]
**Issue URL (Annoyance)**:
https://zitcogroup.com/ibc-bada-business-by-dr-vivek-bindra/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132102240-277c2a0d-363b-4348-9757-aa2d1f9869cf.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
