### ISSUE TITLE
thehiteshyadav.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93714]
**Issue URL (Annoyance)**:
https://thehiteshyadav.com/eae/

<details><summary>Screenshots:</summary>https://thehiteshyadav.com/eae/

![image](https://user-images.githubusercontent.com/76880977/132102108-b69d0ccb-9bb4-4b21-835f-a85178a1ae7f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
