### ISSUE TITLE
theblueoceansgroup.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93717]
**Issue URL (Ads)** :https://www.theblueoceansgroup.com/eae-everything-about-entrepreneurship/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132102180-89f27538-c6d3-4956-8ce3-b4f23a446ce9.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
24200 visitors/month.
