### ISSUE TITLE
kyoto.travel

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93729]
**Issue URL (Annoyance)**:http://cdn.kyoto.travel/single/DWXwVK7rrNY/pradhanmantri-episode-7-lal-bahadur-shastri-abp-news-hindi

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132106519-d13eea65-662b-4a53-ad2e-6ce1445d5151.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
This site is unavailable.
