### ISSUE TITLE
badabusiness-mp.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93721]
**Issue URL (Annoyance)**:
https://www.badabusiness-mp.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132102340-931212f4-5926-4c79-af90-b6756e31fcc8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2310 visitors/month
