### ISSUE TITLE
aptechlearning.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93744]
**Issue URL (Annoyance)**:https://www.aptechlearning.com/it/data-strcutures-in-C-course.aspx

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132108317-4f336479-d220-4b10-a0ae-c8347f1ee3c4.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
