### ISSUE TITLE
codinghumans.xyz

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93741]
**Issue URL (Ads)** :https://www.codinghumans.xyz/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132108155-84cad2cc-e8fe-4310-a838-2aee617c2810.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
