### ISSUE TITLE
learncomputerscienceonline.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93819]
**Issue URL (Ads)** :https://www.learncomputerscienceonline.com/computer-organization-and-architecture/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132133311-18853d54-d9d6-4ea4-bd82-17189b6763e7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`www.learncomputerscienceonline.com###text-3`
`www.learncomputerscienceonline.com###fbw_id-3`

**Comment by zloyden** [comment]
This website has low visitors, but you can add these rules https://github.com/AdguardTeam/AdguardFilters/issues/93819#issuecomment-913247710.
