### ISSUE TITLE
maximonline.ru vokrugsveta.ru

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#93839]
Эти сайты (и ряд других с ними) родственные, а все правила для них в фильтрах общие.
Справа при скроллинге сменяющиеся баннеры, а на сайте Maxim дополнительно подписка на рассылку.  
https://www.vokrugsveta.ru/articles/mozhno-li-dostich-kraya-vselennoi-id668771/
https://www.maximonline.ru/guide/skoro-osen-a-u-tebya-eshe-net-novogo-telefona-id673696/

<details><summary>Screenshot:</summary>

![vokrugsveta](https://user-images.githubusercontent.com/50718960/132137647-321ac567-e92a-42bf-968e-6669635c954c.png)

![maximonline](https://user-images.githubusercontent.com/50718960/132137650-ad65dae7-58f4-4ef1-b015-e847cdc6dd45.png)

</details><br/>

**Comment by Alex-302** [comment]
Справа не повторяется.

**Comment by zubrRB** [comment]
А у меня повторяется. Нужно выждать. При перелистывании статей эти баннеры сменяются, что на одном, что на другом.
Прикрепил сохранённую страницу: [MAXIM.zip](https://github.com/AdguardTeam/AdguardFilters/files/7114767/MAXIM.zip)


Ссылки такого вида: 
https://www.maximonline.ru/gm-api/service-scrooge/click?adunitId=70&creativeId=281&campaignId=150&url=https%3A%2F%2Fwww.vokrugsveta.ru%2Farticles%2Fchelovek-umelyi-v-trekh-machtakh-id674662%2F%3Futm_source%3Dvokrugsveta.ru%26utm_medium%3Dbanner%26utm_content%3Dtgb%26utm_campaign%3D2899552465

https://www.vokrugsveta.ru/gm-api/service-scrooge/click?adunitId=119&creativeId=282&campaignId=150&url=https%3A%2F%2Fwww.vokrugsveta.ru%2Farticles%2Fkrugosvetka-staryi-sposob-obognut-mir-id674656%2F%3Futm_source%3Dvokrugsveta.ru%26utm_medium%3Dbanner%26utm_content%3Dtgb%26utm_campaign%3D2899552465

**Comment by zubrRB** [comment]
Правило для фильтра раздражителей пришло, но чёйта баннеры при скроллинге ниже продолжают маячить.

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/132199330-a76881e4-134a-4074-b0d0-46db3b4fc80f.png)
</details><br/>

**Comment by Alex-302** [comment]
У меня чисто и с прогой и с расширением.

**Comment by zubrRB** [comment]
У меня теперь тоже.

**Comment by zubrRB** [comment]
На сайте `vokrugsveta.ru` все равно баннеры присутствуют. Видео: https://wdfiles.ru/9136e3
