### ISSUE TITLE
inshorts.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93833]
**Issue URL (ANNOYANCE)** :
https://inshorts.com/en/news/promo-featuring-aamir-khan-on-koffee-with-karan-released-1481543977458

<details><summary>Screenshots:</summary>

https://inshorts.com/en/news/promo-featuring-aamir-khan-on-koffee-with-karan-released-1481543977458
![image](https://user-images.githubusercontent.com/76880977/132136419-f49c022a-743d-44b0-8d3d-b6df7a966ea0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`inshorts.com##div[class^="hide-on-med-and-down"]`

**Comment by chirag127** [comment]
> `inshorts.com##div[class^="hide-on-med-and-down"]`

BTW, if you can simply edit the relevant file and add this filter to relevant place in the file and make a pull request will be very helpful if you have time.

**Comment by Mennaruuk** [comment]
No problem, just finished making PRs for all issues I responded to. I also learned about branches today, they saved me plenty of headaches 😅
