### ISSUE TITLE
baristainstitute.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93831]
**Issue URL (Annoyance)**:
https://www.baristainstitute.com/blog/emmi-kinnunen/october-2019/affogato-ristretto-list-most-common-coffee-drinks

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132135417-e184dd6b-a6cb-4a6c-8357-4508c0362603.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`www.baristainstitute.com##.layout-sidebar-second`
