### ISSUE TITLE
inspirenignite.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93838]
**Issue URL (Annoyance)**:
https://www.inspirenignite.com/up/energy-science-engineering-ev-4th-sem-syllabus-for-aktu-b-tech-2019-20-scheme-select-subject-3/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132137110-5533bdd4-f882-4c7b-8a19-4cf338c731c9.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
It's part of the article.

**Comment by chirag127** [comment]
@zloyden please tell me user filter. As this  element is on many pages.

**Comment by zloyden** [comment]
`inspirenignite.com#?#.entry-content > div[class][data-index] > a[href^="https://play.google.com/"]:upward(1)`
