### ISSUE TITLE
medindia.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93832]
**Issue URL (Annoyance)**:
https://www.medindia.net/patients/patientinfo/coffee-types-varieties.htm

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132135442-29a4e836-deb6-4614-b7cf-6589800834e2.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by chirag127** [comment]
@zloyden 
I can still reproduce, it is possible that they don't provide services outside india so they only show this pop up to indian ips.

**Comment by zloyden** [comment]
I removed some leftovers and annoyances, but I haven't reproduced the popup even with Indian IP.
Can you show this element with opened devtools?

**Comment by chirag127** [comment]
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133779110-c21fd0d8-6fef-4a4b-91dd-8ede9bea3b76.png)

![image](https://user-images.githubusercontent.com/76880977/133779226-48300bde-75e2-4274-b2b3-6bc1a048f269.png)


</details><br/>

**Comment by zloyden** [comment]
Try this:
```
medindia.net##.bottom-popup
```
