### ISSUE TITLE
alkas.lt

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93835]
**Issue URL (Ads)** :https://alkas.lt/2021/08/26/del-teises-aktu-painiavos-zemdirbiai-netenka-8-mln-euru/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132136571-ca39672a-1795-4fae-84c2-a9f79b63fb0e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Fixed in EasyList Lithuania
