### ISSUE TITLE
webstaurantstore.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93830]
**Issue URL (Annoyance)**:
https://www.webstaurantstore.com/article/397/types-of-coffee-drinks.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132135400-13260242-7180-4317-b046-8834ac00796a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
Remove mailing list nag only:
`webstaurantstore.com##.fsr-email-prompt`

Remove mailing list nag + photo boxes under:
`webstaurantstore.com##.fsr-side.side-bottom`
