### ISSUE TITLE
mondaq.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93849]
**Issue URL (Annoyance)**:https://www.mondaq.com/india/trademark/1032542/ustr-releases-notorious-markets-list-2021-for-counterfeiting

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132138921-dbcf33f2-77d8-435e-b3dd-739df07d3bf5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
mondaq.com##.cd-user-modal
