### ISSUE TITLE
pakpassion.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93845]
**Issue URL (Annoyance)**:http://www.pakpassion.net/ppforum/showthread.php?42642-All-is-nothing-therefore-nothing-must-end

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132138114-eedf1465-72f5-498e-870a-ab639e7ce19e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`pakpassion.net###sidebar_container`
