### ISSUE TITLE
missouribotanicalgarden.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93842]
**Issue URL (Annoyance)**:http://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a692

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132138027-ef2be7aa-ff1a-4bf2-88fd-7bd118452760.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`missouribotanicalgarden.org###GHPageBodyContentRight`
