### ISSUE TITLE
worldtrademarkreview.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93848]
**Issue URL (Ads)** :
https://www.worldtrademarkreview.com/anti-counterfeiting/notorious-markets-list-2020-ustr-resists-call-include-us-platforms-alibaba-and-amazon-remain

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132138907-507fafe5-53e0-48a4-a9f6-36711673047d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`worldtrademarkreview.com##div[class^="advert-strip"]`
