### ISSUE TITLE
missouribotanicalgarden.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93843]
**Issue URL (Annoyance)**:
https://www.missouribotanicalgarden.org/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132138037-44060341-d2b0-4fcc-b2d3-a7eb859e87c0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`missouribotanicalgarden.org##div[id^="dnn_ctr13400"]`
