### ISSUE TITLE
brandwatch.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93854]
**Issue URL (Annoyance)**:

https://www.brandwatch.com/blog/youtube-stats/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132141443-213d8157-8039-4af5-9c12-d2e94c1fc871.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`brandwatch.com##.pb3`
