### ISSUE TITLE
ftc.gov

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93856]
**Issue URL (Annoyance)**:https://www.ftc.gov/news-events/blogs/business-blog/2019/11/youtube-channel-owners-your-content-directed-children

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132141440-d2f4c9d5-1ecf-4049-aca1-62291d09be81.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`ftc.gov###block-block-301`

**Comment by chirag127** [comment]
> `ftc.gov###block-block-301`

Well there is a better class name available if you look closer into the source code . We try to make rules with names that makes sense.
