### ISSUE TITLE
natlawreview.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93850]
**Issue URL (Social Widget)** :https://www.natlawreview.com/article/us-trade-representative-names-5-chinese-online-markets-2020-review-notorious-markets

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132138932-46e9023f-68ba-4dec-be62-f23b0f215b71.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Mennaruuk** [comment]
`natlawreview.com##.fb_likebox`
