### ISSUE TITLE
livelaw.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93920]
**Issue URL (Incorrent blocking)**:
https://www.livelaw.in/top-stories/neet-all-india-quota-neet-aiq-supreme-court-notice-in-pleas-against-27-obc-10-ews-quota-180996

> broken header .
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132203340-b56ec26f-3440-42a4-a8ac-d6bf3fac058a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/88430#issuecomment-883455833
