### ISSUE TITLE
infoq.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93965]
**Issue URL (Annoyance+TRACKING PARAMETERS)**: https://www.infoq.com/articles/kotlin-ten-years-qa/?topicPageSponsorship=9df7746f-b196-415b-964e-bc8483319fd9&itm_source=articles_about_development&itm_medium=link&itm_campaign=development

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132252298-330177c8-680c-4c8d-86eb-9ed948e82b8c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
May be interestings.
