### ISSUE TITLE
chinese alibaba tracker ESCAPED!

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#94018]
```
/amdc/mobileDispatch
```

If Alibaba's tracker finds that it cannot successfully send a tracking request containing user information, it will try to send it in the form of ip and successfully escape the interception.

It seems to request the IP of the domain name from its own doh server, and that doh server is not blocked, at least not yet.

![Screenshot_20210908-004130_Trebuchet~2.png](https://user-images.githubusercontent.com/75058881/132382680-14301130-3a56-41e1-9865-f451defc582f.png)![Screenshot_20210908-004731_Trebuchet.png](https://user-images.githubusercontent.com/75058881/132382683-62191ce8-1c01-41bc-a6db-d62a63ce7ff2.png)![Screenshot_20210908-004739_Trebuchet.png](https://user-images.githubusercontent.com/75058881/132382689-4e14ed6a-0f36-4376-8dd7-4ef1b05c10ff.png)

**Comment by Alex-302** [comment]
Need HAR file with these requests.

**Comment by c2xusnpq6** [comment]
> Need HAR file with these requests.
> 

does adguard have related functions? i'm not good at this......

**Comment by Alex-302** [comment]
https://kb.adguard.com/en/android/solving-problems/har#howtoget
