### ISSUE TITLE
fossmint.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94026]
**Issue URL (Ads)** :https://www.fossmint.com/watch-blocked-youtube-videos/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132399596-ece56c5f-814f-4707-8619-f1d605b7754b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/134540631-89c14534-c8f2-45c8-a4ae-613eb16d624c.png)
 not an ad
