### ISSUE TITLE
theregister.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94068]
**Issue URL (Social Widget)** :

https://www.theregister.com/2021/09/07/protonmail_hands_user_ip_address_police/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132462744-7f3025b4-4f6e-4e6c-ad8d-7d9fb325c506.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Apious** [comment]
theregister.com##.wptl

already blocked from EasyList (https://forums.lanik.us/)
https://github.com/easylist/easylist/raw/master/easylist/easylist_general_block.txt

**Comment by chirag127** [comment]
> theregister.com##.wptl
> 
> already blocked from EasyList (https://forums.lanik.us/)
> https://github.com/easylist/easylist/raw/master/easylist/easylist_general_block.txt

Well it's not a advertisement.
