### ISSUE TITLE
filecloud.to

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94083]
**Issue URL (Annoyance)**:https://filecloud.to/czzheliv9o04.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132496783-5d89d255-1e6d-4872-b33d-f764c83da64c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
It's probably checked on server side, because boosting timer causes that website display notice - `Skipped countdown`.
