### ISSUE TITLE
livetolearn.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94107]
**Issue URL (Annoyance)**:
https://www.livetolearn.in/site/blog/convert-currency-number-words-ms-word

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132551558-9b0fcf02-e78a-44b0-9505-065fc018cf84.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
7480 visitors/month
