### ISSUE TITLE
madeintext.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94105]
**Issue URL (Ads)** :https://www.madeintext.com/number-to-words/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132551171-ecd8478f-15da-4418-8122-5e9efb1d2f17.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
It seems that it's already fixed.
