### ISSUE TITLE
whncourses.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94120]
**Issue URL (Annoyance)**: https://whncourses.com/the-complete-javascript-course-2021-from-zero-to-expert-free-download/

> click on the free download ot reproducee teh timer
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132582656-ba37a012-7a5f-492c-8034-2cdbe3fb2195.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2910 visitors/month

**Comment by chirag127** [comment]
Please tell me user filter.
