### ISSUE TITLE
queuecosm.bid [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#9413]
**Site**: http://queuecosm.bid/rweasy/-12/2924562/goodbye-christopher-robin-2017?rndad=3075669834-1515244142

**Issue**: Please remove the adblock message.

**Screenshot**: http://prntscr.com/hwtgz4

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Was fixed in commit https://github.com/AdguardTeam/AdguardFilters/commit/ca5dc62230eef5bd1a7f033787ec63c8a255fafa
