### ISSUE TITLE
downloadr.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94197]
**Issue URL (Ads/Annoyance)**:https://downloadr.in/download/?https://drive.google.com/file/d/1l0L9YxNXumEQ0d6hOixlTa4qwucCbJ7z/view?usp=sharing

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132771326-b487fd5a-80df-4918-940c-bb901f45dcfe.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
20900 visitors/month.

**Comment by Sergey-Lyapin** [comment]
for user rules:
`downloadr.in#%#//scriptlet("adjust-setTimeout", "countdown", "", "0.02")`
