### ISSUE TITLE
javadeveloperzone.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94200]
**Issue URL (Annoyance)**:
https://javadeveloperzone.com/nodejs/difference-between-var-let-and-const-in-nodejs/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132778629-19028dc4-6070-4932-aa08-65da1d15a1e9.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
not reproduced with your settings
![Безымянный324](https://user-images.githubusercontent.com/18536328/134391945-96187a91-6d0b-4100-8a66-4c51cdc5fe83.png)
