### ISSUE TITLE
dharma-production.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94216]
**Issue URL (Annoyance)**:https://dharma-production.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132817595-59e76153-3b8d-4f6a-a4b4-2838324588c7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
11400 visitors/month
