### ISSUE TITLE
seaofapps.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94259]
**Issue URL (Ads/Annoyance)**: https://www.seaofapps.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132883857-fe183a86-dc74-4606-8711-8199977772b0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2940 visitors/month
