### ISSUE TITLE
apkdl.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94265]
**Issue URL (Ads/Annoyance)**:https://apkdl.in/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132884397-619c64a6-abde-4889-95cb-6b0e005555ec.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
I'm not sure if it should be blocked.
 It's empty even without any ad blocker.

For user filter:
```
apkdl.in#?#.section > .tab-demo.z-depth-1 > li.indicator:empty:upward(1)
```
