### ISSUE TITLE
allinonedownloadzz.site

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94264]
**Issue URL (Ads/Annoyance)**:
https://allinonedownloadzz.site/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132884343-834047de-8fab-40ef-8305-5981cf5fca4d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can't reproduce the issue with your settings and indian IP.
