### ISSUE TITLE
courseboat.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94275]
**Issue URL (Ads/Annoyance)**:

https://courseboat.com/tutorials/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132885582-a8445ea6-f6e0-4b79-995a-c600106618f5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
8260 visitors/month
