### ISSUE TITLE
btechveda.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94272]
**Issue URL (Ads/Annoyance)**:https://btechveda.in/angular-the-complete-guide-2021-edition/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132885156-8b0fa297-856b-48fd-9fca-c502e97a7336.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
6 990 visitors/month
