### ISSUE TITLE
courselala.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94278]
**Issue URL (Ads/Annoyance)**: https://courselala.com/tutorials/
https://freecourseweb.com/
https://devcourseweb.com/
https://coursewikia.com/
https://courseboat.com/
https://coursehulu.com/
https://courselala.com/
https://coursemega.com/
https://coursepig.com/
https://tutgator.com/
https://tutpig.com/
https://tutsala.com/
https://tutgee.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132886150-1553eaed-4610-447b-ad62-5d813023e9bf.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
