### ISSUE TITLE
coursesvip.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94285]
**Issue URL (Ads/Annoyance)**:https://coursesvip.com/russell-brunson-funnelology-masterclass-2021-download/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132886577-cb164a53-3b18-44f1-8fe9-e9a6cf020ca5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
