### ISSUE TITLE
coursehulu.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94280]
**Issue URL (Ads/Annoyance)**:https://coursehulu.com/tutorials/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132886025-532d4771-b4d0-4c29-af85-e69c957e8f42.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
This website has low visitors.
