### ISSUE TITLE
courseupload.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94287]
**Issue URL (Annoyance)**:

https://courseupload.net/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132886670-5899f50f-7c8f-405e-8563-5cd6f68cffec.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
That was fixed.
