### ISSUE TITLE
dashcourse.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94288]
**Issue URL (Annoyance)**:https://dashcourse.net/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132887071-0d6402d9-b9fa-4992-aa44-4d362930dfa2.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
3750 visitors/month
