### ISSUE TITLE
johnsoftwares.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94306]
**Issue URL (Annoyance)**:
https://johnsoftwares.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132891154-a948bff5-cc12-475c-9235-31cca0132c4d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
10400 visitors/month,
