### ISSUE TITLE
goaudio.online

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94302]
**Issue URL (Ads/Annoyance)**:

https://goaudio.online/whole-loops-golden-bundle-premium/
<details><summary>Screenshots:</summary>

https://goaudio.online/whole-loops-golden-bundle-premium/
![image](https://user-images.githubusercontent.com/76880977/132890571-1f007cb8-9ac9-4e82-8822-0ee8defdcba1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
3300 visitors/month
