### ISSUE TITLE
nefeblog.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94314]
**Issue URL (Ads/Annoyance)**:
https://nefeblog.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132891918-e3b9517d-4de0-403b-b579-0914566887b1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
3120 visitors/month
