### ISSUE TITLE
libraryoftrader.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94312]
**Issue URL (Annoyance)**:https://libraryoftrader.net/?__cf_chl_managed_tk__=pmd_UFhNkcja6DtVKB551CXfa84X_MhGoBN16De2y3QTVtQ-1631293730-0-gqNtZGzNAqWjcnBszRE9

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132891541-5b1c220f-279f-4487-917f-c776e3067f3b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
