### ISSUE TITLE
worldfreeware.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94321]
**Issue URL (Ads/Annoyance)**:https://worldfreeware.com/

<details><summary>Screenshots:</summary>

https://worldfreeware.com/
![image](https://user-images.githubusercontent.com/76880977/132894865-5abdaae7-3d36-4d26-885a-4752a6c53f9e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
A don't see another way to buy premium so it's better to leave it as is.
