### ISSUE TITLE
www.heroturko.bz

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94329]
**Issue URL (Ads/Annoyance)**:
https://www.heroturko.bz/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132895988-b34384f0-fbdc-4fba-8694-c5cb17bb132c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
1 680 visitors/month
