### ISSUE TITLE
www.grafixfather.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94328]
**Issue URL (Ads/Annoyance)**:

https://www.grafixfather.com/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132895912-1145098c-8610-4a14-ac2b-c4c4abd962f6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The site isn't available.
