### ISSUE TITLE
www.topclassstudy.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94331]
**Issue URL (Ads/Annoyance)**:
https://www.topclassstudy.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132896559-7f9e0797-5e43-4dbc-9406-8b1fae3920b5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
