### ISSUE TITLE
androidcentral.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94402]
**Issue URL (Ads/Annoyance)**:https://www.androidcentral.com/why-does-chrome-use-so-much-memory

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132950465-39461509-d9db-4ae2-9d85-23d74d65e838.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not an ad or annoyance.
