### ISSUE TITLE
lovehdwallpapers.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#9440]
**Site**: http://lovehdwallpapers.com/

**Issue**: Please remove the adblock message.

**Screenshot**: http://prntscr.com/hx30ge

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
1.
