### ISSUE TITLE
piunikaweb.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94413]
**Issue URL (Incorrect Blocking)**:

https://piunikaweb.com/2018/12/12/more-info-on-t-series-website-hack/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132952137-a69d5e26-f52e-45da-8bf6-6eb786f64153.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by gork7777** [comment]
This caused by `Fanboy's Annoyances filter`.

**Comment by chirag127** [comment]
numara This caused by adguard social 
![image](https://user-images.githubusercontent.com/76880977/132955755-f10fb0a6-63ff-4ae4-bd7f-0729ad2f44bf.png)
![image](https://user-images.githubusercontent.com/76880977/132955754-63671a5a-df09-49bc-ba7d-dcd0d5ec13e4.png)

**Comment by Sergey-Lyapin** [comment]
caused by `##.fb_iframe_widget` from Fanboy's Annoyances.
https://forums.lanik.us/viewtopic.php?f=64&t=46779

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/453b35b7fe7ca9c6f653fc4765e86996f4070098
