### ISSUE TITLE
www.sohu.com

### ISSUE THREAD

**Issue by shenzhiming88** [AdguardTeam/AdguardFilters#94449]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ad placeholder at the end of the news

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/66902050/132969418-4993fcf7-1937-46a5-94be-a03557265292.png)
</details><br/>

* **Expected behaviour**: 

There should be no advertising placeholders at the end of the news

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***Steps to reproduce the problem***:

- Open https://www.sohu.com/a/488013591_267106
- Pull down the page until you see everyone is watching(`大家都在看`)

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

<details>

uBlock filters

uBlock filters – Badware risks

uBlock filters – Privacy

uBlock filters – Resource abuse

uBlock filters – Unbreak

EasyList

EasyPrivacy

Online Malicious URL Blocklist

Fanboy’s Annoyance

uBlock filters – Annoyances

Peter Lowe’s Ad and tracking server list

CHN: AdGuard Chinese (中文)

</details>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 (64-bit)
Operating system version (Android/iOS) | 21H1 19043.1110
Browser:                               | Microsoft Edge 92.0.902.55
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see that block

![image](https://user-images.githubusercontent.com/8361299/133609326-fce2d68b-dfeb-4cdc-ab90-379cfa7e3ed2.png)

**Comment by shenzhiming88** [comment]
> I don't see that block
> Screenshot:

Well, you may need click `展开全文↓` to see that
I will check it tomorrow. I don't know whether `AdGuard Base` hides it.

**Comment by shenzhiming88** [comment]
@Alex-302 
<details>
<summary>Screenshot</summary>

![网页捕获_19-9-2021_155112_www sohu com](https://user-images.githubusercontent.com/66902050/133919848-112f33ca-e89d-42c6-8763-46100e18ec97.jpeg)

</details>

**Comment by Alex-302** [comment]
On my end Taboola widget is hidden by EasyList rules. I see it with these exclusions:
```
#@##taboola-below-article-thumbnails
#@#.trc_related_container div[data-item-syndicated="true"]
#@#.trc_rbox_div .syndicatedItem
#@#.trc_rbox_border_elm .syndicatedItem
#@#.trc_rbox .syndicatedItem
#@#.trc-content-sponsored
```

Also it can be blocked by our Spyware filter or by this rule `||cdn.taboola.com^$domain=sohu.com`

**Comment by shenzhiming88** [comment]
@Alex-302 Sorry I didn't see it in time
I used EasyList but didn't hide it
So, can you recheck it? Thanks

**Comment by shenzhiming88** [comment]
@Alex-302 I'm sorry I didn't see your response in time.
I wasn't trying to hide the Taboola widget, but the blank spaces in it, like the image above shows
