### ISSUE TITLE
cdn.coursefreedl.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94443]
**Issue URL (Annoyance)**: https://cdn.coursefreedl.com/the-complete-regular-expressionsregex-course-for-beginners-zip/?file=dGhlLWNvbXBsZXRlLXJlZ3VsYXItZXhwcmVzc2lvbnNyZWdleC1jb3Vyc2UtZm9yLWJlZ2lubmVycy56aXA%3D&key=MTg2MjQ4MDUyMA%3D%3D

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132966945-e94b5e2c-c627-4ead-b4ee-aaa3c3df40c5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by chirag127** [comment]
@AdamWr 
click on generate link, I can still reproduce the timer

**Comment by AdamWr** [comment]
Timer is adjusted/boosted on my end.
