### ISSUE TITLE
www.ftuforums.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94441]
**Issue URL (Annoyance)**:
https://www.ftuforums.com/downloading-center/?dlm-dp-dl=2028

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132966874-a8e2f7a4-dcdb-4dad-9dd8-6eab343f8cbb.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
This site has a check on the server.
