### ISSUE TITLE
www.sony.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94482]
**Issue URL (Annoyance)**:
https://www.sony.com/electronics/support/articles/00119211

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132991240-db3ebfe9-2079-4a5a-a046-ca88057baf5d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
We don't block first party widgets.
