### ISSUE TITLE
?xtor

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#94496]
Отслеживающий параметр при интеграции на сторонних сайтах, как например здесь: https://news.zerkalo.io/cellar/2841.html

https://www.bbc.com/russian/features-58493519?xtor=AL-73-%5Bpartner%5D-%5Btutby.news%5D-%5Bheadline%5D-%5Brussian%5D-%5Bbizdev%5D-%5Bisapi%5D

**Comment by zubrRB** [comment]
И на других сайтах замечен: https://github.com/AdguardTeam/AdguardFilters/issues?q=is%3Aissue+%3Fxtor+is%3Aclosed

**Comment by Alex-302** [comment]
Примеры неправильные. Нашёл другие.

**Comment by zubrRB** [comment]
По первой ссылке в блоке справа заголовки статей на BBC с таким параметром.
