### ISSUE TITLE
cdn.coursefreedl.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94553]
**Issue URL (Annoyance)**: https://cdn.coursefreedl.com/digital-advertising-marketing-101-take-the-complete-guide-zip/?file=ZGlnaXRhbC1hZHZlcnRpc2luZy1tYXJrZXRpbmctMTAxLXRha2UtdGhlLWNvbXBsZXRlLWd1aWRlLnppcA%3D%3D&key=NzA0OTU3NTgw

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133012672-3cf6ce2e-b4bd-487d-a2a8-ce6a7e21e6b7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
This was already fixed.
