### ISSUE TITLE
jo.vlip.lv

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94563]
**Issue URL (Ads/Annoyance)**:
https://jo.vlip.lv/q/%23BoloGuruji

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133020160-9ec78145-aad2-464e-bbd1-64d361c9d75a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The site isn't available.
