### ISSUE TITLE
dropgalaxy.in [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#94571]
https://dropgalaxy.in/dzpwwot0skin

After visiting this page, click on Free Download button and the page redirects to
https://techyneed.com/wp/how-to-ace-your-appraisals-in-2021/

The contents of the page are correct (download link). On this page, clicking on "Create Download Link" before the countdown timer reaches zero shows an adblock detected message

Screenshot: https://prnt.sc/1s0vfky

Checked with AG extension for Chrome.

**Comment by zloyden** [comment]
Not reproduced on my end. @AdamWr please take a look.

**Comment by AdamWr** [comment]
I have fixed anti-adblock on dropgalaxy yesterday and I can't reproduce it.
Skipping counter is disabled now, because it causes ad block detection (even if ad blocker is not enabled).

By the way, this websites updates anti-adblock script often, so it may stop working soon again.
