### ISSUE TITLE
www.english-hindi.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94651]
**Issue URL (Ads/Annoyance)**:https://www.english-hindi.net/english-to-hindi-meaning-absolutely-not

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133148010-0ee8fbe3-dd72-4405-a227-8a4ccf45429c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
28600 visitors/month
