### ISSUE TITLE
www.learntodance.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94673]
**Issue URL (Ads/Annoyance)**:
https://www.learntodance.com/how-to-dance-in-a-club-men-women/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133171507-4ea545f5-71d2-46d9-aebc-e2331335af60.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
11700 visitors/month
