### ISSUE TITLE
pCloud e-mail tracker

### ISSUE THREAD

**Issue by furt555nv** [AdguardTeam/AdguardFilters#94677]
I guess they are checking if the user has opened the email.

`||e.pcloud.com/trackopen`

<details>
 <summary>Screenshot</summary>
 
![8yıl_censored](https://user-images.githubusercontent.com/89068379/133176255-dd3a36fa-560f-4542-a698-f338d7249363.jpg)

</details>

**Comment by Alex-302** [comment]
Hi. Cannot reproduce. Do you see this request in any message? Could you please export to HAR this request only(not blocked) and send to filters@adguard.com?

**Comment by furt555nv** [comment]
@Alex-302 

> Do you see this request in any message? 
Yes

You should receive a mail from pCloud to reproduce it. HAR file sent.

**Comment by Alex-302** [comment]
@furt555nv Thanks. Nothing to see - everything is encrypted. Is everyting works as it should with your rule(marked as read, etc.)?

**Comment by furt555nv** [comment]
@Alex-302 



> Nothing to see - everything is encrypted.

OK, got it. If you're not a tracker ,you don't need to block it.


> Is everyting works as it should with your rule

Yes it works fine. It doesn't cause a break and issues for now.

Thank you. Closing this.

**Comment by Alex-302** [comment]
> OK, got it. If you're not a tracker ,you don't need to block it.

Maybe tracker - I don't what is encrypted:)
Added your rule.
