### ISSUE TITLE
www.terencelewis.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94681]
**Issue URL (Annoyance)**:

https://www.terencelewis.com/dance-online.php
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133179350-10112689-0244-43b0-a00f-b331e9cb0384.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>https://www.terencelewis.com/dance-online.php

**Comment by Sergey-Lyapin** [comment]
7890 visitors/month
