### ISSUE TITLE
ad.nwi.jp and ad.mtrf.net is used as a click-through,but it is blocked.

### ISSUE THREAD

**Issue by stm-x** [AdguardTeam/AdguardFilters#94704]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: ad.nwi.jp and ad.mtrf.net is used as a click-through,but it is blocked.
* **Current behaviour**: No problem with AdGuard, but ublock causes strict-blocking.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![無題](https://user-images.githubusercontent.com/86018494/133216161-6442850e-a32d-4330-aa4b-1883e270ffc5.png)
![無題1](https://user-images.githubusercontent.com/86018494/133216164-bb4881ab-804e-462d-9bc8-b262363fa6a4.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

Prevent strict-blocking.  (Add $third-party, etc.)
Also, in my opinion, blocking ad.nwi.jp is excessive.

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
Enable AdGuard Japanese with ublock origin.
Go to `https://www.nwi.jp/518.html`.
Click on the link that says Wordpress. ( `https://ad.nwi.jp/adUrl.php?ad_id=524`)

***System configuration***

**Filters:**
AdGuard Japanese

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by stm-x** [comment]
Will this help?
`@@||ad.nwi.jp^$domain=~third-party`

**Comment by Alex-302** [comment]
I think this is uBO's issue - strict blocking for the rules without modifier. I don't like that. This behawior may be disabled.

**Comment by Yuki2718** [comment]
If it's merely a strict-blocking issue, it would have been easier. The problem is both contents images and ads are delivered through the domain. The safest way would be replacing the rule with cosmetic. Or make it third-party and ignore low-traffic sites (`www.card-rich.com​, www.fx-good.com​`)

**Comment by Alex-302** [comment]
What do you mean?
I see it in your commit, but no site in commit name.

**Comment by Yuki2718** [comment]
I fixed `ad.mtrf.net` from this comment: 
> Description: ad.nwi.jp and ad.mtrf.net is used as a click-through,but it is blocked.

Apparently OP forgot to submit examples of this, so I searched by myself. I did nothing against `ad.nwi.jp` so far.

**Comment by Yuki2718** [comment]
@Alex-302 I suggest just to add `$third-party` to `||ad.nwi.jp^` in JPF and exclude from DNS. All the sites using this adserver are low-traffic, not worth individual fixes.

**Comment by Alex-302** [comment]
Ok
