### ISSUE TITLE
ds3211.co.kr - incorrect blocking

### ISSUE THREAD

**Issue by phu54321** [AdguardTeam/AdguardFilters#94714]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Website is blocked. http://www.ds3211.co.kr/

* **Expected behaviour**: 

This domain is from a delivery company. It's used for tracking shippments, so it shouldnt be blocked.

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      |  Android
Operating system version (Android/iOS) |  11
Browser:                               | Chrome
AdGuard version:                       | dns.adguard.com
Filters enabled:                       | no
AdGuard DNS:                           | Default

**Comment by piquark6046** [comment]
I am sorry. But I cannot access the website even if AdGuard is disabled.
![sre](https://user-images.githubusercontent.com/37463155/133258844-48530f3b-f242-4f01-8c53-791be4f1f78b.png)

**Comment by Alex-302** [comment]
Same.
