### ISSUE TITLE
mini-projects.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94713]
**Issue URL (Annoyance)**: https://mini-projects.in/mba-project-topics-ideas

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133240086-ce117192-ffab-4a05-9846-6520732b65ab.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
