### ISSUE TITLE
yesmovies.ag

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94725]
**Issue URL (Annoyance)**: https://yesmovies.ag/movie/fever-16995/1-1/watching.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133266273-c2eab473-6d00-441d-bd54-eb14d3d079dc.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The site isn't available.
