### ISSUE TITLE
freecourses.monster

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94763]
**Issue URL (Anti Adblock Script/Annoyance):** https://freecourses.monster/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133372464-e88a0754-4f9c-40a5-b09c-062fb6d17089.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
I can't reproduce antiadblock,  @chirag127 is it still relevant?

**Comment by chirag127** [comment]
Not relevant, website redirected to other site.
