### ISSUE TITLE
www.learncomputerscienceonline.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94761]
**Issue URL (Annoyance)**: https://www.learncomputerscienceonline.com/introduction-to-computer-system/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133368485-1095a2a3-4f0e-4ed4-bdba-16da864d42ed.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
