### ISSUE TITLE
turbobit.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94776]
**Issue URL (Annoyance)**: https://turbobit.net/download/free/aw17k1obclus

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133406917-923f6b09-b76b-4388-93f6-5a27a4154763.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The file wasn't found, but as I recall, they have a server side check.
