### ISSUE TITLE
www.coupondunia.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94797]
**Issue URL (antiadblock/Annoyance+ tracking parameter.)**:
https://www.coupondunia.in/flipkart?itm_source=home_top

> sign in and click on the get deal.
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133447563-750384b2-9dca-4fc1-9e39-6c3d308e54e9.png)
![image](https://user-images.githubusercontent.com/76880977/133447568-f350b44e-00c6-4b60-9b29-8d4e3f583fa0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
It can't be checked without an account. If you have it, please send to filters@adguard.com.
