### ISSUE TITLE
mail.aol.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94798]
**Issue URL (Ads/Annoyance)**:
https://mail.aol.com/webmail-std/en-us/suite

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133448017-910b6f1d-4d7f-4fc9-94f5-c374eb2eba4b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
It can't be checked without an account. If you have it, please send to filters@adguard.com.
