### ISSUE TITLE
vivud.com [Leftover Elements] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#9481]
**Site**: http://vivud.com/video/129681/?sid=12111

**Issue**: Please remove the highlighted elements as seen in the screenshot.

**Screenshot**: http://prntscr.com/hx51bc

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Info button is useful button (shows description below the video).
