### ISSUE TITLE
www.scientificamerican.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94833]
**Issue URL (Annoyance)**:
https://www.scientificamerican.com/article/how-the-pandemic-is-changing-mental-health/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133494560-a62d94b2-45b4-49f2-bfa3-b3dfed6ef87d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not an annoyance.
