### ISSUE TITLE
LeMonde.fr cookie popup

### ISSUE THREAD

**Issue by moviuro** [AdguardTeam/AdguardFilters#94830]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://www.lemonde.fr/ shows a cookie banner
* **Current behaviour**: https://www.lemonde.fr/ shows a cookie banner

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![broken](https://user-images.githubusercontent.com/6882978/133493710-68150318-a2d9-47c0-b1ca-1a257cb9e536.png)
</details><br/>

* **Expected behaviour**: no cookie popup

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![fixed](https://user-images.githubusercontent.com/6882978/133493836-e0f24c04-f533-4202-8f6e-a433daafb2e1.png)

</details><br/>

***Steps to reproduce the problem***: https://www.lemonde.fr/

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ArchLinux
Operating system version (Android/iOS) | latest
Browser:                               | Firefox 92.0
AdGuard version:                       | N/A
Filters enabled:                       | See screenshot
AdGuard mode (Android only):           | NO
Filtering quality (Android only):      | NA
HTTPS filtering (Android only):        | NA
Simplified filters (iOS only)          | NA
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | NA
Helpdesk ID (if exists):               | NA

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

<details><summary>settings:</summary>

![settings](https://user-images.githubusercontent.com/6882978/133494236-65c897cd-913c-4236-845d-f8908c4cbdba.png)

</details>

**Comment by adranger** [comment]
Blocking this subdomain removes the cookie overlay. Check if it breaks anything:

`||cmp.lemonde.fr`

**Comment by Alex-302** [comment]
uBO does not support JS rules.

**Comment by moviuro** [comment]
@Alex-302 https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection maybe? (not sure, I'm not familiar with it)

**Comment by Alex-302** [comment]
@moviuro To display content, consent/cookies must be accepted. If "not accepted"/"not declined" - site will be broken. We just simulate click in this case - the easiest way. Solution with scriptlet may take a long time without result, but this even not an ads. You may ask for that in uBlock repository or install AdGuard:)
