### ISSUE TITLE
www.youtube.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94863]
**Issue URL (Annoyance)**:
https://www.youtube.com/results?search_query=wikipedia&sp=CAMSBBABWAM%253D

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133551208-4e99579f-54a9-4743-bacb-37647c0f01e1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The popup not reproduced on my end.
