### ISSUE TITLE
www.attilasec.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94925]
**Issue URL (Ads/Annoyance)**:

https://www.attilasec.com/blog/captive-portal-risk-remote-work-captive-vulnerability-zone
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133649432-a599a3c7-b5fa-47bc-b507-d12c515c705c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
7 100
