### ISSUE TITLE
mytechtalky.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94993]
**Issue URL (Incorrect Blocking)**:
https://mytechtalky.com/youtube-playlist-length/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133739665-f5ea7a8d-367b-4058-9895-f84ac7233138.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
