### ISSUE TITLE
tumblr.com

### ISSUE THREAD

**Issue by invalidCards** [AdguardTeam/AdguardFilters#95066]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: The AdGuard filter causes a React crash on Tumblr due to a vendor script erroring in a race condition.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/842080/133855299-63dcde90-346b-45a9-a7fb-f3e4e9209833.png)
![image](https://user-images.githubusercontent.com/842080/133855349-764063d8-ab75-4946-a709-87d411b923c8.png)

</details><br/>

* **Expected behaviour**: 

[//]: Tumblr should load succesfully.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/842080/133855431-02140afe-491b-4d6a-8bca-80938e8ebda1.png)
</details><br/>

***Steps to reproduce the problem***:

[//]: It seems to be a race issue, since loading the page usually works properly after a couple of reloads of the page, but the most reliable method I've found so far is to enable AdGuard Base and open a new tab with Tumblr. It usually results in a white screen due to the above posted vendor script error. It seems to be caused by https://github.com/AdguardTeam/AdguardFilters/blob/76fa77bc2131fb4b216fca693db470635d2f96b4/EnglishFilter/sections/css_extended.txt#L293 - the solution here would be to only *hide* the element rather than to completely remove it.

***System configuration***

**Filters:**

[//]: uBlock Filters, uBlock Filters - Badware risks, uBlock Filters - Privacy, uBlock Filters - Resource abuse, uBlock Filters - Unbreak, AdGuard Base, AdGuard Mobile Ads, EasyList, AdGuard Tracking Protection, AdGuard URL Tracking Protection, EasyPrivacy, Online Malicious URL Blocklist, Spam404, AdGuard Annoyances, AdGuard Social Media, Anti-Facebook, EasyList Cookie, uBlock Filters - Annoyances, Peter Lowe's Ad and tracking filter list

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | N/A
Browser:                               | Mozilla Firefox
AdGuard version:                       | 2.1.96.17 (Base filter)
Filters enabled:                       | uBlock Filters, uBlock Filters - Badware risks, uBlock Filters - Privacy, uBlock Filters - Resource abuse, uBlock Filters - Unbreak, AdGuard Base, AdGuard Mobile Ads, EasyList, AdGuard Tracking Protection, AdGuard URL Tracking Protection, EasyPrivacy, Online Malicious URL Blocklist, Spam404, AdGuard Annoyances, AdGuard Social Media, Anti-Facebook, EasyList Cookie, uBlock Filters - Annoyances, Peter Lowe's Ad and tracking filter list
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by gork7777** [comment]
You have enabled too many filters. You can find out which filter is the problem by disabling them one by one

**Comment by invalidCards** [comment]
Which I did, and Adguard Base was the culprit.

**Comment by AprilSylph** [comment]
Able to reproduce with
- macOS 11.5.2
- Firefox 93.0b5 (64-bit)
- uBlock Origin 1.37.2
- only AdGuard Base enabled

**Comment by DandelionSprout** [comment]
For that matter, the entry cited by the OP only covers 6 GUI languages, meaning that AdGuard Base is leaving out at least some of the remaining 10 languages: `https://www.technobezz.com/how-to-change-the-language-on-tumblr/`

**Comment by Alex-302** [comment]
I can't reproduce with uBO
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/135255918-13deb237-e85a-43ce-ae89-4cdb62d37fdd.png)

</details>

@invalidCards Do you still get that error?

**Comment by AprilSylph** [comment]
By nature of being a race condition, it only happens sometimes. Took me three refreshes to reproduce this time.

**Comment by Alex-302** [comment]
How frequently? Checked 20 times in FF dev with uBO + Base filter - the site works fine.
Maybe something is wrong with your browser/profile or with ad blocker.

**Comment by AprilSylph** [comment]
I've not been using AdGuard Base because of this issue, so I can only say how many times it takes me to reproduce the issue when I try. Due to being a race condition, it may be impossible to reproduce on your machine.

This time, it took two refreshes on my M1 Mac Mini, and four refreshes on my 10th gen Intel Windows laptop. They are completely different profiles and are not synchronised in any way.

**Comment by Alex-302** [comment]
So this is caused by  this rule?
`tumblr.com#$?#div[style^="top:69px"]:has(h1:contains(/^Sponsor|Patrocinado|Gesponsert|Gesponsord|Спонсируется|広告/)) { remove: true; } `
If so, please check these rules:
`tumblr.com#@$?#div[style^="top:69px"]:has(h1:contains(/^Sponsor|Patrocinado|Gesponsert|Gesponsord|Спонсируется|広告/)) { remove: true; } `(exclusion) 
`tumblr.com#?#div[style^="top:69px"]:has(h1:contains(/^Sponsor|Patrocinado|Gesponsert|Gesponsord|Спонсируется|広告/))`(another variant)

**Comment by AprilSylph** [comment]
The second one is what @invalidCards is suggesting. Removing any elements from a React site has the potential to break it.

**Comment by invalidCards** [comment]
Correct, though after playing around with it for a little bit in my custom filters, it doesn't actually manage to block anything... though I've found the following filter to be quite effective:
`tumblr.com#?#div[tabindex="-1"]:not([data-id]):has(a[href$="/relevantads"])`

**Comment by Alex-302** [comment]
Ok, replaced. Please check if leftovers are not blinking(this is a reason, why used removing of element)
