### ISSUE TITLE
False positive adult website: f002.backblazeb2.com

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdguardFilters#95236]
It seems to be a recurring issue #69945

Can you please allow list the domain and subdomains of `backblazeb2.com` once and for all?

It's a problem with other block lists too, not just AdGuard.

**Comment by Yuki2718** [comment]
I do not see any problem on the site. Please do not skip template.

**Comment by timkgh** [comment]
This is what I see on AdGuard Home DNS with the option "Use AdGuard parental control web service" enabled, which pulls its settings from `family-block.dns.adguard.com`

![image](https://user-images.githubusercontent.com/23507658/134076641-301522ba-b70b-4b77-925b-87ea27ebb79c.png)

Also `dig @94.140.14.15 f002.backblazeb2.com` returns `94.140.14.35` which is an Adguard block page
"We blocked this page because of parental filter restrictions."

**Comment by Yuki2718** [comment]
Looks to be FP of parental control.

**Comment by AlKulagin23** [comment]
The website has been removed from the list of adult websites.

**Comment by hugoamvieira** [comment]
Reopening as it's still flagging. Not as Adult Website but as a Safe Browsing Threat

![image](https://user-images.githubusercontent.com/10965479/154164595-5397a6b0-2998-463c-8de9-b21daf673a74.png)
