### ISSUE TITLE
nikhilbharatshikshaparisad.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#95250]
**Issue URL (Annoyance)**:https://nikhilbharatshikshaparisad.in/nbc-moocs-program

<details><summary>Screenshots:</summary>

https://nikhilbharatshikshaparisad.in/nbc-moocs-program
![image](https://user-images.githubusercontent.com/76880977/133940546-67ab8e73-6b6b-45b2-b999-8a37adbe8946.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Too few visitors, fixed cookie only.
