### ISSUE TITLE
http://www.erightsoft.com/Superdc.html

### ISSUE THREAD

**Issue by Snake87r** [AdguardTeam/AdguardFilters#9535]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
ATTENTION: Malware, bitcoin miner, substitute your default page ed maybe many other threat

* **Current behaviour**: 
If you download this software (the free version) and install it, you install the software plus a bitcoin miner and many malware, and they change your default browser page, and every new webpage you open they show you banner

* **Expected behaviour**: 

Add this page to the malware domains because they distribuite the software with malware and other things inside

***System configuration***

**Filters:**

[//]: #  English, Spyware, social media, annoyance, russian, german, japanese, french, easyprivacy, fanboys social blocking list, fanboy's annoyances, easylist hebrew, easylist italy, adblock warning removal list, anti ad-blocker by reek, malware domains, spam 404

Information
--

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10
Browser:                               |  Chrome
AdGuard version:                       |  6.2
Filters enabled:                       | ?
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    |  NO

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I see no download button.
