### ISSUE TITLE
LINE

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#95431]
torimochi.line-apps.com

It used to be blocked, but now it's gone.
Is it just my environment?

![Screenshot_20210922-110715866](https://user-images.githubusercontent.com/87330832/134272436-157cc06f-bf42-41a0-9cae-a6ca94cee8be.jpg)

**Comment by Alex-302** [comment]
@SASUKE0721 Hi. What the purpose of this domain? I can't check, because they blocked all my accounts.

**Comment by SASUKE0721** [comment]
access analysis

**Comment by Alex-302** [comment]
Ok, blocked.
