### ISSUE TITLE
www.speakforlife.com.au

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#95520]
**Issue URL (Ads/Annoyance)**:https://www.speakforlife.com.au/howtoprojectyourvoice/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/134534342-280ca015-09e2-4b50-b620-7dcb762de227.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
3890 visitors/month
