### ISSUE TITLE
Multiple Unblocked Ads audiobookbay.nl

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardFilters#9582]
The domain is Dutch but the website content is in English.

audiobookbay.nl 

Multiple unblocked ads on the main page on the right-hand side and at the bottom all as images.

audiobookbay.nl/audio-books/the-big-showdown-corrected-mickey-spillane-max-allan-collins

Multiple unblocked ads under any entry, down the right-hand side as an image, and the middle of the page as an image, and at the bottom as an image and as text and links.

![capture](https://user-images.githubusercontent.com/16563034/34732084-1a362194-f55c-11e7-9cf1-00cdbb088564.JPG)

**Comment by BlazDT** [comment]
Please list your filters, thank you.

**Comment by zero77** [comment]
I am using Adguard Base Filters, Adguard Spyware Filters​ and Adguard’s Annoyance List in firefox.

**Comment by BlazDT** [comment]
If you still see ads (after update in 2-3 hours), please post direct link to site, thank you.

For next submissions please use the report tool:

https://reports.adguard.com/en/new_issue.html

**Comment by zero77** [comment]
Thanks

**Comment by Smorvel** [comment]
http://audiobookbay.nl/audio-books/harry-potter-audiobooks-1-7/
![image](https://user-images.githubusercontent.com/19754243/67357923-1d131980-f55f-11e9-9643-a93735317b60.png)
А также ссылка Download Files Now тоже ведет на тот сайт что на баннере...
![image](https://user-images.githubusercontent.com/19754243/67357998-4e8be500-f55f-11e9-85bd-f30f87b59f45.png)

**Comment by BlazDT** [comment]
Fixed, update available in about 3 hours.
