### ISSUE TITLE
launchpadlibrarian.net false positive adult website

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdguardFilters#95870]
`launchpadlibrarian.net` is a repository for Canonical/Ubuntu Launchpad but it's mistakenly identified as an adult web site

```
dig @94.140.14.15 launchpadlibrarian.net

;; ANSWER SECTION:
launchpadlibrarian.net.	3600	IN	A	94.140.14.35
```

**Comment by timkgh** [comment]
See #55988 -- can you just fix it so it doesn't break again?

**Comment by NaylyaM** [comment]
Unblocked everywhere.
