### ISSUE TITLE
Пропущенная реклама на сайте www.mk.ru, вид рекламы Яндекс. Директ

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#9587]
Сайт. http://www.mk.ru/social/2018/01/08/kak-mayor-fsb-arshavina-pampers-v-samolete-menyala-durno-pakhlo.html
Стоит Adguard 2.10.176, фильтры по-умолчанию, фильтрация качественная, HTTP, HTTPS, Android 4.4.4, Nexus 5.
Прикрепляю логи web запросов, еще какой-то из низкоуровневых настройках, забыл название и лог выгрузки инфы из настроек Adguard. http://my-files.ru/qr8tf7 Время 21:51

**Comment by ministr91** [comment]
[spoiler]![screenshot_2018-01-09-21-51-22](https://user-images.githubusercontent.com/22351242/34739465-080fcece-f585-11e7-9d79-42d5d45a570c.png)[/spoiler]

**Comment by Alex-302** [comment]
Добавил
```
||mk.ru/*/*/*/*/*/$replace=/Ya\[([0-9]{10\,15})\]\([\s\S]*\)\$/,script,domain=mk.ru,important
```
