### ISSUE TITLE
gadgetsnow.com

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#95962]
https://www.gadgetsnow.com/slideshows/apple-samsung-and-oneplus-phones-that-will-be-available-at-big-discounts-in-diwali-sale-on-amazon-and-flipkart/photolist/86574190.cms?picid=86574208

On this page, when we click on the 'GET IT' button for any of the phones, then it does not redirect to Amazon website when AG extension for Chrome is enabled. Please check.

https://prnt.sc/1twpi09

**Comment by Alex-302** [comment]
reported to Easylist.
