### ISSUE TITLE
dev.to

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#96011]
**Issue URL (Annoyance)**:
 https://dev.to/adityamitra/telegram-the-one-messenger-app-to-rule-them-all-bl3

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/135121160-ab0dc1e5-af78-469f-a3b6-457adc637111.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Apious** [comment]
blocked big image?

**Comment by Sergey-Lyapin** [comment]
It's just a decorative image.
