### ISSUE TITLE
ok.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#96056]
&nbsp; &nbsp; **Использовал сайт БЕЗ входа в учётную запись.**
<br>

 **1**. Остаток от рекламы на главной.

<details><summary>Screenshot:</summary>

![2021 09 29-1](https://user-images.githubusercontent.com/17948007/135281551-878d2747-2c05-4a0e-9622-7a0df58c9018.png)
</details>

`ok.ru###hook_Block_AnonymMainRightColumnAd`

[https://ok.ru/](https://href.li/?https://ok.ru/)

___________________________________________________

 **2**. Рекламный баннер наверху, в разделе 'Видео'.

<details><summary>Screenshot:</summary>

![2021 09 29-2](https://user-images.githubusercontent.com/17948007/135283979-b84ea130-b830-475b-b527-941a71c9480c.png)
</details>

`ok.ru###hook_Block_VideoBannerBlock`

[https://ok.ru/video/](https://href.li/?https://ok.ru/video/)

___________________________________________________

 **3**. Как и во 'ВКонтакте' при чтении комментариев не залогиненым (исправлено), так и здесь при просмотре видео не залогиненым каждые 1,5-2 минуты темнеет экран и появляется просьба войти в аккаунт или зарегистрироваться.
 Это происходит из-за скрипта [https://ok.ru/res/js/app/AuthLoginPopup_909d4.js](https://href.li/?https://ok.ru/res/js/app/AuthLoginPopup_909d4.js).

<details><summary>Screenshot:</summary>

![2021 09 29-3](https://user-images.githubusercontent.com/17948007/135286055-e1755667-e751-4456-b9eb-1fd7ee80ec4a.png)
</details>

`||ok.ru/res/js/app/AuthLoginPopup`

[https://ok.ru/video/44089805365](https://href.li/?https://ok.ru/video/44089805365)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.13 | Базовый AdGuard; &nbsp; Русский | Стандарт
 FireFox v78.13 ESR | Счётчиков и аналитики; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Раздражителей; &nbsp; Виджетов социальных сетей

**Comment by zloyden** [comment]
В последнем пункте добавил другое правило, поскольку оригинальное ломает авторизацию на главной странице.
Также установи AdGuard Extra.
