### ISSUE TITLE
Korea COVID-19 HOME Page Blocked by Adguard

### ISSUE THREAD

**Issue by Apious** [AdguardTeam/AdguardFilters#96096]
***Description***: https://ncvr2.kdca.go.kr/ not open by mobile. disable to open anywhere
* **Current behaviour**: off to used

<details><summary>Screenshot:
웹페이지를 사용할 수 없음

다음 이유로 https://ncvr2.kdca.go.kr/ 의 웹페이지를 로드할 수 없습니다

net::ERR_NAME_NOT_RESOLVED

</details><br/>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Apious** [comment]
@@||ncvr2.kdca.go.kr^

hi admin please add this Korea COVID-19 HOME PAGE

**Comment by AdamWr** [comment]
It seems that it's not a filters issue, reported here - https://github.com/AdguardTeam/CoreLibs/issues/1524
