### ISSUE TITLE
www.google.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#96252]
**Issue URL (Annoyance)**: https://www.google.com/search?q=form+factor+formula#cobssid=s

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/135711216-1488d699-90f6-498b-b8a4-0c937ef6ef5d.png)
![image](https://user-images.githubusercontent.com/76880977/135711214-4c400f87-3000-4615-8730-726c66b0dd2c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by chirag127** [comment]
Can you please tell me the user filter by the screen shot?

**Comment by BlazDT** [comment]
`google.com##promo-throttler + div[jsname]`
