### ISSUE TITLE
testsafebrowsing.appspot.com (N: AdGuard browsing security service) (T: Incorrect blocking)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#96398]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

`testsafebrowsing.appspot.com` is apparently blocked by AdGuard's browsing security module (which is used in e.g. AdGuard Home and AdGuard for Windows), even though multiple online sources at least claim that it's actually Google's test domain for Google Safe Browsing. Is there any reason for this blocking, or should that entry be removed?

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/135772556-a2141daf-9257-414b-a656-51d28aef127c.png)

(Yes, the DNS server's affected user tried to call me out with subdomains, seemingly unaware of my GitHub repo's issue tracker.)
</details><br/>

* **Expected behaviour**: 

Most likely that it becomes unblocked.

***Steps to reproduce the problem***:

The screenshot should indicate it well enough on paper.

***System configuration***

**Filters:**

N/A

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Unclear (Seems to be Android)
Operating system version (Android/iOS) | Unknown
Browser:                               | Unknown
AdGuard version:                       | Unknown
Filters enabled:                       | Narrowed down to AdGuard Browsing Security, as seen in the screenshot
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by NaylyaM** [comment]
Unblocked.
