### ISSUE TITLE
info.singtel.com, www.straitstimes.com - blank pages on iOS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#964]
I see blocked request to dev.visualwebsiteoptimizer.com in both cases.

It seems that Safari cannot properly block it so we should add this domain to exception.

**Comment by ameshkov** [comment]
I've added that domain to the filters. Do not yet close this issue, we should also file a bug report to webkit guys

**Comment by Alex-302** [comment]
Can we close this issue?

**Comment by Alex-302** [comment]
bump
