### ISSUE TITLE
finanzen.net mangled by adguard-annoyance

### ISSUE THREAD

**Issue by terr72** [AdguardTeam/AdguardFilters#9643]
***Description***:
* **Current behaviour**: 

adguard-annoyance mangles finanzen.net

Just load https://www.finanzen.net/aktien/wacker_chemie-Aktie.
No charts.
Disabling the annoyances list brings the chart back.

***System configuration***

**Filters:**

Easylist, EasyList Germany, AdGuard Annoyance List

Information                            | Value
---                                    | ---
Operating system:                      | Both Linux and Windows
Browser:                               | Firefox 57.0.4

**Comment by BlazDT** [comment]
Will be fixed in https://github.com/AdguardTeam/AdguardFilters/issues/9619
