### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by darek991** [AdguardTeam/AdguardFilters#96442]
It appears as though adguard annoyances breaks https://multiplayer.it/

Page gets randomly cut in half, but since is doesn't always happen, it's hard to replicate. I suppose it's due the cookie banner. Make sure browser cache is empty and load the site. Swapping out to another tab right after having opened it seems to help. Tested on both Firefox and Edge, both updated as well as adguard filters. I'm running adguard extension along with adguard base filter, social media, tracking prevention and annoyances, no stealth mode on.

**Comment by adranger** [comment]
You can use [Temporary Containers](https://addons.mozilla.org/addon/temporary-containers/) to easily test issues like that on Firefox. Every new temporary tab works like a separate private window with clean cookies and cache settings.

Just make sure to open its options from the Add-ons Manager to disable its `Automatic Mode`, or else it will keep creating new containers for all sites you access.

**Comment by Alex-302** [comment]
@darek991 Hi. Sorry for tha late reply. Does it shill happen? It seems the site works fine on my end.
