### ISSUE TITLE
adguard app无法过滤华为视频广告

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#96454]
@biange200 commented on [Mon Oct 04 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3990)

![Screenshot_20211004_214835.jpg](https://user-images.githubusercontent.com/37582806/135874955-d58f46f4-6ae2-468b-bfc0-774e853171a5.jpg)

在用户过滤器里添加了
||cs02-pps-drcn.dbankcdn.com^
||sys.zhangyue.com^
可以过滤广告了 ![Screenshot_20211004_225309.jpg](https://user-images.githubusercontent.com/37582806/135875213-c2528765-74b3-4507-8d23-e3f82ca1e179.jpg)

**Comment by Sergey-Lyapin** [comment]
@biange200 
This is it, right?
https://play.google.com/store/apps/details?id=com.huawei.himovie.overseas&hl=en&gl=US

**Comment by Sergey-Lyapin** [comment]
@biange200
Could you test these rules in user rules?
```
||cs02-pps-drcn.dbankcdn.com^$app=com.huawei.himovie
||sys.zhangyue.com^$app=com.huawei.himovie
```

**Comment by biange200** [comment]
> @biange200
> Could you test these rules in user rules?
> ```
> ||cs02-pps-drcn.dbankcdn.com^$app=com.huawei.himovie
> ||sys.zhangyue.com^$app=com.huawei.himovie
> ```

不过好像添加这些又失效了
好在华为内置了去广告功能![Screenshot_20211013_065004.jpg](https://user-images.githubusercontent.com/37582806/137039339-bf734642-c4ac-458a-9120-338fb0161bb2.jpg)
开启这个就没了
