### ISSUE TITLE
freenet-funk.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#96471]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Dropdownmenu not working
`https://www.freenet-funk.de`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="792" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/135879386-a0b33523-ba70-4395-8754-30869e1fb4be.PNG">

</details><br/>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

<img width="763" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/135902220-406e55e2-1e4a-412a-a8a3-f53cb5862263.PNG">
</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.6.13
Filters enabled:                       | Default + Adguard tracking protection + adguard annoyances + adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Please test these rules and try to accept cookies:

```
@@||cdn.privacy-mgmt.com/wrapperMessagingWithoutDetection.js$domain=freenet-funk.de
@@||googletagmanager.com/gtm.js$domain=freenet-funk.de
```

**Comment by JobcenterTycoon** [comment]
It works

**Comment by BlazDT** [comment]
Thank you, added.
