### ISSUE TITLE
www.psycom.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#96478]
**Issue URL (Ads)** :https://www.psycom.net/quiz-results/?qid=4_3

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/135908852-3b252b78-d2c1-4c69-b58e-c5a5611d8c1e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment]
Fixed by EasyList

**Comment by chirag127** [comment]
> Fixed by EasyList

When ? Where?

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/eb17cc0df3698c9062b202acb42a7c7d8a6cf4c3
