### ISSUE TITLE
Block mining permanently / remember what a user has opted for

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#9653]
> При входе на сайт m.joyreactor.cc каждый раз, а порой и несколько раз за сессию, в браузере всплывет предупреждение о майнинге криптовалюты с двумя диалоговыми окнами (разрешение/блокировка и передача статистики). Данные предупреждения довольно сильно раздражают, потому хотелось бы узнать, можно ли отключить их в принципе и блокировать абсолютно все попытки майнинга по умолчанию или или запомнить выбор для конкретного сайта во избежание повторного появления на нем диалоговых окон (выставление галочки о предотвращении создания диалоговых окон в браузере эффекта не дает)?

1114526

**Comment by Alex-302** [comment]
не повтоняется, никогда там не видил майнера. Но о том, что он есть, слышал.
Он включается юзером, или есть возможность отключения?
