### ISSUE TITLE
Реклама в приложении Kinoplay

### ISSUE THREAD

**Issue by sergunchik25** [AdguardTeam/AdguardFilters#96635]
Реклама в приложении Kinoplay,под видео и при проигрывании видео, версия программы для windows -  [https://get.kinoplay.app/](url)
Реклама(скрин) -https://i115.fastpic.org/big/2021/1007/a1/f0eec4fff4816b4f45c274e547697ba1.jpg
Если исполняемый фаил приложения добавить в список фильтруемых приложений,то приложение перестаёт загружать контент(скрин) - https://i115.fastpic.org/big/2021/1007/43/f7b279e14cf2ad8ec37b834cb9842043.jpg

Если в пользовательский фильтр добавить правило исключение для программы то контент отображается и прекрасно блокируется реклама базовыми фильтрами
Правило - `@@||izifilm.net$app=Kinoplay.exe`

**Comment by zloyden** [comment]
Для `izifilm.net` в наших фильтрах нет блокирующих правил и после добавления приложения в список фильтруемых, проблем с воспроизведением фильмов нет.
Если повторяется до сих пор, покажи скриншот с журналом фильтрации.

**Comment by sergunchik25** [comment]
> У себя этого не наблюдаю. Проблема осталась до сих пор? Если так, то попробуй `@@||izifilm.net$cookie,app=Kinoplay.exe`. Скриншоты лучше грузить сюда на гитхаб под спойлер.

Да проблема присутствует,данное правило исключение не помогает,хотя оно отрабатывает и записей о блокировке кук в журнале уже нет.

**Comment by sergunchik25** [comment]
> Значит не в куках дело. Лучше изначально репорт оформить было б через приложение или по [ссылке](https://agrd.io/report) - больше информации для нас. Какая версия AdGuard for Windows используется? Похоже дело во включенном антитрекинге. Попробуй `@@||izifilm.net^$stealth,app=Kinoplay.exe`
> 
> Screenshot:

Приложение последняя стабильная версия,фильтры базовые от адгуард,dns отключен.Вы правы дело в антитрекинге,правило применилось и всё в порядке отображается и воспроизводиться,в антитрекинге из настроек только прописан юзер агент и заменён реферер на example.org.

**Comment by zloyden** [comment]
Отлично, я правило добавил. Через пару часов появится в обновлении фильтров.
