### ISSUE TITLE
www.nyafilmer.com   and www.dreamfilmhd.io

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardFilters#9670]
hello, pop up, big banners etc over those two whole sites, could u check and maybe have a fix _;=)

**Comment by BlazDT** [comment]
Please list all required information like filters, your AdGuard product and screenshots of those ads, thank you.

For future requests please use the reporting tool:

https://reports.adguard.com/new_issue.html

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/34845832-8c152286-f716-11e7-9734-3be0cf5af700.png)

![image](https://user-images.githubusercontent.com/19514493/34845846-97233726-f716-11e7-92a1-2ae9b22b09de.png)



![image](https://user-images.githubusercontent.com/19514493/34845867-a0fcc8d4-f716-11e7-9e6e-263131ce1a3b.png)

ladda ner nu se nu is malicious links :/

**Comment by BlazDT** [comment]
Popup not reproduced with my filters on nyafilmer.com. Other site is not opening atm for me.
Please list your filters and AdGuard product.

**Comment by cabban** [comment]
Chrome extension
Annoyance filter
English easy list
Mobile ads
Thank u


torsdag 11 januari 2018 skrev BlazDT <notifications@github.com>:

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/34897991-1b8b9758-f7f1-11e7-9cfc-478188f3e635.png)
pop up from nya filmer

**Comment by BlazDT** [comment]
Added rules for popup for nyafilmer.com.

@AdamWr 
Can you please check the other site, thank you.

**Comment by cabban** [comment]
Skickades från E-post för Windows 10

No pop up left but the blue banners under posters and up, 😊 thank u 

Från: BlazDT
Skickat: den 13 januari 2018 00:05
Till: AdguardTeam/AdguardFilters
Kopia: cabban; Author
Ämne: Re: [AdguardTeam/AdguardFilters] www.nyafilmer.com andwww.dreamfilmhd.io (#9670)

Added rules for popup for nyafilmer.com.
@AdamWr
Can you please check the other site, thank you.

**Comment by AdamWr** [comment]
Fixed.

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/35775502-db94e3f2-0989-11e8-9313-c42921b3d14b.png)

is back :( unfortunatly
cheers thank u for your work :)

**Comment by BlazDT** [comment]
Fixed.
