### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#9675]
**Site Sample** | 
------------------|
https://www.dobreprogramy.pl/Luki-Spectre-i-Meldown-moga-byc-tym-co-w-koncu-usmierci-Windowsa-7,News,85325.html

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ad box

CC @AdamWr 

<details><summary><b>Screenshot:</b></summary>

![20180111-164714-001](https://user-images.githubusercontent.com/9846948/34833180-1ac67c0a-f6ef-11e7-863d-412f43934f65.png)

</details><br/>

**Comment by AdamWr** [comment]
Dodałem już odpowiednie reguły - https://github.com/AdguardTeam/AdguardFilters/commit/766579dd4968af86092008e2592b3968f24d57fb
