### ISSUE TITLE
5-tv.ru - Annoyance

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#9683]
Реклама собственных телепередач в фоне - по бокам тела сайта видно изображение и оно кликабельно: http://www.5-tv.ru

<details><summary>Screenshot:</summary>

![5-tv ru](https://user-images.githubusercontent.com/17948007/34838120-dcb19b60-f6f4-11e7-9ff6-2d6991e3d36a.png)
</details><br/>

 Убрать картинку и заменить фон на белый: `5-tv.ru#$#body { background-color: #ffffff!important; background-image: none!important; }`
 Убрать кликабельность картинки: `5-tv.ru##a.pageBranding`
___________________________________________________
Pale Moon v26.5 (Win7) - Adguard v2.8.1 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
ок
