### ISSUE TITLE
cookielaw.org

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#96851]
I've noticed that @BlazDT has added these generic entries to [cookies_whitelist.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/cookies_whitelist.txt), even though whitelisting `cookielaw.org` connections is only necessary for some sites:

    @@||cdn.cookielaw.org/consent
    @@||cdn.cookielaw.org/vendorlist^
    @@||cdn.cookielaw.org/scripttemplates/*.*.*/
    
The same list also has other rules to unbreak specific sites, like:

    @@||cdn.cookielaw.org/consent/$script,domain=rte.ie
    @@||cdn.cookielaw.org/scripttemplates/$script,domain=rte.ie
 
Shouldn't `domain=glamour.de` be added to those generic rules?

**Comment by BlazDT** [comment]
Those generic Whitelist were added as they require a previous site specific unblock.

**Comment by BlazDT** [comment]
Removed them now.
