### ISSUE TITLE
https://www.windowscentral.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#9714]
**Site Sample** | 
------------------|
https://www.windowscentral.com

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ad box

<details><summary><b>Screenshot:</b></summary>

![20180112-084900-001](https://user-images.githubusercontent.com/9846948/34864637-73ef72e2-f775-11e7-8552-0171cb8bcee2.png)

</details><br/>

**Comment by AdamWr** [comment]
Fixed.
