### ISSUE TITLE
qa.emptyq.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97193]
**Issue URL (Ads)** :
https://qa.emptyq.net/q?id=f3cc8848-4e98-41ec-bda3-03177d67065d

<details><summary>Screenshots:</summary>

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
