### ISSUE TITLE
powerusers.microsoft.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97216]
**Issue URL (Annoyance)**:

https://powerusers.microsoft.com/t5/Building-Flows/Create-File-Flow-adding-slashes-to-my-file-name-file-path/td-p/370625
<details><summary>Screenshots:</summary>

https://powerusers.microsoft.com/t5/Building-Flows/Create-File-Flow-adding-slashes-to-my-file-name-file-path/td-p/370625
![image](https://user-images.githubusercontent.com/76880977/137350125-f9c513eb-6524-4e7c-9328-2b1a735d0745.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Hi @chirag127
I can't reproduce this popup, is it still relevant?
