### ISSUE TITLE
`Google Advertising(Shanghai)Co.,Ltd.`

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#97259]
![image](https://user-images.githubusercontent.com/75058881/137477813-ec51617a-3c42-40bd-be99-c87e9244a90f.png)

Suspicious domain: 
```
(later)
```

**Comment by c2xusnpq6** [comment]
https://web.archive.org/web/20211015111046/https://www.google.com/intl/en_us/adwords/select/TC-CHN-201402-PRC.html

**Comment by Alex-302** [comment]
Which are not blocked and where used?
