### ISSUE TITLE
computerbase.de: Please reconsider blocking our Web App Manifest (it was a bug in Chrome)

### ISSUE THREAD

**Issue by steffenweber** [AdguardTeam/AdguardFilters#97260]
I replied to the original issue #88782 one month ago but no-one seems to be paying attention anymore which is why I'm filing this new issue.

The annoying dialog that caused you to block our manifest.json file was caused by a bug in Chrome that I've reported to the Chrome developers and that has meanwhile been fixed (the fix first appeared in Chrome 93.0.4577.82, released 1 month ago). Please see:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1234856
- https://twitter.com/tomayac/status/1421116329009025036

Can you therefore please revert commit abda5baa642e847e0d1f88b0879b055b49c1d3fa?

**Comment by Alex-302** [comment]
Sorry for the late reply. Removed.
