### ISSUE TITLE
support.apple.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97277]
**Issue URL (Annoyance)**:https://support.apple.com/en-us/HT208499

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/137508118-6dde1fd3-fa9d-46ff-81cd-f9b99d4e2822.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not reproduced, but it looks like a part of the functionality of the website.
