### ISSUE TITLE
polygon.com - missing tracking and ads placeholders

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#973]
**trackers**

```
||optimize-stats.voxmedia.com^
```

**social** (placeholder visible on mobile site)

```
###chorus-social-fixed
```

**Comment by Alex-302** [comment]
added to social:
polygon.com###follow-bar-buttons
polygon.com###chorus-social-fixed
to analytics:
||optimize-stats.voxmedia.com^$third-party

**Comment by ameshkov** [comment]
One more:
```
polygon.com##.m-share-buttons
```

**Comment by Alex-302** [comment]
Added.

**Comment by ameshkov** [comment]
One more rule:
```
polygon.com###follow-bar
```
