### ISSUE TITLE
businessinsider.com.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#9735]
**Site Sample** | 
------------------|
https://businessinsider.com.pl/technologie/nowe-technologie/intel-ostrzega-przed-patchami-naprawiajacymi-bledy-procesora/clrztky

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Ad leftover

### Fix

```
businessinsider.com.pl###extraAdsBlock
```

<details><summary><b>Screenshot:</b></summary>

![20180112-164231-001](https://user-images.githubusercontent.com/9846948/34882737-cb38a432-f7b7-11e7-88c4-16d6e75c03e8.png)

</details><br/>

**Comment by AdamWr** [comment]
Wydaje mi się, że to powinno być ukryte przez tę regułę z polskiej listy:
`businessinsider.com.pl###adSS-Detal`
Mógłbyś proszę kliknąć na ten element prawym przyciskiem myszy, wybrać "Zbadaj" i zrobić zrzut ekranu, tak żeby widoczne były inne elementy? Coś jak na obrazku poniżej.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/34891022-55dff4a2-f7d4-11e7-817d-bcd81218fdee.png)

</details>

**Comment by FadeMind** [comment]
Dzisiaj po otwarciu tej strony (i uprzednim usunięciu mojej reguły z ADG) box z reklamami się już nie pojawia o.O

Widocznie ADG miał jakąś zadyszkę w filtrowaniu strony.

**Comment by AdamWr** [comment]
Ok, to zamykam.
