### ISSUE TITLE
parenting.firstcry.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97431]
**Issue URL (Ads)** :https://parenting.firstcry.com/articles/how-to-get-rid-of-rats-and-mice-from-home-12-effective-natural-remedies/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/137642930-aebc3238-7b6b-4a50-b291-d7af5afac092.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/97426
