### ISSUE TITLE
www.bbcmag.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97577]
**Issue URL (Ads)** :

https://www.bbcmag.com/economic-development/the-economic-development-benefits-of-broadband
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/137900929-76057d0f-1853-436c-95e8-389cce8b2b78.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
22200 visitors/month

```
bbcmag.com##.ad-rectanglemed
bbcmag.com##.side-share
```
