### ISSUE TITLE
new.gdtot.org

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#97725]
https://new.gdtot.org/file/5761208539
Was fixed by a dev in the past 
But couldn't find it 
Now again has popups which opens in different tab 
Of browser 
Happening with adguard extension and also desktop app

**Comment by Alex-302** [comment]
Fixed.

**Comment by Bhooty** [comment]
Thanks a lot sir

**Comment by Bhooty** [comment]
@Alex-302 

Sir can u update the filter 
They changed domain from new.gdtot.org to 
New.gdtot.top

**Comment by Alex-302** [comment]
Done

**Comment by Bhooty** [comment]
> Done

Thanks sir
