### ISSUE TITLE
dcode.fr

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#9797]
**Site**: https://www.dcode.fr/duplicates-detector

**Issue**: Please remove the highighted word as seen in the screenshot.

**Screenshot**: http://prntscr.com/i06n4q

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Please try the following rules, can't add it to filter list due to broken pc.

```
dcode.fr##.ad
dcode.fr##img[alt="Share"]
dcode.fr###right > .heading_bar[-ext-has='Share']
dcode.fr###right > .heading_bar[-ext-has='Sponsored ads']
```

**Comment by Nzzyme** [comment]
Apologies @BlazDT for not replying earlier. I am tied up with few things lately. I just checked and this is fixed. Thanks bro.
