### ISSUE TITLE
www.pooripadhai.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97991]
**Issue URL (Annoyance)**:https://www.pooripadhai.com/previous-year-question-paper/universities/aktu/b.tech/me/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138596828-7b8b3b81-bad2-4875-8da5-8afe412a2238.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
11400 visitors/month

**Comment by Sergey-Lyapin** [comment]
```
pooripadhai.com###pop_up_ad_box_id
pooripadhai.com##.footer-fixed-google-ads-class
```
