### ISSUE TITLE
vpntester.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#98072]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Ad overlay after ~ 60 seconds
`https://vpntester.org/perfect-privacy/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="674" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/138729444-c9c4e727-bfc6-4c3b-9d7b-c1e13573a62d.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.6.13
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Sergey-Lyapin** [comment]
1790 visitors/month
`vpntester.org##.pupop-wrapper`

**Comment by JobcenterTycoon** [comment]
@Sergey-Lyapin i get 35.906 visitors per month and the issue still persist. They switched the domain thats why it was low at the beginning
