### ISSUE TITLE
new twitter tracking parameters

### ISSUE THREAD

**Issue by ahmedtds** [AdguardTeam/AdguardFilters#98086]
I started to see "t=" paramater with twitter links a lot

like this: `https://twitter.com/<username>/status/11111111111111111111111?t=somerandomthings`

it's surely a tracking parameter, please add it to "URL Tracking filter"

Also please re-consider "s=" parameter too, it's a tracking parameter too in the end.

**Comment by Alex-302** [comment]
Need real link.

**Comment by ahmedtds** [comment]
> 
> 
> Need real link.

https://twitter.com/lunasorcery/status/1449400981188382722?t=9oAxgaekyCU8sMB3lRo5yw&s=19

**Comment by Alex-302** [comment]
Removing these parameters may break Twitter. `S` - not tracking(at least has low entropy)

**Comment by ahmedtds** [comment]
no, nothing gets broken, they both are just only tracking parameters. they don't have any actual effect on anything. removing these is totally fine.

**Comment by zloyden** [comment]
Hi @ahmedtds ! Just compare these two links. Actually, if we remove these parameters, there will be incorrect blocking and I don't see them as tracking ones.
```
https://twitter.com/lunasorcery/status/1449400981188382722
https://twitter.com/lunasorcery/status/1449400981188382722?t=9oAxgaekyCU8sMB3lRo5yw&s=19
```
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/33488229/142239123-77acd72d-dd00-4cb9-9cb5-5aa9f9b0b07e.png)
![image](https://user-images.githubusercontent.com/33488229/142239201-e3fabda5-b8e9-49f4-b008-bd93e092f101.png)


</details><br/>
