### ISSUE TITLE
How to allow mining on a certain site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#9809]
if it's been previously blocked? Clearing cache and opening it in a private tab is not forcing AdGuard to show the notification again. Reported/asked here: 1726903

Is it possible to check what miners are blocked and where? How does it work in general? :)

**Comment by Alex-302** [comment]
Этот майнер заставляет тормозить даже мой i7 4770k. Он здесь не заблокирован.
Добавил в фильтр `||webminerpool.com/miner.js$third-party`
исклютение: `||webminerpool.com/miner.js$third-party`

**Comment by evgeniy-ADG** [comment]
Все же, если я, допустим, запретил майнить, как мне разрешить это дело обратно? Что нужно сделать, чтобы запрос снова появился?

**Comment by Alex-302** [comment]
очистить localstorage и или куки. Но мы блокируем майнеры и по урлу, так что вероятно ещё сам скрипт понадобится исключить.
