### ISSUE TITLE
nerdyelectronics.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98169]
**Issue URL (Annoyance)**:
https://nerdyelectronics.com/selection-criteria-for-sensors/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138881507-8af7102a-e058-4b46-ab8c-5ce6513f9c21.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Already fixed.
