### ISSUE TITLE
www.escomponents.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98162]
**Issue URL (Annoyance)**: https://www.escomponents.com/blog/2019/7/31/what-is-a-transducer

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138879901-e6c85209-7c0c-4847-8375-ecb18d6a083a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
6190 visitors/month
