### ISSUE TITLE
www.bourns.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98179]
**Issue URL (Ads/Annoyance)**:

https://www.bourns.com/products/encoders/optical-encoders
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138882564-a3f644d4-ca9d-45b0-a993-cb829deb09a8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Already fixed.
