### ISSUE TITLE
theteche.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98187]
**Issue URL (Ads/Annoyance)**:
https://theteche.com/what-is-diaphragm-in-pressure-sensor/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138883548-ba15ccdb-68e7-48b2-afb9-9fe1fd4e10ba.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
It seems that website doesn't have enough visitors.
Please add to "User rules":
```
theteche.com#?##sidebar > div[id^="custom_html-"]:has(> .textwidget > .adsbygoogle)
```
