### ISSUE TITLE
www.avnet.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98190]
**Issue URL (Annoyance)**:

https://www.avnet.com/wps/portal/abacus/solutions/technologies/sensors/pressure-sensors/core-technologies/piezoelectric/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138884032-ba05d34e-2a1f-4ec0-8814-9e6f19e61b03.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not a third party chat.
