### ISSUE TITLE
superuser.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98281]
**Issue URL (Ads/Annoyance)**:https://superuser.com/questions/397178/how-to-change-the-queue-priority-in-bittorrent

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139073877-1fd99f49-902c-433c-88c5-36fb45b3f4ea.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by chirag127** [comment]
Why closed?

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/1ece3fae9ffc34c121b0e5aee06e04b054187c1f
