### ISSUE TITLE
360 Total Security 9.6.0.1187 - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#9830]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Missed ads in 360 Total Security app for Windows. You can find one here: https://filehippo.com/download_360_total_security_free_antivirus/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/34931789-18e0f4f0-f9d9-11e7-9986-f1b077633127.png)

</details><br/>

***System configuration***

**Filters:**

- FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:10 Name: Filter unblocking search ads and self-promotion Url: https://filters.adtidy.org/extension/chromium/filters/10.txt
- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | n/a
AdGuard version:                       | 6.2.437.2171
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | below
Helpdesk ID (if exists):               | 630373

-  "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": false,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "BlockBrowserFlash": false,
-   "BlockBrowserJava": false,
-   "RemoveXClientDataHeader": true,
-   "StripUrl": false,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": true,
-   "RemoveReferrerFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferrer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254",
-   "BlockThirdPartyAuthorization": false

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@evgeniy-ADG как это окно вызвать?
Передай на проверку:
```
||display.360totalsecurity.com/ad_inapp/banner-xl/
```

**Comment by evgeniy-ADG** [comment]
will do

**Comment by Alex-302** [comment]
@evgeniy-ADG ну что?
