### ISSUE TITLE
[NSFW] https://pornfree.me

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#9835]
**Site Sample** | 
------------------|
https://pornfree.me/sunshine-highway-2/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Openload player not show up when ADG is enabled on site. 

<details><summary><b>Screenshot:</b></summary>

![20180115-150158-001](https://user-images.githubusercontent.com/9846948/34945864-1213f7fe-fa05-11e7-9e2a-bf31e7829dae.png)

</details><br/>

**Comment by Alex-302** [comment]
not reproduced.
@AdamWr please check.

**Comment by FadeMind** [comment]
Today I see player too. IDK why this happen.
