### ISSUE TITLE
Nova launcher (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#98394]
App
https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=ja&gl=US

||sessions.bugsnag.com^
![20211029-1312_1fc014df541b78132ea5247efbb66194](https://user-images.githubusercontent.com/87330832/139374599-f254cfea-36d0-4b9c-9ee7-71057735ef14.png)

**Comment by Alex-302** [comment]
Used by developers. Just block nerwork access for this app.

**Comment by SASUKE0721** [comment]
I understood. Thank you
