### ISSUE TITLE
apnews.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98409]
**Issue URL (Ads/Annoyance)**:https://apnews.com/article/6a8f8156d2adf449b4b8e390682f27d7

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139392709-f5e53330-c607-4121-8712-fedc09028d95.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
That is just an empty headline.
