### ISSUE TITLE
www.controleng.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98410]
**Issue URL (Ads/Annoyance)**:https://www.controleng.com/articles/tips-on-sensor-selection/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139393341-8fe7ddc8-454f-42c6-81f5-f62dad1f5f44.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
Already fixed in the EasyList.
