### ISSUE TITLE
www.spanishdict.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#98441]
**Issue URL (Annoyance)** :https://www.spanishdict.com/examples/masturbated?lang=en

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/139431487-77d4139f-923d-470e-a28c-70dbd3dc88b5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352294-46ac9f21-4436-4822-8702-c7d7c09f0563.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
It seems there is no way how to remove this popup safely.
