### ISSUE TITLE
machine-learning-club-india.github.io

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98492]
**Issue URL (Ads/Annoyance)**: https://machine-learning-club-india.github.io/ml-Club/powerful-things-markdown-editor/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139521606-1e1719de-f361-418b-bb5c-f194cd306a7f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Alex-302** [comment]
No visitors.
