### ISSUE TITLE
greatist.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#98510]
**Issue URL (Ads)** :https://greatist.com/health/nutrition-of-semen

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/139530699-8cf47ceb-b764-49d6-9ecb-d1e1d3896bd8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by AdamWr** [comment]
It seems that it's already fixed.
