### ISSUE TITLE
www.phillymag.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#98511]
**Issue URL (Ads)** :

https://www.phillymag.com/news/2013/08/07/turns-semen-protein-thought/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/82926303/139530718-0e89d82a-2981-43d7-a2f8-4a5b351c9dc9.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by Sergey-Lyapin** [comment]
This is not a lefrover, just a decorative element.
