### ISSUE TITLE
www.whatthehealthfilm.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#98550]
**Issue URL (Ads)** :
https://www.whatthehealthfilm.com/

<details><summary>Screenshots:</summary>

https://www.whatthehealthfilm.com/
![image](https://user-images.githubusercontent.com/82926303/139556853-f3f66354-e386-4802-ae0c-d63623d9beea.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/82926303/127352377-a0ee8e8d-aed6-4019-b51f-c12c39f35b66.png)</details><br/>

**Comment by Sergey-Lyapin** [comment]
4800 visitors/month
