### ISSUE TITLE
ijdvl.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98618]
**Issue URL (Ads/Annoyance)**:
https://ijdvl.com/guidelines-for-writing-a-research-project-synopsis-or-protocol/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139582826-00c7ed44-8537-493b-aa5b-7e05d9caa990.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
I have the same without AdGuard. There is no ad, so we won't block it.
