### ISSUE TITLE
www.storybench.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98625]
**Issue URL (Ads/Annoyance)**:
https://www.storybench.org/how-to-scrape-reddit-with-python/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139587203-d277383e-c336-463c-a163-514acb9d4455.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
14 100 visitors/month
