### ISSUE TITLE
stern.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#98652]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Can’t play the video
`https://www.stern.de/panorama/video/ins-netz-gegangen/tiergeschichten/hund-flutet-garten-seiner-besitzer---und-setzt-dabei-eine-unschuldsmine-auf-30873076.html`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="696" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/139599280-8250f21c-ae70-405b-9346-afacb62f67fd.PNG">

</details><br/>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

<img width="673" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/139599281-bcb175a6-dced-4a87-97c1-31df2745d154.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.6.13
Filters enabled:                       | Default + Adguard tracking protection + adguard annoyances + adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

Whitelisting `||baseendpoint.stern.de^` works for me

**Comment by BlazDT** [comment]
Site is broken without AdGuard for me, scrolling broken, no cookie dialog to accept.
I removed that rule from Annoyances filter.

**Comment by Morku** [comment]
@BlazDT 
Should it work now?
I still need to disable Annoyance filter and deny Cookies to make video work


https://user-images.githubusercontent.com/6276915/139653001-fb330ab7-ae30-4d04-a60e-17f337daaaed.mp4

**Comment by krystian3w** [comment]
Try force update list in app? AdGuard refresh file after 4 days in addons/app if you not modify update to faster inverval/set-timeout.

**Comment by krystian3w** [comment]
@kiboke can you unlock cname in Firefox:

bad are:

```
privacy-mgmt.com$domain=~standard.co.uk|~bild.de|~computerbild.de|~bold.dk|~welt.de|~focus.de|~chip.de|~faz.net|~n-tv.de|~spiegel.de|~privacy-mgmt.com|~wunderweib.de|~tvmovie.de|~praxisvita.de|~cosmopolitan.de|~giga.de|~ostsee-zeitung.de|~lvz.de|~mein-schoener-garten.de|~boerse-online.de|~tvspielfilm.de|~autobild.de|~bike-bild.de|~bz-berlin.de|~cyberport.at|~cyberport.de|~golem.de|~express.de|~volkskrant.nl|~rtl2.de|~si.com|~derstandard.de|~derstandard.at|~unsere-helden.com|~rtl.de|~11freunde.de|~finanzen.at|~finanzen.net|~insider.com|~transfermarkt.at|~transfermarkt.ch|~transfermarkt.co.uk|~transfermarkt.com|~transfermarkt.com.tr|~transfermarkt.de|~transfermarkt.fr|~transfermarkt.it|~transfermarkt.nl|~transfermarkt.pl|~transfermarkt.pt|~transfermarkt.us|~vip.de|~businessinsider.de|~clever-tanken.de|~fitbook.de|~meinestadt.de|~metal-hammer.de|~musikexpress.de|~myhomebook.de|~noizz.de|~politico.eu|~rollingstone.de|~stylebook.de|~techbook.de|~testbild.de|~wieistmeineip.at|~wieistmeineip.de|~wieistmeineip.ch
```

![obraz](https://user-images.githubusercontent.com/35370833/139654992-8161dcf9-0212-4e9f-bf1b-974c75a2a4da.png)

**Comment by BlazDT** [comment]
Added auto-click rule and had to remove JS rules for sourcepoint (else not executed).

**Comment by kiboke** [comment]
@krystian3w I will add an exception as you proposed, although on my side everything works fine even without doing that.

**Comment by krystian3w** [comment]
For test needed is install Firefox + uBO and filter list instead addon.

**Comment by kiboke** [comment]
Of course, I did that and it somehow works as it should on my side. Nevermind, the exception will be added.
