### ISSUE TITLE
www.dns-shop.ru, помогите заблокировать попап "Дополнить отзыв"

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#98661]
На сайте днс'а есть такая пакость, как попап "Дополнить отзыв". Авторизованному юзеру оставившему единожды отзыв к любому товару этот попап все мозги своей назойливостью выскребет. Т.к. он появляется рандомно, сохранил mhtml-ку на смарте и выковырял вот такой код попапа :
```
<article class="additional-opinion additional-opinion__wrapper">
	<section class="additional-opinion__content">
		<section class="additional-opinion__image additional-opinion__image_wrapper">
			<picture>
				<img class="loading" src="https://c.dns-shop.ru/thumb/st4/fit/60/60/9f069c6ff257866941fd599f99ddedf6/2c0f31187acf4d4944f9c5a166526785bdba2b15b1d851eee203802a1972765e.jpg" alt="" data-was-processed="true">
				</picture>
		</section>
		<section class="additional-opinion__text additional-opinion__text_wrapper">
			<p class="additional-opinion__text additional-opinion__text_header">Прошло много времени, возможно вам есть что рассказать.</p>
			<p class="additional-opinion__text additional-opinion__text_product-name">Компактная мышь проводная Oklick 105S черный</p>
		</section>
		<section class="additional-opinion-buttons additional-opinion-buttons__wrapper">
			<button class="button-ui button-ui_brand additional-opinion__button additional-opinion-buttons additional-opinion-buttons__opinion-button" data-commerce-target="WidgetAdditionalReview_Starter_Begin">Дополнить отзыв</button>
		</section>
		<span class="additional-opinion additional-opinion__close-icon" data-commerce-target=""/>
	</section>
</article>
```

Помогите составить фильтр, который в частности будет цепляться за строку "Прошло много времени, возможно вам есть что рассказать."

<img src="http://i1.sendpic.org/i/kq/kqMU2cHVtML2I2baBiVbH3rIBGy.jpg"></img>

**Comment by Sergey-Lyapin** [comment]
@Baltazar500
Попробуйте такое правило потестить:
`dns-shop.ru##.additional-opinion`

**Comment by Baltazar500** [comment]
@Sergey-Lyapin, вроде помогло, но ещё пару дней посмотрю. Оно обычно ввлезает каждые сутки. Проконтроллировать отработку своих фильтров в журнале можно ? Или эти события туда не пишутся ?

К слову, с этим фильтром в процессе чтщ-то непонятное творилось. Несколько раз галка снималась, хотя я точно проставлял. Пока не пойму, оз-за чего это происходило. То ои из-за того, что смахивал adguard (работать он поале этого не прекращал как 2.12.250 на 4.2.2) , то ли из-за чего ещё.

**Comment by Sergey-Lyapin** [comment]
@Baltazar500 
Если это не браузерное расширение, то отследить применение косметических правил не получится

**Comment by Baltazar500** [comment]
@Sergey-Lyapin, приложение для android. Может прикрутите такую возможность ? А то поставишь правило плавающий попап и сиди гадай отработало оно или нет - снимешь блоккинг, попап появился, вернёшь назад - вроде исчез, снова отрубишь, а попап уже и без блоккинга не появляется *facepalm*

**Comment by Sergey-Lyapin** [comment]
@Baltazar500
Как я понимаю проблем с правилом не возникло? Добавлю в общий фильтр.
