### ISSUE TITLE
LINEcamera(Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#98670]
App
https://play.google.com/store/apps/details?id=jp.naver.linecamera.android&hl=en_US&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dlinecamera&pcampaignid=APPU_1_DGJ_YZiQDcvY-gTFq6uABQ

Adserver
||adg.kajicam.com^

analysis
||adg-data.kajicam.com^
![Screenshot_20211101-115302675](https://user-images.githubusercontent.com/87330832/139615693-43748224-d082-4d9d-b37c-fb6838707faf.jpg)

**Comment by Alex-302** [comment]
Thanks.
