### ISSUE TITLE
The inscription about the subscription is not hidden, despite the mask added to the subscription!

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardFilters#98758]
@Spok1 commented on [Tue Nov 02 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4016)

### Issue URL (Social Widget)
 [https://ichip.ru/tekhnologii/est-li-smysl-defragmentirovat-ssd-712132](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fichip.ru%2Ftekhnologii%2Fest-li-smysl-defragmentirovat-ssd-712132)
### Screenshots
<details>
  <summary>Screenshot 1</summary>

 ![image](https://user-images.githubusercontent.com/34476664/139775908-4fcd5f3e-ea8b-48f5-b245-1808f42b887c.png)

</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.0
Device model:|Z500M
Root:|No
AdGuard product: | AdGuard for Android v3.6.2 (23)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | disabled

**Comment by Spok1** [comment]
@zloyden,может [этот](https://www.048.ua/amp/news/3244727/zacem-kola-v-odesskoj-oblasti-deputat-zaavil-cto-ne-budet-vakcinirovatsa) сайт тоже добавить под эту маску?

**Comment by zloyden** [comment]
Это не маска, а директива. Ее предназначение в том, чтобы правила использовались только в программе.
Насчет этой задачи https://github.com/AdguardTeam/AdguardFilters/issues/95975#issuecomment-929695192 лучше написать сюда https://github.com/AdguardTeam/AdguardForAndroid/issues, у нас не повторяется.

**Comment by Spok1** [comment]
> Это не маска, а директива. Ее предназначение в том, чтобы правила использовались только в программе. 

Я так и понял,просто не совсем так,как вы это понимаете выразился!
 Создам топик,но, почему-то мне кажется,что именно вы придёте разбираться с этим!😁
