### ISSUE TITLE
Errors in mi router admin panel

### ISSUE THREAD

**Issue by Djaler** [AdguardTeam/AdguardFilters#98826]
Adguard for Windows 7.7.1
Without adguard:
![image](https://user-images.githubusercontent.com/7964583/140015424-5388534b-e7d2-45c5-bdba-b043f4b6b079.png)
With adguard:
![image](https://user-images.githubusercontent.com/7964583/140015396-0b7c31c3-eb88-4b20-bb55-d378f19c8c23.png)

**Comment by Alex-302** [comment]
@Djaler Hi. Which model? What breaks - ad blockin? DNS filtering or stealth mode?

**Comment by Djaler** [comment]
It's Mi Router 4a gigabit edition (Chinese)
Dns protection and stealth mode are disabled.
Also, strange thing - in filtering log this requests are not marked as blocked
![image](https://user-images.githubusercontent.com/7964583/140729842-f9724edd-997b-4e7b-9d02-b91e26af90bc.png)

**Comment by Alex-302** [comment]
@Djaler Please test these rules one by one:
`@@||192.168.31.1^$document`
`@@192.168.31.1$network`

**Comment by Djaler** [comment]
Nope. The strangest thing - it still leads to errors if I disable whole ad blocker in settings. But it works good if I disable protection (on main screen)

**Comment by Alex-302** [comment]
@Djaler Probably a bug https://github.com/AdguardTeam/CoreLibs/issues/1538 Will close here. In the issue above you may attach logs ot ticket ID, if you send the logs to support@adguard.com
How to collect debug logs https://kb.adguard.com/en/windows/solving-problems/adguard-logs
