### ISSUE TITLE
Unable to register Mobile Security & Antivirus app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#9890]
> Не получается активировать лицензию, зарегистрировать мобильный антивирус ESET. Выдает сообщение о невозможности подключиться к интернету. Но интернет нормально работает. Установлено соединение через семейный DNS (176.103.130.132 и 134). DNS прописан в роутере.

https://play.google.com/store/apps/details?id=com.eset.ems2.gp&referrer=utm_source%3Deset.com%26utm_medium%3Dreferral%26utm_campaign%3Dglobal-web

**Comment by Alex-302** [comment]
I can't reproduce this issue.
@AdamWr @BlazDT please check trial license activation with AdGuard DNS on router.
