### ISSUE TITLE
www.idrlabs.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98941]
**Issue URL (Ads/Annoyance)**:https://www.idrlabs.com/psychopathy-spectrum/test.php

<details><summary>Screenshots:</summary>

https://www.idrlabs.com/psychopathy-spectrum/test.php
![image](https://user-images.githubusercontent.com/76880977/140290211-fb633aca-ed0b-48b5-8e24-d3b726241d01.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
Not an annoyance.
