### ISSUE TITLE
iteo.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98958]
**Issue URL (Ads/Annoyance)**:

https://iteo.com/blog/post/10-useful-chrome-plugins-for-software-testers
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/140319810-014a3e3e-bf96-4e56-8084-a3918bb2afb5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
8780 visitors/month
