### ISSUE TITLE
> 윈도우10 업데이트 KB5006670 설치 이후 또는 10월 업데이트 보안 업데이트 이후 wavve 자체광고 아닌 TV광고시 블랙스크린 현상이 일어납니다. 스트리밍이 멈춤 상태가 됩니다. 윈도우 선택 업데이트인 KB5006738 을 설치하면 해결 될거 같았지만 소용 없습니다. 내 이메일 주소 gmg23@hanmail.net 또는 gmg23@daum.net 으로 해결방법 좀 보내주시면 감사 하겠습니다.

### ISSUE THREAD

**Issue by gmg0823** [AdguardTeam/AdguardFilters#98956]
> 윈도우10 업데이트 KB5006670 설치 이후 또는 10월 업데이트 보안 업데이트 이후 wavve 자체광고 아닌 TV광고시 블랙스크린 현상이 일어납니다. 스트리밍이 멈춤 상태가 됩니다. 윈도우 선택 업데이트인 KB5006738 을 설치하면 해결 될거 같았지만 소용 없습니다. 
Please check if this is really related to Adguard by turnning off the extension.

_Originally posted by @Yuki2718 in https://github.com/AdguardTeam/AdguardFilters/issues/98841#issuecomment-958955850_

**Comment by Yuki2718** [comment]
Please do not open a new issue ticket while discussion is ongoing in the original issue.
