### ISSUE TITLE
www.becomeopedia.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98980]
**Issue URL (Ads/Annoyance)**:
https://www.becomeopedia.com/philosopher/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/140407180-eae5effc-2b16-4eee-8800-11a714ba332a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
