### ISSUE TITLE
Canva(Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#99016]
#App
https://play.google.com/store/apps/details?id=com.canva.editor&hl=en_US&gl=US&auao=none&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dcanva&pcampaignid=APPU_1_-qyEYfGQFIXR0PEPs4mM8Ak

||api.castle.io^
![Screenshot_20211105-130240912](https://user-images.githubusercontent.com/87330832/140456478-8a65cb68-23c7-4ed5-a3c7-4ac1c640c001.jpg)

**Comment by Alex-302** [comment]
Not sure. This is fraud protection. Blocked another domain.
