### ISSUE TITLE
ベネッセ(Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#99015]
App
https://play.google.com/store/apps/details?id=jp.co.benesse.ParentsApp&hl=ja&gl=US&auao=none&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3D%E3%81%BE%E3%81%AA%E3%81%B3%E3%81%AE%E6%89%8B%E5%B8%B3+%E7%84%A1%E6%96%99&pcampaignid=APPU_1_wauEYZyDEMXG0PEP8Me3qAI

||api.karte.io^
||*tag.karte.io^
||b.logly.co.jp^
||lt.logly.co.jp^
||*.nakanohito.jp^
||tags.tiqcdn.com^
[Screenshot_20211105-122253399](https://user-images.githubusercontent.com/87330832/140455735-1bd189c5-163a-43ed-a6ce-5f91a7dd862d.jpg)
[Screenshot_20211105-124021562](https://user-images.githubusercontent.com/87330832/140455754-389a3e3e-d6a1-4713-8ba2-6e1d579c4d36.jpg)
[Screenshot_20211105-124026776](https://user-images.githubusercontent.com/87330832/140455772-797b6310-1565-4934-bf6a-3a5e4f07c3d7.jpg)
[Screenshot_20211105-124041095](https://user-images.githubusercontent.com/87330832/140455784-8d662d96-e32a-4867-86c3-75be85d28606.jpg)
[Screenshot_20211105-130004870](https://user-images.githubusercontent.com/87330832/140456196-25280fe8-219f-49ce-9ff2-b1d817a50953.jpg)
[Screenshot_20211105-130047323](https://user-images.githubusercontent.com/87330832/140456201-b77f7ed6-0da6-45ab-9d9c-43f687560ff9.jpg)

**Comment by SASUKE0721** [comment]
||b.logly.co.jp^
||lt.logly.co.jp^
||*.nakanohito.jp^
The display is strange, so I fixed it.
![Screenshot_20211108-214705118](https://user-images.githubusercontent.com/87330832/140744685-fca1a0f3-9aa7-4656-ae06-4b1c8bb9a30e.jpg)

**Comment by Alex-302** [comment]
> ||tags.tiqcdn.com^ 

Will break too much.
Also not sure about some others.

**Comment by SASUKE0721** [comment]
All are tracking domain.  I sometimes see it on LINE.  However, you don't have to block it because the element may be broken in other apps.
