### ISSUE TITLE
抖音(Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#99019]
App
https://a.app.qq.com/o/simple.jsp?pkgname=com.ss.android.ugc.aweme&channel=0002160650432d595942&fromcase=60001

||log*-misc-lf.amemv.com^
||msg.umengcloud.com^
||mon.snssdk.com^
[Screenshot_20211105-132408802](https://user-images.githubusercontent.com/87330832/140465100-ea447e08-25a3-4112-a60d-26fa7963a949.jpg)
[Screenshot_20211105-145708733](https://user-images.githubusercontent.com/87330832/140465173-74fb541c-bdee-4d04-81e8-725a55900d37.jpg)
[Screenshot_20211105-145833658](https://user-images.githubusercontent.com/87330832/140465323-2b6a3762-a1c4-4f4e-a129-c4ebf628d384.jpg)

**Comment by c2xusnpq6** [comment]
https://github.com/privacy-protection-tools/anti-AD/

https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-domains.txt
