### ISSUE TITLE
Adobe tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#99021]
https://www.adobe.com/acrobat/online/pdf-to-jpg.html --> `POST` https://dc-api.adobe.io/system/log

```
https://dc-api.adobe.io/system/log

||dc-api.adobe.io/system/log^
```

![image](https://user-images.githubusercontent.com/75058881/140468170-b08b63a1-a7ef-435f-859a-e83155cbf267.png)

**Comment by Alex-302** [comment]
already blocked
