### ISSUE TITLE
[Android] Drag Racing Classic

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#991]
https://play.google.com/store/apps/details?id=com.creativemobile.DragRacing
screens and logs here - HKB-914-48997

**Comment by Alex-302** [comment]
А где сам вопрос? В тикете ни описания, ни скринов нет.

**Comment by Alex-302** [comment]
Нет новостей?

**Comment by Bohdan-SUP** [comment]
Asked user. Will wait for his reply.

**Comment by evgeniy-ADG** [comment]
He said that the issue still persists.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Вроде всё нормально. Если не ошибаюсь, у него просто всплывает остаток рекламы, игровой процесс не нарушается?
