### ISSUE TITLE
www.howtofree.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99133]
**Issue URL (Annoyance)**:
https://www.howtofree.org/learn-complete-cyber-security-course-hackers-exposed-free-download/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/140586972-cb5a55d9-e8e0-4612-aa0a-d5b87d39a018.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
Timer is already skipped/boosted.
