### ISSUE TITLE
getinternet.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99163]
**Issue URL (Ads/Annoyance)**:
https://getinternet.com/slow-internet-at-night/
<details><summary>Screenshots:</summary>

https://getinternet.com/slow-internet-at-night/
![image](https://user-images.githubusercontent.com/76880977/140605578-1b32f675-a30a-4764-baf4-353fc62cd0eb.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4 090 visitors/month
