### ISSUE TITLE
Consider adding NoCoin filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#9923]
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt

Requested here: 1627368

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #6](https://github.com/AdguardTeam/FiltersRegistry/issues/6) via [**ZenHub**](https://www.zenhub.com/)
