### ISSUE TITLE
www.searchcommander.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99235]
**Issue URL (Ads/Annoyance)**:
https://www.searchcommander.com/seo-tools/bulk-url-checker/

<details><summary>Screenshots:</summary>

https://www.searchcommander.com/seo-tools/bulk-url-checker/
![image](https://user-images.githubusercontent.com/76880977/140646279-95fd48cb-de31-48d4-9010-fdbf75c1b75d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>https://www.searchcommander.com/seo-tools/bulk-url-checker/

**Comment by Sergey-Lyapin** [comment]
18600 visitors/month
