### ISSUE TITLE
A rule that blocks direct IP connections to the server.

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#99232]
![Screenshot_20211107-193156_Trebuchet.png](https://user-images.githubusercontent.com/75058881/140645533-3a986b35-0fcc-45a2-80a8-f6031607afcc.png)

IP `203.119.206.64` will point to the domain `center.amdc.m.taobao.com`, which should have been blocked.

I tried to use this rule, but it blocks all network packets.
```
*$network,app=com.duozhuayu.dejavu
```

![Screenshot_20211107-192843_Trebuchet.png](https://user-images.githubusercontent.com/75058881/140645052-86df819a-9508-4ece-9689-bb318451ac65.png)

https://github.com/AdguardTeam/AdguardForAndroid/issues/4022

**Comment by c2xusnpq6** [comment]
Xiaomi successfully bypassed those network packets from AdGuard:

![Screenshot_20211107-191334_Trebuchet.png](https://user-images.githubusercontent.com/75058881/140645409-6cb0f76d-53e1-4206-b9b2-68991210e589.png)

![Screenshot_20211107-163925_Trebuchet.png](https://user-images.githubusercontent.com/75058881/140645413-d3660cb8-dad4-41b7-a01e-51f269f11669.png)

**Comment by Disqu3-mirOir-qt** [comment]
not bypass network rules work only for ip, not for hostname

**Comment by c2xusnpq6** [comment]
> not bypass network rules work only for ip, not for hostname 

Sorry for not writing clearly enough to make you misunderstood.

Chinese app trackers bypass the filters, so I want to keep some apps from connecting directly to the backend server by ip.

I tried to use this rule, but it blocks all network packets.
```
*$network,app=com.duozhuayu.dejavu
```

**Comment by Alex-302** [comment]
Many sites/services can use the same IP.

**Comment by c2xusnpq6** [comment]
> Many sites/services can use the same IP.

I know that, but my situation is not like that.... reopen pls?

**Comment by c2xusnpq6** [comment]
thx

**Comment by Alex-302** [comment]
So what do you want to do? I don't understand.
