### ISSUE TITLE
halowaypoint.com

### ISSUE THREAD

**Issue by nobelharvards** [AdguardTeam/AdguardFilters#99290]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Halo Waypoint does not load correctly when subscribed to the AdGuard Annoyances list. The page may briefly display some content, but will go blank after a few seconds.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/9457934/140677874-c2a7e82c-a15e-4b67-b53d-10266f8219d3.png)
</details><br/>

* **Expected behaviour**: 

Halo Waypoint content should be displayed.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/9457934/140678074-46c26220-6800-4870-9861-bd9f3a4ad921.png)
</details><br/>

***Steps to reproduce the problem***:

Subscribe to AdGuard Annoyances list with any adblocker. Visit any page on Halo Waypoint.

***System configuration***

**Filters:**

AdGuard Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | N/A
Browser:                               | Firefox
AdGuard version:                       | N/A
Filters enabled:                       | AdGuard Annoyances
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
