### ISSUE TITLE
play.spotify.com - breaks "next" button

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#993]
play.spotify.com

> Also with the Adguard extension on OS X I noticed an issue with play.spotify.com. When viewing an artist's page, clicking an album, and then viewing the track list, it won't allow the song to be played by clicking the play button next to the song (the play button appears on top of the track number when hovering over the song name on the track list). Instead of playing the song, it redirects to a blank page that is black and takes up most of the screen. I tested this again with the extension disabled, and the issue was not present. I like that Adgaurd removes ad banners on the website and also does not play any ads between songs, so I don't want to lose that functionality, but this issue is both strange and frustrating.

**Comment by Alex-302** [comment]
Can't reproduce. Need the filters list.
