### ISSUE TITLE
Revise noop.txt and noop.js redirect rules in the Base filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#99316]
The problem is described here:
https://github.com/uBlockOrigin/uAssets/issues/10238#issuecomment-945925162

Also, note what Raymond says:
https://github.com/uBlockOrigin/uAssets/issues/10238#issuecomment-945866511

> I don't think AdGuard is using /web_accessible_resources/ to redirect, while uBO does. I suspect Firefox is detecting that the resource's mime is not application/javascript and refuses to redirect

The thing is that in v4.0 we now use `/web_accessible_resources/` so those `noop.txt` rules will stop working in Firefox after the update.

In order to avoid that we need to revise `noop.txt` / `noop.js` rules and replace `noop.txt` with `noop.js` where this is applicable.

**Comment by jellizaveta** [comment]
I checked websites where were used `redirect=nooptext` rules for script recurses. After replacing noop.txt with noop.js , rules works same regardless of browser.

**Comment by ameshkov** [comment]
@jellizaveta are there any rules that are still need to be revised? If there're none, this issue can be closed.

**Comment by Alex-302** [comment]
Why closed? Nothing is changed in filters yet.

**Comment by zloyden** [comment]
> I checked websites where were used `redirect=nooptext` rules for script recurses. After replacing noop.txt with noop.js , rules works same regardless of browser.

That's good, but now you should replace those rules with new `redirect`, as @ameshkov said .

**Comment by jellizaveta** [comment]
Replaced rules with new redirect for script resources.
