### ISSUE TITLE
Bromite Browser .dat list?

### ISSUE THREAD

**Issue by RicoHeat** [AdguardTeam/AdguardFilters#99337]
Will you guys please provide us not so tech savvy people an already converted and compiled Adguard list that is compatible with Bromite Browser for Android. The Devs provide instructions on how to create our own but honestly its a little complicated for me at least. That would be great.. The people at Energized are already providing their own lists but I would love an Adguard version.. This would really make my day and it would be an early Christmas gift for all of your fans.    😁👍

**Comment by Alex-302** [comment]
Why not to install AdGuard? Not sure if Bromite supports all our syntax.
