### ISSUE TITLE
http://nwn2db.com/ - unable to whitelist

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#9943]
1. This is how the site looks when AdGuard filters it: https://uploads.adguard.com/0e7lb.png
2. This is how it works when AdGuard is disabled: https://uploads.adguard.com/5g50k.png
3. Here's how we whitelist: https://uploads.adguard.com/97sx4.png

Is there a way to whitelist the site properly?

MacOS High Sierra, Chrome, AdGuard 1.5.3, English, Russian, Spyware, Social media, Annoyances, Safari filters.

**Comment by Alex-302** [comment]
This rule works for me:
```
@@||nwn2db.com^$document
```
