### ISSUE TITLE
canyoublockit.com is blocked in AdGuard Base filter

### ISSUE THREAD

**Issue by TheGeeKing** [AdguardTeam/AdguardFilters#99447]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
canyoublockit.com is blocked in AdGuard Base filter
* **Current behaviour**: 
blocks website

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

* **Expected behaviour**: 
not being blocked as a useful tool to test adblockers

***Steps to reproduce the problem***:
use AdGuard Base filter and go to https://canyoublockit.com

***System configuration***
nextdns or adguard
**Filters:**
AdGuard Base filter

[//]: # (Please enter the correct values for your case to the table below)
[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Sergey-Lyapin** [comment]
Hi, @TheGeeKing 
AdGuard Base filter was not designed to be used with NextDNS, AdGuard DNS, Pi-hole etc. 
Please use AdGuard DNS filter: https://filters.adtidy.org/windows/filters/15.txt
