### ISSUE TITLE
tiktok.com (SDNS filter)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardFilters#99486]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Trying to login to TikTok with SDNS filtering or AdGuard DNS fails to complete the login process.
* **Current behaviour**: 

After logging into the TikTok app on iOS, I am asked to complete two-step authentication via email. Once complete, it redisplays the two-step authentication prompt with a new code. This continues until you are blocked from further codes.

* **Expected behaviour**: 

After logging into the TikTok app on iOS, I am asked to complete a puzzle piece style CAPTCHA, then asked for two-step authentication via email. Once complete, it asks for a second puzzle piece style CAPTCHA. Then, you are logged in with no issue.

***Steps to reproduce the problem***:

1. Fresh install of TikTok on iOS
2. Open and proceed to sign in
3. Sign in via email and enter details
4. (You should be asked for a CAPTCHA, but it is blocked)
5. Complete two-step authentication email verification, and it will ask again for another email verification, and another
6. (You should be asked for a second CAPTCHA, but it is blocked)

**Comment by jellizaveta** [comment]
Hi ! Unfortunately, I could't reproduce repeated verification code on two-step authentication, but faced 'invalid parameters' message on step with date input. Problem caused by rule form AdGuard SDNS filter.So, I added fixes (filter update would be available in 1-2 hours).  Please, let me know, is your issue has been resolved.

**Comment by planet0** [comment]
Hi @jellizaveta, yes! It is now resolved the sign in problems.
