### ISSUE TITLE
LINEマンガ(Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#99488]
App
https://play.google.com/store/apps/details?id=jp.naver.linemanga.android&hl=en_US&gl=US&auao=none&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dline%E3%83%9E%E3%83%B3%E3%82%AC&pcampaignid=APPU_1_epqLYYDGAa3J0PEPp_6s-Ac

Ad server
||w.line.me^
![Screenshot_20211110-190639225](https://user-images.githubusercontent.com/87330832/141093714-2aaf3e9f-a548-41e9-be65-19c53796aa2a.jpg)
![Screenshot_20211110-190707816](https://user-images.githubusercontent.com/87330832/141093730-03ab5325-94f0-444c-9f52-cf73f1cd521f.jpg)

**Comment by SASUKE0721** [comment]
However, please add this rule as you will not be able to take over LINE.
@@||w.line.me^$app=jp.naver.line.android

**Comment by Alex-302** [comment]
Hm. Looks dangerous. What about `||w.line.me^$app=jp.naver.linemanga.android`?

**Comment by SASUKE0721** [comment]
Certainly, the rules I reported can adversely affect other LINE-related services, so I think it's okay to block only LINE Manga.  🙂

**Comment by Alex-302** [comment]
Ok.
