### ISSUE TITLE
pagead2.googlesyndication.com - missed ad domain

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#9949]
Some ads in apps are from pagead2.googlesyndication.com.

It seems that AdamWr didn't see the article.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1520#issuecomment-343815130

Yes, you have rules for pagead2.googlesyndication.com in other filters, but actually you don't block the whole domain, pagead2.googlesyndication.com.

The ads will still appear even if enabling AdGuard Protection.
1. For example, other ad paths under the domain.
2. Because pagead2.googlesyndication.com isn't in Simplified domain names filter, AG Pro for iOS is unable to block ads from pagead2.googlesyndication.com.

I think that it's a common ad domain such as doubleclick.net or flurry.com.
Will there be any affection if blocking the whole pagead2.googlesyndication.com?

If it's possible, please add ||pagead2.googlesyndication.com^ in both of English filter (or Mobile ads filter) and Simplified domain names filter.

B/R

**Comment by AdamWr** [comment]
I think it is related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/4639, so I'm not sure if this rule should be added.

**Comment by Alex-302** [comment]
Yes, we can't block this domain in DNS filter.
