### ISSUE TITLE
[Android] Прерывается видео в приложении ex.ua

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#995]
Вот в этом приложении https://play.google.com/store/apps/details?id=com.ligamedia.films, само видео проигрывается с помощью MX (в других плеерах у меня не проигрывается).

Актуально в режиме VPN, с прокси у меня не повторилось.
1. Запустить программу
2. Выбрать видео, выбрать сжатый поток mp4 http://snag.gy/d6w8Y.jpg
3. Проигрывать в МХ
4. Смотреть несколько минут, после чего изображение зависает, а самом плеере продолжает идти отсчёт времени: http://snag.gy/rKuyc.jpg
5. Отключаем Adguard, ситуация не повторяется, а загрузка фильма значительно ускоряется.
6. Пользователь решил проблему, убрав блокировку рекламы для приложения.

TICKET ID
WUA-386-29922

**Comment by Alex-302** [comment]
Похоже что версия старая. Пусть напишет какая.

**Comment by evgeniy-ADG** [comment]
У меня повторяется на 2.1.267, ex.ua - последняя с маркета.

**Comment by Alex-302** [comment]
А если выключить все фильтры и фильтрацию dns?

**Comment by evgeniy-ADG** [comment]
DNS была выключена, фильтры только что отключил - зависает на второй минуте воспроизведения.

**Comment by Alex-302** [comment]
Похоже баг. Здесь закрываю, открыл в соответствующем разделе
https://github.com/AdguardTeam/AdguardForAndroid/issues/200

**Comment by Alex-302** [comment]
@evgeniy-ADG А запроси, плиз, полный лог.

**Comment by Alex-302** [comment]
и можно HTTP лог со своей стороны.

**Comment by evgeniy-ADG** [comment]
@Alex-302 Мне правила, которые ты просил попробовать, удалить перед записью лога?

**Comment by Alex-302** [comment]
они ж для fs были. Но да, можно удалить.

**Comment by evgeniy-ADG** [comment]
Да, извини. В общем, воспроизвести не смог, всё работает. Ждём пользователя.

**Comment by vbagirov** [comment]
NFM-760-58524

**Comment by Alex-302** [comment]
Вижу только один заблокированный запрос, но он вряд ли ломает.
Пусть проверит выключить все фильтры. Если не поможет - нужно будет переключиться на прокси.
