### ISSUE TITLE
Tracedock tracking domains

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardFilters#99518]
original issue: https://github.com/AdguardTeam/cname-trackers/issues/22

Tracedock domains found:

```
host10.carl-ras.dk
alpha.tracedock.com
apollo.plein.nl
beta.simpel.nl
dtch.brunel.nl
exc.ns.nl
host10.ncoi.nl
host11.polaroid.com
host12.rvshare.com
r.kleertjes.com
s3.smartphonehoesjes.nl
sta.tracedock.com
style.onvz.nl
tdapi.wickey.nl
tdep.hema.nl
tdep.kvk.nl
tdk.petsplace.nl
two.tracedock.com
```

Ref: https://github.com/easylist/easylist/pull/9579

- - -

none of these domains resolves to any `*.eu-central-1.compute.amazonaws.com` subdomains, so nothing can be done with them in `cname-trackers`

but some of them seems to be used for tracking (e.g. `host11.polaroid.com` on [polaroid.com](https://polaroid.com/)) and might be added to tracking protection filter manually

**Comment by nickspaargaren** [comment]
Hi @slavaleleka, thanks for opening the issue here!

**Comment by zloyden** [comment]
Hi @nickspaargaren! Added some of them to our filters.
