### ISSUE TITLE
ovamusic.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99538]
**Issue URL (Ads/Annoyance)**:https://ovamusic.com/2021/10/25/jai-bhim/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141161057-670b3fa3-56b7-4210-9d17-ad1f8491c045.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
It looks the same without AG
