### ISSUE TITLE
blog.media.io

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99551]
**Issue URL (Ads/Annoyance)**:https://blog.media.io/top-list/movie-websites.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141163882-17e66394-be06-4179-8ed6-669c11979deb.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/99554

**Comment by chirag127** [comment]
Why you mentioned this issue? Seems like it have same domain but different issue and url?
