### ISSUE TITLE
Wrong section 

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#99582]
By mistake i reported the issue on a different section

https://github.com/AdguardTeam/ReportsWebApp/issues/287

Can u plz move it to this section and if possible push the update 😅

**Comment by Bhooty** [comment]
I think instead of mlsbd.shop 
U should add mlsbd.* like u did for gdtot sir 
Since they also change domain frequently :(

**Comment by Alex-302** [comment]
> mlsbd.*

Why?

**Comment by Bhooty** [comment]
> > mlsbd.*
> 
> Why?

They change domains after some months so then again u have to change it :(

**Comment by Alex-302** [comment]
Please write here when domain will be changed next time:)
As I see, they may change not TLD only...

**Comment by Bhooty** [comment]
> Please write here when domain will be changed next time:) As I see, they may change not TLD only...

I am here again sir
They again change gdtot.top to gdtot.eu
