### ISSUE TITLE
breeds.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#99596]
[https://www.breeds.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.breeds.com.br/)

Bottom cookie notice:

![breeds](https://user-images.githubusercontent.com/35470489/141234096-af97f7ee-647b-44e8-82ec-0b97f4c35421.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Sergey-Lyapin** [comment]
Too few visitors.
For user rules: `breeds.com.br###m-cookienotice`
