### ISSUE TITLE
ドットエスティ(Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#99603]
App
https://play.google.com/store/apps/details?id=jp.point.android.dailystyling&hl=ja&gl=US&auao=none&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3D%E3%83%89%E3%83%83%E3%83%88%E3%82%A8%E3%82%B9%E3%83%86%E3%82%A3+android&pcampaignid=APPU_1_o5eMYb6MCoXP0PEPtMyfsAs

||ada-tr.staff-start.com^
||analytics.liveact-vault.com^
||dex50.deteql.net^
||syteapi.com^
[Screenshot_20211111-130509860](https://user-images.githubusercontent.com/87330832/141235461-7098aa08-60ac-4073-998a-bd5236d9783a.jpg)
[Screenshot_20211111-130234653](https://user-images.githubusercontent.com/87330832/141235466-9711081f-3091-453c-a1be-735230142bf0.jpg)
[Screenshot_20211111-130739740](https://user-images.githubusercontent.com/87330832/141235469-476a9ccb-d893-44f0-8b4f-7054e1c518ff.jpg)
[Screenshot_20211111-130142806](https://user-images.githubusercontent.com/87330832/141235471-10880a6f-47ef-4cd8-9181-7d9315d8eb21.jpg)

**Comment by Alex-302** [comment]
Cannot find any info about syteapi.com
