### ISSUE TITLE
AdGuard can not work in 360ChromeX（A 64 bit browser）

### ISSUE THREAD

**Issue by KingwithQueen** [AdguardTeam/AdguardFilters#99633]
When using 360ChromeX（A 64 bit browser）, no matter what web page is opened, adguard cannot filter advertisements, and adguard's browser extension also fails. However, without modifying any adguard settings, using a 32-bit browser, such as Microsoft edge, adguard will work normally.

I checked the adguard program and found that adguard is a 32-bit program. I think this is the main reason why adguard can't work properly on 64 bit browsers. I hope it can be solved quickly.

In addition, you can download 360ChromeX through this website: [https://browser.360.cn/eex/index.html?channel=0](url)

PS: I'm not 100% sure that the reason why adguard can't work is that the browser is 64 bit, maybe it's just an incompatibility problem. But anyway, I hope to solve this problem quickly. I'm tired of advertising.

**Comment by DandelionSprout** [comment]
I haven't heard of problems with *AdGuard Browser Extension* or *AdGuard for Windows* in 64-bit builds of Chrome, Vivaldi, or Firefox, so that aspect alone doesn't seem like the main cause.

**Comment by KingwithQueen** [comment]
> I haven't heard of problems with _AdGuard Browser Extension_ or _AdGuard for Windows_ in 64-bit builds of Chrome, Vivaldi, or Firefox, so that aspect alone doesn't seem like the main cause.

Then maybe it's just a browser compatibility problem. I only have this 64 bit browser, and the others are 32-bit browsers. After my test, there is no problem with other browsers, even the 32-bit version of this browser. However, for 64 bit 360ChromeX, AdGuard does not work properly.
This may only be solved by AdGuard's production team.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/142872833-1241deee-b25d-4ff9-9dc8-81fe2184fcbc.png)

Not sure about this.

**Comment by Alex-302** [comment]
Installed on VM, ads are blocked. But not everything is visible in the filtering log,
![image](https://user-images.githubusercontent.com/8361299/142876390-5a689438-3085-4549-adc6-de1f921e914e.png)
