### ISSUE TITLE
banner ad on Bundle app

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#99635]
@Titanposeidon commented on [Wed Nov 10 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4027)

On bundle app i see attached banner ad 
I am using Adguard nightly 4.0.65 on Android

![Screenshot_20211110-215750~2](https://user-images.githubusercontent.com/93843527/141189386-523fe664-2382-4138-a1a8-ed6b2377f75b.png)

---

@Birbber commented on [Thu Nov 11 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4027#issuecomment-966085024)

@Titanposeidon Hi! Could you give us the full package name of the application?

---

@Titanposeidon commented on [Thu Nov 11 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4027#issuecomment-966192378)

hello, here the marked area full package name , and other infos if there is any need
![IMG_20211111_115549](https://user-images.githubusercontent.com/93843527/141283685-c6ed043b-23e3-4d38-89d7-5da9b43f7f2d.jpg)

**Comment by Birbber** [comment]
We couldn't reproduce the issue on our end. Please check it up.
Looks like a location-based ad.

**Comment by Titanposeidon** [comment]
checked but seems not local ad, its im bundle app which on google  play store

**Comment by Alex-302** [comment]
Cannot be blocked inside app.
