### ISSUE TITLE
www.ajio.com

### ISSUE THREAD

**Issue by IThinkIAmCool** [AdguardTeam/AdguardFilters#99657]
**Issue URL (Ads/Annoyance)** : https://www.ajio.com/shop/men

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/87444998/141306382-d3ca11e2-4220-4539-aaa4-cf297e36b4e4.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
We don't block "go top" buttons
