### ISSUE TITLE
www.flipkart.com

### ISSUE THREAD

**Issue by IThinkIAmCool** [AdguardTeam/AdguardFilters#99658]
**Issue URL (Ads/Annoyance)** : https://www.flipkart.com/clothing-and-accessories/pr?sid=clo

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/87444998/141306503-54b5fb67-89c5-45a8-828e-10d257354434.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
What's wrong?
