### ISSUE TITLE
7r6.com (bypass)

### ISSUE THREAD

**Issue by FinderID** [AdguardTeam/AdguardFilters#99698]
shortlink
https://7r6.com/hq9dFk
https://cararegistrasi.com/F9QOwQbz2IJ
https://shrinke.me/GZxXW

can bypass the time/skip time?
https://didonlot.com/internet-download-manager/ (at download link)
https://download.id/ventoy/ (at download link)

thanks

**Comment by FinderID** [comment]
https://tutorial.siberuang.com/?article=cbf2b0b0

**Comment by Alex-302** [comment]
Too short.
