### ISSUE TITLE
Parallelspace (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#99710]
App
https://play.google.com/store/apps/details?id=com.lbe.parallel.intl

||aff-report.lbesecapi.com^
||aff-policy.lbesecapi.com^
||psi.lbesecapi.com^
||report-ps.meettech.net^
[Screenshot_20211112-135214083](https://user-images.githubusercontent.com/87330832/141411831-7393eb19-5f78-4e02-b802-bfb7ed159576.jpg)
[Screenshot_20211112-135410981](https://user-images.githubusercontent.com/87330832/141411876-e7f272e3-d3da-49e0-8a25-67b986b46aee.jpg)
[Screenshot_20211112-135258781](https://user-images.githubusercontent.com/87330832/141411886-722ac396-9bb4-4b95-ae4c-bd4378e4495f.jpg)
[Screenshot_20211112-135200779](https://user-images.githubusercontent.com/87330832/141411893-caf47ad7-bbdc-46b6-b237-5c1038eebf8c.jpg)

**Comment by Alex-302** [comment]
Why these domains must be blocked?

**Comment by SASUKE0721** [comment]
This is because we are sending log reports without permission.
