### ISSUE TITLE
Mo PTT - missed ad

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#9972]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Issue URL:
for iOS:
https://itunes.apple.com/tw/app/mo-ptt/id804745434?mt=8

for Android:
https://play.google.com/store/apps/details?id=mong.moptt&hl=zh_TW

— Missed Ad

Issue Type: Ads
Comment:
Screenshot: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YNQuvtQ.png)
</details><br/>

***Steps to reproduce the problem***:
In the past, we ever solved its ads.
https://github.com/AdguardTeam/AdguardFilters/issues/7593

But it recently updated the app.
It seems that it put ads under moptt.azurewebsites.net.
(The ads under moptt.azurewebsites.net doesn't frequently appear.
I tried to visit many boards on PTT.
Waste above 5 minutes, and then the ads appeared finally.)

However, moptt.azurewebsites.net has general data.
If blocking the whole moptt.azurewebsites.net, MoPTT's one feature will be abnormal.

Simply try its android version.
(In its iOS version, it also put ads under moptt.azurewebsites.net, but I didn't see ads if enabling AdGuard Pro protection on my iPhone.
Maybe Simplified domain names filter can block its ads in DNS-level.)

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PBYEDVW.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cK8FXDC.png)
</details><br/>

My Android OS is v8.0 (no root).
I worry that it maybe doesn't trust AdGuard HTTPS certificate.
Such like the issue:
https://github.com/AdguardTeam/AdguardFilters/issues/8000

May you check for what is under moptt.azurewebsites.net if your Android OS is v6.x?

Although I was unable to capture ads under moptt.azurewebsites.net in my filtering log, it seems that there will be no ad if I add the rule, ||moptt.azurewebsites.net$third-party, in the user filter.

May you also check if the rule, ||moptt.azurewebsites.net$third-party, is valid?
Or maybe you have a better rule.

Thanks a lot!

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | Android v8.0
Browser:                               | ?
AdGuard version:                       | AdGuard for Android v.2.10.176
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default/Blacklist mode)
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Off
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by lancelot-moon** [comment]
Well, I tested by myself.
||moptt.azurewebsites.net$third-party is useless.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/sGZGBdV.png)
</details><br/>

I tried to use "Parallel Space" app.
https://github.com/AdguardTeam/AdguardFilters/issues/8000#issuecomment-354857578

I need to observe for more time since the ad doesn't frequently appear.

**Comment by lancelot-moon** [comment]
@ameshkov 
@IvanIin 

I caught the HTTPS request via "Parallel Space" app.
It seems that "moptt.azurewebsites.net/api/pttboard/update" will call ad servers.

And then those ad servers were blocked by AdGuard as long as the Android device has root access for letting AdGuard HTTPS filtering resolve network traffic.

Without root access, ads appeared when "moptt.azurewebsites.net/api/pttboard/update" called ad servers since AdGuard HTTPS filtering couldn't resolve network traffic because AdGuard HTTPS certificate isn't trusted.

I don't know if my thought is correct.
May you check it?
Thanks.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PDqSpiD.png)
</details><br/>

**Comment by ameshkov** [comment]
The rule seems to be okay. does it really help and removes the ad?

**Comment by lancelot-moon** [comment]
1. The domain, moptt.azurewebsites.net, doesn't trust AdGuard certificate.
So AdGuard for Android is unable to resolve its ad requests from HTTPS filtering.

2. But it seems that it calls external ad servers.

3. Although we can't caught the ad requests under moptt.azurewebsites.net from HTTPS filtering, it seems that we can still block the ads in DNS-level due to the 2nd point.

4. With root access, the rule, "||moptt.azurewebsites.net/api/pttboard/update^", is unnecessary.
Those external ad servers are already in AdGuard filters.

5. Without root access, the rule, "||moptt.azurewebsites.net/api/pttboard/update^", is useless because it's not caught in filtering log.

6. For iOS users:
It seems that...
AdGuard Pro for iOS with AdGuard DNS server / AdGuard SDN filter can block the ads now.

For Android v7/v8 users without root access:
It seems that...
AdGuard for Android without DNS filtering can't block the ads now.
AdGuard for Android with DNS filtering can block the ads now.

However, the ads which are called by "moptt.azurewebsites.net/api/pttboard/update" don't frequently appear.
I am not sure very much.
Need luck to find them.
So it's maybe because I didn't find them during my test.

That's why I asked about the questions.
https://github.com/AdguardTeam/AdguardForiOS/issues/610

B/R

**Comment by lancelot-moon** [comment]
It seems that the skill of Mo PTT's designer isn't mature...

Although AdGuard for Android is unable to fully resolve its network traffic, ads which are called from that path rarely appear without DNS filtering.

And then I tried AdGuard for Android with DNS filtering for more than 10 minutes.

I got the same result with AdGuard Pro for iOS.
Only DNS filtering can block that kind of ads even if HTTPS filtering isn't fully trusted.

Do you have any thought?

**Comment by lancelot-moon** [comment]
@ameshkov 
@Revertron 

> We are aware of that delay. Unfortunately, this delay is for all the apps and we can not do any exception. At least for now. If we make this delay very short, some ads can slip through.

Generally, I use other port number or SSH for login into PTT BBS via mobile PTT BBS app.
It only takes 1~2 seconds.
The delay time is very short.
I reported that some ads could slip through AdGuard's HTTPS filtering and then appeared on Mo PTT in this issue.
But it seems that DNS filtering can block all ads on Mo PTT.
Is it possible due to the cause," too short delay time"?

B/R

**Comment by lancelot-moon** [comment]
@Alex-302
@BlazDT
@AdamWr 

https://www.robtex.com/dns-lookup/moptt.azurewebsites.net

Some Taiwanese netfriends reported that there are still ads in MoPTT for iOS even if we added those sub-domains in SDN filter.
https://github.com/AdguardTeam/AdguardFilters/issues/7593

But some features in MoPTT will be abnormal if blocking moptt.azurewebsites.net.
Moptt.azurewebsites.net is a CNAME to waws-prod-hk1-003.cloudapp.net.
Waws-prod-hk1-003.cloudapp.net has one IP number.
The IP number is 207.46.147.148.
The PTR of the IP number is waws-prod-hk1-003.cloudapp.net.
The IP number is in Hong Kong, Hong Kong. It is hosted by Microsoft.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/HlHNjOe.png)
</details><br/>

moptt.azurewebsites.net
-> waws-prod-hk1-003.vip.azurewebsites.windows.net
-> waws-prod-hk1-003.cloudapp.net

A Taiwanese netfriend reported:
If blocking waws-prod-hk1-003.cloudapp.net, there is no ad in MoPTT.
It seems that he enabled SSH connection in MoPTT setting.
I tested and reviewed the DNS Requests Log by myself.
The DNS requests were a little different when enabling BBS telnet connection or SSH connection for connecting to PTT BBS via MoPTT.

waws-prod-hk1-003.vip.azurewebsites.windows.net and waws-prod-hk1-003.cloudapp.net only appeared in DNS Requests Log when enabling SSH connection for connecting to PTT BBS via MoPTT.

If blocking waws-prod-hk1-003.vip.azurewebsites.windows.net, some features of MoPTT would also not work.

So I tried to only block waws-prod-hk1-003.cloudapp.net, which didn't affect MoPTT's features.
Can we block waws-prod-hk1-003.cloudapp.net instead of blocking moptt.azurewebsites.net?

B/R

**Comment by lancelot-moon** [comment]
@Alex-302

Please add **||graph.facebook.com$app=mong.moptt** in Mobile Ads filter.
This rules can block ads.

Thanks.

**Comment by Alex-302** [comment]
Does this app use Facebook authorization?

**Comment by lancelot-moon** [comment]
For old version of MoPTT, only DNS filtering (SDN filter works in the background) could block all ads in MoPTT.
(In the past, using other DNS changer app with AdGuard DNS server can block its ads in old version of MoPTT.
Now, ads appear in new version of MoPTT even if using AdGuard DNS server.)

For new version of MoPTT, only DNS filtering (SDN filter works in the background) already can't block all ads in MoPTT.
(I think it's because MoPTT started to use graph.facebook.com as one of ad sources.)

For new version of MoPTT, only DNS filtering (SDN filter works in the background) and **||graph.facebook.com$app=com.adguard.dns** in user filter can block all ads in MoPTT.

I tried to add that rule for DNS filtering.
The result is what I guess.

Since we can't block graph.facebook.com in DNS level, that's why I told you to add  ||graph.facebook.com$app=mong.moptt in Mobile Ads filter.

May you add it early??
Or @AdamWr, may you help this?
Thanks.

**Comment by Alex-302** [comment]
If this app uses Facebook authorization, we can't add the rule.

**Comment by lancelot-moon** [comment]
**It doesn't use Facebook authorization!**

AdGuard's Taiwanese users already found that AdGuard is unable to block some ads in MoPTT.
Please add **||graph.facebook.com$app=mong.moptt in Mobile Ads filter**.
And add these domains **both in Mobile Ads filter and SDN filter**.
**||tkcatwalk.aotter.net^
||tkmedia.aotter.net^
||tkmedia-cache.aotter.net^
||tkportal.aotter.net^**

This is an ad example.
https://tkcatwalk.aotter.net/popup/ca3f6696-144d-44db-86db-4fff2a4232d8

Thanks.

**Comment by Alex-302** [comment]
I can't just add these rules.
```
||tkcatwalk.aotter.net^
||tkmedia.aotter.net^
||tkmedia-cache.aotter.net^
||tkportal.aotter.net^
```
Could you please create test account?

**Comment by lancelot-moon** [comment]
Come to Skype.
I lend you PTT BBS account.
I already added some boards in favorite boards.

You need to casually visit boards for many times.
After adding ||graph.facebook.com$app=mong.moptt in Mobile Ads filter and enabling HTTPS & DNS filtering, the opportunity of ads have become lower.

But ads will appear in low opportunity when tkcatwalk.aotter.net, tkmedia-cache.aotter.net and tkportal.aotter.net appear in Filtering Log.

**Comment by Alex-302** [comment]
Ok, added
```
||tkcatwalk.aotter.net^
||tkmedia.aotter.net^
||tkmedia-cache.aotter.net^
||tkportal.aotter.net^
```
