### ISSUE TITLE
www.geektonight.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99736]
**Issue URL (Ads/Annoyance)** : `https://www.geektonight.com/computer-organization-and-architecture-notes/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141460215-8fe883e3-25ea-4a30-a419-1633286e0dea.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by spiri-leo** [comment]
Add this rule: `geektonight.com##a[href^="https://click.linksynergy.com/deeplink"]`
