### ISSUE TITLE
stackoverflow.blog

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99745]
**Issue URL (Ads/Annoyance)**:  `https://stackoverflow.blog/2010/08/18/new-image-upload-support/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141462226-9eb50eea-ead3-40b7-9a88-cc84fc7cf554.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
@chirag127
I can't reproduce this issue, is it still relevant?
