### ISSUE TITLE
coderedirect.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99747]
**Issue URL (Ads/Annoyance)**:  `https://coderedirect.com/questions/323364/using-imgur-api-v3-to-upload-images-anonymously-using-php`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141462435-8b4938f7-c782-4676-8c40-29b73414be90.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
already fixed
