### ISSUE TITLE
freecoursestock.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99758]
**Issue URL (Ads/Annoyance)**:  `http://freecoursestock.com/course/discrete-mathematics-for-computer-science-free-download`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141463932-4fec49c7-82e8-4851-ad64-f6a20c9f6869.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
