### ISSUE TITLE
www.javatpoint.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99752]
**Issue URL (Ads/Annoyance)**:  `https://www.javatpoint.com/discrete-mathematics-tutorial`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141463033-7d5321e5-7573-4ee8-ac46-a46ccb1ba4ec.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
It's on the footer.
