### ISSUE TITLE
www.login-faq.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99759]
**Issue URL (Ads/Annoyance)**:  `https://www.login-faq.com/freetutorials-us/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141464064-e3e10d7b-47f4-45e1-a383-72e5072e7f77.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
It's back to top button.
