### ISSUE TITLE
www.goeduhub.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99764]
**Issue URL (Ads/Annoyance)**:  `https://www.goeduhub.com/5162/ptu-previous-year-papers-discrete-mathematics-free-download?show=5411`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141464368-da18bfc5-6af2-4ab2-83d0-a19abec7d7e2.png)
![image](https://user-images.githubusercontent.com/76880977/141464367-3a95a4da-3248-4181-a514-86f73bfd16db.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
Not an ad and I think that it shouldn't be blocked.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/143423619-e2cbe59a-f01e-4160-a128-e47453e330e8.png)

</details>
