### ISSUE TITLE
www.credential.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99771]
**Issue URL (Ads/Annoyance)**:  `https://www.credential.net/97c055f7-7dfb-4c22-87a5-ff0a8a4ef3cc?username=royshavit335387`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141467381-d7914cf0-4868-458a-ab8e-c8d40eea2235.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
@chirag127 I got `404` error. Can you show the element with opened devtools?
