### ISSUE TITLE
freetutorialshub.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99782]
**Issue URL (Ads/Annoyance)**:  `https://freetutorialshub.com/r-programming-a-z-r-for-data-science-with-real-exercises-2/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141468508-c3f6d392-815b-4bda-a09d-27909c4c4005.png)
z

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
