### ISSUE TITLE
crunchadeal.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99785]
**Issue URL (Ads/Annoyance)**:  `https://crunchadeal.com/coupon/r-programming-a-z-r-for-data-science/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141468776-e749ed33-8dc9-4ab5-b66d-7bf34e60f16c.png)
z

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
