### ISSUE TITLE
blog.vilmatech.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99784]
**Issue URL (Ads/Annoyance)**:  `https://blog.vilmatech.com/95-off-r-programming-z-r-data-science-real-exercises-coupon/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141468754-b3244ed8-05c0-4e08-9aa4-79c21bca79ea.png)
z

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
2280 visitors/month
