### ISSUE TITLE
ai-summary.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99783]
**Issue URL (Ads/Annoyance)**:  `https://ai-summary.com/summary-r-programming-a-ztm-r-for-data-science-with-real-exercises/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141468693-92dd3cf1-bca5-4f89-a066-40c7b5583227.png)
z

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
7610 visitors/month
