### ISSUE TITLE
digitaldefynd.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99780]
**Issue URL (Ads/Annoyance)**:  `https://digitaldefynd.com/r-programming-courses-certifications-tutorial-training/`

<details><summary>Screenshots:</summary>

z

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
What's wrong?
