### ISSUE TITLE
courseforfree.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99793]
**Issue URL (Ads/Annoyance)**:  `https://courseforfree.net/power-of-quora-a-to-z-of-earning-from-quora-quora-ads-courseforfree/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141473566-4690f802-010c-4fbf-8f81-130b8c5f5657.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
