### ISSUE TITLE
raabta.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99796]
**Issue URL (Ads/Annoyance)**:  `https://raabta.net/how-to-download-udemy-courses-free/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141473729-75df69e8-7deb-46c1-9c3b-59da2d420ff3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
