### ISSUE TITLE
webcourses.us

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99799]
**Issue URL (Ads/Annoyance)**:  `https://webcourses.us/the-complete-dart-learning-guide-2021-edition-course-free-download/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141474409-69a465fa-728d-4fab-9aee-13a0978f53f1.png)

</details><br/>
![image](https://user-images.githubusercontent.com/76880977/141474409-69a465fa-728d-4fab-9aee-13a0978f53f1.png)

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
