### ISSUE TITLE
www.trendsduniya.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99797]
**Issue URL (Ads/Annoyance)**:  `https://www.trendsduniya.in/2018/12/best-chrome-extensions-hindi.html`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141473771-fcc44918-7ca4-4e61-b3f6-bc20a5bb809a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
