### ISSUE TITLE
freedownloadcourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99802]
**Issue URL (Ads/Annoyance)**:  `https://freedownloadcourse.com/python-for-data-science-and-machine-learning-bootcamp/`

<details><summary>Screenshots:</summary>

</details><br/>
![image](https://user-images.githubusercontent.com/76880977/141474595-9edcd54a-73f8-4228-b574-d6ba4263db6f.png)

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
