### ISSUE TITLE
www.resendz.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99800]
**Issue URL (Ads/Annoyance)**:  `https://www.resendz.com/6wYFVQZz8rUDP28`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141474471-588a195e-1db7-48cf-b5c7-28ba75cf695f.png)

</details><br/>
![image](https://user-images.githubusercontent.com/76880977/141474471-588a195e-1db7-48cf-b5c7-28ba75cf695f.png)

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
