### ISSUE TITLE
sarkarideals.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99803]
**Issue URL (Ads/Annoyance)**:  `https://sarkarideals.com/udemy-course-free-download/`

<details><summary>Screenshots:</summary>

</details><br/>
![image](https://user-images.githubusercontent.com/76880977/141474629-2bca12e5-b000-49df-877a-882bda75e5b9.png)

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
5330 visitors/month
