### ISSUE TITLE
freecoursesite.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99816]
**Issue URL (Ads/Annoyance)**:  `https://freecoursesite.uk/how-to-download/`

<details><summary>Screenshots:</summary>

</details><br/>
![image](https://user-images.githubusercontent.com/76880977/141477473-aca539c8-d6d0-46cb-8c97-6f668d9a8cd2.png)

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
4260 visitors/month
