### ISSUE TITLE
www.bizarena.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99828]
**Issue URL (Ads/Annoyance)**:  `https://www.bizarena.net/display.cfm?s=python&gsp=aFlKN1RKVEgxa2FpbW1kWDM0TE1ZSUJFVTRIZVUyS3pIS05uamcycTFIN0tETlJHNW4xdlF2alMyNW92Ym5scWJPaktTa2gyU3JCOE9OL0lxRVZRb2VuWVlUZUt0ZllhckRyUkNyQWQ1RTl1Z3hJWW16RjQ1UmN3MXhLT1hzeTYwTDhvbDRnVW9iTE5MZnFEdHY5d1FncTV6VXJPRkJBVDc2aXhGbytzM3hjcVFxQjMxcW5CQ0FsMlFycFRHeVpqZysrZytJMTVIK2NIYkFJL1hmcUtSL0lQcjJqYnlXU2YzTkk5RlM2ZGhsSDl1OGVvaGdUMEZ0V2dkNlQ3SkY2OUcyUFJRdnA5RkJJcHFieDlUcERQUFlialRIOGVsT1pGRkRwVTFibE5zSkY3TGNaL3hpc1hXTzV0Nmk3Q0lsNEY1b1ovSU9CS2U1bVFaTHV6S1h5Vnc5eGRNamZQVzBOeTJDS2ErK1YraTFRTEVYeXhmZ1hSTDVRUVJCdFQ0amMzanVTcjNqUzlZVHBEKzJFRUE3bzh5NEFxYVlWSTdLbDdsN0JENkhONDE1TUo5TzlRb2FDeU5vVy9tNjg2SkdYMWFrbHRZL1dmaUtSbTIvRDZsSmV0ci9uNXk4WVBoRldJR00wQjl3USthM0Q3dlRycG9vM3FIN2lBUTJjUndEMHhSWXJGdkJySVBhZkE1V1lMUytSRmM4MlgzSC8rOVcrbzh0TERrTjJqdHFMeUpldFRzeFloNUlWZFVHUmxCUGk1VWpyOGNvSk1qLzlvSnNhTit2OVduWURQcmlGeFFJZStQam9IbDdyWTFLUUJheG5MbTBDM1JkUVlTYkdpMzFHb0w1eUNsU01VSm1tYXJsYlRHSkl3aXc9PQ%253D%253D&_opnslfp=1`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141479279-e80ce559-5505-4428-8a31-bfd0f92744ee.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment]
On screenshot it looks like a parked domain and it seems that it doesn't work at the moment.
