### ISSUE TITLE
com.google.android.apps.docs

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#9983]
***Description***:
* **Current behaviour**: 

Loses connection when AdGuard is turned on. SSL FILTERING IS NOT ENABLED!

<details><summary>Screenshots:</summary>

![screenshot_2018-01-17-18-15-04](https://user-images.githubusercontent.com/33634917/35063258-405d220e-fbcf-11e7-9a49-012a043b865c.png)
![img_20180117_181257](https://user-images.githubusercontent.com/33634917/35063266-454a8996-fbcf-11e7-8e10-55d5a7319caa.jpg)
![screenshot_2018-01-17-18-11-12](https://user-images.githubusercontent.com/33634917/35063272-486d9ece-fbcf-11e7-96e0-541a25dde2f3.png)

</details><br/>

* **Expected behaviour**: 

Should work fine

***Steps to reproduce the problem***:

Open any file in Google Drive app with AdGuard enabled.

***System configuration***

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Russian filter", "Mobile Ads filter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 5.0.1
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-speed
HTTPS filtering (Android only):        | Off
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1726872

**Comment by Alex-302** [comment]
reproduced few times, but not now.
Please try to add `lh3.googleusercontent.com` to https exclusions.

**Comment by altokarev** [comment]
Cannot reproduce on 6, 8, 8.1 Android.

**Comment by Alex-302** [comment]
@akmLaVx

**Comment by zebrum** [comment]
added to https exclusions
