### ISSUE TITLE
tutsnode.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99836]
**Issue URL (Ads/Annoyance)**:  `https://tutsnode.net/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141479038-8387f12b-0dbc-4ec2-9acc-57d53d18764f.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Sergey-Lyapin** [comment]
10300 visitors/month
