### ISSUE TITLE
usersdrive.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99840]
**Issue URL (Annoyance)**:
https://usersdrive.com/o5x76ft0013r.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141483253-da78f16e-5005-4fbe-a113-fcbb976d27c4.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by zloyden** [comment]
They have a server-side check.
