### ISSUE TITLE
tute.io

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99924]
**Issue URL (Ads/Annoyance)**:  `https://tute.io/courses/master-google-sheets-and-see-why-its-better-than-excel`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141605166-b36f29d3-48f1-4f44-9268-813b72d7dd73.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by Sergey-Lyapin** [comment]
We don't block newsletters in footer.
