### ISSUE TITLE
codermohit.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99922]
**Issue URL (Ads/Annoyance)**:  `https://codermohit.com/udemy-paid-courses-google-drive-download-link/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141605025-a99aeefe-57f4-4240-820f-f743004f680d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
