### ISSUE TITLE
freedownloadcourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99923]
**Issue URL (Ads/Annoyance)**:  `https://freedownloadcourse.com/master-google-sheets-and-see-why-its-better-than-excel/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141605085-c89d1abd-f4e6-4c4e-9884-4beb453160f6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by Sergey-Lyapin** [comment]
5480 visitors/month
