### ISSUE TITLE
vanchiv.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99959]
**Issue URL (Ads/Annoyance)**:  `https://vanchiv.com/create-multiple-folders-at-once-in-windows-10/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141615415-e92465f7-e706-4be6-bb4d-5578a63da5c0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
