### ISSUE TITLE
adblock polska

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/AdguardFilters#9996]
this list is `abandoned`
pls. remove, thx : )

`! Last modified: 07 Nov 2014 22:20 UTC`
![2018-01-18-ustawienia adguard](https://user-images.githubusercontent.com/5884000/35078296-d935498e-fc01-11e7-9ca1-45cac2ded76d.png)
`https://github.com/adblockpolska/Adblock_PL_List/blob/master/adblock_polska.txt`

**Comment by ameshkov** [comment]
@vbagirov please mark it as "obsolete" in the new filters repo.

@KonoromiHimaries thank you! This mark I'm talking about will be visible in the future AdGuard version.

**Comment by vbagirov** [comment]
Done.

**Comment by KonoromiHimaries** [comment]
![2018-02-11-ustawienia adguard](https://user-images.githubusercontent.com/5884000/36069946-fd336d90-0ef1-11e8-97d9-edaf5a6b2697.png)

**Comment by vbagirov** [comment]
@KonoromiHimaries the filter is already marked as obsolete, but only in the json files on the server. We still need to update the extension to teach it to interpret this information properly (i.e. warn users that the filter is outdated).
