### ISSUE TITLE
www.indeed.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99986]
**Issue URL (Ads/Annoyance)**:  `https://www.indeed.com/career-advice/finding-a-job/in-demand-skills`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141647855-d634e1e7-f591-4ee1-a5ed-57e8e79c3810.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by AdamWr** [comment]
It's a shortcut for "Audio Description" so it shouldn't be blocked.
